unpackaged/main/default/objects/Media__c/Media__c.object-meta.xml
<CustomObject>
    <label>Media</label>
    <nameField>
        <displayFormat>M-{0000000}</displayFormat>
        <label>Agency Logo Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Media</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Media__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Denotes the account to which record is bind to</description>
    <inlineHelpText>Denotes the account to which record is bind to</inlineHelpText>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>Agency_Logo</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/classes/BatchTOUpdateAgencyLOGO_Test.cls
@isTest
public class BatchTOUpdateAgencyLOGO_Test {
@isTest
    public static void fetchRecords(){
         PGTestDataFactory_v2.initSetupData();    
        account acc = new account(name='Test');
        insert acc;
        list<Media__c> med = new list<Media__c>();
        for(Integer i=0;i<10;i++){
            med.add(new Media__c(IsActive__c=false,Account__c=acc.id,URL__c='https://res-1.cloudinary.com/crunchbase-production/image/upload/c_lpad,h_120,w_120,f_auto,b_white,q_auto:eco/affmaxcmuywiatu2qrjk'));
        }
        insert med;
        Test.setMock(HttpCalloutMock.class, new BatchTOUpdateAgencyLOGO_Mockclass());
        Test.startTest();
        Database.executeBatch(new BatchTOUpdateAgencyLOGO());
        Test.stopTest();
        system.assertEquals(acc.name,'Test','Name does not match');
    }
}