unpackaged/main/default/objects/Financial__c/Financial__c.object-meta.xml
<CustomObject>
    <description>Posting transactions from NetSuite including Cash Sales, Invoices, Customer Payments, Credit Memos, Cash Refunds, Journal Entries, etc.</description>
    <label>Financial</label>
    <nameField>
        <label>Transaction Id</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Financials</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Financial__c/fields/Document_Id__c.field-meta.xml
<CustomField>
    <fullName>Document_Id__c</fullName>
    <label>Document Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Financial__c/fields/NetSuite_Id__c.field-meta.xml
<CustomField>
    <fullName>NetSuite_Id__c</fullName>
    <externalId>true</externalId>
    <label>NetSuite Id</label>
    <length>25</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

unpackaged/main/default/objects/Financial__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Cash Sale</fullName>
            </value>
            <value>
                <fullName>Invoice</fullName>
            </value>
            <value>
                <fullName>Payment</fullName>
            </value>
            <value>
                <fullName>Credit Memo</fullName>
            </value>
            <value>
                <fullName>Cash Refund</fullName>
            </value>
            <value>
                <fullName>Customer Refund</fullName>
            </value>
            <value>
                <fullName>Customer Deposit</fullName>
            </value>
            <value>
                <fullName>Customer Payment</fullName>
                <isActive>false</isActive>
                <label>Customer Payment</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/classes/PGFinancial_Batch_Test.cls
@isTest
public class PGFinancial_Batch_Test {

    private static final String FAKE_RESPONSE_JSON = 'VGhpcyBpcyBhIFRlc3Q=';
    static testMethod void testDocumentSync() {
        Financial__c FinRec = new Financial__c();
        FinRec.NetSuite_Id__c = '3763639';
        FinRec.Type__c = 'Invoice';
        FinRec.Document_Id__c = '';
        FinRec.Name = 'TestTransaction';
       
        
        insert FinRec;
        Integer ctr = integer.valueof(label.PG_LABEL_BatchJob_TestCtr);
        DateTime dt = DateTime.now().addDays(ctr);
        system.debug(dt);
        test.setCreatedDate(FinRec.Id, dt);
        Test.setMock(HttpCalloutMock.class, new Mock());
        Test.StartTest();
        
		PGFinancial_BatchSchedulable schedulable = new PGFinancial_BatchSchedulable();
		String sch = '0 0 0 * * ? *';
		system.schedule('Test Schedule', sch, schedulable);
        Test.stopTest();
    }

    private class Mock implements HttpCalloutMock {

        public HTTPResponse respond(HTTPRequest req) {

            // You could assert the request content here

            HTTPResponse res = new HTTPResponse();
            res.setBody(FAKE_RESPONSE_JSON);
            res.setStatusCode(200);
            return res;
        }
    }

}