unpackaged/main/default/objects/Financial__c/Financial__c.object-meta.xml
<CustomObject>
    <description>Posting transactions from NetSuite including Cash Sales, Invoices, Customer Payments, Credit Memos, Cash Refunds, Journal Entries, etc.</description>
    <label>Financial</label>
    <nameField>
        <label>Transaction Id</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Financials</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Financial__c/fields/Document_Id__c.field-meta.xml
<CustomField>
    <fullName>Document_Id__c</fullName>
    <label>Document Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Financial__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Cash Sale</fullName>
            </value>
            <value>
                <fullName>Invoice</fullName>
            </value>
            <value>
                <fullName>Payment</fullName>
            </value>
            <value>
                <fullName>Credit Memo</fullName>
            </value>
            <value>
                <fullName>Cash Refund</fullName>
            </value>
            <value>
                <fullName>Customer Refund</fullName>
            </value>
            <value>
                <fullName>Customer Deposit</fullName>
            </value>
            <value>
                <fullName>Customer Payment</fullName>
                <isActive>false</isActive>
                <label>Customer Payment</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/classes/FinancialAPI.cls
@RestResource(urlMapping='/api/financial/*')
global class FinancialAPI {
    
    @HttpPost
    global static void Attachment(){
        string errorResponse = '' ;
        try{
            RestRequest req = RestContext.request;           
            String jsonInput= req.requestBody.toString();
            Map<String, Object> jsonMap = (Map<String, Object>) JSON.deserializeUntyped(jsonInput); 
            Id record = String.valueOf(jsonMap.get('record')) ;    
            String attachment_file = String.valueOf(jsonMap.get('attachment_file')) ;    
            
            if(record <> null){
                for (Financial__c row: [select id, Document_Id__c,Type__c,Name from Financial__c where id =:record]){
                    Document attach = new Document();
                    attach.ContentType = 'application/pdf';
                    attach.name = row.Type__c + '_' + row.Name + '.pdf';
                    attach.body = EncodingUtil.base64Decode(attachment_file);
                    attach.folderId = '00l7F0000011fcq';
                    insert attach;
                    if(attach.Id <> null){
                        System.debug('Document Id:' + attach.Id);
                        row.Document_Id__c = attach.Id;
                        update row;
                        RestContext.response.responseBody = Blob.valueOf('{"Status":"SUCCESS", "Id":"'+row.id+'", "Record":"'+row.Name+'", "AttachmentId":"'+attach.Id+'"}');
                    }
                    else{
                        RestContext.response.responseBody = Blob.valueOf('{"Status":"FAILED""}');
                    }
                }
            }
        }
        catch(Exception e) {
            errorResponse =  e.getMessage();
            system.debug(errorResponse);
        }
    }
}