unpackaged/main/default/objects/Financial__c/Financial__c.object-meta.xml
<CustomObject>
    <description>Posting transactions from NetSuite including Cash Sales, Invoices, Customer Payments, Credit Memos, Cash Refunds, Journal Entries, etc.</description>
    <label>Financial</label>
    <nameField>
        <label>Transaction Id</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Financials</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Financial__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>Financials</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Financial__c/fields/Actuals__c.field-meta.xml
<CustomField>
    <fullName>Actuals__c</fullName>
    <description>This field is to reflect a negative value for &#39;Credit Memo&#39; type Financials.</description>
    <formula>IF(ISPICKVAL( Type__c , &quot;Credit Memo&quot;), (Subtotal__c * (-1)), Subtotal__c )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Actuals</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

unpackaged/main/default/objects/Financial__c/fields/Applied__c.field-meta.xml
<CustomField>
    <fullName>Applied__c</fullName>
    <label>Applied</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

unpackaged/main/default/objects/Financial__c/fields/Currency__c.field-meta.xml
<CustomField>
    <fullName>Currency__c</fullName>
    <label>Currency</label>
    <length>25</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Financial__c/fields/Discount_Total__c.field-meta.xml
<CustomField>
    <fullName>Discount_Total__c</fullName>
    <label>Discount Total</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

unpackaged/main/default/objects/Financial__c/fields/Document_Id__c.field-meta.xml
<CustomField>
    <fullName>Document_Id__c</fullName>
    <label>Document Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Financial__c/fields/Memo__c.field-meta.xml
<CustomField>
    <fullName>Memo__c</fullName>
    <label>Memo</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

unpackaged/main/default/objects/Financial__c/fields/NetSuite_Id__c.field-meta.xml
<CustomField>
    <fullName>NetSuite_Id__c</fullName>
    <externalId>true</externalId>
    <label>NetSuite Id</label>
    <length>25</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

unpackaged/main/default/objects/Financial__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipName>Financials</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Financial__c/fields/Opty_Owner_Email__c.field-meta.xml
<CustomField>
    <fullName>Opty_Owner_Email__c</fullName>
    <label>Opty Owner Email</label>
    <type>Email</type>
</CustomField>

unpackaged/main/default/objects/Financial__c/fields/Shipping_Total__c.field-meta.xml
<CustomField>
    <fullName>Shipping_Total__c</fullName>
    <label>Shipping Total</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

unpackaged/main/default/objects/Financial__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <length>75</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Financial__c/fields/Subtotal__c.field-meta.xml
<CustomField>
    <fullName>Subtotal__c</fullName>
    <description>Transaction subtotal before any discounts, shipping cost, handling cost or tax.</description>
    <label>Subtotal</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

unpackaged/main/default/objects/Financial__c/fields/Terms__c.field-meta.xml
<CustomField>
    <fullName>Terms__c</fullName>
    <label>Terms</label>
    <length>25</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Financial__c/fields/Total__c.field-meta.xml
<CustomField>
    <fullName>Total__c</fullName>
    <label>Total</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

unpackaged/main/default/objects/Financial__c/fields/Transaction_Date__c.field-meta.xml
<CustomField>
    <fullName>Transaction_Date__c</fullName>
    <description>Date of transaction in NetSuite.</description>
    <label>Transaction Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/Financial__c/fields/Transaction_subtotal_before_any_discount__c.field-meta.xml
<CustomField>
    <fullName>Transaction_subtotal_before_any_discount__c</fullName>
    <label>Tax Total</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

unpackaged/main/default/objects/Financial__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Cash Sale</fullName>
            </value>
            <value>
                <fullName>Invoice</fullName>
            </value>
            <value>
                <fullName>Payment</fullName>
            </value>
            <value>
                <fullName>Credit Memo</fullName>
            </value>
            <value>
                <fullName>Cash Refund</fullName>
            </value>
            <value>
                <fullName>Customer Refund</fullName>
            </value>
            <value>
                <fullName>Customer Deposit</fullName>
            </value>
            <value>
                <fullName>Customer Payment</fullName>
                <isActive>false</isActive>
                <label>Customer Payment</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Financial__c/fields/Unapplied__c.field-meta.xml
<CustomField>
    <fullName>Unapplied__c</fullName>
    <label>Unapplied</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

unpackaged/main/default/objects/Financial__c/fields/Upload_Tag__c.field-meta.xml
<CustomField>
    <fullName>Upload_Tag__c</fullName>
    <label>Upload Tag</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/classes/PGCeligoFinancialUpdateDF.cls
global  class PGCeligoFinancialUpdateDF implements Database.batchable<Sobject> {
    
    global Database.QueryLocator start(Database.BatchableContext bc)
    {
        String s='SELECT Id,netsuite_conn__Account__c,Actuals__c,netsuite_conn__Applied__c,netsuite_conn__Currency__c,netsuite_conn__Discount_Total__c,netsuite_conn__Document_Id__c, netsuite_conn__Due_Date__c,netsuite_conn__Memo__c,netsuite_conn__NetSuite_Id__c,netsuite_conn__Opportunity__c,Opty_Owner_Email__c,netsuite_conn__PDF_File__c,netsuite_conn__Shipping_Total__c,netsuite_conn__Status__c,netsuite_conn__Subtotal__c,netsuite_conn__Tax_Total__c, netsuite_conn__Terms__c,netsuite_conn__Total__c,netsuite_conn__Transaction_Date__c, netsuite_conn__Type__c,netsuite_conn__Unapplied__c,Upload_Tag__c from netsuite_conn__NetSuite_Financial__c ';
        return Database.getQueryLocator(s);
        
    }
    global void execute(Database.BatchableContext bc, List<netsuite_conn__NetSuite_Financial__c> FinancialList )
        
    {
        System.debug('@@@'+ FinancialList);
        list<Financial__c> newFinancial = new list<Financial__c>();
        for( netsuite_conn__NetSuite_Financial__c fin : FinancialList) {
            newFinancial.add(new Financial__c(
                
                Account__c = fin.netsuite_conn__Account__c,
                Applied__c = fin.netsuite_conn__Applied__c,
                Currency__c = fin.netsuite_conn__Currency__c,
                Discount_Total__c = fin.netsuite_conn__Discount_Total__c,
                Document_Id__c = fin.netsuite_conn__Document_Id__c,
                Due_Date__c = fin.netsuite_conn__Due_Date__c,
                Memo__c = fin.netsuite_conn__Memo__c,
                NetSuite_Id__c= fin.netsuite_conn__NetSuite_Id__c,
                Opportunity__c = fin.netsuite_conn__Opportunity__c ,
                Opty_Owner_Email__c = fin.Opty_Owner_Email__c,
                Shipping_Total__c = fin.netsuite_conn__Shipping_Total__c,
                Status__c= fin.netsuite_conn__Status__c,
                Subtotal__c = fin.netsuite_conn__Subtotal__c,
                Transaction_subtotal_before_any_discount__c  = fin.netsuite_conn__Tax_Total__c,
                Terms__c = fin.netsuite_conn__Terms__c,
                Total__c = fin.netsuite_conn__Total__c,
                Transaction_Date__c= fin.netsuite_conn__Transaction_Date__c,
                Type__c = fin.netsuite_conn__Type__c,
                Unapplied__c = fin.netsuite_conn__Unapplied__c,
                Upload_Tag__c = fin.Upload_Tag__c));
        }
        
        
        database.insert(newFinancial,false);
       
    }
    global void finish(Database.BatchableContext bc)
    {
        
    }
    
}