unpackaged/main/default/objects/Campaign/fields/Campaign_End_DateTime__c.field-meta.xml
<CustomField>
    <fullName>Campaign_End_DateTime__c</fullName>
    <description>Stores End Date Time of campaign.</description>
    <label>Campaign End DateTime</label>
    <type>DateTime</type>
</CustomField>

unpackaged/main/default/objects/Campaign/fields/Campaign_Start_DateTime__c.field-meta.xml
<CustomField>
    <fullName>Campaign_Start_DateTime__c</fullName>
    <description>Stores Start Date Time of campaign.</description>
    <label>Campaign Start DateTime</label>
    <type>DateTime</type>
</CustomField>

unpackaged/main/default/objects/Campaign/fields/Country__c.field-meta.xml
<CustomField>
    <fullName>Country__c</fullName>
    <description>Denotes the country of campaign members and is synonymous with currency field</description>
    <inlineHelpText>Denotes the country of campaign members and is synonymous with currency field</inlineHelpText>
    <label>Country</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Country</valueSetName>
    </valueSet>
</CustomField>

unpackaged/main/default/classes/Test_ActiveInactiveCampController.cls
@isTest
public class Test_ActiveInactiveCampController {

    public static testmethod void getCampInfoTest(){
        
        Campaign cma = new Campaign();
        cma.Name = 'TestNameCampaign';
        cma.Country__c = 'Singapore';
        cma.IsActive = true;
        cma.StartDate = system.today();
        cma.EndDate = system.today().addDays(+1);
        cma.Campaign_Start_DateTime__c = system.now();
        cma.Campaign_End_DateTime__c = system.now().addDays(+1);
        cma.RecordTypeId = Schema.SObjectType.Campaign.getRecordTypeInfosByName().get('Marketing Promo').getRecordTypeId();
        insert cma;
        
        Campaign camp = new Campaign();
        camp.Name = 'TestNameCampaign';
        camp.Country__c = 'Singapore';
        camp.IsActive = false;
        camp.StartDate = system.today().addDays(+1);
        camp.EndDate = system.today().addDays(+2);
        camp.Campaign_Start_DateTime__c = system.now().addDays(+1);
        camp.Campaign_End_DateTime__c = system.now().addDays(+2);
        camp.RecordTypeId = Schema.SObjectType.Campaign.getRecordTypeInfosByName().get('Marketing Promo').getRecordTypeId();
        insert camp;
        
        Test.startTest();
        ActiveInactiveCampController.getCampInfo(cma.Id);
        ActiveInactiveCampController.getCampInfo(camp.Id);
        ActiveInactiveCampController.getResponse(JSON.serialize(cma));
        ActiveInactiveCampController.getResponse(JSON.serialize(camp));
        Test.stopTest();
    }
}