unpackaged/main/default/objects/Campaign/fields/Campaign_End_DateTime__c.field-meta.xml
<CustomField>
    <fullName>Campaign_End_DateTime__c</fullName>
    <description>Stores End Date Time of campaign.</description>
    <label>Campaign End DateTime</label>
    <type>DateTime</type>
</CustomField>

unpackaged/main/default/objects/Campaign/fields/Campaign_Start_DateTime__c.field-meta.xml
<CustomField>
    <fullName>Campaign_Start_DateTime__c</fullName>
    <description>Stores Start Date Time of campaign.</description>
    <label>Campaign Start DateTime</label>
    <type>DateTime</type>
</CustomField>

unpackaged/main/default/objects/Campaign/fields/Country__c.field-meta.xml
<CustomField>
    <fullName>Country__c</fullName>
    <description>Denotes the country of campaign members and is synonymous with currency field</description>
    <inlineHelpText>Denotes the country of campaign members and is synonymous with currency field</inlineHelpText>
    <label>Country</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Country</valueSetName>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Campaign/fields/Source_Campaign_Reference__c.field-meta.xml
<CustomField>
    <fullName>Source_Campaign_Reference__c</fullName>
    <description>Reference of campaign in external system eg: CMS</description>
    <inlineHelpText>Reference of campaign in external system eg: CMS</inlineHelpText>
    <label>Source Campaign Reference</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Campaign/recordTypes/Marketing_Promo.recordType-meta.xml
<RecordType>
    <fullName>Marketing_Promo</fullName>
    <active>true</active>
    <label>Marketing Promo</label>
</RecordType>

unpackaged/main/default/objects/Trigger_Execute__c/Trigger_Execute__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>Trigger Execute</label>
</CustomObject>

unpackaged/main/default/objects/Trigger_Execute__c/fields/Enable_del__c.field-meta.xml
<CustomField>
    <fullName>Enable_del__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Enable del</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/classes/Test_PGCampMemberTrigger.cls
@isTest
public class Test_PGCampMemberTrigger {

    public static testmethod void credValidationTest(){
        
        Trigger_Execute__c TE = new Trigger_Execute__c();
        TE.Name = 'PGCampMemberTrigger';
        TE.Enable_del__c = true;
        insert TE;
        
        List<CampaignMember> campMemberList = new List<CampaignMember>();
        Campaign camp = new Campaign();
        camp.Name = 'TestCampaign';
        camp.IsActive = true;
        camp.Country__c = 'Singapore';
        camp.CurrencyIsoCode = 'SGD';
        camp.Source_Campaign_Reference__c='camp1';
        camp.RecordTypeId =Schema.SObjectType.Campaign.getRecordTypeInfosByDeveloperName().get('Marketing_Promo').getRecordTypeId();
        camp.StartDate = system.today();
        camp.Campaign_Start_DateTime__c = system.now();
        camp.Campaign_End_DateTime__c = system.now().addDays(+1);
        camp.EndDate = system.today().addDays(+1);
        insert camp;
        
        Contact con = new Contact();
        con.FirstName = 'TestFName';
        con.LastName = 'TestLName';
        con.Email = 'test@mail.com'; 
        insert con;
      
        CampaignMember campMember = new CampaignMember();
        campMember.ContactId = con.Id;
        campMember.Status = 'Eligible';
        campMember.CampaignId = camp.Id;
        campMemberList.add(campMember);
        insert campMemberList;
        
        Test.startTest();
        PGCampMemberTriggerHandler.credValidation(campMemberList);
        update campMemberList;        
        PGCampMemberTriggerHandler.credValidation(campMemberList);
        delete campMemberList;
        PGCampMemberTriggerHandler.credValidation(campMemberList);
        Test.stopTest();
    }
}