unpackaged/main/default/objects/Campaign/fields/Campaign_End_DateTime__c.field-meta.xml
<CustomField>
    <fullName>Campaign_End_DateTime__c</fullName>
    <description>Stores End Date Time of campaign.</description>
    <label>Campaign End DateTime</label>
    <type>DateTime</type>
</CustomField>

unpackaged/main/default/objects/Campaign/fields/Campaign_Start_DateTime__c.field-meta.xml
<CustomField>
    <fullName>Campaign_Start_DateTime__c</fullName>
    <description>Stores Start Date Time of campaign.</description>
    <label>Campaign Start DateTime</label>
    <type>DateTime</type>
</CustomField>

unpackaged/main/default/objects/Campaign/fields/Country__c.field-meta.xml
<CustomField>
    <fullName>Country__c</fullName>
    <description>Denotes the country of campaign members and is synonymous with currency field</description>
    <inlineHelpText>Denotes the country of campaign members and is synonymous with currency field</inlineHelpText>
    <label>Country</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Country</valueSetName>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Campaign/fields/Source_Campaign_Reference__c.field-meta.xml
<CustomField>
    <fullName>Source_Campaign_Reference__c</fullName>
    <description>Reference of campaign in external system eg: CMS</description>
    <inlineHelpText>Reference of campaign in external system eg: CMS</inlineHelpText>
    <label>Source Campaign Reference</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Campaign/recordTypes/Marketing_Promo.recordType-meta.xml
<RecordType>
    <fullName>Marketing_Promo</fullName>
    <active>true</active>
    <label>Marketing Promo</label>
</RecordType>

unpackaged/main/default/objects/Campaign_Eligibility__c/Campaign_Eligibility__c.object-meta.xml
<CustomObject>
    <label>Campaign Eligibility</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Campaign Eligibilities</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Campaign_Eligibility__c/fields/Campaign__c.field-meta.xml
<CustomField>
    <fullName>Campaign__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Denotes the campaign for which campaign eligibility is created</description>
    <inlineHelpText>Denotes Campaign for which campaign eligibility is created</inlineHelpText>
    <label>Campaign</label>
    <referenceTo>Campaign</referenceTo>
    <relationshipLabel>Campaign Eligibilities</relationshipLabel>
    <relationshipName>Campaign_Eligibilities</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Promo_Mechanic__c/Promo_Mechanic__c.object-meta.xml
<CustomObject>
    <label>Promo Mechanic</label>
    <nameField>
        <label>Promo Mechanic Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Promo Mechanic</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Promo_Mechanic__c/fields/Campaign_Eligibility__c.field-meta.xml
<CustomField>
    <fullName>Campaign_Eligibility__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Denotes the related Campaign Eligibility Record</description>
    <inlineHelpText>Denotes the related Campaign Eligibility Record</inlineHelpText>
    <label>Campaign Eligibility</label>
    <referenceTo>Campaign_Eligibility__c</referenceTo>
    <relationshipLabel>Promo Mechanic</relationshipLabel>
    <relationshipName>Promo_Mechanic</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Trigger_Execute__c/Trigger_Execute__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>Trigger Execute</label>
</CustomObject>

unpackaged/main/default/objects/Trigger_Execute__c/fields/Enable_del__c.field-meta.xml
<CustomField>
    <fullName>Enable_del__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Enable del</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/classes/Test_PGPromoMechanicHandler.cls
@isTest
public class Test_PGPromoMechanicHandler {

    public static testmethod void checkCREDTest() {
        
        Trigger_Execute__c TE = new Trigger_Execute__c();
        TE.Name = 'PGCampaignEligibilityTrigger';
        TE.Enable_del__c = true;
        insert TE;
        
        Trigger_Execute__c TEPromoMech = new Trigger_Execute__c();
        TEPromoMech.Name = 'PGPromoMechanicTrigger';
        TEPromoMech.Enable_del__c = true;
        insert TEPromoMech;
        
        Map<Id,Campaign> mapOfCampIdVsCamp = new Map<Id,Campaign>();
        List<Campaign> campList = new List<Campaign>();
        Campaign camp = new Campaign();
        camp.Name = 'TestCampaign';
        camp.IsActive = false;
        camp.Country__c = 'Singapore';
        camp.CurrencyIsoCode = 'SGD';
        camp.Source_Campaign_Reference__c='camp1';
        camp.RecordTypeId =Schema.SObjectType.Campaign.getRecordTypeInfosByDeveloperName().get('Marketing_Promo').getRecordTypeId();
        camp.StartDate = system.today();
        camp.Campaign_Start_DateTime__c = system.now();
        camp.Campaign_End_DateTime__c = system.now().addDays(+1);
        camp.EndDate = system.today().addDays(+1);
        insert camp;
        mapOfCampIdVsCamp.put(camp.Id,camp);

        Campaign_Eligibility__c campElig = new Campaign_Eligibility__c();
        campElig.Name = 'Test Elig';
        campElig.CurrencyIsoCode ='SGD';
        campElig.Campaign__c =camp.Id ;
        insert campElig;
        
        Test.startTest();
        camp.IsActive = true;
        update camp;
        
        Promo_Mechanic__c promoMech = new Promo_Mechanic__c();
        promoMech.Name = 'Test PM';
        promoMech.CurrencyIsoCode ='SGD';
        promoMech.Campaign_Eligibility__c =campElig.Id ;
        insert promoMech;
        update promoMech; 
        
        Test.stopTest();
    }
}