unpackaged/main/default/objects/Campaign/fields/Country__c.field-meta.xml
<CustomField>
    <fullName>Country__c</fullName>
    <description>Denotes the country of campaign members and is synonymous with currency field</description>
    <inlineHelpText>Denotes the country of campaign members and is synonymous with currency field</inlineHelpText>
    <label>Country</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Country</valueSetName>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Campaign_Eligibility__c/Campaign_Eligibility__c.object-meta.xml
<CustomObject>
    <label>Campaign Eligibility</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Campaign Eligibilities</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Campaign_Eligibility__c/fields/Campaign__c.field-meta.xml
<CustomField>
    <fullName>Campaign__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Denotes the campaign for which campaign eligibility is created</description>
    <inlineHelpText>Denotes Campaign for which campaign eligibility is created</inlineHelpText>
    <label>Campaign</label>
    <referenceTo>Campaign</referenceTo>
    <relationshipLabel>Campaign Eligibilities</relationshipLabel>
    <relationshipName>Campaign_Eligibilities</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Campaign_Eligibility__c/fields/Criteria_Type__c.field-meta.xml
<CustomField>
    <fullName>Criteria_Type__c</fullName>
    <description>Denotes the type of entry of criteria</description>
    <inlineHelpText>Denotes the type of entry of criteria</inlineHelpText>
    <label>Criteria Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>SOQL</fullName>
            </value>
            <value>
                <fullName>Apex Method</fullName>
            </value>
            <value>
                <fullName>Custom Metadata</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Campaign_Eligibility__c/fields/Priority__c.field-meta.xml
<CustomField>
    <fullName>Priority__c</fullName>
    <description>Denotes the order in which the campaign eligibility rules are processed by Campaign Rule Engine. This is useful when there are multiple/dependant rules in execution</description>
    <inlineHelpText>Denotes the order in which the campaign eligibility rules are processed by Campaign Rule Engine. This is useful when there are multiple/dependant rules in execution</inlineHelpText>
    <label>Priority</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/Campaign_Eligibility__c/fields/Rule_Name_Extension__c.field-meta.xml
<CustomField>
    <fullName>Rule_Name_Extension__c</fullName>
    <description>To accommodate longer SOQL queries (&gt;255 char) when Criteria Type is &#39;SOQL&#39;</description>
    <inlineHelpText>To accommodate longer SOQL queries (&gt;255 char) when Criteria Type is &#39;SOQL&#39;</inlineHelpText>
    <label>Rule Name Extension</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

unpackaged/main/default/objects/Campaign_Eligibility__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>Denotes whether the rule is active or inactive</description>
    <inlineHelpText>Denotes whether the rule is active or inactive</inlineHelpText>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Trigger_Execute__c/Trigger_Execute__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>Trigger Execute</label>
</CustomObject>

unpackaged/main/default/objects/Trigger_Execute__c/fields/Enable_del__c.field-meta.xml
<CustomField>
    <fullName>Enable_del__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Enable del</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/classes/CampaignMemberOperationsBatch_Test.cls
@isTest
public class CampaignMemberOperationsBatch_Test {
    
    
    @isTest
    static void CampaignMemberOperationsMethod(){
        
        Trigger_Execute__c TE = new Trigger_Execute__c();
        TE.Name = 'PGCampaignEligibilityTrigger';
        TE.Enable_del__c = true;
        insert TE;
        
        Trigger_Execute__c TECM = new Trigger_Execute__c();
        TECM.Name = 'PGCampMemberTrigger';
        TECM.Enable_del__c = true;
        insert TECM;
        
        Campaign cma = new Campaign();
        cma.Name = 'TestNameCampaign';
        cma.Country__c = 'Singapore';  
        cma.IsActive = true;
        insert cma;
        
        Contact con = new Contact();
        con.FirstName = 'TestFName';
        con.LastName = 'testLname';
        con.Email = 'test@nmail.com'; 
        insert con;
        
        Lead ld = new Lead();
        ld.LastName = 'ldName';
        ld.Company = 'testCompany';
        insert ld;
        
        CampaignMember cmp = new CampaignMember();
        cmp.ContactId = con.Id;
        cmp.Status = 'Revoked';
        cmp.CampaignId = cma.Id;
        
        insert cmp;
        system.debug('>>>>'+cmp.Status);
        
        Campaign_Eligibility__c ce1 = new Campaign_Eligibility__c(Name='test1',Rule_Name_Extension__c='Select Id From Contact',Criteria_Type__c = 'SOQL',Priority__c=1,Campaign__c=cma.Id,Status__c='Active');     
        insert ce1;
        
        Map<id,list<Contact>> idVsListOfObjectMap = new Map<id,list<Contact>>();
        idVsListOfObjectMap.put(ce1.Id,[select Id,Name from Contact]);
        Test.startTest();
        DataBase.executeBatch(new CampaignMemberOperationsBatch(idVsListOfObjectMap),1);
        Test.stopTest();
        
    }
    @isTest
    static void CampaignMemberOperationsMethod1(){
        
        Trigger_Execute__c TE = new Trigger_Execute__c();
        TE.Name = 'PGCampaignEligibilityTrigger';
        TE.Enable_del__c = true;
        insert TE;
        
        Trigger_Execute__c TECM = new Trigger_Execute__c();
        TECM.Name = 'PGCampMemberTrigger';
        TECM.Enable_del__c = true;
        insert TECM;
        
        Campaign cma = new Campaign();
        cma.Name = 'TestNameCampaign';
        cma.Country__c = 'Singapore';
        cma.IsActive = true;
        insert cma;
        
        Contact con = new Contact();
        con.FirstName = 'TestFName';
        con.LastName = 'testLname';
        con.Email = 'test@nmail.com';
        insert con;
        
        Lead ld = new Lead();
        ld.LastName = 'ldName';
        ld.Company = 'testCompany';
        insert ld;
        
        CampaignMember cmp = new CampaignMember();
        cmp.LeadId = ld.Id;
        cmp.Status = 'Eligible';
        cmp.CampaignId = cma.Id;
        insert cmp;
        system.debug('>>>>'+cmp.Status);
        
        Campaign_Eligibility__c ce2 = new Campaign_Eligibility__c(Name='test2',Rule_Name_Extension__c='DynamicMethodCall;multiplyNumbers',Criteria_Type__c = 'Apex Method',Priority__c=2,Campaign__c=cma.Id,Status__c='Active');     
        insert ce2;
        
        Map<id,list<Lead>> idVsListOfObjectMap = new Map<id,list<Lead>>();
        idVsListOfObjectMap.put(ce2.Id,[select Id,Name from Lead]);
        Test.startTest();
        //CampaignMemberOper_BatchSchedulable objcls=new CampaignMemberOper_BatchSchedulable();
        //SchedulableContext SC;
        //objcls.execute(SC);
        DataBase.executeBatch(new CampaignMemberOperationsBatch(idVsListOfObjectMap));
        Test.stopTest();
        
    }
    
}