unpackaged/main/default/objects/Campaign/fields/Event_Type__c.field-meta.xml
<CustomField>
    <fullName>Event_Type__c</fullName>
    <description>Denotes type of event based campaigns</description>
    <inlineHelpText>Denotes type of event based campaigns</inlineHelpText>
    <label>Event Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Networking</fullName>
            </value>
            <value>
                <fullName>Festival</fullName>
            </value>
            <value>
                <fullName>Association</fullName>
            </value>
            <value>
                <fullName>Others</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Campaign/fields/PG_Campaign_Id__c.field-meta.xml
<CustomField>
    <fullName>PG_Campaign_Id__c</fullName>
    <label>PG Campaign Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Campaign/recordTypes/Renewal.recordType-meta.xml
<RecordType>
    <fullName>Renewal</fullName>
    <active>true</active>
    <label>Renewal</label>
</RecordType>

unpackaged/main/default/objects/Campaign_Eligibility__c/Campaign_Eligibility__c.object-meta.xml
<CustomObject>
    <label>Campaign Eligibility</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Campaign Eligibilities</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Campaign_Eligibility__c/fields/Campaign__c.field-meta.xml
<CustomField>
    <fullName>Campaign__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Denotes the campaign for which campaign eligibility is created</description>
    <inlineHelpText>Denotes Campaign for which campaign eligibility is created</inlineHelpText>
    <label>Campaign</label>
    <referenceTo>Campaign</referenceTo>
    <relationshipLabel>Campaign Eligibilities</relationshipLabel>
    <relationshipName>Campaign_Eligibilities</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/CampaignMember/fields/Needs_to_Sync__c.field-meta.xml
<CustomField>
    <fullName>Needs_to_Sync__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Value to update for self serve campaign for identifier for workato</description>
    <label>Needs to Sync</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Lead/recordTypes/B2B.recordType-meta.xml
<RecordType>
    <fullName>B2B</fullName>
    <active>true</active>
    <businessProcess>B2B Lead Process</businessProcess>
    <description>Will convert to Business Account</description>
    <label>B2B</label>
</RecordType>

unpackaged/main/default/objects/RSS_discount_campaign_event__e/RSS_discount_campaign_event__e.object-meta.xml
<CustomObject>
    <label>RSS discount campaign event</label>
    <pluralLabel>RSS discount campaign events</pluralLabel>
</CustomObject>

unpackaged/main/default/objects/RSS_discount_campaign_event__e/fields/campaign_ID__c.field-meta.xml
<CustomField>
    <fullName>campaign_ID__c</fullName>
    <label>campaign ID</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/RSS_discount_campaign_event__e/fields/event_type__c.field-meta.xml
<CustomField>
    <fullName>event_type__c</fullName>
    <label>event type</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Self_Serve_Campaign_Notification__e/Self_Serve_Campaign_Notification__e.object-meta.xml
<CustomObject>
    <description>Used to send the event to workato on the finish of the campaign member creation,</description>
    <label>Self Serve Campaign Notification</label>
    <pluralLabel>Self Serve Campaign Notification</pluralLabel>
</CustomObject>

unpackaged/main/default/objects/Self_Serve_Campaign_Notification__e/fields/PG_Campaign_Id__c.field-meta.xml
<CustomField>
    <fullName>PG_Campaign_Id__c</fullName>
    <description>PG Campaign Id of the related campaign.</description>
    <label>PG Campaign Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Self_Serve_Campaign_Notification__e/fields/SF_Campaign_Id__c.field-meta.xml
<CustomField>
    <fullName>SF_Campaign_Id__c</fullName>
    <description>Consist of Campaign 18digit Id</description>
    <label>SF Campaign Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/classes/CMInsertCRE.cls
/*
 * TestClass : CMInsertCRE_Test
 */
public class CMInsertCRE implements DataBase.Batchable<String>,Database.stateful,Database.AllowsCallouts{
    
    public class Payload {
        String text;
    }
    public String campaignId;
    //public map<id,list<sObject>> idVsListOfObjectMap;
    public Id scope;
    public list<String> oldLeadVsContactId = new list<String>(); 
    public Database.SaveResult[] allInsertList ;    
    public list<Id> conLeadIds;
    List<Self_Serve_Campaign_Notification__e> listSSNotification = new List<Self_Serve_Campaign_Notification__e>();    
  List<RSS_discount_campaign_event__e > listRSSNotification = new List<RSS_discount_campaign_event__e >();    
    public CMInsertCRE(){ 
        
    }
    public CMInsertCRE(Id scope,Set<String> oldLeadVsContactId){ 
        
        this.scope = scope;
        this.oldLeadVsContactId.addAll(oldLeadVsContactId);
        allInsertList = new list<Database.SaveResult>();
        conLeadIds = new list<id>();
    }
    
    public Iterable<String> start(DataBase.BatchableContext bc){
        
        return oldLeadVsContactId;
    }
    
    public void execute(DataBase.BatchableContext bc,List<String> oldLeadVsContactId2){
        PGCampMemberTriggerHandler.Bypass = true;
        Campaign_Eligibility__c camp = [
            SELECT Id, Campaign__c, Campaign__r.RecordType.Name, Campaign__r.PG_Campaign_Id__c
            FROM Campaign_Eligibility__c 
            WHERE Id =: scope
        ];
        campaignId = camp.Campaign__c;
        list<CampaignMember> insertCampaignMemberList = new list<CampaignMember>();
        //To create list of CM to be inserted
        if(oldLeadVsContactId2 != null && !oldLeadVsContactId2.isEmpty()){
            for(String cid : oldLeadVsContactId2){
                if(String.valueOf(cid).startsWith('003')){
                    CampaignMember newMember = new CampaignMember(ContactId = cid, status='Eligible', campaignid = camp.Campaign__c);
                    if(camp.Campaign__r.RecordType.Name.equals('Self Serve Marketing Promotion')) {
                        newMember.Needs_to_Sync__c = true;
                    }
                    conLeadIds.add(cid);
                    insertCampaignMemberList.add(newMember);
                }
                else if(String.valueOf(cid).startsWith('00Q')){
                    IF(camp.Campaign__r.recordType.Name=='B2B Developer Online Form'){
                        CampaignMember newMember = new CampaignMember(LeadId = cid, status='Joined', campaignid = camp.Campaign__c);
                        conLeadIds.add(cid);
                        insertCampaignMemberList.add(newMember);
                    }else{
                        CampaignMember newMember = new CampaignMember(LeadId = cid, status='Eligible', campaignid = camp.Campaign__c);
                        if(camp.Campaign__r.RecordType.Name.equals('Self Serve Marketing Promotion')) {
                            newMember.Needs_to_Sync__c = true;
                        }
                        conLeadIds.add(cid);
                        insertCampaignMemberList.add(newMember);
                    }
                    
                }
                
            }
            
        }
        if(!insertCampaignMemberList.isEmpty()){
            Database.SaveResult[] insertList = Database.insert(insertCampaignMemberList,false);
            allInsertList.addAll(insertList);
        }
        
        if(camp.Campaign__r.RecordType.Name.equals('Self Serve Marketing Promotion')) {
            Self_Serve_Campaign_Notification__e newSSNotification = new Self_Serve_Campaign_Notification__e();
            newSSNotification.SF_Campaign_Id__c = camp.Campaign__c;
            newSSNotification.PG_Campaign_Id__c = camp.Campaign__r.PG_Campaign_Id__c;
            listSSNotification.add(newSSNotification);
        }
         if(camp.Campaign__r.RecordType.Name.equals('Self Serve Renewal campaigns')) {
            RSS_discount_campaign_event__e  newSSNotification = new RSS_discount_campaign_event__e ();
            newSSNotification.campaign_ID__c  = camp.Campaign__c;
                newSSNotification.event_type__c  = 'Batch';
            listRSSNotification.add(newSSNotification);
        }
    }
    
    public void finish(DataBase.BatchableContext bc){
        campaignMemberSlackAlert(campaignId,allInsertList);
        if(!listSSNotification.isEmpty()) {
            //event used to send the info to workato
            //PGAUTO-5803
            EventBus.publish(listSSNotification);
        }
         if(!listRSSNotification.isEmpty())
         EventBus.publish(listRSSNotification);
    
    }
    
    public void campaignMemberSlackAlert(String campaignId, Database.SaveResult[] insertList){
        
        if(!runningInASandbox() || Test.isRunningTest()){
        
            Payload PayloadData = new Payload();
            Integer Count = 0;
            String title = '', text = '```"CampaignId", "Contact/Lead Id", "Error"\n', payload = '';
            for(integer i=0;i<insertList.size();i++){
                if(insertList[i] !=null && !insertList[i].isSuccess() && insertList[i].getErrors() !=null && insertList[i].getErrors().size() > 0 ){
                    //text += '"", '+String.valueOf(insertList[i].getErrors()[0].getMessage())+'"\n';
                    String conLead = conLeadIds==null || conLeadIds[i] == null ?'':conLeadIds[i];
                    text += '"'+campaignId+'", "'+conLead+'", "'+String.valueOf(insertList[i].getErrors()[0].getMessage())+'"\n';
                        Count++;
                }
            }
            
            if(Count > 0){
                text += '```';
                title += '<@U02AP0BELQ0> <@UTDHN0FU2>'+Count +' CampaignMembers with error\n';
                payload += title + text;
            }
            if(payload <> ''){
                Http h = new Http();
                HttpRequest req = new HttpRequest();
                req.setEndpoint(label.PG_LABEL_PGAutomationAlert);
                req.setMethod('POST');
                req.setHeader('Cache-Control', 'no-cache');
                req.setHeader('Content-Type', 'application/json');
                PayloadData.text = payload;
                string request = system.JSON.serialize(PayloadData);
                req.setBody(request);
                if(!Test.isRunningTest()){
                    HttpResponse res = h.send(req);
                    if (res.getStatusCode() <> 200) {
                        String errorResponse = res.getBody();
                    }
                }
            }
        }
    }
    public static Boolean runningInASandbox() {
        return [SELECT IsSandbox FROM Organization LIMIT 1].IsSandbox;
    }
    
}