unpackaged/main/default/objects/CS_Billing_Schedule__c/CS_Billing_Schedule__c.object-meta.xml
<CustomObject>
    <label>Billing Schedule</label>
    <nameField>
        <displayFormat>BIL-{00000000}</displayFormat>
        <label>Billing Schedule Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Billing Schedule</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/CS_Billing_Schedule__c/fields/CS_Sales_Order_Schedule__c.field-meta.xml
<CustomField>
    <fullName>CS_Sales_Order_Schedule__c</fullName>
    <label>CS Sales Order Schedule</label>
    <referenceTo>CS_Sales_Order_Schedule__c</referenceTo>
    <relationshipName>Billing_Schedule_Headers</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/CS_Billing_Schedule__c/fields/Product_Configuration__c.field-meta.xml
<CustomField>
    <fullName>Product_Configuration__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Link to Product Configuration</description>
    <inlineHelpText>Link to Product Configuration</inlineHelpText>
    <label>Product Configuration</label>
    <referenceTo>cscfga__Product_Configuration__c</referenceTo>
    <relationshipName>Billing_Schedule_Headers</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/CS_Billing_Schedule_Item__c/CS_Billing_Schedule_Item__c.object-meta.xml
<CustomObject>
    <description>Individiual details for one billing period for one line within a Sales Order</description>
    <label>Billing Schedule Item</label>
    <nameField>
        <displayFormat>BILI-{00000000}</displayFormat>
        <label>Billing Schedule Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Billing Schedule Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/CS_Billing_Schedule_Item__c/fields/Billing_Date__c.field-meta.xml
<CustomField>
    <fullName>Billing_Date__c</fullName>
    <description>Billing Date based on the Billing Rule + Billing Calendar.
-Monthly Standard  : Last day of each Standard Calendar Month from SO line item  Start to End of Campaign.
-Monthly Broadcast: Last day of each Broadcast Calendar Month from SO line item  Start to End of Campaign</description>
    <inlineHelpText>Billing Date based on the Billing Rule + Billing Calendar</inlineHelpText>
    <label>Billing Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/CS_Billing_Schedule_Item__c/fields/Billing_Schedule__c.field-meta.xml
<CustomField>
    <fullName>Billing_Schedule__c</fullName>
    <label>Billing Schedule</label>
    <referenceTo>CS_Billing_Schedule__c</referenceTo>
    <relationshipLabel>Billing Schedule Items</relationshipLabel>
    <relationshipName>Billing_Schedule_Items</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/CS_Billing_Schedule_Item__c/fields/Billing_Source__c.field-meta.xml
<CustomField>
    <fullName>Billing_Source__c</fullName>
    <description>Billing Rule as defined in the Sales Order Line
 - Contracted
 - DFP Actuals
 - 3rd Party Actuals</description>
    <inlineHelpText>Billing Rule as defined in the Sales Order Line
 - Contracted
 - DFP Actuals
 - 3rd Party Actuals</inlineHelpText>
    <label>Billing Source</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Contracted</fullName>
            </value>
            <value>
                <fullName>DFP Actuals</fullName>
            </value>
            <value>
                <fullName>3rd Party Actuals</fullName>
            </value>
            <value>
                <fullName>Megaphone</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/CS_Billing_Schedule_Item__c/fields/Flight_Begin__c.field-meta.xml
<CustomField>
    <fullName>Flight_Begin__c</fullName>
    <description>Flight Begin as defined in the Sales Order Line.</description>
    <inlineHelpText>Flight Begin as defined in the Sales Order Line.</inlineHelpText>
    <label>Flight Begin</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/CS_Billing_Schedule_Item__c/fields/Insertion_Unit_Type__c.field-meta.xml
<CustomField>
    <fullName>Insertion_Unit_Type__c</fullName>
    <description>Insertion Unit Type as defined in the Sales Order Line.</description>
    <inlineHelpText>Insertion Unit Type as defined in the Sales Order Line.</inlineHelpText>
    <label>Insertion Unit Type</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/CS_Billing_Schedule_Item__c/fields/Product_Configuration__c.field-meta.xml
<CustomField>
    <fullName>Product_Configuration__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Link to the related Product Configuration (Sales Order Line)</description>
    <inlineHelpText>Link to the related Product Configuration (Sales Order Line)</inlineHelpText>
    <label>Product Configuration</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>cscfga__Product_Configuration__c.Sales_Order__c</field>
            <operation>equals</operation>
            <valueField>$Source.Sales_Order__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>cscfga__Product_Configuration__c</referenceTo>
    <relationshipLabel>Billing Schedule Item</relationshipLabel>
    <relationshipName>Billing_Schedule_Item</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/CS_Billing_Schedule_Item__c/fields/X3rd_Party_Ad_Server__c.field-meta.xml
<CustomField>
    <fullName>X3rd_Party_Ad_Server__c</fullName>
    <description>3rd Party Ad Server as defined in the Sales Order Line.</description>
    <inlineHelpText>3rd Party Ad Server as defined in the Sales Order Line.</inlineHelpText>
    <label>3rd Party Ad Server</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/CS_Revenue_Schedule__c/CS_Revenue_Schedule__c.object-meta.xml
<CustomObject>
    <description>Header record for Revenue Recognition line items at Product Configuration level</description>
    <label>Revenue Schedule</label>
    <nameField>
        <displayFormat>REV-{00000000}</displayFormat>
        <label>Revenue Schedule Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Revenue Schedule</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/CS_Revenue_Schedule__c/fields/Billing_Schedule__c.field-meta.xml
<CustomField>
    <fullName>Billing_Schedule__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The sibling Billing Schedule header for the same SOLI</description>
    <inlineHelpText>The sibling Billing Schedule header for the same SOLI</inlineHelpText>
    <label>Billing Schedule</label>
    <referenceTo>CS_Billing_Schedule__c</referenceTo>
    <relationshipLabel>Revenue Schedule</relationshipLabel>
    <relationshipName>Revenue_Schedule</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/CS_Revenue_Schedule__c/fields/CS_Sales_Order_Schedule__c.field-meta.xml
<CustomField>
    <fullName>CS_Sales_Order_Schedule__c</fullName>
    <description>Link to Sales Order Schedule</description>
    <inlineHelpText>Link to Sales Order Schedule</inlineHelpText>
    <label>CS Sales Order Schedule</label>
    <referenceTo>CS_Sales_Order_Schedule__c</referenceTo>
    <relationshipName>Revenue_Schedule_Headers</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/CS_Revenue_Schedule__c/fields/Product_Configuration__c.field-meta.xml
<CustomField>
    <fullName>Product_Configuration__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Link to Product Configuration</description>
    <inlineHelpText>Link to Product Configuration</inlineHelpText>
    <label>Product Configuration</label>
    <referenceTo>cscfga__Product_Configuration__c</referenceTo>
    <relationshipName>Revenue_Schedule_Headers</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/CS_Revenue_Schedule_Item__c/CS_Revenue_Schedule_Item__c.object-meta.xml
<CustomObject>
    <description>Individiual details for one billing period for one line within a Sales Order</description>
    <label>Revenue Schedule Item</label>
    <nameField>
        <displayFormat>REVI-{00000000}</displayFormat>
        <label>Revenue Recognition Schedule Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Revenue Schedule Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/CS_Revenue_Schedule_Item__c/fields/Billing_Source__c.field-meta.xml
<CustomField>
    <fullName>Billing_Source__c</fullName>
    <description>Billing Rule as defined in the Sales Order Line.</description>
    <inlineHelpText>Billing Rule as defined in the Sales Order Line.</inlineHelpText>
    <label>Billing Source</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Contracted</fullName>
            </value>
            <value>
                <fullName>DFP Actuals</fullName>
            </value>
            <value>
                <fullName>3rd Party Actuals</fullName>
            </value>
            <value>
                <fullName>Megaphone</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/CS_Revenue_Schedule_Item__c/fields/Flight_End__c.field-meta.xml
<CustomField>
    <fullName>Flight_End__c</fullName>
    <description>Flight End as defined in the Sales Order Line.</description>
    <inlineHelpText>Flight End as defined in the Sales Order Line.</inlineHelpText>
    <label>Flight End</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/CS_Revenue_Schedule_Item__c/fields/Product_Configuration__c.field-meta.xml
<CustomField>
    <fullName>Product_Configuration__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Link to the related Product Configuration (Sales Order Line)</description>
    <inlineHelpText>Link to the related Product Configuration (Sales Order Line)</inlineHelpText>
    <label>Product Configuration</label>
    <referenceTo>cscfga__Product_Configuration__c</referenceTo>
    <relationshipLabel>Revenue Schedule Item</relationshipLabel>
    <relationshipName>Revenue_Schedule_Item</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/CS_Revenue_Schedule_Item__c/fields/Revenue_Schedule__c.field-meta.xml
<CustomField>
    <fullName>Revenue_Schedule__c</fullName>
    <description>Link to Revenue Schedule Header</description>
    <inlineHelpText>Link to Revenue Schedule Header</inlineHelpText>
    <label>Revenue Schedule</label>
    <referenceTo>CS_Revenue_Schedule__c</referenceTo>
    <relationshipLabel>Revenue Schedule Items</relationshipLabel>
    <relationshipName>Revenue_Schedule_Items</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/CS_Sales_Order_Schedule__c/CS_Sales_Order_Schedule__c.object-meta.xml
<CustomObject>
    <label>Sales Order Schedule</label>
    <nameField>
        <displayFormat>RS-{00000000}</displayFormat>
        <label>Sales Order Schedules Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sales Order Schedules</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/CS_Sales_Order_Schedule__c/fields/Billing_Date__c.field-meta.xml
<CustomField>
    <fullName>Billing_Date__c</fullName>
    <label>Billing Date</label>
    <summarizedField>CS_Billing_Schedule__c.Next_Billing_Date__c</summarizedField>
    <summaryForeignKey>CS_Billing_Schedule__c.CS_Sales_Order_Schedule__c</summaryForeignKey>
    <summaryOperation>min</summaryOperation>
    <type>Summary</type>
</CustomField>

unpackaged/main/default/objects/Worker__c/Worker__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>Worker</label>
</CustomObject>

unpackaged/main/default/objects/Worker__c/fields/Batch_Jobs_Limit__c.field-meta.xml
<CustomField>
    <fullName>Batch_Jobs_Limit__c</fullName>
    <label>Batch Jobs Limit</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/Worker__c/fields/Batch_Retry_Time__c.field-meta.xml
<CustomField>
    <fullName>Batch_Retry_Time__c</fullName>
    <label>Batch Retry Time</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/X3rd_Party_Ad_Server__c/X3rd_Party_Ad_Server__c.object-meta.xml
<CustomObject>
    <description>Object to store 3rd Party Ad Server values</description>
    <label>3rd Party Ad Server</label>
    <nameField>
        <displayFormat>AS-{00000000}</displayFormat>
        <label>Ad Server Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>3rd Party Ad Servers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/X3rd_Party_Ad_Server__c/fields/X3rd_Party_Ad_Server__c.field-meta.xml
<CustomField>
    <fullName>X3rd_Party_Ad_Server__c</fullName>
    <description>Values for 3rd Party Ad Server from DFP Spotify Prod definition</description>
    <inlineHelpText>Values for 3rd Party Ad Server from DFP Spotify Prod definition</inlineHelpText>
    <label>3rd Party Ad Server</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>MediaMind</fullName>
            </value>
            <value>
                <fullName>DFA by Google</fullName>
            </value>
            <value>
                <fullName>FlashTalking</fullName>
            </value>
            <value>
                <fullName>Innovid3P</fullName>
            </value>
            <value>
                <fullName>Dart Report Reader</fullName>
            </value>
            <value>
                <fullName>Mediaplex</fullName>
            </value>
            <value>
                <fullName>Rubicon</fullName>
            </value>
            <value>
                <fullName>EyeReturn</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/classes/CS_BatchConsolidateThirdPartyActualsTest.cls
/**
 * Created by jameshladek on 2/13/20.
 */
@IsTest
public with sharing class CS_BatchConsolidateThirdPartyActualsTest {

    @TestSetup static void setupData() {
        Worker__c worker = new Worker__c();
        worker.Batch_Jobs_Limit__c = 5;
        worker.Batch_Retry_Time__c = 15;
        insert worker;

        X3rd_Party_Ad_Server__c server = new X3rd_Party_Ad_Server__c();
        server.X3rd_Party_Ad_Server__c = 'Test Server';
        insert server;

        cscfga__Product_Configuration__c testConfig = TestDataSetupSO.createproductConfigAndDef('Test Data');
        testConfig.Flight_Begin__c = Date.today().addMonths(-1);
        testConfig.Flight_End__c = Date.today();
        testConfig.Insertion_Unit_Type__c = 'CPC';
        testConfig.Order_Line_ID__c = '523678245';
        testConfig.Billing_Source__c = '3rd Party Actuals';
        testConfig.X3rd_Party_Ad_Server__c = server.Id;
        update testConfig;

        CS_Sales_Order_Schedule__c schedule = new CS_Sales_Order_Schedule__c();
        insert schedule;

        CS_Sales_Order_Schedule__c salesOrderSchedule = new CS_Sales_Order_Schedule__c(); 
        insert salesOrderSchedule;

        CS_Billing_Schedule__c billingSchedule = new CS_Billing_Schedule__c();
        billingSchedule.CS_Sales_Order_Schedule__c = salesOrderSchedule.Id;
        insert billingSchedule;

        CS_Revenue_Schedule__c revenueSchedule = new CS_Revenue_Schedule__c();
        revenueSchedule.CS_Sales_Order_Schedule__c = salesOrderSchedule.Id;
        insert revenueSchedule;

        CS_Billing_Schedule_Item__c bsi = new CS_Billing_Schedule_Item__c();
        bsi.Billing_Schedule__c = billingSchedule.Id;
        bsi.Billing_Date__c = Date.today().addMonths(-1);
        bsi.Product_Configuration__c = testConfig.Id;
        insert bsi;

        CS_Revenue_Schedule_Item__c rsi = new CS_Revenue_Schedule_Item__c();
        rsi.Revenue_Schedule__c = revenueSchedule.Id;
        rsi.Rev_Rec_Date__c = Date.today().addMonths(-1);
        rsi.Product_Configuration__c = testConfig.Id;
        insert rsi;

        Third_Party_Monthly_Actual__c monthlyActual1 = new Third_Party_Monthly_Actual__c();
        monthlyActual1.Clicks__c = 10;
        monthlyActual1.Impressions__c = 5;
        monthlyActual1.Order_Line_Id__c = '523678245';
        monthlyActual1.Report_Date__c = Date.today().addMonths(-1);
        monthlyActual1.Local_Server_Name__c = 'Test Server';
        insert monthlyActual1;

        Third_Party_Monthly_Actual__c monthlyActual2 = new Third_Party_Monthly_Actual__c();
        monthlyActual2.Clicks__c = 20;
        monthlyActual2.Impressions__c = 10;
        monthlyActual2.Order_Line_Id__c = '523678245';
        monthlyActual2.Report_Date__c = Date.today().addMonths(-1);
        monthlyActual2.Local_Server_Name__c = 'Test Server';
        insert monthlyActual2;
    }

    @IsTest static void testPCCPC() {

        CS_BatchConsolidateThirdPartyActuals batch = new CS_BatchConsolidateThirdPartyActuals();
        Test.startTest();
        Database.executeBatch(batch);
        Test.stopTest();
        CS_Revenue_Schedule_Item__c revenueScheduleItem = [SELECT Third_Party_Monthly_Actuals__c FROM CS_Revenue_Schedule_Item__c LIMIT 1];
        CS_Billing_Schedule_Item__c billingScheduleItem = [SELECT Third_Party_Monthly_Actuals__c FROM CS_Billing_Schedule_Item__c LIMIT 1];

        //System.assertEquals(30, revenueScheduleItem.Third_Party_Monthly_Actuals__c);
        //System.assertEquals(30, billingScheduleItem.Third_Party_Monthly_Actuals__c);
    }

    @IsTest static void testPCNonCPC() {
        cscfga__Product_Configuration__c pc = [
                SELECT Id, Insertion_Unit_Type__c, Flight_Begin__c, Flight_End__c, (SELECT Id, Third_Party_Monthly_Actuals__c FROM Billing_Schedule_Item__r), (SELECT Id, Third_Party_Monthly_Actuals__c FROM Revenue_Schedule_Item__r)
                FROM cscfga__Product_Configuration__c
                LIMIT 1
        ];
        pc.Insertion_Unit_Type__c = 'CPM';
        update pc;

        CS_BatchConsolidateThirdPartyActuals batch = new CS_BatchConsolidateThirdPartyActuals();
        Test.startTest();
        Database.executeBatch(batch);
        Test.stopTest();

        CS_Revenue_Schedule_Item__c revenueScheduleItem = [SELECT Third_Party_Monthly_Actuals__c FROM CS_Revenue_Schedule_Item__c LIMIT 1];
        CS_Billing_Schedule_Item__c billingScheduleItem = [SELECT Third_Party_Monthly_Actuals__c FROM CS_Billing_Schedule_Item__c LIMIT 1];

        //System.assertEquals(15, revenueScheduleItem.Third_Party_Monthly_Actuals__c);
        //System.assertEquals(15, billingScheduleItem.Third_Party_Monthly_Actuals__c);
    }

    @IsTest static void testScheduleCall() {
        Test.startTest();
        CS_BatchConsolidateThirdPartyActuals.scheduleIt();
        Test.stopTest();
    }

}