unpackaged/main/default/objects/CS_Billing_Schedule__c/CS_Billing_Schedule__c.object-meta.xml
<CustomObject>
    <label>Billing Schedule</label>
    <nameField>
        <displayFormat>BIL-{00000000}</displayFormat>
        <label>Billing Schedule Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Billing Schedule</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/CS_Billing_Schedule__c/fields/Product_Configuration__c.field-meta.xml
<CustomField>
    <fullName>Product_Configuration__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Link to Product Configuration</description>
    <inlineHelpText>Link to Product Configuration</inlineHelpText>
    <label>Product Configuration</label>
    <referenceTo>cscfga__Product_Configuration__c</referenceTo>
    <relationshipName>Billing_Schedule_Headers</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/CS_Billing_Schedule__c/fields/Sales_Order__c.field-meta.xml
<CustomField>
    <fullName>Sales_Order__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Link to the related Sales Order</description>
    <inlineHelpText>Link to the related Sales Order</inlineHelpText>
    <label>Sales Order</label>
    <referenceTo>csmso__Sales_Order__c</referenceTo>
    <relationshipName>Billing_Schedule_Headers</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/CS_Billing_Schedule__c/fields/Under_IFC__c.field-meta.xml
<CustomField>
    <fullName>Under_IFC__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Marks if the line is under in Flight Changes.</description>
    <inlineHelpText>Marks if the line is under in Flight Changes.</inlineHelpText>
    <label>Under In Flight Change</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/CS_Billing_Schedule_Item__c/CS_Billing_Schedule_Item__c.object-meta.xml
<CustomObject>
    <description>Individiual details for one billing period for one line within a Sales Order</description>
    <label>Billing Schedule Item</label>
    <nameField>
        <displayFormat>BILI-{00000000}</displayFormat>
        <label>Billing Schedule Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Billing Schedule Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/CS_Billing_Schedule_Item__c/fields/Is_Closed__c.field-meta.xml
<CustomField>
    <fullName>Is_Closed__c</fullName>
    <description>Specifies if a Line is considered &#39;open or closed&#39; based on status</description>
    <formula>OR(
ISPICKVAL(Status__c, &quot;Ready&quot;),
ISPICKVAL(Status__c, &quot;Pending Closure&quot;),
ISPICKVAL(Status__c, &quot;Pending&quot;), 
ISPICKVAL(Status__c, &quot;Locked&quot;),
ISPICKVAL(Status__c, &quot;Closed&quot;)
)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>Specifies if a Line is considered &#39;open or closed&#39; based on status</inlineHelpText>
    <label>Is Closed</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/CS_Billing_Schedule_Item__c/fields/Is_Open__c.field-meta.xml
<CustomField>
    <fullName>Is_Open__c</fullName>
    <description>Specifies if the record is Open for billing processes</description>
    <formula>ISPICKVAL(Status__c, &quot;Open&quot;)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>Specifies if the record is Open for billing processes</inlineHelpText>
    <label>Is Open</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/CS_Billing_Schedule_Item__c/fields/IsForecast__c.field-meta.xml
<CustomField>
    <fullName>IsForecast__c</fullName>
    <description>This field is to determine the billing Schedules are forecast billing schedules or not.</description>
    <formula>If(TEXT(Status__c)  = &#39;Forecast&#39;,true,false)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>This field is to determine the billing Schedules are forecast billing schedules or not.</inlineHelpText>
    <label>IsForecast</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/CS_Billing_Schedule_Item__c/fields/Product_Configuration__c.field-meta.xml
<CustomField>
    <fullName>Product_Configuration__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Link to the related Product Configuration (Sales Order Line)</description>
    <inlineHelpText>Link to the related Product Configuration (Sales Order Line)</inlineHelpText>
    <label>Product Configuration</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>cscfga__Product_Configuration__c.Sales_Order__c</field>
            <operation>equals</operation>
            <valueField>$Source.Sales_Order__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>cscfga__Product_Configuration__c</referenceTo>
    <relationshipLabel>Billing Schedule Item</relationshipLabel>
    <relationshipName>Billing_Schedule_Item</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/CS_Billing_Schedule_Item__c/fields/Sales_Order__c.field-meta.xml
<CustomField>
    <fullName>Sales_Order__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Link to the related Sales Order.</description>
    <inlineHelpText>Link to the related Sales Order.</inlineHelpText>
    <label>Sales Order</label>
    <referenceTo>csmso__Sales_Order__c</referenceTo>
    <relationshipLabel>Billing Schedule Item</relationshipLabel>
    <relationshipName>CS_Billing_Schedule_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/CS_Billing_Schedule_Item__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>Billing Schedule Status.</description>
    <inlineHelpText>Billing Schedule Status</inlineHelpText>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Open</fullName>
            </value>
            <value>
                <fullName>Locked</fullName>
            </value>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Ready</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
            <value>
                <fullName>Forecast</fullName>
            </value>
            <value>
                <fullName>Pending Closure</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/CS_Billing_Schedule_Item__c/fields/Under_IFC__c.field-meta.xml
<CustomField>
    <fullName>Under_IFC__c</fullName>
    <formula>Billing_Schedule__r.Under_IFC__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Under In Flight Change</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/CS_Revenue_Schedule__c/CS_Revenue_Schedule__c.object-meta.xml
<CustomObject>
    <description>Header record for Revenue Recognition line items at Product Configuration level</description>
    <label>Revenue Schedule</label>
    <nameField>
        <displayFormat>REV-{00000000}</displayFormat>
        <label>Revenue Schedule Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Revenue Schedule</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/CS_Revenue_Schedule__c/fields/Product_Configuration__c.field-meta.xml
<CustomField>
    <fullName>Product_Configuration__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Link to Product Configuration</description>
    <inlineHelpText>Link to Product Configuration</inlineHelpText>
    <label>Product Configuration</label>
    <referenceTo>cscfga__Product_Configuration__c</referenceTo>
    <relationshipName>Revenue_Schedule_Headers</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/CS_Revenue_Schedule__c/fields/Sales_Order__c.field-meta.xml
<CustomField>
    <fullName>Sales_Order__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Link to the related Sales Order</description>
    <inlineHelpText>Link to the related Sales Order</inlineHelpText>
    <label>Sales Order</label>
    <referenceTo>csmso__Sales_Order__c</referenceTo>
    <relationshipName>Revenue_Schedule_Headers</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/CS_Revenue_Schedule__c/fields/Under_IFC__c.field-meta.xml
<CustomField>
    <fullName>Under_IFC__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Indicates that Line item is unlocked for changes.</description>
    <inlineHelpText>Indicates that Line item is unlocked for changes.</inlineHelpText>
    <label>Under In Flight Change</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/classes/CS_UnlockLinesInvoker.cls
/**
 * Created by tvrtko.matosevic on 10/06/2019.
 *
 * Bulkified version of UnlockLineController class, it is used for Unlocking line items through MLE
 */

global with sharing class CS_UnlockLinesInvoker  {
    global String performAction(String parameters) {
        System.debug('parameters => ' + parameters);

        List<Id> configIds = (List<Id>) JSON.deserialize(parameters, List<Id>.class);

        Map<Id, List<CS_Billing_Schedule_Item__c>> billingScheduleItemListByConfigIdMap = getBillingScheduleItemListByConfigIdMap(configIds);

        List<String> attNames = new List<String>{
                'Flight Begin Date Time Selected', 'Flight End Date Time Selected'
        };
        List<cscfga__Attribute__c> attributeList = [
                SELECT
                        Id, Name, cscfga__Value__c, cscfga__Product_Configuration__c
                FROM
                        cscfga__Attribute__c
                WHERE
                cscfga__Product_Configuration__c = :configIds AND Name IN :attNames
        ];

        Map<Id, Boolean> isFlightBeginAfterTodayByConfigIdMap = new Map<Id, Boolean>();
        Map<Id, Boolean> isFlightEndBeforeTodayByConfigIdMap = new Map<Id, Boolean>();
        Datetime dateTimeNow = Datetime.now();
        for (cscfga__Attribute__c attribute : attributeList) {
            Boolean startDateAfterToday;
            Boolean endDateBeforeToday;

            if (attribute.Name == 'Flight Begin Date Time Selected') {
                Datetime flightBeginDateTime;

                if (attribute.cscfga__Value__c.split(' ').size() > 2) {
                    flightBeginDateTime = CS_utl_Datetime.getTimezoneOffset(attribute.cscfga__Value__c);
                } else {
                    flightBeginDateTime = Datetime.valueOf(attribute.cscfga__Value__c + ':00');
                }

                if (flightBeginDateTime > dateTimeNow) {
                    startDateAfterToday = true;
                } else {
                    startDateAfterToday = false;
                }

                isFlightBeginAfterTodayByConfigIdMap.put(attribute.cscfga__Product_Configuration__c, startDateAfterToday);
            }

            if (attribute.Name == 'Flight End Date Time Selected') {
                Datetime flightEndDateTime;

                if (attribute.cscfga__Value__c.split(' ').size() > 2) {
                    flightEndDateTime = CS_utl_Datetime.getTimezoneOffset(attribute.cscfga__Value__c);
                } else {
                    flightEndDateTime = Datetime.valueOf(attribute.cscfga__Value__c + ':00');
                }

                if (flightEndDateTime.addDays(14) > dateTimeNow) {
                    endDateBeforeToday = false;
                } else {
                    endDateBeforeToday = true;
                }

                isFlightEndBeforeTodayByConfigIdMap.put(attribute.cscfga__Product_Configuration__c, endDateBeforeToday);
            }
        }

        Map<Id, String> productConfigurationFulfilmentStatusByConfigIdMap = getPCFulfilmentItemStatusByConfigIdMap(configIds);
        List<ProductConfigurationLockingStatus> pcLockingStatusList = getPCLockingStatusList(productConfigurationFulfilmentStatusByConfigIdMap,
                                                                                   isFlightBeginAfterTodayByConfigIdMap,
                                                                                   isFlightEndBeforeTodayByConfigIdMap,
                                                                                   billingScheduleItemListByConfigIdMap);

        return JSON.serialize(pcLockingStatusList);
    }

    Map<Id, List<CS_Billing_Schedule_Item__c>> getBillingScheduleItemListByConfigIdMap(List<Id> configIds){
        List<CS_Billing_Schedule_Item__c> billingScheduleItemList = [
                SELECT
                        Id, Name, Sales_Order__c, Product_Configuration__c, 
                        Status__c, Is_Open__c, Is_Closed__c, IsForecast__c
                FROM
                        CS_Billing_Schedule_Item__c
                WHERE
                        Product_Configuration__c = :configIds
        ];

        Map<Id, List<CS_Billing_Schedule_Item__c>> billingScheduleItemListByConfigIdMap = new Map<Id, List<CS_Billing_Schedule_Item__c>>();
        for (CS_Billing_Schedule_Item__c billingScheduleItem : billingScheduleItemList) {
            if (!billingScheduleItemListByConfigIdMap.containsKey(billingScheduleItem.Product_Configuration__c)) {
                billingScheduleItemListByConfigIdMap.put(billingScheduleItem.Product_Configuration__c, new List<CS_Billing_Schedule_Item__c>{
                        billingScheduleItem
                });
            } else {
                billingScheduleItemListByConfigIdMap.get(billingScheduleItem.Product_Configuration__c).add(billingScheduleItem);
            }
        }

        return billingScheduleItemListByConfigIdMap;
    }

    Map<Id, String> getPCFulfilmentItemStatusByConfigIdMap (List<Id> configIds) {
        List<cscfga__Product_Configuration__c> productConfigurations = [
                SELECT Id, Fulfilment_Item_Status__c
                FROM cscfga__Product_Configuration__c
                WHERE Id = :configIds
        ];
        Map<Id, String> productConfigurationFulfilmentStatusByConfigIdMap = new Map<Id, String>();
        for (cscfga__Product_Configuration__c pc : productConfigurations) {
            productConfigurationFulfilmentStatusByConfigIdMap.put(pc.Id, pc.Fulfilment_Item_Status__c);
        }

        return productConfigurationFulfilmentStatusByConfigIdMap;
    }

    List<ProductConfigurationLockingStatus> getPCLockingStatusList(Map<Id, String> productConfigurationFulfilmentStatusByConfigIdMap,
            Map<Id, Boolean> isFlightBeginAfterTodayByConfigIdMap,
            Map<Id, Boolean> isFlightEndBeforeTodayByConfigIdMap,
            Map<Id, List<CS_Billing_Schedule_Item__c>> billingScheduleItemListByConfigIdMap) {

        List<ProductConfigurationLockingStatus> pcLockingStatusList = new List<ProductConfigurationLockingStatus>();
        List<Id> configIdsToUpdateSchedules = new List<Id>();
        for (Id configId : productConfigurationFulfilmentStatusByConfigIdMap.keySet()) {
            Boolean hasAllLinesClosed = true;
            Boolean hasAllLinesOpen = true;
            Boolean hasOpenBillSch = false;
            Boolean lockedForReconciliation = false;

            // process related Billing Schedules
            if (!billingScheduleItemListByConfigIdMap.isEmpty()){
                for (CS_Billing_Schedule_Item__c currentBillSchedule : billingScheduleItemListByConfigIdMap.get(configId)) {
                    if (currentBillSchedule.Is_Open__c) {
                        hasOpenBillSch = true;
                        hasAllLinesClosed = false;
                    }
                    if (currentBillSchedule.Is_Closed__c) {
                        hasAllLinesOpen = false;
                    }
                    if (currentBillSchedule.IsForecast__c) {
                        hasAllLinesOpen = false;
                    }

                    if (currentBillSchedule.Status__c == 'Pending' || currentBillSchedule.Status__c == 'Ready') {
                        lockedForReconciliation = true;
                    }
                }
            }

            // FI status
            Boolean isActiveLine = productConfigurationFulfilmentStatusByConfigIdMap.get(configId) != CS_const_SalesOrder.FulfilmentItemStatus_Draft
                    && productConfigurationFulfilmentStatusByConfigIdMap.get(configId) != CS_const_SalesOrder.FulfilmentItemStatus_Inactive
                    && productConfigurationFulfilmentStatusByConfigIdMap.get(configId) != CS_const_SalesOrder.FulfilmentItemStatus_Ready;

            // final status check
            String finalStatus = 'Locked';
            if ((isFlightEndBeforeTodayByConfigIdMap.get(configId) && isActiveLine)) {
                finalStatus = 'Locked';
            }
            // Partially Locked - Line is partially Invoiced & End date is in the future and Line is not locked for reconciliation
            if ((!isFlightEndBeforeTodayByConfigIdMap.get(configId) || !isActiveLine)) {
                finalStatus = 'Partially Locked';
            }
            // Unlocked - Line is NOT Invoiced & End date is in the future and Line is not locked for reconciliation
            if (hasAllLinesOpen && isFlightBeginAfterTodayByConfigIdMap.get(configId) && (!isFlightEndBeforeTodayByConfigIdMap.get(configId) || !isActiveLine) && !lockedForReconciliation) {
                finalStatus = 'Unlocked';
            }

            // IF Sales Order Line is Partially Locked or Unlocked ALL related Billing Schedule and Rev Rec Schedule with Status = Open is set On Hold for IFC
            if (finalStatus == 'Unlocked' || finalStatus == 'Partially Locked') {
                configIdsToUpdateSchedules .add(configId);
            }

            System.debug('#### Unlock Controller / hasAllLinesClosed - ' + hasAllLinesClosed + ' / lockedForReconciliation - ' + lockedForReconciliation);
            System.debug('#### Unlock Controller / hasOpenBillSch - ' + hasOpenBillSch + ' / endDateBeforeToday - ' + isFlightEndBeforeTodayByConfigIdMap.get(configId));
            System.debug('#### Unlock Controller / hasAllLinesOpen - ' + hasAllLinesOpen + ' / startDateAfterToday - ' + isFlightBeginAfterTodayByConfigIdMap.get(configId));
            System.debug('#### Unlock Controller / finalStatus - ' + finalStatus);

            pcLockingStatusList.add(new ProductConfigurationLockingStatus(configId, finalStatus));
        }

        if (!configIdsToUpdateSchedules .isEmpty()) {
            updateSchedules(configIdsToUpdateSchedules);
        }

        return pcLockingStatusList;
    }

    public static void updateSchedules(List<Id> configIds) {
        List<CS_Revenue_Schedule__c> revRecScheduleList = [
                SELECT
                        Id, Name, Under_IFC__c
                FROM
                        CS_Revenue_Schedule__c
                WHERE
                        Product_Configuration__c IN :configIds
        ];

        // NEW - We only need to update the billing schedule Headers here.
        // CPS 30/10/2018
        List<CS_Billing_Schedule__c> billingScheduleList = [
                SELECT
                        Id, Name, Under_IFC__c
                FROM
                        CS_Billing_Schedule__c
                WHERE
                        Product_Configuration__c IN :configIds
        ];

        List<CS_Revenue_Schedule__c> revRecSchedulesUpdate = new List<CS_Revenue_Schedule__c>();
        for (CS_Revenue_Schedule__c currentRevRecSch : revRecScheduleList) {
            if (currentRevRecSch.Under_IFC__c == false) {
                currentRevRecSch.Under_IFC__c = true;
                revRecSchedulesUpdate.add(currentRevRecSch);
            }
        }

        if (!revRecSchedulesUpdate.isEmpty()) {
            update revRecSchedulesUpdate;
        }


        // CPS 30/10/18 - We just need to update the Billing Schedule Headers here, not each item.
        List<CS_Billing_Schedule__c> billSchedulesUpdate = new List<CS_Billing_Schedule__c>();
        for (CS_Billing_Schedule__c currentBillSch : billingScheduleList) {
            if (currentBillSch.Under_IFC__c == false) {
                currentBillSch.Under_IFC__c = true;
                billSchedulesUpdate.add(currentBillSch);
            }
        }

        if (!billSchedulesUpdate.isEmpty()) {
            update billSchedulesUpdate;
        }
    }

    public class ProductConfigurationLockingStatus {
        public Id Id;
        public String LockingStatus;

        public ProductConfigurationLockingStatus(Id id, String lockingStatus){
            this.Id = id;
            this.LockingStatus = lockingStatus;
        }
    }
}