unpackaged/main/default/objects/CS_Billing_Schedule__c/CS_Billing_Schedule__c.object-meta.xml
<CustomObject>
    <label>Billing Schedule</label>
    <nameField>
        <displayFormat>BIL-{00000000}</displayFormat>
        <label>Billing Schedule Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Billing Schedule</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/CS_Billing_Schedule__c/fields/CS_Sales_Order_Schedule__c.field-meta.xml
<CustomField>
    <fullName>CS_Sales_Order_Schedule__c</fullName>
    <label>CS Sales Order Schedule</label>
    <referenceTo>CS_Sales_Order_Schedule__c</referenceTo>
    <relationshipName>Billing_Schedule_Headers</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/CS_Billing_Schedule__c/fields/Sales_Order__c.field-meta.xml
<CustomField>
    <fullName>Sales_Order__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Link to the related Sales Order</description>
    <inlineHelpText>Link to the related Sales Order</inlineHelpText>
    <label>Sales Order</label>
    <referenceTo>csmso__Sales_Order__c</referenceTo>
    <relationshipName>Billing_Schedule_Headers</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/CS_Billing_Schedule__c/fields/Under_IFC__c.field-meta.xml
<CustomField>
    <fullName>Under_IFC__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Marks if the line is under in Flight Changes.</description>
    <inlineHelpText>Marks if the line is under in Flight Changes.</inlineHelpText>
    <label>Under In Flight Change</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/CS_Billing_Schedule_Item__c/CS_Billing_Schedule_Item__c.object-meta.xml
<CustomObject>
    <description>Individiual details for one billing period for one line within a Sales Order</description>
    <label>Billing Schedule Item</label>
    <nameField>
        <displayFormat>BILI-{00000000}</displayFormat>
        <label>Billing Schedule Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Billing Schedule Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/CS_Billing_Schedule_Item__c/fields/Billing_Period_End_Date__c.field-meta.xml
<CustomField>
    <fullName>Billing_Period_End_Date__c</fullName>
    <description>- Monthly Standard: The earliest from SO Line End Date or last day of Standard Calendar Month for the Billing Date
 - Monthly Broadcast: The earliest from SO Line End Date or last day of Broadcast Calendar Month for the Billing Date</description>
    <inlineHelpText>- Monthly Standard: The earliest from SO Line End Date or last day of Standard Calendar Month for the Billing Date
 - Monthly Broadcast: The earliest from SO Line End Date or last day of Broadcast Calendar Month for the Billing Date</inlineHelpText>
    <label>Billing Period End Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/CS_Billing_Schedule_Item__c/fields/Billing_Period_Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Billing_Period_Start_Date__c</fullName>
    <description>- Monthly Standard: The latest from SO Line Start Date or first day of Standard Calendar Month for the Billing Date
 - Monthly Broadcast: The latest from SO Line Start Date or first day of Broadcast Calendar Month for the Billing Date</description>
    <inlineHelpText>- Monthly Standard: The latest from SO Line Start Date or first day of Standard Calendar Month for the Billing Date
 - Monthly Broadcast: The latest from SO Line Start Date or first day of Broadcast Calendar Month for the Billing Date</inlineHelpText>
    <label>Billing Period Start Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/CS_Billing_Schedule_Item__c/fields/Billing_Schedule__c.field-meta.xml
<CustomField>
    <fullName>Billing_Schedule__c</fullName>
    <label>Billing Schedule</label>
    <referenceTo>CS_Billing_Schedule__c</referenceTo>
    <relationshipLabel>Billing Schedule Items</relationshipLabel>
    <relationshipName>Billing_Schedule_Items</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/CS_Billing_Schedule_Item__c/fields/DFP_Order_Line_ID__c.field-meta.xml
<CustomField>
    <fullName>DFP_Order_Line_ID__c</fullName>
    <description>Related DFP Order  Line ID (If exists)</description>
    <inlineHelpText>Related DFP Order  Line ID (If exists)</inlineHelpText>
    <label>DFP Order Line ID</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/CS_Billing_Schedule_Item__c/fields/Sales_Order__c.field-meta.xml
<CustomField>
    <fullName>Sales_Order__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Link to the related Sales Order.</description>
    <inlineHelpText>Link to the related Sales Order.</inlineHelpText>
    <label>Sales Order</label>
    <referenceTo>csmso__Sales_Order__c</referenceTo>
    <relationshipLabel>Billing Schedule Item</relationshipLabel>
    <relationshipName>CS_Billing_Schedule_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/CS_Billing_Schedule_Item__c/fields/Under_IFC__c.field-meta.xml
<CustomField>
    <fullName>Under_IFC__c</fullName>
    <formula>Billing_Schedule__r.Under_IFC__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Under In Flight Change</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/CS_DFP_Actuals_By_Hour_Report_Data__c/CS_DFP_Actuals_By_Hour_Report_Data__c.object-meta.xml
<CustomObject>
    <label>DFP Actuals By Hour Report Data</label>
    <nameField>
        <displayFormat>DFPAH-{00000000}</displayFormat>
        <label>DFP Actuals Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>DFP Actuals By Hour Report Data</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/CS_DFP_Actuals_By_Hour_Report_Data__c/fields/Hour__c.field-meta.xml
<CustomField>
    <fullName>Hour__c</fullName>
    <description>The hour in which the impressions were delivered (in GMT)</description>
    <inlineHelpText>The hour in which the impressions were delivered (in GMT)</inlineHelpText>
    <label>Hour</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/CS_DFP_Actuals_By_Hour_Report_Data__c/fields/Order_Line_Id__c.field-meta.xml
<CustomField>
    <fullName>Order_Line_Id__c</fullName>
    <externalId>true</externalId>
    <label>Order Line Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/CS_Sales_Order_Schedule__c/CS_Sales_Order_Schedule__c.object-meta.xml
<CustomObject>
    <label>Sales Order Schedule</label>
    <nameField>
        <displayFormat>RS-{00000000}</displayFormat>
        <label>Sales Order Schedules Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sales Order Schedules</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/CS_Sales_Order_Schedule__c/fields/Sales_Order__c.field-meta.xml
<CustomField>
    <fullName>Sales_Order__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Link to the related Sales Order</description>
    <inlineHelpText>Link to the related Sales Order</inlineHelpText>
    <label>Sales Order</label>
    <referenceTo>csmso__Sales_Order__c</referenceTo>
    <relationshipLabel>Sales Order Schedules</relationshipLabel>
    <relationshipName>Sales_Order_Schedules</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/classes/CS_BatchDeleteReportDataTest.cls
/**
 * Created by sasa.marjancic on 14.1.2020..
 */
@isTest
public class CS_BatchDeleteReportDataTest {
    @testSetup
    private static void setup() {
        CS_utl_User.disableAllTriggers(UserInfo.getUserId());
        CS_th_Worker.create();
        csmso__SalesOrderAPI__c soapi = TestDataSetupSO.createSalesOrderAPI();
        insert soapi;

        csmso__Sales_Order__c salesOrder = new csmso__Sales_Order__c();
        insert salesOrder;

        CS_Sales_Order_Schedule__c sOs = new CS_Sales_Order_Schedule__c();
        sos.sales_order__c = salesOrder.id;
        insert sOs;

        CS_Billing_Schedule__c bs = new CS_Billing_Schedule__c();
        bs.CS_Sales_Order_Schedule__c = sOs.id;
        bs.Under_IFC__c = false;
        insert bs;

        CS_Billing_Schedule_Item__c bsi = new CS_Billing_Schedule_Item__c();
        bsi.Sales_Order__c = salesOrder.Id;
        bsi.Billing_Period_Start_Date__c = Date.Today().addDays(-10);
        bsi.Billing_Period_End_Date__c = Date.Today().addDays(5);
        bsi.billing_schedule__c = bs.id;
        bsi.DFP_Order_Line_ID__c = '12345';
        insert bsi;

        Test.startTest();
    }

    @isTest
    private static void test_deleteDuplicates() {
        List<CS_DFP_Actuals_By_Hour_Report_Data__c> dfpActualsOld = new List<CS_DFP_Actuals_By_Hour_Report_Data__c>();
        List<CS_DFP_Actuals_By_Hour_Report_Data__c> dfpActuals = new List<CS_DFP_Actuals_By_Hour_Report_Data__c>();
        for(Integer i = 0; i < 1000; i++) {
            CS_DFP_Actuals_By_Hour_Report_Data__c actual = new CS_DFP_Actuals_By_Hour_Report_Data__c(
                Order_Line_Id__c = '12345',
                Report_Date__c = Date.today().addDays((i/100.00).intValue() - 10),
                Impressions__c = (i/10.00).intValue(),
                Hour__c = Math.mod(i, 24)
            );
            dfpActualsOld.add(actual);
        }
        insert dfpActualsOld;

        for(Integer i = 0; i < 240; i++) {
            CS_DFP_Actuals_By_Hour_Report_Data__c actual = new CS_DFP_Actuals_By_Hour_Report_Data__c(
                    Order_Line_Id__c = '12345',
                    Report_Date__c = Date.today().addDays((i/24.00).intValue() - 10),
                    Impressions__c = (i/10.00).intValue(),
                    Hour__c = Math.mod(i, 24)
            );
            dfpActuals.add(actual);
        }
        insert dfpActuals;

        System.assertEquals(1240, [Select Id from CS_DFP_Actuals_By_Hour_Report_Data__c].size());
        Test.startTest();

        CS_BatchDeleteReportData batchWorker = new CS_BatchDeleteReportData();
        batchWorker.execute();

        Test.stopTest();

        System.assertEquals(240, [Select Id from CS_DFP_Actuals_By_Hour_Report_Data__c].size());
    }
}