unpackaged/main/default/objects/MarketingEmailHistoryTracker__c/MarketingEmailHistoryTracker__c.object-meta.xml
<CustomObject>
    <label>MarketingEmailHistoryTracker</label>
    <nameField>
        <displayFormat>MCH-{0000000}</displayFormat>
        <label>MarketingEmailHistoryTracker Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>MarketingEmailHistoryTracker</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/MarketingEmailHistoryTracker__c/fields/CampaignName__c.field-meta.xml
<CustomField>
    <fullName>CampaignName__c</fullName>
    <label>CampaignName</label>
    <type>TextArea</type>
</CustomField>

unpackaged/main/default/objects/MarketingEmailHistoryTracker__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>MarketingEmailHistoryTracker</relationshipLabel>
    <relationshipName>MarketingEmailHistoryTracker</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/MarketingEmailHistoryTracker__c/fields/DateTimeSent__c.field-meta.xml
<CustomField>
    <fullName>DateTimeSent__c</fullName>
    <label>DateTimeSent</label>
    <type>DateTime</type>
</CustomField>

unpackaged/main/default/objects/MarketingEmailHistoryTracker__c/fields/EmailName__c.field-meta.xml
<CustomField>
    <fullName>EmailName__c</fullName>
    <label>EmailName</label>
    <length>400</length>
    <type>LongTextArea</type>
</CustomField>

unpackaged/main/default/objects/MarketingEmailHistoryTracker__c/fields/OriginalURL__c.field-meta.xml
<CustomField>
    <fullName>OriginalURL__c</fullName>
    <label>OriginalURL</label>
    <type>Url</type>
</CustomField>

unpackaged/main/default/objects/MarketingEmailHistoryTracker__c/fields/PermURL__c.field-meta.xml
<CustomField>
    <fullName>PermURL__c</fullName>
    <label>PermURL</label>
    <type>Url</type>
</CustomField>

unpackaged/main/default/classes/MarketingEmailHistoryDisplayClass.cls
public class MarketingEmailHistoryDisplayClass {

    @AuraEnabled
    public static List<MarketingEmailHistoryTracker__c> getMarketingEmail(String accId){
       List<MarketingEmailHistoryTracker__c> merketingList = new List<MarketingEmailHistoryTracker__c>();
        merketingList = [SELECT Id, CreatedDate, EmailName__c, DateTimeSent__c, CampaignName__c, OriginalURL__c, PermURL__c, Contact__c FROM MarketingEmailHistoryTracker__c where Contact__r.AccountId = : accId and PermURL__c!=null  order by DateTimeSent__c desc];
        system.debug('merketingList$$$ '+merketingList);
        system.debug('merketingListSize '+merketingList.size());
        return merketingList;
       
    }
    @AuraEnabled
    public static String getHtmlEmailContent(String mId){
        system.debug('--mId--'+mId);
        if(Test.isRunningTest()){
            return 'test http';
        }
        return readFileFromAwsClass.getContentFromAws(mId).replace('http','https');
    }
}