unpackaged/main/default/objects/Account/fields/AA_Completed_Date__c.field-meta.xml
<CustomField>
    <fullName>AA_Completed_Date__c</fullName>
    <label>AA Completed Date</label>
    <type>DateTime</type>
</CustomField>

unpackaged/main/default/objects/Purge_Batch_Job__c/Purge_Batch_Job__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>Purge Batch Job</label>
</CustomObject>

unpackaged/main/default/objects/Purge_Batch_Job__c/fields/Date_Filter__c.field-meta.xml
<CustomField>
    <fullName>Date_Filter__c</fullName>
    <defaultValue>&quot;CreatedDate&quot;</defaultValue>
    <description>API field name used in the query.</description>
    <inlineHelpText>API field name used in the query.</inlineHelpText>
    <label>Date Filter</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Purge_Batch_Job__c/fields/Number_of_Days_To_Purge__c.field-meta.xml
<CustomField>
    <fullName>Number_of_Days_To_Purge__c</fullName>
    <description>Specify the age in days of records to purge. Anything older than the the days specified will be removed.</description>
    <inlineHelpText>Specify the age in days of records to purge. Anything older than the the days specified will be removed.</inlineHelpText>
    <label>Number of Days To Purge</label>
    <precision>4</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/Purge_Batch_Job__c/fields/Object_API_Name__c.field-meta.xml
<CustomField>
    <fullName>Object_API_Name__c</fullName>
    <description>Name of the objects that will be processed by the Purge Batch job</description>
    <inlineHelpText>Name of the objects that will be processed by the Purge Batch job</inlineHelpText>
    <label>Object API Name</label>
    <length>50</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

unpackaged/main/default/classes/PurgeDataSchedulerTest.cls
@IsTest
private class PurgeDataSchedulerTest {
    
    /*method to test for single records in object */
    @IsTest
    static void testpurgeData_Single(){
        
        List<Purge_Batch_Job__c> objList = new List<Purge_Batch_Job__c>();
        
        csam__Incoming_Message__c inMsg = new csam__Incoming_Message__c(Name = 'testinmsg', csam__HTTP_Method__c = 'test');
        insert inMsg;
        
        csam__Outgoing_Message__c outMsg= new csam__Outgoing_Message__c(Name = 'testoutmsg', csam__Content_Type__c = 'testtype', csam__URL_Host__c = 'testhost');
        insert outMsg;
        
        Purge_Batch_Job__c pb = new Purge_Batch_Job__c();
        pb.Name = 'testName';
        pb.Object_API_Name__c = 'csam__Incoming_Message__c';
        pb.Number_of_Days_To_Purge__c = 0;
        objList.add(pb);
        
        Purge_Batch_Job__c pb1 = new Purge_Batch_Job__c();
        pb1.Name = 'testName1';
        pb1.Object_API_Name__c = 'csam__Outgoing_Message__c';
        pb1.Number_of_Days_To_Purge__c = 0;
        objList.add(pb1);
        insert objList;
        
        Test.startTest();
        PurgeDataScheduler.scheduleIt();
        Test.stopTest();
    }
    
    /*method to test for bulk records with multiple objects */
    @IsTest
    static void testpurgeData_Bulk(){
        List<csam__Incoming_Message__c> inMsgs = TestDataSetupTargetables.createInMsgs(100);
        TestDataSetupTargetables.createCSCustomSettings();
        TestDataSetupTargetables.createPurgeBatchJob();
        Test.startTest();
        PurgeDataScheduler.scheduleIt();
        Test.stopTest();
    }

    @IsTest
    static void purge_batchExecuteTest()
    {
        Account a = TestDataSetupTargetables.createAccount();
        a.AA_Completed_Date__c = Date.today().addDays(-2);
        insert a;

        Purge_Batch_Job__c pb1 = new Purge_Batch_Job__c();
        pb1.Name = 'testName1';
        pb1.Date_Filter__c = 'AA_Completed_Date__c';
        pb1.Object_API_Name__c = 'Account';
        pb1.Number_of_Days_To_Purge__c = 0;
        insert pb1;

        List<String> scope = new List<String>();
        scope.add(a.Id);

        Test.startTest();
        PurgeDataBatch batch = new PurgeDataBatch();
        Database.executeBatch( batch );
        Test.stopTest();
        
        Account[] accs = [SELECT Id FROM Account WHERE Id = :a.Id];
        System.assert(accs.size() == 0);
    }
}