unpackaged/main/default/objects/Account/fields/Account_Rule_Code__c.field-meta.xml
<CustomField>
    <fullName>Account_Rule_Code__c</fullName>
    <defaultValue>IF( $RecordType.DeveloperName = &quot;Agent&quot;, &quot;TRIAL&quot;, &quot;&quot;)</defaultValue>
    <description>Denotes account rule code (short text) for the account rule</description>
    <inlineHelpText>Denotes account rule code (short text) for the account rule</inlineHelpText>
    <label>Account Rule Code</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/AgentNet_ID__c.field-meta.xml
<CustomField>
    <fullName>AgentNet_ID__c</fullName>
    <description>Denotes a numeric id of agents in PG system</description>
    <inlineHelpText>Denotes a numeric id of agents in PG system</inlineHelpText>
    <label>AgentNet ID</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/CEA_Salesperson_Number__c.field-meta.xml
<CustomField>
    <fullName>CEA_Salesperson_Number__c</fullName>
    <description>Denotes the agent license number registered under a governing authority</description>
    <inlineHelpText>Denotes the agent registration number issued by CEA for SG agents and MIEA for MY agents</inlineHelpText>
    <label>Agent Identification Number</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/Commando_Sales_Rep__c.field-meta.xml
<CustomField>
    <fullName>Commando_Sales_Rep__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Commando Sales Rep</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Accounts1</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/Country__c.field-meta.xml
<CustomField>
    <fullName>Country__c</fullName>
    <defaultValue>if(  BEGINS($UserRole.Name, &quot;TH&quot;),&quot;Thailand&quot;,if(ISPICKVAL($User.Subsidiary__c,&quot;MyProperty Data Sdn. Bhd.&quot;),&quot;Malaysia&quot;,&quot;&quot;))</defaultValue>
    <description>Denotes the country of an account</description>
    <inlineHelpText>Denotes the country of an account</inlineHelpText>
    <label>Country</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Country</valueSetName>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Account/fields/Current_Subscription__c.field-meta.xml
<CustomField>
    <fullName>Current_Subscription__c</fullName>
    <label>Current Subscription</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/Current_Subscription_Code__c.field-meta.xml
<CustomField>
    <fullName>Current_Subscription_Code__c</fullName>
    <label>Current Subscription Code</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/Customer_Type__c.field-meta.xml
<CustomField>
    <fullName>Customer_Type__c</fullName>
    <description>Created a custom field as standard field &#39;Type&#39; cannot be mapped in lead mapping</description>
    <label>Customer Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Agent</fullName>
            </value>
            <value>
                <fullName>Owner</fullName>
            </value>
            <value>
                <fullName>Agency</fullName>
            </value>
            <value>
                <fullName>Developer</fullName>
                <default>true</default>
                <label>Developer</label>
            </value>
            <value>
                <fullName>Non-Property</fullName>
            </value>
            <value>
                <fullName>Consumer</fullName>
            </value>
            <value>
                <fullName>Media Agency</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Account/fields/PG_Tenure__c.field-meta.xml
<CustomField>
    <fullName>PG_Tenure__c</fullName>
    <description>Denotes tenure of an agent with PG</description>
    <formula>IF(OR(ISPICKVAL(Country__c, &#39;Malaysia&#39;),ISPICKVAL(Country__c, &#39;Thailand&#39;)),
FLOOR(
(((Year(Subscription_End_Date__c)-Year(Loyalty_Start_Date__c))*12 + (IF(IF(MONTH(Subscription_End_Date__c)+1&gt;12,MONTH(Subscription_End_Date__c)+1-12,
MONTH(Subscription_End_Date__c)+1)=MONTH(Loyalty_Start_Date__c),MONTH(Subscription_End_Date__c)+1-MONTH(Loyalty_Start_Date__c),
MONTH(Subscription_End_Date__c)-MONTH(Loyalty_Start_Date__c))))/12)),
IF(ISPICKVAL(Country__c, &#39;Singapore&#39;),
FLOOR((((Year(Subscription_End_Date__c)-Year(Loyalty_Start_Date__c))*12 + (IF(IF(MONTH(Subscription_End_Date__c)+1&gt;12,MONTH(Subscription_End_Date__c)+1-12,
MONTH(Subscription_End_Date__c)+1)=MONTH(Loyalty_Start_Date__c),MONTH(Subscription_End_Date__c)+1-MONTH(Loyalty_Start_Date__c),
MONTH(Subscription_End_Date__c)-MONTH(Loyalty_Start_Date__c))))/12)),1)
)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>PG Tenure is calculated as Subscription End Date minus Loyalty Start Date</inlineHelpText>
    <label>PG Tenure</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>Denotes the status of an agent in the agent lifecycle</description>
    <inlineHelpText>Denotes the status of an agent in the agent lifecycle</inlineHelpText>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Trial</fullName>
            </value>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Downgraded</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Suspended</fullName>
            </value>
            <value>
                <fullName>Expired</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Account/fields/Subscription_End_Date__c.field-meta.xml
<CustomField>
    <fullName>Subscription_End_Date__c</fullName>
    <description>Denotes end date of an agent&#39;s current subscriptions</description>
    <inlineHelpText>Denotes end date of an agent&#39;s current subscriptions</inlineHelpText>
    <label>Subscription End Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/Subscription_Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Subscription_Start_Date__c</fullName>
    <description>Denotes the start date of agent&#39;s current subscription</description>
    <inlineHelpText>Denotes the start date of agent&#39;s current subscription</inlineHelpText>
    <label>Subscription Start Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/Subsidiary__c.field-meta.xml
<CustomField>
    <fullName>Subsidiary__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Denotes the PG subsidiary to which the account belongs to</description>
    <inlineHelpText>Denotes the PG subsidiary to which the account belongs to</inlineHelpText>
    <label>Subsidiary</label>
    <referenceTo>Subsidiary__c</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/Total_Spending__c.field-meta.xml
<CustomField>
    <fullName>Total_Spending__c</fullName>
    <defaultValue>0</defaultValue>
    <inlineHelpText>This is total spending on Discretionary Products</inlineHelpText>
    <label>Total Spending</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/VIP__c.field-meta.xml
<CustomField>
    <fullName>VIP__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Flag to denote if agent is VIP</description>
    <inlineHelpText>Flag to denote if agent is VIP</inlineHelpText>
    <label>VIP</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Account/recordTypes/Agency.recordType-meta.xml
<RecordType>
    <fullName>Agency</fullName>
    <active>true</active>
    <label>Agency</label>
</RecordType>

unpackaged/main/default/objects/Opportunity/fields/Account_Rule_Code__c.field-meta.xml
<CustomField>
    <fullName>Account_Rule_Code__c</fullName>
    <label>Account Rule Code</label>
    <length>15</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Country__c.field-meta.xml
<CustomField>
    <fullName>Country__c</fullName>
    <formula>TEXT(Subsidiary__r.Country__c )</formula>
    <label>Country</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Months_Included__c.field-meta.xml
<CustomField>
    <fullName>Months_Included__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Included in Total Spending 12 months or not</description>
    <label>Months Included</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/PG_Tenure__c.field-meta.xml
<CustomField>
    <fullName>PG_Tenure__c</fullName>
    <label>PG Tenure</label>
    <precision>4</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Product_Category__c.field-meta.xml
<CustomField>
    <fullName>Product_Category__c</fullName>
    <label>Product Category</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Awards</fullName>
            </value>
            <value>
                <fullName>China Solutions</fullName>
            </value>
            <value>
                <fullName>Events</fullName>
            </value>
            <value>
                <fullName>Agent Discretionary</fullName>
            </value>
            <value>
                <fullName>Agent Subscriptions</fullName>
            </value>
            <value>
                <fullName>Developer Listings</fullName>
            </value>
            <value>
                <fullName>Online Advertising</fullName>
            </value>
            <value>
                <fullName>Marketing Services</fullName>
            </value>
            <value>
                <fullName>Database Marketing</fullName>
            </value>
            <value>
                <fullName>Content</fullName>
            </value>
            <value>
                <fullName>FinTech</fullName>
            </value>
            <value>
                <fullName>FastKey</fullName>
            </value>
            <value>
                <fullName>Data MPD</fullName>
            </value>
            <value>
                <fullName>Discretionary</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Subscription_End_Date__c.field-meta.xml
<CustomField>
    <fullName>Subscription_End_Date__c</fullName>
    <label>Subscription End Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Subsidiary__c.field-meta.xml
<CustomField>
    <fullName>Subsidiary__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Subsidiary</label>
    <referenceTo>Subsidiary__c</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Total_Spending__c.field-meta.xml
<CustomField>
    <fullName>Total_Spending__c</fullName>
    <label>Total Spending (last 12 months)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/recordTypes/B2B.recordType-meta.xml
<RecordType>
    <fullName>B2B</fullName>
    <active>true</active>
    <businessProcess>B2B</businessProcess>
    <description>B2B Opportunity Record</description>
    <label>B2B</label>
</RecordType>

unpackaged/main/default/objects/Opportunity/recordTypes/B2C.recordType-meta.xml
<RecordType>
    <fullName>B2C</fullName>
    <active>true</active>
    <businessProcess>B2C</businessProcess>
    <description>B2C Opportunity Record</description>
    <label>B2C</label>
</RecordType>

unpackaged/main/default/objects/Product2/fields/Product_Category__c.field-meta.xml
<CustomField>
    <fullName>Product_Category__c</fullName>
    <description>Denotes the category of B2C products</description>
    <inlineHelpText>Denotes the category of B2C products</inlineHelpText>
    <label>Product Category</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Subscription</fullName>
            </value>
            <value>
                <fullName>Discretionary</fullName>
            </value>
            <value>
                <fullName>Repost</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Product2/fields/Segment__c.field-meta.xml
<CustomField>
    <fullName>Segment__c</fullName>
    <description>Denotes the business segment</description>
    <inlineHelpText>Denotes the business segment</inlineHelpText>
    <label>Segment</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>B2B Only</fullName>
            </value>
            <value>
                <fullName>B2C Only</fullName>
            </value>
            <value>
                <fullName>B2B &amp; B2C</fullName>
            </value>
            <value>
                <fullName>[object Object]</fullName>
                <isActive>false</isActive>
                <label>[object Object]</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Product2/fields/SKU_Code__c.field-meta.xml
<CustomField>
    <fullName>SKU_Code__c</fullName>
    <description>Denotes the unique code of product</description>
    <inlineHelpText>Denotes the unique code of product</inlineHelpText>
    <label>SKU Code</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Product2/fields/Subsidiary__c.field-meta.xml
<CustomField>
    <fullName>Subsidiary__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Denotes the PG subsidiary to which the product belongs to</description>
    <inlineHelpText>Denotes the PG subsidiary to which the product belongs to</inlineHelpText>
    <label>Subsidiary</label>
    <referenceTo>Subsidiary__c</referenceTo>
    <relationshipLabel>Products</relationshipLabel>
    <relationshipName>Products</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Subsidiary__c/Subsidiary__c.object-meta.xml
<CustomObject>
    <description>This is a custom object to contain the information on Subsidiary and Country</description>
    <label>Subsidiary</label>
    <nameField>
        <label>Subsidiary Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Subsidiaries</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Subsidiary__c/fields/Country__c.field-meta.xml
<CustomField>
    <fullName>Country__c</fullName>
    <description>Values from global picklist</description>
    <label>Country</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Country</valueSetName>
    </valueSet>
</CustomField>

unpackaged/main/default/classes/OpportunityRenewal_Batch_Test.cls
@isTest
public class OpportunityRenewal_Batch_Test {
    /*
* Created by : Yuni
* Company    : Viseo Asia PTE LTD
* created Date : 27/07/2018
*/
    
    static testMethod void runTest() {
        Test.StartTest();
        id subId = PGTestDataFactory.createSubsidiary().Id;
        PGTestDataFactory_v2.initSetupData();
        
        string accRectypeB2B = Schema.SObjectType.Account.getRecordTypeInfosByName().get('B2B - Account').getRecordTypeId();
        Account aB2B = new Account();
        aB2B.RecordTypeId = accRectypeB2B;
        aB2B.Name = 'Unit Test Agency';
        aB2B.Customer_Type__c = 'Developer';
        aB2B.BillingStreet = 'test street';
        aB2B.BillingCity = 'city';
        aB2B.BillingCountry = 'Singapore';
        aB2B.BillingPostalCode = '8373';
       // a.BillingState = 'test';
        aB2B.Country__c = 'Singapore';
        insert aB2B;
        
        string accRectype = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Agent').getRecordTypeId();        
        Account a = new Account();
        a.RecordTypeId = accRectype;
        a.LastName = 'TestYuni';
        a.CurrencyIsoCode = 'SGD';
        a.Subscription_Start_Date__c = system.today().addMonths(-10);
        a.BillingStreet = 'test';
        a.BillingCity = 'test';
        a.BillingCountry = 'Singapore';
        a.BillingPostalCode = '8373';
        a.CEA_Salesperson_Number__c='12345';
       // a.BillingState = 'Singapore';
        a.Current_Subscription__c = 'Advance';
        a.Current_Subscription_Code__c = 'abc';
        a.Subscription_End_Date__c = system.today();
        a.account_rule_code__c = 'Standard';
        a.personemail = 'alkjha@yaho.com';
        a.salutation = 'Mr.';
        a.firstname = 'aaaa';
        a.PersonBirthdate= Date.newInstance(2016, 12, 9);
        a.Country__c = 'Singapore';
        a.Subsidiary__c = subId;
        a.Status__c = 'Active';
        a.Commando_Sales_Rep__c = UserInfo.getUserId();
        insert a;

        Account ac = new Account();
        ac.RecordTypeId = accRectype;
        ac.LastName = 'TestYuni';
        ac.AgentNet_ID__c = 'TestPurposeId';
        ac.CurrencyIsoCode = 'SGD';
        ac.Subscription_Start_Date__c = system.today().addMonths(-10);
        ac.Subscription_End_Date__c = system.today().addMonths(1);
        ac.BillingStreet = 'test';
        ac.BillingCity = 'test';
        ac.BillingCountry = 'Singapore';
        ac.BillingPostalCode = '83713';
      //  ac.BillingState = 'test';
        ac.Current_Subscription__c = 'Premier';
        ac.Current_Subscription_Code__c = 'abc';
        ac.account_rule_code__c = 'Standard';
        ac.personemail = 'a1213axy@yaho.com';
        ac.salutation = 'Mr.';
        ac.firstname = 'aaaa';
        ac.Country__c = 'Malaysia';
        ac.Subsidiary__c = subId;
        ac.Status__c = 'Active';
        ac.Commando_Sales_Rep__c = UserInfo.getUserId();
        ac.VIP__c = true;
        ac.CEA_Salesperson_Number__c = '123456';
        ac.PersonBirthdate= Date.newInstance(2016, 12, 9);
        insert ac;
         
        Opportunity opp = new opportunity();
        opp.Name = 'Test Opp';
        opp.StageName = 'Prospecting';
        opp.AccountId = aB2B.id;
        opp.CloseDate = system.today().AddDays(30);
        opp.PG_Tenure__c = 4;
        opp.Total_Spending__c = 100;
        opp.Months_Included__c = true;
        opp.Subsidiary__c = subId;
        insert opp;
        
        Product2 prod = new Product2(Name = 'Test Prod', IsActive = true, Segment__c = 'B2C Only', Product_Category__c = 'Subscription', SKU_Code__c = 'abc');
        insert prod;
        
        Id StdpricebookId = Test.getStandardPricebookId();
        
        PricebookEntry pbe = new PricebookEntry(pricebook2id=StdpricebookId, product2id=prod.id,unitprice=100.0, isActive=true);
        insert pbe; 
        
        OpportunityLineItem oplineItem = new OpportunityLineItem();
        oplineItem.OpportunityId = opp.id;
        oplineItem.Product2Id = prod.id;
        oplineItem.PricebookEntryId = pbe.id;
        oplineItem.Quantity = 2;
        oplineItem.UnitPrice = 1200;
        insert oplineItem;
        
        OpportunityRenewal_Batch obj = new OpportunityRenewal_Batch();
        Database.executeBatch(obj);
        Test.stopTest();

       /* //AccountAssignment_BatchSchedulable sh1 = new AccountAssignment_BatchSchedulable();      
        String sch = '0 0 0 * * ? *';
        // system.schedule('Test Schedule', sch, sh1);
        
        
        OpportunityRenewal_BatchSchedulable orbs = new OpportunityRenewal_BatchSchedulable();      
        sch = '0 0 0 * * ? *';
        system.schedule('Test Schedule Renewal', sch, orbs);
        */
    }
    
}