unpackaged/main/default/objects/Account/fields/Account_Rule_Code__c.field-meta.xml
<CustomField>
    <fullName>Account_Rule_Code__c</fullName>
    <defaultValue>IF( $RecordType.DeveloperName = &quot;Agent&quot;, &quot;TRIAL&quot;, &quot;&quot;)</defaultValue>
    <description>Denotes account rule code (short text) for the account rule</description>
    <inlineHelpText>Denotes account rule code (short text) for the account rule</inlineHelpText>
    <label>Account Rule Code</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/Agency__c.field-meta.xml
<CustomField>
    <fullName>Agency__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Denotes the real estate/property agency to which the agent belongs to</description>
    <inlineHelpText>Denotes the real estate/property agency to which the agent belongs to</inlineHelpText>
    <label>Agency</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>Please select proper Agency Account.</errorMessage>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Agency</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Agents</relationshipLabel>
    <relationshipName>Agency</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/Agency_Id__c.field-meta.xml
<CustomField>
    <fullName>Agency_Id__c</fullName>
    <description>Denotes the unique id of an agency in PG system</description>
    <externalId>true</externalId>
    <inlineHelpText>Denotes the unique id of an agency in PG system</inlineHelpText>
    <label>Agency Id</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/AgentNet_ID__c.field-meta.xml
<CustomField>
    <fullName>AgentNet_ID__c</fullName>
    <description>Denotes a numeric id of agents in PG system</description>
    <inlineHelpText>Denotes a numeric id of agents in PG system</inlineHelpText>
    <label>AgentNet ID</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/CEA_License__c.field-meta.xml
<CustomField>
    <fullName>CEA_License__c</fullName>
    <description>Denotes the agency license number registered under a governing authority</description>
    <externalId>true</externalId>
    <inlineHelpText>Denotes the agency registration number issued by CEA for SG agencies and MIEA for MY agencies</inlineHelpText>
    <label>Agency Identification Number</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/Country__c.field-meta.xml
<CustomField>
    <fullName>Country__c</fullName>
    <defaultValue>if(  BEGINS($UserRole.Name, &quot;TH&quot;),&quot;Thailand&quot;,if(ISPICKVAL($User.Subsidiary__c,&quot;MyProperty Data Sdn. Bhd.&quot;),&quot;Malaysia&quot;,&quot;&quot;))</defaultValue>
    <description>Denotes the country of an account</description>
    <inlineHelpText>Denotes the country of an account</inlineHelpText>
    <label>Country</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Country</valueSetName>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Account/fields/Current_Subscription_Code__c.field-meta.xml
<CustomField>
    <fullName>Current_Subscription_Code__c</fullName>
    <label>Current Subscription Code</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/Customer_Type__c.field-meta.xml
<CustomField>
    <fullName>Customer_Type__c</fullName>
    <description>Created a custom field as standard field &#39;Type&#39; cannot be mapped in lead mapping</description>
    <label>Customer Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Agent</fullName>
            </value>
            <value>
                <fullName>Owner</fullName>
            </value>
            <value>
                <fullName>Agency</fullName>
            </value>
            <value>
                <fullName>Developer</fullName>
                <default>true</default>
                <label>Developer</label>
            </value>
            <value>
                <fullName>Non-Property</fullName>
            </value>
            <value>
                <fullName>Consumer</fullName>
            </value>
            <value>
                <fullName>Media Agency</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Account/fields/Subscription_Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Subscription_Start_Date__c</fullName>
    <description>Denotes the start date of agent&#39;s current subscription</description>
    <inlineHelpText>Denotes the start date of agent&#39;s current subscription</inlineHelpText>
    <label>Subscription Start Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/Subsidiary__c.field-meta.xml
<CustomField>
    <fullName>Subsidiary__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Denotes the PG subsidiary to which the account belongs to</description>
    <inlineHelpText>Denotes the PG subsidiary to which the account belongs to</inlineHelpText>
    <label>Subsidiary</label>
    <referenceTo>Subsidiary__c</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Account/recordTypes/Agency.recordType-meta.xml
<RecordType>
    <fullName>Agency</fullName>
    <active>true</active>
    <label>Agency</label>
</RecordType>

unpackaged/main/default/objects/Case/fields/CEA_License__c.field-meta.xml
<CustomField>
    <fullName>CEA_License__c</fullName>
    <description>Denotes the CEA license number of the agent</description>
    <inlineHelpText>Denotes the CEA license number of the agent</inlineHelpText>
    <label>Agent Identification Number</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Case/fields/Country__c.field-meta.xml
<CustomField>
    <fullName>Country__c</fullName>
    <label>Country</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Singapore</fullName>
            </value>
            <value>
                <fullName>Malaysia</fullName>
            </value>
            <value>
                <fullName>Thailand</fullName>
            </value>
            <value>
                <fullName>Indonesia</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Case/recordTypes/Case.recordType-meta.xml
<RecordType>
    <fullName>Case</fullName>
    <active>true</active>
    <businessProcess>Case</businessProcess>
    <label>Case</label>
</RecordType>

unpackaged/main/default/objects/Case/recordTypes/Sales_Enablement.recordType-meta.xml
<RecordType>
    <fullName>Sales_Enablement</fullName>
    <active>true</active>
    <businessProcess>Sales Enablement</businessProcess>
    <description>To support sales enablement inquiries from Sales Teams both B2B and B2C</description>
    <label>Sales Enablement</label>
</RecordType>

unpackaged/main/default/objects/Field_Mapping__c/Field_Mapping__c.object-meta.xml
<CustomObject>
    <label>Field Mapping</label>
    <nameField>
        <displayFormat>fm-{0000}</displayFormat>
        <label>Field Mapping Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Field Mappings</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Field_Mapping__c/fields/DataType__c.field-meta.xml
<CustomField>
    <fullName>DataType__c</fullName>
    <label>DataType</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Text</fullName>
            </value>
            <value>
                <fullName>Number</fullName>
            </value>
            <value>
                <fullName>Date</fullName>
            </value>
            <value>
                <fullName>Picklist</fullName>
            </value>
            <value>
                <fullName>Checkbox</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Field_Mapping__c/fields/from__c.field-meta.xml
<CustomField>
    <fullName>from__c</fullName>
    <label>From</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Field_Mapping__c/fields/Instance_Name__c.field-meta.xml
<CustomField>
    <fullName>Instance_Name__c</fullName>
    <label>Instance Name</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>PG</fullName>
            </value>
            <value>
                <fullName>iPP</fullName>
            </value>
            <value>
                <fullName>Both</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Field_Mapping__c/fields/recordCreation__c.field-meta.xml
<CustomField>
    <fullName>recordCreation__c</fullName>
    <defaultValue>false</defaultValue>
    <label>recordCreation</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Field_Mapping__c/fields/Search_Data__c.field-meta.xml
<CustomField>
    <fullName>Search_Data__c</fullName>
    <label>Search Data</label>
    <referenceTo>Search_and_tag_admin__c</referenceTo>
    <relationshipLabel>Field Mappings</relationshipLabel>
    <relationshipName>Field_Mappings</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/Field_Mapping__c/fields/Sequennce__c.field-meta.xml
<CustomField>
    <fullName>Sequennce__c</fullName>
    <label>Sequennce</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/Search_and_tag_admin__c/Search_and_tag_admin__c.object-meta.xml
<CustomObject>
    <label>Search And Tag</label>
    <nameField>
        <label>Search Data Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Search and tags</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Search_and_tag_admin__c/fields/active__c.field-meta.xml
<CustomField>
    <fullName>active__c</fullName>
    <defaultValue>false</defaultValue>
    <label>active</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Search_and_tag_admin__c/fields/Client__c.field-meta.xml
<CustomField>
    <fullName>Client__c</fullName>
    <label>ClientSecret</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Search_and_tag_admin__c/fields/Destination_Object_API__c.field-meta.xml
<CustomField>
    <fullName>Destination_Object_API__c</fullName>
    <label>Destination Object API</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Search_and_tag_admin__c/fields/Destination_Recordtype_Id__c.field-meta.xml
<CustomField>
    <fullName>Destination_Recordtype_Id__c</fullName>
    <label>Destination Recordtype Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Search_and_tag_admin__c/fields/password__c.field-meta.xml
<CustomField>
    <fullName>password__c</fullName>
    <label>password</label>
    <length>175</length>
    <maskChar>asterisk</maskChar>
    <maskType>all</maskType>
    <type>EncryptedText</type>
</CustomField>

unpackaged/main/default/objects/Search_and_tag_admin__c/fields/Search_Field__c.field-meta.xml
<CustomField>
    <fullName>Search_Field__c</fullName>
    <label>Search Field</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

unpackaged/main/default/objects/Search_and_tag_admin__c/fields/Source_Object_API__c.field-meta.xml
<CustomField>
    <fullName>Source_Object_API__c</fullName>
    <label>Source Object API</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Search_and_tag_admin__c/fields/Source_RecordTypeID__c.field-meta.xml
<CustomField>
    <fullName>Source_RecordTypeID__c</fullName>
    <label>Source RecordTypeID</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Subsidiary__c/Subsidiary__c.object-meta.xml
<CustomObject>
    <description>This is a custom object to contain the information on Subsidiary and Country</description>
    <label>Subsidiary</label>
    <nameField>
        <label>Subsidiary Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Subsidiaries</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Subsidiary__c/fields/Country__c.field-meta.xml
<CustomField>
    <fullName>Country__c</fullName>
    <description>Values from global picklist</description>
    <label>Country</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Country</valueSetName>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Subsidiary__c/fields/Logo_url__c.field-meta.xml
<CustomField>
    <fullName>Logo_url__c</fullName>
    <label>Logo url</label>
    <type>Url</type>
</CustomField>

unpackaged/main/default/objects/Subsidiary__c/fields/NS_Subsidiary_Internal_ID__c.field-meta.xml
<CustomField>
    <fullName>NS_Subsidiary_Internal_ID__c</fullName>
    <description>NetSuite record internal ID</description>
    <externalId>true</externalId>
    <label>NS Subsidiary Internal ID</label>
    <length>20</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

unpackaged/main/default/objects/Subsidiary__c/fields/Tax_Label__c.field-meta.xml
<CustomField>
    <fullName>Tax_Label__c</fullName>
    <description>This label is used in the Print Contract PDF to display tax</description>
    <inlineHelpText>GST | VAT</inlineHelpText>
    <label>Tax Label</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Trigger_Execute__c/Trigger_Execute__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>Trigger Execute</label>
</CustomObject>

unpackaged/main/default/objects/Trigger_Execute__c/fields/Enable_del__c.field-meta.xml
<CustomField>
    <fullName>Enable_del__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Enable del</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/User/fields/Subsidiary__c.field-meta.xml
<CustomField>
    <fullName>Subsidiary__c</fullName>
    <label>Subsidiary</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Subsidiary</valueSetName>
    </valueSet>
</CustomField>

unpackaged/main/default/classes/TagUnTagCase_cc_Test.cls
@istest
public class TagUnTagCase_cc_Test {
    public static testmethod void TagUnTagCase() {
        
        Trigger_Execute__c TEAccMember = new Trigger_Execute__c();
        TEAccMember.Name = 'PGAccountTrigger';
        TEAccMember.Enable_del__c = true;
        insert TEAccMember;
        
        Trigger_Execute__c TECase = new Trigger_Execute__c();
        TECase.Name = 'PGCaseTrigger';
        TECase.Enable_del__c = true;
        insert TECase;
        
        string accRectype = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Agent').getRecordTypeId();
        Profile p = [SELECT Id FROM Profile WHERE Name='System Administrator']; 
        User u = new User(Alias = 'standt', Email='syncorg@m.com', 
                          EmailEncodingKey='UTF-8', LastName='Testing', LanguageLocaleKey='en_US',country ='Malaysia', 
                          LocaleSidKey='en_US', ProfileId = p.Id, Subsidiary__c ='PropertyGuru International (Malaysia) Sdn Bhd',
                          TimeZoneSidKey='America/Los_Angeles', UserName='syncorg@m.com');
        insert u;
        subsidiary__c sb = new Subsidiary__c();
        sb.Name = u.Subsidiary__c;
        sb.NS_Subsidiary_Internal_ID__c = '1';
        sb.CurrencyIsoCode = 'SGD';
        sb.Tax_Label__c = 'taxLabel';
        sb.Country__c = 'Malaysia';
        sb.Logo_url__c='https://c.ap5.visual.force.com/resource/1525687701000/SG_Sales_Order_Header_v3_PGG';
        insert sb;
        System.runAs(u){
            Search_and_tag_admin__c sd1 = new Search_and_tag_admin__c(Destination_Object_API__c ='Account',Client__c='test',ClientID__c='test',
                                                                      Source_Object_API__c ='Account',UserName__c='test',password__c='test',Search_Field__c='Name,Id,Country__c',
                                                                      EndPoint__c='test.com',Source_RecordTypeID__c = accRectype,
                                                                      Destination_Recordtype_Id__c = accRectype,active__c=true);
            insert sd1;
            
            Field_Mapping__c fieldMap1 = new Field_Mapping__c();
            fieldMap1.CurrencyIsoCode = 'SGD';
            fieldMap1.isActive__c = True; 
            fieldMap1.Search_Data__c = sd1.id;
            fieldMap1.Instance_Name__c = 'Both';
            fieldMap1.Label__c = 'Name';    
            fieldMap1.from__c = 'name';
            fieldMap1.To__c = 'Name';
            fieldMap1.Sequennce__c = 50;
            fieldMap1.DataType__c = 'text'; 
            fieldMap1.recordCreation__c = True;
            insert fieldMap1;
            
            Account agency = new Account();
            PGTestDataFactory_v2.initSetupData();
            agency.name = 'Unit Test Agency';
            agency.Agency_Id__c = '40574';
            agency.CEA_License__c = 'CEAUNittest1';
            agency.RecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Agency').getRecordTypeId();
            agency.Country__c = 'Malaysia';
            agency.Subsidiary__c = sb.Id;
            
            insert  agency;  
            
            Account a = new Account();
            a.RecordTypeId = accRectype;
            a.LastName = 'TestYuni';
            a.Agency__c = agency.Id;
            //a.Customer_Type__c = 'Agency';
            a.CurrencyIsoCode = 'SGD';
            a.AgentNet_ID__c = 'TestPurposeIdXX';
            a.Subscription_Start_Date__c = system.today().addMonths(-10);
            a.BillingStreet = 'test';
            a.BillingCity = 'test';
            a.BillingCountry = 'Malaysia';
            a.BillingPostalCode = '83173';
            // a.BillingState = 'test';
            a.Current_Subscription_Code__c = 'abc';
            a.account_rule_code__c = 'Standard';
            a.personemail = 'asd131sfaa@yaho.com';
            a.salutation = 'Mr.';
            a.firstname = 'aaaa';
            a.Country__c = 'Malaysia'; 
            a.Status__c = 'Active';
            a.NetSuite_Id__c = '6777';
            a.CEA_Salesperson_Number__c = 'W567653H';
            a.External_field__c = '867685777';
            a.Overlap_Agent__c = true;
            a.PersonBirthdate=system.today();
            a.Brickz_Agent__c = true;
            a.Mobile_Country__c='65';
            insert a;
             
            Case caseObj = new Case();
            caseObj.RecordTypeId =Schema.SObjectType.Case.getRecordTypeInfosByDeveloperName().get('Sales_Enablement').getRecordTypeId();
            caseObj.Status = 'New';
            caseObj.Subject = 'Tag overlapping agent';
            caseObj.accountid = a.id;
            caseObj.Account_Temp_ExternalField__c = a.id;
            insert caseObj;
            
            Account a1 = new Account();
            a1.RecordTypeId = accRectype;
            a1.LastName = 'TestYuni';
            a1.Agency__c = agency.Id;
            //a.Customer_Type__c = 'Agency';
            a1.CurrencyIsoCode = 'SGD';
            a1.AgentNet_ID__c = 'estPurposeIdXX';
            a1.Subscription_Start_Date__c = system.today().addMonths(-10);
            a1.BillingStreet = 'test';
            a1.BillingCity = 'test';
            a1.BillingCountry = 'Malaysia';
            a1.BillingPostalCode = '80173';
            // a.BillingState = 'test';
            a1.Current_Subscription_Code__c = 'abc';
            a1.account_rule_code__c = 'Standard';
            a1.personemail = 'asd31sfaa@yaho.com';
            a1.salutation = 'Mr.';
            a1.firstname = 'aaaa';
            a1.Country__c = 'Malaysia';
            a1.Status__c = 'Active';
            a1.NetSuite_Id__c = '6779';
            a1.CEA_Salesperson_Number__c = 'W367653H';
            a1.External_field__c = '867680777';
            a1.Overlap_Agent__c = false;
            a1.PersonBirthdate=system.today();
            a1.Brickz_Agent__c = true;
             a1.Mobile_Country__c='65';
            insert a1;
            
            Case caseObj1 = new Case();
            caseObj1.RecordTypeId =Schema.SObjectType.Case.getRecordTypeInfosByDeveloperName().get('Sales_Enablement').getRecordTypeId();
            caseObj1.Status = 'New';
            caseObj1.Subject = 'Tag Brickz Only agent';
            caseObj1.accountid = a1.id;
            caseObj1.Account_Temp_ExternalField__c = a1.id;
            insert caseObj1;
            
            Account a2 = new Account();
            a2.RecordTypeId = accRectype;
            a2.LastName = 'TestYuni';
            a2.Agency__c = agency.Id;
            //a.Customer_Type__c = 'Agency';
            a2.CurrencyIsoCode = 'SGD';
            a2.AgentNet_ID__c = 'TestPurposeIdX';
            a2.Subscription_Start_Date__c = system.today().addMonths(-10);
            a2.BillingStreet = 'test';
            a2.BillingCity = 'test';
            a2.BillingCountry = 'Malaysia';
            a2.BillingPostalCode = '83173';
            // a.BillingState = 'test';
            a2.Current_Subscription_Code__c = 'abc';
            a2.account_rule_code__c = 'Standard';
            a2.personemail = 'sd131sfaa@yaho.com';
            a2.salutation = 'Mr.';
            a2.firstname = 'aaaa';
            a2.Country__c = 'Malaysia';
            a2.Status__c = 'Active';
            a2.NetSuite_Id__c = '0777';
            a2.CEA_Salesperson_Number__c = 'W567643H';
            a2.External_field__c = '867685777';
            a2.Overlap_Agent__c = true;
            a2.PersonBirthdate=system.today();
            a2.Brickz_Agent__c = false;
             a2.Mobile_Country__c='65';
            insert a2;
            
            Case caseObj2 = new Case();
            caseObj2.RecordTypeId =Schema.SObjectType.Case.getRecordTypeInfosByDeveloperName().get('Sales_Enablement').getRecordTypeId();
            caseObj2.Status = 'New';
            caseObj2.Subject = 'Un-Tag overlapping agent';
            caseObj2.accountid = a2.id;
            caseObj2.Account_Temp_ExternalField__c = a2.id;
            insert caseObj2;
            Case caseObj3 = new Case();
            caseObj3.RecordTypeId =Schema.SObjectType.Case.getRecordTypeInfosByDeveloperName().get('Sales_Enablement').getRecordTypeId();
            caseObj3.Status = 'New';
            caseObj3.Subject = 'un-Tag Brickz Only agent';
            caseObj3.accountid = a1.id;
            caseObj3.Account_Temp_ExternalField__c = a1.id;
            insert caseObj3;
            Case caseObj4 = new Case();
            caseObj4.RecordTypeId =Schema.SObjectType.Case.getRecordTypeInfosByDeveloperName().get('Sales_Enablement').getRecordTypeId();
            caseObj4.Status = 'New';
            caseObj4.Subject = ' Only agent';
            caseObj4.accountid = a1.id;
            caseObj4.Account_Temp_ExternalField__c = a1.id;
            insert caseObj4;
            
            test.startTest();
            TagUnTagCase_cc.updateCase(caseObj.id);
            TagUnTagCase_cc.updateCase(caseObj1.id);
            TagUnTagCase_cc.updateCase(caseObj2.id);
            TagUnTagCase_cc.updateCase(caseObj3.id);
            TagUnTagCase_cc.updateCase(caseObj4.id);
            test.stopTest();
        }
    }
}