unpackaged/main/default/objects/Account/fields/Account_Rule_Code__c.field-meta.xml
<CustomField>
    <fullName>Account_Rule_Code__c</fullName>
    <defaultValue>IF( $RecordType.DeveloperName = &quot;Agent&quot;, &quot;TRIAL&quot;, &quot;&quot;)</defaultValue>
    <description>Denotes account rule code (short text) for the account rule</description>
    <inlineHelpText>Denotes account rule code (short text) for the account rule</inlineHelpText>
    <label>Account Rule Code</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/Commando_Sales_Rep__c.field-meta.xml
<CustomField>
    <fullName>Commando_Sales_Rep__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Commando Sales Rep</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Accounts1</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/Country__c.field-meta.xml
<CustomField>
    <fullName>Country__c</fullName>
    <defaultValue>if(  BEGINS($UserRole.Name, &quot;TH&quot;),&quot;Thailand&quot;,if(ISPICKVAL($User.Subsidiary__c,&quot;MyProperty Data Sdn. Bhd.&quot;),&quot;Malaysia&quot;,&quot;&quot;))</defaultValue>
    <description>Denotes the country of an account</description>
    <inlineHelpText>Denotes the country of an account</inlineHelpText>
    <label>Country</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Country</valueSetName>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Account/fields/Opportunity_Created_Date__c.field-meta.xml
<CustomField>
    <fullName>Opportunity_Created_Date__c</fullName>
    <label>Opportunity Created Date</label>
    <type>DateTime</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>Denotes the status of an agent in the agent lifecycle</description>
    <inlineHelpText>Denotes the status of an agent in the agent lifecycle</inlineHelpText>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Trial</fullName>
            </value>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Downgraded</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Suspended</fullName>
            </value>
            <value>
                <fullName>Expired</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Account/fields/Subscription_End_Date__c.field-meta.xml
<CustomField>
    <fullName>Subscription_End_Date__c</fullName>
    <description>Denotes end date of an agent&#39;s current subscriptions</description>
    <inlineHelpText>Denotes end date of an agent&#39;s current subscriptions</inlineHelpText>
    <label>Subscription End Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/Subsidiary__c.field-meta.xml
<CustomField>
    <fullName>Subsidiary__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Denotes the PG subsidiary to which the account belongs to</description>
    <inlineHelpText>Denotes the PG subsidiary to which the account belongs to</inlineHelpText>
    <label>Subsidiary</label>
    <referenceTo>Subsidiary__c</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/Updated_from_API__c.field-meta.xml
<CustomField>
    <fullName>Updated_from_API__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Updated from API</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/VIP__c.field-meta.xml
<CustomField>
    <fullName>VIP__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Flag to denote if agent is VIP</description>
    <inlineHelpText>Flag to denote if agent is VIP</inlineHelpText>
    <label>VIP</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Lead/recordTypes/B2C.recordType-meta.xml
<RecordType>
    <fullName>B2C</fullName>
    <active>true</active>
    <businessProcess>B2C Lead Process</businessProcess>
    <description>Will convert to Agent</description>
    <label>B2C</label>
</RecordType>

unpackaged/main/default/objects/Opportunity/fields/Account_Rule_Code__c.field-meta.xml
<CustomField>
    <fullName>Account_Rule_Code__c</fullName>
    <label>Account Rule Code</label>
    <length>15</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Country__c.field-meta.xml
<CustomField>
    <fullName>Country__c</fullName>
    <formula>TEXT(Subsidiary__r.Country__c )</formula>
    <label>Country</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/IsClone__c.field-meta.xml
<CustomField>
    <fullName>IsClone__c</fullName>
    <label>IsClone</label>
    <length>3</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Order_Type_Clone__c.field-meta.xml
<CustomField>
    <fullName>Order_Type_Clone__c</fullName>
    <label>Order Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Contract - New</fullName>
            </value>
            <value>
                <fullName>Contract - Upsell</fullName>
            </value>
            <value>
                <fullName>Contract - Renewal</fullName>
            </value>
            <value>
                <fullName>Contract - Make Good</fullName>
            </value>
            <value>
                <fullName>Dual-SO</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Renewal_State__c.field-meta.xml
<CustomField>
    <fullName>Renewal_State__c</fullName>
    <label>Renewal State</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Actual Month</fullName>
            </value>
            <value>
                <fullName>Actual Month +1</fullName>
            </value>
            <value>
                <fullName>Early Bird</fullName>
            </value>
            <value>
                <fullName>Back to Back Renewal</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Subscription_End_Date__c.field-meta.xml
<CustomField>
    <fullName>Subscription_End_Date__c</fullName>
    <label>Subscription End Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Subsidiary__c.field-meta.xml
<CustomField>
    <fullName>Subsidiary__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Subsidiary</label>
    <referenceTo>Subsidiary__c</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/recordTypes/B2C.recordType-meta.xml
<RecordType>
    <fullName>B2C</fullName>
    <active>true</active>
    <businessProcess>B2C</businessProcess>
    <description>B2C Opportunity Record</description>
    <label>B2C</label>
</RecordType>

unpackaged/main/default/objects/Subsidiary__c/Subsidiary__c.object-meta.xml
<CustomObject>
    <description>This is a custom object to contain the information on Subsidiary and Country</description>
    <label>Subsidiary</label>
    <nameField>
        <label>Subsidiary Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Subsidiaries</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Subsidiary__c/fields/Country__c.field-meta.xml
<CustomField>
    <fullName>Country__c</fullName>
    <description>Values from global picklist</description>
    <label>Country</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Country</valueSetName>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/User/fields/Subsidiary__c.field-meta.xml
<CustomField>
    <fullName>Subsidiary__c</fullName>
    <label>Subsidiary</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Subsidiary</valueSetName>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/User/fields/Team_Lead__c.field-meta.xml
<CustomField>
    <fullName>Team_Lead__c</fullName>
    <label>Team Lead</label>
    <relationshipName>TeamLead</relationshipName>
    <restrictedAdminField>false</restrictedAdminField>
    <type>Hierarchy</type>
</CustomField>

unpackaged/main/default/classes/OpportunityRenewal_Batch.cls
/*------------------------------------------------------------
Author:        Whisnu Satriya Wardhana
Company:       Viseo Asia PTE LTD
Description:   Batch class to create Renewal Opportunity
Inputs:        

Test Class:    
History
<Date>      <Authors Name>     <Brief Description of Change>
------------------------------------------------------------*/
global class OpportunityRenewal_Batch implements Database.Batchable<sObject>{
    String query; 
    
    global Database.QueryLocator start(Database.BatchableContext BC)  {
        string identifier = 'AC_OpportunityRenewal_Batch';
        list<string> listCountry = EligibilityHandler.getCountryEligibility(identifier);
        datetime nextMonth = system.today().addMonths(1);
        query = 'SELECT Id, Name, OwnerId, Country__c, CurrencyIsoCode, Subsidiary__c, Subscription_End_Date__c, Opportunity_Created_Date__c, Updated_From_API__c FROM Account WHERE Country__c in (\''+string.join(listCountry, '\',\'')+'\') and calendar_month(Subscription_End_Date__c) = '+nextMonth.month()+' and calendar_year(Subscription_End_Date__c) = '+nextMonth.year()+' AND ((Country__c=\'Singapore\' and Status__c!=\'Cancelled\') or (Country__c=\'Malaysia\' and Status__c=\'Active\')) AND Account_Rule_Code__c not in (\'Trial\', \'\',\'Developer\', null) AND (NOT Account_Rule_Code__c like \'%CORP%\') AND RecordType.Name = \'Agent\'';
        system.debug(query);
        return Database.getQueryLocator(query);       
    }
    global void execute(Database.BatchableContext BC, List<Account> batch) {        
        if(batch.size() > 0){
            map<integer, string> mapMonth = new map<integer, string>{1=>'January', 2=>'February', 3=>'March', 4=>'April', 5=>'May', 6=>'June', 7=>'July', 8=>'August', 9=>'September', 10=>'October', 11=>'November', 12=>'December'};
                list<Id> listCheckAgentHasRenewalOpp = new list<Id>();
            list<Id> listAgentId = new list<Id>();
            list<Opportunity> listExistingOpp = new list<Opportunity>();
            map<string, string> MapAccRT = new map<string, string>();
            map<string, string> mapCountryOwner = new map<string, string>{'Singapore' => id.valueOf(label.PG_LABEL_SG_Renewal_Team_Lead), 'Thailand' => id.valueOf(label.PG_LABEL_TH_Renewal_Team_Lead), 'Malaysia' => id.valueOf(label.PG_LABEL_MY_Renewal_Team_Lead), 'Indonesia' => id.valueOf(label.PG_LABEL_ID_Renewal_Team_Lead)};
                for (RecordType rt : [SELECT Id, Name FROM RecordType WHERE SObjectType='Opportunity' and Name='B2C']){
                    MapAccRT.put(rt.Name, rt.Id);
                }
            List<Opportunity> newOpportunityRenewal = new List<Opportunity>();
            for(Account row : batch){
                listAgentId.add(row.Id);
            }
            datetime currentMonth = system.today();
            for (Opportunity row: [select Id, AccountId from Opportunity where RecordType.Name='B2C' and Order_Type_Clone__c ='Contract - Renewal' and calendar_month(CreatedDate)=:currentMonth.month() and calendar_year(CreatedDate)=:currentMonth.year() and AccountId in :listAgentId]) {
                listCheckAgentHasRenewalOpp.add(row.AccountId);
            }
            Opportunity temp;
            
            for (Account row: batch) {
                if (!listCheckAgentHasRenewalOpp.contains(row.Id)) {
                    Date dateField = row.Subscription_End_Date__c;
                    dateField = dateField.addMonths(1);
                    Integer numberOfDays = Date.daysInMonth(dateField.year(), dateField.month());
                    Date lastDayOfMonth = Date.newInstance(dateField.year(), dateField.month(), numberOfDays);
                    temp = new Opportunity(
                        CloseDate = lastDayOfMonth,
                        Name = (mapMonth.get(row.Subscription_End_Date__c.month()) + ' ' + row.Subscription_End_Date__c.year() + ' Renew Agent ' + row.Name),
                        StageName = 'Proposal',
                        AccountId = row.Id,
                        Subsidiary__c = row.Subsidiary__c,
                        CurrencyIsoCode = row.CurrencyIsoCode,
                        OwnerId = mapCountryOwner.get(row.Country__c),
                        RecordTypeId = MapAccRT.get('B2C'),
                        Subscription_End_Date__c = row.Subscription_End_Date__c.addYears(1),
                        Order_Type_Clone__c  = 'Contract - Renewal',
                        IsClone__c = 'NO',
                        Renewal_State__c = 'Early Bird' 
                    );
                    newOpportunityRenewal.add(temp);
                }
            }
            if(newOpportunityRenewal.size() > 0){
                list<Id> listOppId = new list<Id>();
                list<Opportunity> listOpp = new list<Opportunity>();
                list<Id> listAccId = new list<Id>();
                list<Account> listAcc = new list<Account>();
                
                // DML statement
                Database.SaveResult[] srList = Database.insert(newOpportunityRenewal, false);
                
                // Iterate through each returned result
                for (Database.SaveResult sr : srList) {
                    if (sr.isSuccess()) {
                        // Operation was successful, so get the ID of the record that was processed
                        system.debug('succeed sr.getId():'+sr.getId());
                        listOppId.add(sr.getId());
                    } else {
                        // Operation failed, so get all errors                
                        for(Database.Error err : sr.getErrors()) {
                            System.debug('The following error has occurred.');                    
                            System.debug(err.getStatusCode() + ': ' + err.getMessage());
                            System.debug('Account fields that affected this error: ' + err.getFields());
                        }
                    }
                }
                
                list<Task> tskList = new list<task>();
                List<OpportunityTeamMember> createOpportunityTeamMember = new List<OpportunityTeamMember>();
                if(!listOppId.IsEmpty() && listOppId.size()>0)
                    for(Opportunity op : [select Id,AccountId,CloseDate,Account.VIP__c,Account.Commando_Sales_Rep__r.IsActive,Account.Commando_Sales_Rep__c,Account.Commando_Sales_Rep__r.Team_Lead__c,Account.PersonContactId from Opportunity where Id In : listOppId]){
                        if(String.isNotBlank(op.Account.Commando_Sales_Rep__c) && op.Account.VIP__c == true){
                            
                            //create task for Commando Sales Rep/Team Lead
                            Task tsk = new Task();
                            tsk.Subject = 'Followup VIP Package';
                            tsk.Status = 'Open';
                            tsk.Priority = 'Normal';
                            tsk.WhatId = op.Id;
                            tsk.ActivityDate = op.CloseDate;
                            tsk.WhoId = op.Account.PersonContactId;
                            
                            //Create Opportunity Team Member
                            OpportunityTeamMember otm = new OpportunityTeamMember();
                            otm.OpportunityId = op.Id;
                            otm.OpportunityAccessLevel = 'Read';
                            if(op.Account.Commando_Sales_Rep__r.IsActive){
                                otm.UserId = op.Account.Commando_Sales_Rep__c;
                            	tsk.OwnerId = op.Account.Commando_Sales_Rep__c;
                            }
                            
                            else if(op.Account.Commando_Sales_Rep__r.Team_Lead__c != null){
                                otm.UserId = op.Account.Commando_Sales_Rep__r.Team_Lead__c;
                                tsk.OwnerId = op.Account.Commando_Sales_Rep__c;
                            }
                                
                            
                            otm.TeamMemberRole = 'Sales Rep';
                            
                            if(otm.UserId != null)
                            createOpportunityTeamMember.add(otm);
                            
                            if(tsk.OwnerId != null)
                            tskList.add(tsk);
                        }
                    }
                if(!createOpportunityTeamMember.isEmpty())
                    insert createOpportunityTeamMember;
                
                if(!tskList.isEmpty())
                    insert tskList;
                
                //added by vikas
                if(!listOppId.IsEmpty())
                    QuoteSyncHandler.syncQuoteToOpp(listOppId);
                
                if (listOppId.size() > 0) {
                    for (Opportunity row: [select Id, Name, AccountId from Opportunity where Id in :listOppId]) {
                        listAccId.add(row.AccountId);
                    }
                    
                    listAcc = [select Id, Opportunity_Created_Date__c, Updated_From_API__c from Account where Id in :listAccId];
                    for (Account row: listAcc) {
                        row.Opportunity_Created_Date__c = system.today();
                        row.Updated_From_API__c = !row.Updated_From_API__c;
                    }
                    update listAcc;
                    system.debug('update succeed.');
                }
            }  
        }
    }
    
    global void finish(Database.BatchableContext BC) {
        
    }
}