unpackaged/main/default/objects/Account/fields/Account_Rule_Code__c.field-meta.xml
<CustomField>
    <fullName>Account_Rule_Code__c</fullName>
    <defaultValue>IF( $RecordType.DeveloperName = &quot;Agent&quot;, &quot;TRIAL&quot;, &quot;&quot;)</defaultValue>
    <description>Denotes account rule code (short text) for the account rule</description>
    <inlineHelpText>Denotes account rule code (short text) for the account rule</inlineHelpText>
    <label>Account Rule Code</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/Agency__c.field-meta.xml
<CustomField>
    <fullName>Agency__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Denotes the real estate/property agency to which the agent belongs to</description>
    <inlineHelpText>Denotes the real estate/property agency to which the agent belongs to</inlineHelpText>
    <label>Agency</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>Please select proper Agency Account.</errorMessage>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Agency</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Agents</relationshipLabel>
    <relationshipName>Agency</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/Agency_Id__c.field-meta.xml
<CustomField>
    <fullName>Agency_Id__c</fullName>
    <description>Denotes the unique id of an agency in PG system</description>
    <externalId>true</externalId>
    <inlineHelpText>Denotes the unique id of an agency in PG system</inlineHelpText>
    <label>Agency Id</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/AgentNet_ID__c.field-meta.xml
<CustomField>
    <fullName>AgentNet_ID__c</fullName>
    <description>Denotes a numeric id of agents in PG system</description>
    <inlineHelpText>Denotes a numeric id of agents in PG system</inlineHelpText>
    <label>AgentNet ID</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/Approval_Status__c.field-meta.xml
<CustomField>
    <fullName>Approval_Status__c</fullName>
    <description>Denotes the approval status for an agent in the VIP approval process</description>
    <inlineHelpText>Denotes the approval status for an agent in the VIP approval process</inlineHelpText>
    <label>Approval Status</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/CEA_License__c.field-meta.xml
<CustomField>
    <fullName>CEA_License__c</fullName>
    <description>Denotes the agency license number registered under a governing authority</description>
    <externalId>true</externalId>
    <inlineHelpText>Denotes the agency registration number issued by CEA for SG agencies and MIEA for MY agencies</inlineHelpText>
    <label>Agency Identification Number</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/CEA_Salesperson_Number__c.field-meta.xml
<CustomField>
    <fullName>CEA_Salesperson_Number__c</fullName>
    <description>Denotes the agent license number registered under a governing authority</description>
    <inlineHelpText>Denotes the agent registration number issued by CEA for SG agents and MIEA for MY agents</inlineHelpText>
    <label>Agent Identification Number</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/Country__c.field-meta.xml
<CustomField>
    <fullName>Country__c</fullName>
    <defaultValue>if(  BEGINS($UserRole.Name, &quot;TH&quot;),&quot;Thailand&quot;,if(ISPICKVAL($User.Subsidiary__c,&quot;MyProperty Data Sdn. Bhd.&quot;),&quot;Malaysia&quot;,&quot;&quot;))</defaultValue>
    <description>Denotes the country of an account</description>
    <inlineHelpText>Denotes the country of an account</inlineHelpText>
    <label>Country</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Country</valueSetName>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Account/fields/Created_From_AdminNet__c.field-meta.xml
<CustomField>
    <fullName>Created_From_AdminNet__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Equals to true if agent is created from adminNet.</description>
    <label>Created From AdminNet</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/Current_Subscription_Code__c.field-meta.xml
<CustomField>
    <fullName>Current_Subscription_Code__c</fullName>
    <label>Current Subscription Code</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/LocalLanguage_Last_Name__c.field-meta.xml
<CustomField>
    <fullName>LocalLanguage_Last_Name__c</fullName>
    <description>Denotes Last Name in local language</description>
    <inlineHelpText>Denotes Last Name in local language</inlineHelpText>
    <label>Last Name (Local Language)</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/Loyalty_Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Loyalty_Start_Date__c</fullName>
    <description>Denotes the loyalty start date of an agent</description>
    <inlineHelpText>Denotes the loyalty start date of an agent</inlineHelpText>
    <label>Loyalty Start Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/Mobile_Country__c.field-meta.xml
<CustomField>
    <fullName>Mobile_Country__c</fullName>
    <description>Denotes country code of mobile number of agents</description>
    <inlineHelpText>Denotes country code of mobile number of agents</inlineHelpText>
    <label>Mobile Country</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>65</fullName>
            </value>
            <value>
                <fullName>62</fullName>
            </value>
            <value>
                <fullName>60</fullName>
            </value>
            <value>
                <fullName>66</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Account/fields/Reward_Points__c.field-meta.xml
<CustomField>
    <fullName>Reward_Points__c</fullName>
    <label>Reward Points</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/Reward_Tier__c.field-meta.xml
<CustomField>
    <fullName>Reward_Tier__c</fullName>
    <label>Reward Tier</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Solitaire</fullName>
            </value>
            <value>
                <fullName>Titanium</fullName>
            </value>
            <value>
                <fullName>Platinum</fullName>
            </value>
            <value>
                <fullName>Gold</fullName>
            </value>
            <value>
                <fullName>Silver</fullName>
            </value>
            <value>
                <fullName>Elite</fullName>
            </value>
            <value>
                <fullName>Black</fullName>
                <isActive>false</isActive>
                <label>Black</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Account/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>Denotes the status of an agent in the agent lifecycle</description>
    <inlineHelpText>Denotes the status of an agent in the agent lifecycle</inlineHelpText>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Trial</fullName>
            </value>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Downgraded</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Suspended</fullName>
            </value>
            <value>
                <fullName>Expired</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Account/fields/Subscription_End_Date__c.field-meta.xml
<CustomField>
    <fullName>Subscription_End_Date__c</fullName>
    <description>Denotes end date of an agent&#39;s current subscriptions</description>
    <inlineHelpText>Denotes end date of an agent&#39;s current subscriptions</inlineHelpText>
    <label>Subscription End Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/Subscription_Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Subscription_Start_Date__c</fullName>
    <description>Denotes the start date of agent&#39;s current subscription</description>
    <inlineHelpText>Denotes the start date of agent&#39;s current subscription</inlineHelpText>
    <label>Subscription Start Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/Subsidiary__c.field-meta.xml
<CustomField>
    <fullName>Subsidiary__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Denotes the PG subsidiary to which the account belongs to</description>
    <inlineHelpText>Denotes the PG subsidiary to which the account belongs to</inlineHelpText>
    <label>Subsidiary</label>
    <referenceTo>Subsidiary__c</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/VIP__c.field-meta.xml
<CustomField>
    <fullName>VIP__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Flag to denote if agent is VIP</description>
    <inlineHelpText>Flag to denote if agent is VIP</inlineHelpText>
    <label>VIP</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/VIP_Campaign__c.field-meta.xml
<CustomField>
    <fullName>VIP_Campaign__c</fullName>
    <description>Denotes the VIP campaign to which the agent is approved to be a campaign member</description>
    <inlineHelpText>Denotes the VIP campaign to which the agent is approved to be a campaign member</inlineHelpText>
    <label>VIP Campaign</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Account/recordTypes/Agency.recordType-meta.xml
<RecordType>
    <fullName>Agency</fullName>
    <active>true</active>
    <label>Agency</label>
</RecordType>

unpackaged/main/default/objects/Campaign/fields/Country__c.field-meta.xml
<CustomField>
    <fullName>Country__c</fullName>
    <description>Denotes the country of campaign members and is synonymous with currency field</description>
    <inlineHelpText>Denotes the country of campaign members and is synonymous with currency field</inlineHelpText>
    <label>Country</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Country</valueSetName>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Campaign/fields/VIP_Quota__c.field-meta.xml
<CustomField>
    <fullName>VIP_Quota__c</fullName>
    <description>Denotes the count of VIP agents allocated per year</description>
    <inlineHelpText>Denotes the count of VIP agents allocated per year</inlineHelpText>
    <label>VIP Quota</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/Campaign/recordTypes/Standard.recordType-meta.xml
<RecordType>
    <fullName>Standard</fullName>
    <active>true</active>
    <label>Standard</label>
</RecordType>

unpackaged/main/default/objects/Contact/fields/Subsidiary__c.field-meta.xml
<CustomField>
    <fullName>Subsidiary__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Denotes the PG subsidiary to which the contact belongs to</description>
    <inlineHelpText>Denotes the PG subsidiary to which the contact belongs to</inlineHelpText>
    <label>Subsidiary</label>
    <referenceTo>Subsidiary__c</referenceTo>
    <relationshipLabel>Contacts</relationshipLabel>
    <relationshipName>Contacts</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Media__c/Media__c.object-meta.xml
<CustomObject>
    <label>Media</label>
    <nameField>
        <displayFormat>M-{0000000}</displayFormat>
        <label>Agency Logo Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Media</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Media__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Denotes the account to which record is bind to</description>
    <inlineHelpText>Denotes the account to which record is bind to</inlineHelpText>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>Agency_Logo</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Subsidiary__c/Subsidiary__c.object-meta.xml
<CustomObject>
    <description>This is a custom object to contain the information on Subsidiary and Country</description>
    <label>Subsidiary</label>
    <nameField>
        <label>Subsidiary Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Subsidiaries</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Subsidiary__c/fields/Country__c.field-meta.xml
<CustomField>
    <fullName>Country__c</fullName>
    <description>Values from global picklist</description>
    <label>Country</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Country</valueSetName>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Trigger_Execute__c/Trigger_Execute__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>Trigger Execute</label>
</CustomObject>

unpackaged/main/default/objects/Trigger_Execute__c/fields/Enable_del__c.field-meta.xml
<CustomField>
    <fullName>Enable_del__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Enable del</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/User/fields/Subsidiary__c.field-meta.xml
<CustomField>
    <fullName>Subsidiary__c</fullName>
    <label>Subsidiary</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Subsidiary</valueSetName>
    </valueSet>
</CustomField>

unpackaged/main/default/classes/PGAccountTriggerHandler_Test.cls
@isTest
public class PGAccountTriggerHandler_Test {
    public testMethod static void runTest() {
        Test.startTest();
        User thisuser = [SELECT Id,Subsidiary__c FROM User WHERE country = 'Singapore' and isActive = true and profile.name = 'System Administrator' LIMIT 1];
        System.runAs(thisuser){
            Trigger_Execute__c customsetting=new Trigger_Execute__c();
            customsetting.Name='PGAccountTrigger';
            customsetting.Enable_del__c=true;
            insert customsetting;
            
            Trigger_Execute__c TE = new Trigger_Execute__c();
            TE.Name = 'PGCampMemberTrigger';
            TE.Enable_del__c = true;
            insert TE;
            
            id subId = PGTestDataFactory.createSubsidiary().Id;
            list<Account> listAccount1 = new list<Account>();
            Account agency = new Account();
            PGTestDataFactory_v2.initSetupData();
            agency.name = 'Unit Test Agency';
            agency.Agency_Id__c = '40574';
            agency.CEA_License__c = 'CEAUNittest1';
            agency.RecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Agency').getRecordTypeId();
            agency.Country__c = 'Singapore';
            agency.Subsidiary__c = subId;
            listAccount1.add(agency);
            
            Media__c newMedia = new Media__c();
            newMedia.Account__c = listAccount1[0].id;
            newMedia.CurrencyIsoCode = 'SGD';
            newMedia.IsActive__c = True;
            insert newMedia;
            
            Blob bodyblob = Blob.valueOf('PG Agency default');
            Contentversion cv = new contentversion(title ='PG Agency default',PathOnClient ='PG Agency default.jpg',versiondata = bodyblob,origin ='H');
            insert cv;
            
            ContentVersion conVersion = [SELECT Id, ContentSize ,PathOnClient,Title,ContentDocumentId FROM ContentVersion WHERE Id =: cv.id];
            ContentDocumentLink cdl = new ContentDocumentLink();
            cdl.ContentDocumentId = conVersion.ContentDocumentId;
            cdl.LinkedEntityId = newMedia.id;
            cdl.ShareType = 'V';
            cdl.Visibility = 'AllUsers'; 
            insert cdl;
            insert listAccount1;
            
            list<Account> listAccount = new list<Account>();
            Account acc = new Account();
            PGTestDataFactory_v2.initSetupData();
            acc.FirstName = 'TestMe';
            acc.LastName = 'Lasting';
            acc.AgentNet_ID__c = 'AgentNet_ID__c test';
            acc.Salutation = 'Mrs.';
            acc.CurrencyIsoCode = 'SGD';
            //acc.Lead_BirthDate__c =system.today();
            acc.PersonBirthdate = system.today().addDays(-30);
            acc.Subscription_Start_Date__c = system.today().addMonths(-10);
            acc.BillingStreet = 'test';
            acc.BillingCity = 'test';
            acc.Reward_Points__c = 700;
            acc.Reward_Tier__c = 'Gold';
            acc.BillingCountry = 'Singapore';
            acc.BillingPostalCode = '8373';
            //  acc.BillingState = 'test';
            acc.Current_Subscription_Code__c = 'abc';
            acc.PersonEmail = 'test@yuni.com';
            acc.Account_Rule_Code__c = 'test';
            acc.Status__c = 'Active';
            acc.Country__c = 'Singapore';
            acc.Agency__c = agency.id;
            acc.Subsidiary__c = subId;
            acc.CEA_Salesperson_Number__c='R123456H';
            acc.PersonBirthdate=system.today();
            acc.Subscription_End_Date__c = Date.newInstance(2019, 12, 9);
            acc.Loyalty_Start_Date__c = Date.newInstance(2018, 12, 9);
            acc.RecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Agent').getRecordTypeId();
            acc.VIP_Campaign__c = 'VIP Advance SC';
            acc.Approval_Status__c = 'Test';
            acc.Mobile_Country__c='65';
            acc.Created_From_AdminNet__c = true;
            
            Account accReward = new Account();
            PGTestDataFactory_v2.initSetupData();
            accReward.FirstName = 'TestMe';
            accReward.LastName = 'Lasting';
            accReward.AgentNet_ID__c = 'AgentNet_ID__c test';
            accReward.Salutation = 'Mrs.';
            accReward.CurrencyIsoCode = 'SGD';
            accReward.Subscription_Start_Date__c = system.today().addMonths(-10);
            accReward.BillingStreet = 'test';
            accReward.BillingCity = 'test';
            //accReward.Lead_BirthDate__c =system.today();
            accReward.BillingCountry = 'Singapore';
            accReward.BillingPostalCode = '8373';
            //  acc.BillingState = 'test';
            accReward.Current_Subscription_Code__c = 'abc';
            accReward.PersonEmail = 'accReward@yuni.com';
            accReward.Account_Rule_Code__c = 'test';
            accReward.Status__c = 'Active';
            accReward.Country__c = 'Singapore';
            accReward.Agency__c = agency.id;
            accReward.Subsidiary__c = subId;
            accReward.CEA_Salesperson_Number__c='A678996A';
            accReward.PersonBirthdate=system.today();
            accReward.Subscription_End_Date__c = Date.newInstance(2030, 12, 9);
            accReward.Subscription_Start_Date__c = System.today();
            accReward.Account_Rule_Code__c ='Standard';
            accReward.Loyalty_Start_Date__c = Date.newInstance(2018, 12, 9);
            accReward.RecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Agent').getRecordTypeId();
            accReward.VIP_Campaign__c = 'VIP Advance SC';
            accReward.Approval_Status__c = 'Test';
            accReward.Created_From_AdminNet__c = true;
            accReward.Mobile_Country__c='65';
            listAccount.add(accReward);
            listAccount.add(acc); 
            
            Account acc2 = new Account();
            PGTestDataFactory_v2.initSetupData();
            acc2.FirstName = 'TestMe';
            acc2.LastName = 'Lasting';
            
            acc2.AgentNet_ID__c = 'AgentNet_ID__c test';
            acc2.Salutation = 'Mrs.';
            acc2.CurrencyIsoCode = 'SGD';
            acc2.Subscription_Start_Date__c = system.today().addMonths(-10);
            acc2.BillingStreet = 'test';
            acc2.BillingCity = 'test';
            acc2.BillingCountry = 'Singapore';
            //acc2.Lead_BirthDate__c =system.today();
            acc2.BillingPostalCode = '83273';
            //acc2.BillingState = 'test';
            acc2.Current_Subscription_Code__c = 'abc';
            acc2.PersonBirthdate = system.today();
            acc2.PersonEmail = 'test@yuwni.com';
            acc2.Account_Rule_Code__c = 'test';
            acc2.Status__c = 'Pending';
            acc2.Country__c = 'Singapore';
            acc2.Agency__c = agency.id;
            acc2.Subsidiary__c = subId;
            acc2.CEA_Salesperson_Number__c='R123456H';
            acc2.Subscription_End_Date__c = Date.newInstance(2019, 12, 9);
            acc2.Loyalty_Start_Date__c = Date.newInstance(2018, 12, 9);
            acc2.RecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Agent').getRecordTypeId();
            acc2.VIP_Campaign__c = 'VIP Advance SC-1';
            acc2.Approval_Status__c = '';
            acc2.Mobile_Country__c='65';
            listAccount.add(acc2);
            PGAccountTriggerHandler.setQualifyAgentReferral(listAccount);
            insert listAccount;
            PGAccountTriggerHandler.markAsTestAccount(listAccount,null);
            
            listAccount[0].Subscription_End_Date__c = Date.newInstance(2019, 12, 9);
            listAccount[0].Loyalty_Start_Date__c = Date.newInstance(2017, 12, 9);
            update listAccount;
            
            Account ac = [Select Id,PersonContactId,VIP_Campaign__c from Account where Id = : acc2.Id limit 1];
            
            Campaign cma = new Campaign();
            cma.Name = 'VIP Advance SC-1';
            cma.Country__c = 'Singapore';
            cma.IsActive = true;
            cma.CurrencyIsoCode = 'SGD';
            cma.EndDate = system.today().addDays(-2);
            cma.VIP_Quota__c = 2;
            insert cma;
            
            CampaignMember cmp = new CampaignMember();
            cmp.ContactId = ac.PersonContactId;
            cmp.Status = 'Approved';
            cmp.CampaignId = cma.Id;
            insert cmp;
            
            
            Contact con = new Contact();
            con.FirstName = 'TestFName';
            con.LastName = 'testLname';
            con.Email = 'test@nmail.com';
            insert con;
            
            CampaignMember cmp1 = new CampaignMember();
            cmp1.ContactId = con.Id;
            cmp1.Status = 'Approved';
            cmp1.CampaignId = cma.Id;
            insert cmp1;
            
            PGAccountTriggerHandler.accountTriggerRecursion = false;
            
            Map<Id,Account> oldMap = new Map<Id,Account>();
            PGAccountTriggerHandler.updatePGTenure(listAccount, oldMap);
            PGAccountTriggerHandler.increasecoverage();
            acc2.Approval_Status__c = acc2.VIP_Campaign__c+'Approved';
            acc2.VIP__c = true;
            acc2.Status__c = 'Trial';
            update acc2;
        }
        Test.stopTest();
    }
    public testMethod static void runTest1() {
        Test.startTest();
        User thisuser = [SELECT Id,Subsidiary__c FROM User WHERE country = 'Singapore' and isActive = true and profile.name = 'System Administrator' LIMIT 1];
        System.runAs(thisuser){
            Trigger_Execute__c customsetting=new Trigger_Execute__c();
            customsetting.Name='PGAccountTrigger';
            customsetting.Enable_del__c=true;
            insert customsetting;
            
            Trigger_Execute__c TE = new Trigger_Execute__c();
            TE.Name = 'PGCampMemberTrigger';
            TE.Enable_del__c = true;
            insert TE;
            
            id subId = PGTestDataFactory.createSubsidiary().Id;
            list<Account> listAccount1 = new list<Account>();
            Account agency = new Account();
            PGTestDataFactory_v2.initSetupData();
            agency.name = 'Unit Test Agency';
            agency.Agency_Id__c = '40574';
            agency.CEA_License__c = 'CEAUNittest1';
            agency.RecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Agency').getRecordTypeId();
            agency.Country__c = 'Singapore';
            agency.Subsidiary__c = subId;
            listAccount1.add(agency);
            
            
            Media__c newMedia = new Media__c();
            newMedia.Account__c = listAccount1[0].id;
            newMedia.CurrencyIsoCode = 'SGD';
            newMedia.IsActive__c = True;
            insert newMedia;
            
            Blob bodyblob = Blob.valueOf('PG Agency default');
            Contentversion cv = new contentversion(title ='PG Agency default',PathOnClient ='PG Agency default.jpg',versiondata = bodyblob,origin ='H');
            insert cv;
            
            ContentVersion conVersion = [SELECT Id, ContentSize ,PathOnClient,Title,ContentDocumentId FROM ContentVersion WHERE Id =: cv.id];
            ContentDocumentLink cdl = new ContentDocumentLink();
            cdl.ContentDocumentId = conVersion.ContentDocumentId;
            cdl.LinkedEntityId = newMedia.id;
            cdl.ShareType = 'V';
            cdl.Visibility = 'AllUsers'; 
            insert cdl;
            insert listAccount1;
            
            list<Account> listAccount = new list<Account>();
            Account acc = new Account();
            PGTestDataFactory_v2.initSetupData();
            acc.FirstName = 'TestMe';
            acc.LastName = 'Lasting';
            acc.AgentNet_ID__c = 'AgentNet_ID__c test';
            acc.Salutation = 'Mrs.';
            acc.CurrencyIsoCode = 'SGD';
            acc.PersonBirthdate = system.today().addDays(-30);
            acc.Subscription_Start_Date__c = system.today().addMonths(-10);
            acc.BillingStreet = 'test';
            // acc.Lead_BirthDate__c =system.today();
            acc.BillingCity = 'test';
            acc.Reward_Points__c = 700;
            acc.Reward_Tier__c = 'Gold';
            acc.BillingCountry = 'Singapore';
            acc.BillingPostalCode = '8373';
            //  acc.BillingState = 'test';
            acc.Current_Subscription_Code__c = 'abc';
            acc.PersonEmail = 'test@yuni.com';
            acc.Account_Rule_Code__c = 'test';
            acc.Status__c = 'Active';
            acc.Country__c = 'Singapore';
            acc.Agency__c = agency.id;
            acc.Subsidiary__c = subId;
            acc.CEA_Salesperson_Number__c='R123456H';
            acc.PersonBirthdate=system.today();
            acc.Subscription_End_Date__c = Date.newInstance(2019, 12, 9);
            acc.Loyalty_Start_Date__c = Date.newInstance(2018, 12, 9);
            acc.RecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Agent').getRecordTypeId();
            acc.VIP_Campaign__c = 'VIP Advance SC';
            acc.Approval_Status__c = 'Test';
            acc.Created_From_AdminNet__c = true;
            acc.Mobile_Country__c = '65';
            
            Account accReward = new Account();
            PGTestDataFactory_v2.initSetupData();
            accReward.FirstName = 'TestMe';
            accReward.LastName = 'Lasting';
            accReward.AgentNet_ID__c = 'AgentNet_ID__c test';
            accReward.Salutation = 'Mrs.';
            accReward.CurrencyIsoCode = 'SGD';
            accReward.Subscription_Start_Date__c = system.today().addMonths(-10);
            accReward.BillingStreet = 'test';
            accReward.BillingCity = 'test';
            //accReward.Lead_BirthDate__c =system.today();
            accReward.BillingCountry = 'Singapore';
            accReward.BillingPostalCode = '8373';
            //  acc.BillingState = 'test';
            accReward.Current_Subscription_Code__c = 'abc';
            accReward.PersonEmail = 'accReward@yuni.com';
            accReward.Account_Rule_Code__c = 'test';
            accReward.Status__c = 'Active';
            accReward.Country__c = 'Singapore';
            accReward.Agency__c = agency.id;
            accReward.Subsidiary__c = subId;
            accReward.CEA_Salesperson_Number__c='A678996A';
            accReward.PersonBirthdate=system.today();
            accReward.Subscription_End_Date__c = Date.newInstance(2030, 12, 9);
            accReward.Subscription_Start_Date__c = System.today();
            accReward.Account_Rule_Code__c ='Standard';
            accReward.Loyalty_Start_Date__c = Date.newInstance(2018, 12, 9);
            accReward.RecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Agent').getRecordTypeId();
            accReward.VIP_Campaign__c = 'VIP Advance SC';
            accReward.Approval_Status__c = 'Test';
            accReward.Created_From_AdminNet__c = true;
            accReward.Mobile_Country__c = '65';
            listAccount.add(accReward);
            listAccount.add(acc); 
            
            Account acc2 = new Account();
            PGTestDataFactory_v2.initSetupData();
            acc2.FirstName = 'TestMe';
            acc2.LastName = 'Lasting';
            
            acc2.AgentNet_ID__c = 'AgentNet_ID__c test';
            acc2.Salutation = 'Mrs.';
            acc2.CurrencyIsoCode = 'SGD';
            acc2.Subscription_Start_Date__c = system.today().addMonths(-10);
            acc2.BillingStreet = 'test';
            acc2.BillingCity = 'test';
            acc2.BillingCountry = 'Singapore';
            acc2.BillingPostalCode = '83273';
            //acc2.BillingState = 'test';
            //acc2.Lead_BirthDate__c =system.today();
            acc2.Current_Subscription_Code__c = 'abc';
            acc2.PersonBirthdate = system.today();
            acc2.PersonEmail = 'test@yuwni.com';
            acc2.Account_Rule_Code__c = 'test';
            acc2.Status__c = 'Active';
            acc2.Country__c = 'Singapore';
            acc2.Agency__c = agency.id;
            acc2.Subsidiary__c = subId;
            acc2.CEA_Salesperson_Number__c='R123456H';
            acc2.Subscription_End_Date__c = Date.newInstance(2019, 12, 9);
            acc2.Loyalty_Start_Date__c = Date.newInstance(2018, 12, 9);
            acc2.RecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Agent').getRecordTypeId();
            acc2.VIP_Campaign__c = 'VIP Advance SC-1';
            acc2.Approval_Status__c = '';
            acc2.Mobile_Country__c = '65';
            listAccount.add(acc2);
            PGAccountTriggerHandler.setQualifyAgentReferral(listAccount);
            insert listAccount;
            /*acc3.LocalLanguage_last_name__c ='testLast';
acc3.localLanguage_First_name__c ='testFirst';
acc3.FirstName = 'First';
acc3.LastName = 'Last';
acc3.Customer_Type__c='Owner';
update acc3;*/
            listAccount[0].Subscription_End_Date__c = Date.newInstance(2019, 12, 9);
            listAccount[0].Loyalty_Start_Date__c = Date.newInstance(2017, 12, 9);
            update listAccount;
            
            Account ac = [Select Id,name,PersonContactId,VIP_Campaign__c from Account where Id = : acc2.Id limit 1];
            
            Campaign cma = new Campaign();
            cma.Name = ac.Name;
            cma.Country__c = 'Singapore';
            cma.IsActive = true;
            cma.CurrencyIsoCode = 'SGD';
            cma.EndDate = system.today().addDays(-2);
            cma.VIP_Quota__c = 1;
            insert cma;
            
            CampaignMember cmp = new CampaignMember();
            cmp.ContactId = ac.PersonContactId;
            cmp.Status = 'Approved';
            cmp.CampaignId = cma.Id;
            insert cmp;
            
            Map<Id,Account> oldMap = new Map<Id,Account>();
            PGAccountTriggerHandler.updatePGTenure(listAccount, oldMap);
            PGAccountTriggerHandler.increasecoverage();
            
        }
        Test.stopTest();
        
    }
    
    public testMethod static void runTest2() {
        User thisUser = [SELECT Id,Subsidiary__c,profile.name FROM User WHERE country = 'Malaysia' and isActive = true and profile.name = 'System Administrator' LIMIT 1];
        System.runAs (thisUser) {
            Test.startTest();
            Trigger_Execute__c customsetting=new Trigger_Execute__c();
            customsetting.Name='PGAccountTrigger';
            customsetting.Enable_del__c=true;
            insert customsetting;
            
            Trigger_Execute__c TE = new Trigger_Execute__c();
            TE.Name = 'PGCampMemberTrigger';
            TE.Enable_del__c = true;
            insert TE;
            
            id subId = PGTestDataFactory.createMYSubsidiary().Id;
            list<Account> listAccount1 = new list<Account>();
            Account agency = new Account();
            PGTestDataFactory_v2.initSetupData();
            agency.name = 'Unit Test Agency';
            agency.Agency_Id__c = '000000';
            agency.CEA_License__c = 'CEAUNittest1';
            agency.RecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Agency').getRecordTypeId();
            agency.Country__c = 'Malaysia';
            agency.Subsidiary__c = subId;
            listAccount1.add(agency);
            
            
            Media__c newMedia = new Media__c();
            newMedia.Account__c = listAccount1[0].id;
            newMedia.CurrencyIsoCode = 'SGD';
            newMedia.IsActive__c = True;
            insert newMedia;
            
            Blob bodyblob = Blob.valueOf('PG Agency default');
            Contentversion cv = new contentversion(title ='PG Agency default',PathOnClient ='PG Agency default.jpg',versiondata = bodyblob,origin ='H');
            insert cv;
            
            ContentVersion conVersion = [SELECT Id, ContentSize ,PathOnClient,Title,ContentDocumentId FROM ContentVersion WHERE Id =: cv.id];
            ContentDocumentLink cdl = new ContentDocumentLink();
            cdl.ContentDocumentId = conVersion.ContentDocumentId;
            cdl.LinkedEntityId = newMedia.id;
            cdl.ShareType = 'V';
            cdl.Visibility = 'AllUsers'; 
            insert cdl;
            insert listAccount1;
            
            list<Account> listAccount = new list<Account>();
            Account acc = new Account();
            PGTestDataFactory_v2.initSetupData();
            acc.FirstName = 'TestMe';
            acc.LastName = 'Lasting';
            acc.AgentNet_ID__c = 'AgentNet_ID__c test';
            acc.Salutation = 'Mrs.';
            acc.CurrencyIsoCode = 'MYR';
            acc.Subscription_Start_Date__c = system.today().addMonths(-10);
            acc.BillingStreet = 'test';
            acc.BillingCity = 'test';
            acc.BillingCountry = 'Malaysia';
            acc.BillingPostalCode = '83712';
            // acc.BillingState = 'test';
            acc.Current_Subscription_Code__c = 'abc';
            acc.PersonEmail = 'test@yuni.com';
            acc.Account_Rule_Code__c = 'test';
            acc.Status__c = 'Active';
            acc.Country__c = 'Malaysia';
            acc.Agency__c = agency.id;
            acc.Subsidiary__c = subId;
            acc.CEA_Salesperson_Number__c='K123456H';
            acc.PersonBirthdate=system.today();
            acc.Subscription_End_Date__c = Date.newInstance(2019, 12, 9);
            acc.Loyalty_Start_Date__c = Date.newInstance(2018, 12, 9);
            acc.RecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Agent').getRecordTypeId();
            acc.Mobile_Country__c = '60';
            listAccount.add(acc); 
            Account acc2 = new Account();
            PGTestDataFactory_v2.initSetupData();
            acc2.FirstName = 'TestMe';
            acc2.LastName = 'Lasting';
            acc2.AgentNet_ID__c = 'AgentNet_ID__c test';
            acc2.Salutation = 'Mrs.';
            acc2.CurrencyIsoCode = 'MYR';
            acc2.Subscription_Start_Date__c = system.today().addMonths(-10);
            acc2.BillingStreet = 'test';
            acc.BillingCity = 'test';
            acc.BillingCountry = 'Malaysia';
            acc2.BillingPostalCode = '83210';
            // acc2.BillingState = 'test';
            acc2.Current_Subscription_Code__c = 'abc';
            acc2.PersonEmail = 'test@yuwni.com';
            acc2.Account_Rule_Code__c = 'test';
            acc2.Status__c = 'Active';
            acc2.Country__c = 'Malaysia';
            acc2.Agency__c = agency.id;
            acc2.Subsidiary__c = subId;
            acc2.Subscription_End_Date__c = Date.newInstance(2019, 12, 9);
            acc2.Loyalty_Start_Date__c = Date.newInstance(2018, 12, 9);
            acc2.RecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Agent').getRecordTypeId();
            acc2.VIP_Campaign__c = 'VIP Advance SC-1';
            acc2.Approval_Status__c = '';
            acc2.CEA_Salesperson_Number__c='N123456H';
            acc2.Mobile_Country__c = '60';
            listAccount.add(acc2);
            
            Account acc3 = new Account();
            PGTestDataFactory_v2.initSetupData();
            acc3.FirstName = 'TestMe';
            acc3.LastName = 'Lasting';
            acc3.AgentNet_ID__c = 'AgentNet_ID__c test';
            acc3.Salutation = 'Mrs.';
            acc3.CurrencyIsoCode = 'MYR';
            acc3.Subscription_Start_Date__c = system.today().addMonths(-10);
            acc3.BillingStreet = 'test';
            acc3.BillingCity = 'test';
            acc3.BillingCountry = 'Malaysia';
            acc3.BillingPostalCode = '83210';
            // acc3.BillingState = 'test';
            acc3.Current_Subscription_Code__c = 'abc';
            acc3.PersonEmail = 'test@yuwni.com';
            acc3.Account_Rule_Code__c = 'test';
            acc3.Status__c = 'Active';
            acc3.Country__c = 'Malaysia';
            acc3.Agency__c = agency.id;
            acc3.Subsidiary__c = subId;
            acc3.Subscription_End_Date__c = Date.newInstance(2019, 12, 9);
            acc3.Loyalty_Start_Date__c = Date.newInstance(2018, 12, 9);
            acc3.RecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Agent').getRecordTypeId();
            acc3.VIP_Campaign__c = 'VIP Advance SC-1';
            acc3.Approval_Status__c = '';
            acc3.CEA_Salesperson_Number__c='G123456U';
            acc.PersonBirthdate=system.today();
            acc3.PersonMobilePhone='132453678';
            acc3.Mobile_Country__c='66';
            
            listAccount.add(acc3);
            
            PGAccountTriggerHandler.setQualifyAgentReferral(listAccount);
            insert listAccount;
            acc3.LocalLanguage_last_name__c ='testLast';
            acc3.localLanguage_First_name__c ='testFirst';
            acc3.FirstName = 'First';
            acc3.LastName = 'Last';
            acc3.Customer_Type__c='Owner';
            update acc3;
            listAccount[0].Subscription_End_Date__c = Date.newInstance(2019, 12, 9);
            listAccount[0].Loyalty_Start_Date__c = Date.newInstance(2017, 12, 9);
            update listAccount;
            
            Account ac = [Select Id,name,PersonContactId,VIP_Campaign__c from Account where Id = : acc2.Id limit 1];
            
            Campaign cma = new Campaign();
            cma.Name = ac.Name;
            cma.Country__c = 'Malaysia';
            cma.IsActive = true;
            cma.EndDate = system.today().addDays(-2);
            cma.CurrencyIsoCode = 'MYR';
            cma.VIP_Quota__c = 1;
            insert cma;
            
            CampaignMember cmp = new CampaignMember();
            cmp.ContactId = ac.PersonContactId;
            cmp.Status = 'Approved';
            cmp.CampaignId = cma.Id;
            insert cmp;
            
            
            
            Map<Id,Account> oldMap = new Map<Id,Account>();
            PGAccountTriggerHandler.updatePGTenure(listAccount, oldMap);
            // PGAccountTriggerHandler.updatePGTenure(listAccount4, oldMap);
            PGAccountTriggerHandler.increasecoverage();
            Test.stopTest();
        }
    }
    
    public testMethod static void runTest3() {
        User thisUser = [SELECT Id,Subsidiary__c FROM User WHERE country = 'Thailand' and isActive = true and profile.name = 'TH B2C Sales User' Limit 1];
        System.runAs (thisUser) {
            Test.startTest();
            Trigger_Execute__c customsetting=new Trigger_Execute__c();
            customsetting.Name='PGAccountTrigger';
            customsetting.Enable_del__c=true;
            insert customsetting;
            
            Trigger_Execute__c TE = new Trigger_Execute__c();
            TE.Name = 'PGCampMemberTrigger';
            TE.Enable_del__c = true;
            insert TE;
            
            User usr = new User();
            usr.Id = UserInfo.getUserId();
            
            id subId = PGTestDataFactory_v2.createTHSubsidiary(usr).Id;
            list<Account> listAccount1 = new list<Account>();
            Account agency = new Account();
            PGTestDataFactory_v2.initSetupData();
            agency.name = 'Unit Test Agency';
            agency.Agency_Id__c = '000000';
            agency.CEA_License__c = 'CEAUNittest1';
            agency.RecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Agency').getRecordTypeId();
            agency.Country__c = 'Thailand';
            agency.Subsidiary__c = subId;
            listAccount1.add(agency);
            
            Media__c newMedia = new Media__c();
            newMedia.Account__c = listAccount1[0].id;
            newMedia.CurrencyIsoCode = 'SGD';
            newMedia.IsActive__c = True;
            insert newMedia;
            
            Blob bodyblob = Blob.valueOf('PG Agency default');
            Contentversion cv = new contentversion(title ='PG Agency default',PathOnClient ='PG Agency default.jpg',versiondata = bodyblob,origin ='H');
            insert cv;
            
            ContentVersion conVersion = [SELECT Id, ContentSize ,PathOnClient,Title,ContentDocumentId FROM ContentVersion WHERE Id =: cv.id];
            ContentDocumentLink cdl = new ContentDocumentLink();
            cdl.ContentDocumentId = conVersion.ContentDocumentId;
            cdl.LinkedEntityId = newMedia.id;
            cdl.ShareType = 'V';
            cdl.Visibility = 'AllUsers'; 
            insert cdl;
            insert listAccount1;
            
            list<Account> listAccount = new list<Account>();
            Account acc = new Account();
            PGTestDataFactory_v2.initSetupData();
            acc.FirstName = 'TestMe';
            acc.LastName = 'Lasting';
            acc.AgentNet_ID__c = 'AgentNet_ID__c test';
            acc.Salutation = 'Mrs.';
            acc.CurrencyIsoCode = 'THB';
            acc.Subscription_Start_Date__c = system.today().addMonths(-10);
            acc.BillingStreet = 'test';
            acc.BillingCity = 'test';
            acc.BillingCountry = 'Thailand';
            acc.BillingPostalCode = '83712';
            // acc.BillingState = 'test';
            acc.Current_Subscription_Code__c = 'abc';
            acc.PersonEmail = 'test@yuni.com';
            acc.Account_Rule_Code__c = 'test';
            acc.Status__c = 'Active';
            acc.Country__c = 'Thailand';
            acc.Agency__c = agency.id;
            acc.Subsidiary__c = subId;
            acc.CEA_Salesperson_Number__c='P12345678H';
            acc.PersonBirthdate=system.today();
            acc.Subscription_End_Date__c = Date.newInstance(2019, 12, 9);
            acc.Loyalty_Start_Date__c = Date.newInstance(2018, 12, 9);
            acc.PersonMobilePhone = '876544';
            acc.Mobile_Country__c='66';
            acc.RecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Agent').getRecordTypeId();
            listAccount.add(acc); 
            Account acc2 = new Account();
            PGTestDataFactory_v2.initSetupData();
            acc2.FirstName = 'TestMe';
            acc2.LastName = 'Lasting';
            acc2.AgentNet_ID__c = 'AgentNet_ID__c test';
            acc2.Salutation = 'Mrs.';
            acc2.CurrencyIsoCode = 'THB';
            acc2.Subscription_Start_Date__c = system.today().addMonths(-10);
            acc2.BillingStreet = 'test';
            acc2.BillingCity = 'test';
            acc2.BillingCountry = 'Thailand';
            acc2.BillingPostalCode = '83210';
            // acc2.BillingState = 'test';
            acc2.Current_Subscription_Code__c = 'abc';
            acc2.PersonEmail = 'test@yuwni.com';
            acc2.Account_Rule_Code__c = 'test';
            acc2.Status__c = 'Active';
            acc2.Country__c = 'Thailand';
            acc2.Agency__c = agency.id;
            acc2.Subsidiary__c = subId;
            acc2.Subscription_End_Date__c = Date.newInstance(2019, 12, 9);
            acc2.Loyalty_Start_Date__c = Date.newInstance(2018, 12, 9);
            acc2.RecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Agent').getRecordTypeId();
            acc2.VIP_Campaign__c = 'VIP Advance SC-1';
            acc2.Approval_Status__c = '';
            acc2.PersonMobilePhone = '876544';
            acc2.Mobile_Country__c='66';
            acc2.CEA_Salesperson_Number__c='J123456H';
            listAccount.add(acc2);
            
            Account acc3 = new Account();
            PGTestDataFactory_v2.initSetupData();
            acc3.FirstName = 'TestMe';
            acc3.LastName = 'Lasting';
            acc3.AgentNet_ID__c = 'AgentNet_ID__c test';
            acc3.Salutation = 'Mrs.';
            acc3.CurrencyIsoCode = 'THB';
            acc3.Subscription_Start_Date__c = system.today().addMonths(-10);
            acc3.BillingStreet = 'test';
            acc3.BillingCity = 'test';
            acc3.BillingCountry = 'Thailand';
            acc3.BillingPostalCode = '83210';
            // acc3.BillingState = 'test';
            acc3.Current_Subscription_Code__c = 'abc';
            acc3.PersonEmail = 'test@yuwni.com';
            acc3.Account_Rule_Code__c = 'test';
            acc3.Status__c = 'Active';
            acc3.Country__c = 'Thailand';
            acc3.Agency__c = agency.id;
            acc3.Subsidiary__c = subId;
            acc3.Subscription_End_Date__c = Date.newInstance(2019, 12, 9);
            acc3.Loyalty_Start_Date__c = Date.newInstance(2018, 12, 9);
            acc3.RecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Agent').getRecordTypeId();
            acc3.VIP_Campaign__c = 'VIP Advance SC-1';
            acc3.Approval_Status__c = '';
            acc3.CEA_Salesperson_Number__c='X123456R';
            acc.PersonBirthdate=system.today();
            acc3.PersonMobilePhone='132453678';
            acc3.Mobile_Country__c='66';
            acc3.PersonMobilePhone = '876544';
            listAccount.add(acc3);
            
            PGAccountTriggerHandler.setQualifyAgentReferral(listAccount);
            insert listAccount;
            acc3.LocalLanguage_last_name__c ='testLast';
            acc3.localLanguage_First_name__c ='testFirst';
            acc3.FirstName = 'First';
            acc3.LastName = 'Last';
            //acc3.Customer_Type__c='Owner';
            update acc3;
            listAccount[0].Subscription_End_Date__c = Date.newInstance(2019, 12, 9);
            listAccount[0].Loyalty_Start_Date__c = Date.newInstance(2017, 12, 9);
            update listAccount;
            
            Account ac = [Select Id,name,PersonContactId,VIP_Campaign__c from Account where Id = : acc2.Id limit 1];
            
            Campaign cma = new Campaign();
            cma.Name = ac.Name;
            cma.Country__c = 'Thailand';
            cma.IsActive = true;
            cma.EndDate = system.today().addDays(-2);
            cma.CurrencyIsoCode = 'THB';
            cma.VIP_Quota__c = 1;
            insert cma;
            
            CampaignMember cmp = new CampaignMember();
            cmp.ContactId = ac.PersonContactId;
            cmp.Status = 'Approved';
            cmp.CampaignId = cma.Id;
            insert cmp;
            
            Map<Id,Account> oldMap = new Map<Id,Account>();
            PGAccountTriggerHandler.updatePGTenure(listAccount, oldMap);
            PGAccountTriggerHandler.increasecoverage();
            Test.stopTest();
        }
    }
    public testMethod static void runTest4() {
        Test.startTest();
        User thisuser = [SELECT Id,Subsidiary__c FROM User WHERE country = 'Singapore' and isActive = true and profile.name = 'System Administrator' LIMIT 1];
        System.runAs(thisuser){
            Trigger_Execute__c customsetting=new Trigger_Execute__c();
            customsetting.Name='PGAccountTrigger';
            customsetting.Enable_del__c=true;
            insert customsetting;
            
            Trigger_Execute__c TE = new Trigger_Execute__c();
            TE.Name = 'PGCampMemberTrigger';
            TE.Enable_del__c = true;
            insert TE;
            
            Rewards_Calculator__c customsetting1  = new Rewards_Calculator__c();
            customsetting1.Name='Singapore';
            customsetting1.X_factor__c=8;
            customsetting1.Y_factor__c=5;
            customsetting1.country__c='Singapore';
            insert customsetting1;
            
            Trigger_Execute__c PGAgentRewardTrigger=new Trigger_Execute__c();
            PGAgentRewardTrigger.Name='PGAgentRewardTrigger';
            PGAgentRewardTrigger.Enable_del__c=true;
            insert PGAgentRewardTrigger;
            
            id subId = PGTestDataFactory.createSubsidiary().Id;
            list<Account> listAccount1 = new list<Account>();
            Account agency = new Account();
            PGTestDataFactory_v2.initSetupData();
            agency.name = 'Unit Test Agency';
            agency.Agency_Id__c = '40574';
            agency.CEA_License__c = 'CEAUNittest1';
            agency.RecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Agency').getRecordTypeId();
            agency.Country__c = 'Singapore';
            agency.Subsidiary__c = subId;
            listAccount1.add(agency);
            
            Media__c newMedia = new Media__c();
            newMedia.Account__c = listAccount1[0].id;
            newMedia.CurrencyIsoCode = 'SGD';
            newMedia.IsActive__c = True;
            insert newMedia;
            
            Blob bodyblob = Blob.valueOf('PG Agency default');
            Contentversion cv = new contentversion(title ='PG Agency default',PathOnClient ='PG Agency default.jpg',versiondata = bodyblob,origin ='H');
            insert cv;
            
            ContentVersion conVersion = [SELECT Id, ContentSize ,PathOnClient,Title,ContentDocumentId FROM ContentVersion WHERE Id =: cv.id];
            ContentDocumentLink cdl = new ContentDocumentLink();
            cdl.ContentDocumentId = conVersion.ContentDocumentId;
            cdl.LinkedEntityId = newMedia.id;
            cdl.ShareType = 'V';
            cdl.Visibility = 'AllUsers'; 
            insert cdl;
            insert listAccount1;
            
            list<Account> listAccount = new list<Account>();
            
            Account accReward = new Account();
            PGTestDataFactory_v2.initSetupData();
            accReward.FirstName = 'TestMe';
            accReward.LastName = 'Lasting';
            accReward.AgentNet_ID__c = 'AgentNet_ID__c test';
            accReward.Salutation = 'Mrs.';
            accReward.CurrencyIsoCode = 'SGD';
            accReward.Subscription_Start_Date__c = system.today().addMonths(-10);
            accReward.BillingStreet = 'test';
            accReward.BillingCity = 'test';
            accReward.BillingCountry = 'Singapore';
            accReward.BillingPostalCode = '8373';
            //  acc.BillingState = 'test';
            accReward.Current_Subscription_Code__c = 'abc';
            accReward.PersonEmail = 'accReward@yuni.com';
            accReward.Account_Rule_Code__c = 'test';
            accReward.Status__c = 'Trial';
            accReward.Country__c = 'Singapore';
            accReward.Agency__c = agency.id;
            accReward.Subsidiary__c = subId;
            accReward.CEA_Salesperson_Number__c='A678996A';
            accReward.Reward_Points__c = 600;
            accReward.Reward_Tier__c = 'Gold';
            accReward.PersonBirthdate=system.today();
            accReward.Subscription_End_Date__c = Date.newInstance(2030, 12, 9);
            accReward.Subscription_Start_Date__c = System.today();
            accReward.Account_Rule_Code__c ='Standard';
            accReward.Loyalty_Start_Date__c = Date.newInstance(2018, 12, 9);
            accReward.RecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Agent').getRecordTypeId();
            accReward.VIP_Campaign__c = 'VIP Advance SC';
            accReward.Approval_Status__c = 'Test';
            accReward.Created_From_AdminNet__c = true;
            accReward.Mobile_Country__c = '60';
            listAccount.add(accReward);
            
            insert listAccount;
            accReward.Status__c = 'Active';
            update accReward;
            
            Account accReward1 = new Account();
            PGTestDataFactory_v2.initSetupData();
            accReward1.FirstName = 'TestMe1';
            accReward1.LastName = 'Lasting1';
            accReward1.AgentNet_ID__c = 'AgentNet_ID__c test1';
            accReward1.Salutation = 'Mrs.';
            accReward1.CurrencyIsoCode = 'SGD';
            accReward1.Subscription_Start_Date__c = system.today().addMonths(-10);
            accReward1.BillingStreet = 'test';
            accReward1.BillingCity = 'test';
            accReward1.BillingCountry = 'Singapore';
            accReward1.BillingPostalCode = '8373';
            //  acc.BillingState = 'test';
            accReward1.Current_Subscription_Code__c = 'abc';
            accReward1.PersonEmail = 'accReward@yuni.com';
            accReward1.Account_Rule_Code__c = 'test';
            accReward1.Status__c = 'Trial';
            accReward1.Country__c = 'Singapore';
            accReward1.Agency__c = agency.id;
            accReward1.Subsidiary__c = subId;
            accReward1.CEA_Salesperson_Number__c='A678996A';
            accReward1.Reward_Points__c = 700;
            accReward1.Reward_Tier__c = 'Gold';
            accReward1.PersonBirthdate=system.today();
            accReward1.Subscription_End_Date__c = Date.newInstance(2030, 12, 9);
            accReward1.Subscription_Start_Date__c = System.today();
            accReward1.Account_Rule_Code__c ='Beginner';
            accReward1.Loyalty_Start_Date__c = Date.newInstance(2018, 12, 9);
            accReward1.RecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Agent').getRecordTypeId();
            accReward1.VIP_Campaign__c = 'VIP Advance SC';
            accReward1.Approval_Status__c = 'Test';
            accReward1.Created_From_AdminNet__c = true;
            accReward1.Status__c = 'Active';
            accReward1.Mobile_Country__c = '65';
            listAccount.add(accReward1);
            PGAccountTriggerHandler.publishRewardPoints(listAccount,null);
        }
        Test.stopTest();
    }
    
    public testMethod static void runTest5() {
        User thisUser = [SELECT Id,Subsidiary__c FROM User WHERE country = 'Thailand' and isActive = true and profile.name = 'TH B2C Sales User' Limit 1];
        System.runAs (thisUser) {
            Test.startTest();
            Trigger_Execute__c customsetting=new Trigger_Execute__c();
            customsetting.Name='PGAccountTrigger';
            customsetting.Enable_del__c=true;
            insert customsetting;
            
            Trigger_Execute__c TE = new Trigger_Execute__c();
            TE.Name = 'PGCampMemberTrigger';
            TE.Enable_del__c = true;
            insert TE;
            
            id subId = PGTestDataFactory.createSubsidiary().Id;
            list<Account> listAccount1 = new list<Account>();
            Account agency = new Account();
            PGTestDataFactory_v2.initSetupData();
            agency.name = 'Unit Test Agency';
            agency.Agency_Id__c = '40574';
            agency.CEA_License__c = 'CEAUNittest1';
            agency.RecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Agency').getRecordTypeId();
            agency.Country__c = 'Thailand';
            agency.Subsidiary__c = subId;
            listAccount1.add(agency);
            
            Media__c newMedia = new Media__c();
            newMedia.Account__c = listAccount1[0].id;
            newMedia.CurrencyIsoCode = 'SGD';
            newMedia.IsActive__c = True;
            insert newMedia;
            
            Blob bodyblob = Blob.valueOf('PG Agency default');
            Contentversion cv = new contentversion(title ='PG Agency default',PathOnClient ='PG Agency default.jpg',versiondata = bodyblob,origin ='H');
            insert cv;
            
            ContentVersion conVersion = [SELECT Id, ContentSize ,PathOnClient,Title,ContentDocumentId FROM ContentVersion WHERE Id =: cv.id];
            ContentDocumentLink cdl = new ContentDocumentLink();
            cdl.ContentDocumentId = conVersion.ContentDocumentId;
            cdl.LinkedEntityId = newMedia.id;
            cdl.ShareType = 'V';
            cdl.Visibility = 'AllUsers'; 
            insert cdl;
            insert listAccount1;
            
            list<Account> listAccount = new list<Account>();
            Account acc = new Account();
            PGTestDataFactory_v2.initSetupData();
            acc.FirstName = 'TestMe';
            acc.LastName = 'Lasting';
            acc.AgentNet_ID__c = 'AgentNet_ID__c test';
            acc.Salutation = 'Mrs.';
            acc.CurrencyIsoCode = 'THB';
            acc.PersonMobilePhone = '476867687';
            acc.PersonBirthdate = system.today().addDays(-30);
            acc.Subscription_Start_Date__c = system.today().addMonths(-10);
            acc.BillingStreet = 'test';
            acc.BillingCity = 'test';
            acc.Reward_Points__c = 700;
            acc.Reward_Tier__c = 'Gold';
            acc.BillingCountry = 'Thailand';
            acc.BillingPostalCode = '83736';
            //  acc.BillingState = 'test';
            acc.Current_Subscription_Code__c = 'abc';
            acc.PersonEmail = 'test@yuni.com';
            acc.Account_Rule_Code__c = 'Standard';
            acc.Status__c = 'Active';
            acc.Country__c = 'Thailand';
            acc.Mobile_Country__c = '66';
            acc.Agency__c = agency.id;
            acc.Subsidiary__c = subId;
            acc.CEA_Salesperson_Number__c='R123456H';
            acc.PersonBirthdate=system.today();
            acc.Subscription_End_Date__c = Date.newInstance(2019, 12, 9);
            acc.Loyalty_Start_Date__c = Date.newInstance(2018, 12, 9);
            acc.RecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Agent').getRecordTypeId();
            acc.VIP_Campaign__c = 'VIP Advance SC';
            acc.Approval_Status__c = 'Test';
            acc.Created_From_AdminNet__c = true;
            
            Account accReward = new Account();
            PGTestDataFactory_v2.initSetupData();
            accReward.FirstName = 'TestMe';
            accReward.LastName = 'Lasting';
            accReward.AgentNet_ID__c = 'AgentNet_ID__c test';
            accReward.Salutation = 'Mrs.';
            accReward.CurrencyIsoCode = 'THB';
            accReward.Subscription_Start_Date__c = system.today().addMonths(-10);
            accReward.BillingStreet = 'test';
            accReward.BillingCity = 'test';
            accReward.PersonMobilePhone = '479867687';
            accReward.BillingCountry = 'Thailand';
            accReward.BillingPostalCode = '83723';
            //  acc.BillingState = 'test';
            accReward.Mobile_Country__c = '66';
            accReward.Current_Subscription_Code__c = 'abc';
            accReward.PersonEmail = 'accReward@yuni.com';
            accReward.Account_Rule_Code__c = 'Business';
            accReward.Status__c = 'Active';
            accReward.Country__c = 'Thailand';
            accReward.Agency__c = agency.id;
            accReward.Reward_Points__c = 600;
            accReward.Reward_Tier__c = 'Gold';
            accReward.Subsidiary__c = subId;
            accReward.CEA_Salesperson_Number__c='A678996A';
            accReward.PersonBirthdate=system.today();
            accReward.Subscription_End_Date__c = Date.newInstance(2030, 12, 9);
            accReward.Subscription_Start_Date__c = System.today();
            accReward.Account_Rule_Code__c ='Standard';
            accReward.Loyalty_Start_Date__c = Date.newInstance(2018, 12, 9);
            accReward.RecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Agent').getRecordTypeId();
            accReward.VIP_Campaign__c = 'VIP Advance SC';
            accReward.Approval_Status__c = 'Test';
            accReward.Created_From_AdminNet__c = true;
            listAccount.add(accReward);
            listAccount.add(acc); 
            
            Account acc2 = new Account();
            PGTestDataFactory_v2.initSetupData();
            acc2.FirstName = 'TestMe';
            acc2.LastName = 'Lasting';
            
            acc2.AgentNet_ID__c = 'AgentNet_ID__c test';
            acc2.Salutation = 'Mrs.';
            acc2.CurrencyIsoCode = 'THB';
            acc2.Subscription_Start_Date__c = system.today().addMonths(-10);
            acc2.BillingStreet = 'test';
            acc2.PersonMobilePhone = '476869687';
            acc.BillingCity = 'test';
            acc.BillingCountry = 'Thailand';
            acc2.Mobile_Country__c = '66';
            acc2.BillingPostalCode = '83273';
            //acc2.BillingState = 'test';
            acc2.Current_Subscription_Code__c = 'abc';
            acc2.PersonBirthdate = system.today();
            acc2.PersonEmail = 'test@yuwni.com';
            acc2.Status__c = 'Active';
            acc2.Country__c = 'Thailand';
            acc2.Agency__c = agency.id;
            acc2.Subsidiary__c = subId;
            acc2.Account_Rule_Code__c = 'PRO';
            acc2.CEA_Salesperson_Number__c='R123456H';
            acc2.Subscription_End_Date__c = Date.newInstance(2019, 12, 9);
            acc2.Loyalty_Start_Date__c = Date.newInstance(2018, 12, 9);
            acc2.RecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Agent').getRecordTypeId();
            acc2.VIP_Campaign__c = 'VIP Advance SC-1';
            acc2.Approval_Status__c = '';
            acc2.Reward_Points__c = 700;
            acc2.Reward_Tier__c = 'Gold';
            listAccount.add(acc2);
            PGAccountTriggerHandler.setQualifyAgentReferral(listAccount);
            insert listAccount;
            PGAccountTriggerHandler.markAsTestAccount(listAccount,null);
            
            listAccount[0].Subscription_End_Date__c = Date.newInstance(2019, 12, 9);
            listAccount[0].Loyalty_Start_Date__c = Date.newInstance(2017, 12, 9);
            
            update listAccount;
            
            Account ac = [Select Id,PersonContactId,VIP_Campaign__c from Account where Id = : acc2.Id limit 1];
            listAccount[2].Account_Rule_Code__c = 'CORP';
            update listAccount[2];
            
            
            PGAccountTriggerHandler.accountTriggerRecursion = false;
            
            Map<Id,Account> oldMap = new Map<Id,Account>();
            PGAccountTriggerHandler.updatePGTenure(listAccount, oldMap);
            PGAccountTriggerHandler.publishRewardPoints(listAccount,null);
            acc2.Approval_Status__c = acc2.VIP_Campaign__c+'Approved';
            acc2.VIP__c = true;
            update acc2;
            acc.Status__c = 'Active';
            update acc;
            Test.stopTest();
        }
    }
    
    public testMethod static void runTest6() {
        User thisUser = [SELECT Id,Subsidiary__c FROM User WHERE country = 'Thailand' and isActive = true and profile.name = 'TH B2C Sales User' Limit 1];
        System.runAs (thisUser) {
            Test.startTest();
            Trigger_Execute__c customsetting=new Trigger_Execute__c();
            customsetting.Name='PGAccountTrigger';
            customsetting.Enable_del__c=true;
            insert customsetting;
            
            Trigger_Execute__c TE = new Trigger_Execute__c();
            TE.Name = 'PGCampMemberTrigger';
            TE.Enable_del__c = true;
            insert TE;
            
            Rewards_Calculator__c customsetting1  = new Rewards_Calculator__c();
            customsetting1.Name='Thailand';
            customsetting1.X_factor__c=8;
            customsetting1.Y_factor__c=5;
            customsetting1.country__c='Thailand';
            insert customsetting1;
            
            Trigger_Execute__c PGAgentRewardTrigger=new Trigger_Execute__c();
            PGAgentRewardTrigger.Name='PGAgentRewardTrigger';
            PGAgentRewardTrigger.Enable_del__c=true;
            insert PGAgentRewardTrigger;
            
            id subId = PGTestDataFactory.createSubsidiary().Id;
            list<Account> listAccount1 = new list<Account>();
            Account agency = new Account();
            PGTestDataFactory_v2.initSetupData();
            agency.name = 'Unit Test Agency';
            agency.Agency_Id__c = '40574';
            agency.CEA_License__c = 'CEAUNittest1';
            agency.RecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Agency').getRecordTypeId();
            agency.Country__c = 'Thailand';
            agency.Subsidiary__c = subId;
            listAccount1.add(agency);
            
            Media__c newMedia = new Media__c();
            newMedia.Account__c = listAccount1[0].id;
            newMedia.CurrencyIsoCode = 'SGD';
            newMedia.IsActive__c = True;
            insert newMedia;
            
            Blob bodyblob = Blob.valueOf('PG Agency default');
            Contentversion cv = new contentversion(title ='PG Agency default',PathOnClient ='PG Agency default.jpg',versiondata = bodyblob,origin ='H');
            insert cv;
            
            ContentVersion conVersion = [SELECT Id, ContentSize ,PathOnClient,Title,ContentDocumentId FROM ContentVersion WHERE Id =: cv.id];
            ContentDocumentLink cdl = new ContentDocumentLink();
            cdl.ContentDocumentId = conVersion.ContentDocumentId;
            cdl.LinkedEntityId = newMedia.id;
            cdl.ShareType = 'V';
            cdl.Visibility = 'AllUsers'; 
            insert cdl;
            insert listAccount1;
            
            list<Account> listAccount = new list<Account>();
            
            Account accReward = new Account();
            PGTestDataFactory_v2.initSetupData();
            accReward.FirstName = 'TestMe';
            accReward.LastName = 'Lasting';
            accReward.AgentNet_ID__c = 'AgentNet_ID__c test';
            accReward.Salutation = 'Mrs.';
            accReward.CurrencyIsoCode = 'THB';
            accReward.Subscription_Start_Date__c = system.today().addMonths(-10);
            accReward.BillingStreet = 'test';
            accReward.BillingCity = 'test';
            accReward.BillingCountry = 'Thailand';
            accReward.BillingPostalCode = '83473';
            //  acc.BillingState = 'test';
            accReward.Current_Subscription_Code__c = 'abc';
            accReward.PersonEmail = 'accReward@yuni.com';
            accReward.Account_Rule_Code__c = 'test';
            accReward.Status__c = 'Trial';
            accReward.Country__c = 'Thailand';
            accReward.Agency__c = agency.id;
            accReward.Subsidiary__c = subId;
            accReward.CEA_Salesperson_Number__c='A678996A';
            accReward.Reward_Points__c = 600;
            accReward.Reward_Tier__c = 'Gold';
            accReward.PersonBirthdate=system.today();
            accReward.Subscription_End_Date__c = Date.newInstance(2030, 12, 9);
            accReward.Mobile_Country__c = '66';
            accReward.PersonMobilePhone = '986576878';
            accReward.Subscription_Start_Date__c = System.today();
            accReward.Account_Rule_Code__c ='Pro';
            accReward.Loyalty_Start_Date__c = Date.newInstance(2018, 12, 9);
            accReward.RecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Agent').getRecordTypeId();
            accReward.VIP_Campaign__c = 'VIP Advance SC';
            accReward.Approval_Status__c = 'Test';
            accReward.Created_From_AdminNet__c = true;
            listAccount.add(accReward);
            
            insert listAccount;
            accReward.Status__c = 'Active';
            update accReward;
            
            Account accReward1 = new Account();
            PGTestDataFactory_v2.initSetupData();
            accReward1.FirstName = 'TestMe1';
            accReward1.LastName = 'Lasting1';
            accReward1.AgentNet_ID__c = 'AgentNet_ID__c test1';
            accReward1.Salutation = 'Mrs.';
            accReward1.CurrencyIsoCode = 'THB';
            accReward1.Subscription_Start_Date__c = system.today().addMonths(-10);
            accReward1.BillingStreet = 'test';
            accReward1.BillingCity = 'test';
            accReward1.BillingCountry = 'Thailand';
            accReward1.BillingPostalCode = '83373';
            //  acc.BillingState = 'test';
            accReward1.Current_Subscription_Code__c = 'abc';
            accReward1.PersonEmail = 'accReward@yuni.com';
            accReward1.Account_Rule_Code__c = 'test';
            accReward1.Status__c = 'Trial';
            accReward1.Country__c = 'Thailand';
            accReward1.Agency__c = agency.id;
            accReward1.Subsidiary__c = subId;
            accReward1.CEA_Salesperson_Number__c='A678996A';
            accReward1.Reward_Points__c = 700;
            accReward1.Reward_Tier__c = 'Gold';
            accReward1.PersonBirthdate=system.today();
            accReward1.Subscription_End_Date__c = Date.newInstance(2030, 12, 9);
            accReward1.Subscription_Start_Date__c = System.today();
            accReward1.Account_Rule_Code__c ='Pro';
            accReward1.Loyalty_Start_Date__c = Date.newInstance(2018, 12, 9);
            accReward1.RecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Agent').getRecordTypeId();
            accReward1.VIP_Campaign__c = 'VIP Advance SC';
            accReward1.Approval_Status__c = 'Test';
            accReward1.Created_From_AdminNet__c = true;
            accReward1.Status__c = 'Active';
            listAccount.add(accReward1);
            PGAccountTriggerHandler.publishRewardPoints(listAccount,null);            
            Test.stopTest();   
        }  
    }   
}