unpackaged/main/default/objects/Account/fields/Account_Rule_Code__c.field-meta.xml
<CustomField>
    <fullName>Account_Rule_Code__c</fullName>
    <defaultValue>IF( $RecordType.DeveloperName = &quot;Agent&quot;, &quot;TRIAL&quot;, &quot;&quot;)</defaultValue>
    <description>Denotes account rule code (short text) for the account rule</description>
    <inlineHelpText>Denotes account rule code (short text) for the account rule</inlineHelpText>
    <label>Account Rule Code</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/Agency__c.field-meta.xml
<CustomField>
    <fullName>Agency__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Denotes the real estate/property agency to which the agent belongs to</description>
    <inlineHelpText>Denotes the real estate/property agency to which the agent belongs to</inlineHelpText>
    <label>Agency</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>Please select proper Agency Account.</errorMessage>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Agency</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Agents</relationshipLabel>
    <relationshipName>Agency</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/Agency_Id__c.field-meta.xml
<CustomField>
    <fullName>Agency_Id__c</fullName>
    <description>Denotes the unique id of an agency in PG system</description>
    <externalId>true</externalId>
    <inlineHelpText>Denotes the unique id of an agency in PG system</inlineHelpText>
    <label>Agency Id</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/AgentNet_ID__c.field-meta.xml
<CustomField>
    <fullName>AgentNet_ID__c</fullName>
    <description>Denotes a numeric id of agents in PG system</description>
    <inlineHelpText>Denotes a numeric id of agents in PG system</inlineHelpText>
    <label>AgentNet ID</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/Approval_Status__c.field-meta.xml
<CustomField>
    <fullName>Approval_Status__c</fullName>
    <description>Denotes the approval status for an agent in the VIP approval process</description>
    <inlineHelpText>Denotes the approval status for an agent in the VIP approval process</inlineHelpText>
    <label>Approval Status</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/CEA_License__c.field-meta.xml
<CustomField>
    <fullName>CEA_License__c</fullName>
    <description>Denotes the agency license number registered under a governing authority</description>
    <externalId>true</externalId>
    <inlineHelpText>Denotes the agency registration number issued by CEA for SG agencies and MIEA for MY agencies</inlineHelpText>
    <label>Agency Identification Number</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/CEA_Salesperson_Number__c.field-meta.xml
<CustomField>
    <fullName>CEA_Salesperson_Number__c</fullName>
    <description>Denotes the agent license number registered under a governing authority</description>
    <inlineHelpText>Denotes the agent registration number issued by CEA for SG agents and MIEA for MY agents</inlineHelpText>
    <label>Agent Identification Number</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/Country__c.field-meta.xml
<CustomField>
    <fullName>Country__c</fullName>
    <defaultValue>if(  BEGINS($UserRole.Name, &quot;TH&quot;),&quot;Thailand&quot;,if(ISPICKVAL($User.Subsidiary__c,&quot;MyProperty Data Sdn. Bhd.&quot;),&quot;Malaysia&quot;,&quot;&quot;))</defaultValue>
    <description>Denotes the country of an account</description>
    <inlineHelpText>Denotes the country of an account</inlineHelpText>
    <label>Country</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Country</valueSetName>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Account/fields/Current_Subscription_Code__c.field-meta.xml
<CustomField>
    <fullName>Current_Subscription_Code__c</fullName>
    <label>Current Subscription Code</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/Loyalty_Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Loyalty_Start_Date__c</fullName>
    <description>Denotes the loyalty start date of an agent</description>
    <inlineHelpText>Denotes the loyalty start date of an agent</inlineHelpText>
    <label>Loyalty Start Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/Next_Subscription_Activation_Date__c.field-meta.xml
<CustomField>
    <fullName>Next_Subscription_Activation_Date__c</fullName>
    <description>Denotes the next subscription activation date after a successful purchase of a Agent subscription</description>
    <inlineHelpText>Denotes the next subscription activation date after a successful purchase of a Agent subscription</inlineHelpText>
    <label>Next Subscription Activation Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>Denotes the status of an agent in the agent lifecycle</description>
    <inlineHelpText>Denotes the status of an agent in the agent lifecycle</inlineHelpText>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Trial</fullName>
            </value>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Downgraded</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Suspended</fullName>
            </value>
            <value>
                <fullName>Expired</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Account/fields/Subscription_Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Subscription_Start_Date__c</fullName>
    <description>Denotes the start date of agent&#39;s current subscription</description>
    <inlineHelpText>Denotes the start date of agent&#39;s current subscription</inlineHelpText>
    <label>Subscription Start Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/Subsidiary__c.field-meta.xml
<CustomField>
    <fullName>Subsidiary__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Denotes the PG subsidiary to which the account belongs to</description>
    <inlineHelpText>Denotes the PG subsidiary to which the account belongs to</inlineHelpText>
    <label>Subsidiary</label>
    <referenceTo>Subsidiary__c</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Account/recordTypes/Agency.recordType-meta.xml
<RecordType>
    <fullName>Agency</fullName>
    <active>true</active>
    <label>Agency</label>
</RecordType>

unpackaged/main/default/objects/LSD_Update__c/LSD_Update__c.object-meta.xml
<CustomObject>
    <description>Used to update the loyalty start date</description>
    <label>LSD Update</label>
    <nameField>
        <displayFormat>LU-{000000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>LSD Updates</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/LSD_Update__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>Loyalty_Start_Dates</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/LSD_Update__c/fields/Approval_Status__c.field-meta.xml
<CustomField>
    <fullName>Approval_Status__c</fullName>
    <label>Approval Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Submit for approval</fullName>
            </value>
            <value>
                <fullName>Not Required</fullName>
                <default>true</default>
                <label>Not Required</label>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/LSD_Update__c/fields/Loyalty_Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Loyalty_Start_Date__c</fullName>
    <label>Loyalty Start Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/Media__c/Media__c.object-meta.xml
<CustomObject>
    <label>Media</label>
    <nameField>
        <displayFormat>M-{0000000}</displayFormat>
        <label>Agency Logo Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Media</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Media__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Denotes the account to which record is bind to</description>
    <inlineHelpText>Denotes the account to which record is bind to</inlineHelpText>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>Agency_Logo</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Subsidiary__c/Subsidiary__c.object-meta.xml
<CustomObject>
    <description>This is a custom object to contain the information on Subsidiary and Country</description>
    <label>Subsidiary</label>
    <nameField>
        <label>Subsidiary Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Subsidiaries</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Subsidiary__c/fields/Country__c.field-meta.xml
<CustomField>
    <fullName>Country__c</fullName>
    <description>Values from global picklist</description>
    <label>Country</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Country</valueSetName>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Trigger_Execute__c/Trigger_Execute__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>Trigger Execute</label>
</CustomObject>

unpackaged/main/default/objects/Trigger_Execute__c/fields/Enable_del__c.field-meta.xml
<CustomField>
    <fullName>Enable_del__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Enable del</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/User/fields/Subsidiary__c.field-meta.xml
<CustomField>
    <fullName>Subsidiary__c</fullName>
    <label>Subsidiary</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Subsidiary</valueSetName>
    </valueSet>
</CustomField>

unpackaged/main/default/classes/BatchToUpdateAccountLSD_Test.cls
@isTest
public class BatchToUpdateAccountLSD_Test {
    @isTest
    public static void updateLSD(){
        User thisuser = [SELECT Id,Subsidiary__c FROM User WHERE country = 'Singapore' and isActive = true and profile.name = 'System Administrator' LIMIT 1];
        System.runAs(thisuser){
            Trigger_Execute__c customsetting=new Trigger_Execute__c();
            customsetting.Name='PGAccountTrigger';
            customsetting.Enable_del__c=true;
            insert customsetting;
            
            Trigger_Execute__c TE = new Trigger_Execute__c();
            TE.Name = 'PGLSDUpdateTrigger';
            TE.Enable_del__c = true;
            insert TE;
            
            id subId = PGTestDataFactory.createSubsidiary().Id;
            list<Account> listAccount1 = new list<Account>();
            Account agency = new Account();
            PGTestDataFactory_v2.initSetupData();
            agency.name = 'Unit Test Agency';
            agency.Agency_Id__c = '40574';
            agency.CEA_License__c = 'CEAUNittest1';
            agency.RecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Agency').getRecordTypeId();
            agency.Country__c = 'Singapore';
            agency.Subsidiary__c = subId;
            listAccount1.add(agency);
            
            Media__c newMedia = new Media__c();
            newMedia.Account__c = listAccount1[0].id;
            newMedia.CurrencyIsoCode = 'SGD';
            newMedia.IsActive__c = True;
            insert newMedia;
            
            Blob bodyblob = Blob.valueOf('PG Agency default');
            Contentversion cv = new contentversion(title ='PG Agency default',PathOnClient ='PG Agency default.jpg',versiondata = bodyblob,origin ='H');
            insert cv;
            
            ContentVersion conVersion = [SELECT Id, ContentSize ,PathOnClient,Title,ContentDocumentId FROM ContentVersion WHERE Id =: cv.id];
            ContentDocumentLink cdl = new ContentDocumentLink();
            cdl.ContentDocumentId = conVersion.ContentDocumentId;
            cdl.LinkedEntityId = newMedia.id;
            cdl.ShareType = 'V';
            cdl.Visibility = 'AllUsers'; 
            insert cdl;
            insert listAccount1;
            
            PGTestDataFactory_v2.initSetupData();    
            string accRectype = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Agent').getRecordTypeId();
            Account a = new Account();
            a.RecordTypeId = accRectype;
            a.LastName = 'PGAccount';
            a.salutation = 'Mr.';
            a.FirstName = 'abc';
            a.CurrencyIsoCode = 'SGD';
            a.Subscription_Start_Date__c = system.today().addMonths(-10);
            a.BillingStreet = 'test';
            a.BillingCity = 'test';
            a.BillingCountry = 'Singapore';
            a.BillingPostalCode = '83735';
            a.Current_Subscription_Code__c = 'abc';
            a.Account_Rule_Code__c = 'test';
            a.AgentNet_ID__c = '123';
            a.PersonEmail = 'test@test.com';
            a.Country__c = 'Singapore';
            a.Status__c = 'Active';
            a.Next_Subscription_Activation_Date__c=System.todAY()-9;
            a.CEA_Salesperson_Number__c = 'S215463K';
            a.PersonBirthdate = system.today();
            a.Agency__c = agency.id;
            a.Subsidiary__c = subId;
            a.Loyalty_Start_Date__c = Date.newInstance(2017, 12, 9);
            insert a;
            
            LSD_Update__c lsd = new LSD_Update__c();
            lsd.Approval_Status__c ='Approved';
            lsd.Account__c =a.id;
            lsd.Loyalty_Start_Date__c = system.today();
            lsd.LastModifiedById = '0057F000005TAluQAG';
            insert lsd;
            
            Test.startTest();
            
            BatchToUpdateAccountLSD obj = new BatchToUpdateAccountLSD();
            DataBase.executeBatch(obj);
            
            Test.stopTest();
        }
    }
}