unpackaged/main/default/objects/Account/fields/Account_Rule_Code__c.field-meta.xml
<CustomField>
    <fullName>Account_Rule_Code__c</fullName>
    <defaultValue>IF( $RecordType.DeveloperName = &quot;Agent&quot;, &quot;TRIAL&quot;, &quot;&quot;)</defaultValue>
    <description>Denotes account rule code (short text) for the account rule</description>
    <inlineHelpText>Denotes account rule code (short text) for the account rule</inlineHelpText>
    <label>Account Rule Code</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/AgentNet_ID__c.field-meta.xml
<CustomField>
    <fullName>AgentNet_ID__c</fullName>
    <description>Denotes a numeric id of agents in PG system</description>
    <inlineHelpText>Denotes a numeric id of agents in PG system</inlineHelpText>
    <label>AgentNet ID</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/Birthdate_Verified__c.field-meta.xml
<CustomField>
    <fullName>Birthdate_Verified__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Denotes whether the birthdate of an agent is verified by PG</description>
    <inlineHelpText>Denotes whether the birthdate of an agent is verified by PG</inlineHelpText>
    <label>Birthdate Verified</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/CEA_Salesperson_Number__c.field-meta.xml
<CustomField>
    <fullName>CEA_Salesperson_Number__c</fullName>
    <description>Denotes the agent license number registered under a governing authority</description>
    <inlineHelpText>Denotes the agent registration number issued by CEA for SG agents and MIEA for MY agents</inlineHelpText>
    <label>Agent Identification Number</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/Country__c.field-meta.xml
<CustomField>
    <fullName>Country__c</fullName>
    <defaultValue>if(  BEGINS($UserRole.Name, &quot;TH&quot;),&quot;Thailand&quot;,if(ISPICKVAL($User.Subsidiary__c,&quot;MyProperty Data Sdn. Bhd.&quot;),&quot;Malaysia&quot;,&quot;&quot;))</defaultValue>
    <description>Denotes the country of an account</description>
    <inlineHelpText>Denotes the country of an account</inlineHelpText>
    <label>Country</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Country</valueSetName>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Account/fields/Current_Subscription_Code__c.field-meta.xml
<CustomField>
    <fullName>Current_Subscription_Code__c</fullName>
    <label>Current Subscription Code</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/Subscription_Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Subscription_Start_Date__c</fullName>
    <description>Denotes the start date of agent&#39;s current subscription</description>
    <inlineHelpText>Denotes the start date of agent&#39;s current subscription</inlineHelpText>
    <label>Subscription Start Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/User/fields/Webuser_ID__c.field-meta.xml
<CustomField>
    <fullName>Webuser_ID__c</fullName>
    <label>Webuser ID</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/classes/BatchToCreateActivityForContact_Test.cls
@isTest
public class BatchToCreateActivityForContact_Test {

    static testMethod void runTest() {
        
        Date startDate = system.today(); 
        Date endDate = system.today().AddDays(30);
        User runUsser = [Select id, Webuser_ID__c From User where id =: UserInfo.getUserId()];
        runUsser.Webuser_ID__c= 1;  
        update runUsser;   
        string resp = '';   
        string accRectype = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Agent').getRecordTypeId();        
        Account a = new Account();
         PGTestDataFactory_v2.initSetupData();    
        a.RecordTypeId = accRectype;  
        a.LastName = 'TestYuni';
        a.salutation = 'Mr.';
        a.FirstName = 'abc';
        a.CurrencyIsoCode = 'SGD';
        a.Subscription_Start_Date__c = system.today().addMonths(-10);
        a.BillingStreet = 'test';
        a.BillingCity = 'test';
        a.BillingCountry = 'Singapore';
        a.BillingPostalCode = '8373';
       // a.BillingState = 'test';
        a.Current_Subscription_Code__c = 'abc';
        a.Account_Rule_Code__c = 'test';
        a.AgentNet_ID__c = '123';
        a.PersonEmail = '12121assas@yahoo.com';
        a.Country__c = 'Singapore';
        a.Birthdate_Verified__c = true;
        a.CEA_Salesperson_Number__c='qwerty';
        a.PersonBirthdate=system.today();
        insert a;
        Test.startTest();
        Database.executeBatch(new BatchToCreateActivityForContact(),100);
        Test.stopTest();
        
    }     
}