unpackaged/main/default/objects/Account/fields/Account_Rule_Code__c.field-meta.xml
<CustomField>
    <fullName>Account_Rule_Code__c</fullName>
    <defaultValue>IF( $RecordType.DeveloperName = &quot;Agent&quot;, &quot;TRIAL&quot;, &quot;&quot;)</defaultValue>
    <description>Denotes account rule code (short text) for the account rule</description>
    <inlineHelpText>Denotes account rule code (short text) for the account rule</inlineHelpText>
    <label>Account Rule Code</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/AgentKey__c.field-meta.xml
<CustomField>
    <fullName>AgentKey__c</fullName>
    <description>Denotes a unique key specifying the countrycodes(SG,MY,TH,ID) and the unique id in PG system</description>
    <externalId>true</externalId>
    <inlineHelpText>Denotes a unique key specifying the countrycodes(SG,MY,TH,ID) and the unique id in PG system</inlineHelpText>
    <label>AgentKey</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/AgentNet_ID__c.field-meta.xml
<CustomField>
    <fullName>AgentNet_ID__c</fullName>
    <description>Denotes a numeric id of agents in PG system</description>
    <inlineHelpText>Denotes a numeric id of agents in PG system</inlineHelpText>
    <label>AgentNet ID</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/CEA_Salesperson_Number__c.field-meta.xml
<CustomField>
    <fullName>CEA_Salesperson_Number__c</fullName>
    <description>Denotes the agent license number registered under a governing authority</description>
    <inlineHelpText>Denotes the agent registration number issued by CEA for SG agents and MIEA for MY agents</inlineHelpText>
    <label>Agent Identification Number</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/Country__c.field-meta.xml
<CustomField>
    <fullName>Country__c</fullName>
    <defaultValue>if(  BEGINS($UserRole.Name, &quot;TH&quot;),&quot;Thailand&quot;,if(ISPICKVAL($User.Subsidiary__c,&quot;MyProperty Data Sdn. Bhd.&quot;),&quot;Malaysia&quot;,&quot;&quot;))</defaultValue>
    <description>Denotes the country of an account</description>
    <inlineHelpText>Denotes the country of an account</inlineHelpText>
    <label>Country</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Country</valueSetName>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Account/fields/Current_Subscription__c.field-meta.xml
<CustomField>
    <fullName>Current_Subscription__c</fullName>
    <label>Current Subscription</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/Current_Subscription_Code__c.field-meta.xml
<CustomField>
    <fullName>Current_Subscription_Code__c</fullName>
    <label>Current Subscription Code</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>Denotes the status of an agent in the agent lifecycle</description>
    <inlineHelpText>Denotes the status of an agent in the agent lifecycle</inlineHelpText>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Trial</fullName>
            </value>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Downgraded</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Suspended</fullName>
            </value>
            <value>
                <fullName>Expired</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Account/fields/Subscription_Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Subscription_Start_Date__c</fullName>
    <description>Denotes the start date of agent&#39;s current subscription</description>
    <inlineHelpText>Denotes the start date of agent&#39;s current subscription</inlineHelpText>
    <label>Subscription Start Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/classes/GurulandApi_Test.cls
@isTest
public class GurulandApi_Test {
    static testMethod void runTest() {
 PGTestDataFactory_v2.CreateTriggerExecuteCS('PGAccountTrigger',true);
        string accRectype = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Agent').getRecordTypeId();
        Account a = new Account();
        a.RecordTypeId = accRectype;
        a.LastName = 'Unit Test';
        a.salutation = 'Mr.';
        a.FirstName = 'Resend email';
        a.CurrencyIsoCode = 'SGD';
        a.Subscription_Start_Date__c = system.today().addMonths(-10);
        a.BillingStreet = 'test';
        a.BillingCity = 'test';
        a.BillingCountry = 'Singapore';
        a.BillingPostalCode = '8373';
       // a.BillingState = 'test';
        //a.Current_Subscription__c = 'Advance Account';
        a.Current_Subscription_Code__c = 'ADVANCE';
        a.Account_Rule_Code__c = 'test';
        a.Status__c = 'Pending';
        a.AgentNet_ID__c ='10244901';
        a.AgentKey__c = 'SG10244901';
        a.PersonEmail = 'resendemail@unittest.com';
        a.Country__c = 'Singapore';
        a.PersonBirthdate = system.today();
        a.CEA_Salesperson_Number__c = 'est';
        insert a;

        Test.StartTest();
        string agentkey = GurulandApi.getAgentNetKey(a.id);
        System.debug('Agentkey is ' + agentkey);

        // Set mock callout class
        Test.setMock(HttpCalloutMock.class, new GurulandApiMock());
        // This causes a fake response to be sent from the class that implements HttpCalloutMock.
        HttpResponse response = GurulandApi.callResendEndpoint(a.id);
        // Verify that the response received contains fake values
        String actualValue = response.getBody();
        system.debug(response.getBody());
        String expectedValue = '{"agentId":"10244901","code":"AG2000","message":"Resend verification email is successful."}';
        system.assertEquals(expectedValue, actualValue, 'Invalid HTTP Response body');
        system.assertEquals(200, response.getStatusCode(), 'Invalid Status Code');

        Test.stopTest();
    }

    static testMethod void runTest1() {
  PGTestDataFactory_v2.CreateTriggerExecuteCS('PGAccountTrigger',true);
        string accRectype = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Agent').getRecordTypeId();
        Account a = new Account();
        a.RecordTypeId = accRectype;
        a.LastName = 'Unit Test';
        a.salutation = 'Mr.';
        a.FirstName = 'Resend email';
        a.CurrencyIsoCode = 'SGD';
        a.Subscription_Start_Date__c = system.today().addMonths(-10);
        a.BillingStreet = 'test';
        a.BillingCity = 'test';
        a.BillingCountry = 'Singapore';
        a.BillingPostalCode = '8373';
       // a.BillingState = 'test';
        //a.Current_Subscription__c = 'Advance Account';
        a.Current_Subscription_Code__c = 'ADVANCE';
        a.Account_Rule_Code__c = 'test';
        a.Status__c = 'Pending';
        a.AgentNet_ID__c ='10244901';
        a.AgentKey__c = 'SG10244901';
        a.PersonEmail = 'resendemail@unittest.com';
        a.Country__c = 'Singapore';
        a.PersonBirthdate = system.today();
        a.CEA_Salesperson_Number__c = 'est';
        insert a;

        Test.StartTest();
        GurulandApi.callResendApi(a.Id);
        Test.stopTest();
    }

    static testMethod void runTest3() {
        PGTestDataFactory_v2.CreateTriggerExecuteCS('PGAccountTrigger',true);
        string accRectype = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Agent').getRecordTypeId();
        Account a = new Account();
        a.RecordTypeId = accRectype;
        a.LastName = 'Unit Test';
        a.salutation = 'Mr.';
        a.FirstName = 'Resend email';
        a.CurrencyIsoCode = 'SGD';
        a.Subscription_Start_Date__c = system.today().addMonths(-10);
        a.BillingStreet = 'test';
        a.BillingCity = 'test';
        a.BillingCountry = 'Malaysia';
        a.BillingPostalCode = '83732';
        // a.BillingState = 'test';
        //a.Current_Subscription__c = 'Advance Account';
        a.Current_Subscription_Code__c = 'ADVANCE';
        a.Account_Rule_Code__c = 'test';
        a.Status__c = 'Pending';
        a.AgentNet_ID__c ='10244901';
        a.AgentKey__c = 'MY10244901';
        a.PersonEmail = 'resendemail@unittest.com';
        a.Country__c = 'Malaysia';
        a.PersonBirthdate = system.today();
        a.CEA_Salesperson_Number__c = 'est';
        insert a;

        Test.StartTest();
        string agentkey = GurulandApi.getAgentNetKey(a.id);
        System.debug('Agentkey is ' + agentkey);

        // Set mock callout class
        Test.setMock(HttpCalloutMock.class, new GurulandApiMock());
        // This causes a fake response to be sent from the class that implements HttpCalloutMock.
        HttpResponse response = GurulandApi.callResendEndpoint(a.id);
        // Verify that the response received contains fake values
        String actualValue = response.getBody();
        system.debug(response.getBody());
        String expectedValue = '{"agentId":"10244901","code":"AG2000","message":"Resend verification email is successful."}';
        system.assertEquals(expectedValue, actualValue, 'Invalid HTTP Response body');
        system.assertEquals(200, response.getStatusCode(), 'Invalid Status Code');

        Test.stopTest();
    }
}