unpackaged/main/default/objects/Account/fields/Account_Rule_Code__c.field-meta.xml
<CustomField>
    <fullName>Account_Rule_Code__c</fullName>
    <defaultValue>IF( $RecordType.DeveloperName = &quot;Agent&quot;, &quot;TRIAL&quot;, &quot;&quot;)</defaultValue>
    <description>Denotes account rule code (short text) for the account rule</description>
    <inlineHelpText>Denotes account rule code (short text) for the account rule</inlineHelpText>
    <label>Account Rule Code</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/Agency__c.field-meta.xml
<CustomField>
    <fullName>Agency__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Denotes the real estate/property agency to which the agent belongs to</description>
    <inlineHelpText>Denotes the real estate/property agency to which the agent belongs to</inlineHelpText>
    <label>Agency</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>Please select proper Agency Account.</errorMessage>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Agency</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Agents</relationshipLabel>
    <relationshipName>Agency</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/Agency_Id__c.field-meta.xml
<CustomField>
    <fullName>Agency_Id__c</fullName>
    <description>Denotes the unique id of an agency in PG system</description>
    <externalId>true</externalId>
    <inlineHelpText>Denotes the unique id of an agency in PG system</inlineHelpText>
    <label>Agency Id</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/AgentNet_ID__c.field-meta.xml
<CustomField>
    <fullName>AgentNet_ID__c</fullName>
    <description>Denotes a numeric id of agents in PG system</description>
    <inlineHelpText>Denotes a numeric id of agents in PG system</inlineHelpText>
    <label>AgentNet ID</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/Approval_Status__c.field-meta.xml
<CustomField>
    <fullName>Approval_Status__c</fullName>
    <description>Denotes the approval status for an agent in the VIP approval process</description>
    <inlineHelpText>Denotes the approval status for an agent in the VIP approval process</inlineHelpText>
    <label>Approval Status</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/CEA_License__c.field-meta.xml
<CustomField>
    <fullName>CEA_License__c</fullName>
    <description>Denotes the agency license number registered under a governing authority</description>
    <externalId>true</externalId>
    <inlineHelpText>Denotes the agency registration number issued by CEA for SG agencies and MIEA for MY agencies</inlineHelpText>
    <label>Agency Identification Number</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/CEA_Salesperson_Number__c.field-meta.xml
<CustomField>
    <fullName>CEA_Salesperson_Number__c</fullName>
    <description>Denotes the agent license number registered under a governing authority</description>
    <inlineHelpText>Denotes the agent registration number issued by CEA for SG agents and MIEA for MY agents</inlineHelpText>
    <label>Agent Identification Number</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/Country__c.field-meta.xml
<CustomField>
    <fullName>Country__c</fullName>
    <defaultValue>if(  BEGINS($UserRole.Name, &quot;TH&quot;),&quot;Thailand&quot;,if(ISPICKVAL($User.Subsidiary__c,&quot;MyProperty Data Sdn. Bhd.&quot;),&quot;Malaysia&quot;,&quot;&quot;))</defaultValue>
    <description>Denotes the country of an account</description>
    <inlineHelpText>Denotes the country of an account</inlineHelpText>
    <label>Country</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Country</valueSetName>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Account/fields/Current_Subscription_Code__c.field-meta.xml
<CustomField>
    <fullName>Current_Subscription_Code__c</fullName>
    <label>Current Subscription Code</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/Loyalty_Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Loyalty_Start_Date__c</fullName>
    <description>Denotes the loyalty start date of an agent</description>
    <inlineHelpText>Denotes the loyalty start date of an agent</inlineHelpText>
    <label>Loyalty Start Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/Reward_Points__c.field-meta.xml
<CustomField>
    <fullName>Reward_Points__c</fullName>
    <label>Reward Points</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/Reward_Tier__c.field-meta.xml
<CustomField>
    <fullName>Reward_Tier__c</fullName>
    <label>Reward Tier</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Solitaire</fullName>
            </value>
            <value>
                <fullName>Titanium</fullName>
            </value>
            <value>
                <fullName>Platinum</fullName>
            </value>
            <value>
                <fullName>Gold</fullName>
            </value>
            <value>
                <fullName>Silver</fullName>
            </value>
            <value>
                <fullName>Elite</fullName>
            </value>
            <value>
                <fullName>Black</fullName>
                <isActive>false</isActive>
                <label>Black</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Account/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>Denotes the status of an agent in the agent lifecycle</description>
    <inlineHelpText>Denotes the status of an agent in the agent lifecycle</inlineHelpText>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Trial</fullName>
            </value>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Downgraded</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Suspended</fullName>
            </value>
            <value>
                <fullName>Expired</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Account/fields/Subscription_End_Date__c.field-meta.xml
<CustomField>
    <fullName>Subscription_End_Date__c</fullName>
    <description>Denotes end date of an agent&#39;s current subscriptions</description>
    <inlineHelpText>Denotes end date of an agent&#39;s current subscriptions</inlineHelpText>
    <label>Subscription End Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/Subscription_Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Subscription_Start_Date__c</fullName>
    <description>Denotes the start date of agent&#39;s current subscription</description>
    <inlineHelpText>Denotes the start date of agent&#39;s current subscription</inlineHelpText>
    <label>Subscription Start Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/Subsidiary__c.field-meta.xml
<CustomField>
    <fullName>Subsidiary__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Denotes the PG subsidiary to which the account belongs to</description>
    <inlineHelpText>Denotes the PG subsidiary to which the account belongs to</inlineHelpText>
    <label>Subsidiary</label>
    <referenceTo>Subsidiary__c</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/VIP_Campaign__c.field-meta.xml
<CustomField>
    <fullName>VIP_Campaign__c</fullName>
    <description>Denotes the VIP campaign to which the agent is approved to be a campaign member</description>
    <inlineHelpText>Denotes the VIP campaign to which the agent is approved to be a campaign member</inlineHelpText>
    <label>VIP Campaign</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Account/recordTypes/Agency.recordType-meta.xml
<RecordType>
    <fullName>Agency</fullName>
    <active>true</active>
    <label>Agency</label>
</RecordType>

unpackaged/main/default/objects/Agent_Reward__c/Agent_Reward__c.object-meta.xml
<CustomObject>
    <label>Agent Reward</label>
    <nameField>
        <displayFormat>AR-{0000}</displayFormat>
        <label>Agent Reward Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Agent Rewards</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Agent_Reward__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.Record_Type_Text__c</field>
            <operation>equals</operation>
            <value>Agent</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Agent Rewards</relationshipLabel>
    <relationshipName>Agent_Rewards</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Agent_Reward__c/fields/Approval_Status__c.field-meta.xml
<CustomField>
    <fullName>Approval_Status__c</fullName>
    <defaultValue>&#39;Not Required&#39;</defaultValue>
    <label>Approval Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Approval Submitted</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Not Required</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Agent_Reward__c/fields/Country__c.field-meta.xml
<CustomField>
    <fullName>Country__c</fullName>
    <formula>TEXT(Account__r.Country__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Country</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Agent_Reward__c/fields/Discretionary_Spending__c.field-meta.xml
<CustomField>
    <fullName>Discretionary_Spending__c</fullName>
    <label>Discretionary Spending</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/Agent_Reward__c/fields/Reward_Points__c.field-meta.xml
<CustomField>
    <fullName>Reward_Points__c</fullName>
    <label>Total Reward Points</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/Agent_Reward__c/fields/Reward_Tier__c.field-meta.xml
<CustomField>
    <fullName>Reward_Tier__c</fullName>
    <label>Reward Tier</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Solitaire</fullName>
            </value>
            <value>
                <fullName>Titanium</fullName>
            </value>
            <value>
                <fullName>Platinum</fullName>
            </value>
            <value>
                <fullName>Gold</fullName>
            </value>
            <value>
                <fullName>Silver</fullName>
            </value>
            <value>
                <fullName>Elite</fullName>
            </value>
            <value>
                <fullName>Black</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Agent_Reward__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New Quarter</fullName>
            </value>
            <value>
                <fullName>Published</fullName>
            </value>
            <value>
                <fullName>Not Published</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Subsidiary__c/Subsidiary__c.object-meta.xml
<CustomObject>
    <description>This is a custom object to contain the information on Subsidiary and Country</description>
    <label>Subsidiary</label>
    <nameField>
        <label>Subsidiary Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Subsidiaries</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Subsidiary__c/fields/Country__c.field-meta.xml
<CustomField>
    <fullName>Country__c</fullName>
    <description>Values from global picklist</description>
    <label>Country</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Country</valueSetName>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Trigger_Execute__c/Trigger_Execute__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>Trigger Execute</label>
</CustomObject>

unpackaged/main/default/objects/Trigger_Execute__c/fields/Enable_del__c.field-meta.xml
<CustomField>
    <fullName>Enable_del__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Enable del</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Update_PGF_Reward_Points__e/Update_PGF_Reward_Points__e.object-meta.xml
<CustomObject>
    <label>Update PGF Reward Points</label>
    <pluralLabel>Update PGF Reward Pointss</pluralLabel>
</CustomObject>

unpackaged/main/default/objects/Update_PGF_Reward_Points__e/fields/Reward_Points__c.field-meta.xml
<CustomField>
    <fullName>Reward_Points__c</fullName>
    <label>Total Reward Points</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/classes/AgentrewardTriggerHandler_test.cls
@istest
public class AgentrewardTriggerHandler_test {
    @istest
    private static void insertAgentReward(){
        Trigger_Execute__c customsetting=new Trigger_Execute__c();
        customsetting.Name='PGAccountTrigger';
        customsetting.Enable_del__c=true;
        insert customsetting;
        
        
        Trigger_Execute__c PGUpdatePGFPoints=new Trigger_Execute__c();
        PGUpdatePGFPoints.Name='PGUpdatePGFPoints';
        PGUpdatePGFPoints.Enable_del__c=true;
        insert PGUpdatePGFPoints;
        
        Trigger_Execute__c customsetting1=new Trigger_Execute__c();
        customsetting1.Name='PGAgentRewardTrigger';
        customsetting1.Enable_del__c=true;
        insert customsetting1;
        
        Test.startTest();
        id subId = PGTestDataFactory.createSubsidiary().Id;
        list<Account> listAccount1 = new list<Account>();
        Account agency = new Account();
        PGTestDataFactory_v2.initSetupData();
        agency.name = 'Unit Test Agency';
        agency.Agency_Id__c = '40574';
        agency.CEA_License__c = 'CEAUNittest1';
        agency.RecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Agency').getRecordTypeId();
        agency.Country__c = 'Singapore';
        agency.Subsidiary__c = subId;
        listAccount1.add(agency);
        insert listAccount1;
        
        list<Account> listAccount = new list<Account>();
        Account acc = new Account();
        PGTestDataFactory_v2.initSetupData();
        acc.FirstName = 'TestMe';
        acc.LastName = 'Lasting';
        acc.AgentNet_ID__c = 'AgentNet_ID__c test';
        acc.Salutation = 'Mrs.';
        acc.CurrencyIsoCode = 'SGD';
        acc.Subscription_Start_Date__c = system.today().addMonths(-10);
        acc.BillingStreet = 'test';
        acc.BillingCity = 'test';
        acc.BillingCountry = 'Singapore';
        acc.BillingPostalCode = '8373';
        //  acc.BillingState = 'test';
        acc.Current_Subscription_Code__c = 'abc';
        acc.PersonEmail = 'test0@yuni.com';
        acc.Account_Rule_Code__c = 'Standard';
        acc.Status__c = 'Active';
        acc.Country__c = 'Singapore';
        acc.Agency__c = agency.id;
        acc.Subsidiary__c = subId;
        acc.CEA_Salesperson_Number__c='F000002G';
        acc.PersonBirthdate=system.today();
        acc.Subscription_End_Date__c = Date.newInstance(2019, 12, 9);
        acc.Loyalty_Start_Date__c = Date.newInstance(2018, 12, 9);
        acc.RecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Agent').getRecordTypeId();
        acc.VIP_Campaign__c = 'VIP Advance SC';
        acc.Approval_Status__c = 'Test';
        acc.Reward_Points__c = 100;
        acc.Reward_Tier__c = 'Gold';
        
        insert acc;
        
        Account acc1 = new Account();
        PGTestDataFactory_v2.initSetupData();
        acc1.FirstName = 'TestMe1';
        acc1.LastName = 'Lasting1';
        acc1.AgentNet_ID__c = '76886';
        acc1.Salutation = 'Mrs.';
        acc1.CurrencyIsoCode = 'SGD';
        acc1.Subscription_Start_Date__c = system.today().addMonths(-10);
        acc1.BillingStreet = 'test';
        acc1.BillingCity = 'test';
        acc1.BillingCountry = 'Singapore';
        acc1.BillingPostalCode = '8373';
        acc1.Current_Subscription_Code__c = 'abc';
        acc1.PersonEmail = 'test10@1yuni.com';
        acc1.Account_Rule_Code__c = 'Standard';
        acc1.Status__c = 'Active';
        acc1.Country__c = 'Singapore';
        acc1.Agency__c = agency.id;
        acc1.Subsidiary__c = subId;
        acc1.CEA_Salesperson_Number__c='F000004K';
        acc1.PersonBirthdate=system.today();
        acc1.Subscription_End_Date__c = Date.newInstance(2019, 12, 9);
        acc1.Loyalty_Start_Date__c = Date.newInstance(2018, 12, 9);
        acc1.RecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Agent').getRecordTypeId();
        acc1.VIP_Campaign__c = 'VIP Advance SC';
        acc1.Approval_Status__c = 'Test';
        
        insert acc1;
        
          Account acc2 = new Account();
        PGTestDataFactory_v2.initSetupData();
        acc2.FirstName = 'TestMe2';
        acc2.LastName = 'Lasting2';
        acc2.AgentNet_ID__c = '7886';
        acc2.Salutation = 'Mrs.';
        acc2.CurrencyIsoCode = 'SGD';
        acc2.Subscription_Start_Date__c = system.today().addMonths(-10);
        acc2.BillingStreet = 'test';
        acc2.BillingCity = 'test';
        acc2.BillingCountry = 'Singapore';
        acc2.BillingPostalCode = '8373';
        //  acc.BillingState = 'test';
        acc2.Current_Subscription_Code__c = 'abc';
        acc2.PersonEmail = 'test391@yuni.com';
        acc2.Account_Rule_Code__c = 'Standard';
        acc2.Status__c = 'Active';
        acc2.Country__c = 'Singapore';
        acc2.Agency__c = agency.id;
        acc2.Subsidiary__c = subId;
        acc2.CEA_Salesperson_Number__c='A000011D';
        acc2.PersonBirthdate=system.today();
        acc2.Subscription_End_Date__c = Date.newInstance(2019, 12, 9);
        acc2.Loyalty_Start_Date__c = Date.newInstance(2018, 12, 9);
        acc2.RecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Agent').getRecordTypeId();
        acc2.VIP_Campaign__c = 'VIP Advance SC';
        acc2.Approval_Status__c = 'Test';
        acc2.Reward_Tier__c ='Solitaire';
        
        insert acc2;
        list<agent_reward__c> ARList = new list<agent_reward__C>();
        
        Agent_reward__c Ar4 = new Agent_reward__c();
        Ar4.Account__c = acc.id;
        Ar4.Status__c = 'Published';
        Ar4.Discretionary_Spending__c =1000;
        Ar4.Subscription_Spending__c = 2322;
        Ar4.Reward_Points__c = 3000;
        Ar4.Reward_Tier__c = 'Solitaire';
        
        ARList.add(Ar4);
        Agent_reward__c Ar5 = new Agent_reward__c();
        Ar5.Account__c = acc1.id;
        Ar5.Status__c = 'Published';
        Ar5.Discretionary_Spending__c =1000;
        Ar5.Subscription_Spending__c = 2322;
        Ar5.Reward_Points__c = 3000;
        Ar5.Reward_Tier__c = 'Solitaire';
        
        ARList.add(Ar5);
        Agent_reward__c Ar1 = new Agent_reward__c();
        Ar1.Account__c = acc2.id;
        Ar1.Status__c = 'Published';
        Ar1.Discretionary_Spending__c =1000;
        Ar1.Subscription_Spending__c = 2322;
        Ar1.Reward_Points__c = 100;
        Ar1.Reward_Tier__c = 'Elite';
        
        ARList.add(Ar1);        
        Agent_reward__c Ar = new Agent_reward__c();
        Ar.Account__c = acc.id;
        Ar.Status__c = 'New Quarter';
        Ar.Discretionary_Spending__c =1000;
        Ar.Subscription_Spending__c = 2322;
        Ar.Reward_Points__c = 233;
        Ar.Reward_Tier__c = 'Silver';
        
        ARList.add(Ar);
              
        Agent_reward__c Ar6 = new Agent_reward__c();
        Ar6.Account__c = acc1.id;
        Ar6.Status__c = 'New Quarter';
        Ar6.Discretionary_Spending__c =20000;
        Ar6.Subscription_Spending__c = 2322;
        Ar6.Reward_Points__c = 700;
        Ar6.Reward_Tier__c = 'Platinum';
        
        ARList.add(Ar6);
        
        Agent_reward__c Ar8 = new Agent_reward__c();
        Ar8.Account__c = acc2.id;
        Ar8.Status__c = 'New Quarter';
        Ar8.Discretionary_Spending__c =43;
        Ar8.Subscription_Spending__c = 12;
        Ar8.Reward_Points__c = 70;
        Ar8.Reward_Tier__c = 'Elite';
        
        ARList.add(Ar8);
        insert ARList;
        
        Agent_reward__c Ar7 = new Agent_reward__c();
        Ar7.Account__c = acc.id;
        Ar7.Status__c = 'New Quarter';
        Ar7.Discretionary_Spending__c =20000;
        Ar7.Subscription_Spending__c = 2322;
        Ar7.Reward_Points__c = 2000;
        Ar7.Reward_Tier__c = 'Solitaire';
        insert Ar7;
        ARList.add(Ar7);
        Ar7.Approval_Status__c ='Approved';
        update Ar7;
               
        Agent_reward__c Ar3 = new Agent_reward__c();
        Ar3.Account__c = acc1.id;
        Ar3.Status__c = 'New Quarter';
        Ar3.Discretionary_Spending__c =20000;
        Ar3.Subscription_Spending__c = 2322;
        Ar3.Reward_Points__c = 2000;
        Ar3.Reward_Tier__c = 'Solitaire';
        AR3.PGF_LoanId__c = '7797867';
        AR3.PGF_Loan_Reward_Points__c = 50;
        insert Ar3;
        
        Ar3.Approval_Status__c ='rejected';
        AR3.PGF_Loan_Reward_Points__c = 80;
        update Ar3;
        
         Ar8.Approval_Status__c ='approved';
        AR3.PGF_Loan_Reward_Points__c = 30;
        update Ar3;
        
        Account acc3 = new Account();
        PGTestDataFactory_v2.initSetupData();
        acc3.FirstName = 'TestMe11';
        acc3.LastName = 'Lasting11';
        acc3.AgentNet_ID__c = '17886';
        acc3.Salutation = 'Mrs.';
        acc3.CurrencyIsoCode = 'SGD';
        acc3.Subscription_Start_Date__c = system.today().addMonths(-10);
        acc3.BillingStreet = 'tes1t';
        acc3.BillingCity = 'test1';
        acc3.BillingCountry = 'Singapore';
        acc3.BillingPostalCode = '128373';
        //  acc.BillingState = 'test';
        acc3.Current_Subscription_Code__c = '1abc';
        acc3.PersonEmail = 'test913@1yuni.com';
        acc3.Account_Rule_Code__c = 'Standard';
        acc3.Status__c = 'Active';
        acc3.Country__c = 'Singapore';
        acc3.Agency__c = agency.id;
        acc3.Subsidiary__c = subId;
        acc3.CEA_Salesperson_Number__c='A000234A';
        acc3.PersonBirthdate=system.today();
        acc3.Subscription_End_Date__c = Date.newInstance(2019, 12, 9);
        acc3.Loyalty_Start_Date__c = Date.newInstance(2018, 12, 9);
        acc3.RecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Agent').getRecordTypeId();
        acc3.VIP_Campaign__c = 'VIP Advance SC';
        acc3.Approval_Status__c = 'Test';
        acc3.Reward_Tier__c ='Gold';
        
        insert acc3;
        
         acc3.CEA_Salesperson_Number__c = '';
        
        
        Agent_reward__c Ar13 = new Agent_reward__c();
        Ar13.Account__c = acc3.id;
        Ar13.Status__c = 'New Quarter';
        Ar13.Discretionary_Spending__c =20000;
        Ar13.Subscription_Spending__c = 2322;
        Ar13.Reward_Points__c = 2000;
        Ar13.Reward_Tier__c = 'Solitaire';
        AR13.PGF_LoanId__c = '17797867';
        AR13.PGF_Loan_Reward_Points__c = 50;
        insert Ar13;
        
        List<Update_PGF_Reward_Points__e> eventPGFList = new List<Update_PGF_Reward_Points__e>();
        Update_PGF_Reward_Points__e pgfEvent = new Update_PGF_Reward_Points__e();
        pgfEvent.Account_Id__c = acc.Id;
        pgfEvent.PGF_Reward_Points__c = acc.PGF_Reward_Points__c;
        pgfEvent.Reward_Points__c = acc.Reward_Points__c;
        eventPGFList.add(pgfEvent);
        
        String AccountId = '001689754412345678';
        Update_PGF_Reward_Points__e pgfEvent1 = new Update_PGF_Reward_Points__e();
        pgfEvent1.Account_Id__c = acc1.Id;
        pgfEvent1.PGF_Reward_Points__c = 50.02;
        pgfEvent1.Reward_Points__c = acc1.Reward_Points__c;
        eventPGFList.add(pgfEvent1);
       
        EventBus.publish(eventPGFList);
        
        
        
        PGUpdatePGFPointsController.createErrorLog(Ar3.id,JSON.serialize(Ar3),'error');
        PGUpdatePGFPointsController.updateAgentPGFPoints(eventPGFList);
        Test.stopTest();
        
    }
}