unpackaged/main/default/objects/Account/fields/Account_Rule_Code__c.field-meta.xml
<CustomField>
    <fullName>Account_Rule_Code__c</fullName>
    <defaultValue>IF( $RecordType.DeveloperName = &quot;Agent&quot;, &quot;TRIAL&quot;, &quot;&quot;)</defaultValue>
    <description>Denotes account rule code (short text) for the account rule</description>
    <inlineHelpText>Denotes account rule code (short text) for the account rule</inlineHelpText>
    <label>Account Rule Code</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/AgentNet_ID__c.field-meta.xml
<CustomField>
    <fullName>AgentNet_ID__c</fullName>
    <description>Denotes a numeric id of agents in PG system</description>
    <inlineHelpText>Denotes a numeric id of agents in PG system</inlineHelpText>
    <label>AgentNet ID</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/Approval_Status__c.field-meta.xml
<CustomField>
    <fullName>Approval_Status__c</fullName>
    <description>Denotes the approval status for an agent in the VIP approval process</description>
    <inlineHelpText>Denotes the approval status for an agent in the VIP approval process</inlineHelpText>
    <label>Approval Status</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/CEA_Salesperson_Number__c.field-meta.xml
<CustomField>
    <fullName>CEA_Salesperson_Number__c</fullName>
    <description>Denotes the agent license number registered under a governing authority</description>
    <inlineHelpText>Denotes the agent registration number issued by CEA for SG agents and MIEA for MY agents</inlineHelpText>
    <label>Agent Identification Number</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/Country__c.field-meta.xml
<CustomField>
    <fullName>Country__c</fullName>
    <defaultValue>if(  BEGINS($UserRole.Name, &quot;TH&quot;),&quot;Thailand&quot;,if(ISPICKVAL($User.Subsidiary__c,&quot;MyProperty Data Sdn. Bhd.&quot;),&quot;Malaysia&quot;,&quot;&quot;))</defaultValue>
    <description>Denotes the country of an account</description>
    <inlineHelpText>Denotes the country of an account</inlineHelpText>
    <label>Country</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Country</valueSetName>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Account/fields/Current_Subscription_Code__c.field-meta.xml
<CustomField>
    <fullName>Current_Subscription_Code__c</fullName>
    <label>Current Subscription Code</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/Current_Subscription_Spending_Amount__c.field-meta.xml
<CustomField>
    <fullName>Current_Subscription_Spending_Amount__c</fullName>
    <label>Current Subscription Spending Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/PG_Tenure__c.field-meta.xml
<CustomField>
    <fullName>PG_Tenure__c</fullName>
    <description>Denotes tenure of an agent with PG</description>
    <formula>IF(OR(ISPICKVAL(Country__c, &#39;Malaysia&#39;),ISPICKVAL(Country__c, &#39;Thailand&#39;)),
FLOOR(
(((Year(Subscription_End_Date__c)-Year(Loyalty_Start_Date__c))*12 + (IF(IF(MONTH(Subscription_End_Date__c)+1&gt;12,MONTH(Subscription_End_Date__c)+1-12,
MONTH(Subscription_End_Date__c)+1)=MONTH(Loyalty_Start_Date__c),MONTH(Subscription_End_Date__c)+1-MONTH(Loyalty_Start_Date__c),
MONTH(Subscription_End_Date__c)-MONTH(Loyalty_Start_Date__c))))/12)),
IF(ISPICKVAL(Country__c, &#39;Singapore&#39;),
FLOOR((((Year(Subscription_End_Date__c)-Year(Loyalty_Start_Date__c))*12 + (IF(IF(MONTH(Subscription_End_Date__c)+1&gt;12,MONTH(Subscription_End_Date__c)+1-12,
MONTH(Subscription_End_Date__c)+1)=MONTH(Loyalty_Start_Date__c),MONTH(Subscription_End_Date__c)+1-MONTH(Loyalty_Start_Date__c),
MONTH(Subscription_End_Date__c)-MONTH(Loyalty_Start_Date__c))))/12)),1)
)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>PG Tenure is calculated as Subscription End Date minus Loyalty Start Date</inlineHelpText>
    <label>PG Tenure</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>Denotes the status of an agent in the agent lifecycle</description>
    <inlineHelpText>Denotes the status of an agent in the agent lifecycle</inlineHelpText>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Trial</fullName>
            </value>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Downgraded</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Suspended</fullName>
            </value>
            <value>
                <fullName>Expired</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Account/fields/Subscription_Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Subscription_Start_Date__c</fullName>
    <description>Denotes the start date of agent&#39;s current subscription</description>
    <inlineHelpText>Denotes the start date of agent&#39;s current subscription</inlineHelpText>
    <label>Subscription Start Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/Subsidiary__c.field-meta.xml
<CustomField>
    <fullName>Subsidiary__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Denotes the PG subsidiary to which the account belongs to</description>
    <inlineHelpText>Denotes the PG subsidiary to which the account belongs to</inlineHelpText>
    <label>Subsidiary</label>
    <referenceTo>Subsidiary__c</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/Total_Spending__c.field-meta.xml
<CustomField>
    <fullName>Total_Spending__c</fullName>
    <defaultValue>0</defaultValue>
    <inlineHelpText>This is total spending on Discretionary Products</inlineHelpText>
    <label>Total Spending</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Account_Rule_Code__c.field-meta.xml
<CustomField>
    <fullName>Account_Rule_Code__c</fullName>
    <label>Account Rule Code</label>
    <length>15</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Country__c.field-meta.xml
<CustomField>
    <fullName>Country__c</fullName>
    <formula>TEXT(Subsidiary__r.Country__c )</formula>
    <label>Country</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Include_Subscription_Ext__c.field-meta.xml
<CustomField>
    <fullName>Include_Subscription_Ext__c</fullName>
    <defaultValue>true</defaultValue>
    <label>Include Subscription Ext</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Is_Current_Subscription__c.field-meta.xml
<CustomField>
    <fullName>Is_Current_Subscription__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is Current Subscription</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Months_Included__c.field-meta.xml
<CustomField>
    <fullName>Months_Included__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Included in Total Spending 12 months or not</description>
    <label>Months Included</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Order_Type_Clone__c.field-meta.xml
<CustomField>
    <fullName>Order_Type_Clone__c</fullName>
    <label>Order Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Contract - New</fullName>
            </value>
            <value>
                <fullName>Contract - Upsell</fullName>
            </value>
            <value>
                <fullName>Contract - Renewal</fullName>
            </value>
            <value>
                <fullName>Contract - Make Good</fullName>
            </value>
            <value>
                <fullName>Dual-SO</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/PG_Tenure__c.field-meta.xml
<CustomField>
    <fullName>PG_Tenure__c</fullName>
    <label>PG Tenure</label>
    <precision>4</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Subsidiary__c.field-meta.xml
<CustomField>
    <fullName>Subsidiary__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Subsidiary</label>
    <referenceTo>Subsidiary__c</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Summary_Of_Subscription_Item_new__c.field-meta.xml
<CustomField>
    <fullName>Summary_Of_Subscription_Item_new__c</fullName>
    <label>Summary Of Subscription Item</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Total_Spending__c.field-meta.xml
<CustomField>
    <fullName>Total_Spending__c</fullName>
    <label>Total Spending (last 12 months)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Total_Spending_on_Discretionary_Prod_new__c.field-meta.xml
<CustomField>
    <fullName>Total_Spending_on_Discretionary_Prod_new__c</fullName>
    <defaultValue>0.00</defaultValue>
    <label>Total Spending on Discretionary Product</label>
    <precision>15</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/recordTypes/B2C.recordType-meta.xml
<RecordType>
    <fullName>B2C</fullName>
    <active>true</active>
    <businessProcess>B2C</businessProcess>
    <description>B2C Opportunity Record</description>
    <label>B2C</label>
</RecordType>

unpackaged/main/default/objects/OpportunityLineItem/fields/Amount__c.field-meta.xml
<CustomField>
    <fullName>Amount__c</fullName>
    <description>Amount after discount before tax (Sales Price * Qty - Discount), exclude complimentary</description>
    <formula>IF( Complimentary__c = TRUE, IF(Record_Type__c=&quot;B2C&quot;, (UnitPrice *  Quantity) - TotalPrice, (UnitPrice *  Quantity) - Discounted_Amount__c -  TotalPrice) , IF(Record_Type__c=&quot;B2C&quot;, (UnitPrice *  Quantity) - Discounted_Amount__c - Pro_Rate_Amount__c, (UnitPrice *  Quantity) - Discounted_Amount__c))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>(Sales Price * Qty - Discount) - Complimentary, before Tax</inlineHelpText>
    <label>Price after discount</label>
    <precision>18</precision>
    <scale>3</scale>
    <type>Currency</type>
</CustomField>

unpackaged/main/default/objects/Pricebook2/fields/Subsidiary__c.field-meta.xml
<CustomField>
    <fullName>Subsidiary__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Denotes the PG subsidiary to which the pricebook belongs to</description>
    <inlineHelpText>Denotes the PG subsidiary to which the pricebook belongs to</inlineHelpText>
    <label>Subsidiary</label>
    <referenceTo>Subsidiary__c</referenceTo>
    <relationshipLabel>Price Books</relationshipLabel>
    <relationshipName>Price_Books</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Product2/fields/Subsidiary__c.field-meta.xml
<CustomField>
    <fullName>Subsidiary__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Denotes the PG subsidiary to which the product belongs to</description>
    <inlineHelpText>Denotes the PG subsidiary to which the product belongs to</inlineHelpText>
    <label>Subsidiary</label>
    <referenceTo>Subsidiary__c</referenceTo>
    <relationshipLabel>Products</relationshipLabel>
    <relationshipName>Products</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Product2/fields/Tax_Code__c.field-meta.xml
<CustomField>
    <fullName>Tax_Code__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Denotes reference to the tax code</description>
    <inlineHelpText>Denotes reference to the tax code</inlineHelpText>
    <label>Tax Code</label>
    <referenceTo>Tax_Code__c</referenceTo>
    <relationshipLabel>Products</relationshipLabel>
    <relationshipName>Products</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Subsidiary__c/Subsidiary__c.object-meta.xml
<CustomObject>
    <description>This is a custom object to contain the information on Subsidiary and Country</description>
    <label>Subsidiary</label>
    <nameField>
        <label>Subsidiary Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Subsidiaries</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Subsidiary__c/fields/Country__c.field-meta.xml
<CustomField>
    <fullName>Country__c</fullName>
    <description>Values from global picklist</description>
    <label>Country</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Country</valueSetName>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Tax_Code__c/Tax_Code__c.object-meta.xml
<CustomObject>
    <description>This is custom object to store all tax codes and rates.</description>
    <label>Tax Code</label>
    <nameField>
        <label>Tax Code</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Tax Codes</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Tax_Code__c/fields/Country__c.field-meta.xml
<CustomField>
    <fullName>Country__c</fullName>
    <description>Denotes the country of tax code belongs to</description>
    <inlineHelpText>Denotes the country of tax code belongs to</inlineHelpText>
    <label>Country</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Country</valueSetName>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Tax_Code__c/fields/Tax_Rate__c.field-meta.xml
<CustomField>
    <fullName>Tax_Rate__c</fullName>
    <description>Denotes the tax rate</description>
    <inlineHelpText>Denotes the tax rate</inlineHelpText>
    <label>Tax Rate</label>
    <precision>4</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

unpackaged/main/default/classes/OppIncludeSubscription_Batch_Test.cls
/**
* Created by Yuni on 9/21/2018.
*/
@IsTest
public class OppIncludeSubscription_Batch_Test {
    static testMethod void runTest() {
        Test.startTest();
        list<Opportunity> listOpp = new list<Opportunity>();
        list<Opportunity> listOpp2 = new list<Opportunity>();
        
        string accRectype = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Agent').getRecordTypeId();
        
        Subsidiary__c sb = PGTestDataFactory.createSubsidiary();
        PGTestDataFactory_v2.initSetupData();
        Account a = new Account();
        a.RecordTypeId = accRectype;
        a.FirstName = 'IsYuni';
        a.LastName = 'TestYuni';
        a.AgentNet_ID__c = 'AgentNet_ID__c test';
        a.Salutation = 'Mrs.';
        a.CurrencyIsoCode = 'SGD';
        a.Subscription_Start_Date__c = system.today().addMonths(-10);
        a.BillingStreet = 'test';
        a.BillingCity = 'test';
        a.BillingCountry = 'Singapore';
        a.BillingPostalCode = '8373';
        //a.BillingState = 'test';
        a.Current_Subscription_Code__c = 'abc';
        a.PersonEmail = 'test@yuni.com';
        a.Status__c = 'Active';
        a.Account_Rule_Code__c = 'test';
        a.Subsidiary__pc = sb.Id;
        a.Country__c = 'Singapore';
        a.CEA_Salesperson_Number__c = '51231231';
        a.Current_Subscription_Spending_Amount__c = 200;
        a.CEA_Salesperson_Number__c = 'CEACHECK';
        a.PersonBirthdate = Date.newInstance(1996, 12, 21);
        insert a;
        
        Tax_Code__c taxcode = new Tax_Code__c();
        taxcode.Name = 'SG - 7% GST';
        taxcode.Tax_Rate__c =  7;
        taxcode.Country__c = 'Singapore';
        insert taxcode;
        
        string oppRectype = Schema.SObjectType.Opportunity.getRecordTypeInfosByName().get('B2C').getRecordTypeId();
        Opportunity opp = new opportunity();
        opp.Name = 'Test Opp';
        opp.StageName = 'Closed Won';
        opp.AccountId = a.id;
        opp.CloseDate = system.today().AddDays(-30);
        opp.Subsidiary__c = sb.id;
        opp.PG_Tenure__c = 4;
        opp.Total_Spending__c = 100;
        opp.Months_Included__c = false;
        opp.Is_Current_Subscription__c = true;
        opp.RecordTypeId =oppRectype;
        opp.Include_Subscription_Ext__c = true;
        opp.Summary_Of_Subscription_Item_new__c = null;
        opp.Total_Spending_on_Discretionary_Prod_new__c = null;
        opp.Order_Type_Clone__c = 'Contract - Upgrade';
        opp.Approval_Status__c = 'OMC Approval Approved';
		opp.OMC_Approved_Date__c = date.today().addDays(-366);
        listOpp.add(opp);
        
        Pricebook2 standardPB = new Pricebook2(Name = 'Standard Pricebook', Description = 'Price Book', Subsidiary__c = sb.id,  IsActive = true, CurrencyIsoCode = 'SGD');
        insert standardPB;
        
        Product_Class__c productClass = new Product_Class__c(Name = 'Tier1UnitSubNew', CurrencyIsoCode = 'SGD'/*, NS_Internal_ID__c ='1234567890'*/);
        insert productClass;
        
        list<Product2> listProd = new list<Product2>();
        Product2 prod = new Product2(Name = 'Test Prod', IsActive = true, Segment__c = 'B2C Only', Product_Category__c = 'Subscription', SKU_Code__c = 'abc', Product_Class__c = productClass.Id, Tax_Code__c = taxcode.Id);
        listProd.add(prod);
        
        Product2 prod2 = new Product2(Name = 'Test Prod2', IsActive = true, Segment__c = 'B2C Only', Product_Category__c = 'Subscription', SKU_Code__c = 'abc', Product_Class__c = productClass.Id, Tax_Code__c = taxcode.Id);
        listProd.add(prod2);
        insert listProd;
        
        Id StdpricebookId = Test.getStandardPricebookId();
        
        list<PricebookEntry> listPBE = new list<PricebookEntry>();
        PricebookEntry pbe = new PricebookEntry(pricebook2id=StdpricebookId, product2id=prod.id, unitprice=100.0, isActive=true);
        listPBE.add(pbe);
        
        PricebookEntry pbe2 = new PricebookEntry(pricebook2id=standardPB.Id, product2id=prod.id, unitprice=100.0, isActive=true, CurrencyIsoCode = 'SGD', UseStandardPrice = false);
        listPBE.add(pbe2);
        insert listPBE;
        
        opp = new opportunity();
        opp.Name = 'Test Opp 2';
        opp.StageName = 'Closed Won';
        opp.AccountId = a.id;
        opp.CloseDate = system.today().AddDays(-10);
        opp.Subsidiary__c = sb.id;
        opp.PG_Tenure__c = 4;
        opp.Total_Spending__c = 100;
        opp.Months_Included__c = true;
        opp.Is_Current_Subscription__c = true;
        opp.RecordTypeId =oppRectype;
        opp.Include_Subscription_Ext__c = true;
        opp.Order_Type_Clone__c = 'Contract - Upgrade';
        opp.Total_Spending_on_Discretionary_Prod_new__c = null;
        opp.Approval_Status__c = 'OMC Approval Approved';
		opp.OMC_Approved_Date__c = date.today().addDays(-366);
        listOpp.add(opp);
        
        Opportunity opp1 = new opportunity();
        opp1.Name = 'Test Opp 3';
        opp1.StageName = 'Closed Won';
        opp1.AccountId = a.id;
        opp1.CloseDate = system.today().AddDays(-325);
        opp1.Subsidiary__c = sb.id;
        opp1.PG_Tenure__c = 4;
        opp1.Total_Spending__c = 100;
        opp1.Months_Included__c = true;
        opp1.Is_Current_Subscription__c = true;
       	opp1.RecordTypeId =oppRectype;
        opp1.Include_Subscription_Ext__c = true;
        opp1.Order_Type_Clone__c = 'Contract - Upgrade';
        opp1.Summary_Of_Subscription_Item_new__c = null;
        opp1.Total_Spending_on_Discretionary_Prod_new__c = null;
        opp.Approval_Status__c = 'OMC Approval Approved';
		opp.OMC_Approved_Date__c = date.today().addDays(-366);
        listOpp.add(opp1);
        
        insert listOpp;
        
        Integer SummaryAmount1 = 0, SummaryAmount2 = 0;
        list<OpportunityLineItem> listOppLine = new list<OpportunityLineItem>();
        OpportunityLineItem oppLine = New OpportunityLineItem();
        oppLine.OpportunityId = listOpp[0].Id;
        oppLine.Push_to_NetSuite__c = true;
        oppLine.PricebookEntryId = pbe2.Id;
        oppLine.Product2Id = prod.Id;
        oppLine.UnitPrice = 300;
        oppLine.Product_Category__c = 'Subscription';
        oppLine.Discount_Reason__c = 'VIP (Relationship)';
        oppLine.Quantity = 2;
        SummaryAmount1 = 300;
        oppline.Amount_Despite_VIP__c = 300;
        listOppLine.add(oppLine);
        
        oppLine = New OpportunityLineItem();
        oppLine.OpportunityId = listOpp[1].Id;
        oppLine.Push_to_NetSuite__c = true;
        oppLine.PricebookEntryId = pbe2.Id;
        oppLine.Product2Id = prod.Id;
        oppLine.UnitPrice = 2500;
        oppLine.Quantity = 2;
        SummaryAmount2 = 2500;
        oppline.Amount_Despite_VIP__c = 2500;
        oppLine.Product_Category__c = 'Subscription';
        listOppLine.add(oppLine);
        insert listOppLine;
        
        //oppLine = [select Id, Product_Category__c, Amount_Despite_VIP__c, Opportunity.Summary_Of_Subscription_Item__c, UnitPrice, Amount__c from OpportunityLineItem where id =: opp.id or id=:opp1.Id];
        system.debug('OPPLINE:'+oppLine);
        
        //listOpp = [Select id, Is_Current_Subscription__c, StageName, Include_Subscription_Ext__c, Attachment_Limit_Exceeded__c, OMC_Approved_Date__c, Approval_Status__c,Summary_Of_Subscription_Item__c,IsWon,recordtype.name,Summary_Of_Subscription_Item_new__c from opportunity where id =: opp.id or id=:opp1.Id];
        for (Opportunity row: listOpp) {
            row.StageName = 'Closed Won';
            row.Approval_Status__c = 'OMC Approval Approved';
            row.Is_Current_Subscription__c = true;
            row.Attachment_Limit_Exceeded__c = true;
            if(row.Id == opp1.Id){
                row.OMC_Approved_Date__c = date.today().addDays(-366);
            }
            else{
                row.OMC_Approved_Date__c = date.today();
            }
            row.Summary_Of_Subscription_Item_new__c = 1;
            //
        } 
        update listOpp;
        
        system.debug('IKI:' + [Select id,accountid,Total_Spending_on_Discretionary_Prod_new__c, Is_Current_Subscription__c, StageName, Include_Subscription_Ext__c,Include_Subscription__c , Attachment_Limit_Exceeded__c, OMC_Approved_Date__c, Approval_Status__c,Summary_Of_Subscription_Item__c,IsWon,recordtype.name,Summary_Of_Subscription_Item_new__c from opportunity where id =: opp.id or id=:opp1.Id]);
        //listOpp2 = [select Id, Name, AccountId, Include_Subscription__c, Include_Subscription_Ext__c, ByAuto__c, CloseDate, Is_Current_Subscription__c, Summary_Of_Subscription_Item_new__c, iswon, RecordType.Name, Account.Status__c  from Opportunity where RecordType.Name='B2C' and IsWon=true and Account.Status__c!='Cancelled' order by CloseDate desc];
        
        OppIncludeSubscription_BatchSchedulable schedulable = new OppIncludeSubscription_BatchSchedulable('');
        String sch = '0 0 0 * * ? *';
        system.schedule('Test Schedule', sch, schedulable);
        
        //AccountCurrentSubscriptionFix z = new AccountCurrentSubscriptionFix();
        //database.executeBatch(z);
        OppIncludeSubscription_Batch x = new OppIncludeSubscription_Batch(a.id);
        //  and ((Include_Subscription__c=true and Include_Subscription_Ext__c=false) or (Include_Subscription__c=false and Include_Subscription_Ext__c=true) or (Is_Current_Subscription__c=true and DAY_ONLY(OMC_Approved_Date__C)<=today))
        database.executeBatch(x);
        
        /*Database.executeBatch(new OppIncludeSubscription_Batch(a.id));
        Database.executeBatch(new OppIncludeSubscription_Batch(null));
        ExcludeFromSpending_BatchSchedulable schedulable = new ExcludeFromSpending_BatchSchedulable(a.id);
        String sch = '0 0 0 * * ? *';
        system.schedule('Test Schedule', sch, schedulable);
        */
        SlackAlert_Batch w = new SlackAlert_Batch();
        database.executeBatch(w);
        Database.executeBatch(new OptyRollUpFieldUpd_Batch(opp.id));
        Database.executeBatch(new OptyRollUpFieldUpd_Batch(opp1.id));
        Database.executeBatch(new OptyRollUpFieldUpd_Batch_DF());
        
        Database.executeBatch(new AccountCSS_Batch_DF());
        Database.executeBatch(new AccountCSSRefundCOVID_DF());
        Database.executeBatch(new AccountCSS_Batch(a.Id));
        Database.executeBatch(new AccountTS_Batch_DF());
        Database.executeBatch(new AccountTS_Batch(a.Id));
        //Database.executeBatch(new OptyAmtDespiteVIPUpg_Batch_DF());
        //Database.executeBatch(new OptyAmtDespiteVIPRen_Batch_DF());
        
        
    }
    static testMethod void runTest2(){
              
         test.startTest(); 
         list<Opportunity> listOpp = new list<Opportunity>();
        list<Opportunity> listOpp2 = new list<Opportunity>();
        
        string accRectype = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Agent').getRecordTypeId();
        
        Subsidiary__c sb = PGTestDataFactory.createSubsidiary();
        PGTestDataFactory_v2.initSetupData();
        Account a = new Account();
        a.RecordTypeId = accRectype;
        a.FirstName = 'IsYuni';
        a.LastName = 'TestYuni';
        a.AgentNet_ID__c = 'AgentNet_ID__c test';
        a.Salutation = 'Mrs.';
        a.CurrencyIsoCode = 'SGD';
        a.Subscription_Start_Date__c = system.today().addMonths(-10);
        a.BillingStreet = 'test';
        a.BillingCity = 'test';
        a.BillingCountry = 'Singapore';
        a.BillingPostalCode = '8373';
       // a.BillingState = 'test';
        a.Current_Subscription_Code__c = 'abc';
        a.PersonEmail = 'test@yuni.com';
        a.Status__c = 'Active';
        a.Account_Rule_Code__c = 'test';
        a.Subsidiary__pc = sb.Id;
        a.Country__c = 'Singapore';
        a.CEA_Salesperson_Number__c = '51231231';
        a.PersonBirthdate = date.newInstance(1970, 1, 1);
        a.Current_Subscription_Spending_Amount__c = 200;
        a.CEA_Salesperson_Number__c = 'CEACHECK';
        a.PersonBirthdate = Date.newInstance(1996, 12, 21);
        insert a;
        
        Tax_Code__c taxcode = new Tax_Code__c();
        taxcode.Name = 'SG - 7% GST';
        taxcode.Tax_Rate__c =  7;
        taxcode.Country__c = 'Singapore';
        insert taxcode;
        
        string oppRectype = Schema.SObjectType.Opportunity.getRecordTypeInfosByName().get('B2C').getRecordTypeId();
        Opportunity opp = new opportunity();
        opp.Name = 'Test Opp';
        opp.StageName = 'Closed Won';
        opp.AccountId = a.id;
        opp.CloseDate = system.today().AddDays(-30);
        opp.Subsidiary__c = sb.id;
        opp.PG_Tenure__c = 4;
        opp.Total_Spending__c = 100;
        opp.Months_Included__c = false;
        opp.Is_Current_Subscription__c = true;
        opp.RecordTypeId =oppRectype;
        opp.Include_Subscription_Ext__c = true;
        opp.Summary_Of_Subscription_Item_new__c = null;
        opp.Total_Spending_on_Discretionary_Prod_new__c = null;
        opp.Order_Type_Clone__c = 'Contract - Upgrade';
        opp.Approval_Status__c = 'OMC Approval Approved';
		opp.OMC_Approved_Date__c = date.today().addDays(-366);
        listOpp.add(opp);
        
        Pricebook2 standardPB = new Pricebook2(Name = 'Standard Pricebook', Description = 'Price Book', Subsidiary__c = sb.id,  IsActive = true, CurrencyIsoCode = 'SGD');
        insert standardPB;
        
        Product_Class__c productClass = new Product_Class__c(Name = 'Tier1UnitSubNew', CurrencyIsoCode = 'SGD'/*, NS_Internal_ID__c ='1234567890'*/);
        insert productClass;
        
        list<Product2> listProd = new list<Product2>();
        Product2 prod = new Product2(Name = 'Test Prod', IsActive = true, Segment__c = 'B2C Only', Product_Category__c = 'Subscription', SKU_Code__c = 'abc', Product_Class__c = productClass.Id, Tax_Code__c = taxcode.Id);
        listProd.add(prod);
        
        Product2 prod2 = new Product2(Name = 'Test Prod2', IsActive = true, Segment__c = 'B2C Only', Product_Category__c = 'Subscription', SKU_Code__c = 'abc', Product_Class__c = productClass.Id, Tax_Code__c = taxcode.Id);
        listProd.add(prod2);
        insert listProd;
        
        Id StdpricebookId = Test.getStandardPricebookId();
        
        list<PricebookEntry> listPBE = new list<PricebookEntry>();
        PricebookEntry pbe = new PricebookEntry(pricebook2id=StdpricebookId, product2id=prod.id, unitprice=100.0, isActive=true);
        listPBE.add(pbe);
        
        PricebookEntry pbe2 = new PricebookEntry(pricebook2id=standardPB.Id, product2id=prod.id, unitprice=100.0, isActive=true, CurrencyIsoCode = 'SGD', UseStandardPrice = false);
        listPBE.add(pbe2);
        insert listPBE;
        
        opp = new opportunity();
        opp.Name = 'Test Opp 2';
        opp.StageName = 'Closed Won';
        opp.AccountId = a.id;
        opp.CloseDate = system.today().AddDays(-10);
        opp.Subsidiary__c = sb.id;
        opp.PG_Tenure__c = 4;
        opp.Total_Spending__c = 100;
        opp.Months_Included__c = true;
        opp.Is_Current_Subscription__c = true;
        opp.RecordTypeId =oppRectype;
        opp.Include_Subscription_Ext__c = true;
        opp.Order_Type_Clone__c = 'Contract - Upgrade';
        opp.Total_Spending_on_Discretionary_Prod_new__c = null;
        opp.Approval_Status__c = 'OMC Approval Approved';
		opp.OMC_Approved_Date__c = date.today().addDays(-366);
        listOpp.add(opp);
        
        Opportunity opp1 = new opportunity();
        opp1.Name = 'Test Opp 3';
        opp1.StageName = 'Closed Won';
        opp1.AccountId = a.id;
        opp1.CloseDate = system.today().AddDays(-325);
        opp1.Subsidiary__c = sb.id;
        opp1.PG_Tenure__c = 4;
        opp1.Total_Spending__c = 100;
        opp1.Months_Included__c = true;
        opp1.Is_Current_Subscription__c = true;
       	opp1.RecordTypeId =oppRectype;
        opp1.Include_Subscription_Ext__c = true;
        opp1.Order_Type_Clone__c = 'Contract - Upgrade';
        opp1.Summary_Of_Subscription_Item_new__c = null;
        opp1.Total_Spending_on_Discretionary_Prod_new__c = null;
        opp.Approval_Status__c = 'OMC Approval Approved';
		opp.OMC_Approved_Date__c = date.today().addDays(-366);
        listOpp.add(opp1);
        
        insert listOpp;
        
        Integer SummaryAmount1 = 0, SummaryAmount2 = 0;
        list<OpportunityLineItem> listOppLine = new list<OpportunityLineItem>();
        OpportunityLineItem oppLine = New OpportunityLineItem();
        oppLine.OpportunityId = listOpp[0].Id;
        oppLine.Push_to_NetSuite__c = true;
        oppLine.PricebookEntryId = pbe2.Id;
        oppLine.Product2Id = prod.Id;
        oppLine.UnitPrice = 300;
        oppLine.Product_Category__c = 'Subscription';
        oppLine.Discount_Reason__c = 'VIP (Relationship)';
        oppLine.Quantity = 2;
        SummaryAmount1 = 300;
        oppline.Amount_Despite_VIP__c = 300;
        listOppLine.add(oppLine);
        
        oppLine = New OpportunityLineItem();
        oppLine.OpportunityId = listOpp[1].Id;
        oppLine.Push_to_NetSuite__c = true;
        oppLine.PricebookEntryId = pbe2.Id;
        oppLine.Product2Id = prod.Id;
        oppLine.UnitPrice = 2500;
        oppLine.Quantity = 2;
        SummaryAmount2 = 2500;
        oppline.Amount_Despite_VIP__c = 2500;
        oppLine.Product_Category__c = 'Subscription';
        listOppLine.add(oppLine);
        insert listOppLine;
        
        //oppLine = [select Id, Product_Category__c, Amount_Despite_VIP__c, Opportunity.Summary_Of_Subscription_Item__c, UnitPrice, Amount__c from OpportunityLineItem where id =: opp.id or id=:opp1.Id];
        system.debug('OPPLINE:'+oppLine);
        
        //listOpp = [Select id, Is_Current_Subscription__c, StageName, Include_Subscription_Ext__c, Attachment_Limit_Exceeded__c, OMC_Approved_Date__c, Approval_Status__c,Summary_Of_Subscription_Item__c,IsWon,recordtype.name,Summary_Of_Subscription_Item_new__c from opportunity where id =: opp.id or id=:opp1.Id];
        for (Opportunity row: listOpp) {
            row.StageName = 'Closed Won';
            row.Approval_Status__c = 'OMC Approval Approved';
            row.Is_Current_Subscription__c = true;
            row.Attachment_Limit_Exceeded__c = true;
            if(row.Id == opp1.Id){
                row.OMC_Approved_Date__c = date.today().addDays(-366);
            }
            else{
                row.OMC_Approved_Date__c = date.today();
            }
            row.Summary_Of_Subscription_Item_new__c = 1;
            //
        } 
        update listOpp;
      
        Database.executeBatch(new OptyRollUpFieldUpd_Batch(opp.id));
        Database.executeBatch(new OptyRollUpFieldUpd_Batch(opp1.id));
         System.schedule('Job from test class 5', '0 0 0 * * ? *', new SlackAlert_BatchSchedulable());
        System.schedule('Job from test class 3', '0 0 0 * * ? *', new AccountCSS_BatchSchedulable());
        System.schedule('Job from test class 4', '0 0 0 * * ? *', new AccountTS_BatchSchedulable());
       test.stopTest();
        
    }

	static testMethod void runTest3(){
              
         test.startTest(); 
         list<Opportunity> listOpp = new list<Opportunity>();
        list<Opportunity> listOpp2 = new list<Opportunity>();
        
        string accRectype = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Agent').getRecordTypeId();
        PGTestDataFactory_v2.initSetupData();
        Subsidiary__c sb = PGTestDataFactory.createSubsidiary();
        
        Account a = new Account();
        a.RecordTypeId = accRectype;
        a.FirstName = 'IsYuni';
        a.LastName = 'TestYuni';
        a.AgentNet_ID__c = 'AgentNet_ID__c test';
        a.Salutation = 'Mrs.';
        a.CurrencyIsoCode = 'SGD';
        a.Subscription_Start_Date__c = system.today().addMonths(-10);
        a.BillingStreet = 'test';
        a.BillingCity = 'test';
        a.BillingCountry = 'Singapore';
        a.BillingPostalCode = '8373';
      //  a.BillingState = 'test';
        a.Current_Subscription_Code__c = 'abc';
        a.PersonEmail = 'test@yuni.com';
        a.Status__c = 'Active';
        a.Account_Rule_Code__c = 'test';
        a.Subsidiary__pc = sb.Id;
        a.Country__c = 'Singapore';
        a.CEA_Salesperson_Number__c = '51231231';
        a.PersonBirthdate = date.newInstance(1970, 1, 1);
        a.Current_Subscription_Spending_Amount__c = 200;
        a.CEA_Salesperson_Number__c = 'CEACHECK';
        a.PersonBirthdate = Date.newInstance(1996, 12, 21);
        insert a;
        
        Tax_Code__c taxcode = new Tax_Code__c();
        taxcode.Name = 'SG - 7% GST';
        taxcode.Tax_Rate__c =  7;
        taxcode.Country__c = 'Singapore';
        insert taxcode;
        
        string oppRectype = Schema.SObjectType.Opportunity.getRecordTypeInfosByName().get('B2C').getRecordTypeId();
        Opportunity opp = new opportunity();
        opp.Name = 'Test Opp';
        opp.StageName = 'Closed Won';
        opp.AccountId = a.id;
        opp.CloseDate = system.today().AddDays(-30);
        opp.Subsidiary__c = sb.id;
        opp.PG_Tenure__c = 4;
        opp.Total_Spending__c = 100;
        opp.Months_Included__c = false;
        opp.Is_Current_Subscription__c = true;
        opp.RecordTypeId =oppRectype;
        opp.Include_Subscription_Ext__c = true;
        opp.Summary_Of_Subscription_Item_new__c = null;
        opp.Total_Spending_on_Discretionary_Prod_new__c = null;
        opp.Order_Type_Clone__c = 'Contract - Upgrade';
        opp.Approval_Status__c = 'OMC Approval Approved';
		opp.OMC_Approved_Date__c = date.today().addDays(-366);
        listOpp.add(opp);
        
        Pricebook2 standardPB = new Pricebook2(Name = 'Standard Pricebook', Description = 'Price Book', Subsidiary__c = sb.id,  IsActive = true, CurrencyIsoCode = 'SGD');
        insert standardPB;
        
        Product_Class__c productClass = new Product_Class__c(Name = 'Tier1UnitSubNew', CurrencyIsoCode = 'SGD'/*, NS_Internal_ID__c ='1234567890'*/);
        insert productClass;
        
        list<Product2> listProd = new list<Product2>();
        Product2 prod = new Product2(Name = 'Test Prod', IsActive = true, Segment__c = 'B2C Only', Product_Category__c = 'Subscription', SKU_Code__c = 'abc', Product_Class__c = productClass.Id, Tax_Code__c = taxcode.Id);
        listProd.add(prod);
        
        Product2 prod2 = new Product2(Name = 'Test Prod2', IsActive = true, Segment__c = 'B2C Only', Product_Category__c = 'Subscription', SKU_Code__c = 'abc', Product_Class__c = productClass.Id, Tax_Code__c = taxcode.Id);
        listProd.add(prod2);
        insert listProd;
        
        Id StdpricebookId = Test.getStandardPricebookId();
        
        list<PricebookEntry> listPBE = new list<PricebookEntry>();
        PricebookEntry pbe = new PricebookEntry(pricebook2id=StdpricebookId, product2id=prod.id, unitprice=100.0, isActive=true);
        listPBE.add(pbe);
        
        PricebookEntry pbe2 = new PricebookEntry(pricebook2id=standardPB.Id, product2id=prod.id, unitprice=100.0, isActive=true, CurrencyIsoCode = 'SGD', UseStandardPrice = false);
        listPBE.add(pbe2);
        insert listPBE;
        
        opp = new opportunity();
        opp.Name = 'Test Opp 2';
        opp.StageName = 'Closed Won';
        opp.AccountId = a.id;
        opp.CloseDate = system.today().AddDays(-10);
        opp.Subsidiary__c = sb.id;
        opp.PG_Tenure__c = 4;
        opp.Total_Spending__c = 100;
        opp.Months_Included__c = true;
        opp.Is_Current_Subscription__c = true;
        opp.RecordTypeId =oppRectype;
        opp.Include_Subscription_Ext__c = true;
        opp.Order_Type_Clone__c = 'Contract - Upgrade';
        opp.Total_Spending_on_Discretionary_Prod_new__c = null;
        opp.Approval_Status__c = 'OMC Approval Approved';
		opp.OMC_Approved_Date__c = date.today().addDays(-366);
        listOpp.add(opp);
        
        Opportunity opp1 = new opportunity();
        opp1.Name = 'Test Opp 3';
        opp1.StageName = 'Closed Won';
        opp1.AccountId = a.id;
        opp1.CloseDate = system.today().AddDays(-325);
        opp1.Subsidiary__c = sb.id;
        opp1.PG_Tenure__c = 4;
        opp1.Total_Spending__c = 100;
        opp1.Months_Included__c = true;
        opp1.Is_Current_Subscription__c = true;
       	opp1.RecordTypeId =oppRectype;
        opp1.Include_Subscription_Ext__c = true;
        opp1.Order_Type_Clone__c = 'Contract - Upgrade';
        opp1.Summary_Of_Subscription_Item_new__c = null;
        opp1.Total_Spending_on_Discretionary_Prod_new__c = null;
        opp.Approval_Status__c = 'OMC Approval Approved';
		opp.OMC_Approved_Date__c = date.today().addDays(-366);
        listOpp.add(opp1);
        
        insert listOpp;
        
        Integer SummaryAmount1 = 0, SummaryAmount2 = 0;
        list<OpportunityLineItem> listOppLine = new list<OpportunityLineItem>();
        OpportunityLineItem oppLine = New OpportunityLineItem();
        oppLine.OpportunityId = listOpp[0].Id;
        oppLine.Push_to_NetSuite__c = true;
        oppLine.PricebookEntryId = pbe2.Id;
        oppLine.Product2Id = prod.Id;
        oppLine.UnitPrice = 300;
        oppLine.Product_Category__c = 'Subscription';
        oppLine.Discount_Reason__c = 'VIP (Relationship)';
        oppLine.Quantity = 2;
        SummaryAmount1 = 300;
        oppline.Amount_Despite_VIP__c = 300;
        listOppLine.add(oppLine);
        
        oppLine = New OpportunityLineItem();
        oppLine.OpportunityId = listOpp[1].Id;
        oppLine.Push_to_NetSuite__c = true;
        oppLine.PricebookEntryId = pbe2.Id;
        oppLine.Product2Id = prod.Id;
        oppLine.UnitPrice = 2500;
        oppLine.Quantity = 2;
        SummaryAmount2 = 2500;
        oppline.Amount_Despite_VIP__c = 2500;
        oppLine.Product_Category__c = 'Subscription';
        oppLine.Discount_Reason__c = 'VIP (Spending)';
        listOppLine.add(oppLine);
        insert listOppLine;
        
        //oppLine = [select Id, Product_Category__c, Amount_Despite_VIP__c, Opportunity.Summary_Of_Subscription_Item__c, UnitPrice, Amount__c from OpportunityLineItem where id =: opp.id or id=:opp1.Id];
        system.debug('OPPLINE:'+oppLine);
        
        //listOpp = [Select id, Is_Current_Subscription__c, StageName, Include_Subscription_Ext__c, Attachment_Limit_Exceeded__c, OMC_Approved_Date__c, Approval_Status__c,Summary_Of_Subscription_Item__c,IsWon,recordtype.name,Summary_Of_Subscription_Item_new__c from opportunity where id =: opp.id or id=:opp1.Id];
        for (Opportunity row: listOpp) {
            row.StageName = 'Closed Won';
            row.Approval_Status__c = 'OMC Approval Approved';
            row.Is_Current_Subscription__c = true;
            row.Attachment_Limit_Exceeded__c = true;
            if(row.Id == opp1.Id){
                row.OMC_Approved_Date__c = date.today().addDays(-366);
            }
            else{
                row.OMC_Approved_Date__c = date.today();
            }
            row.Summary_Of_Subscription_Item_new__c = 1;
            //
        } 
        update listOpp;
      
        Database.executeBatch(new OptyRollUpFieldUpd_Batch_DF());
       test.stopTest();
        
    }
    
}