unpackaged/main/default/objects/Account/fields/Account_Rule_Code__c.field-meta.xml
<CustomField>
    <fullName>Account_Rule_Code__c</fullName>
    <defaultValue>IF( $RecordType.DeveloperName = &quot;Agent&quot;, &quot;TRIAL&quot;, &quot;&quot;)</defaultValue>
    <description>Denotes account rule code (short text) for the account rule</description>
    <inlineHelpText>Denotes account rule code (short text) for the account rule</inlineHelpText>
    <label>Account Rule Code</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/AgentNet_ID__c.field-meta.xml
<CustomField>
    <fullName>AgentNet_ID__c</fullName>
    <description>Denotes a numeric id of agents in PG system</description>
    <inlineHelpText>Denotes a numeric id of agents in PG system</inlineHelpText>
    <label>AgentNet ID</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/CEA_License__c.field-meta.xml
<CustomField>
    <fullName>CEA_License__c</fullName>
    <description>Denotes the agency license number registered under a governing authority</description>
    <externalId>true</externalId>
    <inlineHelpText>Denotes the agency registration number issued by CEA for SG agencies and MIEA for MY agencies</inlineHelpText>
    <label>Agency Identification Number</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/CEA_Salesperson_Number__c.field-meta.xml
<CustomField>
    <fullName>CEA_Salesperson_Number__c</fullName>
    <description>Denotes the agent license number registered under a governing authority</description>
    <inlineHelpText>Denotes the agent registration number issued by CEA for SG agents and MIEA for MY agents</inlineHelpText>
    <label>Agent Identification Number</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/Commandos_Team_Lead__c.field-meta.xml
<CustomField>
    <fullName>Commandos_Team_Lead__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Denotes the team lead in commandos sales team whose responsible for agency relationship</description>
    <inlineHelpText>Denotes the team lead in commandos sales team whose responsible for agency relationship</inlineHelpText>
    <label>Commandos Team Lead</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/Current_Subscription_Code__c.field-meta.xml
<CustomField>
    <fullName>Current_Subscription_Code__c</fullName>
    <label>Current Subscription Code</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/Customer_Type__c.field-meta.xml
<CustomField>
    <fullName>Customer_Type__c</fullName>
    <description>Created a custom field as standard field &#39;Type&#39; cannot be mapped in lead mapping</description>
    <label>Customer Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Agent</fullName>
            </value>
            <value>
                <fullName>Owner</fullName>
            </value>
            <value>
                <fullName>Agency</fullName>
            </value>
            <value>
                <fullName>Developer</fullName>
                <default>true</default>
                <label>Developer</label>
            </value>
            <value>
                <fullName>Non-Property</fullName>
            </value>
            <value>
                <fullName>Consumer</fullName>
            </value>
            <value>
                <fullName>Media Agency</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Account/fields/Subscription_End_Date__c.field-meta.xml
<CustomField>
    <fullName>Subscription_End_Date__c</fullName>
    <description>Denotes end date of an agent&#39;s current subscriptions</description>
    <inlineHelpText>Denotes end date of an agent&#39;s current subscriptions</inlineHelpText>
    <label>Subscription End Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/Subscription_Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Subscription_Start_Date__c</fullName>
    <description>Denotes the start date of agent&#39;s current subscription</description>
    <inlineHelpText>Denotes the start date of agent&#39;s current subscription</inlineHelpText>
    <label>Subscription Start Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/Account/recordTypes/Agency.recordType-meta.xml
<RecordType>
    <fullName>Agency</fullName>
    <active>true</active>
    <label>Agency</label>
</RecordType>

unpackaged/main/default/classes/AccountAssignment_Batch_Test.cls
/*
* Created by : Yuni
* Company    : Viseo Asia PTE LTD
* created Date : 27/07/2018
*/
@isTest
public class AccountAssignment_Batch_Test {
    static testMethod void runTest() {
        Test.StartTest();
PGTestDataFactory_v2.CreateTriggerExecuteCS('PGAccountTrigger',true);
//        Group g = new Group();
//        g.Name = 'New Business Team';
//        g.Type = 'Queue';
//        insert g;
 PGTestDataFactory_v2.CreateTriggerExecuteCS('PGAccountTrigger',true);

        Profile p = [SELECT Id FROM Profile WHERE Name='System Administrator'];
        User u = new User(Alias = 'gtest', Email='giantest@testorg.com',
                EmailEncodingKey='UTF-8', LastName='GianTest', LanguageLocaleKey='en_US',
                LocaleSidKey='en_US', ProfileId = p.Id,
                TimeZoneSidKey='America/Los_Angeles', UserName='giantest@testorg.com'
        );

        insert u;

        User uManager = new User(Alias = 'gManager', Email='giantestmanager@testorg.com',
                EmailEncodingKey='UTF-8', LastName='GianTestmanager', LanguageLocaleKey='en_US',
                LocaleSidKey='en_US', ProfileId = p.Id,
                TimeZoneSidKey='America/Los_Angeles', UserName='giantestmanager@testorg.com'
        );

        insert uManager;

        u.ManagerId = uManager.Id;
        update u;

        System.runAs(u){
            Group q = [SELECT Id, Name FROM Group WHERE Name = 'New Business Team' AND Type = 'Queue'];
            GroupMember gm = new GroupMember(GroupId = q.Id, UserOrGroupId = u.Id);
            insert gm;
        }

        string accRectype = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Agent').getRecordTypeId();
        Account a = new Account();
        a.RecordTypeId = accRectype;
        a.LastName = 'TestYuni1';
        a.CurrencyIsoCode = 'SGD';
        a.Subscription_Start_Date__c = system.today().addMonths(-10);
        a.BillingStreet = 'test';
        a.BillingCity = 'test';
        a.BillingCountry = 'Singapore';
        a.BillingPostalCode = '8373';
        //a.BillingState = 'Singapore';
        
        a.Current_Subscription_Code__c = 'abc';
        a.account_rule_code__c = 'Standard';
        a.personemail = 'aa123@yaho.com';
        a.salutation = 'Mr.';
        a.firstname = 'aaaa';
        a.CEA_Salesperson_Number__c = 'CEACHECK';
        a.PersonBirthdate = system.today();
        insert a;

        Account ac = new Account();
        ac.RecordTypeId = accRectype;
        ac.LastName = 'TestYuni222323323';
        ac.AgentNet_ID__c = 'TestPurposeId';
        ac.CurrencyIsoCode = 'SGD';
        ac.Subscription_Start_Date__c = system.today().addMonths(-10);
        ac.Subscription_End_Date__c = system.today().addMonths(1);
        ac.BillingStreet = 'test';
        ac.BillingCity = 'test';
        ac.BillingCountry = 'Singapore';
        ac.BillingPostalCode = '8373';
        //ac.BillingState = 'test';
        ac.Account_Rule_Code__c = 'Premier';
        
        ac.Current_Subscription_Code__c = 'abc';
        ac.personemail = 'aaaaaasadxx@yaho.com';
        ac.salutation = 'Mr.';
        ac.firstname = 'aaaa';
        ac.CEA_Salesperson_Number__c = 'CEACHECK';
        ac.PersonBirthdate = system.today();
        insert ac;
        
        
        Account acommando = new Account();
        acommando.RecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Agency').getRecordTypeId();
        acommando.Name = 'Unit Test Agency';
        acommando.CurrencyIsoCode = 'SGD';
        acommando.Customer_Type__c = 'Agency';
        acommando.CEA_License__c = 'testcea';
        acommando.Commandos_Team_Lead__c = u.Id;
       
        insert acommando;

        Account acommando2 = new Account();
        acommando2.RecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Agency').getRecordTypeId();
        acommando2.Name = 'Dummy commando Unit Test Agency 2 test viseo';
        acommando2.CurrencyIsoCode = 'SGD';
        acommando2.Customer_Type__c = 'Agency';
        acommando2.CEA_License__c = 'testcea2233ss';
        
        insert acommando2;

        AccountAssignment_BatchSchedulable sh1 = new AccountAssignment_BatchSchedulable();
        String sch = '0 0 0 * * ? *';
        system.schedule('Test Schedule', sch, sh1);

        Test.stopTest();
    }
}