unpackaged/main/default/objects/Account/fields/Account_Rule_Code__c.field-meta.xml
<CustomField>
    <fullName>Account_Rule_Code__c</fullName>
    <defaultValue>IF( $RecordType.DeveloperName = &quot;Agent&quot;, &quot;TRIAL&quot;, &quot;&quot;)</defaultValue>
    <description>Denotes account rule code (short text) for the account rule</description>
    <inlineHelpText>Denotes account rule code (short text) for the account rule</inlineHelpText>
    <label>Account Rule Code</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/AgentNet_ID__c.field-meta.xml
<CustomField>
    <fullName>AgentNet_ID__c</fullName>
    <description>Denotes a numeric id of agents in PG system</description>
    <inlineHelpText>Denotes a numeric id of agents in PG system</inlineHelpText>
    <label>AgentNet ID</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/CEA_Salesperson_Number__c.field-meta.xml
<CustomField>
    <fullName>CEA_Salesperson_Number__c</fullName>
    <description>Denotes the agent license number registered under a governing authority</description>
    <inlineHelpText>Denotes the agent registration number issued by CEA for SG agents and MIEA for MY agents</inlineHelpText>
    <label>Agent Identification Number</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/Country__c.field-meta.xml
<CustomField>
    <fullName>Country__c</fullName>
    <defaultValue>if(  BEGINS($UserRole.Name, &quot;TH&quot;),&quot;Thailand&quot;,if(ISPICKVAL($User.Subsidiary__c,&quot;MyProperty Data Sdn. Bhd.&quot;),&quot;Malaysia&quot;,&quot;&quot;))</defaultValue>
    <description>Denotes the country of an account</description>
    <inlineHelpText>Denotes the country of an account</inlineHelpText>
    <label>Country</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Country</valueSetName>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Account/fields/Current_Subscription_Code__c.field-meta.xml
<CustomField>
    <fullName>Current_Subscription_Code__c</fullName>
    <label>Current Subscription Code</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/Customer_Type__c.field-meta.xml
<CustomField>
    <fullName>Customer_Type__c</fullName>
    <description>Created a custom field as standard field &#39;Type&#39; cannot be mapped in lead mapping</description>
    <label>Customer Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Agent</fullName>
            </value>
            <value>
                <fullName>Owner</fullName>
            </value>
            <value>
                <fullName>Agency</fullName>
            </value>
            <value>
                <fullName>Developer</fullName>
                <default>true</default>
                <label>Developer</label>
            </value>
            <value>
                <fullName>Non-Property</fullName>
            </value>
            <value>
                <fullName>Consumer</fullName>
            </value>
            <value>
                <fullName>Media Agency</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Account/fields/Is_Qualify_Agent_Referral_Program__c.field-meta.xml
<CustomField>
    <fullName>Is_Qualify_Agent_Referral_Program__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Denotes whether agent is qualify for referral program</description>
    <inlineHelpText>Denotes whether agent is qualify for referral program</inlineHelpText>
    <label>Is Qualify Agent Referral Program</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/Loyalty_Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Loyalty_Start_Date__c</fullName>
    <description>Denotes the loyalty start date of an agent</description>
    <inlineHelpText>Denotes the loyalty start date of an agent</inlineHelpText>
    <label>Loyalty Start Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/Previous_Account_Rule__c.field-meta.xml
<CustomField>
    <fullName>Previous_Account_Rule__c</fullName>
    <description>Denotes the account rule code of agents which corresponds to the previous subscription</description>
    <inlineHelpText>Denotes the account rule code of agents which corresponds to the previous subscription</inlineHelpText>
    <label>Previous Account Rule Code</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>Denotes the status of an agent in the agent lifecycle</description>
    <inlineHelpText>Denotes the status of an agent in the agent lifecycle</inlineHelpText>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Trial</fullName>
            </value>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Downgraded</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Suspended</fullName>
            </value>
            <value>
                <fullName>Expired</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Account/fields/Subscription_End_Date__c.field-meta.xml
<CustomField>
    <fullName>Subscription_End_Date__c</fullName>
    <description>Denotes end date of an agent&#39;s current subscriptions</description>
    <inlineHelpText>Denotes end date of an agent&#39;s current subscriptions</inlineHelpText>
    <label>Subscription End Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/Subscription_Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Subscription_Start_Date__c</fullName>
    <description>Denotes the start date of agent&#39;s current subscription</description>
    <inlineHelpText>Denotes the start date of agent&#39;s current subscription</inlineHelpText>
    <label>Subscription Start Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/Subsidiary__c.field-meta.xml
<CustomField>
    <fullName>Subsidiary__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Denotes the PG subsidiary to which the account belongs to</description>
    <inlineHelpText>Denotes the PG subsidiary to which the account belongs to</inlineHelpText>
    <label>Subsidiary</label>
    <referenceTo>Subsidiary__c</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/Total_Spending__c.field-meta.xml
<CustomField>
    <fullName>Total_Spending__c</fullName>
    <defaultValue>0</defaultValue>
    <inlineHelpText>This is total spending on Discretionary Products</inlineHelpText>
    <label>Total Spending</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

unpackaged/main/default/objects/Account/recordTypes/Agency.recordType-meta.xml
<RecordType>
    <fullName>Agency</fullName>
    <active>true</active>
    <label>Agency</label>
</RecordType>

unpackaged/main/default/objects/Opportunity/fields/Account_Rule_Code__c.field-meta.xml
<CustomField>
    <fullName>Account_Rule_Code__c</fullName>
    <label>Account Rule Code</label>
    <length>15</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Billing_City_new__c.field-meta.xml
<CustomField>
    <fullName>Billing_City_new__c</fullName>
    <label>Billing-City</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Billing_Country_new__c.field-meta.xml
<CustomField>
    <fullName>Billing_Country_new__c</fullName>
    <label>Billing-Country</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Billing_Street_new__c.field-meta.xml
<CustomField>
    <fullName>Billing_Street_new__c</fullName>
    <label>Billing-Street</label>
    <type>TextArea</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Country__c.field-meta.xml
<CustomField>
    <fullName>Country__c</fullName>
    <formula>TEXT(Subsidiary__r.Country__c )</formula>
    <label>Country</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Subscription_End_Date__c.field-meta.xml
<CustomField>
    <fullName>Subscription_End_Date__c</fullName>
    <label>Subscription End Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Subsidiary__c.field-meta.xml
<CustomField>
    <fullName>Subsidiary__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Subsidiary</label>
    <referenceTo>Subsidiary__c</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Total_Spending__c.field-meta.xml
<CustomField>
    <fullName>Total_Spending__c</fullName>
    <label>Total Spending (last 12 months)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/recordTypes/B2C.recordType-meta.xml
<RecordType>
    <fullName>B2C</fullName>
    <active>true</active>
    <businessProcess>B2C</businessProcess>
    <description>B2C Opportunity Record</description>
    <label>B2C</label>
</RecordType>

unpackaged/main/default/objects/QliToOliFieldMapping__c/QliToOliFieldMapping__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>This custom setting is user for mapping Quote line item&#39;s fields to Opportunity Line Item when status of Quote is Accepted. Use Name as Quote lint item&#39;s fields API and oliField__c for Opportuntiy line item&#39;s fields API.</description>
    <label>QliToOliFieldMapping</label>
</CustomObject>

unpackaged/main/default/objects/QliToOliFieldMapping__c/fields/OliField__c.field-meta.xml
<CustomField>
    <fullName>OliField__c</fullName>
    <label>OliField</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Quote/fields/Account_Rule_Code__c.field-meta.xml
<CustomField>
    <fullName>Account_Rule_Code__c</fullName>
    <label>Account Rule Code</label>
    <length>15</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Quote/fields/Country__c.field-meta.xml
<CustomField>
    <fullName>Country__c</fullName>
    <formula>TEXT(Opportunity.Subsidiary__r.Country__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Country</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Quote/fields/Subscription_End_Date__c.field-meta.xml
<CustomField>
    <fullName>Subscription_End_Date__c</fullName>
    <label>Subscription End Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/Quote/fields/Subsidiary__c.field-meta.xml
<CustomField>
    <fullName>Subsidiary__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Subsidiary</label>
    <referenceTo>Subsidiary__c</referenceTo>
    <relationshipLabel>Quotes</relationshipLabel>
    <relationshipName>Quotes</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Quote/recordTypes/B2C.recordType-meta.xml
<RecordType>
    <fullName>B2C</fullName>
    <active>true</active>
    <label>B2C</label>
</RecordType>

unpackaged/main/default/objects/Subsidiary__c/Subsidiary__c.object-meta.xml
<CustomObject>
    <description>This is a custom object to contain the information on Subsidiary and Country</description>
    <label>Subsidiary</label>
    <nameField>
        <label>Subsidiary Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Subsidiaries</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Subsidiary__c/fields/Country__c.field-meta.xml
<CustomField>
    <fullName>Country__c</fullName>
    <description>Values from global picklist</description>
    <label>Country</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Country</valueSetName>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Subsidiary__c/fields/Logo_url__c.field-meta.xml
<CustomField>
    <fullName>Logo_url__c</fullName>
    <label>Logo url</label>
    <type>Url</type>
</CustomField>

unpackaged/main/default/objects/Subsidiary__c/fields/NS_Subsidiary_Internal_ID__c.field-meta.xml
<CustomField>
    <fullName>NS_Subsidiary_Internal_ID__c</fullName>
    <description>NetSuite record internal ID</description>
    <externalId>true</externalId>
    <label>NS Subsidiary Internal ID</label>
    <length>20</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

unpackaged/main/default/objects/Subsidiary__c/fields/Tax_Label__c.field-meta.xml
<CustomField>
    <fullName>Tax_Label__c</fullName>
    <description>This label is used in the Print Contract PDF to display tax</description>
    <inlineHelpText>GST | VAT</inlineHelpText>
    <label>Tax Label</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Trigger_Execute__c/Trigger_Execute__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>Trigger Execute</label>
</CustomObject>

unpackaged/main/default/objects/Trigger_Execute__c/fields/Enable_del__c.field-meta.xml
<CustomField>
    <fullName>Enable_del__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Enable del</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Trigger_Execute__c/fields/IsTrackingEnable__c.field-meta.xml
<CustomField>
    <fullName>IsTrackingEnable__c</fullName>
    <defaultValue>false</defaultValue>
    <label>IsTrackingEnable</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/User/fields/Subsidiary__c.field-meta.xml
<CustomField>
    <fullName>Subsidiary__c</fullName>
    <label>Subsidiary</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Subsidiary</valueSetName>
    </valueSet>
</CustomField>

unpackaged/main/default/classes/SG_RenewalOppty_SendEmailReminder_test.cls
@isTest
public class SG_RenewalOppty_SendEmailReminder_test {
    
     public static testMethod void unitTest(){
        PGTestDataFactory_v2.CreateTriggerExecuteCS('PGAccountTrigger',true); 
        User runningUser = [Select id, Subsidiary__c From user where id =: UserInfo.getUserId() LIMIT 1];
        runningUser.Subsidiary__c = 'PropertyGuru Pte Ltd';
        update runningUser;
        string accRectype = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Agent').getRecordTypeId();
        string oppRectype = Schema.SObjectType.Opportunity.getRecordTypeInfosByName().get('B2C').getRecordTypeId();
        string quoteRectype = Schema.SObjectType.quote.getRecordTypeInfosByName().get('B2C').getRecordTypeId();
        
        Trigger_Execute__c tE = new Trigger_Execute__c();
        tE.Name = 'QuoteLineItemTrigger';
        insert tE;
        Subsidiary__c sb = new Subsidiary__c();
        sb.Name = 'PropertyGuru Pte Ltd';
        sb.NS_Subsidiary_Internal_ID__c = '1';
        sb.CurrencyIsoCode = 'SGD';
        sb.Tax_Label__c = 'taxLabel';
        sb.Country__c = 'Singapore';
        sb.Logo_url__c='https://c.ap5.visual.force.com/resource/1525687701000/SG_Sales_Order_Header_v3_PGG';
        insert sb;
        
        QliToOliFieldMapping__c objcustomsetting=new QliToOliFieldMapping__c();
        objcustomsetting.Name='Start_Date__c';
        objcustomsetting.OliField__c='Start_Date__c';
        insert objcustomsetting;
        
        Trigger_Execute__c objcustom=new Trigger_Execute__c();
        objcustom.Name='Trigger_Quote';
        objcustom.Enable_del__c=true;
        objcustom.IsTrackingEnable__c = true;
        insert objcustom;
        
        Account a = new Account();
        a.RecordTypeId = accRectype;
        a.FirstName = 'IsYuni';
        a.LastName = 'TestYuni';
        a.AgentNet_ID__c = 'AgentNet_ID__c test';
        a.Salutation = 'Mrs.';
        //a.Customer_Type__c = 'Agency';
        a.CurrencyIsoCode = 'SGD';
        a.Subscription_Start_Date__c = system.today().addMonths(-10);
        a.BillingStreet = 'test';
        a.BillingCity = 'test';
        a.BillingCountry = 'Singapore';
        a.BillingPostalCode = '8373';
        //a.BillingState = 'test';
        a.Current_Subscription_Code__c = 'abc';
        a.PersonEmail = 'test@yuni.com';
        a.Account_Rule_Code__c = 'test';
        a.Previous_Account_Rule__c = 'test';
        a.Status__c = 'Active';
        a.Country__c = 'Singapore';
        a.Subscription_End_Date__c = system.today().addMonths(-9);
        a.Loyalty_Start_Date__c = system.today().addMonths(-1);
        a.Is_Qualify_Agent_Referral_Program__c = true;
        a.CEA_Salesperson_Number__c = 'CEACHECK';
        a.PersonBirthdate = Date.newInstance(1996, 12, 21);
        insert a;
        Opportunity opp = new opportunity();
        opp.Name = 'Test Opp';
        opp.StageName = 'Proposal';
        opp.AccountId = a.id;
        opp.CloseDate = system.today().AddDays(30);
        opp.Subsidiary__c = sb.id;
        opp.Total_Spending__c = 100;
        opp.RecordTypeId = oppRectype;
        opp.Billing_Street_new__c='TEst';
        opp.Billing_City_new__c='city';
        opp.Billing_Country_new__c='Singapore';
        opp.PG_Tenure__c = 1;
        opp.Stinger__c = true;
        opp.Opportunity_Type__c = 'B2C - Renewal';
        opp.Order_Type_Clone__c   = 'Contract - Renewal';
        
        insert opp;
        system.assertEquals(opp.Id,opp.Id,'1');
        
        Quote objquote=new Quote();
        objquote.name='Test';
        objquote.CreatedDate__c=system.today();
        objquote.OpportunityId=opp.Id;
        objquote.Subsidiary__c = sb.id;
        objquote.CurrencyIsoCode = 'SGD';
        objquote.RecordTypeId = quoteRectype;
        insert objquote;
        
        opp.SyncedQuoteId=objquote.Id;
        opp.OMC_Approved_Date__c=system.today();
        opp.stageName='Pending OMC Approval';
        opp.Submit_to_OMC_Manually__c =false;
        
        opp.Approval_Status__c='OMC Approval Approved';
        update opp;
        
        objquote.Status='Pending Online Payment';
        
        objquote.SG_Payment_Link_Expiry__c=system.today().AddDays(15);
        objquote.Guruland_Link_Created_Date__c =system.today().AddDays(10);
        objquote.Approval_Status__c='OMC Approval Approved';
        objquote.Agent_Accepted_Time__c =null;
        
        
        update objquote;
        
        Quote objquote1=new Quote();
        objquote1.name='Test';
        objquote1.CreatedDate__c=system.today();
        objquote1.OpportunityId=opp.Id;
        objquote1.Subsidiary__c = sb.id;
        objquote1.CurrencyIsoCode = 'SGD';
        objquote1.RecordTypeId = quoteRectype;
        insert objquote1;
        
        
        objquote1.Status='Pending Online Payment';
        
        objquote1.SG_Payment_Link_Expiry__c=system.today().AddDays(15);
        objquote1.Guruland_Link_Created_Date__c =system.today().AddDays(10);
        objquote1.Approval_Status__c='OMC Approval Approved';
        objquote1.Agent_Accepted_Time__c =null;
        objquote1.Payment_Next_Reminder_Date__c =system.today().AddDays(7);
        
        
        update objquote1;
        
        System.debug(objquote1.recordtype.name);
        list<quote> quotelist = [Select id  ,Guruland_Link_Created_Date__c,IsSyncing,country__c,Payment_Next_Reminder_Date__c,recordtype.name,SG_Payment_Link_Expiry__c,Quote_Type__c,Status,Agent_Accepted_Time__c from quote where id =:objquote.id OR id =:objquote1.id ];
        system.debug(quotelist[0].status+'--->>>'+quotelist[0].SG_Payment_Link_Expiry__c+'---->>'+quotelist[0].country__c+'---->>'+quotelist[0].IsSyncing+'---->>'+quotelist[0].recordtype.name+'--->>>'+quotelist[0].Quote_Type__c+'-->>'+quotelist[0].Agent_Accepted_Time__c);
        
        test.startTest();
        SG_RenewalOppty_SendEmailReminder obj = new SG_RenewalOppty_SendEmailReminder();
        //   database.executeBatch(obj);
        obj.start(null);
        obj.execute(null,quotelist);
        obj.finish(null);
        test.stoptest();
        
    }
}