unpackaged/main/default/objects/Account/fields/AgentKey__c.field-meta.xml
<CustomField>
    <fullName>AgentKey__c</fullName>
    <description>Denotes a unique key specifying the countrycodes(SG,MY,TH,ID) and the unique id in PG system</description>
    <externalId>true</externalId>
    <inlineHelpText>Denotes a unique key specifying the countrycodes(SG,MY,TH,ID) and the unique id in PG system</inlineHelpText>
    <label>AgentKey</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/Country__c.field-meta.xml
<CustomField>
    <fullName>Country__c</fullName>
    <defaultValue>if(  BEGINS($UserRole.Name, &quot;TH&quot;),&quot;Thailand&quot;,if(ISPICKVAL($User.Subsidiary__c,&quot;MyProperty Data Sdn. Bhd.&quot;),&quot;Malaysia&quot;,&quot;&quot;))</defaultValue>
    <description>Denotes the country of an account</description>
    <inlineHelpText>Denotes the country of an account</inlineHelpText>
    <label>Country</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Country</valueSetName>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Account/fields/NetSuite_Id__c.field-meta.xml
<CustomField>
    <fullName>NetSuite_Id__c</fullName>
    <externalId>true</externalId>
    <label>NetSuite Id</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

unpackaged/main/default/objects/Account/fields/Sync_to_NetSuite__c.field-meta.xml
<CustomField>
    <fullName>Sync_to_NetSuite__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Sync to NetSuite</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Appr_Code__c.field-meta.xml
<CustomField>
    <fullName>Appr_Code__c</fullName>
    <label>Appr Code</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Country__c.field-meta.xml
<CustomField>
    <fullName>Country__c</fullName>
    <formula>TEXT(Subsidiary__r.Country__c )</formula>
    <label>Country</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Invoice_Id__c.field-meta.xml
<CustomField>
    <fullName>Invoice_Id__c</fullName>
    <externalId>true</externalId>
    <label>Invoice Id</label>
    <length>20</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Opportunity_Type__c.field-meta.xml
<CustomField>
    <fullName>Opportunity_Type__c</fullName>
    <defaultValue>IF( $RecordType.DeveloperName = &#39;B2C&#39; , &#39;B2C - Standard&#39;, null)</defaultValue>
    <label>Opportunity Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>B2C - Standard</fullName>
            </value>
            <value>
                <fullName>B2C - Upgrade</fullName>
            </value>
            <value>
                <fullName>B2C - Renewal</fullName>
            </value>
            <value>
                <fullName>Self-Serve Standard</fullName>
            </value>
            <value>
                <fullName>Self-Serve Renewal</fullName>
            </value>
            <value>
                <fullName>Self-Serve Abandoned</fullName>
            </value>
            <value>
                <fullName>Marketing Automation</fullName>
            </value>
            <value>
                <fullName>B2C - Conversion</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Payment_Gateway__c.field-meta.xml
<CustomField>
    <fullName>Payment_Gateway__c</fullName>
    <label>Payment Gateway</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Adyen</fullName>
            </value>
            <value>
                <fullName>Braintree</fullName>
            </value>
            <value>
                <fullName>PayPal</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Sync_To_NetSuite__c.field-meta.xml
<CustomField>
    <fullName>Sync_To_NetSuite__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Sync To NetSuite</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/recordTypes/B2C.recordType-meta.xml
<RecordType>
    <fullName>B2C</fullName>
    <active>true</active>
    <businessProcess>B2C</businessProcess>
    <description>B2C Opportunity Record</description>
    <label>B2C</label>
</RecordType>

unpackaged/main/default/objects/OpportunityLineItem/fields/Discount__c.field-meta.xml
<CustomField>
    <fullName>Discount__c</fullName>
    <defaultValue>0</defaultValue>
    <description>Discount %, not using standard SF field</description>
    <inlineHelpText>Apply this Discount % (DO NOT input Discount Amount if this is applicable)</inlineHelpText>
    <label>Discount %</label>
    <precision>5</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

unpackaged/main/default/objects/OpportunityLineItem/fields/Discount_Amount__c.field-meta.xml
<CustomField>
    <fullName>Discount_Amount__c</fullName>
    <defaultValue>0</defaultValue>
    <description>This is the discount amount that the sales user will input</description>
    <inlineHelpText>Apply this Discount Amount (DO NOT input Discount % if this is applicable)</inlineHelpText>
    <label>Discount Amt</label>
    <precision>18</precision>
    <scale>3</scale>
    <type>Currency</type>
</CustomField>

unpackaged/main/default/objects/OpportunityLineItem/fields/End_Date__c.field-meta.xml
<CustomField>
    <fullName>End_Date__c</fullName>
    <defaultValue>TODAY()</defaultValue>
    <description>End Date of the contract for the line item. Map to NetSuite SO.</description>
    <label>End Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/OpportunityLineItem/fields/GST_VAT_Code__c.field-meta.xml
<CustomField>
    <fullName>GST_VAT_Code__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Allow sales user to change the tax code of the product line if is different from Product Master</description>
    <inlineHelpText>Select a different tax code if applicable</inlineHelpText>
    <label>GST/VAT Code</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Tax_Code__c.Active__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Tax_Code__c</referenceTo>
    <relationshipLabel>Opportunity Product</relationshipLabel>
    <relationshipName>Opportunity_Product</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/OpportunityLineItem/fields/SNo__c.field-meta.xml
<CustomField>
    <fullName>SNo__c</fullName>
    <description>System generated this number for use of grouping parent and child. Also use when print contract, the order of the products will in ascending order. When users delete the products, the number isn&#39;t reused.</description>
    <label>SNo</label>
    <precision>5</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/OpportunityLineItem/fields/Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Start_Date__c</fullName>
    <defaultValue>TODAY()</defaultValue>
    <description>Start Date of the contract for the line item. Map to NetSuite SO.</description>
    <label>Start Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/Payment__c/Payment__c.object-meta.xml
<CustomObject>
    <label>Payment</label>
    <nameField>
        <displayFormat>PY{0}</displayFormat>
        <label>Payment Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Payments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Payment__c/fields/Amount2__c.field-meta.xml
<CustomField>
    <fullName>Amount2__c</fullName>
    <label>Amount</label>
    <precision>12</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/Payment__c/fields/Appr_Code__c.field-meta.xml
<CustomField>
    <fullName>Appr_Code__c</fullName>
    <description>Denotes the approval code when payment method is Credit Card (KBank)</description>
    <inlineHelpText>Denotes the approval code when payment method is Credit Card (KBank)</inlineHelpText>
    <label>Appr Code</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Payment__c/fields/Opportunity_Record__c.field-meta.xml
<CustomField>
    <fullName>Opportunity_Record__c</fullName>
    <description>Denotes the opportunity record that payment is created for</description>
    <inlineHelpText>Denotes the opportunity record that payment is created for</inlineHelpText>
    <label>Opportunity Record</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Payments</relationshipLabel>
    <relationshipName>Payments</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/Payment__c/fields/Payment_Date__c.field-meta.xml
<CustomField>
    <fullName>Payment_Date__c</fullName>
    <description>Denotes the date when agent has made payment</description>
    <inlineHelpText>Denotes the date when agent has made payment</inlineHelpText>
    <label>Payment Date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/Payment__c/fields/Payment_Gateway__c.field-meta.xml
<CustomField>
    <fullName>Payment_Gateway__c</fullName>
    <description>Denotes the payment gateway that is integrated with PG system</description>
    <inlineHelpText>Denotes the payment gateway that is integrated with PG system</inlineHelpText>
    <label>Payment Gateway</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Adyen</fullName>
            </value>
            <value>
                <fullName>Braintree</fullName>
            </value>
            <value>
                <fullName>PayPal</fullName>
            </value>
            <value>
                <fullName>2c2p</fullName>
            </value>
            <value>
                <fullName>kbank</fullName>
            </value>
            <value>
                <fullName>enets</fullName>
            </value>
            <value>
                <fullName>Apple</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Payment__c/fields/Payment_Method__c.field-meta.xml
<CustomField>
    <fullName>Payment_Method__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Denotes the payment method that is integrated with PG system</description>
    <inlineHelpText>Denotes the payment method that is integrated with PG system</inlineHelpText>
    <label>Payment Method (NS)</label>
    <referenceTo>Payment_Method__c</referenceTo>
    <relationshipLabel>Payments</relationshipLabel>
    <relationshipName>Payments</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Payment__c/fields/Payment_Mode__c.field-meta.xml
<CustomField>
    <fullName>Payment_Mode__c</fullName>
    <description>Denotes the payment mode</description>
    <inlineHelpText>Denotes the payment mode</inlineHelpText>
    <label>Payment Mode</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>bank-transfer</fullName>
            </value>
            <value>
                <fullName>credit-card</fullName>
            </value>
            <value>
                <fullName>installment-plan</fullName>
            </value>
            <value>
                <fullName>Offline</fullName>
            </value>
            <value>
                <fullName>Paypal</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Payment__c/fields/Reference_Number__c.field-meta.xml
<CustomField>
    <fullName>Reference_Number__c</fullName>
    <description>Denotes the unique number generated after successful payment</description>
    <externalId>true</externalId>
    <inlineHelpText>Denotes the unique number generated after successful payment</inlineHelpText>
    <label>Reference Number</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Payment_Method__c/Payment_Method__c.object-meta.xml
<CustomObject>
    <label>Payment Method</label>
    <nameField>
        <label>Payment Method Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Payment Methods</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Product2/fields/NetSuite_Id__c.field-meta.xml
<CustomField>
    <fullName>NetSuite_Id__c</fullName>
    <externalId>true</externalId>
    <label>NetSuite Id</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

unpackaged/main/default/objects/Product2/fields/Tax_Code__c.field-meta.xml
<CustomField>
    <fullName>Tax_Code__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Denotes reference to the tax code</description>
    <inlineHelpText>Denotes reference to the tax code</inlineHelpText>
    <label>Tax Code</label>
    <referenceTo>Tax_Code__c</referenceTo>
    <relationshipLabel>Products</relationshipLabel>
    <relationshipName>Products</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Tax_Code__c/Tax_Code__c.object-meta.xml
<CustomObject>
    <description>This is custom object to store all tax codes and rates.</description>
    <label>Tax Code</label>
    <nameField>
        <label>Tax Code</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Tax Codes</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Tax_Code__c/fields/Country__c.field-meta.xml
<CustomField>
    <fullName>Country__c</fullName>
    <description>Denotes the country of tax code belongs to</description>
    <inlineHelpText>Denotes the country of tax code belongs to</inlineHelpText>
    <label>Country</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Country</valueSetName>
    </valueSet>
</CustomField>

unpackaged/main/default/classes/processorderiOSAPI.cls
@RestResource(urlMapping='/api/processorder/')
global class processorderiOSAPI {
    
    @HttpPost
    global static void upsertOpporunity(){
        Savepoint sp = Database.setSavepoint();    
        RestRequest request = RestContext.request;
        RestResponse res = RestContext.response;
        List<Object> paramsList;
        Map<String,Object> params;
        List<object> items=new List<object> ();
        List<object> payment=new List<object> ();
        List<String> productNSId = new List<String>();
        List<String> nullParams = new List<String>();
        List<OpportunityLineItem> oliList = new list<opportunityLineItem>();
        Map<String,Object> pay;
        Opportunity opp;
        Account acc;
        String accCountry ;
        Set<String> paymentMethodNames = new Set<String>();
        List<Opportunity> OppList =  new List<Opportunity>();
        List<Payment__c> paymentList = new List<Payment__c>();
        Map<String, Id> paymentMap = new Map<String, Id>();
        List<Payment_Method__c> paymentMethodList = new List<Payment_Method__c>();
        try{
            Id devRecordTypeId = Schema.SObjectType.Opportunity.getRecordTypeInfosByName().get('B2C Self-Serve').getRecordTypeId();
            if(request != null && String.isNotBlank(request.requestBody.toString())){
                system.debug('---<<<req>>>--- '+request.requestBody.toString());
              //  paramsList = ( List<Object>)JSON.deserializeUntyped(request.requestBody.toString());
                params = (Map<String,Object>)JSON.deserializeUntyped(request.requestBody.toString());
            } 
            
            
            if(params == null){
                JSONGenerator gen = JSON.createGenerator(true);
                gen.writeStartObject();
                gen.writeStringField('status', 'failure');
                gen.writeStringField('message', 'Params are not present.');
                gen.writeEndObject();
                String jsonData = gen.getAsString();
                res.statusCode = 200;
                res.responseBody =Blob.valueOf(gen.getAsString());
                return; 
            }
            
            
            if(params != null){
                if (params.get('agentKey') == '' || params.get('agentKey') == null){
                    nullParams.add('Agent Key');
                }
                if (params.get('orderNumber') == '' || params.get('orderNumber') == null){
                    nullParams.add('Order Number');
                }
                if (params.get('totalPrice') == '' || params.get('totalPrice') == null){
                    nullParams.add('Total price');
                }
                if (params.get('items') == '' || params.get('items') == null){
                    nullParams.add('Items');
                }else
                { 
                    items = ( List<object> )params.get('items');
                    for(integer i =0; i<items.size();i++){
                        Map<String,Object> item = (Map<String,Object>) items[i];
                        productNSId.add((String)item.get('externalId'));
                        system.debug((String)item.get('productCode'));
                        system.debug((String)item.get('productCode') == '' || (String)item.get('productCode')==null);
                        if((String)item.get('externalId') == '' || (String)item.get('externalId')==null){
                            nullParams.add('externalId');
                        }
                        
                        if((String)item.get('startDate') == '' || (String)item.get('startDate')==null){
                            nullParams.add('Start Date');
                        }
                        if((String)item.get('endDate') == '' || (String)item.get('endDate')==null){
                            nullParams.add('End Date');
                        }
                      
                        if( !item.containsKey('qty')){
                            nullParams.add('Quantity');
                        }
                        
                    }
                }
                if (params.get('payment') == '' || params.get('payment') == null){
                    nullParams.add('Payment Details');
                }else
                {
                    payment = (List<object> )params.get('payment');
                    for(integer i =0; i<payment.size();i++){
                        Map<String,Object> item = (Map<String,Object>) payment[i];
                        system.debug(payment);
                        system.debug(item);
                        if( !item.containsKey('paymentDate') || (String)item.get('paymentDate') == '' || (String)item.get('paymentDate')==null){
                            nullParams.add('Payment Date');
                        }
                        if((String)item.get('paymentGateway ') == '' || (String)item.get('paymentGateway')==null){
                            nullParams.add('Payment Gateway');
                        }
                        if((String)item.get('paymentMode') == '' || (String)item.get('paymentMode')==null){
                            nullParams.add('Payment Mode');
                        }
                        if( (Decimal)item.get('paymentAmount')==null){
                            nullParams.add('Payment Amount');
                        }
                        if((String)item.get('paymentReference') == '' || (String)item.get('paymentReference')==null){
                            nullParams.add('Payment Reference');
                        }
                    }
                }
                
            }
            if(!nullParams.isEmpty()){
                JSONGenerator gen = JSON.createGenerator(true);
                gen.writeStartObject();
                gen.writeStringField('status', 'failure');
                gen.writeStringField('message', String.join(nullParams,', ')+ ' is Empty.');
                gen.writeEndObject();
                String jsonData = gen.getAsString();
                res.statusCode = 200;
                res.responseBody =Blob.valueOf(gen.getAsString());
                return;
                
            }
            pay = (Map<String,Object>) Payment[0];
            //Product2 Product = [SELECT Id, Name FROM Product2 WHERE NetSuite_Id__c =: productNSId];
            String priceBookId;
            Map<String,PricebookEntry> externalIDVsPbe = new  Map<String,PricebookEntry>();
            for(PricebookEntry pbe : [select Id, pricebook2Id, product2Id, Pricebook2.CurrencyIsoCode, 
                                      product2.netsuite_id__c, CurrencyIsoCode, product2.Tax_Code__c 
                                      from pricebookentry where product2.netsuite_id__c in : productNSId 
                                      and Pricebook2.Name!='Standard Price Book' and IsActive=true]){
                                          if(pbe.Pricebook2.CurrencyIsoCode == pbe.CurrencyIsoCode){
                                              priceBookId = pbe.pricebook2Id;
                                              externalIDVsPbe.put(pbe.product2.netsuite_id__c,pbe); 
                                          } 
                                      }
            system.debug('****'+productNSId);
            system.debug(externalIDVsPbe);
            //Product2 primeCred = [SELECT Id, Name FROM Product2 WHERE name = 'PGSG Prime Credit' limit 1];
            //  PriceBook2 priceBook = [SELECT Id, Name FROM PriceBook2 WHERE name = 'PG SG' LIMIT 1]; 
            //  PricebookEntry ProdEntry = [SELECT  Id, Name FROM PricebookEntry WHERE Product2Id =: Product.Id and pricebook2Id =: priceBook.Id LIMIT 1];
            //PricebookEntry primeCredEntry = [SELECT  Id, Name FROM PricebookEntry WHERE Product2Id =: primeCred.Id and pricebook2Id =: priceBook.Id LIMIT 1];
            
            String agentKey = (String) params.get('agentKey');
            acc = [select id,ownerid,country__c,agentKey__c from Account where AgentKey__c = :agentKey];
            accCountry = acc.country__c;
            opp = new Opportunity();
            opp.ownerID	= acc.OwnerID;
            opp.AccountID = acc.id;
            opp.Name = acc.AgentKey__c +' Purchased '+(String) params.get('orderNumber') +' @ $'+(Decimal) pay.get('paymentAmount');
            opp.stageName = 'Converted';
            opp.CloseDate = system.today();
            opp.Invoice_Id__c = (String) params.get('orderNumber');
            opp.Opportunity_Type__c = 'Self-Serve Standard';
            opp.Order_Date__c = date.valueOf((String)pay.get('paymentDate'));
            opp.recordtypeid = devRecordTypeId;
            opp.pricebook2id = priceBookId;
            opp.Sync_To_NetSuite__c = true;	
            insert opp;
            paymentMethodList = [Select id, name from Payment_Method__c];
            for(Payment_Method__c p : paymentMethodList){
                paymentMap.put(p.Name, p.Id);
            }
            if(pay.get('paymentAmount')!=0){
                Payment__c oPayment = new Payment__c();
                oPayment.Opportunity_Record__c = opp.Id;
                oPayment.Amount2__c =  (Decimal) pay.get('paymentAmount');
                oPayment.Appr_Code__c = (String)  pay.get('apprCode');
                oPayment.Payment_Date__c = date.valueOf((String)pay.get('paymentDate'));
                oPayment.Payment_Gateway__c = (String) pay.get('paymentGateway');
                oPayment.Reference_Number__c = (String) pay.get('paymentReference');
                if((String) pay.get('paymentGateway') == 'Adyen'){
                    if(accCountry == 'Singapore' && paymentMap.containsKey('Adyen (SG)')){
                        oPayment.Payment_Method__c = paymentMap.get('Adyen (SG)');
                    }else if(accCountry == 'Malaysia' && paymentMap.containsKey('Adyen (MY)')){
                        oPayment.Payment_Method__c = paymentMap.get('Adyen (MY)');
                    }else if(accCountry == 'Indonesia' && paymentMap.containsKey('Adyen (ID)')){
                        oPayment.Payment_Method__c = paymentMap.get('Adyen (ID)');
                    }else if(accCountry == 'Thailand' && paymentMap.containsKey('Adyen (TH)')){
                        oPayment.Payment_Method__c = paymentMap.get('Adyen (TH)');
                    }
                }
                if((String) pay.get('paymentGateway') == 'Braintree' && paymentMap.containsKey('Braintree')){
                    oPayment.Payment_Method__c = paymentMap.get('Braintree');
                }
                if((String) pay.get('paymentGateway') == 'Paypal' && paymentMap.containsKey('Paypal')){
                    oPayment.Payment_Method__c = paymentMap.get('Paypal');
                }
                if((String) pay.get('paymentGateway') == '2c2p') {
                    if (((String) pay.get('BankName')).contains('UOB') && (Decimal) pay.get('installmentPeriod') == 6) {
                        oPayment.Payment_Method__c = paymentMap.get('UOB 6 Month Installment_Online');
                    } else if (((String) pay.get('BankName')).contains('UOB') && (Decimal) pay.get('installmentPeriod')== 12) {
                        oPayment.Payment_Method__c = paymentMap.get('UOB 12 Month Installment_Online');
                    }
                }
                if((String) pay.get('paymentGateway') == 'enets') {
                    if (((String) pay.get('BankName')).contains('DBS') &&(Decimal) pay.get('installmentPeriod') == 6) {
                        oPayment.Payment_Method__c = paymentMap.get('DBS 6 Month Installment');
                    } else if (((String) pay.get('BankName')).contains('DBS') && (Decimal) pay.get('installmentPeriod') == 12) {
                        oPayment.Payment_Method__c = paymentMap.get('DBS 12 Month Installment');
                    }
                }
                if((String) pay.get('paymentGateway') == 'Apple'){
                    oPayment.Payment_Method__c = paymentMap.get('Apple');
                }
                oPayment.Payment_Mode__c = (String) pay.get('paymentMode');
                paymentList.add(oPayment);    
            }
            insert paymentList;
            Integer count =1;
            for(integer i =0; i<items.size();i++){
                Map<String,Object> item = (Map<String,Object>) items[i];
                OpportunityLineItem oli = new OpportunityLineItem();
                if(externalIDVsPbe.containsKey((String)item.get('externalId'))){
                   
                    oli.Product2Id =  externalIDVsPbe.get((String)item.get('externalId')).Product2Id;
                    oli.PricebookEntryId =  externalIDVsPbe.get((String)item.get('externalId')).Id;
                }
               
                oli.OpportunityID = opp.id;
                oli.UnitPrice  = (Decimal) item.get('unitPrice');
                oli.Quantity  =(Decimal)  item.get('qty');
                if(item.containsKey('discountType')){
                    if(item.get('discountType') == 'Amount'){
                        oli.Discount_Amount__c  = (Decimal)item.get('discount');
                    } else if(item.get('discountType') =='Percent'){
                        oli.Discount__c = (Decimal)item.get('discount');
                    }
                }
                oli.Start_Date__c  = date.valueOf((String)item.get('startDate'));
                oli.End_Date__c = date.valueOf((String)item.get('endDate'));
                oli.SNo__c = count;
                count++;
                if(Label.Allow_Tax_Code_for_GST_SS  == 'Yes')
                    oli.GST_VAT_Code__c = externalIDVsPbe.get((String)item.get('externalId')).product2.Tax_Code__c ;
                OliList.add(oli);
            }
            
            insert oliList;
            JSONGenerator gen = JSON.createGenerator(true);
            gen.writeStartObject();
            gen.writeStringField('status', 'Success');
            gen.writeStringField('message', 'Opportunity, Line Items and payment is created');
            gen.writeEndObject();
            String jsonData = gen.getAsString();
            res.statusCode = 200;
            res.responseBody =Blob.valueOf(gen.getAsString());
            return;
            
        }
        catch(Exception e){
            Database.rollback(sp);
            system.debug('Error ::: at line '+e.getLineNumber()+' -- '+e.getMessage());
            JSONGenerator gen = JSON.createGenerator(true);
            gen.writeStartObject();
            gen.writeStringField('status', 'failure');
            gen.writeStringField('message', 'Error ::: at line '+e.getLineNumber()+' -- '+e.getMessage());
            gen.writeEndObject();
            String jsonData = gen.getAsString();
            res.statusCode = 200;
            res.responseBody =Blob.valueOf(gen.getAsString());
            return; 
        }
    }
}