unpackaged/main/default/objects/Account/fields/AgentNet_ID__c.field-meta.xml
<CustomField>
    <fullName>AgentNet_ID__c</fullName>
    <description>Denotes a numeric id of agents in PG system</description>
    <inlineHelpText>Denotes a numeric id of agents in PG system</inlineHelpText>
    <label>AgentNet ID</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/Country__c.field-meta.xml
<CustomField>
    <fullName>Country__c</fullName>
    <defaultValue>if(  BEGINS($UserRole.Name, &quot;TH&quot;),&quot;Thailand&quot;,if(ISPICKVAL($User.Subsidiary__c,&quot;MyProperty Data Sdn. Bhd.&quot;),&quot;Malaysia&quot;,&quot;&quot;))</defaultValue>
    <description>Denotes the country of an account</description>
    <inlineHelpText>Denotes the country of an account</inlineHelpText>
    <label>Country</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Country</valueSetName>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Account/fields/NetSuite_Id__c.field-meta.xml
<CustomField>
    <fullName>NetSuite_Id__c</fullName>
    <externalId>true</externalId>
    <label>NetSuite Id</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Country__c.field-meta.xml
<CustomField>
    <fullName>Country__c</fullName>
    <formula>TEXT(Subsidiary__r.Country__c )</formula>
    <label>Country</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Guruland_Quote_Link__c.field-meta.xml
<CustomField>
    <fullName>Guruland_Quote_Link__c</fullName>
    <label>Payment Link</label>
    <type>Url</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Opportunity_Number__c.field-meta.xml
<CustomField>
    <fullName>Opportunity_Number__c</fullName>
    <displayFormat>PGSO-{YY}{000000}</displayFormat>
    <label>Opportunity Number</label>
    <type>AutoNumber</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Opportunity_Type__c.field-meta.xml
<CustomField>
    <fullName>Opportunity_Type__c</fullName>
    <defaultValue>IF( $RecordType.DeveloperName = &#39;B2C&#39; , &#39;B2C - Standard&#39;, null)</defaultValue>
    <label>Opportunity Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>B2C - Standard</fullName>
            </value>
            <value>
                <fullName>B2C - Upgrade</fullName>
            </value>
            <value>
                <fullName>B2C - Renewal</fullName>
            </value>
            <value>
                <fullName>Self-Serve Standard</fullName>
            </value>
            <value>
                <fullName>Self-Serve Renewal</fullName>
            </value>
            <value>
                <fullName>Self-Serve Abandoned</fullName>
            </value>
            <value>
                <fullName>Marketing Automation</fullName>
            </value>
            <value>
                <fullName>B2C - Conversion</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Order_Type_Clone__c.field-meta.xml
<CustomField>
    <fullName>Order_Type_Clone__c</fullName>
    <label>Order Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Contract - New</fullName>
            </value>
            <value>
                <fullName>Contract - Upsell</fullName>
            </value>
            <value>
                <fullName>Contract - Renewal</fullName>
            </value>
            <value>
                <fullName>Contract - Make Good</fullName>
            </value>
            <value>
                <fullName>Dual-SO</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Total_Amount__c.field-meta.xml
<CustomField>
    <fullName>Total_Amount__c</fullName>
    <description>Sum up product line amount after discount before tax</description>
    <inlineHelpText>(Sales Price * Qty) - Discount - Complimentary</inlineHelpText>
    <label>Total Amount (after Discount)</label>
    <summarizedField>OpportunityLineItem.Amount__c</summarizedField>
    <summaryForeignKey>OpportunityLineItem.OpportunityId</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Total_Discounted_Amount__c.field-meta.xml
<CustomField>
    <fullName>Total_Discounted_Amount__c</fullName>
    <label>Total Discounted Amount</label>
    <summarizedField>OpportunityLineItem.Discounted_Amount__c</summarizedField>
    <summaryForeignKey>OpportunityLineItem.OpportunityId</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Total_Gross_Amount__c.field-meta.xml
<CustomField>
    <fullName>Total_Gross_Amount__c</fullName>
    <inlineHelpText>Total Amount after discount &amp; tax</inlineHelpText>
    <label>Total Gross Amount</label>
    <summarizedField>OpportunityLineItem.Gross_Amount__c</summarizedField>
    <summaryForeignKey>OpportunityLineItem.OpportunityId</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Total_Tax_Amount__c.field-meta.xml
<CustomField>
    <fullName>Total_Tax_Amount__c</fullName>
    <label>Total Tax Amount</label>
    <summarizedField>OpportunityLineItem.Tax_Amount__c</summarizedField>
    <summaryForeignKey>OpportunityLineItem.OpportunityId</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/recordTypes/B2B.recordType-meta.xml
<RecordType>
    <fullName>B2B</fullName>
    <active>true</active>
    <businessProcess>B2B</businessProcess>
    <description>B2B Opportunity Record</description>
    <label>B2B</label>
</RecordType>

unpackaged/main/default/objects/Opportunity/recordTypes/B2C.recordType-meta.xml
<RecordType>
    <fullName>B2C</fullName>
    <active>true</active>
    <businessProcess>B2C</businessProcess>
    <description>B2C Opportunity Record</description>
    <label>B2C</label>
</RecordType>

unpackaged/main/default/objects/OpportunityLineItem/fields/Actual_Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Actual_Start_Date__c</fullName>
    <formula>if( Start_Date__c &gt;  DATEVALUE(Opportunity.OMC_Approved_Date__c) ,Start_Date__c,DATEVALUE(Opportunity.OMC_Approved_Date__c))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Actual Start Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/OpportunityLineItem/fields/Amount__c.field-meta.xml
<CustomField>
    <fullName>Amount__c</fullName>
    <description>Amount after discount before tax (Sales Price * Qty - Discount), exclude complimentary</description>
    <formula>IF( Complimentary__c = TRUE, IF(Record_Type__c=&quot;B2C&quot;, (UnitPrice *  Quantity) - TotalPrice, (UnitPrice *  Quantity) - Discounted_Amount__c -  TotalPrice) , IF(Record_Type__c=&quot;B2C&quot;, (UnitPrice *  Quantity) - Discounted_Amount__c - Pro_Rate_Amount__c, (UnitPrice *  Quantity) - Discounted_Amount__c))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>(Sales Price * Qty - Discount) - Complimentary, before Tax</inlineHelpText>
    <label>Price after discount</label>
    <precision>18</precision>
    <scale>3</scale>
    <type>Currency</type>
</CustomField>

unpackaged/main/default/objects/OpportunityLineItem/fields/Amount_Despite_VIP__c.field-meta.xml
<CustomField>
    <fullName>Amount_Despite_VIP__c</fullName>
    <label>Amount Despite VIP</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/OpportunityLineItem/fields/Discount_Amount__c.field-meta.xml
<CustomField>
    <fullName>Discount_Amount__c</fullName>
    <defaultValue>0</defaultValue>
    <description>This is the discount amount that the sales user will input</description>
    <inlineHelpText>Apply this Discount Amount (DO NOT input Discount % if this is applicable)</inlineHelpText>
    <label>Discount Amt</label>
    <precision>18</precision>
    <scale>3</scale>
    <type>Currency</type>
</CustomField>

unpackaged/main/default/objects/OpportunityLineItem/fields/End_Date__c.field-meta.xml
<CustomField>
    <fullName>End_Date__c</fullName>
    <defaultValue>TODAY()</defaultValue>
    <description>End Date of the contract for the line item. Map to NetSuite SO.</description>
    <label>End Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/OpportunityLineItem/fields/Gross_Amount__c.field-meta.xml
<CustomField>
    <fullName>Gross_Amount__c</fullName>
    <formula>Amount__c+( Amount__c *  GST_VAT_Rate__c )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>Total Price after discount and tax</inlineHelpText>
    <label>Gross Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

unpackaged/main/default/objects/OpportunityLineItem/fields/PO__c.field-meta.xml
<CustomField>
    <fullName>PO__c</fullName>
    <defaultValue>true</defaultValue>
    <description>Send to PO API when it&#39;s checked</description>
    <inlineHelpText>Send to PO API when it&#39;s checked</inlineHelpText>
    <label>Auto-Activation</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/OpportunityLineItem/fields/SNo__c.field-meta.xml
<CustomField>
    <fullName>SNo__c</fullName>
    <description>System generated this number for use of grouping parent and child. Also use when print contract, the order of the products will in ascending order. When users delete the products, the number isn&#39;t reused.</description>
    <label>SNo</label>
    <precision>5</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/OpportunityLineItem/fields/Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Start_Date__c</fullName>
    <defaultValue>TODAY()</defaultValue>
    <description>Start Date of the contract for the line item. Map to NetSuite SO.</description>
    <label>Start Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/OpportunityLineItem/fields/Tax_Amount__c.field-meta.xml
<CustomField>
    <fullName>Tax_Amount__c</fullName>
    <formula>Amount__c  *   GST_VAT_Rate__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>Tax amount (Price after discount * tax rate)</inlineHelpText>
    <label>Tax Amount</label>
    <precision>18</precision>
    <scale>3</scale>
    <type>Currency</type>
</CustomField>

unpackaged/main/default/objects/Product2/fields/CustItem_Duration_Unit__c.field-meta.xml
<CustomField>
    <fullName>CustItem_Duration_Unit__c</fullName>
    <description>Denotes the unit in which the duration of product is expressed</description>
    <inlineHelpText>Denotes the unit in which the duration of product is expressed</inlineHelpText>
    <label>CustItem Duration Unit</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Weeks</fullName>
            </value>
            <value>
                <fullName>Months</fullName>
            </value>
            <value>
                <fullName>Years</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Product2/fields/CustItem_Duration_Value__c.field-meta.xml
<CustomField>
    <fullName>CustItem_Duration_Value__c</fullName>
    <description>Denotes the value of product duration</description>
    <inlineHelpText>Denotes the value of product duration</inlineHelpText>
    <label>CustItem Duration Value</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/Product2/fields/CustItem_Validity_Unit__c.field-meta.xml
<CustomField>
    <fullName>CustItem_Validity_Unit__c</fullName>
    <description>Denotes the unit of product validity</description>
    <inlineHelpText>Denotes the unit of product validity</inlineHelpText>
    <label>CustItem Validity Unit</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Weeks</fullName>
            </value>
            <value>
                <fullName>Months</fullName>
            </value>
            <value>
                <fullName>Years</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Product2/fields/CustItem_Validity_Value__c.field-meta.xml
<CustomField>
    <fullName>CustItem_Validity_Value__c</fullName>
    <description>Denotes the value of product validity</description>
    <inlineHelpText>Denotes the value of product validity</inlineHelpText>
    <label>CustItem Validity Value</label>
    <precision>16</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/Product2/fields/NetSuite_Id__c.field-meta.xml
<CustomField>
    <fullName>NetSuite_Id__c</fullName>
    <externalId>true</externalId>
    <label>NetSuite Id</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

unpackaged/main/default/objects/Product2/fields/Product_Function__c.field-meta.xml
<CustomField>
    <fullName>Product_Function__c</fullName>
    <label>Product Function</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/classes/OpportunityOrderAPI.cls
/*------------------------------------------------------------
Author      : Steven Junaidy
Company     : Viseo Asia PTE LTD
Description : Opportunity Order Endpoint
Inputs      :
<Date>      <Authors Name>     <Brief Description of Change>
------------------------------------------------------------*/
@RestResource(urlMapping='/api/order/*')
global class OpportunityOrderAPI {

    /*------------------------------------------------------------
Author      : Steven Junaidy
Company     : Viseo Asia PTE LTD
Description : Wrapper class to map salesforce opportunity fields into order PurchasedProducts fields.
<Date>      <Authors Name>     <Brief Description of Change>
------------------------------------------------------------*/
    global class PurchasedProducts {
        String internalId;              String autoActivate;              String externalProductId;
        integer salesPersonId;          String validityPeriod;
        String chargeCurrency;          String durationPeriod;            String startDate;
        String chargeValue;             String statusCode;                String expiryDate;
        String netAmount;               Integer createdBy;                String parent;
        String quantity;                String standardProduct;           String parentInternalId;
        list<purchasedProductFunctions> purchasedProductFunctions;

        PurchasedProducts   (String internalId,String autoActivate,String externalProductId,integer salesPersonId,String validityPeriod,
                             String chargeCurrency,String durationPeriod,String startDate,String chargeValue,String statusCode,String expiryDate,String netAmount,
                             Integer createdBy, String parent, String quantity, String standardProduct,String parentInternalId,list<purchasedProductFunctions> ppf){

                                 This.internalId = internalId;              This.parentInternalId = parentInternalId;       This.externalProductId = externalProductId;
                                 This.salesPersonId = salesPersonId;        This.validityPeriod = validityPeriod;           This.chargeCurrency = chargeCurrency.toUpperCase();
                                 This.durationPeriod = durationPeriod;      This.startDate = startDate + ' 00:00:00';       This.autoActivate = autoActivate.substring(0,1).toUpperCase();
                                 This.chargeValue = chargeValue;            This.statusCode = statusCode;                   This.expiryDate = expiryDate + ' 00:00:00';
                                 This.netAmount = netAmount;                This.createdBy = createdBy;                     This.parent = parent;
                                 This.quantity = quantity;                  This.standardProduct = standardProduct;
                                 this.purchasedProductFunctions = ppf;
                             }
    }
    /*------------------------------------------------------------
Author      : Steven Junaidy
Company     : Viseo Asia PTE LTD
Description : Wrapper class to map salesforce opportunity fields into order Dataflow fields.
<Date>      <Authors Name>     <Brief Description of Change>
------------------------------------------------------------*/
    global class Data_Flow {
        String totalAmount;             integer webuserId;             Integer createdBy;
        String invoiceId;               integer billingSourceId;       String source;
        String purchasedDate;           String externalId;             list<purchasedProducts> purchasedProducts;

        Data_Flow(  Decimal totalAmount,string webuserId,integer createdBy,id invoiceId,integer billingSourceId,String source,
                  String purchasedDate,string externalId,  list<purchasedProducts> pp){

                      This.totalAmount = String.Valueof(totalAmount);                   This.webuserId = Integer.valueOf(webuserId);    This.createdBy = createdBy;
                      This.invoiceId = invoiceId;                                       This.billingSourceId = billingSourceId;         This.source = source;
                      This.externalId = String.Valueof(externalId);                     this.purchasedProducts = pp;
                      This.purchasedDate = purchasedDate;
                  }
    }
    /*------------------------------------------------------------
Author      : Steven Junaidy
Company     : Viseo Asia PTE LTD
Description : Wrapper class to map salesforce opportunity fields into order PurchasedProductFunctions fields.
<Date>      <Authors Name>     <Brief Description of Change>
------------------------------------------------------------*/
    global class PurchasedProductFunctions{
        String code; String value = '0';
        PurchasedProductFunctions(string code){
            this.code = code;
        }
    }
    /*------------------------------------------------------------
Author      : Steven Junaidy
Company     : Viseo Asia PTE LTD
Description : GET Method, send requested salesforce opportunity data to Property Guru
Inputs      : Salesforce Opportunity Id and Hash_64 from Guruland response
History
<Date>      <Authors Name>     <Brief Description of Change>
------------------------------------------------------------*/
    @HttpGet
    global static void getOpportunity() {
        String OppID = RestContext.request.params.get('id');    String result;      String internalID='';
        String Parentid;                                        Date startDate;     Date dueDate;
        Integer numberDaysDue;                                  String comma ;      String SNo_c;
        String Sno;                                             Date actualEndDate;
        RestResponse res = RestContext.response;
        String oppQuoteNum;
        system.debug(OppID +'  OppID ');
        list<Opportunity> Opportunitiess = new list<Opportunity>( [SELECT id,name, Account.BillingCountry ,Account.BillingPostalCode,Account.BillingState,Account.BillingCity,
                                                                   Account.BillingStreet, Account.AgentNet_ID__c, CurrencyIsoCode,Total_Gross_Amount__c,Order_Date__c,
                                                                   StageName,Amount, Total_Tax_Amount__c, Total_Discounted_Amount__c, ownerid, createdby.name, Account.name,
                                                                   Account.personEmail, owner.name, Opportunity_Number__c,Guruland_Quote_Link__c, owner.Webuser_ID__c,
                                                                   Country__c, Total_Amount__c,
                                                                   (SELECT Id,Opp_Quote_Ref_num__c from Quotes WHERE isSyncing =true limit 1)
                                                                   FROM Opportunity  WHERE Id =: OppID LIMIT 1]);
        if(Opportunitiess.size()>0){
            String ValidityPeriod;
            String DurationPeriod;
            String Standard_Product='';
            Opportunity Opportunities = new Opportunity();
            Opportunities = Opportunitiess.get(0);
             //PGAUTO-2694
             if(Opportunities.quotes.size()>0){
            oppQuoteNum=Opportunities.quotes[0].Opp_Quote_Ref_num__c;
             }
             else{
             oppQuoteNum=Opportunities.Opportunity_Number__c;
             }
            list<OpportunityLineItem> Opl = new list<OpportunityLineItem>([SELECT SNo__c,Product2.name,product2.product_function__c,product2.description, quantity, Unitprice,
                                                                           Discount_Amount__c,tax_amount__c, Createdby.name,Product2.NetSuite_Id__c,
                                                                           Opportunity.OwnerID,Opportunity.CurrencyIsoCode,Gross_Amount__C, Start_date__c, End_date__c,PO__c,
                                                                           Product2.CustItem_Validity_Value__c, Product2.CustItem_Validity_Unit__c, Product2.CustItem_Duration_Value__c,
                                                                           Product2.CustItem_Duration_Unit__c,opportunity.Opportunity_Number__c,Actual_Start_Date__c,
                                                                           opportunity.owner.Webuser_ID__c, Opportunity.Order_Type_Clone__c,Opportunity.Opportunity_Type__c,
                                                                           Opportunity.Country__c, Opportunity.RecordTypeId, Amount_Despite_VIP__c, Amount__c
                                                                           FROM OpportunityLineItem WHERE OpportunityID =: OppID ]);

            List<purchasedProducts> pP = new List<purchasedProducts>();
            //Matching Salesforce fields with Guruland fields format
            for (OpportunityLineItem opp : Opl){
                String internalIdForLineItems = oppQuoteNum;
                system.debug('opp.Actual_Start_Date__c ' +opp.Actual_Start_Date__c );
                if(opp.Opportunity.RecordTypeId == '0127F000000K50eQAC'){
                    //If b2c
                    //if not project x
                    startDate = opp.Actual_Start_Date__c;
                    if((opp.Opportunity.Order_Type_Clone__c  == 'Contract - Upgrade' || opp.Opportunity.Opportunity_Type__c == 'B2C - Upgrade') && opp.Opportunity.country__c == 'Malaysia') {
                        //if MY upgrade
                        actualEndDate = opp.End_Date__c;
                    } else {
                        //for other b2c cases
                        actualEndDate = opp.Start_Date__c == opp.Actual_Start_Date__c ? opp.End_Date__c : opp.Actual_Start_Date__c.addDays(opp.Start_Date__c.daysBetween(opp.End_Date__c));
                    }

                }
                else{
                    //b2b
                    startDate = opp.Start_Date__c;
                    actualEndDate = opp.End_Date__c;
                }
                ValidityPeriod = opp.Product2.CustItem_Validity_Value__c + ' ' +  opp.Product2.CustItem_Validity_Unit__c;
                DurationPeriod =  opp.Product2.CustItem_Duration_Value__c + ' ' + opp.Product2.CustItem_Duration_Unit__c;


                if(opp.SNo__c <> null){
                    SNo = string.valueof(opp.SNo__c);
                    comma = Sno.substring(Sno.length()-2, Sno.length());
                    if( comma == '00'){
                        internalID = internalIdForLineItems + '_' + Sno.substring(0,Sno.length()-3);
                        ParentID = internalID;
                        Standard_Product = '1';
                    }else{
                        SNo_c = string.valueof(opp.SNo__c);
                        Standard_Product = '0';
                        if(comma.substring(0,1) == '0'){
                            internalID = internalIdForLineItems + '_' + Sno.substring(0,1) + '_' + comma.substring(1,comma.length()) ;

                        }else{
                            internalID = internalIdForLineItems + '_' + String.valueOf(opp.SNo__c).replace('.', '_');
                        }
                        OpportunityLineItem OppLine = new OpportunityLineItem();
                        OppLine = [SELECT id,opportunityid, Opportunity.Opportunity_Number__c
                                   FROM OpportunityLineItem
                                   WHERE opportunityid =: OppID and Sno__c =: Decimal.valueOF(Sno_c.substring(0,1) + '.00')];
                        parentid = oppQuoteNum + '_' + Sno_c.substring(0,Sno_c.length()-3);
                    }
                }
                list<purchasedProductFunctions> ppp = new list<purchasedProductFunctions>();
                if(opp.product2.product_function__c <> null){
                    purchasedProductFunctions pf = new  PurchasedProductFunctions(opp.product2.product_function__c);
                    ppp.add(pf);
                }

                //added for PGAUTO-6980 (gst implemetation)
                Decimal decNetAmount = opp.Gross_Amount__c;
                if(String.isNotBlank(Opportunities.Country__c) && Opportunities.Country__c.equals('Singapore')) {
                    decNetAmount = opp.Amount__c;
                }

                purchasedProducts prod = new purchasedProducts( internalID,string.valueof(opp.PO__c), opp.Product2.NetSuite_Id__c,
                                                               integer.valueOf(opp.opportunity.owner.Webuser_ID__c), ValidityPeriod, opp.Opportunity.CurrencyIsoCode,DurationPeriod,
                                                               string.valueof(startDate), string.valueof(opp.UnitPrice), 'ACTIVE', string.valueof(actualEndDate),
                                                               string.valueof(decNetAmount), integer.valueOf(opp.opportunity.owner.Webuser_ID__c),
                                                               opp.Product2.NetSuite_Id__c, string.valueof(opp.quantity), Standard_Product, parentid, ppp) ;
                pP.add(prod);
            }

            //added for PGAUTO-6980 (gst implemetation)
            Decimal decTotalAmount = Opportunities.Total_Gross_Amount__c;
            if(String.isNotBlank(Opportunities.Country__c) && Opportunities.Country__c.equals('Singapore')) {
                decTotalAmount = Opportunities.Total_Amount__c;
            }
            Data_Flow df = new Data_Flow(decTotalAmount, Opportunities.Account.AgentNet_id__c, integer.valueOf(Opportunities.owner.Webuser_ID__c), Opportunities.id, 3,
                                         'offline', String.Valueof(system.now()), (oppQuoteNum), pp);
            if (df <> null){
                res.statusCode = 200;
                result =   system.JSON.serialize(df);
                res.responseBody = blob.valueOf(result);
                system.debug('OrderAPI Response' + result );
            }
        }else{
            res.statusCode = 400;
            result =  'Opportunity requested by Guruland does not exist in Salesforce.';
            res.responseBody = blob.valueOf(result);
        }

    }
}