unpackaged/main/default/objects/Account/fields/AgentNet_ID__c.field-meta.xml
<CustomField>
    <fullName>AgentNet_ID__c</fullName>
    <description>Denotes a numeric id of agents in PG system</description>
    <inlineHelpText>Denotes a numeric id of agents in PG system</inlineHelpText>
    <label>AgentNet ID</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/Billing_email__c.field-meta.xml
<CustomField>
    <fullName>Billing_email__c</fullName>
    <inlineHelpText>The invoice will be sent to this address</inlineHelpText>
    <label>Billing email</label>
    <type>Email</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/Corporate_Brand_Name__c.field-meta.xml
<CustomField>
    <fullName>Corporate_Brand_Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>This is the main brand of this advertiser. Volvo Corporation AB would probably have Volvo as the brand name.</inlineHelpText>
    <label>Corporate Brand Name</label>
    <referenceTo>Corporate_Brand_Name__c</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/Industry_Tier_2__c.field-meta.xml
<CustomField>
    <fullName>Industry_Tier_2__c</fullName>
    <description>Tier 2 (Lower) Industry Catagories</description>
    <label>Industry (Tier 2)</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Industry</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>Adult Beverages</fullName>
            </value>
            <value>
                <fullName>Alcoholic Beverages</fullName>
            </value>
            <value>
                <fullName>Appliances</fullName>
            </value>
            <value>
                <fullName>Artist/Band</fullName>
            </value>
            <value>
                <fullName>Automotive</fullName>
            </value>
            <value>
                <fullName>Auto Parts Retailers</fullName>
            </value>
            <value>
                <fullName>Banking</fullName>
            </value>
            <value>
                <fullName>Banks</fullName>
            </value>
            <value>
                <fullName>Big Box Retail</fullName>
            </value>
            <value>
                <fullName>Big-Box Retail</fullName>
            </value>
            <value>
                <fullName>Brands/OEM</fullName>
            </value>
            <value>
                <fullName>Chemicals</fullName>
            </value>
            <value>
                <fullName>Commercial Vechicles</fullName>
            </value>
            <value>
                <fullName>Commercial Vehicles</fullName>
            </value>
            <value>
                <fullName>Concert</fullName>
            </value>
            <value>
                <fullName>Consumer Electronics</fullName>
            </value>
            <value>
                <fullName>Consumer Electronics/Computing Products</fullName>
            </value>
            <value>
                <fullName>Creative Agency</fullName>
            </value>
            <value>
                <fullName>Credit Cards</fullName>
            </value>
            <value>
                <fullName>Dealerships</fullName>
            </value>
            <value>
                <fullName>Dealerships/LMAs</fullName>
            </value>
            <value>
                <fullName>Digital Media</fullName>
            </value>
            <value>
                <fullName>eCommerce</fullName>
            </value>
            <value>
                <fullName>E-Commerce</fullName>
            </value>
            <value>
                <fullName>Education</fullName>
            </value>
            <value>
                <fullName>Fashion/Apparel</fullName>
            </value>
            <value>
                <fullName>Fashon/Apparel</fullName>
            </value>
            <value>
                <fullName>Festival</fullName>
            </value>
            <value>
                <fullName>Festivals</fullName>
                <label>Festivals/Concerts</label>
            </value>
            <value>
                <fullName>Film</fullName>
            </value>
            <value>
                <fullName>Media Agency</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Account/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>Denotes the status of an agent in the agent lifecycle</description>
    <inlineHelpText>Denotes the status of an agent in the agent lifecycle</inlineHelpText>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Trial</fullName>
            </value>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Downgraded</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Suspended</fullName>
            </value>
            <value>
                <fullName>Expired</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Account/recordTypes/Agency.recordType-meta.xml
<RecordType>
    <fullName>Agency</fullName>
    <active>true</active>
    <label>Agency</label>
</RecordType>

unpackaged/main/default/objects/Corporate_Brand_Name__c/Corporate_Brand_Name__c.object-meta.xml
<CustomObject>
    <label>Corporate Brand Name</label>
    <nameField>
        <label>Corporate Brand Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Corporate Brand Names</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Corporate_Brand_Name__c/fields/Global_Customer_Segment__c.field-meta.xml
<CustomField>
    <fullName>Global_Customer_Segment__c</fullName>
    <label>Demand Channel</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Advertiser</fullName>
            </value>
            <value>
                <fullName>Agency</fullName>
            </value>
            <value>
                <fullName>Reseller</fullName>
            </value>
            <value>
                <fullName>Label</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Appr_Code__c.field-meta.xml
<CustomField>
    <fullName>Appr_Code__c</fullName>
    <label>Appr Code</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Billing_Email__c.field-meta.xml
<CustomField>
    <fullName>Billing_Email__c</fullName>
    <description>Billing Email pulled from Account.</description>
    <formula>IF(ISBLANK(Account.Billing_email__c), &#39;notused@propertyguru.com&#39;, Account.Billing_email__c)</formula>
    <inlineHelpText>Billing Email pulled from Account.</inlineHelpText>
    <label>Billing Email</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Payment_Amount__c.field-meta.xml
<CustomField>
    <fullName>Payment_Amount__c</fullName>
    <label>Payment Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Payment_Gateway__c.field-meta.xml
<CustomField>
    <fullName>Payment_Gateway__c</fullName>
    <label>Payment Gateway</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Adyen</fullName>
            </value>
            <value>
                <fullName>Braintree</fullName>
            </value>
            <value>
                <fullName>PayPal</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Payment_Reference__c.field-meta.xml
<CustomField>
    <fullName>Payment_Reference__c</fullName>
    <label>Payment Reference</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Payment_Term__c.field-meta.xml
<CustomField>
    <fullName>Payment_Term__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Lookup to custom object, Payment Term</description>
    <label>Payment Term</label>
    <referenceTo>Payment_Term__c</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Primary_Sales_Order__c.field-meta.xml
<CustomField>
    <fullName>Primary_Sales_Order__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Primary Sales Order linked to this Opportunity</description>
    <inlineHelpText>Primary Sales Order linked to this Opportunity</inlineHelpText>
    <label>Primary Sales Order</label>
    <referenceTo>csmso__Sales_Order__c</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/recordTypes/B2B.recordType-meta.xml
<RecordType>
    <fullName>B2B</fullName>
    <active>true</active>
    <businessProcess>B2B</businessProcess>
    <description>B2B Opportunity Record</description>
    <label>B2B</label>
</RecordType>

unpackaged/main/default/objects/Payment_Term__c/Payment_Term__c.object-meta.xml
<CustomObject>
    <description>This is to store the various payment terms for Oppty</description>
    <label>Payment Term</label>
    <nameField>
        <label>Payment Term Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Payment Terms</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Payment_Term__c/fields/NS_Payment_Term_ID__c.field-meta.xml
<CustomField>
    <fullName>NS_Payment_Term_ID__c</fullName>
    <description>Denotes the unique external id that is integrated with netsuite system</description>
    <externalId>true</externalId>
    <inlineHelpText>Denotes the unique external id that is integrated with netsuite system</inlineHelpText>
    <label>NS Payment Term ID</label>
    <precision>10</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
    <unique>true</unique>
</CustomField>

unpackaged/main/default/objects/QliToOliFieldMapping__c/QliToOliFieldMapping__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>This custom setting is user for mapping Quote line item&#39;s fields to Opportunity Line Item when status of Quote is Accepted. Use Name as Quote lint item&#39;s fields API and oliField__c for Opportuntiy line item&#39;s fields API.</description>
    <label>QliToOliFieldMapping</label>
</CustomObject>

unpackaged/main/default/objects/QliToOliFieldMapping__c/fields/OliField__c.field-meta.xml
<CustomField>
    <fullName>OliField__c</fullName>
    <label>OliField</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/classes/SOPaymentTermRestrictionTest.cls
@isTest
public class SOPaymentTermRestrictionTest{
    
    @isTest
    static void runTestMethod(){
        
        
        TestDataSetupBasic.insertPGAccountTrigger();
        
        String randomNumber = String.valueOf(Integer.valueOf((Math.random() * 100)));
        Corporate_Brand_Name__c corporateBrandName = new Corporate_Brand_Name__c();
        
        List<Corporate_Brand_Name__c> corporateBrandNameList = [SELECT Id FROM Corporate_Brand_Name__c];
        if (corporateBrandNameList.size() > 0) {
            corporateBrandName = corporateBrandNameList[0];
        } else {
            corporateBrandName = new Corporate_Brand_Name__c(Name = 'Test Corporate Brand Name ' + randomNumber,
                                                             Global_Customer_Segment__c = 'Advertiser');
            insert corporateBrandName;
        }
        
        Id recordTypeId = CS_utl_RecordType.getRecordTypeId(Account.getSObjectType(), 'B2B - Account');
        Account testAccount = new Account(Name = 'Test Account', Website = 'www.cloudsense.com',
                                          BillingCity = 'City', BillingCountry = 'United States', BillingCountryCode = 'US', BillingPostalCode = '10000',
                                          BillingState = 'Alabama', BillingStateCode = 'AL', BillingStreet = 'Some Street', Billing_email__c = 'some@some.com',
                                          Industry = 'Agency', Industry_Tier_2__c = 'Media Agency', Type = 'Advertiser', CurrencyIsoCode = 'EUR',
                                          Corporate_Brand_Name__c = corporateBrandName.Id, RecordTypeId = recordTypeId,Status__c = 'Active',AgentNet_ID__c = 'test');
        insert testAccount;
        
        
        
        
        
        Id idRecordType = Schema.SObjectType.Opportunity.getRecordTypeInfosByDeveloperName().get('B2B').getRecordTypeId();  
        Opportunity testOpportunity = new Opportunity(Name = 'testOpportunityForSalesOrderSupportTest' + System.now().getTime(),
                                                      AccountId = testAccount.Id,
                                                      StageName = 'Prospecting',
                                                      CloseDate = System.today(),
                                                      RecordTypeId = idRecordType
                                                     );
        insert testOpportunity ;
        
        QliToOliFieldMapping__c setting = new QliToOliFieldMapping__c();
        setting.Name = 'Amount_Despite_VIP__c';
        setting.OliField__c = 'Amount_Despite_VIP__c';
        insert setting;
        
        Payment_Term__c paymentTerm = new Payment_Term__c();
        paymentTerm.Name = 'Monthly';
        paymentTerm.NS_Payment_Term_ID__c = 123456.00;
        insert paymentTerm;
        

        csmso__Sales_Order__c so = new csmso__Sales_Order__c();
        so.Advertiser_Final__c = testAccount.Id;
        so.csmso__Advertiser__c = testAccount.Id;
        so.csmso__Status__c = 'In Progress';
        so.csmso__Opportunity__c = testOpportunity.Id;
        so.Primary_Sales_Order__c = true;
       // so.NetSuite_Payment_Term__c = paymentTerm.Id;
        insert so;
        cscfga__Product_Basket__c prodBasket = TestDataSetupTargetables.createProdBasket(so);
        prodBasket.Name = 'Basket test';
        prodBasket.Appr_Code__c = '2';
        prodBasket.Payment_Amount__c = 2;
        prodBasket.cscfga__Total_Price__c = 100;
        prodBasket.Payment_Date__c = System.today();
        prodBasket.Payment_Reference__c = 'PayPal';
        prodBasket.Payment_Gateway__c = 'PayPal';
        prodBasket.Payment_Mode__c = 'PayPal';
        prodBasket.EcomReference__c = 'test';
        prodbasket.csmso__Sales_Order__c = so.id;
        insert prodBasket;
        so.NetSuite_Payment_Term__c = paymentTerm.Id;
        try{
        update so;
        }
        catch (exception e){
            
        }
        cscfga__Product_Configuration__c prodConfig = TestDataSetupTargetables.createProdConfig(prodBasket);
        prodConfig.cscfga__Product_Family__c ='MPD Subscriptions';
       
        insert prodCOnfig;
        update so;
    }
}