unpackaged/main/default/objects/Account/fields/AgentNet_ID__c.field-meta.xml
<CustomField>
    <fullName>AgentNet_ID__c</fullName>
    <description>Denotes a numeric id of agents in PG system</description>
    <inlineHelpText>Denotes a numeric id of agents in PG system</inlineHelpText>
    <label>AgentNet ID</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/Brickz_Agent__c.field-meta.xml
<CustomField>
    <fullName>Brickz_Agent__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Brickz Agent</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/Country__c.field-meta.xml
<CustomField>
    <fullName>Country__c</fullName>
    <defaultValue>if(  BEGINS($UserRole.Name, &quot;TH&quot;),&quot;Thailand&quot;,if(ISPICKVAL($User.Subsidiary__c,&quot;MyProperty Data Sdn. Bhd.&quot;),&quot;Malaysia&quot;,&quot;&quot;))</defaultValue>
    <description>Denotes the country of an account</description>
    <inlineHelpText>Denotes the country of an account</inlineHelpText>
    <label>Country</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Country</valueSetName>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Account/fields/External_Field__c.field-meta.xml
<CustomField>
    <fullName>External_Field__c</fullName>
    <label>External Field</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/NetSuite_Id__c.field-meta.xml
<CustomField>
    <fullName>NetSuite_Id__c</fullName>
    <externalId>true</externalId>
    <label>NetSuite Id</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

unpackaged/main/default/objects/Account/fields/Overlap_Agent__c.field-meta.xml
<CustomField>
    <fullName>Overlap_Agent__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Overlap Agent</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/Test_Account__c.field-meta.xml
<CustomField>
    <fullName>Test_Account__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Represents accounts created for testing purpose</description>
    <inlineHelpText>Represents accounts created for testing</inlineHelpText>
    <label>Test Account</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Biforst_Sync__e/Biforst_Sync__e.object-meta.xml
<CustomObject>
    <label>Biforst Sync</label>
    <pluralLabel>Biforst Syncs</pluralLabel>
</CustomObject>

unpackaged/main/default/objects/Field_Mapping__c/Field_Mapping__c.object-meta.xml
<CustomObject>
    <label>Field Mapping</label>
    <nameField>
        <displayFormat>fm-{0000}</displayFormat>
        <label>Field Mapping Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Field Mappings</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Field_Mapping__c/fields/DataType__c.field-meta.xml
<CustomField>
    <fullName>DataType__c</fullName>
    <label>DataType</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Text</fullName>
            </value>
            <value>
                <fullName>Number</fullName>
            </value>
            <value>
                <fullName>Date</fullName>
            </value>
            <value>
                <fullName>Picklist</fullName>
            </value>
            <value>
                <fullName>Checkbox</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Field_Mapping__c/fields/from__c.field-meta.xml
<CustomField>
    <fullName>from__c</fullName>
    <label>From</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Field_Mapping__c/fields/Instance_Name__c.field-meta.xml
<CustomField>
    <fullName>Instance_Name__c</fullName>
    <label>Instance Name</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>PG</fullName>
            </value>
            <value>
                <fullName>iPP</fullName>
            </value>
            <value>
                <fullName>Both</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Field_Mapping__c/fields/Picklist_values__c.field-meta.xml
<CustomField>
    <fullName>Picklist_values__c</fullName>
    <label>Picklist values</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Field_Mapping__c/fields/recordCreation__c.field-meta.xml
<CustomField>
    <fullName>recordCreation__c</fullName>
    <defaultValue>false</defaultValue>
    <label>recordCreation</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Field_Mapping__c/fields/Related_List_Label__c.field-meta.xml
<CustomField>
    <fullName>Related_List_Label__c</fullName>
    <label>Related List Label</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Field_Mapping__c/fields/related_Object_API__c.field-meta.xml
<CustomField>
    <fullName>related_Object_API__c</fullName>
    <label>Related Object API</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Field_Mapping__c/fields/Search_Data__c.field-meta.xml
<CustomField>
    <fullName>Search_Data__c</fullName>
    <label>Search Data</label>
    <referenceTo>Search_and_tag_admin__c</referenceTo>
    <relationshipLabel>Field Mappings</relationshipLabel>
    <relationshipName>Field_Mappings</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/Field_Mapping__c/fields/Sequennce__c.field-meta.xml
<CustomField>
    <fullName>Sequennce__c</fullName>
    <label>Sequennce</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Country__c.field-meta.xml
<CustomField>
    <fullName>Country__c</fullName>
    <formula>TEXT(Subsidiary__r.Country__c )</formula>
    <label>Country</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/External_Field__c.field-meta.xml
<CustomField>
    <fullName>External_Field__c</fullName>
    <label>External Field</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Search_and_tag_admin__c/Search_and_tag_admin__c.object-meta.xml
<CustomObject>
    <label>Search And Tag</label>
    <nameField>
        <label>Search Data Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Search and tags</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Search_and_tag_admin__c/fields/active__c.field-meta.xml
<CustomField>
    <fullName>active__c</fullName>
    <defaultValue>false</defaultValue>
    <label>active</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Search_and_tag_admin__c/fields/Client__c.field-meta.xml
<CustomField>
    <fullName>Client__c</fullName>
    <label>ClientSecret</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Search_and_tag_admin__c/fields/Destination_Object_API__c.field-meta.xml
<CustomField>
    <fullName>Destination_Object_API__c</fullName>
    <label>Destination Object API</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Search_and_tag_admin__c/fields/Destination_Recordtype_Id__c.field-meta.xml
<CustomField>
    <fullName>Destination_Recordtype_Id__c</fullName>
    <label>Destination Recordtype Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Search_and_tag_admin__c/fields/External_Field__c.field-meta.xml
<CustomField>
    <fullName>External_Field__c</fullName>
    <label>External Field</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Search_and_tag_admin__c/fields/password__c.field-meta.xml
<CustomField>
    <fullName>password__c</fullName>
    <label>password</label>
    <length>175</length>
    <maskChar>asterisk</maskChar>
    <maskType>all</maskType>
    <type>EncryptedText</type>
</CustomField>

unpackaged/main/default/objects/Search_and_tag_admin__c/fields/Source_Object_API__c.field-meta.xml
<CustomField>
    <fullName>Source_Object_API__c</fullName>
    <label>Source Object API</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Search_and_tag_admin__c/fields/Source_RecordTypeID__c.field-meta.xml
<CustomField>
    <fullName>Source_RecordTypeID__c</fullName>
    <label>Source RecordTypeID</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/classes/createOpportunitiesAPI.cls
//Test Class : createOpportunitiesAPI_Test
@RestResource(urlMapping='/api/createOpportunitiesAndQuotes/*')
global class createOpportunitiesAPI {
    @HttpPost
    global static void createOpportunities() {
        string result = '';
        list<opportunity> oppList = new list<opportunity>();
        Http http = new Http();
        RestRequest request = Restcontext.request;
        system.debug('request.requestBody.tostring()@@'+request.requestBody.tostring());           
        RestResponse res = RestContext.response;
        Savepoint sp = Database.setSavepoint();    
        Try{  
            Map<String,Object> reqbody = (Map<String,Object>)JSON.deserializeUntyped(RestContext.request.requestBody.tostring());
            List<sObject> objects = new List<sObject>();
            Set<String> iPProdList = new Set<String>();
            opportunity dummyOpp = new opportunity();
            Account dummyAcc = new Account();
            list<Account> accList = new list<Account>();
            String accId;
            Boolean allowInsert = true;
            String failureReason;
            String recordtype =  (String)reqbody.get('desrecordtype');
            String userEmail =  (String)reqbody.get('email');
            String sObjName = (String)reqbody.get('sObjName');
            String externalId = (String)reqbody.get('objectId');
            String accountId = (String)reqbody.get('accountId');
            List<object> resList = (List<object>)reqbody.get('sendResponse');
            List<Object> prodList = (List<object>)reqbody.get('prodList');
            Date startdate;
            boolean isOverlapping;
            
            if(reqbody.containskey('StartDate')&& (String)reqbody.get('StartDate')!=null){
                String quotedate = (String)reqbody.get('StartDate');
                Date d = date.valueOf(quotedate);
                Date finalDate = date.newInstance(d.year(), d.month(), d.day());
                startdate = finalDate; 
            }
            System.debug('prodList@@ '+prodList);
            list<User> userList = [Select Id from user where email =: userEmail ];
            list<String> prodskucode = new list<String>();
            for(Object obj : prodList){
                String code = (String)obj;
                prodskucode.add(code);
            }
            List<Search_and_tag_admin__c> sdList = new List<Search_and_tag_admin__c> ();
            
            sdList = [select id, Destination_Object_API__c , Client__c, ClientID__c, Destination_Recordtype_Id__c, 
                      Password__c, UserName__c, EndPoint__c,External_Field__c  , Source_Object_API__c ,
                      (Select id, from__c, To__c,Instance_Name__c,label__c,DataType__c,Related_List_Label__c,
                       related_Object_API__c,Picklist_values__c,Sequennce__c
                       from Field_Mappings__r where isActive__c =true and recordCreation__c=true order by Sequennce__c )
                      from Search_and_tag_admin__c  where Source_Object_API__c  =: sObjName and Active__c =true
                      and Source_RecordTypeID__c  =: recordtype];
            Map<String,Field_Mapping__c> fmList = new Map<String,Field_Mapping__c>();
            if(!sdList.isEmpty()){
                Search_and_tag_admin__c  sd = sdList[0];
                for(Field_Mapping__c fm : sd.Field_Mappings__r){
                    fmList.put(fm.from__c,fm);
                }
            }
            System.debug('fmList@@'+fmList);
            for(object obj : resList){
                Map<String,object> response = (Map<String,object>)obj;
                
                if(sObjName == 'Opportunity'){
                    
                    if(fmList.containskey((String)response.get('label'))){
                        if(response.get('label') =='Accountid'){
                            accId = (String)response.get('value');
                        }
                        else if(fmList.get((String)response.get('label')).DataType__c !='Date'){
                            
                            dummyOpp.put((String)response.get('label'),(String)response.get('value'));  
                            
                        }else if(fmList.get((String)response.get('label')).DataType__c =='Date'){
                            String closedate = (String)response.get('value');
                            Date d = date.valueOf(closedate);
                            Date finalDate = date.newInstance(d.year(), d.month(), d.day());
                            dummyOpp.put((String)response.get('label'),finalDate);  
                        }
                    }
                    dummyOpp.put('External_field__c',externalId);       
                }else if(sObjName == 'Account'){
                   
                    if(fmList.containskey((String)response.get('label'))){
                        if(fmList.get((String)response.get('label')).DataType__c =='Date'){
                            String closedate = (String)response.get('value');
                            Date d = date.valueOf(closedate);
                            Date finalDate = date.newInstance(d.year(), d.month(), d.day());
                            dummyAcc.put((String)response.get('label'),finalDate);  
                        }else if(fmList.get((String)response.get('label')).DataType__c =='Checkbox'){
                            
                            dummyAcc.put((String)response.get('label'),(Boolean)response.get('value'));  
                            boolean  Overlap_Agent = false;
                            boolean Brickz_Agent = false;
                                    
                            if((String)response.get('label') == 'Brickz_Agent__c'){
                                Brickz_Agent = (boolean)dummyAcc.get('Brickz_Agent__c');    
                            }
                            else if((String)response.get('label') == 'Overlap_Agent__c'){
                                
                                Overlap_Agent = (boolean)dummyAcc.get('Overlap_Agent__c');
                            }
                            if(Brickz_Agent||Overlap_Agent){
                                isOverlapping = true;   
                            }
                            
                            else {
                                isOverlapping = false;
                            }
                            
                            
                        }
                        
                        else{
                            dummyAcc.put((String)response.get('label'),(String)response.get('value'));  
                            
                        }
                    } 
                }
                
            }
            if(accountId!=null){
                accList = [Select Id,External_field__c,country__c,AgentNet_ID__c,Test_Account__c,NetSuite_Id__c
                           from account where id =: accountId];
                if(!accList.isempty()){
                    if(accList[0].External_field__c==null){
                        allowInsert = false;
                        failureReason = 'Related Account should be overlapping';
                    }else if(accList[0].AgentNet_ID__c == null){
                        allowInsert = false;
                        failureReason = 'Please sync related account record to AdminNet'; 
                        
                    }
                    else if(accList[0].Test_Account__c == true){
                        allowInsert = false;
                        failureReason = 'Related account  a test account';  
                        
                    }
                    else if(accList[0].NetSuite_Id__c == null){
                        allowInsert = false;
                        failureReason = 'Please sync related account record to Netsuite'; 
                        
                    }
                    else if(accList[0].country__c != 'Malaysia'){
                        allowInsert = false;
                        failureReason = 'Cross Sell Opportunities can only be created for MY agents'; 
                        
                    }
                }
            }
            if(allowInsert){
                if(sObjName == 'Opportunity'){
                    dummyOpp.put('recordtypeid',recordtype);
                    if(!userList.isempty()){
                        dummyOpp.put('ownerid',userList[0].id);  
                    }
                    if(accountId!=null){
                        dummyOpp.put('accountid',accountId);     
                    }
                    objects.add(dummyOpp); 
                }
                if(sObjName == 'Account'){
                    dummyAcc.put('recordtypeid',recordtype);
                    String phoneNumber = (String)dummyAcc.get('PersonMobilePhone');
                    if(phoneNumber.startsWith('+60')){
                      String phone = (String)phoneNumber.substring(3);
                      dummyAcc.put('PersonMobilePhone',phone);  
                    }
                    if(!userList.isempty()){
                        dummyAcc.put('ownerid',userList[0].id);  
                    }
                     if(isOverlapping!=null && isOverlapping == true){
                        dummyAcc.put('External_field__c',externalId);   
                    }  
                    objects.add(dummyAcc); 
                }
                System.debug(objects);
                if(!objects.isempty())
                    insert objects; 
                if(sObjName == 'Opportunity'){
                    Set<String> oppIds = new Set<String>();
                    for(sobject opp:objects) {
                        oppIds.add(opp.Id);
                    }
                    createOpportunities.createQuote(oppIds,prodskucode,StartDate);
                } 
                if(sObjName == 'Account'){
                    Biforst_Sync__e biforstSync = new Biforst_Sync__e();
                    biforstSync.AccountId__c = objects[0].id;
                    Eventbus.publish(biforstSync);
                }
                result =   (Id)objects[0].id;
            }else{
                result =   (String)failureReason; 
            }
            res.responseBody = blob.valueOf(result);
            
            
        }
        catch(DmlException e){
            Database.rollback(sp);
            res.statusCode = 400;
            system.debug('ERROR' + e.getMessage() + e.getLineNumber());
            result =  e.getMessage();
            res.responseBody = blob.valueOf(result);
            
        }
    }
    
}