unpackaged/main/default/objects/Account/fields/Agency_Id__c.field-meta.xml
<CustomField>
    <fullName>Agency_Id__c</fullName>
    <description>Denotes the unique id of an agency in PG system</description>
    <externalId>true</externalId>
    <inlineHelpText>Denotes the unique id of an agency in PG system</inlineHelpText>
    <label>Agency Id</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Account/recordTypes/Agency.recordType-meta.xml
<RecordType>
    <fullName>Agency</fullName>
    <active>true</active>
    <label>Agency</label>
</RecordType>

unpackaged/main/default/objects/Media__c/Media__c.object-meta.xml
<CustomObject>
    <label>Media</label>
    <nameField>
        <displayFormat>M-{0000000}</displayFormat>
        <label>Agency Logo Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Media</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Media__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Denotes the account to which record is bind to</description>
    <inlineHelpText>Denotes the account to which record is bind to</inlineHelpText>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>Agency_Logo</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/classes/AgencyAPI_Logo.cls
//TEST CLASS : UploadAgencyLogoCont_Test
@RestResource(urlMapping='/api/agency/logo/*')
global class AgencyAPI_Logo {
    @HttpGet
    global static void getAgencyLogo() {
        String Id = RestContext.request.params.get('id');
        system.debug('--Id--'+Id);
        RestResponse res = RestContext.response; //0017F00001JnE2SQAV 
        List<Media__c> lstmedia=[SELECT Id,Account__r.Agency_Id__c,createdDate FROM Media__c where Account__c=:Id and isActive__c=true  order By createdDate Desc limit:1];
        If(lstmedia.size()>0){//a1L6D000000Lh0dUAC
            ContentDocumentLink ObjContentDoc = [SELECT Id, LinkedEntityId, ContentDocumentId FROM ContentDocumentLink where LinkedEntityId=:lstmedia[0].Id];
        	Contentversion attach=[SELECT Id,Title,ContentDocumentId,VersionData FROM ContentVersion where ContentDocumentId=:ObjContentDoc.ContentDocumentId];
            RestContext.response.statusCode = 200;
            RestContext.response.responseBody = attach.VersionData;
        }else{
            RestContext.response.statusCode = 400;
            RestContext.response.responseBody =blob.valueOf('Logo is not present for requested agency id'+Id);
        }
        
    }
}