unpackaged/main/default/objects/Account/fields/AgentNet_ID__c.field-meta.xml
<CustomField>
    <fullName>AgentNet_ID__c</fullName>
    <description>Denotes a numeric id of agents in PG system</description>
    <inlineHelpText>Denotes a numeric id of agents in PG system</inlineHelpText>
    <label>AgentNet ID</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/Approval_Status__c.field-meta.xml
<CustomField>
    <fullName>Approval_Status__c</fullName>
    <description>Denotes the approval status for an agent in the VIP approval process</description>
    <inlineHelpText>Denotes the approval status for an agent in the VIP approval process</inlineHelpText>
    <label>Approval Status</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/Country__c.field-meta.xml
<CustomField>
    <fullName>Country__c</fullName>
    <defaultValue>if(  BEGINS($UserRole.Name, &quot;TH&quot;),&quot;Thailand&quot;,if(ISPICKVAL($User.Subsidiary__c,&quot;MyProperty Data Sdn. Bhd.&quot;),&quot;Malaysia&quot;,&quot;&quot;))</defaultValue>
    <description>Denotes the country of an account</description>
    <inlineHelpText>Denotes the country of an account</inlineHelpText>
    <label>Country</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Country</valueSetName>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Account/fields/isRewardTierUpdated__c.field-meta.xml
<CustomField>
    <fullName>isRewardTierUpdated__c</fullName>
    <defaultValue>false</defaultValue>
    <label>isRewardTierUpdated</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/PG_Reward_Points__c.field-meta.xml
<CustomField>
    <fullName>PG_Reward_Points__c</fullName>
    <label>PG Reward Points</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/Reward_Points__c.field-meta.xml
<CustomField>
    <fullName>Reward_Points__c</fullName>
    <label>Reward Points</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/Reward_Tier__c.field-meta.xml
<CustomField>
    <fullName>Reward_Tier__c</fullName>
    <label>Reward Tier</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Solitaire</fullName>
            </value>
            <value>
                <fullName>Titanium</fullName>
            </value>
            <value>
                <fullName>Platinum</fullName>
            </value>
            <value>
                <fullName>Gold</fullName>
            </value>
            <value>
                <fullName>Silver</fullName>
            </value>
            <value>
                <fullName>Elite</fullName>
            </value>
            <value>
                <fullName>Black</fullName>
                <isActive>false</isActive>
                <label>Black</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Account/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>Denotes the status of an agent in the agent lifecycle</description>
    <inlineHelpText>Denotes the status of an agent in the agent lifecycle</inlineHelpText>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Trial</fullName>
            </value>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Downgraded</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Suspended</fullName>
            </value>
            <value>
                <fullName>Expired</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Agent_Reward__c/Agent_Reward__c.object-meta.xml
<CustomObject>
    <label>Agent Reward</label>
    <nameField>
        <displayFormat>AR-{0000}</displayFormat>
        <label>Agent Reward Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Agent Rewards</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Agent_Reward__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.Record_Type_Text__c</field>
            <operation>equals</operation>
            <value>Agent</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Agent Rewards</relationshipLabel>
    <relationshipName>Agent_Rewards</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Agent_Reward__c/fields/Approval_Status__c.field-meta.xml
<CustomField>
    <fullName>Approval_Status__c</fullName>
    <defaultValue>&#39;Not Required&#39;</defaultValue>
    <label>Approval Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Approval Submitted</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Not Required</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Agent_Reward__c/fields/Approval_Type__c.field-meta.xml
<CustomField>
    <fullName>Approval_Type__c</fullName>
    <label>Approval Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Upgrade</fullName>
            </value>
            <value>
                <fullName>Downgrade</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Agent_Reward__c/fields/Calculated_from__c.field-meta.xml
<CustomField>
    <fullName>Calculated_from__c</fullName>
    <label>Calculated from</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Agent_Reward__c/fields/Country__c.field-meta.xml
<CustomField>
    <fullName>Country__c</fullName>
    <formula>TEXT(Account__r.Country__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Country</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Agent_Reward__c/fields/PG_Reward_Points__c.field-meta.xml
<CustomField>
    <fullName>PG_Reward_Points__c</fullName>
    <label>PG Reward Points</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/Agent_Reward__c/fields/Reward_Points__c.field-meta.xml
<CustomField>
    <fullName>Reward_Points__c</fullName>
    <label>Total Reward Points</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/Agent_Reward__c/fields/Reward_Tier__c.field-meta.xml
<CustomField>
    <fullName>Reward_Tier__c</fullName>
    <label>Reward Tier</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Solitaire</fullName>
            </value>
            <value>
                <fullName>Titanium</fullName>
            </value>
            <value>
                <fullName>Platinum</fullName>
            </value>
            <value>
                <fullName>Gold</fullName>
            </value>
            <value>
                <fullName>Silver</fullName>
            </value>
            <value>
                <fullName>Elite</fullName>
            </value>
            <value>
                <fullName>Black</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Agent_Reward__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New Quarter</fullName>
            </value>
            <value>
                <fullName>Published</fullName>
            </value>
            <value>
                <fullName>Not Published</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Reward_Calculation_Tier__mdt/Reward_Calculation_Tier__mdt.object-meta.xml
<CustomObject>
    <description>Stores the Tiers for the point range as per country</description>
    <label>Reward Calculation Tier</label>
    <pluralLabel>Reward Calculation Tiers</pluralLabel>
</CustomObject>

unpackaged/main/default/objects/Reward_Calculation_Tier__mdt/fields/Lower_Limit__c.field-meta.xml
<CustomField>
    <fullName>Lower_Limit__c</fullName>
    <label>Lower Limit</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/Reward_Calculation_Tier__mdt/fields/Tier__c.field-meta.xml
<CustomField>
    <fullName>Tier__c</fullName>
    <label>Tier</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Reward_Calculation_Tier__mdt/fields/Upload_To_AdminNet__c.field-meta.xml
<CustomField>
    <fullName>Upload_To_AdminNet__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Upload To AdminNet</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Reward_Calculation_Tier__mdt/fields/Upper_Limit__c.field-meta.xml
<CustomField>
    <fullName>Upper_Limit__c</fullName>
    <label>Upper Limit</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/RewardCalculation__e/RewardCalculation__e.object-meta.xml
<CustomObject>
    <label>RewardCalculation</label>
    <pluralLabel>RewardCalculations</pluralLabel>
</CustomObject>

unpackaged/main/default/objects/RewardCalculation__e/fields/Message__c.field-meta.xml
<CustomField>
    <fullName>Message__c</fullName>
    <label>Message</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/classes/publishRewardsToAgents.cls
public class publishRewardsToAgents {
/**
*  Method used to publish Agent Points and Tiers
*  @name publishPoints
*  @param List<Agent_Reward__c>
*  @return void
*/
    public static CSVWrapper publishPoints( List<Agent_Reward__c> arrList,Map<Id,Account> pgRewardPoints,String country,Boolean isbatch){
        Set<Id> accountIds = new Set<Id>();
        Map<Id,Account> accList = new Map<Id,Account>();
        Map<Id,Agent_Reward__c> newAR = new Map<Id,Agent_Reward__c>();
        Map<Id,Agent_Reward__c> previousAR = new Map<Id,Agent_Reward__c>();
        Map<Id,String> currentARTier = new Map<Id,String>();
        Map<Id,String> agentTier = new Map<Id,String>();
        List<Account> toUpdateAccount = new List<Account>();
        Map<id,String> agentVsTier = new Map<id,String>();
        Map<String,String> countryVsHighestTier = new Map<String,String>();
        
        for(Agent_Reward__c ar : arrList) {
            accountIds.add(ar.account__c);
            newAR.put(ar.account__c,ar);
        }
        
        for(Reward_Calculation_Tier__mdt rewardTier : [Select id,Country__c,Lower_Limit__c,Upper_Limit__c,Tier__c from Reward_Calculation_Tier__mdt order by Upper_Limit__c desc]){           
            if(!countryVsHighestTier.containskey(rewardTier.Country__c)){
                countryVsHighestTier.put(rewardTier.Country__c,rewardTier.Tier__c);
            }
        }
        for(Account acc : [SELECT Id,Reward_Points__c,PG_Reward_Points__c,Reward_Tier__c,AgentNet_ID__c,isRewardTierUpdated__c FROM account WHERE Id IN : accountIds]){
            accList.put(acc.Id,acc);
            if(acc.Reward_Tier__c!=null){
                agentVsTier.put(acc.id,acc.Reward_Tier__c);  
            }
        }
        for(Agent_Reward__c prevAR : [SELECT Id ,Approval_Status__c,Approval_Type__c,Calculated_from__c,Reward_Points__c,Reward_Tier__c,account__c,Published_Date__c,Status__c FROM Agent_Reward__c WHERE (account__c IN :accountIds  AND status__c = 'Published') ORDER BY CREATEDDATE DESC]){
            if(!previousAR.containskey(prevAR.account__c)) {
                previousAR.put(prevAR.account__c,prevAR);
            }
        }
        for(Id acc :accList.keyset()) {
            Decimal currentARPoints;
            if(accList.get(acc).Reward_Points__c == null && previousAR.containskey(acc)){
                currentARPoints = previousAR.get(acc).Reward_Points__c;
                currentARTier = calculateTier(previousAR.get(acc).Reward_Points__c,acc,country);
            }else {
                currentARPoints = accList.get(acc).Reward_Points__c;
            currentARTier = calculateTier(accList.get(acc).Reward_Points__c,acc,country);
            }
            if(!previousAR.containskey(acc)) {
                if(currentARPoints==null) {
                    if(newAR.get(acc).Reward_Tier__c != countryVsHighestTier.get(country)) {
                        if(accList.get(acc).Reward_Tier__c != null && accList.get(acc).Reward_Tier__c.equals(countryVsHighestTier.get(country))) {
                            newAR.get(acc).Approval_Status__c ='Approval Submitted';
                            newAR.get(acc).Approval_Type__c = 'Downgrade';
                        } else {
                            accList.get(acc).Reward_Tier__c = newAR.get(acc).Reward_Tier__c; 
                            newAR.get(acc).Status__c ='Published'; 
                            newAR.get(acc).Published_Date__c = System.now();
                        }
                    } else {
                        if(accList.get(acc).Reward_Tier__c != countryVsHighestTier.get(country)) {
                            newAR.get(acc).Approval_Status__c ='Approval Submitted';
                            newAR.get(acc).Approval_Type__c = 'Upgrade';
                        } else {
                            accList.get(acc).Reward_Tier__c = newAR.get(acc).Reward_Tier__c;
                            newAR.get(acc).Status__c ='Published';
                            newAR.get(acc).Published_Date__c = System.now();
                        }
                    }
                } else {
                    if(newAR.get(acc).Reward_Points__c >=currentARPoints) {
                        if(newAR.get(acc).Reward_Tier__c !=countryVsHighestTier.get(country)) {
                            if(accList.get(acc).Reward_Tier__c != null && accList.get(acc).Reward_Tier__c.equals(countryVsHighestTier.get(country))) {
                                newAR.get(acc).Approval_Status__c ='Approval Submitted';
                                newAR.get(acc).Approval_Type__c = 'Downgrade';
                            } else {
                                accList.get(acc).Reward_Tier__c = newAR.get(acc).Reward_Tier__c; 
                                newAR.get(acc).Status__c ='Published';
                                newAR.get(acc).Published_Date__c = System.now();
                            }
                        } else {
                            if(accList.get(acc).Reward_Tier__c != countryVsHighestTier.get(country)){
                                newAR.get(acc).Approval_Status__c ='Approval Submitted'; 
                                newAR.get(acc).Approval_Type__c = 'Upgrade';
                            }else{
                                accList.get(acc).Reward_Tier__c = newAR.get(acc).Reward_Tier__c;
                                newAR.get(acc).Status__c ='Published';
                                newAR.get(acc).Published_Date__c = System.now();
                            }
                        }
                    } 
                    else{
                        // Agent will remain same
                        newAR.get(acc).Status__c ='Not Published';
                    }
                }
            } else {
                if(previousAR.get(acc).Reward_Points__c >=currentARPoints) { // PQ- CQ DG or Same 
                    if(previousAR.get(acc).Reward_Tier__c == currentARTier.get(acc)) { // PQ- CQ Same Tier
                        if(newAR.get(acc).Reward_Tier__c == currentARTier.get(acc)) { // NQ-CQ Same Tier
                            if(newAR.get(acc).Reward_Tier__c !=countryVsHighestTier.get(country)) {
                                if(accList.get(acc).Reward_Tier__c != null && accList.get(acc).Reward_Tier__c.equals(countryVsHighestTier.get(country))) {
                                    newAR.get(acc).Approval_Status__c ='Approval Submitted';
                                    newAR.get(acc).Approval_Type__c = 'Downgrade';
                                } else { 
                                    accList.get(acc).Reward_Tier__c =newAR.get(acc).Reward_Tier__c;
                                    newAR.get(acc).Status__c ='Published';
                                    newAR.get(acc).Published_Date__c = System.now();
                                }
                            } else {
                                if(accList.get(acc).Reward_Tier__c != countryVsHighestTier.get(country)) {
                                    newAR.get(acc).Approval_Status__c ='Approval Submitted'; 
                                    newAR.get(acc).Approval_Type__c = 'Upgrade';
                                } else {
                                    accList.get(acc).Reward_Tier__c = newAR.get(acc).Reward_Tier__c;
                                    newAR.get(acc).Status__c ='Published';
                                    newAR.get(acc).Published_Date__c = System.now();
                                }
                            } 
                        } else if(newAR.get(acc).Reward_Points__c >currentARPoints) { //NQ-CQ Upgrade
                            if(newAR.get(acc).Reward_Tier__c !=countryVsHighestTier.get(country)){
                                if(accList.get(acc).Reward_Tier__c != null && accList.get(acc).Reward_Tier__c.equals(countryVsHighestTier.get(country))) {
                                    newAR.get(acc).Approval_Status__c ='Approval Submitted';
                                    newAR.get(acc).Approval_Type__c = 'Downgrade';
                                } else { 
                                    accList.get(acc).Reward_Tier__c =newAR.get(acc).Reward_Tier__c; 
                                    newAR.get(acc).Status__c ='Published';
                                    newAR.get(acc).Published_Date__c = System.now();
                                }
                            } else {
                                if(accList.get(acc).Reward_Tier__c != countryVsHighestTier.get(country)){
                                    newAR.get(acc).Approval_Status__c ='Approval Submitted'; 
                                    newAR.get(acc).Approval_Type__c = 'Upgrade';
                                }  else{
                                    accList.get(acc).Reward_Tier__c = newAR.get(acc).Reward_Tier__c;
                                    newAR.get(acc).Status__c ='Published';
                                    newAR.get(acc).Published_Date__c = System.now();
                                }
                            }
                        } else {  
                            if(accList.get(acc).Reward_Tier__c !=countryVsHighestTier.get(country)) { //NQ-CQ DG for 1st Time
                                accList.get(acc).Reward_Tier__c = currentARTier.get(acc);
                                newAR.get(acc).Status__c ='Not Published';
                            } else {
                                newAR.get(acc).Approval_Status__c ='Approval Submitted'; 
                                newAR.get(acc).Approval_Type__c = 'Downgrade';
                            }
                        }
                    } else {  
                        // PQ- CQ Downgrage
                        if(newAR.get(acc).Reward_Tier__c !=countryVsHighestTier.get(country) ) {
                            if(accList.get(acc).Reward_Tier__c != null && accList.get(acc).Reward_Tier__c.equals(countryVsHighestTier.get(country))) {
                                newAR.get(acc).Approval_Status__c ='Approval Submitted';
                                newAR.get(acc).Approval_Type__c = 'Downgrade';
                            } else {
                                accList.get(acc).Reward_Tier__c = newAR.get(acc).Reward_Tier__c;  
                                newAR.get(acc).Status__c ='Published';
                                newAR.get(acc).Published_Date__c = System.now();
                            }
                        } else {
                            newAR.get(acc).Approval_Status__c ='Approval Submitted'; 
                            newAR.get(acc).Approval_Type__c = 'Downgrade';
                        }
                    }
                } else if (previousAR.get(acc).Reward_Points__c < currentARPoints) {// PQ- CQ UG or Same 
                    if(previousAR.get(acc).Reward_Tier__c != currentARTier.get(acc)) { // PQ- CQ UG
                        system.debug('currentARTier'+currentARTier);
                        system.debug('newAR'+newAR);
                        if(newAR.get(acc).Reward_Tier__c == currentARTier.get(acc)) { // NQ-CQ Same Tier
                            if(newAR.get(acc).Reward_Tier__c !=countryVsHighestTier.get(country)){
                                if(accList.get(acc).Reward_Tier__c != null && accList.get(acc).Reward_Tier__c.equals(countryVsHighestTier.get(country))) {
                                    newAR.get(acc).Approval_Status__c ='Approval Submitted';
                                    newAR.get(acc).Approval_Type__c = 'Downgrade';
                                } else {
                                    accList.get(acc).Reward_Tier__c =newAR.get(acc).Reward_Tier__c; 
                                    newAR.get(acc).Status__c ='Published';
                                    newAR.get(acc).Published_Date__c = System.now();
                                }
                            } else {
                                if(accList.get(acc).Reward_Tier__c != countryVsHighestTier.get(country)){
                                    newAR.get(acc).Approval_Status__c ='Approval Submitted'; 
                                    newAR.get(acc).Approval_Type__c = 'Upgrade';
                                } else {
                                    accList.get(acc).Reward_Tier__c = newAR.get(acc).Reward_Tier__c;
                                    newAR.get(acc).Status__c ='Published';
                                    newAR.get(acc).Published_Date__c = System.now();
                                }
                            }
                            system.debug('newAR'+newAR.get(acc).Reward_Points__c);
                            system.debug('accList'+accList.get(acc).Reward_Points__c);
                        } else if(newAR.get(acc).Reward_Points__c >currentARPoints) { //NQ-CQ Upgrade
                            if(newAR.get(acc).Reward_Tier__c !=countryVsHighestTier.get(country)) {
                                if(accList.get(acc).Reward_Tier__c != null && accList.get(acc).Reward_Tier__c.equals(countryVsHighestTier.get(country))) {
                                    newAR.get(acc).Approval_Status__c ='Approval Submitted';
                                    newAR.get(acc).Approval_Type__c = 'Downgrade';
                                } else {
                                    accList.get(acc).Reward_Tier__c =newAR.get(acc).Reward_Tier__c; 
                                    newAR.get(acc).Status__c ='Published';
                                    newAR.get(acc).Published_Date__c = System.now();
                                }
                            }else{
                                if(accList.get(acc).Reward_Tier__c != countryVsHighestTier.get(country)){
                                    newAR.get(acc).Approval_Status__c ='Approval Submitted'; 
                                    newAR.get(acc).Approval_Type__c = 'Upgrade';
                                } 
                                else{
                                    accList.get(acc).Reward_Tier__c = newAR.get(acc).Reward_Tier__c;
                                    newAR.get(acc).Status__c ='Published';
                                    newAR.get(acc).Published_Date__c = System.now();
                                }
                            }
                        } else {
                            if(accList.get(acc).Reward_Tier__c !=countryVsHighestTier.get(country)) {         //NQ-CQ DG for 1st Time
                                accList.get(acc).Reward_Tier__c = currentARTier.get(acc);
                                newAR.get(acc).Status__c ='Not Published';
                            } else {
                                newAR.get(acc).Approval_Status__c ='Approval Submitted'; 
                                newAR.get(acc).Approval_Type__c = 'Downgrade';
                            }
                        } 
                    }else{
                        
                    }
                }  
            }
            if(!pgRewardPoints.isempty() && pgRewardPoints.containskey(acc) && pgRewardPoints.get(acc) != null){       
                accList.get(acc).PG_Reward_Points__c = pgRewardPoints.get(acc).PG_Reward_Points__c; 
            }
            accList.get(acc).Reward_Points__c = newAR.get(acc).Reward_Points__c;
            accList.get(acc).isRewardTierUpdated__c = true;
            toUpdateAccount.add(accList.get(acc));
        } 
        List<account> temp = toUpdateAccount;
        Database.SaveResult[] updateResults =  Database.update(accList.values(),false);
        Database.SaveResult[] updateResults1 =  Database.update(newAR.values(),false);
        
        CSVWrapper csvWrap = notifyUpdateStatus(updateResults,toUpdateAccount,country,agentVsTier,isbatch);
        return csvWrap;
    }
    
    
    public static Map<Id,String> calculateTier(Decimal Points,Id acc,String country) {
        Map<id,String> mapToUpdate = new Map<id,String>();
        for(Reward_Calculation_Tier__mdt rewardTier : [Select id,Country__c,Lower_Limit__c,Upper_Limit__c,Tier__c from Reward_Calculation_Tier__mdt where Country__c=:Country]){
          
            if(Points >= rewardTier.Lower_Limit__c && Points <= rewardTier.Upper_Limit__c ){
                System.debug(Points+rewardTier.Tier__c);
                mapToUpdate.put(acc,rewardTier.Tier__c);
                break;
            }     
        }  return mapToUpdate;         
    }
    
    public static CSVWrapper notifyUpdateStatus(Database.SaveResult[] updateResults,list<account> toUpdateAccount,String country,Map<id,string> agentVsTier,boolean isbatch){
        String failedDML;
        String AccountId;
        String csvColumnHeader; 
        List<String> csvRowValuesSuccess = new List<String>(); // Stores the account Updated successsfuly
        List<String> csvRowValues = new List<String>(); // Stores the accountdetails with error
        List<String> csvRemoveAgents = new List<String>(); //Stores the agent to be removed from AdminNet
        List<String> allowTierAdmitNet = new List<String>();
        
        for(Reward_Calculation_Tier__mdt reward :[SELECT tier__c,Upload_To_AdminNet__c, Country__c FROM Reward_Calculation_Tier__mdt WHERE Country__c =: country and Upload_To_AdminNet__c = true]){
            allowTierAdmitNet.add(reward.tier__c); 
        }
        Folder f = [SELECT Id, Name FROM Folder WHERE Name = 'BatchToComputeTotalSpending_Results'];
        
        for(Integer i=0;i< updateResults.size();i++){
            String rowStr;
            if(updateResults.get(i).isSuccess()) {
                Id accId = updateResults.get(i).getId();
                if(toUpdateAccount[i].reward_tier__c!=null){
                    if(allowTierAdmitNet.contains(toUpdateAccount[i].reward_tier__c)){
                        rowStr = Datetime.now().format('MMM') + ','+ accId +',' +toUpdateAccount[i].Reward_Points__c + ','+ toUpdateAccount[i].reward_tier__c+','+ toUpdateAccount[i].AgentNet_ID__c +',' + 'Successfully Updated';
                        csvRowValuesSuccess.add(rowStr);    
                    }else{
                        if(!agentVsTier.isempty() && agentVsTier.containskey(accId) && allowTierAdmitNet.contains(agentVsTier.get(accId))){
                            rowStr = Datetime.now().format('MMM') + ','+ accId +',' +toUpdateAccount[i].Reward_Points__c + ','+ toUpdateAccount[i].reward_tier__c+','+ toUpdateAccount[i].AgentNet_ID__c +',' + 'Remove the AgentId from AdminNet';
                            csvRemoveAgents.add(rowStr);
                        }
                    }
                    
                }    
                
            } else {
                Database.Error error = updateResults.get(i).getErrors().get(0);
                failedDML = error.getMessage();
                AccountId = toUpdateAccount[i].id; //failed record from the list
                rowStr = Datetime.now().format('MMM') + ','+ AccountId +','+failedDML;
                csvRowValues.add(rowStr);
            }
        }
        
        CSVWrapper csvWrapperObj = new CSVWrapper();
        csvWrapperObj.successCSV = csvRowValuesSuccess;
        csvWrapperObj.errorCSV = csvRowValues;
        csvWrapperObj.removeAgentIdsCSV = csvRemoveAgents;
        if(!isbatch){
            List<RewardCalculation__e> rewardCalculationSuccess = new List<RewardCalculation__e>();
            
            if(!csvRowValuesSuccess.isEmpty()){
                
                String documentName = 'BatchToComputeTotalSpending_SuccessResults-'+ Datetime.now().format('MMM') + Datetime.now().year();
                csvColumnHeader = 'Date, AccountId ,Reward Points, Reward Tiers ,AgentNet ID,Update Status\n';
                String csvFile = csvColumnHeader + String.join(csvRowValuesSuccess,'\n');
                
                Document doc = new Document(Name = documentName, Body = Blob.valueOf(csvFile), FolderId = f.Id, Type = 'csv', ContentType='application/vnd.ms-excel');
                insert doc;     
                
                rewardCalculationSuccess.add(new RewardCalculation__e(Document_Id__c = doc.id, Message__c = country+': Update'));
                EventBus.publish(rewardCalculationSuccess);
            }
            if(!csvRemoveAgents.isEmpty()){
                String documentName = 'BatchToComputeTotalSpending_Remove_From_AdminNet '+ Datetime.now().format('MMM') + Datetime.now().year();
                csvColumnHeader = 'Date, AccountId ,Reward Points, Reward Tiers ,AgentNet ID,Update Status\n';
                String csvFile = csvColumnHeader + String.join(csvRemoveAgents,'\n');
                
                Document doc = new Document(Name = documentName, Body = Blob.valueOf(csvFile), FolderId = f.Id, Type = 'csv', ContentType='application/vnd.ms-excel');
                insert doc;     
                
                rewardCalculationSuccess.add(new RewardCalculation__e(Document_Id__c = doc.id, Message__c = country+': Remove'));
                EventBus.publish(rewardCalculationSuccess);
                
            }
            
            if(!csvRowValues.isEmpty()){
                String documentName = 'BatchToComputeTotalSpending_Results-'+ Datetime.now().format('MMM') + Datetime.now().year();
                csvColumnHeader = 'Date, AccountId ,Error Message\n';
                String csvFile = csvColumnHeader + String.join(csvRowValues,'\n');
                
                // To send alert on PG Automation Channel
                
                String slack_user = label.PG_LABEL_BatchToComputeTotalSpending_SlackUser;
                String text = '', payload = '';
                String title = slack_user +' '+ 'Please find detailed Error information of BatchToComputeTotalSpending\n';
                title += '```"Id"';
                text += '"'+csvFile+'"\n';
                if(String.isNotBlank(text)){
                    text += '```';
                    payload += title + text; 
                }
                if(payload!= '') {
                    SlackAlert.notifyPGAutoChannel(payload);
                }
                Document doc = new Document(Name = documentName, Body = Blob.valueOf(csvFile), FolderId = f.Id, Type = 'csv', ContentType='application/vnd.ms-excel');
                insert doc;
            }         
        }
        return csvWrapperObj;
    }
    
    public class CSVWrapper {
        public List<String> successCSV;
        public List<String> errorCSV;
        public List<String> removeAgentIdsCSV;
    }
}