unpackaged/main/default/objects/Account/fields/AgentNet_ID__c.field-meta.xml
<CustomField>
    <fullName>AgentNet_ID__c</fullName>
    <description>Denotes a numeric id of agents in PG system</description>
    <inlineHelpText>Denotes a numeric id of agents in PG system</inlineHelpText>
    <label>AgentNet ID</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/Country__c.field-meta.xml
<CustomField>
    <fullName>Country__c</fullName>
    <defaultValue>if(  BEGINS($UserRole.Name, &quot;TH&quot;),&quot;Thailand&quot;,if(ISPICKVAL($User.Subsidiary__c,&quot;MyProperty Data Sdn. Bhd.&quot;),&quot;Malaysia&quot;,&quot;&quot;))</defaultValue>
    <description>Denotes the country of an account</description>
    <inlineHelpText>Denotes the country of an account</inlineHelpText>
    <label>Country</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Country</valueSetName>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Account/fields/Email__c.field-meta.xml
<CustomField>
    <fullName>Email__c</fullName>
    <description>Denotes email id for business account</description>
    <inlineHelpText>Denotes email id for business account</inlineHelpText>
    <label>Email</label>
    <type>Email</type>
</CustomField>

unpackaged/main/default/objects/CountryCode__c/CountryCode__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>CountryCode</label>
</CustomObject>

unpackaged/main/default/objects/Opportunity/fields/Agent_Accepted_Time__c.field-meta.xml
<CustomField>
    <fullName>Agent_Accepted_Time__c</fullName>
    <label>Agent Accepted Time</label>
    <type>DateTime</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Country__c.field-meta.xml
<CustomField>
    <fullName>Country__c</fullName>
    <formula>TEXT(Subsidiary__r.Country__c )</formula>
    <label>Country</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Guruland_Link_Expiry_Date__c.field-meta.xml
<CustomField>
    <fullName>Guruland_Link_Expiry_Date__c</fullName>
    <formula>Guruland_Link_Created_Date__c +
 IF(Country__c=&quot;Singapore&quot;, $CustomMetadata.Country_Attribute__mdt.Singapore.Expired_Hours__c/24,
  IF(Country__c=&quot;Malaysia&quot;, $CustomMetadata.Country_Attribute__mdt.Malaysia.Expired_Hours__c/24,
   IF(Country__c=&quot;Thailand&quot;, $CustomMetadata.Country_Attribute__mdt.Thailand.Expired_Hours__c/24,
    IF(Country__c=&quot;Indonesia&quot;, $CustomMetadata.Country_Attribute__mdt.Indonesia.Expired_Hours__c/24, 0))))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Guruland Link Expiry Date</label>
    <type>DateTime</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Opportunity_Number__c.field-meta.xml
<CustomField>
    <fullName>Opportunity_Number__c</fullName>
    <displayFormat>PGSO-{YY}{000000}</displayFormat>
    <label>Opportunity Number</label>
    <type>AutoNumber</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Payment_Amount__c.field-meta.xml
<CustomField>
    <fullName>Payment_Amount__c</fullName>
    <label>Payment Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Payment_Gateway__c.field-meta.xml
<CustomField>
    <fullName>Payment_Gateway__c</fullName>
    <label>Payment Gateway</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Adyen</fullName>
            </value>
            <value>
                <fullName>Braintree</fullName>
            </value>
            <value>
                <fullName>PayPal</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Payment_Reference__c.field-meta.xml
<CustomField>
    <fullName>Payment_Reference__c</fullName>
    <label>Payment Reference</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Payment_Time__c.field-meta.xml
<CustomField>
    <fullName>Payment_Time__c</fullName>
    <label>Payment Time</label>
    <type>DateTime</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Payment_Type__c.field-meta.xml
<CustomField>
    <fullName>Payment_Type__c</fullName>
    <label>Payment Method</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Online</fullName>
            </value>
            <value>
                <fullName>Offline</fullName>
            </value>
            <value>
                <fullName>credit-card</fullName>
                <label>Credit Card</label>
            </value>
            <value>
                <fullName>bank-transfer</fullName>
                <label>Bank Transfer</label>
            </value>
            <value>
                <fullName>paypal</fullName>
                <label>Paypal</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Push_To_NetSuite__c.field-meta.xml
<CustomField>
    <fullName>Push_To_NetSuite__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Push To NetSuite</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Total_Amount_Before_Discount__c.field-meta.xml
<CustomField>
    <fullName>Total_Amount_Before_Discount__c</fullName>
    <inlineHelpText>(Sales Price * Qty) - Complimentary</inlineHelpText>
    <label>Total Amount Before Discount</label>
    <summarizedField>OpportunityLineItem.Price_before_discount__c</summarizedField>
    <summaryForeignKey>OpportunityLineItem.OpportunityId</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Total_Discounted_Amount__c.field-meta.xml
<CustomField>
    <fullName>Total_Discounted_Amount__c</fullName>
    <label>Total Discounted Amount</label>
    <summarizedField>OpportunityLineItem.Discounted_Amount__c</summarizedField>
    <summaryForeignKey>OpportunityLineItem.OpportunityId</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Total_Gross_Amount__c.field-meta.xml
<CustomField>
    <fullName>Total_Gross_Amount__c</fullName>
    <inlineHelpText>Total Amount after discount &amp; tax</inlineHelpText>
    <label>Total Gross Amount</label>
    <summarizedField>OpportunityLineItem.Gross_Amount__c</summarizedField>
    <summaryForeignKey>OpportunityLineItem.OpportunityId</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Total_Tax_Amount__c.field-meta.xml
<CustomField>
    <fullName>Total_Tax_Amount__c</fullName>
    <label>Total Tax Amount</label>
    <summarizedField>OpportunityLineItem.Tax_Amount__c</summarizedField>
    <summaryForeignKey>OpportunityLineItem.OpportunityId</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

unpackaged/main/default/objects/OpportunityLineItem/fields/Amount__c.field-meta.xml
<CustomField>
    <fullName>Amount__c</fullName>
    <description>Amount after discount before tax (Sales Price * Qty - Discount), exclude complimentary</description>
    <formula>IF( Complimentary__c = TRUE, IF(Record_Type__c=&quot;B2C&quot;, (UnitPrice *  Quantity) - TotalPrice, (UnitPrice *  Quantity) - Discounted_Amount__c -  TotalPrice) , IF(Record_Type__c=&quot;B2C&quot;, (UnitPrice *  Quantity) - Discounted_Amount__c - Pro_Rate_Amount__c, (UnitPrice *  Quantity) - Discounted_Amount__c))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>(Sales Price * Qty - Discount) - Complimentary, before Tax</inlineHelpText>
    <label>Price after discount</label>
    <precision>18</precision>
    <scale>3</scale>
    <type>Currency</type>
</CustomField>

unpackaged/main/default/objects/OpportunityLineItem/fields/Discount_Amount__c.field-meta.xml
<CustomField>
    <fullName>Discount_Amount__c</fullName>
    <defaultValue>0</defaultValue>
    <description>This is the discount amount that the sales user will input</description>
    <inlineHelpText>Apply this Discount Amount (DO NOT input Discount % if this is applicable)</inlineHelpText>
    <label>Discount Amt</label>
    <precision>18</precision>
    <scale>3</scale>
    <type>Currency</type>
</CustomField>

unpackaged/main/default/objects/OpportunityLineItem/fields/End_Date__c.field-meta.xml
<CustomField>
    <fullName>End_Date__c</fullName>
    <defaultValue>TODAY()</defaultValue>
    <description>End Date of the contract for the line item. Map to NetSuite SO.</description>
    <label>End Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/OpportunityLineItem/fields/Gross_Amount__c.field-meta.xml
<CustomField>
    <fullName>Gross_Amount__c</fullName>
    <formula>Amount__c+( Amount__c *  GST_VAT_Rate__c )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>Total Price after discount and tax</inlineHelpText>
    <label>Gross Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

unpackaged/main/default/objects/OpportunityLineItem/fields/Push_to_NetSuite__c.field-meta.xml
<CustomField>
    <fullName>Push_to_NetSuite__c</fullName>
    <defaultValue>true</defaultValue>
    <label>Push to NetSuite</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/OpportunityLineItem/fields/Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Start_Date__c</fullName>
    <defaultValue>TODAY()</defaultValue>
    <description>Start Date of the contract for the line item. Map to NetSuite SO.</description>
    <label>Start Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/OpportunityLineItem/fields/Tax_Amount__c.field-meta.xml
<CustomField>
    <fullName>Tax_Amount__c</fullName>
    <formula>Amount__c  *   GST_VAT_Rate__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>Tax amount (Price after discount * tax rate)</inlineHelpText>
    <label>Tax Amount</label>
    <precision>18</precision>
    <scale>3</scale>
    <type>Currency</type>
</CustomField>

unpackaged/main/default/objects/Product2/fields/Push_To_NetSuite__c.field-meta.xml
<CustomField>
    <fullName>Push_To_NetSuite__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Push To NetSuite</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Quote/fields/Agent_Accepted_Time__c.field-meta.xml
<CustomField>
    <fullName>Agent_Accepted_Time__c</fullName>
    <label>Agent Accepted Time</label>
    <type>DateTime</type>
</CustomField>

unpackaged/main/default/objects/Quote/fields/Country__c.field-meta.xml
<CustomField>
    <fullName>Country__c</fullName>
    <formula>TEXT(Opportunity.Subsidiary__r.Country__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Country</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Quote/fields/Guruland_Link_Expiry_Date__c.field-meta.xml
<CustomField>
    <fullName>Guruland_Link_Expiry_Date__c</fullName>
    <formula>IF(Country__c=&quot;Singapore&quot; &amp;&amp; ISPICKVAL(Quote_Type__c, &#39;B2C - Renewal&#39;) ,SG_Payment_Link_Expiry__c,
			Guruland_Link_Created_Date__c +
IF(Country__c=&quot;Singapore&quot;, $CustomMetadata.Country_Attribute__mdt.Singapore.Expired_Hours__c/24,
IF(Country__c=&quot;Malaysia&quot;, $CustomMetadata.Country_Attribute__mdt.Malaysia.Expired_Hours__c/24,
IF(Country__c=&quot;Thailand&quot;, $CustomMetadata.Country_Attribute__mdt.Thailand.Expired_Hours__c/24,
IF(Country__c=&quot;Indonesia&quot;, $CustomMetadata.Country_Attribute__mdt.Indonesia.Expired_Hours__c/24, 0)))))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Guruland Link Expiry Date</label>
    <type>DateTime</type>
</CustomField>

unpackaged/main/default/objects/Quote/fields/Opportunity_Number__c.field-meta.xml
<CustomField>
    <fullName>Opportunity_Number__c</fullName>
    <displayFormat>PGSO-{YY}{000000}</displayFormat>
    <label>Opportunity Number</label>
    <type>AutoNumber</type>
</CustomField>

unpackaged/main/default/objects/Quote/fields/Payment_Amount__c.field-meta.xml
<CustomField>
    <fullName>Payment_Amount__c</fullName>
    <label>Payment Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

unpackaged/main/default/objects/Quote/fields/Payment_Reference__c.field-meta.xml
<CustomField>
    <fullName>Payment_Reference__c</fullName>
    <label>Payment Reference</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Quote/fields/Payment_Time__c.field-meta.xml
<CustomField>
    <fullName>Payment_Time__c</fullName>
    <label>Payment Time</label>
    <type>DateTime</type>
</CustomField>

unpackaged/main/default/objects/Quote/fields/Total_Amount_Before_Discount__c.field-meta.xml
<CustomField>
    <fullName>Total_Amount_Before_Discount__c</fullName>
    <inlineHelpText>(Sales Price * Qty) - Complimentary</inlineHelpText>
    <label>Total Amount Before Discount</label>
    <summarizedField>QuoteLineItem.Price_before_discount1__c</summarizedField>
    <summaryForeignKey>QuoteLineItem.QuoteId</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

unpackaged/main/default/objects/Quote/fields/Total_Discounted_Amount__c.field-meta.xml
<CustomField>
    <fullName>Total_Discounted_Amount__c</fullName>
    <label>Total Discounted Amount</label>
    <summarizedField>QuoteLineItem.Discounted_Amount__c</summarizedField>
    <summaryForeignKey>QuoteLineItem.QuoteId</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

unpackaged/main/default/objects/Quote/fields/Total_Gross_Amount__c.field-meta.xml
<CustomField>
    <fullName>Total_Gross_Amount__c</fullName>
    <label>Total Gross Amount</label>
    <summarizedField>QuoteLineItem.Gross_Amount__c</summarizedField>
    <summaryForeignKey>QuoteLineItem.QuoteId</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

unpackaged/main/default/objects/Quote/fields/Total_Tax_Amount__c.field-meta.xml
<CustomField>
    <fullName>Total_Tax_Amount__c</fullName>
    <label>Total Tax Amount</label>
    <summarizedField>QuoteLineItem.Tax_Amount_new__c</summarizedField>
    <summaryForeignKey>QuoteLineItem.QuoteId</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

unpackaged/main/default/objects/User/fields/Webuser_ID__c.field-meta.xml
<CustomField>
    <fullName>Webuser_ID__c</fullName>
    <label>Webuser ID</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/classes/QuotesAPI.cls
/*------------------------------------------------------------
Author      : Thinh Ho
Company     : Viseo Asia PTE LTD
Description : Endpoint to handle integration between Guruland (Quote) and Salesforce (Opportunity).
Inputs      : JSON Request
History
<Date>      <Authors Name>     <Brief Description of Change>
------------------------------------------------------------*/
@RestResource(urlMapping='/api/quote/*')
global with sharing class QuotesAPI {
    /*------------------------------------------------------------
Author      : Thinh Ho
Company     : Viseo Asia PTE LTD
Description : GET method. To send requested salesforce opportunity record by Guruland. Guruland must include <id>Salesforce Id to get the Opportunity data.
Inputs      : JSON <id>
History
<Date>      <Authors Name>     <Brief Description of Change>
------------------------------------------------------------*/
    @HttpGet
    global static void readQuote() {
        restResponse res = restContext.response;
        string result;
        String opptyId = RestContext.request.params.get('id');
        List<Opportunity> oppties = [SELECT Id, Name, Account.AgentNet_Id__c, Account.Name, 
                                     Account.BillingAddress, Account.Email__c, Opportunity_Number__c, 
                                     Amount, CreatedDate, StageName, Owner.Name,Account.Country__c,
                                     CreatedBy.Name,Total_Tax_Amount__c, Total_Gross_Amount__c,
                                     Total_Amount_Before_Discount__c, Total_Discounted_Amount__c,Owner.Webuser_ID__c,Guruland_Link_Expiry_Date__c, Account.personEmail,
                                     (SELECT Id, Product2.Name, Description, Quantity, UnitPrice,
                                      Tax_Amount__c, Discount_Amount__c, Amount__c,Gross_amount__c,
                                      Start_Date__c, End_Date__c
                                      FROM OpportunityLineItems where Push_to_NetSuite__c =: true)
                                     FROM Opportunity 
                                     WHERE ID=:opptyId];
        
        Quote quote = new Quote(); 
        if (oppties.size()>0){
            quote = new Quote(oppties[0]) ;
            res.statusCode = 200;
            result = system.JSON.serialize(quote);
            res.responseBody = blob.valueOf(result);
        }else{
            res.statusCode = 400;
            result = 'Opportunity requested by Guruland is not found';
            res.responseBody = blob.valueOf(result);
        }
        
    }
    /*------------------------------------------------------------
Author      : Thinh Ho
Company     : Viseo Asia PTE LTD
Description : Post Method to Update Salesforce Opportunty record <Payment Time, Payment Type, and Agent Accepted Time> with data from Guruland. Guruland must include <id>Salesforce Id.
Inputs      : JSON request
History
<Date>      <Authors Name>     <Brief Description of Change>
------------------------------------------------------------*/    
    @HttpPost
    global static void updateQuote() {
        Quote quote = new Quote();
        Savepoint sp = Database.setSavepoint();   
        try {
            List<String> updatedFields = new List<String>();
            Opportunity requestData = (Opportunity) System.JSON.deserialize(RestContext.request.requestBody.tostring(), Opportunity.class);   
            Opportunity existingOppty = [SELECT Id, Name, Payment_Type__c, Payment_Time__c, Agent_Accepted_Time__c ,
                                         Account.AgentNet_Id__c, Account.Name, 
                                         Account.BillingAddress, Account.Email__c, Opportunity_Number__c, 
                                         Amount, CreatedDate, StageName, Owner.Name,Total_Tax_Amount__c,
                                         CreatedBy.Name,
                                         Payment_Amount__c, Payment_Reference__c,Account.Country__c,Total_Gross_Amount__c,Payment_Gateway__c,
                                         Total_Amount_Before_Discount__c,Owner.Webuser_ID__c,Guruland_Link_Expiry_Date__c, Account.personEmail,
                                         (SELECT Id, Product2.Name, Description, Quantity, UnitPrice,
                                          Tax_Amount__c, Discount_Amount__c, Amount__c,Gross_amount__c,
                                          Start_Date__c, End_Date__c
                                          FROM OpportunityLineItems)
                                         FROM Opportunity 
                                         WHERE Opportunity_Number__c = :requestData.Id];
            
            if (existingOppty.Payment_Time__c == null && requestData.Payment_Time__c != null) {
                existingOppty.Payment_Time__c = requestData.Payment_Time__c;
            }
            
            if (existingOppty.Agent_Accepted_Time__c == null && requestData.Agent_Accepted_Time__c != null) {
                existingOppty.Agent_Accepted_Time__c = requestData.Agent_Accepted_Time__c;
            }
            
            existingOppty.Payment_Type__c = requestData.Payment_Type__c;
            existingOppty.Payment_Amount__c = requestData.Payment_Amount__c;
            existingOppty.Payment_Reference__c = requestData.Payment_Reference__c;
            existingOppty.Payment_Gateway__c = requestData.Payment_Gateway__c;
            
            update existingOppty;
            
            quote = new Quote(existingOppty);
            RestContext.response.responseBody = Blob.valueOf(JSON.serialize(quote));
            
        } catch (Exception ex) {
            Database.rollback(sp);
            system.debug('ERROR' + ex.getMessage() + ' ' + ex.getLineNumber());
            RestContext.response.statusCode = 400;
            RestContext.response.responseBody = Blob.valueOf(ex.getMessage() + ' ' + ex.getLineNumber());
        }
    }
    /*------------------------------------------------------------
Author      : Thinh Ho
Company     : Viseo Asia PTE LTD
Description : Wrapper class to map salesforce field into guruland quote JSON request.
Inputs      : String Opportunity <StageName>
History
<Date>      <Authors Name>     <Brief Description of Change>
------------------------------------------------------------*/    
    global class Quote {
        String region;
        String agent_id;
        String invoice_id;
        String total;
        OrderInfo order_info;
        String created;
        String status; 
        String expiry;
        public Quote() {
            
        }
        
        public Quote(Opportunity oppty) {
            String countryCode='';
            CountryCode__C[] country_Code = CountryCode__c.getAll().Values();
            map<string,string> Cc = new map<string,string>();
            for (integer i = 0 ; i<country_Code.size();i++){
                Cc.put(country_Code[i].name,country_Code[i].code__c);
            }
            if(oppty.Account.Country__c <> null){
                countryCode = Cc.get(string.valueOF(oppty.Account.Country__c.toLowerCase()));
            }
            this.region = countryCode;
            this.agent_id = oppty.Account.AgentNet_Id__c;
            this.invoice_id = oppty.Opportunity_Number__c;
            this.total = String.valueOf(oppty.Total_Gross_Amount__c.setScale(2));   
            this.created = String.valueOf(oppty.CreatedDate);
            this.status = translateStage(oppty.StageName);
            this.order_info = new OrderInfo(oppty);
            
            this.expiry = string.valueOF(oppty.Guruland_Link_Expiry_Date__c.format('YYYY-MM-dd HH:mm:ss'));
        }
        
        /*------------------------------------------------------------
Author      : Thinh Ho
Company     : Viseo Asia PTE LTD
Description : This method translates opportunity stage to guruland quote status.
Inputs      : String Opportunity <StageName>
History
<Date>      <Authors Name>     <Brief Description of Change>
------------------------------------------------------------*/
        private String translateStage(String opptyStage) {
            Map<String, String> statusMap = new Map<String, String> {
                'new'                       => 'close',
                    'proposal'                  => 'close',
                    'pending online payment'    => 'open',  
                    'pending omc approval'      => 'close',
                    'closed won'                => 'close',
                    'closed lost'               => 'close'
                    };
                        opptyStage = opptyStage.toLowerCase();
            String quoteStatus = opptyStage; 
            if (statusMap.containsKey(opptyStage))
                quoteStatus = statusMap.get(opptyStage);
            else
                quoteStatus = opptyStage;
            return quoteStatus;
        }
    } 
    /*------------------------------------------------------------
Author      : Thinh Ho
Company     : Viseo Asia PTE LTD
Description : Wrapper class to map Salesforce fields into guruland quote (order_info) JSON request.
Inputs      : String Opportunity <StageName>
History
<Date>      <Authors Name>     <Brief Description of Change>
------------------------------------------------------------*/  
    global class OrderInfo {
        String region;          String webuserId;   	String customerName;    String billaddress;
        String email;           String referenceNo;     String createdDate;		SalesRepInformation salesRep; 
        List<Item> items;   	String tranAmount;      String tranTax;
        String tranDisc;        String tranTotal;
        
        public OrderInfo(Opportunity oppty) {
            String countryCode='';
            String webuser='';
            User rowUser = new User();
            rowUser = [SELECT id,name, MobilePhone,email FROM user WHERE id =: oppty.ownerid ];
            salesRepInformation rowSalesRep = new salesRepInformation(rowUser.Name, rowUser.Email, rowUser.MobilePhone);
            if(oppty.Account.AgentNet_Id__c <> null){
                webuser = string.valueOF(oppty.Account.AgentNet_Id__c);
            }
            CountryCode__C[] country_Code = CountryCode__c.getAll().Values();
            map<string,string> Cc = new map<string,string>();
            for (integer i = 0 ; i<country_Code.size();i++){
                Cc.put(country_Code[i].name,country_Code[i].code__c);
            }
            if(oppty.Account.Country__c <> null){
                countryCode = Cc.get(string.valueOF(oppty.Account.Country__c.toLowerCase()));
            }
            
            this.region = countryCode;
            this.webuserId = webuser;
            this.customerName = oppty.Account.Name;
            if (oppty.Account.BillingAddress != null)
                this.billaddress = String.join(
                    new List<String> {oppty.Account.BillingAddress.getStreet(),
                        oppty.Account.BillingAddress.getCity(),
                        oppty.Account.BillingAddress.getCountry()}, 
                    ' ');
            this.email = oppty.Account.personEmail;
            this.referenceNo = oppty.Opportunity_Number__c;
            this.createdDate = String.valueOf(oppty.CreatedDate);
            this.tranAmount = String.valueOf((oppty.Total_Amount_Before_Discount__c + oppty.Total_Tax_Amount__c.setScale(2)));
            this.tranTax = String.valueOf(oppty.Total_Tax_Amount__c.setScale(2));
            this.tranDisc = String.valueOf(oppty.Total_Discounted_Amount__c);
            this.tranTotal = String.valueOf(oppty.Total_Gross_Amount__c.setScale(2));
            this.salesRep = rowSalesRep;
            
            this.items = new List<Item>();
            for (OpportunityLineItem opptyItem : oppty.OpportunityLineItems) {
                items.add(new Item(opptyItem));
            }
        }
    }
    /*------------------------------------------------------------
Author      : Steven Junaidy
Company     : Viseo Asia PTE LTD
Description : Wrapper class to map Salesforce fields into guruland quote(salesRep) JSON request.
Inputs      : String Opportunity <StageName>
History
<Date>      <Authors Name>     <Brief Description of Change>
------------------------------------------------------------*/  
    global class SalesRepInformation {
        string name; string email ; string contactNo;
        SalesRepInformation( string name, string email, string contactNo){
            this.name = name; this.email = email; this.contactNo = contactNo;
        }
    }
    
    /*------------------------------------------------------------
Author      : Thinh Ho
Company     : Viseo Asia PTE LTD
Description : Wrapper class to map Salesforce fields into guruland quote(item) JSON request.
Inputs      : String Opportunity <StageName>
History
<Date>      <Authors Name>     <Brief Description of Change>
------------------------------------------------------------*/  
    global class Item {
        String itemName;        String itemDescription;     String itemQuantity;    String itemPrice;       String itemTax;
        String itemDisc;        String itemAmount;          String startDate;       String endDate;
        
        public Item(OpportunityLineItem opptyItem) {
            this.itemName = opptyItem.Product2.Name;
            this.itemDescription = opptyItem.Description;
            this.itemQuantity = String.valueOf(opptyItem.Quantity);
            this.itemPrice = String.valueOf(opptyItem.UnitPrice.setScale(2));
            this.itemTax = String.valueOf(opptyItem.Tax_Amount__c);
            this.itemDisc = String.valueOf(opptyItem.Discount_Amount__c);
            this.itemAmount = String.valueOf(opptyItem.Gross_amount__c.setScale(2));
            this.startDate = String.valueOf(opptyItem.Start_Date__c);
            this.endDate = String.valueOf(opptyItem.End_Date__c);
        }
    }
    /*------------------------------------------------------------
Author      : Thinh Ho
Company     : Viseo Asia PTE LTD
Description : Wrapper class to store Salesforce fields in Quote data_flow JSON request.
Inputs      : String Opportunity <StageName>
History
<Date>      <Authors Name>     <Brief Description of Change>
------------------------------------------------------------*/  
    global class OpptyInterface {
        String opportunityId;
        String paymentTime;
        String paymentMethod;
        String agentAcceptedTime;
    }
}