unpackaged/main/default/objects/Account/fields/Agency_Id__c.field-meta.xml
<CustomField>
    <fullName>Agency_Id__c</fullName>
    <description>Denotes the unique id of an agency in PG system</description>
    <externalId>true</externalId>
    <inlineHelpText>Denotes the unique id of an agency in PG system</inlineHelpText>
    <label>Agency Id</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/CEA_License__c.field-meta.xml
<CustomField>
    <fullName>CEA_License__c</fullName>
    <description>Denotes the agency license number registered under a governing authority</description>
    <externalId>true</externalId>
    <inlineHelpText>Denotes the agency registration number issued by CEA for SG agencies and MIEA for MY agencies</inlineHelpText>
    <label>Agency Identification Number</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/Customer_Type__c.field-meta.xml
<CustomField>
    <fullName>Customer_Type__c</fullName>
    <description>Created a custom field as standard field &#39;Type&#39; cannot be mapped in lead mapping</description>
    <label>Customer Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Agent</fullName>
            </value>
            <value>
                <fullName>Owner</fullName>
            </value>
            <value>
                <fullName>Agency</fullName>
            </value>
            <value>
                <fullName>Developer</fullName>
                <default>true</default>
                <label>Developer</label>
            </value>
            <value>
                <fullName>Non-Property</fullName>
            </value>
            <value>
                <fullName>Consumer</fullName>
            </value>
            <value>
                <fullName>Media Agency</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Account/recordTypes/Agency.recordType-meta.xml
<RecordType>
    <fullName>Agency</fullName>
    <active>true</active>
    <label>Agency</label>
</RecordType>

unpackaged/main/default/objects/Media__c/Media__c.object-meta.xml
<CustomObject>
    <label>Media</label>
    <nameField>
        <displayFormat>M-{0000000}</displayFormat>
        <label>Agency Logo Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Media</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Media__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Denotes the account to which record is bind to</description>
    <inlineHelpText>Denotes the account to which record is bind to</inlineHelpText>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>Agency_Logo</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/classes/UploadAgencyLogoCont_Test.cls
@isTest
public class UploadAgencyLogoCont_Test {
    public static testMethod void unitTest(){
      PGTestDataFactory_v2.CreateTriggerExecuteCS('PGAccountTrigger',true);
        String accRectype2 = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Agency').getRecordTypeId();
        Account a = new Account();
        a.RecordTypeId = accRectype2;
        a.Name = 'Unit Test Agency';
        a.Customer_Type__c = 'Agency';
        a.Agency_Id__c = '1234';
        a.CEA_License__c = 'Test';
        insert a;
        
        Account a2 = new Account();
        a2.RecordTypeId = accRectype2;
        a2.Name = 'Unit Test Agency';
        a2.Customer_Type__c = 'Agency';
        a2.Agency_Id__c = '1234';
        a2.CEA_License__c = 'Test';
        insert a2;
        
        
        RestRequest req = new RestRequest(); 
        RestResponse res = new RestResponse();
        media__c media = new media__c ();
        media.isActive__c= true; 
        media.Account__c=a.Id ;
                insert media ; 

        
        
        
         media__c media2 = new media__c ();
        media2.isActive__c= true; 
        media2.Account__c=a.Id ;
        
        
        
       
     
        insert media2 ; 
       
        ContentVersion cv = new ContentVersion();
        cv.versionData =  blob.valueOf('test');
        cv.title ='TEST_FILE1.png' ;
        cv.pathOnClient ='TEST_FILE1.png' ;
        cv.FirstPublishLocationId = media.Id;
        
        insert cv;
        List<ContentDocument> documents = [SELECT Id, Title, LatestPublishedVersionId FROM ContentDocument];
        
        //create ContentDocumentLink  record 
        ContentDocumentLink cdl = New ContentDocumentLink();
        cdl.LinkedEntityId = media2.id;
        cdl.ContentDocumentId = documents[0].Id;
        cdl.shareType = 'V';
        insert cdl;
        
        
        
        
        req.requestURI = '/services/apexrest/api/agency/logo?id='+a.id;  
        req.httpMethod = 'GET';
        req.addParameter('id', a.id);
        RestContext.request = req;
        RestContext.response= res;
        
        AgencyAPI_Logo.getAgencyLogo();
        
        test.startTest();
             id m=  UploadAgencyLogoCont.createAgencyLogo(a.Id);
        UploadAgencyLogoCont.getActiveContentDoc(a.Id);
         UploadAgencyLogoCont.getActiveContentDoc(a2.Id);

      boolean b=  UploadAgencyLogoCont.notifyBiforst(a2.Id,m); 
        test.stopTest();

            
        
    }
}