unpackaged/main/default/objects/Account/fields/Agency_Id__c.field-meta.xml
<CustomField>
    <fullName>Agency_Id__c</fullName>
    <description>Denotes the unique id of an agency in PG system</description>
    <externalId>true</externalId>
    <inlineHelpText>Denotes the unique id of an agency in PG system</inlineHelpText>
    <label>Agency Id</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/Country__c.field-meta.xml
<CustomField>
    <fullName>Country__c</fullName>
    <defaultValue>if(  BEGINS($UserRole.Name, &quot;TH&quot;),&quot;Thailand&quot;,if(ISPICKVAL($User.Subsidiary__c,&quot;MyProperty Data Sdn. Bhd.&quot;),&quot;Malaysia&quot;,&quot;&quot;))</defaultValue>
    <description>Denotes the country of an account</description>
    <inlineHelpText>Denotes the country of an account</inlineHelpText>
    <label>Country</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Country</valueSetName>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Account/recordTypes/Agency.recordType-meta.xml
<RecordType>
    <fullName>Agency</fullName>
    <active>true</active>
    <label>Agency</label>
</RecordType>

unpackaged/main/default/objects/Media__c/Media__c.object-meta.xml
<CustomObject>
    <label>Media</label>
    <nameField>
        <displayFormat>M-{0000000}</displayFormat>
        <label>Agency Logo Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Media</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Media__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Denotes the account to which record is bind to</description>
    <inlineHelpText>Denotes the account to which record is bind to</inlineHelpText>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>Agency_Logo</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/classes/UploadAgencyLogoCont.cls
public class UploadAgencyLogoCont {
    //This method is used to get Id of media object to file upload component.
    @AuraEnabled
    public static Id createAgencyLogo(Id accId){
        Media__c objLogo=new Media__c();
        if(accId !=null){
            objLogo.Account__c=accId;
            insert objLogo;
        }
        return objLogo.Id;
    }
    //This method is used in ShowAgencyLogo.cmp component for displaying Agency Logo Images on detail page
    @AuraEnabled
    public static List<ContentVersion> getActiveContentDoc(Id accId){
        system.debug('--accId--'+accId);
        List<Media__c> lstmedia=[SELECT Id,Account__r.Agency_Id__c,createdDate FROM Media__c where isActive__c=true and Account__c=:accId order By createdDate Desc limit:1];
        if(lstmedia.size()>0){
        ContentDocumentLink ObjContentDoc = [SELECT Id, LinkedEntityId, ContentDocumentId FROM ContentDocumentLink where LinkedEntityId=:lstmedia[0].Id];
        List<Contentversion> attach=[SELECT Id,Title,ContentDocumentId FROM ContentVersion where ContentDocumentId=:ObjContentDoc.ContentDocumentId];
        return attach;
        }else{
            return null;
        }
            
    }
    // Call Biforst After file successufully uploaded in Media Object
    @AuraEnabled
    public static Boolean notifyBiforst(Id accId,Id mediaId){
        String RootEndpoint, RootEndpoint_Key;
        List<Media__c> inactiveListMedia=[select Id, Account__c,isActive__C from Media__c where Account__c=:accId AND Id <>:mediaId AND isActive__C=true];
        Map<string, string> mapCountryCode = EligibilityHandler.getMapCountryCode();
        system.debug('--inactiveListMedia--'+inactiveListMedia);
        system.debug('--mediaId--'+mediaId);
        Map<string,string> reqHeaders = new Map<string,string>();
        
        if (runningInASandbox()) {
            RootEndpoint = label.PG_LABEL_SendNotifyEndpoint_SB; 
            RootEndpoint_Key = label.PG_LABEL_sendNotifyKey_SB;
        }
        else{
            RootEndpoint = label.PG_LABEL_SendNotifyEndpoint;
            RootEndpoint_Key = label.PG_LABEL_sendNotifyKey; 
        }
        
        reqHeaders.put('Content-Type', 'application/json');
        reqHeaders.put('x-api-key', RootEndpoint_Key);
        reqHeaders.put('Content-Type', 'application/json');
        
        List <Account> acctoSend = new list<Account>();
        acctoSend = [SELECT Id, Country__c, Agency_Id__c  from Account where id  =: accId];
        AgencyLogo objlogo= new AgencyLogo();
        objlogo.id = acctoSend[0].id;
        objlogo.region = mapCountryCode.get(acctoSend[0].Country__c.toLowerCase());
        string requestt = system.JSON.serialize(objlogo);
        
        HTTPResponse res = GenricClassForCallout.GenericbasicAuthCallout(reqHeaders,RootEndpoint,requestt,'POST',true,false,null,null);
        if(!Test.isRunningTest() && res.getStatusCode() == 200){
            If(inactiveListMedia.size()>0){
                for(Media__c each :inactiveListMedia){
                    each.isActive__c=false;
                }
                Update inactiveListMedia;
            }
            if(mediaId !=null){
                Media__c objMedia=new Media__c(Id=mediaId,isActive__c=true);
                Update objMedia;
                system.debug('--objMedia--'+objMedia);
            }
            return true;
        }
        return false;
    }
    //This method is used to check if code execution is from sandbox environment or production
    public static Boolean runningInASandbox() {
        return [SELECT IsSandbox FROM Organization LIMIT 1].IsSandbox;
    }
    public class AgencyLogo { 
        String id;     String region= '';     String entity = 'media' ;        String origin = 'sfsc';  
    }
}