unpackaged/main/default/objects/Account/fields/AgentKey__c.field-meta.xml
<CustomField>
    <fullName>AgentKey__c</fullName>
    <description>Denotes a unique key specifying the countrycodes(SG,MY,TH,ID) and the unique id in PG system</description>
    <externalId>true</externalId>
    <inlineHelpText>Denotes a unique key specifying the countrycodes(SG,MY,TH,ID) and the unique id in PG system</inlineHelpText>
    <label>AgentKey</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/Country__c.field-meta.xml
<CustomField>
    <fullName>Country__c</fullName>
    <defaultValue>if(  BEGINS($UserRole.Name, &quot;TH&quot;),&quot;Thailand&quot;,if(ISPICKVAL($User.Subsidiary__c,&quot;MyProperty Data Sdn. Bhd.&quot;),&quot;Malaysia&quot;,&quot;&quot;))</defaultValue>
    <description>Denotes the country of an account</description>
    <inlineHelpText>Denotes the country of an account</inlineHelpText>
    <label>Country</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Country</valueSetName>
    </valueSet>
</CustomField>

unpackaged/main/default/classes/BatchToUpdateEcommField.cls
global class BatchToUpdateEcommField  implements Database.batchable<Sobject> {
    global Database.QueryLocator start(Database.BatchableContext bc)
    {
        String s='';
        if(test.isRunningTest()){
            s='SELECT Id, csb2c__E_Commerce_Customer_Id__c,Agentkey__c  FROM Account where recordType.name=\'Agent\' and csb2c__E_Commerce_Customer_Id__c=null and country__c=\'Singapore\'';
        }
        else 
            s= Label.PG_LABEL_BatchToUpdateEcommFieldQuery;
        System.debug(s);
        return Database.getQueryLocator(s);
        
    }
    global void execute(Database.BatchableContext bc, List<Account> accList )
        
    {
        System.debug('@@@'+ accList);
        
        for(Account acc : accList) {        
            // Update the Account Name 
            acc.csb2c__E_Commerce_Customer_Id__c = acc.Agentkey__c ;
        }
        try{
            update accList;
            //System.debug(accList);
             
            
        } catch(Exception e) {
            System.debug(e);
        }
        
    }    
    global void finish(Database.BatchableContext bc)
    {
        
    }     
    
}