unpackaged/main/default/objects/Account/fields/Approval_Status__c.field-meta.xml
<CustomField>
    <fullName>Approval_Status__c</fullName>
    <description>Denotes the approval status for an agent in the VIP approval process</description>
    <inlineHelpText>Denotes the approval status for an agent in the VIP approval process</inlineHelpText>
    <label>Approval Status</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/Customer_Type__c.field-meta.xml
<CustomField>
    <fullName>Customer_Type__c</fullName>
    <description>Created a custom field as standard field &#39;Type&#39; cannot be mapped in lead mapping</description>
    <label>Customer Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Agent</fullName>
            </value>
            <value>
                <fullName>Owner</fullName>
            </value>
            <value>
                <fullName>Agency</fullName>
            </value>
            <value>
                <fullName>Developer</fullName>
                <default>true</default>
                <label>Developer</label>
            </value>
            <value>
                <fullName>Non-Property</fullName>
            </value>
            <value>
                <fullName>Consumer</fullName>
            </value>
            <value>
                <fullName>Media Agency</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Account/fields/Loyalty_Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Loyalty_Start_Date__c</fullName>
    <description>Denotes the loyalty start date of an agent</description>
    <inlineHelpText>Denotes the loyalty start date of an agent</inlineHelpText>
    <label>Loyalty Start Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/Account/recordTypes/Agency.recordType-meta.xml
<RecordType>
    <fullName>Agency</fullName>
    <active>true</active>
    <label>Agency</label>
</RecordType>

unpackaged/main/default/objects/LSD_Update__c/LSD_Update__c.object-meta.xml
<CustomObject>
    <description>Used to update the loyalty start date</description>
    <label>LSD Update</label>
    <nameField>
        <displayFormat>LU-{000000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>LSD Updates</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/LSD_Update__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>Loyalty_Start_Dates</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/LSD_Update__c/fields/Approval_Status__c.field-meta.xml
<CustomField>
    <fullName>Approval_Status__c</fullName>
    <label>Approval Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Submit for approval</fullName>
            </value>
            <value>
                <fullName>Not Required</fullName>
                <default>true</default>
                <label>Not Required</label>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/LSD_Update__c/fields/Loyalty_Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Loyalty_Start_Date__c</fullName>
    <label>Loyalty Start Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/Trigger_Execute__c/Trigger_Execute__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>Trigger Execute</label>
</CustomObject>

unpackaged/main/default/objects/Trigger_Execute__c/fields/Enable_del__c.field-meta.xml
<CustomField>
    <fullName>Enable_del__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Enable del</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/classes/LSDUpdateTriggerHandler_Test.cls
@isTest
public class LSDUpdateTriggerHandler_Test {
    public static testmethod  void Method1(){
        
        Test.startTest();
        Trigger_Execute__c TE1 = new Trigger_Execute__c();
        TE1.Name = 'PGAccountTrigger';
        TE1.Enable_del__c = true;
        insert TE1;
        
        Map<Id,Id> accmap = new Map<Id,Id>();
        Account act =new Account();
        act.Name='HelloTest';
        act.Customer_Type__c='Agency';
        act.CurrencyIsoCode='EUR';
        insert act;
        
        Trigger_Execute__c TE = new Trigger_Execute__c();
        TE.Name = 'PGLSDUpdateTrigger';
        TE.Enable_del__c = true;
        insert TE;
        
        Map< Id,LSD_Update__c> lsdoldmap = new Map< Id,LSD_Update__c>();
        List< LSD_Update__c> lsdlist = new List< LSD_Update__c>();
        LSD_Update__c lsd = new LSD_Update__c();
        lsd.Approval_Status__c ='Submit for approval';
        lsd.Account__c =act.id;
        lsd.Loyalty_Start_Date__c = system.today();
        insert lsd;
        lsdlist.add(lsd);
        lsdoldmap.put(lsd.id,lsd);
        lsd.Loyalty_Start_Date__c =system.today().adddays(1);
        lsd.Approval_Status__c ='Approved';
        update lsd;
        test.stopTest();
    }    
}