unpackaged/main/default/objects/Account/fields/Approval_Status__c.field-meta.xml
<CustomField>
    <fullName>Approval_Status__c</fullName>
    <description>Denotes the approval status for an agent in the VIP approval process</description>
    <inlineHelpText>Denotes the approval status for an agent in the VIP approval process</inlineHelpText>
    <label>Approval Status</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/Subscription_End_Date__c.field-meta.xml
<CustomField>
    <fullName>Subscription_End_Date__c</fullName>
    <description>Denotes end date of an agent&#39;s current subscriptions</description>
    <inlineHelpText>Denotes end date of an agent&#39;s current subscriptions</inlineHelpText>
    <label>Subscription End Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Approval_Status__c.field-meta.xml
<CustomField>
    <fullName>Approval_Status__c</fullName>
    <label>Approval Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Discount Approval Submitted</fullName>
            </value>
            <value>
                <fullName>Discount Approval Approved</fullName>
            </value>
            <value>
                <fullName>Discount Approval Rejected</fullName>
            </value>
            <value>
                <fullName>Re-submit Discount Approval</fullName>
            </value>
            <value>
                <fullName>Awaits OMC Approval</fullName>
            </value>
            <value>
                <fullName>OMC Approval Submitted</fullName>
            </value>
            <value>
                <fullName>OMC Approval Approved</fullName>
            </value>
            <value>
                <fullName>OMC Approval Recalled</fullName>
            </value>
            <value>
                <fullName>OMC Approval Rejected</fullName>
            </value>
            <value>
                <fullName>Not Required</fullName>
            </value>
            <value>
                <fullName>NS Order Generated</fullName>
            </value>
            <value>
                <fullName>Product Owner Approved</fullName>
            </value>
            <value>
                <fullName>Director Approved</fullName>
            </value>
            <value>
                <fullName>Country Manager Approved</fullName>
            </value>
            <value>
                <fullName>CBO Approved</fullName>
            </value>
            <value>
                <fullName>Discount Approval Required</fullName>
                <isActive>false</isActive>
                <label>Discount Approval Required</label>
            </value>
            <value>
                <fullName>Manager Approved</fullName>
                <isActive>false</isActive>
                <label>Manager Approved</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/ByAuto__c.field-meta.xml
<CustomField>
    <fullName>ByAuto__c</fullName>
    <defaultValue>false</defaultValue>
    <label>ByAuto</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Loss_Reason__c.field-meta.xml
<CustomField>
    <fullName>Loss_Reason__c</fullName>
    <label>Loss Reason</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>StageName</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>No Payment</fullName>
            </value>
            <value>
                <fullName>Not Interested</fullName>
            </value>
            <value>
                <fullName>Unable to reach (at least 5 attempts)</fullName>
            </value>
            <value>
                <fullName>Already Renewed/Purchased/Registered/Bosted</fullName>
            </value>
            <value>
                <fullName>Already Renewed - VIP</fullName>
            </value>
            <value>
                <fullName>Payment Expired</fullName>
            </value>
            <value>
                <fullName>Lost to Competitor</fullName>
            </value>
            <value>
                <fullName>Price</fullName>
            </value>
            <value>
                <fullName>Product Features</fullName>
            </value>
            <value>
                <fullName>Project Abandoned</fullName>
            </value>
            <value>
                <fullName>No Budget / Lost Funding</fullName>
            </value>
            <value>
                <fullName>Wrong Number</fullName>
            </value>
            <value>
                <fullName>DO NOT CALL list</fullName>
            </value>
            <value>
                <fullName>Not Eligible</fullName>
            </value>
            <value>
                <fullName>Duplicate Record</fullName>
            </value>
            <value>
                <fullName>Agent is suspended or cancelled</fullName>
            </value>
            <value>
                <fullName>Project Completed / Completing</fullName>
            </value>
            <value>
                <fullName>Project Delayed</fullName>
            </value>
            <value>
                <fullName>Decision Maker Uncontactable</fullName>
            </value>
            <value>
                <fullName>Current System Sufficient</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Order_Type_Clone__c.field-meta.xml
<CustomField>
    <fullName>Order_Type_Clone__c</fullName>
    <label>Order Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Contract - New</fullName>
            </value>
            <value>
                <fullName>Contract - Upsell</fullName>
            </value>
            <value>
                <fullName>Contract - Renewal</fullName>
            </value>
            <value>
                <fullName>Contract - Make Good</fullName>
            </value>
            <value>
                <fullName>Dual-SO</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Subscription_End_Date__c.field-meta.xml
<CustomField>
    <fullName>Subscription_End_Date__c</fullName>
    <label>Subscription End Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/recordTypes/B2C.recordType-meta.xml
<RecordType>
    <fullName>B2C</fullName>
    <active>true</active>
    <businessProcess>B2C</businessProcess>
    <description>B2C Opportunity Record</description>
    <label>B2C</label>
</RecordType>

unpackaged/main/default/classes/CloseRenewalOpportunity_Batch.cls
/*------------------------------------------------------------
Author      : Steven Junaidy
Company     : Viseo Asia PTE LTD
Description : Batch job to 
History

<Date>      <Authors Name>     <Brief Description of Change>
------------------------------------------------------------*/
global class CloseRenewalOpportunity_Batch implements Database.Batchable<sObject>{
    global date todayDate = date.today();
    string query ;
    boolean isExpired = false;
    global CloseRenewalOpportunity_Batch(){
        this.query = 'SELECT id,Recordtypeid,Approval_Status__c,byAuto__c,Account.Subscription_End_Date__c, StageName, Loss_Reason__c,closeDate FROM Opportunity WHERE (StageName = \'new\' or StageName = \'Proposal\') and Order_Type_Clone__c = \'Contract - Renewal\'' ;
        system.debug(query);
    }
    global System.Iterable<sObject> start(Database.BatchableContext jobId) {
        return Database.getQueryLocator(query);
    }
    
    global Void execute(Database.BatchableContext jobId, List<sObject> recordList) {
        List<Opportunity> ToUpdateOpp = new List<Opportunity>();
        Map<String,String> MapOppRT = new Map<String,String>();
        System.debug(recordList);
        for (RecordType rt : [SELECT Id,Name FROM RecordType WHERE SObjectType='Opportunity']){
            MapOppRT.put(rt.Name,rt.Id);
        } 
        for(sObject obj : recordList) {
            Opportunity Opp = (Opportunity)obj;
            if (Opp.recordtypeid == mapOppRT.get('B2C') && todayDate >= Opp.CloseDate){
               System.debug(Opp.iD + ' Closed Lost');
                Opp.StageName = 'Closed Lost';
                Opp.Loss_Reason__c = 'Expired Offer';
                Opp.byAuto__c = true;
                ToUpdateOpp.add(Opp);
            }      
        }
        if(toUpdateOpp.size()>0){
            system.debug('Update');
            Update toUpdateOpp;
        }
    }
    global Void finish(Database.BatchableContext jobId) {
    }
}