unpackaged/main/default/objects/Account/fields/Approval_Status__c.field-meta.xml
<CustomField>
    <fullName>Approval_Status__c</fullName>
    <description>Denotes the approval status for an agent in the VIP approval process</description>
    <inlineHelpText>Denotes the approval status for an agent in the VIP approval process</inlineHelpText>
    <label>Approval Status</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/Loyalty_Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Loyalty_Start_Date__c</fullName>
    <description>Denotes the loyalty start date of an agent</description>
    <inlineHelpText>Denotes the loyalty start date of an agent</inlineHelpText>
    <label>Loyalty Start Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/LSD_Update__c/LSD_Update__c.object-meta.xml
<CustomObject>
    <description>Used to update the loyalty start date</description>
    <label>LSD Update</label>
    <nameField>
        <displayFormat>LU-{000000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>LSD Updates</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/LSD_Update__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>Loyalty_Start_Dates</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/LSD_Update__c/fields/Approval_Status__c.field-meta.xml
<CustomField>
    <fullName>Approval_Status__c</fullName>
    <label>Approval Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Submit for approval</fullName>
            </value>
            <value>
                <fullName>Not Required</fullName>
                <default>true</default>
                <label>Not Required</label>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/LSD_Update__c/fields/Loyalty_Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Loyalty_Start_Date__c</fullName>
    <label>Loyalty Start Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/classes/newLSDUpdaterequestController.cls
public class newLSDUpdaterequestController {
    /**
*  Method used to validate that only 1 request is made at a time
*  @name validateApprovalCap
*  @param List<LSD_Update__c>, Map<Id,LSD_Update__c>
*  @return void
*/
    @AuraEnabled(cacheable = true)
    public static LightningResponse validateApprovalCap(String accId) {
        try {
            WrapResponse objResponse = calculateInputFields(accId);
            return new LightningResponse(true, 'Success', JSON.serialize(objResponse));   
        } catch (Exception ex) {
            return new LightningResponse(false, ex.getMessage(), '');
        }
    } 
    public static WrapResponse calculateInputFields (String accId){
        Account acc = [SELECT Loyalty_Start_Date__c from Account where Id =: accId];
        Id currentUserId = UserInfo.getUserId();
        Boolean hasAccess = [SELECT RecordId, HasEditAccess FROM UserRecordAccess WHERE UserId =: currentUserId AND RecordId =: accId].HasEditAccess;
        WrapResponse wrapRes = new WrapResponse();
        wrapRes.loyaltyStartDate = acc.Loyalty_Start_Date__c;
        
        List<LSD_Update__c> LSDSubmitted = [SELECT Id,Approval_Status__c FROM LSD_Update__c WHERE Approval_Status__c ='Submit for approval' and account__C =:accId];
        
        if(LSDSubmitted.size() >=1 || !hasAccess) {
            wrapRes.allowRequest = false;
        }else{
            wrapRes.allowRequest = true;
        }
        
        return wrapRes;
    }
    
    public class WrapResponse {
        @AuraEnabled
        public date loyaltyStartDate;
        @AuraEnabled
        public boolean allowRequest;
    } 
     
}