unpackaged/main/default/objects/Account/fields/Approval_Status__c.field-meta.xml
<CustomField>
    <fullName>Approval_Status__c</fullName>
    <description>Denotes the approval status for an agent in the VIP approval process</description>
    <inlineHelpText>Denotes the approval status for an agent in the VIP approval process</inlineHelpText>
    <label>Approval Status</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/Loyalty_Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Loyalty_Start_Date__c</fullName>
    <description>Denotes the loyalty start date of an agent</description>
    <inlineHelpText>Denotes the loyalty start date of an agent</inlineHelpText>
    <label>Loyalty Start Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/LSD_Update__c/LSD_Update__c.object-meta.xml
<CustomObject>
    <description>Used to update the loyalty start date</description>
    <label>LSD Update</label>
    <nameField>
        <displayFormat>LU-{000000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>LSD Updates</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/LSD_Update__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>Loyalty_Start_Dates</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/LSD_Update__c/fields/Approval_Status__c.field-meta.xml
<CustomField>
    <fullName>Approval_Status__c</fullName>
    <label>Approval Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Submit for approval</fullName>
            </value>
            <value>
                <fullName>Not Required</fullName>
                <default>true</default>
                <label>Not Required</label>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/LSD_Update__c/fields/Loyalty_Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Loyalty_Start_Date__c</fullName>
    <label>Loyalty Start Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/classes/BatchToUpdateAccountLSD.cls
public class BatchToUpdateAccountLSD implements Database.Batchable<sObject>{
    
    public database.QueryLocator start(database.BatchableContext BC){
        String query;
        query = 'select Id,Loyalty_Start_Date__c,(select Account__c  from Loyalty_Start_Dates__r ORDER by Loyalty_Start_Date__c desc) from Account';  
        return Database.getQueryLocator(query);
    }
    public void execute(database.BatchableContext BC,list<Account> scope){
       
        set<Id> accIds = new set<Id>();
        list<Account> accList2Update = new List<Account>();
        Map<String,DateTime> accIdVsLSDDate = new Map<String,DateTime>();
        for(Account acc : scope)
        {
            if(!acc.Loyalty_Start_Dates__r.IsEmpty())
            {
                accIds.add(acc.id);
            }  
        }

        for(LSD_Update__c lsd : [select Id,Loyalty_Start_Date__c,Account__r.Loyalty_Start_Date__c,Account__c,
                                 LastModifiedById,Approval_Status__c from LSD_Update__c where Account__c In : accIds 
                                 AND LastModifiedById =: System.Label.Batch_To_Update_LSD_User_ID.split(';') 
                                 AND Approval_Status__c = 'Approved' ORDER by Loyalty_Start_Date__c desc limit 1])
        {
            if(!accIdVsLSDDate.containskey(lsd.Account__c)) 
            {
                accIdVsLSDDate.put(lsd.Account__c,lsd.Loyalty_Start_Date__c);
            }
        }
        
        for(Account accObj:[SELECT ID,Loyalty_Start_Date__c FROM Account Where id In:accIdVsLSDDate.keyset()]){
            accObj.Loyalty_Start_Date__c = Date.valueof(accIdVsLSDDate.get(accObj.id));
            accList2Update.add(accObj);
        }
        
        if(!accList2Update.isEmpty()){
            Update accList2Update;
        }
        
    }
    public void finish(database.BatchableContext BC){
        
    }
    
}