unpackaged/main/default/objects/Account/fields/Birthdate_Verified__c.field-meta.xml
<CustomField>
    <fullName>Birthdate_Verified__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Denotes whether the birthdate of an agent is verified by PG</description>
    <inlineHelpText>Denotes whether the birthdate of an agent is verified by PG</inlineHelpText>
    <label>Birthdate Verified</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>Denotes the status of an agent in the agent lifecycle</description>
    <inlineHelpText>Denotes the status of an agent in the agent lifecycle</inlineHelpText>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Trial</fullName>
            </value>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Downgraded</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Suspended</fullName>
            </value>
            <value>
                <fullName>Expired</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Activity__c/Activity__c.object-meta.xml
<CustomObject>
    <label>Activity</label>
    <nameField>
        <label>Activity Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Activities</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Activity__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Activities</relationshipLabel>
    <relationshipName>Activities</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Activity__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Verified</fullName>
            </value>
            <value>
                <fullName>Unverified</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Activity__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Birthday verification</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/classes/BatchToCreateActivityForContact.cls
//BatchToCreateActivityForContact_Test
public class BatchToCreateActivityForContact implements Database.Batchable<sObject>{
	
    public Database.QueryLocator start(Database.BatchableContext BC)  {
        
        String statusAct = 'Verified';
        String typeAct = 'Birthday verification';
        return Database.getQueryLocator('select id,Account.Birthdate_Verified__c,(Select id,Status__c,Type__c from Activities__r where Status__c =: statusAct AND Type__c =: typeAct ) from Contact where Account.Birthdate_Verified__c = true');
    }   
    
    public void execute(Database.BatchableContext BC, List<Contact> conList) {
        list<Activity__c> actListToInsert = new list<Activity__c>();
        for(Contact con: conList){
            if(con.Activities__r.isEmpty()){
                Activity__c act = new Activity__c();
                act.Type__c = 'Birthday verification';
                act.Status__c = 'Verified';
                act.Description__c = 'Updated from Script';
                act.Contact__c = con.id;
                actListToInsert.add(act);
            }
        }
        if(!actListToInsert.isEmpty())
            insert actListToInsert;
    }
    
    public void finish(Database.BatchableContext BC) {
        
    }
}