unpackaged/main/default/objects/Account/fields/Confirmation_Date__c.field-meta.xml
<CustomField>
    <fullName>Confirmation_Date__c</fullName>
    <description>Denotes the date when an agent has confirmed his/her identity using email and SMS verification with PG</description>
    <inlineHelpText>Denotes the date when an agent has confirmed his/her identity using email and SMS verification with PG</inlineHelpText>
    <label>Confirmation Date</label>
    <type>DateTime</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>Denotes the status of an agent in the agent lifecycle</description>
    <inlineHelpText>Denotes the status of an agent in the agent lifecycle</inlineHelpText>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Trial</fullName>
            </value>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Downgraded</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Suspended</fullName>
            </value>
            <value>
                <fullName>Expired</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/classes/BatchToUpdateConfirmationDate.cls
public class BatchToUpdateConfirmationDate implements DataBase.Batchable<Sobject>{
    
    public DataBase.QueryLocator start(DataBase.BatchableContext Bc){
        
        
        String trialStr = 'Trial';
        String pendingStr = 'Pending';
        String query = 'select id,CreatedDate,Confirmation_Date__c, (select CreatedDate, Id, OldValue, NewValue, AccountId from Histories where Field= \'Status__c\' ) from Account where RecordType.DeveloperName= \'Agent\' AND  Confirmation_Date__c = null order by createdDate desc';
        return DataBase.getQueryLocator(query);
    }
    
    public void execute(DataBase.BatchableContext Bc,List<Account> accList){
        for(Account ac : accList){
            ac.Confirmation_Date__c = ac.CreatedDate;
            for(AccountHistory ah : ac.Histories){
                if(ah.OldValue == 'Pending' && ah.NewValue == 'Trial'){
                    ac.Confirmation_Date__c = ah.CreatedDate;     
                }    
                                
            }
        }
        update accList;
    }
    public void finish(DataBase.BatchableContext Bc){
        
    }
}