unpackaged/main/default/objects/Account/fields/Corporate_Brand_Name__c.field-meta.xml
<CustomField>
    <fullName>Corporate_Brand_Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>This is the main brand of this advertiser. Volvo Corporation AB would probably have Volvo as the brand name.</inlineHelpText>
    <label>Corporate Brand Name</label>
    <referenceTo>Corporate_Brand_Name__c</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/Industry_Tier_2__c.field-meta.xml
<CustomField>
    <fullName>Industry_Tier_2__c</fullName>
    <description>Tier 2 (Lower) Industry Catagories</description>
    <label>Industry (Tier 2)</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Industry</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>Adult Beverages</fullName>
            </value>
            <value>
                <fullName>Alcoholic Beverages</fullName>
            </value>
            <value>
                <fullName>Appliances</fullName>
            </value>
            <value>
                <fullName>Artist/Band</fullName>
            </value>
            <value>
                <fullName>Automotive</fullName>
            </value>
            <value>
                <fullName>Auto Parts Retailers</fullName>
            </value>
            <value>
                <fullName>Banking</fullName>
            </value>
            <value>
                <fullName>Banks</fullName>
            </value>
            <value>
                <fullName>Big Box Retail</fullName>
            </value>
            <value>
                <fullName>Big-Box Retail</fullName>
            </value>
            <value>
                <fullName>Brands/OEM</fullName>
            </value>
            <value>
                <fullName>Chemicals</fullName>
            </value>
            <value>
                <fullName>Commercial Vechicles</fullName>
            </value>
            <value>
                <fullName>Commercial Vehicles</fullName>
            </value>
            <value>
                <fullName>Concert</fullName>
            </value>
            <value>
                <fullName>Consumer Electronics</fullName>
            </value>
            <value>
                <fullName>Consumer Electronics/Computing Products</fullName>
            </value>
            <value>
                <fullName>Creative Agency</fullName>
            </value>
            <value>
                <fullName>Credit Cards</fullName>
            </value>
            <value>
                <fullName>Dealerships</fullName>
            </value>
            <value>
                <fullName>Dealerships/LMAs</fullName>
            </value>
            <value>
                <fullName>Digital Media</fullName>
            </value>
            <value>
                <fullName>eCommerce</fullName>
            </value>
            <value>
                <fullName>E-Commerce</fullName>
            </value>
            <value>
                <fullName>Education</fullName>
            </value>
            <value>
                <fullName>Fashion/Apparel</fullName>
            </value>
            <value>
                <fullName>Fashon/Apparel</fullName>
            </value>
            <value>
                <fullName>Festival</fullName>
            </value>
            <value>
                <fullName>Festivals</fullName>
                <label>Festivals/Concerts</label>
            </value>
            <value>
                <fullName>Film</fullName>
            </value>
            <value>
                <fullName>Media Agency</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Account/recordTypes/Agency.recordType-meta.xml
<RecordType>
    <fullName>Agency</fullName>
    <active>true</active>
    <label>Agency</label>
</RecordType>

unpackaged/main/default/objects/Corporate_Brand_Name__c/Corporate_Brand_Name__c.object-meta.xml
<CustomObject>
    <label>Corporate Brand Name</label>
    <nameField>
        <label>Corporate Brand Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Corporate Brand Names</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Corporate_Brand_Name__c/fields/Global_Customer_Segment__c.field-meta.xml
<CustomField>
    <fullName>Global_Customer_Segment__c</fullName>
    <label>Demand Channel</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Advertiser</fullName>
            </value>
            <value>
                <fullName>Agency</fullName>
            </value>
            <value>
                <fullName>Reseller</fullName>
            </value>
            <value>
                <fullName>Label</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/classes/CS_th_Account.cls
/**
 * @name CS_th_Account
 * @description Factory class for Account object
 * @revision
 *
 */
@IsTest
public class CS_th_Account {
	/**
	 * Create an account for test
	 * @param  name String
	 * @return      Account
	 */
	public static Account create(String name) {
		return create(name, true);
	}

	/**
	 * Create an account for test
	 * @param  name         String
	 * @param  insertRecord Boolean
	 * @return              Account
	 */
	public static Account create(String name, Boolean insertRecord) {
		Id recordTypeId = CS_utl_RecordType.getRecordTypesById(Account.getSObjectType()).values().get(0).getRecordTypeId();
		return create(name, recordTypeId, insertRecord);
	}

	/**
	 * Create an account for test
	 * @param  name         String
	 * @param  recordTypeId Id
	 * @param  insertRecord Boolean
	 * @return              Account
	 */
	public static Account create(String name, Id recordTypeId, Boolean insertRecord) {
        TestDataSetupBasic.insertPGAccountTrigger();

		String randomNumber = String.valueOf(Integer.valueOf((Math.random() * 100)));
		Corporate_Brand_Name__c corporateBrandName = new Corporate_Brand_Name__c();

		List<Corporate_Brand_Name__c> corporateBrandNameList = [SELECT Id FROM Corporate_Brand_Name__c];
		if (corporateBrandNameList.size() > 0) {
			corporateBrandName = corporateBrandNameList[0];
		} else {
			corporateBrandName = new Corporate_Brand_Name__c(Name = 'Test Corporate Brand Name ' + randomNumber,
					Global_Customer_Segment__c = 'Advertiser');
			insert corporateBrandName;
		}

		Account account = new Account(
                Name = name,
				Phone = '12345',
				BillingStreet = 'Test Street',
				BillingCity = 'City',
				BillingPostalCode = '10000',
				BillingCountry = 'United States',
				BillingCountryCode = 'US',
				RecordTypeId = recordTypeId,
				Website = 'www.cloudsense.com',
				Industry = 'Agency',
				Industry_Tier_2__c = 'Media Agency',
				Type = 'Advertiser',
				CurrencyIsoCode = 'EUR',
				Corporate_Brand_Name__c = corporateBrandName.Id
        );

		if (insertRecord) {
			insert account;
		}

		return account;
	}

	/**
	 * Create an account for test
	 * @param  name         String
	 * @param  insertRecord Boolean
	 * @param  count        Integer
	 * @return              Account
	 */
	public static List<Account> createMultiple(String name, Boolean insertRecord, Integer count) {
		Id recordTypeId = CS_utl_RecordType.getRecordTypesById(Account.getSObjectType()).values().get(0).getRecordTypeId();
		return createMultiple(name, recordTypeId, insertRecord, count);
	}

	/**
	 * Create an account for test
	 * @param  name         String
	 * @param  recordTypeId Id
	 * @param  insertRecord Boolean
	 * @param  count        Integer
	 * @return              Account
	 */
	public static List<Account> createMultiple(String name, Id recordTypeId, Boolean insertRecord, Integer count) {
        TestDataSetupBasic.insertPGAccountTrigger();

		String randomNumber = String.valueOf(Integer.valueOf((Math.random() * 100)));
		Corporate_Brand_Name__c corporateBrandName = new Corporate_Brand_Name__c();

		List<Corporate_Brand_Name__c> corporateBrandNameList = [SELECT Id FROM Corporate_Brand_Name__c];
		if (corporateBrandNameList.size() > 0) {
			corporateBrandName = corporateBrandNameList[0];
		} else {
			corporateBrandName = new Corporate_Brand_Name__c(Name = 'Test Corporate Brand Name ' + randomNumber,
					Global_Customer_Segment__c = 'Advertiser');
			insert corporateBrandName;
		}

		List<Account> accounts = new List<Account>();
		for (Integer i = 0; i < count; i++) {
			Account acc = new Account(
                    Name = name + String.valueOf(i),
					Phone = '12345',
					BillingStreet = 'Test Street',
					BillingCity = 'City',
					BillingPostalCode = '10000',
					BillingCountry = 'United States',
					BillingCountryCode = 'US',
					RecordTypeId = recordTypeId,
					Website = 'www.cloudsense.com',
					Industry = 'Agency',
					Industry_Tier_2__c = 'Media Agency',
					Type = 'Advertiser',
					CurrencyIsoCode = 'EUR',
					Corporate_Brand_Name__c = corporateBrandName.Id
            );
			accounts.add(acc);
		}

		if (!accounts.isEmpty() && insertRecord) {
			insert accounts;
		}

		return accounts;
	}
}