unpackaged/main/default/objects/Account/fields/Country__c.field-meta.xml
<CustomField>
    <fullName>Country__c</fullName>
    <defaultValue>if(  BEGINS($UserRole.Name, &quot;TH&quot;),&quot;Thailand&quot;,if(ISPICKVAL($User.Subsidiary__c,&quot;MyProperty Data Sdn. Bhd.&quot;),&quot;Malaysia&quot;,&quot;&quot;))</defaultValue>
    <description>Denotes the country of an account</description>
    <inlineHelpText>Denotes the country of an account</inlineHelpText>
    <label>Country</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Country</valueSetName>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Account/fields/Record_Eligibility__c.field-meta.xml
<CustomField>
    <fullName>Record_Eligibility__c</fullName>
    <label>Record Eligibility</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

unpackaged/main/default/objects/Country_Attribute__mdt/Country_Attribute__mdt.object-meta.xml
<CustomObject>
    <label>Country Attribute</label>
    <pluralLabel>Country Attributes</pluralLabel>
</CustomObject>

unpackaged/main/default/objects/CountryCode__c/CountryCode__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>CountryCode</label>
</CustomObject>

unpackaged/main/default/classes/EligibilityHandler_Test.cls
@isTest
public class EligibilityHandler_Test {
    public testMethod static void runEligibleTest() {
        CountryCode__c cc = new CountryCode__c();
        cc.Name = 'singapore';
        cc.code__c = 'sg';
        insert cc;
        map<string, string> testCountryCode = EligibilityHandler.getMapCountryCode();
        system.assertEquals(testCountryCode.get('singapore'), 'sg');
        map<string, Country_Attribute__mdt> testMapCountryAtt = EligibilityHandler.getCountryAttribute();
        system.assert(testMapCountryAtt.keySet().contains('Singapore'));
        list<string> testCountryEligibility = EligibilityHandler.getCountryEligibility('AT_PGOpportunityTrigger');
        system.assert(testCountryEligibility.contains('Singapore'));
        
        list<Account> testListAcc = new list<Account>();
        String agentRT = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Agent').getRecordTypeId();
        Account testAcc = new Account();
        testAcc.Country__c = 'Singapore';
        testAcc.FirstName = 'TestAgentFirst';
        testAcc.LastName = 'TestAgentLast';
        testAcc.RecordTypeId = agentRT;
        testListAcc.add(testAcc);
        EligibilityHandler.assignValue(testListAcc, 'Singapore');
        system.assert(testListAcc[0].Record_Eligibility__c.contains('AT_PGAccountTrigger'));
    }
}