unpackaged/main/default/objects/Account/fields/Country__c.field-meta.xml
<CustomField>
    <fullName>Country__c</fullName>
    <defaultValue>if(  BEGINS($UserRole.Name, &quot;TH&quot;),&quot;Thailand&quot;,if(ISPICKVAL($User.Subsidiary__c,&quot;MyProperty Data Sdn. Bhd.&quot;),&quot;Malaysia&quot;,&quot;&quot;))</defaultValue>
    <description>Denotes the country of an account</description>
    <inlineHelpText>Denotes the country of an account</inlineHelpText>
    <label>Country</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Country</valueSetName>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Account/fields/PG_Tenure__c.field-meta.xml
<CustomField>
    <fullName>PG_Tenure__c</fullName>
    <description>Denotes tenure of an agent with PG</description>
    <formula>IF(OR(ISPICKVAL(Country__c, &#39;Malaysia&#39;),ISPICKVAL(Country__c, &#39;Thailand&#39;)),
FLOOR(
(((Year(Subscription_End_Date__c)-Year(Loyalty_Start_Date__c))*12 + (IF(IF(MONTH(Subscription_End_Date__c)+1&gt;12,MONTH(Subscription_End_Date__c)+1-12,
MONTH(Subscription_End_Date__c)+1)=MONTH(Loyalty_Start_Date__c),MONTH(Subscription_End_Date__c)+1-MONTH(Loyalty_Start_Date__c),
MONTH(Subscription_End_Date__c)-MONTH(Loyalty_Start_Date__c))))/12)),
IF(ISPICKVAL(Country__c, &#39;Singapore&#39;),
FLOOR((((Year(Subscription_End_Date__c)-Year(Loyalty_Start_Date__c))*12 + (IF(IF(MONTH(Subscription_End_Date__c)+1&gt;12,MONTH(Subscription_End_Date__c)+1-12,
MONTH(Subscription_End_Date__c)+1)=MONTH(Loyalty_Start_Date__c),MONTH(Subscription_End_Date__c)+1-MONTH(Loyalty_Start_Date__c),
MONTH(Subscription_End_Date__c)-MONTH(Loyalty_Start_Date__c))))/12)),1)
)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>PG Tenure is calculated as Subscription End Date minus Loyalty Start Date</inlineHelpText>
    <label>PG Tenure</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/Subsidiary__c.field-meta.xml
<CustomField>
    <fullName>Subsidiary__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Denotes the PG subsidiary to which the account belongs to</description>
    <inlineHelpText>Denotes the PG subsidiary to which the account belongs to</inlineHelpText>
    <label>Subsidiary</label>
    <referenceTo>Subsidiary__c</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/Subsidiary_Type__c.field-meta.xml
<CustomField>
    <fullName>Subsidiary_Type__c</fullName>
    <defaultValue>if(ISPICKVAL($User.Subsidiary__c,&#39;MyProperty Data Sdn. Bhd.&#39;),&#39;MPD&#39;,&#39;&#39;)</defaultValue>
    <label>Subsidiary Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>MPD</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Account/fields/Total_Spending__c.field-meta.xml
<CustomField>
    <fullName>Total_Spending__c</fullName>
    <defaultValue>0</defaultValue>
    <inlineHelpText>This is total spending on Discretionary Products</inlineHelpText>
    <label>Total Spending</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Count_of_Subscription_Item_new__c.field-meta.xml
<CustomField>
    <fullName>Count_of_Subscription_Item_new__c</fullName>
    <label>Count of Subscription Item</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Country__c.field-meta.xml
<CustomField>
    <fullName>Country__c</fullName>
    <formula>TEXT(Subsidiary__r.Country__c )</formula>
    <label>Country</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Opportunity_Type__c.field-meta.xml
<CustomField>
    <fullName>Opportunity_Type__c</fullName>
    <defaultValue>IF( $RecordType.DeveloperName = &#39;B2C&#39; , &#39;B2C - Standard&#39;, null)</defaultValue>
    <label>Opportunity Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>B2C - Standard</fullName>
            </value>
            <value>
                <fullName>B2C - Upgrade</fullName>
            </value>
            <value>
                <fullName>B2C - Renewal</fullName>
            </value>
            <value>
                <fullName>Self-Serve Standard</fullName>
            </value>
            <value>
                <fullName>Self-Serve Renewal</fullName>
            </value>
            <value>
                <fullName>Self-Serve Abandoned</fullName>
            </value>
            <value>
                <fullName>Marketing Automation</fullName>
            </value>
            <value>
                <fullName>B2C - Conversion</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Order_Type_Clone__c.field-meta.xml
<CustomField>
    <fullName>Order_Type_Clone__c</fullName>
    <label>Order Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Contract - New</fullName>
            </value>
            <value>
                <fullName>Contract - Upsell</fullName>
            </value>
            <value>
                <fullName>Contract - Renewal</fullName>
            </value>
            <value>
                <fullName>Contract - Make Good</fullName>
            </value>
            <value>
                <fullName>Dual-SO</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/PG_Tenure__c.field-meta.xml
<CustomField>
    <fullName>PG_Tenure__c</fullName>
    <label>PG Tenure</label>
    <precision>4</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Primary_Sales_Order__c.field-meta.xml
<CustomField>
    <fullName>Primary_Sales_Order__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Primary Sales Order linked to this Opportunity</description>
    <inlineHelpText>Primary Sales Order linked to this Opportunity</inlineHelpText>
    <label>Primary Sales Order</label>
    <referenceTo>csmso__Sales_Order__c</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Subsidiary__c.field-meta.xml
<CustomField>
    <fullName>Subsidiary__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Subsidiary</label>
    <referenceTo>Subsidiary__c</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Subsidiary_Code__c.field-meta.xml
<CustomField>
    <fullName>Subsidiary_Code__c</fullName>
    <formula>Subsidiary__r.Subsidiary_Code__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Subsidiary Code</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Subsidiary_Type__c.field-meta.xml
<CustomField>
    <fullName>Subsidiary_Type__c</fullName>
    <label>Subsidiary Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>iPP</fullName>
            </value>
            <value>
                <fullName>Property Guru</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Total_Spending__c.field-meta.xml
<CustomField>
    <fullName>Total_Spending__c</fullName>
    <label>Total Spending (last 12 months)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/recordTypes/B2B.recordType-meta.xml
<RecordType>
    <fullName>B2B</fullName>
    <active>true</active>
    <businessProcess>B2B</businessProcess>
    <description>B2B Opportunity Record</description>
    <label>B2B</label>
</RecordType>

unpackaged/main/default/objects/Opportunity/recordTypes/B2C.recordType-meta.xml
<RecordType>
    <fullName>B2C</fullName>
    <active>true</active>
    <businessProcess>B2C</businessProcess>
    <description>B2C Opportunity Record</description>
    <label>B2C</label>
</RecordType>

unpackaged/main/default/objects/Subsidiary__c/Subsidiary__c.object-meta.xml
<CustomObject>
    <description>This is a custom object to contain the information on Subsidiary and Country</description>
    <label>Subsidiary</label>
    <nameField>
        <label>Subsidiary Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Subsidiaries</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Subsidiary__c/fields/Country__c.field-meta.xml
<CustomField>
    <fullName>Country__c</fullName>
    <description>Values from global picklist</description>
    <label>Country</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Country</valueSetName>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Subsidiary__c/fields/Logo_url__c.field-meta.xml
<CustomField>
    <fullName>Logo_url__c</fullName>
    <label>Logo url</label>
    <type>Url</type>
</CustomField>

unpackaged/main/default/objects/Subsidiary__c/fields/NS_Subsidiary_Internal_ID__c.field-meta.xml
<CustomField>
    <fullName>NS_Subsidiary_Internal_ID__c</fullName>
    <description>NetSuite record internal ID</description>
    <externalId>true</externalId>
    <label>NS Subsidiary Internal ID</label>
    <length>20</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

unpackaged/main/default/objects/Subsidiary__c/fields/Subsidiary_Code__c.field-meta.xml
<CustomField>
    <fullName>Subsidiary_Code__c</fullName>
    <description>An internal custom code for checking with User subsidiary and using this code to determine approval route</description>
    <label>Subsidiary Code</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Subsidiary__c/fields/Tax_Label__c.field-meta.xml
<CustomField>
    <fullName>Tax_Label__c</fullName>
    <description>This label is used in the Print Contract PDF to display tax</description>
    <inlineHelpText>GST | VAT</inlineHelpText>
    <label>Tax Label</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Trigger_Execute__c/Trigger_Execute__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>Trigger Execute</label>
</CustomObject>

unpackaged/main/default/objects/Trigger_Execute__c/fields/Enable_del__c.field-meta.xml
<CustomField>
    <fullName>Enable_del__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Enable del</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/User/fields/Subsidiary__c.field-meta.xml
<CustomField>
    <fullName>Subsidiary__c</fullName>
    <label>Subsidiary</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Subsidiary</valueSetName>
    </valueSet>
</CustomField>

unpackaged/main/default/classes/CallNSforiPP_Test.cls
@isTest
public class CallNSforiPP_Test {

    @isTest
    public static void unitTest(){
        
        Trigger_Execute__c customsetting=new Trigger_Execute__c();
        customsetting.Name='PGAccountTrigger';
        customsetting.Enable_del__c=true;
        insert customsetting;
        
        Trigger_Execute__c TEOppSplit = new Trigger_Execute__c();
        TEOppSplit.Name = 'Trigger_OpportunitySplit';
        TEOppSplit.Enable_del__c = true;
        insert TEOppSplit;
        
        string b2baccRectype = Schema.SObjectType.Account.getRecordTypeInfosByName().get('B2B - Account').getRecordTypeId();
        string b2boppRectype = Schema.SObjectType.Opportunity.getRecordTypeInfosByName().get('B2B').getRecordTypeId();
        user u = [select id,Subsidiary__c from user where id = :userinfo.getuserID()];
       // u.Subsidiary__c=''
     Subsidiary__c sb = new Subsidiary__c();
        sb.Name = 'iProperty.com Malaysia Sdn Bhd';
        sb.NS_Subsidiary_Internal_ID__c = '11';
        sb.Subsidiary_Code__c  ='iPP';
        sb.CurrencyIsoCode = 'MYR';
        sb.Tax_Label__c = 'taxLabel';
        sb.Country__c = 'Malaysia';
        sb.Logo_url__c='https://c.ap5.visual.force.com/resource/1525687701000/SG_Sales_Order_Header_v3_PGG';
        insert sb;
        Subsidiary__c sb1 = PGTestDataFactory_v2.createMYSubsidiary(u);
       
        //sb.Subsidiary_Code__c = 'ipp';
      
        Account acc = new Account();
        acc.Name = 'Acc Dunning';
        acc.Country__c = 'Malaysia';
        acc.RecordTypeId = b2baccRectype;
        insert acc;
        
        Test.startTest();
        Opportunity opp = new opportunity();
        opp.Name = 'Test Opp';
        opp.StageName = 'Prospecting';
        opp.AccountId = acc.id;
        opp.CloseDate = system.today().AddDays(30);
         opp.Subsidiary__c = sb.id;
        opp.Total_Spending__c = 100;
        opp.RecordTypeId = b2boppRectype;
        opp.PG_Tenure__c = 1;
        opp.count_of_subscription_item_new__c = 100.0;
        //opp.Order_Type_Clone__c   = 'Contract - Renewal';
       // opp.Opportunity_Type__c='B2C - Renewal';
        opp.Subsidiary_Type__c = 'iPP';
        insert opp;
        
        csmso__Sales_Order__c so = new csmso__Sales_Order__c();
        so.csmso__Advertiser__c = acc.Id;
        so.csmso__Status__c = 'Delivered';
        so.csmso__Opportunity__c = opp.Id;
        so.Primary_Sales_Order__c = true;
        so.Advertiser_Final__c = acc.Id;
        so.Billing_schedule__c = 'Bill by item';
        insert so;
        
        CSPOFA__Orchestration_Process_Template__c ProTemp = new CSPOFA__Orchestration_Process_Template__c();
        ProTemp.Name = 'temp';
        insert ProTemp;
        
        CSPOFA__Orchestration_Process__c process = new CSPOFA__Orchestration_Process__c();
        process.Name = 'process';
        process.CSPOFA__Orchestration_Process_Template__c = ProTemp.Id;
        process.Sales_Order__c = so.id;
        insert process;
        
        CSPOFA__Orchestration_Step__c step = new CSPOFA__Orchestration_Step__c();
        step.Name = 'step';
        //step.Sales_Order__c = so.id;
        step.CSPOFA__Orchestration_Process__c = process.Id;
        insert step;
         List<CSPOFA__Orchestration_Step__c> steps = [
            SELECT Id, CSPOFA__Orchestration_Process__c, CSPOFA__Orchestration_Process__r.Name, Sales_Order__c,
            Orchestration_Process_Name__c, CSPOFA__Execute_Count__c, CSPOFA__Status__c
            FROM CSPOFA__Orchestration_Step__c where id= :step.id
        ];
        list<CSPOFA__Orchestration_Step__c> steplist = new list<CSPOFA__Orchestration_Step__c>();
        //steplist.add(steps);
        
        CallNSforiPP call = new CallNSforiPP();
        call.performCallouts(steps);
        call.process(steplist);
        
        Test.stopTest();
    }
}