unpackaged/main/default/objects/Account/fields/Country__c.field-meta.xml
<CustomField>
    <fullName>Country__c</fullName>
    <defaultValue>if(  BEGINS($UserRole.Name, &quot;TH&quot;),&quot;Thailand&quot;,if(ISPICKVAL($User.Subsidiary__c,&quot;MyProperty Data Sdn. Bhd.&quot;),&quot;Malaysia&quot;,&quot;&quot;))</defaultValue>
    <description>Denotes the country of an account</description>
    <inlineHelpText>Denotes the country of an account</inlineHelpText>
    <label>Country</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Country</valueSetName>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Account/fields/Previous_Acct_End_Date__c.field-meta.xml
<CustomField>
    <fullName>Previous_Acct_End_Date__c</fullName>
    <description>Denotes the end date of an agent’s previous subscription</description>
    <inlineHelpText>Denotes the end date of an agent’s previous subscription</inlineHelpText>
    <label>Previous Acct End Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>Denotes the status of an agent in the agent lifecycle</description>
    <inlineHelpText>Denotes the status of an agent in the agent lifecycle</inlineHelpText>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Trial</fullName>
            </value>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Downgraded</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Suspended</fullName>
            </value>
            <value>
                <fullName>Expired</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Account/fields/Subscription_End_Date__c.field-meta.xml
<CustomField>
    <fullName>Subscription_End_Date__c</fullName>
    <description>Denotes end date of an agent&#39;s current subscriptions</description>
    <inlineHelpText>Denotes end date of an agent&#39;s current subscriptions</inlineHelpText>
    <label>Subscription End Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Country__c.field-meta.xml
<CustomField>
    <fullName>Country__c</fullName>
    <formula>TEXT(Subsidiary__r.Country__c )</formula>
    <label>Country</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Opportunity_Type__c.field-meta.xml
<CustomField>
    <fullName>Opportunity_Type__c</fullName>
    <defaultValue>IF( $RecordType.DeveloperName = &#39;B2C&#39; , &#39;B2C - Standard&#39;, null)</defaultValue>
    <label>Opportunity Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>B2C - Standard</fullName>
            </value>
            <value>
                <fullName>B2C - Upgrade</fullName>
            </value>
            <value>
                <fullName>B2C - Renewal</fullName>
            </value>
            <value>
                <fullName>Self-Serve Standard</fullName>
            </value>
            <value>
                <fullName>Self-Serve Renewal</fullName>
            </value>
            <value>
                <fullName>Self-Serve Abandoned</fullName>
            </value>
            <value>
                <fullName>Marketing Automation</fullName>
            </value>
            <value>
                <fullName>B2C - Conversion</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Order_Type_Clone__c.field-meta.xml
<CustomField>
    <fullName>Order_Type_Clone__c</fullName>
    <label>Order Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Contract - New</fullName>
            </value>
            <value>
                <fullName>Contract - Upsell</fullName>
            </value>
            <value>
                <fullName>Contract - Renewal</fullName>
            </value>
            <value>
                <fullName>Contract - Make Good</fullName>
            </value>
            <value>
                <fullName>Dual-SO</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Renewal_State__c.field-meta.xml
<CustomField>
    <fullName>Renewal_State__c</fullName>
    <label>Renewal State</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Actual Month</fullName>
            </value>
            <value>
                <fullName>Actual Month +1</fullName>
            </value>
            <value>
                <fullName>Early Bird</fullName>
            </value>
            <value>
                <fullName>Back to Back Renewal</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Subscription_End_Date__c.field-meta.xml
<CustomField>
    <fullName>Subscription_End_Date__c</fullName>
    <label>Subscription End Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/recordTypes/B2C.recordType-meta.xml
<RecordType>
    <fullName>B2C</fullName>
    <active>true</active>
    <businessProcess>B2C</businessProcess>
    <description>B2C Opportunity Record</description>
    <label>B2C</label>
</RecordType>

unpackaged/main/default/objects/Quote/fields/Country__c.field-meta.xml
<CustomField>
    <fullName>Country__c</fullName>
    <formula>TEXT(Opportunity.Subsidiary__r.Country__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Country</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Quote/fields/Renewal_State__c.field-meta.xml
<CustomField>
    <fullName>Renewal_State__c</fullName>
    <label>Renewal State</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Actual Month</fullName>
            </value>
            <value>
                <fullName>Actual Month +1</fullName>
            </value>
            <value>
                <fullName>Early Bird</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Quote/fields/Subscription_End_Date__c.field-meta.xml
<CustomField>
    <fullName>Subscription_End_Date__c</fullName>
    <label>Subscription End Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/Quote/recordTypes/B2C.recordType-meta.xml
<RecordType>
    <fullName>B2C</fullName>
    <active>true</active>
    <label>B2C</label>
</RecordType>

unpackaged/main/default/classes/OpportunityRenewalUpd_Batch.cls
global class OpportunityRenewalUpd_Batch implements Database.Batchable<sObject>{
    
    String query;
    global Database.QueryLocator start(Database.BatchableContext BC)  {
        map<string, string> MapAccRT = new map<string, string>();
        for (RecordType rt : [SELECT Id, Name FROM RecordType WHERE SObjectType='Opportunity' and Name='B2C']){
            MapAccRT.put(rt.Name, rt.Id);
        }
        query = 'select id,Renewal_State__c,Country__c,Account.Status__c,Account.Subscription_End_Date__c,Account.Previous_Acct_End_Date__c  from opportunity where StageName IN(\'New\', \'Proposal\',\'Pending Online Payment\',\'Pending OMC Approval\') AND (Order_Type_Clone__c = \'Contract - Renewal\' OR Opportunity_Type__c = \'B2C - Renewal\') AND RecordTypeId = \''+ MapAccRT.get('B2C') +'\'';
        system.debug(query);
        return Database.getQueryLocator(query);       
    }
    
    global void execute(Database.BatchableContext BC, List<Opportunity> batch) {        
        if(batch.size() > 0){
            Set<Id> OppIdSet = new Set<Id>();
            for(Opportunity op : batch){
                OppIdSet.add(op.id); 
            }
            Map<Id,Opportunity> mapOfIdVsOpportunity = new Map<Id,Opportunity>([Select id,(select id,Renewal_State__c,Opportunityid from quotes where Status not IN ('Invalid','Expired','Accepted') ) from Opportunity where id in : OppIdSet]);
            List<Quote> toUpdateQuote = new List<Quote>();
            List<Opportunity> toUpdate = new List<Opportunity>();
            system.debug('Batch:' + batch);
            Set<Id> setOfOppIds = new Set<Id>();
            
            for(sObject obj : batch) {
                Opportunity opty = (Opportunity)obj;
                boolean isAm = false; //= (opty.Account.Subscription_End_Date__c.month() == system.today().month() && opty.Account.Subscription_End_Date__c.year() == system.today().year());
                boolean isAmPlus1 = false; //= (opty.Account.Subscription_End_Date__c.addMonths(1).month() == system.today().month() && opty.Account.Subscription_End_Date__c.addMonths(1).year() == system.today().year());
                boolean isEB = false; //= (opty.Account.Subscription_End_Date__c.addMonths(-1).month() == system.today().month() && opty.Account.Subscription_End_Date__c.addMonths(-1).year() == system.today().year());
                if(opty.Country__c=='Singapore'){
                    if(opty.Account.Status__c=='Active' && opty.Account.Subscription_End_Date__c.month() == system.today().month() && opty.Account.Subscription_End_Date__c.year() == system.today().year()){
                        isAm=true;
                    } else if(opty.Account.Status__c=='Downgraded' && opty.Account.Previous_Acct_End_Date__c.month() == system.today().month() && opty.Account.Previous_Acct_End_Date__c.year() == system.today().year()){
                        isAm=true;
                    } else if(opty.Account.Status__c=='Suspended' && opty.Account.Subscription_End_Date__c.month() == system.today().month() && opty.Account.Subscription_End_Date__c.year() == system.today().year()){
                        //added the condition as part of change of Penny, PGAUTO-5441
                        isAm=true;
                    } else if(opty.Account.Status__c=='Active' && opty.Account.Subscription_End_Date__c.addMonths(1).month() == system.today().month() && opty.Account.Subscription_End_Date__c.addMonths(1).year() == system.today().year()){
                        isAmPlus1=true;
                    } else if(opty.Account.Status__c=='Downgraded' && opty.Account.Previous_Acct_End_Date__c.addMonths(1).month() == system.today().month() && opty.Account.Previous_Acct_End_Date__c.addMonths(1).year() == system.today().year()){
                        isAmPlus1=true;
                    } else if(opty.Account.Status__c=='Active' && opty.Account.Subscription_End_Date__c.month() == system.today().addMonths(1).month() && opty.Account.Subscription_End_Date__c.year() == system.today().addMonths(1).year()){
                        isEB=true;
                    }
                }else if(opty.Country__c=='Malaysia' || opty.Country__c=='Thailand'){
                    if(opty.Account.Subscription_End_Date__c.month() == system.today().month() && opty.Account.Subscription_End_Date__c.year() == system.today().year()){
                        isAm=true;
                    }else if(opty.Account.Subscription_End_Date__c.addMonths(1).month() == system.today().month() && opty.Account.Subscription_End_Date__c.addMonths(1).year() == system.today().year()){
                        isAmPlus1=true;
                    }else if(opty.Account.Status__c=='Active' && opty.Account.Subscription_End_Date__c.month() == system.today().addMonths(1).month() && opty.Account.Subscription_End_Date__c.year() == system.today().addMonths(1).year()){
                        isEB=true;
                    }
                }
                
                if(isAm && opty.Renewal_State__c != 'Actual Month'){
                    opty.Renewal_State__c = 'Actual Month';
                    toUpdate.add(opty);
                    setOfOppIds.add(opty.Id);
                }
                if(isAmPlus1 && opty.Renewal_State__c != 'Actual Month +1'){
                    opty.Renewal_State__c = 'Actual Month +1';
                    toUpdate.add(opty);
                    setOfOppIds.add(opty.Id);
                }
                if(isEB && opty.Renewal_State__c != 'Early Bird'){
                    opty.Renewal_State__c = 'Early Bird';
                    toUpdate.add(opty);
                    setOfOppIds.add(opty.Id);
                }
                Opportunity oppList = mapOfIdVsOpportunity.get(opty.id);
                if(oppList.quotes.size()>0){
                    for(Quote qu : oppList.quotes){
                        if(setOfOppIds.contains(qu.OpportunityId)){
                            if(opty.Renewal_State__c!=null && opty.Renewal_State__c!=''){
                                qu.Renewal_State__c = opty.Renewal_State__c;
                                toUpdateQuote.add(qu);
                            }
                        }
                    }
                }
            }
            if(toUpdate.size() > 0) {
                system.debug('toUpdate: ' + toUpdate);
                Database.update(toUpdate, false);
            }
            if(toUpdateQuote.size() > 0) {
                Database.update(toUpdateQuote, false);
            }
            
        }
    }
    
    global void finish(Database.BatchableContext BC) {
        
    }  
}