unpackaged/main/default/objects/Account/fields/Country__c.field-meta.xml
<CustomField>
    <fullName>Country__c</fullName>
    <defaultValue>if(  BEGINS($UserRole.Name, &quot;TH&quot;),&quot;Thailand&quot;,if(ISPICKVAL($User.Subsidiary__c,&quot;MyProperty Data Sdn. Bhd.&quot;),&quot;Malaysia&quot;,&quot;&quot;))</defaultValue>
    <description>Denotes the country of an account</description>
    <inlineHelpText>Denotes the country of an account</inlineHelpText>
    <label>Country</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Country</valueSetName>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Account/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>Denotes the status of an agent in the agent lifecycle</description>
    <inlineHelpText>Denotes the status of an agent in the agent lifecycle</inlineHelpText>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Trial</fullName>
            </value>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Downgraded</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Suspended</fullName>
            </value>
            <value>
                <fullName>Expired</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Account/fields/Subsidiary__c.field-meta.xml
<CustomField>
    <fullName>Subsidiary__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Denotes the PG subsidiary to which the account belongs to</description>
    <inlineHelpText>Denotes the PG subsidiary to which the account belongs to</inlineHelpText>
    <label>Subsidiary</label>
    <referenceTo>Subsidiary__c</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Account/recordTypes/Agency.recordType-meta.xml
<RecordType>
    <fullName>Agency</fullName>
    <active>true</active>
    <label>Agency</label>
</RecordType>

unpackaged/main/default/objects/CamMemberStatusValue__c/CamMemberStatusValue__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>CamMemberStatusValue</label>
</CustomObject>

unpackaged/main/default/objects/CamMemberStatusValue__c/fields/Values__c.field-meta.xml
<CustomField>
    <fullName>Values__c</fullName>
    <label>Values</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Campaign/fields/Country__c.field-meta.xml
<CustomField>
    <fullName>Country__c</fullName>
    <description>Denotes the country of campaign members and is synonymous with currency field</description>
    <inlineHelpText>Denotes the country of campaign members and is synonymous with currency field</inlineHelpText>
    <label>Country</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Country</valueSetName>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Campaign/fields/Coupon_code__c.field-meta.xml
<CustomField>
    <fullName>Coupon_code__c</fullName>
    <description>Denotes coupon code to be applied as part of campaign</description>
    <inlineHelpText>Denotes coupon code to be applied as part of campaign</inlineHelpText>
    <label>Coupon code</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Campaign/fields/PG_Campaign_Id__c.field-meta.xml
<CustomField>
    <fullName>PG_Campaign_Id__c</fullName>
    <label>PG Campaign Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Campaign/fields/Theme__c.field-meta.xml
<CustomField>
    <fullName>Theme__c</fullName>
    <description>Denotes theme in Self Serve front-end application</description>
    <inlineHelpText>Denotes theme in Self Serve front-end application</inlineHelpText>
    <label>Theme</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Campaign/recordTypes/Standard.recordType-meta.xml
<RecordType>
    <fullName>Standard</fullName>
    <active>true</active>
    <label>Standard</label>
</RecordType>

unpackaged/main/default/objects/Campaign_Eligibility__c/Campaign_Eligibility__c.object-meta.xml
<CustomObject>
    <label>Campaign Eligibility</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Campaign Eligibilities</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Campaign_Eligibility__c/fields/Next_run_scheduled__c.field-meta.xml
<CustomField>
    <fullName>Next_run_scheduled__c</fullName>
    <description>Denotes the next time the campaign eligibility is run by Campaign Rule Engine (CRE) for the related campaign</description>
    <inlineHelpText>Denotes the next time the campaign eligibility is run by Campaign Rule Engine (CRE) for the related campaign</inlineHelpText>
    <label>Next Run scheduled</label>
    <type>DateTime</type>
</CustomField>

unpackaged/main/default/objects/Campaign_Eligibility__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>Denotes whether the rule is active or inactive</description>
    <inlineHelpText>Denotes whether the rule is active or inactive</inlineHelpText>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Case/fields/Country__c.field-meta.xml
<CustomField>
    <fullName>Country__c</fullName>
    <label>Country</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Singapore</fullName>
            </value>
            <value>
                <fullName>Malaysia</fullName>
            </value>
            <value>
                <fullName>Thailand</fullName>
            </value>
            <value>
                <fullName>Indonesia</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Case/recordTypes/Case.recordType-meta.xml
<RecordType>
    <fullName>Case</fullName>
    <active>true</active>
    <businessProcess>Case</businessProcess>
    <label>Case</label>
</RecordType>

unpackaged/main/default/objects/Contact/fields/Subsidiary__c.field-meta.xml
<CustomField>
    <fullName>Subsidiary__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Denotes the PG subsidiary to which the contact belongs to</description>
    <inlineHelpText>Denotes the PG subsidiary to which the contact belongs to</inlineHelpText>
    <label>Subsidiary</label>
    <referenceTo>Subsidiary__c</referenceTo>
    <relationshipLabel>Contacts</relationshipLabel>
    <relationshipName>Contacts</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Entitlement_Promotion__c/Entitlement_Promotion__c.object-meta.xml
<CustomObject>
    <label>Entitlement Promotion</label>
    <nameField>
        <label>Entitlement Product Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Entitlement Promotion</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Entitlement_Promotion__c/fields/Promo_Mechanic__c.field-meta.xml
<CustomField>
    <fullName>Promo_Mechanic__c</fullName>
    <description>Denotes the related promo mechanic of this entitlement Promotion</description>
    <inlineHelpText>Denotes the related promo mechanic of this entitlement Promotion</inlineHelpText>
    <label>Promo Mechanic</label>
    <referenceTo>Promo_Mechanic__c</referenceTo>
    <relationshipName>Entitlement_Product</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/Product2/fields/Product_Class__c.field-meta.xml
<CustomField>
    <fullName>Product_Class__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Denotes the reference product class in netsuite</description>
    <inlineHelpText>Denotes the reference product class in netsuite</inlineHelpText>
    <label>Product Class</label>
    <referenceTo>Product_Class__c</referenceTo>
    <relationshipLabel>Products</relationshipLabel>
    <relationshipName>Products</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Product2/fields/Subsidiary__c.field-meta.xml
<CustomField>
    <fullName>Subsidiary__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Denotes the PG subsidiary to which the product belongs to</description>
    <inlineHelpText>Denotes the PG subsidiary to which the product belongs to</inlineHelpText>
    <label>Subsidiary</label>
    <referenceTo>Subsidiary__c</referenceTo>
    <relationshipLabel>Products</relationshipLabel>
    <relationshipName>Products</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Product2/fields/Tax_Code__c.field-meta.xml
<CustomField>
    <fullName>Tax_Code__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Denotes reference to the tax code</description>
    <inlineHelpText>Denotes reference to the tax code</inlineHelpText>
    <label>Tax Code</label>
    <referenceTo>Tax_Code__c</referenceTo>
    <relationshipLabel>Products</relationshipLabel>
    <relationshipName>Products</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Promo_Mechanic__c/Promo_Mechanic__c.object-meta.xml
<CustomObject>
    <label>Promo Mechanic</label>
    <nameField>
        <label>Promo Mechanic Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Promo Mechanic</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Promo_Mechanic__c/fields/Campaign_Eligibility__c.field-meta.xml
<CustomField>
    <fullName>Campaign_Eligibility__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Denotes the related Campaign Eligibility Record</description>
    <inlineHelpText>Denotes the related Campaign Eligibility Record</inlineHelpText>
    <label>Campaign Eligibility</label>
    <referenceTo>Campaign_Eligibility__c</referenceTo>
    <relationshipLabel>Promo Mechanic</relationshipLabel>
    <relationshipName>Promo_Mechanic</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Promo_Mechanic__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>Denotes whether the promo mechanic is active or inactive</description>
    <inlineHelpText>Denotes whether the promo mechanic is active or inactive</inlineHelpText>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Subsidiary__c/Subsidiary__c.object-meta.xml
<CustomObject>
    <description>This is a custom object to contain the information on Subsidiary and Country</description>
    <label>Subsidiary</label>
    <nameField>
        <label>Subsidiary Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Subsidiaries</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Subsidiary__c/fields/Country__c.field-meta.xml
<CustomField>
    <fullName>Country__c</fullName>
    <description>Values from global picklist</description>
    <label>Country</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Country</valueSetName>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Tax_Code__c/Tax_Code__c.object-meta.xml
<CustomObject>
    <description>This is custom object to store all tax codes and rates.</description>
    <label>Tax Code</label>
    <nameField>
        <label>Tax Code</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Tax Codes</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Tax_Code__c/fields/Country__c.field-meta.xml
<CustomField>
    <fullName>Country__c</fullName>
    <description>Denotes the country of tax code belongs to</description>
    <inlineHelpText>Denotes the country of tax code belongs to</inlineHelpText>
    <label>Country</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Country</valueSetName>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Trigger_Execute__c/Trigger_Execute__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>Trigger Execute</label>
</CustomObject>

unpackaged/main/default/objects/Trigger_Execute__c/fields/Enable_del__c.field-meta.xml
<CustomField>
    <fullName>Enable_del__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Enable del</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/User/fields/Subsidiary__c.field-meta.xml
<CustomField>
    <fullName>Subsidiary__c</fullName>
    <label>Subsidiary</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Subsidiary</valueSetName>
    </valueSet>
</CustomField>

unpackaged/main/default/classes/GetRequestForPGCampaigns_Test.cls
@isTest
public class GetRequestForPGCampaigns_Test {
    
    @isTest
    static void runTest1(){
        
        user runUser = [Select Id,Name from user where Id =: userinfo.getUserId()];
        Subsidiary__c sub = PGTestDataFactory_v2.createSubsidiary(RunUser);
          Trigger_Execute__c TE = new Trigger_Execute__c();
        TE.Name = 'PGCampMemberTrigger';
        TE.Enable_del__c = false;
        insert TE;
          Trigger_Execute__c TE2 = new Trigger_Execute__c();
        TE2.Name = 'PGCampaignEligibilityTrigger';
        TE2.Enable_del__c = false;
        insert TE2;
         Trigger_Execute__c TEPromoMech = new Trigger_Execute__c();
        TEPromoMech.Name = 'PGPromoMechanicTrigger';
        TEPromoMech.Enable_del__c = false;
        insert TEPromoMech;
          Trigger_Execute__c TEEntPromo = new Trigger_Execute__c();
        TEEntPromo.Name = 'PGEntitlementPromoTrigger';
        TEEntPromo.Enable_del__c = false;
        insert TEEntPromo;
        Campaign cma = PGTestDataFactory_v2.CreateCampaign(System.Today().addmonths(1));
        Contact con = PGTestDataFactory_v2.createContact('FirstName','LastName','test@mail.com');
        CampaignMember cmp = PGTestDataFactory_v2.CreateCampaignMember(con.Id, cma.Id);
        Campaign_Eligibility__c ce = PGTestDataFactory_v2.CreateCampaignEligibility(cma.Id);
        insert ce;
        
        Tax_Code__c taxcode = PGTestDataFactory_v2.createSGTaxCode();
        Product_Class__c productClass = PGTestDataFactory_v2.CreateProductClass('Prod Class Name',sub);
        Product2 prod = PGTestDataFactory_v2.CreateProduct('ProdName', 'B2C Only', 'Discretionary', 'SKU', productClass, taxcode);
        insert prod;
        
        Promo_Mechanic__c prm = PGTestDataFactory_v2.CreatePromoMechanic(prod.Id,ce.Id);
        
        Entitlement_Promotion__c ep = PGTestDataFactory_v2.CreateEntitlementPromotion(prm.Id);
        
        //unable to insert custom setting due to null RecordTypeId
        CamMemberStatusValue__c setting = new CamMemberStatusValue__c();
        setting.Name = 'null';
        setting.Values__c = cma.RecordTypeId;
        insert setting;
        
        
        RestRequest req = new RestRequest();
        RestResponse res = new RestResponse();
        req.requestURI = '/services/apexrest/api/pgcampaign/getactivecampaigns/'+cma.Id;
        req.httpMethod = 'GET';
                
        RestContext.request = req;
        RestContext.response= res;
        
        Test.startTest();
        GetRequestForPGCampaigns.getCampaignAndRelatedDetails();
        Test.stopTest();
    }
    @isTest
    static void runTest2(){
        
        RestRequest req = new RestRequest();
        RestResponse res = new RestResponse();
        req.requestURI = '/services/apexrest/api/pgcampaign/getactivecampaigns/';
        req.httpMethod = 'GET';
                
        RestContext.request = req;
        RestContext.response= res;
        
        Test.startTest();
        GetRequestForPGCampaigns.getCampaignAndRelatedDetails();
        Test.stopTest();
    }
    @isTest
    static void runTest3(){
        
        Campaign cma = PGTestDataFactory_v2.CreateCampaign(System.Today().addmonths(1));
        cma.IsActive = false;
        update cma;
        
        RestRequest req = new RestRequest();
        RestResponse res = new RestResponse();
        req.requestURI = '/services/apexrest/api/pgcampaign/getactivecampaigns/'+cma.Id;
        req.httpMethod = 'GET';
                
        RestContext.request = req;
        RestContext.response= res;
        
        Test.startTest();
        GetRequestForPGCampaigns.getCampaignAndRelatedDetails();
        Test.stopTest();
    }
    
    //case to cover empty camplist
    @isTest
    static void runTest4(){
        
        RestRequest req = new RestRequest();
        RestResponse res = new RestResponse();
        req.requestURI = '/services/apexrest/api/pgcampaign/getactivecampaigns/null';
        req.httpMethod = 'GET';
                
        RestContext.request = req;
        RestContext.response= res;
        
        Test.startTest();
        GetRequestForPGCampaigns.getCampaignAndRelatedDetails();
        Test.stopTest();
    }
    
    
    // case to cover various if else
    @isTest
    static void runTest5(){
        
        user runUser = [Select Id,Name from user where Id =: userinfo.getUserId()];
        Subsidiary__c sub = PGTestDataFactory_v2.createSubsidiary(RunUser);
          Trigger_Execute__c TE = new Trigger_Execute__c();
        TE.Name = 'PGCampMemberTrigger';
        TE.Enable_del__c = false;
        insert TE;
         Trigger_Execute__c TE2 = new Trigger_Execute__c();
        TE2.Name = 'PGCampaignEligibilityTrigger';
        TE2.Enable_del__c = false;
        insert TE2;
         Trigger_Execute__c TEPromoMech = new Trigger_Execute__c();
        TEPromoMech.Name = 'PGPromoMechanicTrigger';
        TEPromoMech.Enable_del__c = false;
        insert TEPromoMech;
          Trigger_Execute__c TEEntPromo = new Trigger_Execute__c();
        TEEntPromo.Name = 'PGEntitlementPromoTrigger';
        TEEntPromo.Enable_del__c = false;
        insert TEEntPromo;
        //Campaign cma = PGTestDataFactory_v2.CreateCampaign(System.Today().addmonths(1));
        // need some specific data and campaign cannot be updated as well thus creating required data here only
        Campaign cma = new Campaign();
        cma.Name = 'Test Campaign';
        cma.IsActive = true;
        cma.StartDate = System.today();
        cma.EndDate = null;
        cma.Country__c = '';
        cma.Type = null;
        cma.Coupon_code__c = 'Not Null';
        cma.PG_Campaign_Id__c = 'Not Null';
        cma.Theme__c ='Test';
        insert cma; 
        
        Contact con = PGTestDataFactory_v2.createContact('FirstName','LastName','test@mail.com');
        CampaignMember cmp = PGTestDataFactory_v2.CreateCampaignMember(con.Id, cma.Id);
        //Campaign_Eligibility__c ce = PGTestDataFactory_v2.CreateCampaignEligibility(cma.Id);
        Campaign_Eligibility__c ce = new Campaign_Eligibility__c(status__c='',Next_run_scheduled__c=null,Run_Frequency__c='',Name='Test Camapign',Rule_Name_Extension__c='Select Id From Contact where Account.RecordType.developerName = \'Agency\'',Criteria_Type__c = '',Priority__c=1,Campaign__c = cma.Id);
        insert ce;
        Tax_Code__c taxcode = PGTestDataFactory_v2.createSGTaxCode();
        Product_Class__c productClass = PGTestDataFactory_v2.CreateProductClass('Prod Class Name',sub);
        Product2 prod = PGTestDataFactory_v2.CreateProduct('ProdName', 'B2C Only', 'Discretionary', 'SKU', productClass, taxcode);
        insert prod;
        
        //Promo_Mechanic__c prm = PGTestDataFactory_v2.CreatePromoMechanic(prod.Id,ce.Id);
        Promo_Mechanic__c prm = new Promo_Mechanic__c();
        prm.Name = '';
        prm.Status__c ='Active';
        prm.Eligible_Product__c = prod.Id;
        prm.Campaign_Eligibility__c = ce.Id;
        prm.Usage__c = 1;
        prm.Min_Qty__c = 1;
        prm.Max_Qty__c = 1;
        prm.Denomination__c = 100;
        prm.Minimum_Spend__c = 10;
        prm.Renewal_Type__c='Upgrade';
        prm.Discount_Reason__c = 'Others';
        prm.Opportunity_Type__c = 'B2C - Standard';
        //prm.eCommerceCatalogueProductReference__c = 
        insert prm;
        
        
        Entitlement_Promotion__c ep = PGTestDataFactory_v2.CreateEntitlementPromotion(prm.Id);
        
        
        RestRequest req = new RestRequest();
        RestResponse res = new RestResponse();
        req.requestURI = '/services/apexrest/api/pgcampaign/getactivecampaigns/'+cma.Id;
        req.httpMethod = 'GET';
                
        RestContext.request = req;
        RestContext.response= res;
        
        
        Test.startTest();
        GetRequestForPGCampaigns.getCampaignAndRelatedDetails();
        Test.stopTest();
    }
}