unpackaged/main/default/objects/Account/fields/Country__c.field-meta.xml
<CustomField>
    <fullName>Country__c</fullName>
    <defaultValue>if(  BEGINS($UserRole.Name, &quot;TH&quot;),&quot;Thailand&quot;,if(ISPICKVAL($User.Subsidiary__c,&quot;MyProperty Data Sdn. Bhd.&quot;),&quot;Malaysia&quot;,&quot;&quot;))</defaultValue>
    <description>Denotes the country of an account</description>
    <inlineHelpText>Denotes the country of an account</inlineHelpText>
    <label>Country</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Country</valueSetName>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Account/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>Denotes the status of an agent in the agent lifecycle</description>
    <inlineHelpText>Denotes the status of an agent in the agent lifecycle</inlineHelpText>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Trial</fullName>
            </value>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Downgraded</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Suspended</fullName>
            </value>
            <value>
                <fullName>Expired</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Account/recordTypes/Agency.recordType-meta.xml
<RecordType>
    <fullName>Agency</fullName>
    <active>true</active>
    <label>Agency</label>
</RecordType>

unpackaged/main/default/objects/Campaign/fields/Country__c.field-meta.xml
<CustomField>
    <fullName>Country__c</fullName>
    <description>Denotes the country of campaign members and is synonymous with currency field</description>
    <inlineHelpText>Denotes the country of campaign members and is synonymous with currency field</inlineHelpText>
    <label>Country</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Country</valueSetName>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Campaign_Eligibility__c/Campaign_Eligibility__c.object-meta.xml
<CustomObject>
    <label>Campaign Eligibility</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Campaign Eligibilities</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Campaign_Eligibility__c/fields/Campaign__c.field-meta.xml
<CustomField>
    <fullName>Campaign__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Denotes the campaign for which campaign eligibility is created</description>
    <inlineHelpText>Denotes Campaign for which campaign eligibility is created</inlineHelpText>
    <label>Campaign</label>
    <referenceTo>Campaign</referenceTo>
    <relationshipLabel>Campaign Eligibilities</relationshipLabel>
    <relationshipName>Campaign_Eligibilities</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Campaign_Eligibility__c/fields/Criteria_Type__c.field-meta.xml
<CustomField>
    <fullName>Criteria_Type__c</fullName>
    <description>Denotes the type of entry of criteria</description>
    <inlineHelpText>Denotes the type of entry of criteria</inlineHelpText>
    <label>Criteria Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>SOQL</fullName>
            </value>
            <value>
                <fullName>Apex Method</fullName>
            </value>
            <value>
                <fullName>Custom Metadata</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Campaign_Eligibility__c/fields/Next_run_scheduled__c.field-meta.xml
<CustomField>
    <fullName>Next_run_scheduled__c</fullName>
    <description>Denotes the next time the campaign eligibility is run by Campaign Rule Engine (CRE) for the related campaign</description>
    <inlineHelpText>Denotes the next time the campaign eligibility is run by Campaign Rule Engine (CRE) for the related campaign</inlineHelpText>
    <label>Next Run scheduled</label>
    <type>DateTime</type>
</CustomField>

unpackaged/main/default/objects/Campaign_Eligibility__c/fields/Priority__c.field-meta.xml
<CustomField>
    <fullName>Priority__c</fullName>
    <description>Denotes the order in which the campaign eligibility rules are processed by Campaign Rule Engine. This is useful when there are multiple/dependant rules in execution</description>
    <inlineHelpText>Denotes the order in which the campaign eligibility rules are processed by Campaign Rule Engine. This is useful when there are multiple/dependant rules in execution</inlineHelpText>
    <label>Priority</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/Campaign_Eligibility__c/fields/Rule_Name_Extension__c.field-meta.xml
<CustomField>
    <fullName>Rule_Name_Extension__c</fullName>
    <description>To accommodate longer SOQL queries (&gt;255 char) when Criteria Type is &#39;SOQL&#39;</description>
    <inlineHelpText>To accommodate longer SOQL queries (&gt;255 char) when Criteria Type is &#39;SOQL&#39;</inlineHelpText>
    <label>Rule Name Extension</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

unpackaged/main/default/objects/Campaign_Eligibility__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>Denotes whether the rule is active or inactive</description>
    <inlineHelpText>Denotes whether the rule is active or inactive</inlineHelpText>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Object_Name__c/Object_Name__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>Object Name</label>
</CustomObject>

unpackaged/main/default/objects/Rule_Engine__c/Rule_Engine__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>Rule Engine</label>
</CustomObject>

unpackaged/main/default/objects/Rule_Engine__c/fields/Campaign_Ids__c.field-meta.xml
<CustomField>
    <fullName>Campaign_Ids__c</fullName>
    <label>Campaign Ids</label>
    <type>TextArea</type>
</CustomField>

unpackaged/main/default/objects/Trigger_Execute__c/Trigger_Execute__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>Trigger Execute</label>
</CustomObject>

unpackaged/main/default/objects/Trigger_Execute__c/fields/Enable_del__c.field-meta.xml
<CustomField>
    <fullName>Enable_del__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Enable del</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/classes/PreprocessorRuleEngine_Test.cls
@isTest
public class PreprocessorRuleEngine_Test {
    
    static{
        Object_Name__c obj = new Object_Name__c();
        obj.Name = 'Campaign Eligibility';
        obj.Enabled__c = true;
        insert obj;
        
        Trigger_Execute__c TECampEligibility = new Trigger_Execute__c();
        TECampEligibility.Name = 'PGCampaignEligibilityTrigger';
        TECampEligibility.Enable_del__c = true;
        insert TECampEligibility;

        Campaign cma = new Campaign();
        cma.Name = 'TestNameCampaign';
        cma.Country__c = 'Singapore';
        cma.IsActive = true;
        cma.RecordTypeId = Schema.SObjectType.Campaign.getRecordTypeInfosByName().get('VIP Promotion').getRecordTypeId();
        insert cma;
        
        Rule_Engine__c re = new Rule_Engine__c();
        re.Batch_Size__c = 200;
        re.Campaign_Ids__c = cma.Id;
        re.Name = 'Campaign Ids';
        insert re;
            
        list<Campaign_Eligibility__c> listCE = new list<Campaign_Eligibility__c>();
      	Campaign_Eligibility__c ce1 = new Campaign_Eligibility__c(status__c='Active',Next_run_scheduled__c=system.now(),Name='test1',Rule_Name_Extension__c='Select Id From Contact where Account.RecordType.developerName = \'Agency\'',Criteria_Type__c = 'SOQL',Priority__c=1,Campaign__c = cma.Id );     
        listCE.add(ce1);
        /*Campaign_Eligibility__c ce2 = new Campaign_Eligibility__c(Name='test2',Rule_Name_Extension__c='DynamicMethodCall;multiplyNumbers',Criteria_Type__c = 'Apex Method',Priority__c=2,Campaign__c = cma.Id);     
        listCE.add(ce2);*/
        insert listCE;
    }
    
   
    @isTest static void method1(){
        PreprocessorRuleEngine.startPreProcessing('Campaign Eligibility','VIP Promotion',new list<string>());
        PreprocessorRuleEngine.increaseCoverage();
        Campaign c=[select id from campaign limit 1];
        PreprocessorRuleEngine.runCRE(c.id);
    }
}