unpackaged/main/default/objects/Account/fields/Customer_Type__c.field-meta.xml
<CustomField>
    <fullName>Customer_Type__c</fullName>
    <description>Created a custom field as standard field &#39;Type&#39; cannot be mapped in lead mapping</description>
    <label>Customer Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Agent</fullName>
            </value>
            <value>
                <fullName>Owner</fullName>
            </value>
            <value>
                <fullName>Agency</fullName>
            </value>
            <value>
                <fullName>Developer</fullName>
                <default>true</default>
                <label>Developer</label>
            </value>
            <value>
                <fullName>Non-Property</fullName>
            </value>
            <value>
                <fullName>Consumer</fullName>
            </value>
            <value>
                <fullName>Media Agency</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Account/fields/Pro_Rate_Amount__c.field-meta.xml
<CustomField>
    <fullName>Pro_Rate_Amount__c</fullName>
    <description>Denotes the amount that will be used to pro-rate an agent’s future upgrades</description>
    <inlineHelpText>Denotes the amount that will be used to pro-rate an agent’s future upgrades</inlineHelpText>
    <label>Pro Rate Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>Denotes the status of an agent in the agent lifecycle</description>
    <inlineHelpText>Denotes the status of an agent in the agent lifecycle</inlineHelpText>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Trial</fullName>
            </value>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Downgraded</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Suspended</fullName>
            </value>
            <value>
                <fullName>Expired</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/OMC_Approved_Date__c.field-meta.xml
<CustomField>
    <fullName>OMC_Approved_Date__c</fullName>
    <label>OMC Approved Date</label>
    <type>DateTime</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Order_Type_Clone__c.field-meta.xml
<CustomField>
    <fullName>Order_Type_Clone__c</fullName>
    <label>Order Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Contract - New</fullName>
            </value>
            <value>
                <fullName>Contract - Upsell</fullName>
            </value>
            <value>
                <fullName>Contract - Renewal</fullName>
            </value>
            <value>
                <fullName>Contract - Make Good</fullName>
            </value>
            <value>
                <fullName>Dual-SO</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Payment_Amount__c.field-meta.xml
<CustomField>
    <fullName>Payment_Amount__c</fullName>
    <label>Payment Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Pro_Rate__c.field-meta.xml
<CustomField>
    <fullName>Pro_Rate__c</fullName>
    <label>Pro Rate</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Product_Category__c.field-meta.xml
<CustomField>
    <fullName>Product_Category__c</fullName>
    <label>Product Category</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Awards</fullName>
            </value>
            <value>
                <fullName>China Solutions</fullName>
            </value>
            <value>
                <fullName>Events</fullName>
            </value>
            <value>
                <fullName>Agent Discretionary</fullName>
            </value>
            <value>
                <fullName>Agent Subscriptions</fullName>
            </value>
            <value>
                <fullName>Developer Listings</fullName>
            </value>
            <value>
                <fullName>Online Advertising</fullName>
            </value>
            <value>
                <fullName>Marketing Services</fullName>
            </value>
            <value>
                <fullName>Database Marketing</fullName>
            </value>
            <value>
                <fullName>Content</fullName>
            </value>
            <value>
                <fullName>FinTech</fullName>
            </value>
            <value>
                <fullName>FastKey</fullName>
            </value>
            <value>
                <fullName>Data MPD</fullName>
            </value>
            <value>
                <fullName>Discretionary</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Push_To_NetSuite__c.field-meta.xml
<CustomField>
    <fullName>Push_To_NetSuite__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Push To NetSuite</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/OpportunityLineItem/fields/Amount__c.field-meta.xml
<CustomField>
    <fullName>Amount__c</fullName>
    <description>Amount after discount before tax (Sales Price * Qty - Discount), exclude complimentary</description>
    <formula>IF( Complimentary__c = TRUE, IF(Record_Type__c=&quot;B2C&quot;, (UnitPrice *  Quantity) - TotalPrice, (UnitPrice *  Quantity) - Discounted_Amount__c -  TotalPrice) , IF(Record_Type__c=&quot;B2C&quot;, (UnitPrice *  Quantity) - Discounted_Amount__c - Pro_Rate_Amount__c, (UnitPrice *  Quantity) - Discounted_Amount__c))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>(Sales Price * Qty - Discount) - Complimentary, before Tax</inlineHelpText>
    <label>Price after discount</label>
    <precision>18</precision>
    <scale>3</scale>
    <type>Currency</type>
</CustomField>

unpackaged/main/default/objects/OpportunityLineItem/fields/Amount_Despite_VIP__c.field-meta.xml
<CustomField>
    <fullName>Amount_Despite_VIP__c</fullName>
    <label>Amount Despite VIP</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/OpportunityLineItem/fields/Complimentary__c.field-meta.xml
<CustomField>
    <fullName>Complimentary__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Indicate this product is given to customer as Complimentary</description>
    <inlineHelpText>Check if this product is Complimentary</inlineHelpText>
    <label>Complimentary</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/OpportunityLineItem/fields/Discount_Amount__c.field-meta.xml
<CustomField>
    <fullName>Discount_Amount__c</fullName>
    <defaultValue>0</defaultValue>
    <description>This is the discount amount that the sales user will input</description>
    <inlineHelpText>Apply this Discount Amount (DO NOT input Discount % if this is applicable)</inlineHelpText>
    <label>Discount Amt</label>
    <precision>18</precision>
    <scale>3</scale>
    <type>Currency</type>
</CustomField>

unpackaged/main/default/objects/OpportunityLineItem/fields/Discount_Reason__c.field-meta.xml
<CustomField>
    <fullName>Discount_Reason__c</fullName>
    <label>Discount Reason</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Discount_Reasons</valueSetName>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/OpportunityLineItem/fields/End_Date__c.field-meta.xml
<CustomField>
    <fullName>End_Date__c</fullName>
    <defaultValue>TODAY()</defaultValue>
    <description>End Date of the contract for the line item. Map to NetSuite SO.</description>
    <label>End Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/OpportunityLineItem/fields/PO__c.field-meta.xml
<CustomField>
    <fullName>PO__c</fullName>
    <defaultValue>true</defaultValue>
    <description>Send to PO API when it&#39;s checked</description>
    <inlineHelpText>Send to PO API when it&#39;s checked</inlineHelpText>
    <label>Auto-Activation</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/OpportunityLineItem/fields/Pro_Rate_Amount__c.field-meta.xml
<CustomField>
    <fullName>Pro_Rate_Amount__c</fullName>
    <label>Pro Rate Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/OpportunityLineItem/fields/Push_to_NetSuite__c.field-meta.xml
<CustomField>
    <fullName>Push_to_NetSuite__c</fullName>
    <defaultValue>true</defaultValue>
    <label>Push to NetSuite</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/OpportunityLineItem/fields/SNo__c.field-meta.xml
<CustomField>
    <fullName>SNo__c</fullName>
    <description>System generated this number for use of grouping parent and child. Also use when print contract, the order of the products will in ascending order. When users delete the products, the number isn&#39;t reused.</description>
    <label>SNo</label>
    <precision>5</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/OpportunityLineItem/fields/Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Start_Date__c</fullName>
    <defaultValue>TODAY()</defaultValue>
    <description>Start Date of the contract for the line item. Map to NetSuite SO.</description>
    <label>Start Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/Payment__c/Payment__c.object-meta.xml
<CustomObject>
    <label>Payment</label>
    <nameField>
        <displayFormat>PY{0}</displayFormat>
        <label>Payment Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Payments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Payment__c/fields/Amount2__c.field-meta.xml
<CustomField>
    <fullName>Amount2__c</fullName>
    <label>Amount</label>
    <precision>12</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/Payment__c/fields/Amount__c.field-meta.xml
<CustomField>
    <fullName>Amount__c</fullName>
    <label>Amount</label>
    <precision>10</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

unpackaged/main/default/objects/Payment__c/fields/Opportunity_Record__c.field-meta.xml
<CustomField>
    <fullName>Opportunity_Record__c</fullName>
    <description>Denotes the opportunity record that payment is created for</description>
    <inlineHelpText>Denotes the opportunity record that payment is created for</inlineHelpText>
    <label>Opportunity Record</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Payments</relationshipLabel>
    <relationshipName>Payments</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/classes/OptyAmtDespiteVIPRen_Batch_DF.cls
global class OptyAmtDespiteVIPRen_Batch_DF implements Database.Batchable<sObject>{
    
    String query;
    
    global Database.QueryLocator start(Database.BatchableContext BC)  {
        
        String def_query = label.PG_LABEL_OptyAmtDespiteVIPRen_Batch_DF_q;
        if(def_query != ''){
          query = def_query;
        }
        else{
          query = 'select id from Account where (Status__c != \'Cancelled\' AND Status__c != \'Suspended\' AND Status__c != \'Expired\') and Customer_Type__c = \'Agent\'';
        }
        //query = select id from Account where (Status__c != 'Cancelled' AND Status__c != 'Suspended' AND Status__c != 'Expired');
        system.debug(query);
        return Database.getQueryLocator(query);
    }
    
    global void execute(Database.BatchableContext BC, list<Account> AccList) {
        Integer amt_d_vip = 0;
        
        system.debug('size ren:'+AccList.size());
        if(AccList.size() > 0){
            for(Account acct: AccList){
                system.debug('acct ren: ' + acct.id);
                for(Opportunity OptyUpd: [select Id,Pro_Rate__c,Payment_Amount__c from Opportunity where AccountId = :acct.id and Order_Type_Clone__c  = 'Contract - Renewal' and StageName = 'Closed Won' Order By OMC_Approved_Date__c DESC NULLS LAST LIMIT 1]){
                    system.debug('OptyUpd:' + OptyUpd);
                    for(OpportunityLineItem OptyUpdAmt: [Select id, Push_to_NetSuite__c, Amount_Despite_VIP__c, Discount_Reason__c, Pro_Rate_Amount__c, UnitPrice, Amount__c   from OpportunityLineItem where Opportunityid =: OptyUpd.Id and Product_Category__c = 'Subscription' AND Complimentary__c = false and Push_to_NetSuite__c =true]){
                        /*system.debug('OptyUpd:' + OptyUpdAmt);
                        Decimal PAmount = 0.00;
                        if(OptyUpd.Payment_Amount__c > 0){
                            if(OptyUpd.Payment_Amount__c < OptyUpdAmt.UnitPrice){
                                if(OptyUpd.Pro_Rate__c > 0){
                                    OptyUpdAmt.Discount_Amount__c  = ((OptyUpdAmt.UnitPrice-OptyUpd.Pro_Rate__c) - OptyUpd.Payment_Amount__c);
                                }
                                else{
                                    OptyUpdAmt.Discount_Amount__c  = (OptyUpdAmt.UnitPrice - OptyUpd.Payment_Amount__c);
                                }
                            }
                        }
                        else{
                            for(Payment__c paymentrec:[Select id, Amount2__c from Payment__c where Opportunity_Record__c = :OptyUpd.Id]){
                                PAmount += paymentrec.Amount2__c;
                            }
                            system.debug('PAmount:' + PAmount);
                            if(PAmount > 0){
                                if(PAmount < OptyUpdAmt.UnitPrice){
                                    if(OptyUpd.Pro_Rate__c > 0){
                                        OptyUpdAmt.Discount_Amount__c  = ((OptyUpdAmt.UnitPrice-OptyUpd.Pro_Rate__c) - PAmount);
                                    }
                                    else{
                                        OptyUpdAmt.Discount_Amount__c  = (OptyUpdAmt.UnitPrice - PAmount);
                                    }
                                }
                            }
                        }
                        OptyUpdAmt.Push_to_NetSuite__c = true;
                        OptyUpdAmt.SNo__c  = 1.00;
                        for(OpportunityLineItem OptyCheck: [Select id,Start_Date__c,End_Date__c,PO__c from OpportunityLineItem where id != :OptyUpdAmt.id and Opportunityid =: OptyUpd.Id LIMIT 1]){
                            system.debug('OptyCheck:' + OptyCheck);
                            OptyUpdAmt.Start_Date__c = OptyCheck.Start_Date__c;
                            OptyUpdAmt.End_Date__c = OptyCheck.End_Date__c ;
                            OptyUpdAmt.PO__c  = OptyCheck.PO__c;
                        }
                        system.debug('OptyUpdAmt Upd:' + OptyUpdAmt);
                        update OptyUpdAmt;*/
                        
                        if((OptyUpdAmt.Discount_Reason__c != '' && OptyUpdAmt.Discount_Reason__c != null)){
                            if((OptyUpdAmt.Discount_Reason__c).contains('VIP')){
                                OptyUpdAmt.Amount_Despite_VIP__c = OptyUpdAmt.UnitPrice;
                                OptyUpdAmt.Pro_Rate_Amount__c = 0;
                            }
                        }
                        else{
                            OptyUpdAmt.Amount_Despite_VIP__c = OptyUpdAmt.Amount__c;
                            OptyUpdAmt.Pro_Rate_Amount__c = 0;
                        }
                        update OptyUpdAmt;
                    }
                }
            }
        }
        
    }
    
    global void finish(Database.BatchableContext BC) {
            
    }
    
}