unpackaged/main/default/objects/Account/fields/Customer_Type__c.field-meta.xml
<CustomField>
    <fullName>Customer_Type__c</fullName>
    <description>Created a custom field as standard field &#39;Type&#39; cannot be mapped in lead mapping</description>
    <label>Customer Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Agent</fullName>
            </value>
            <value>
                <fullName>Owner</fullName>
            </value>
            <value>
                <fullName>Agency</fullName>
            </value>
            <value>
                <fullName>Developer</fullName>
                <default>true</default>
                <label>Developer</label>
            </value>
            <value>
                <fullName>Non-Property</fullName>
            </value>
            <value>
                <fullName>Consumer</fullName>
            </value>
            <value>
                <fullName>Media Agency</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Account/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>Denotes the status of an agent in the agent lifecycle</description>
    <inlineHelpText>Denotes the status of an agent in the agent lifecycle</inlineHelpText>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Trial</fullName>
            </value>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Downgraded</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Suspended</fullName>
            </value>
            <value>
                <fullName>Expired</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Exclude_from_Spending_at__c.field-meta.xml
<CustomField>
    <fullName>Exclude_from_Spending_at__c</fullName>
    <formula>ADDMONTHS( CloseDate ,12 )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Exclude from Spending at :</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Months_Included__c.field-meta.xml
<CustomField>
    <fullName>Months_Included__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Included in Total Spending 12 months or not</description>
    <label>Months Included</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Total_Spending_on_Discretionary_Product__c.field-meta.xml
<CustomField>
    <fullName>Total_Spending_on_Discretionary_Product__c</fullName>
    <label>Total Spending on Discretionary Product</label>
    <summarizedField>OpportunityLineItem.Amount__c</summarizedField>
    <summaryFilterItems>
        <field>OpportunityLineItem.Product_Category__c</field>
        <operation>equals</operation>
        <value>Discretionary</value>
    </summaryFilterItems>
    <summaryForeignKey>OpportunityLineItem.OpportunityId</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/recordTypes/B2C.recordType-meta.xml
<RecordType>
    <fullName>B2C</fullName>
    <active>true</active>
    <businessProcess>B2C</businessProcess>
    <description>B2C Opportunity Record</description>
    <label>B2C</label>
</RecordType>

unpackaged/main/default/classes/ExcludeFromSpending_Batch.cls
/*------------------------------------------------------------
Author      : Steven Junaidy
Company     : Viseo Asia PTE LTD
Description : Batch job to exclude opportunity from total spending(last 12 months) calculation.
History
<Date>      <Authors Name>     <Brief Description of Change>
------------------------------------------------------------*/
global class ExcludeFromSpending_Batch implements Database.Batchable<sObject>, Database.Stateful{
    global date ExcludedDate = date.today();
    global string query;
    global String paramId = null;
    
    global ExcludeFromSpending_Batch(String AccountId, String BatchName){
        
        if(!Test.isRunningTest()){
            if(BatchName!=null && BatchName!= ''){
                system.abortJob(BatchName);
            }
        }
        System.debug('ExcludeFromSpending Batch Start');
        paramId = AccountId;
        query = label.PG_LABEL_OppExclude_q;
        if(AccountId != null && AccountId != ''){
            this.query = 'select Id from Account where (Status__c != \'Cancelled\' AND Status__c != \'Suspended\' AND Status__c != \'Expired\' AND Status__c != \'Pending\') and Customer_Type__c = \'Agent\' and Id in (\''+paramId+'\')';
        }
        else{
            if(query == 'null'){
                this.query = 'select id from Account where (Status__c != \'Cancelled\' AND Status__c != \'Suspended\' AND Status__c != \'Expired\' AND Status__c != \'Pending\') and Customer_Type__c = \'Agent\'';
            }
        }
        system.debug('query:' + query);
    }
    global System.Iterable<sObject> start(Database.BatchableContext jobId) {
        return Database.getQueryLocator(query);
    }
    
    global Void execute(Database.BatchableContext jobId, List<Account> AcctList) {
        system.Debug('Execute: ExcludeFromSpending_Batch');
        List<Opportunity> ToUpdateOpp = new List<Opportunity>();
        Map<String,String> MapOppRT = new Map<String,String>();
        
        for (RecordType rt : [SELECT Id,Name FROM RecordType WHERE SObjectType='Opportunity']){
            MapOppRT.put(rt.Name,rt.Id);
        }
        for(Account acct : AcctList){
            for(Opportunity Opp: [SELECT id,Recordtypeid,Months_Included__c,Exclude_from_Spending_at__c,total_spending_on_Discretionary_Product__c,Account.Status__c FROM Opportunity WHERE isWON= TRUE and Months_Included__c = TRUE and Exclude_from_Spending_at__c < :ExcludedDate and AccountId = :acct.id]){
                //for(Opportunity Opp : recordList) {
                //Opportunity Opp = (Opportunity)obj;
                system.debug('Opp.Months_Included__c:' + Opp.Months_Included__c);
                system.debug('Opp.recordtypeid:' + Opp.recordtypeid);
                system.debug('mapOppRT.get(\'B2C\'):' + mapOppRT.get('B2C'));
                system.debug('Exclude_from_Spending_at__c:' + Opp.Exclude_from_Spending_at__c);
                system.debug('ExcludedDate:' + ExcludedDate);
                system.debug('Opp.total_spending_on_Discretionary_Product__c:' + Opp.total_spending_on_Discretionary_Product__c);
                if(Opp.recordtypeid == mapOppRT.get('B2C')){ 
                    Opp.Months_Included__c = FALSE;
                    ToUpdateOpp.add(Opp);
                }
            }
            if(toUpdateOpp.size()>0){
                Update toUpdateOpp;
            }
            //}
        }
    }
    global Void finish(Database.BatchableContext jobId) {
        
        //include
        if(paramId!=null && paramId != ''){
            OppIncludeSubscription_Batch x = new OppIncludeSubscription_Batch(paramId);
            database.executeBatch(x);
        }
    }
}