unpackaged/main/default/objects/Account/fields/Customer_Type__c.field-meta.xml
<CustomField>
    <fullName>Customer_Type__c</fullName>
    <description>Created a custom field as standard field &#39;Type&#39; cannot be mapped in lead mapping</description>
    <label>Customer Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Agent</fullName>
            </value>
            <value>
                <fullName>Owner</fullName>
            </value>
            <value>
                <fullName>Agency</fullName>
            </value>
            <value>
                <fullName>Developer</fullName>
                <default>true</default>
                <label>Developer</label>
            </value>
            <value>
                <fullName>Non-Property</fullName>
            </value>
            <value>
                <fullName>Consumer</fullName>
            </value>
            <value>
                <fullName>Media Agency</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Account/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>Denotes the status of an agent in the agent lifecycle</description>
    <inlineHelpText>Denotes the status of an agent in the agent lifecycle</inlineHelpText>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Trial</fullName>
            </value>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Downgraded</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Suspended</fullName>
            </value>
            <value>
                <fullName>Expired</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/OMC_Approved_Date__c.field-meta.xml
<CustomField>
    <fullName>OMC_Approved_Date__c</fullName>
    <label>OMC Approved Date</label>
    <type>DateTime</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Product_Category__c.field-meta.xml
<CustomField>
    <fullName>Product_Category__c</fullName>
    <label>Product Category</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Awards</fullName>
            </value>
            <value>
                <fullName>China Solutions</fullName>
            </value>
            <value>
                <fullName>Events</fullName>
            </value>
            <value>
                <fullName>Agent Discretionary</fullName>
            </value>
            <value>
                <fullName>Agent Subscriptions</fullName>
            </value>
            <value>
                <fullName>Developer Listings</fullName>
            </value>
            <value>
                <fullName>Online Advertising</fullName>
            </value>
            <value>
                <fullName>Marketing Services</fullName>
            </value>
            <value>
                <fullName>Database Marketing</fullName>
            </value>
            <value>
                <fullName>Content</fullName>
            </value>
            <value>
                <fullName>FinTech</fullName>
            </value>
            <value>
                <fullName>FastKey</fullName>
            </value>
            <value>
                <fullName>Data MPD</fullName>
            </value>
            <value>
                <fullName>Discretionary</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Push_To_NetSuite__c.field-meta.xml
<CustomField>
    <fullName>Push_To_NetSuite__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Push To NetSuite</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/recordTypes/B2C.recordType-meta.xml
<RecordType>
    <fullName>B2C</fullName>
    <active>true</active>
    <businessProcess>B2C</businessProcess>
    <description>B2C Opportunity Record</description>
    <label>B2C</label>
</RecordType>

unpackaged/main/default/objects/Product2/fields/Product_Category__c.field-meta.xml
<CustomField>
    <fullName>Product_Category__c</fullName>
    <description>Denotes the category of B2C products</description>
    <inlineHelpText>Denotes the category of B2C products</inlineHelpText>
    <label>Product Category</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Subscription</fullName>
            </value>
            <value>
                <fullName>Discretionary</fullName>
            </value>
            <value>
                <fullName>Repost</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Product2/fields/Push_To_NetSuite__c.field-meta.xml
<CustomField>
    <fullName>Push_To_NetSuite__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Push To NetSuite</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/classes/AmountRollUpBatch.cls
/**
@name			AmountRollUpBatch
@Description	Schedulable batch class to update the roll up fields (like CSS amount and pro rate)
@Version 		1.0
@reference 		PGAUTO-6559
**/
global class AmountRollUpBatch implements Database.Batchable<sObject>, System.Schedulable {
    
    global final static string B2C_OPP_RECORDTYPEiD = RecordTypeSelector.getRecordTypeId('Opportunity', 'B2C');
    global final static string B2C_SS_OPP_RECORDTYPEiD = RecordTypeSelector.getRecordTypeId('Opportunity', 'B2C Self-Serve');
    
    global Database.QueryLocator start(Database.BatchableContext jobId) {
        String activeOppQuery = label.PG_LABEL_OppExclude_q;
        if(activeOppQuery.equals('null')) {
            activeOppQuery = 'SELECT Id FROM Account WHERE (Status__c != \'Cancelled\' AND Status__c != \'Suspended\' AND Status__c != \'Expired\' ';
            activeOppQuery += 'AND Status__c != \'Pending\') and Customer_Type__c = \'Agent\'';
        }
        return Database.getQueryLocator(activeOppQuery);
    }
    
    global void execute(Database.BatchableContext BC, List<Account> activeAgents) {
        Set<Id> accIds = new Set<Id>();
        for(Account acc : activeAgents) {
            accIds.add(acc.Id); 
        }

        Map<Id,Opportunity> accIdsVsB2cOpp = new Map<Id,Opportunity>();
        Map<Id,Opportunity> accIdsVsB2cSSOpp = new Map<Id,Opportunity>();
        
        if(!accIds.isEmpty()) {
            for(Opportunity opp:[SELECT Id, AccountId, OMC_Approved_Date__c,
                                 (SELECT Id, Push_to_NetSuite__c 
                                  FROM OpportunityLineItems 
                                  WHERE Product2.Product_Category__c ='Subscription' 
                                  AND Complimentary__c = false
                                  AND Push_to_NetSuite__c = true
                                 ) FROM Opportunity
                                 WHERE AccountId IN: accIds
                                 AND IsWon = true
                                 AND RecordTypeId =: B2C_OPP_RECORDTYPEiD
                                 ORDER BY OMC_Approved_Date__c DESC
                                ]
               ) { 
                   if(!opp.OpportunityLineItems.isEmpty() && !accIdsVsB2cOpp.containsKey(opp.AccountId)) {
                       accIdsVsB2cOpp.put(opp.AccountId,opp);
                   }
               }
            
            for(Opportunity opp:[SELECT Id, AccountId, CloseDate,
                                 (SELECT Id, Push_to_NetSuite__c 
                                  FROM OpportunityLineItems 
                                  WHERE Product2.Product_Category__c ='Subscription' 
                                  AND Complimentary__c = false
                                  AND Push_to_NetSuite__c = true
                                 ) FROM Opportunity
                                 WHERE AccountId IN: accIds
                                 AND StageName = 'Converted'
                                 AND RecordTypeId =: B2C_SS_OPP_RECORDTYPEiD
                                 ORDER BY CloseDate DESC
                                ]
               ) { 
                   if(!opp.OpportunityLineItems.isEmpty() && !accIdsVsB2cSSOpp.containsKey(opp.AccountId)) {
                       accIdsVsB2cSSOpp.put(opp.AccountId,opp);
                   }
               }
            
        }
        for(Account eachAcc : activeAgents) {
            if(!accIdsVsB2cOpp.isEmpty() && 
               accIdsVsB2cOpp.containsKey(eachAcc.Id) &&
               !accIdsVsB2cSSOpp.isEmpty() && 
               accIdsVsB2cSSOpp.containsKey(eachAcc.Id)
              ) {
                  if(accIdsVsB2cOpp.get(eachAcc.Id).OMC_Approved_Date__c > accIdsVsB2cSSOpp.get(eachAcc.Id).CloseDate) {
                      AmountRollUpHandler.populateClosedWonFields(eachAcc.Id,accIdsVsB2cOpp.get(eachAcc.Id).Id);
                  } else if(accIdsVsB2cOpp.get(eachAcc.Id).OMC_Approved_Date__c < accIdsVsB2cSSOpp.get(eachAcc.Id).CloseDate) {
                      AmountRollUpHandler.populateConvertedSSFields(accIdsVsB2cSSOpp.get(eachAcc.Id).Id);
                  }
              } else if(!accIdsVsB2cOpp.isEmpty() && accIdsVsB2cOpp.containsKey(eachAcc.Id) ) {
                  AmountRollUpHandler.populateClosedWonFields(eachAcc.Id,accIdsVsB2cOpp.get(eachAcc.Id).Id);      
              } else if(!accIdsVsB2cSSOpp.isEmpty() && accIdsVsB2cSSOpp.containsKey(eachAcc.Id)) {
                  AmountRollUpHandler.populateConvertedSSFields(accIdsVsB2cSSOpp.get(eachAcc.Id).Id); 
              }
        }
    }
    
    global void finish(Database.BatchableContext BC) {
          
    }
    
    global Void execute(System.SchedulableContext context) {
        Database.executeBatch(new AmountRollUpBatch(), 1);
    }
}