unpackaged/main/default/objects/Account/fields/isSuspended__c.field-meta.xml
<CustomField>
    <fullName>isSuspended__c</fullName>
    <defaultValue>false</defaultValue>
    <label>isSuspended</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>Denotes the status of an agent in the agent lifecycle</description>
    <inlineHelpText>Denotes the status of an agent in the agent lifecycle</inlineHelpText>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Trial</fullName>
            </value>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Downgraded</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Suspended</fullName>
            </value>
            <value>
                <fullName>Expired</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Account/fields/Suspended_Date_Time__c.field-meta.xml
<CustomField>
    <fullName>Suspended_Date_Time__c</fullName>
    <label>Suspended Date Time</label>
    <type>DateTime</type>
</CustomField>

unpackaged/main/default/classes/AccountActions.cls
/*******************************************************************
 *	Author: Suraj Bisht
 *  Class Name: AccountActions
 *  Description: Class to define invocable action for account object
 * 	Test Class: AccountActions_Test
 ******************************************************************/
public with sharing class AccountActions {
    
 /*******************************************************************
 *	Author: Suraj Bisht
 *  Description: Method will update the account status 
 ******************************************************************/
    @InvocableMethod(label='Update account status' description='Update account Status')
    public static void updateAccountStatus(List<InputParamCls> inputs) {
        if(inputs != null && !inputs.isEmpty()){
            list<Account> listOfAccountToUpdate=new list<Account>();
            for(InputParamCls input:inputs){
                Account objAccount=new Account(Id=input.accountId,Status__c=input.status);
                if(objAccount.Status__c == 'Suspended'){
                    objAccount.Suspended_Date_Time__c=Datetime.now();
                    objAccount.isSuspended__c=true;
                }
                listOfAccountToUpdate.add(objAccount);
            } 
            //Avoiding partial dml to show any error if occurred to user on screen flow
            update listOfAccountToUpdate;
        }
    } 
/*******************************************************************
 *	Author: Suraj Bisht
 *  Description: Class defining the input paramater that can be passed to apex from flow
******************************************************************/
    public class InputParamCls{
        @InvocableVariable public Id accountId;
        @InvocableVariable public String status;    
    }
}