unpackaged/main/default/objects/Account/fields/NetSuite_Id__c.field-meta.xml
<CustomField>
    <fullName>NetSuite_Id__c</fullName>
    <externalId>true</externalId>
    <label>NetSuite Id</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

unpackaged/main/default/objects/Account/fields/Subsidiary_Type__c.field-meta.xml
<CustomField>
    <fullName>Subsidiary_Type__c</fullName>
    <defaultValue>if(ISPICKVAL($User.Subsidiary__c,&#39;MyProperty Data Sdn. Bhd.&#39;),&#39;MPD&#39;,&#39;&#39;)</defaultValue>
    <label>Subsidiary Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>MPD</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Account/fields/Tax_Reg_Number__c.field-meta.xml
<CustomField>
    <fullName>Tax_Reg_Number__c</fullName>
    <description>Denotes tax registration number of an account</description>
    <inlineHelpText>Denotes tax registration number of an account</inlineHelpText>
    <label>GST REG. / VAT REG. / NPWP</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Account/recordTypes/Agency.recordType-meta.xml
<RecordType>
    <fullName>Agency</fullName>
    <active>true</active>
    <label>Agency</label>
</RecordType>

unpackaged/main/default/objects/Billing_Entity__c/Billing_Entity__c.object-meta.xml
<CustomObject>
    <label>Billing Entity</label>
    <nameField>
        <displayFormat>NS-{0000}</displayFormat>
        <label>Netsuite ID Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Billing Entities</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Billing_Entity__c/fields/NetSuite_ID__c.field-meta.xml
<CustomField>
    <fullName>NetSuite_ID__c</fullName>
    <label>NetSuite ID</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Contact/fields/NetSuite_Id__c.field-meta.xml
<CustomField>
    <fullName>NetSuite_Id__c</fullName>
    <externalId>true</externalId>
    <label>NetSuite_Id</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Billing_Entity__c.field-meta.xml
<CustomField>
    <fullName>Billing_Entity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Billing Entity</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Opportunities (Billing Entity)</relationshipLabel>
    <relationshipName>Opportunities8</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Product_Category__c.field-meta.xml
<CustomField>
    <fullName>Product_Category__c</fullName>
    <label>Product Category</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Awards</fullName>
            </value>
            <value>
                <fullName>China Solutions</fullName>
            </value>
            <value>
                <fullName>Events</fullName>
            </value>
            <value>
                <fullName>Agent Discretionary</fullName>
            </value>
            <value>
                <fullName>Agent Subscriptions</fullName>
            </value>
            <value>
                <fullName>Developer Listings</fullName>
            </value>
            <value>
                <fullName>Online Advertising</fullName>
            </value>
            <value>
                <fullName>Marketing Services</fullName>
            </value>
            <value>
                <fullName>Database Marketing</fullName>
            </value>
            <value>
                <fullName>Content</fullName>
            </value>
            <value>
                <fullName>FinTech</fullName>
            </value>
            <value>
                <fullName>FastKey</fullName>
            </value>
            <value>
                <fullName>Data MPD</fullName>
            </value>
            <value>
                <fullName>Discretionary</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Re_print_Contract__c.field-meta.xml
<CustomField>
    <fullName>Re_print_Contract__c</fullName>
    <defaultValue>false</defaultValue>
    <description>This field indicates whether a new contract needs to be generated and reprint.
Update Yes - whenever oppty / line items is changed
Update No - after contract is generated (script runs to copy Oppty to Quotes)</description>
    <label>Re-print Contract</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/SO_for_Customer_Approval__c.field-meta.xml
<CustomField>
    <fullName>SO_for_Customer_Approval__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>SO for Customer Approval</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>csmso__Sales_Order__c.csmso__Opportunity__r.Id</field>
            <operation>equals</operation>
            <valueField>$Source.Id</valueField>
        </filterItems>
        <infoMessage>Select a Sales Order that is attached to this Opportunity.</infoMessage>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>csmso__Sales_Order__c</referenceTo>
    <relationshipLabel>Opportunities (SO for Customer Approval)</relationshipLabel>
    <relationshipName>Opportunities1</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Subsidiary_Type__c.field-meta.xml
<CustomField>
    <fullName>Subsidiary_Type__c</fullName>
    <label>Subsidiary Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>iPP</fullName>
            </value>
            <value>
                <fullName>Property Guru</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Opportunity/recordTypes/B2B.recordType-meta.xml
<RecordType>
    <fullName>B2B</fullName>
    <active>true</active>
    <businessProcess>B2B</businessProcess>
    <description>B2B Opportunity Record</description>
    <label>B2B</label>
</RecordType>

unpackaged/main/default/classes/CS_OppCustomerApprovalControllerTest.cls
@IsTest
private class CS_OppCustomerApprovalControllerTest {
	private static Opportunity opp;
	private static csmso__Sales_Order__c so;

	private static void createTestData() {
		CS_utl_User.disableAllTriggers(UserInfo.getUserId());

		csmso__SalesOrderAPI__c soapi = TestDataSetupSO.createSalesOrderAPI();
		insert soapi;

		cscfga__Product_Category__c testProdCateg = TestDataSetupTargetables.createProdCateg();
		insert testProdCateg;

		cscfga__Product_Definition__c testProDef = TestDataSetupTargetables.createProDef(testProdCateg);
		insert testProDef;

		cscfga__Attribute_Definition__c testAttrDef = TestDataSetupTargetables.createAttrDef(testProDef);
		insert testAttrDef;

		Account acc = TestDataSetupTargetables.createAccount();
             acc.RecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('B2B - Account').getRecordTypeId();
		acc.NetSuite_Id__c = 'CUSTOMER APPROVAL TEST CONTACT ID';
        
        
        acc.Phone = '2345';
		insert acc;
        Account childAcc = TestDataSetupTargetables.createAccount();
        childAcc.name='child acc';
        childAcc.Tax_Reg_Number__c ='tyg';
        childAcc.RecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('B2B - Account').getRecordTypeId();
        childAcc.NetSuite_Id__c = 'CUSTOMED';
        childAcc.ParentId = acc.id;

        childAcc.Phone = '2345';
        insert childAcc;
		Account agency = TestDataSetupTargetables.createAccount();
		agency.Type = 'Media Agency';
        agency.Phone = '2345';
		insert agency;

		Contact con = TestDataSetupTargetables.createContact(acc);
		con.NetSuite_Id__c = 'TEST CONTACT ID'; //CUSTOM VALIDATION ON CONTACT ROLES
		insert con;

		opp = TestDataSetupTargetables.createOpportunity(acc, con);
        opp.RecordTypeId = Schema.SObjectType.Opportunity.getRecordTypeInfosByName().get('B2B').getRecordTypeId();
		opp.Re_print_Contract__c = false;
        opp.Product_category__c='Discretionary';
        opp.billing_entity__c = childAcc.id;
        opp.Subsidiary_Type__c = 'iPP';
		insert opp;

		so = TestDataSetupTargetables.createSalesOrder(acc, opp);
		so.csmso__Status__c = 'Ready For Customer Approval';
		insert so;
	}

	private static void createOppContactRoles() {
		Contact con = [SELECT Id FROM Contact LIMIT 1];

		List<OpportunityContactRole> oppContactRoles = new List<OpportunityContactRole>{
				new OpportunityContactRole(ContactId= con.Id,Role = CS_OppCustomerApprovalController.BILLING_CONTACT,IsPrimary=true,OpportunityId = opp.Id),
				new OpportunityContactRole(ContactId= con.Id,Role = CS_OppCustomerApprovalController.CLIENT_SIGNATORY, OpportunityId = opp.Id)
		};

		insert oppContactRoles;
	}

	@IsTest
	static void testOppCustomerApprovalControllerClickApprove() {
		createTestData();
		createOppContactRoles();
		opp.StageName = 'Negotiating';
		opp.SO_for_Customer_Approval__c = so.Id;
		update opp;

		Test.startTest();
		ApexPages.StandardController stdController = new ApexPages.StandardController(opp);
		ApexPages.currentPage().getParameters().put('oppId', opp.Id);
		ApexPages.currentPage().getParameters().put('buttonClicked', 'Send_Approval_ClickApprove');

		CS_OppCustomerApprovalController oppCustomerApprovalController = new CS_OppCustomerApprovalController(stdController);
		PageReference pageReference = oppCustomerApprovalController.doAction();

		System.assertEquals(pageReference.getUrl(), '/apex/CSCAP__SendFormalEmailForApproval_LE?Id=' + opp.Id);
		Test.stopTest();
	}

	@IsTest
	static void testOppCustomerApprovalControllerManual() {
		createTestData();
		createOppContactRoles();
		opp.StageName = 'Negotiating';
		opp.SO_for_Customer_Approval__c = so.Id;
		update opp;

		Test.startTest();
		ApexPages.StandardController stdController = new ApexPages.StandardController(opp);
		ApexPages.currentPage().getParameters().put('oppId', opp.Id);
		ApexPages.currentPage().getParameters().put('buttonClicked', 'Send_Approval_Manual');

		CS_OppCustomerApprovalController oppCustomerApprovalController = new CS_OppCustomerApprovalController(stdController);
		PageReference pageReference = oppCustomerApprovalController.doAction();

		System.assertEquals(pageReference, null);
		Test.stopTest();
	}

	@IsTest
	static void testOppCustomerApprovalControllerWrongStatus() {
		createTestData();

		Test.startTest();
		ApexPages.StandardController stdController = new ApexPages.StandardController(opp);
		ApexPages.currentPage().getParameters().put('oppId', opp.Id);
		ApexPages.currentPage().getParameters().put('buttonClicked', 'Send_Approval_ClickApprove');

		CS_OppCustomerApprovalController oppCustomerApprovalController = new CS_OppCustomerApprovalController(stdController);
		PageReference pageReference = oppCustomerApprovalController.doAction();

		System.assertEquals(pageReference, null);
		Test.stopTest();
	}
}