unpackaged/main/default/objects/Account/fields/Next_Subscription_Activation_Date__c.field-meta.xml
<CustomField>
    <fullName>Next_Subscription_Activation_Date__c</fullName>
    <description>Denotes the next subscription activation date after a successful purchase of a Agent subscription</description>
    <inlineHelpText>Denotes the next subscription activation date after a successful purchase of a Agent subscription</inlineHelpText>
    <label>Next Subscription Activation Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Count_of_Subscription_Item_new__c.field-meta.xml
<CustomField>
    <fullName>Count_of_Subscription_Item_new__c</fullName>
    <label>Count of Subscription Item</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/OMC_Approved_Date__c.field-meta.xml
<CustomField>
    <fullName>OMC_Approved_Date__c</fullName>
    <label>OMC Approved Date</label>
    <type>DateTime</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Product_Category__c.field-meta.xml
<CustomField>
    <fullName>Product_Category__c</fullName>
    <label>Product Category</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Awards</fullName>
            </value>
            <value>
                <fullName>China Solutions</fullName>
            </value>
            <value>
                <fullName>Events</fullName>
            </value>
            <value>
                <fullName>Agent Discretionary</fullName>
            </value>
            <value>
                <fullName>Agent Subscriptions</fullName>
            </value>
            <value>
                <fullName>Developer Listings</fullName>
            </value>
            <value>
                <fullName>Online Advertising</fullName>
            </value>
            <value>
                <fullName>Marketing Services</fullName>
            </value>
            <value>
                <fullName>Database Marketing</fullName>
            </value>
            <value>
                <fullName>Content</fullName>
            </value>
            <value>
                <fullName>FinTech</fullName>
            </value>
            <value>
                <fullName>FastKey</fullName>
            </value>
            <value>
                <fullName>Data MPD</fullName>
            </value>
            <value>
                <fullName>Discretionary</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/OpportunityLineItem/fields/Actual_Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Actual_Start_Date__c</fullName>
    <formula>if( Start_Date__c &gt;  DATEVALUE(Opportunity.OMC_Approved_Date__c) ,Start_Date__c,DATEVALUE(Opportunity.OMC_Approved_Date__c))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Actual Start Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/OpportunityLineItem/fields/SNo__c.field-meta.xml
<CustomField>
    <fullName>SNo__c</fullName>
    <description>System generated this number for use of grouping parent and child. Also use when print contract, the order of the products will in ascending order. When users delete the products, the number isn&#39;t reused.</description>
    <label>SNo</label>
    <precision>5</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/OpportunityLineItem/fields/Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Start_Date__c</fullName>
    <defaultValue>TODAY()</defaultValue>
    <description>Start Date of the contract for the line item. Map to NetSuite SO.</description>
    <label>Start Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/Product2/fields/Product_Category__c.field-meta.xml
<CustomField>
    <fullName>Product_Category__c</fullName>
    <description>Denotes the category of B2C products</description>
    <inlineHelpText>Denotes the category of B2C products</inlineHelpText>
    <label>Product Category</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Subscription</fullName>
            </value>
            <value>
                <fullName>Discretionary</fullName>
            </value>
            <value>
                <fullName>Repost</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/classes/UpdateNextSubsDateOnAccount_Batch.cls
/*----------------------------------------------------
* Created By : 
* Created On : November 17,2020
* Description : To update Next_Subscription_Activation_Date__c on Account
* UnitTest : UpdateNextSubsDateOnAccount_Batch_Test.apxc
* --------------------------------------------------
*/
global class UpdateNextSubsDateOnAccount_Batch implements Database.Batchable<sObject> {
 
    global Database.QueryLocator start(Database.BatchableContext BC)  {
        String query = 'Select id,AccountId,createdDate,Count_of_Subscription_Item_new__c,Account.Next_Subscription_Activation_Date__c,OMC_Approved_Date__c from Opportunity where Count_of_Subscription_Item_new__c = 1 and stageName=\'Closed Won\' and Account.Next_Subscription_Activation_Date__c = null order by createdDate Desc';
        return Database.getQueryLocator(query);
    }
    
    global void execute(Database.BatchableContext BC,List<Opportunity> scope)  {
        
        Set<Id> oppIdSet = new Set<Id>();
        
        //fetch all ids and store in set
        for(Opportunity opp:scope){oppIdSet.add(opp.Id);}
        
        Map<Id,Account> accUpdateList = new Map<Id,Account>();
        
        List<Opportunity> oppList = new List<Opportunity>([Select Id,stageName,Name,OMC_Approved_Date__c,Account.RecordType.DeveloperName,
                                                           AccountId,
                                                           (select id, SNo__c, OpportunityId,Start_date__c 
                                                           from OpportunityLineItems where  SNO__c != null AND
                                                           Product2.Product_Category__c ='Subscription' Order By SNO__c ASC) 
                                                           from Opportunity where id =:oppIdSet]);
        Date startDate = null;
        Date approvedDate = null;
        System.debug('#opplist# '+oppList);
        if(!oppList.isEmpty()){
        for(Opportunity newOpp:oppList){
				System.debug('#inside opplist loop# '+oppList);
                if(newOpp.OMC_Approved_Date__c!=null) {
                    approvedDate = date.newInstance(newOpp.OMC_Approved_Date__c.year(),newOpp.OMC_Approved_Date__c.Month(),
                                                    newOpp.OMC_Approved_Date__c.Day());
                }
            
                if(newOpp.OpportunityLineItems.size() >= 1){
                    //check for lowest Integer SNO
                    OpportunityLineItem oli = BatchToUpdateNextSubscriptionActivation.getOLIwithLowestSnoWhole(newOpp.OpportunityLineItems);
                    
                    //DEPENDENCY of field Actual start date (Actual_Start_Date__c on OLI)
                    //Please update logic below if there is any change in Actual_Start_Date__c.
                    if(oli != null){
                        if(oli.Start_Date__c > approvedDate ){
                            startDate =  oli.Start_date__c; 
                        }
                        else {
                            startDate =  approvedDate;
                        }
                        
                    }
                }
                if(startDate !=null){
                    
                    //set Next Subscription Activation Date for all the accounts whose oppty is closed won with above conditions.
                    if(newOpp.Account.RecordType.DeveloperName == 'Agent'){
                        Account acc = new Account(Id = newOpp.AccountId,Next_Subscription_Activation_Date__c = startDate);
                        accUpdateList.put(acc.Id,acc);
                    }    
                }
        }//for loop ends
        Database.update(accUpdateList.values(),false);
    	}
        
    }
    global void finish(Database.BatchableContext BC)  {
        
    }
}