unpackaged/main/default/objects/Account/fields/Next_Subscription_Activation_Date__c.field-meta.xml
<CustomField>
    <fullName>Next_Subscription_Activation_Date__c</fullName>
    <description>Denotes the next subscription activation date after a successful purchase of a Agent subscription</description>
    <inlineHelpText>Denotes the next subscription activation date after a successful purchase of a Agent subscription</inlineHelpText>
    <label>Next Subscription Activation Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/Subscription_Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Subscription_Start_Date__c</fullName>
    <description>Denotes the start date of agent&#39;s current subscription</description>
    <inlineHelpText>Denotes the start date of agent&#39;s current subscription</inlineHelpText>
    <label>Subscription Start Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Count_of_Subscription_Item_new__c.field-meta.xml
<CustomField>
    <fullName>Count_of_Subscription_Item_new__c</fullName>
    <label>Count of Subscription Item</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/OMC_Approved_Date__c.field-meta.xml
<CustomField>
    <fullName>OMC_Approved_Date__c</fullName>
    <label>OMC Approved Date</label>
    <type>DateTime</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Product_Category__c.field-meta.xml
<CustomField>
    <fullName>Product_Category__c</fullName>
    <label>Product Category</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Awards</fullName>
            </value>
            <value>
                <fullName>China Solutions</fullName>
            </value>
            <value>
                <fullName>Events</fullName>
            </value>
            <value>
                <fullName>Agent Discretionary</fullName>
            </value>
            <value>
                <fullName>Agent Subscriptions</fullName>
            </value>
            <value>
                <fullName>Developer Listings</fullName>
            </value>
            <value>
                <fullName>Online Advertising</fullName>
            </value>
            <value>
                <fullName>Marketing Services</fullName>
            </value>
            <value>
                <fullName>Database Marketing</fullName>
            </value>
            <value>
                <fullName>Content</fullName>
            </value>
            <value>
                <fullName>FinTech</fullName>
            </value>
            <value>
                <fullName>FastKey</fullName>
            </value>
            <value>
                <fullName>Data MPD</fullName>
            </value>
            <value>
                <fullName>Discretionary</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/OpportunityLineItem/fields/Actual_Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Actual_Start_Date__c</fullName>
    <formula>if( Start_Date__c &gt;  DATEVALUE(Opportunity.OMC_Approved_Date__c) ,Start_Date__c,DATEVALUE(Opportunity.OMC_Approved_Date__c))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Actual Start Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/OpportunityLineItem/fields/SNo__c.field-meta.xml
<CustomField>
    <fullName>SNo__c</fullName>
    <description>System generated this number for use of grouping parent and child. Also use when print contract, the order of the products will in ascending order. When users delete the products, the number isn&#39;t reused.</description>
    <label>SNo</label>
    <precision>5</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/Product2/fields/Product_Category__c.field-meta.xml
<CustomField>
    <fullName>Product_Category__c</fullName>
    <description>Denotes the category of B2C products</description>
    <inlineHelpText>Denotes the category of B2C products</inlineHelpText>
    <label>Product Category</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Subscription</fullName>
            </value>
            <value>
                <fullName>Discretionary</fullName>
            </value>
            <value>
                <fullName>Repost</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/classes/BatchToUpdateNextSubscriptionActivation.cls
/*
TestClass : BatchToUpdateNextSAD_Test
*/
public class BatchToUpdateNextSubscriptionActivation implements DataBase.Batchable<Sobject> {
    
    
    public Database.QueryLocator start(Database.BatchableContext bc){
        
        String query = 'select Id,Next_Subscription_Activation_Date__c,Subscription_Start_Date__c,(select Id,StageName,Count_of_Subscription_Item_new__c,OMC_Approved_Date__c  from Opportunities where StageName = \'Closed Won\' and Count_of_Subscription_Item_new__c > 1 order by OMC_Approved_Date__c desc limit 1 ) from Account where RecordType.DeveloperName= \'Agent\' AND  Next_Subscription_Activation_Date__c = null';
        return DataBase.getQueryLocator(query);      
    }
    
    public void execute(Database.BatchableContext bc, List<Account> updateAccountList){
        
        Set<Id> oppId = new Set<Id>();
        List<Account> accListToUpdate = new List<Account>();
        for(Account acc : updateAccountList){
            if(acc.Opportunities.size()>0 && !acc.Opportunities.isEmpty() && acc.Opportunities[0].Count_of_Subscription_Item_new__c >1)
                oppId.add(acc.Opportunities[0].Id);
        }
        for(Opportunity opp : [select id,Name,AccountId,(select id, SNO__c,Actual_Start_date__c from OpportunityLineItems where Actual_Start_date__c != null AND SNO__c != null AND Product2.Product_Category__c='Subscription' Order By SNO__c ASC) from Opportunity where id IN :oppId  ]){
            
            OpportunityLineItem getOLI = getOLIwithLowestSnoWhole(opp.OpportunityLineItems);
            if(getOLI != null)
            accListToUpdate.add(new Account(id=opp.AccountId,Next_Subscription_Activation_Date__c = getOLI.Actual_Start_date__c));
        }
        if(!accListToUpdate.isEmpty())
        update accListToUpdate;
    }
    
    public void finish(Database.BatchableContext bc){
        
    }
    
    public static OpportunityLineItem getOLIwithLowestSnoWhole(list<OpportunityLineItem> SNoList){
        OpportunityLineItem oliReturn;
        for(OpportunityLineItem oli : SNoList){
            if(oli.Sno__c == Integer.valueOf(oli.Sno__c)){
                oliReturn = oli;
                break;
            }
        }
        
        return oliReturn;
    }
}