unpackaged/main/default/objects/Account/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>Denotes the status of an agent in the agent lifecycle</description>
    <inlineHelpText>Denotes the status of an agent in the agent lifecycle</inlineHelpText>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Trial</fullName>
            </value>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Downgraded</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Suspended</fullName>
            </value>
            <value>
                <fullName>Expired</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Account/recordTypes/B2B_Account.recordType-meta.xml
<RecordType>
    <fullName>B2B_Account</fullName>
    <active>true</active>
    <label>B2B - Account</label>
</RecordType>

unpackaged/main/default/objects/Contact/fields/MC_Sync__c.field-meta.xml
<CustomField>
    <fullName>MC_Sync__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Denotes whether contact needs to be sync to marketing cloud</description>
    <inlineHelpText>Denotes whether contact needs to be sync to marketing cloud</inlineHelpText>
    <label>MC Sync</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/classes/BatchUpdateOppFieldHis.cls
/*
 * TestClass : BatchUpdateOppFieldHis_Test
 */
global class BatchUpdateOppFieldHis implements Database.Batchable<sObject> {
    
    public Database.QueryLocator start(Database.BatchableContext BC) {
        
        String query = 'Select id,MC_Sync__c,ispersonAccount,Account.IspersonAccount,Account.name,Account.recordType.DeveloperName from Contact where (ispersonAccount = true AND Account.status__c IN (\'Active\',\'Downgraded\',\'Trial\')) OR Account.recordType.DeveloperName = \'B2B_Account\'';
        
        return Database.getQueryLocator(query);
    }
    
    public void execute(Database.BatchableContext BC, List<Contact> contactList) {
        
        List<Contact> contactListToUpdate = new List<Contact>();
        for(Contact eachContact : contactList){
            
            Contact con = new Contact(id = eachContact.id);
            con.MC_Sync__c = true;
            contactListToUpdate.add(con);
        }
        if(contactListToUpdate.size()>0)
            Database.update(contactListToUpdate, false) ;
            
    }
    public void finish(Database.BatchableContext BC){
        
    }
}