unpackaged/main/default/objects/Account/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>Denotes the status of an agent in the agent lifecycle</description>
    <inlineHelpText>Denotes the status of an agent in the agent lifecycle</inlineHelpText>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Trial</fullName>
            </value>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Downgraded</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Suspended</fullName>
            </value>
            <value>
                <fullName>Expired</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Bill_Run__c/Bill_Run__c.object-meta.xml
<CustomObject>
    <description>Bill Run object is used to schedule Billing Date. With that he is also setting Lock and Auto-Reconciliation Date. Also contains Calendar Type and Status fields.</description>
    <label>Bill Run</label>
    <nameField>
        <displayFormat>BR-{00000000}</displayFormat>
        <label>Bill Run No</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Bill Runs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Bill_Run__c/fields/Billing_Date__c.field-meta.xml
<CustomField>
    <fullName>Billing_Date__c</fullName>
    <description>Set the Billing Date or the Revenue Period End Date of Bill Run.</description>
    <inlineHelpText>Set the Billing Date or the Revenue Period End Date of Bill Run.</inlineHelpText>
    <label>Billing / Revenue Date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/Bill_Run__c/fields/Reference_Date__c.field-meta.xml
<CustomField>
    <fullName>Reference_Date__c</fullName>
    <label>Reference Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/Bill_Run__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>Status of the Bill Run.</description>
    <inlineHelpText>Status of the Bill Run.</inlineHelpText>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Scheduled</fullName>
                <default>true</default>
                <label>Scheduled</label>
            </value>
            <value>
                <fullName>Locking Bill Schedules</fullName>
            </value>
            <value>
                <fullName>Auto-Reconciliating</fullName>
            </value>
            <value>
                <fullName>Complete</fullName>
            </value>
            <value>
                <fullName>Consolidating Actuals</fullName>
                <isActive>false</isActive>
                <label>Consolidating Actuals</label>
            </value>
            <value>
                <fullName>Recalculating Billing Schedules</fullName>
                <isActive>false</isActive>
                <label>Recalculating Billing Schedules</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/CS_Billing_Schedule__c/CS_Billing_Schedule__c.object-meta.xml
<CustomObject>
    <label>Billing Schedule</label>
    <nameField>
        <displayFormat>BIL-{00000000}</displayFormat>
        <label>Billing Schedule Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Billing Schedule</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/CS_Billing_Schedule__c/fields/CS_Sales_Order_Schedule__c.field-meta.xml
<CustomField>
    <fullName>CS_Sales_Order_Schedule__c</fullName>
    <label>CS Sales Order Schedule</label>
    <referenceTo>CS_Sales_Order_Schedule__c</referenceTo>
    <relationshipName>Billing_Schedule_Headers</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/CS_Billing_Schedule__c/fields/Sales_Order__c.field-meta.xml
<CustomField>
    <fullName>Sales_Order__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Link to the related Sales Order</description>
    <inlineHelpText>Link to the related Sales Order</inlineHelpText>
    <label>Sales Order</label>
    <referenceTo>csmso__Sales_Order__c</referenceTo>
    <relationshipName>Billing_Schedule_Headers</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/CS_Billing_Schedule_Item__c/CS_Billing_Schedule_Item__c.object-meta.xml
<CustomObject>
    <description>Individiual details for one billing period for one line within a Sales Order</description>
    <label>Billing Schedule Item</label>
    <nameField>
        <displayFormat>BILI-{00000000}</displayFormat>
        <label>Billing Schedule Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Billing Schedule Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/CS_Billing_Schedule_Item__c/fields/Bill_Run__c.field-meta.xml
<CustomField>
    <fullName>Bill_Run__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Bill Run</label>
    <referenceTo>Bill_Run__c</referenceTo>
    <relationshipLabel>Billing Schedule Items</relationshipLabel>
    <relationshipName>Billing_Schedule_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/CS_Billing_Schedule_Item__c/fields/Billing_Calendar__c.field-meta.xml
<CustomField>
    <fullName>Billing_Calendar__c</fullName>
    <description>Billing Calendar as defined in the Sales Order
- Standard
- Broadcast</description>
    <inlineHelpText>Billing Calendar as defined in the Sales Order
- Standard
- Broadcast</inlineHelpText>
    <label>Billing Calendar</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Standard</fullName>
            </value>
            <value>
                <fullName>Broadcast</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/CS_Billing_Schedule_Item__c/fields/Billing_Date__c.field-meta.xml
<CustomField>
    <fullName>Billing_Date__c</fullName>
    <description>Billing Date based on the Billing Rule + Billing Calendar.
-Monthly Standard  : Last day of each Standard Calendar Month from SO line item  Start to End of Campaign.
-Monthly Broadcast: Last day of each Broadcast Calendar Month from SO line item  Start to End of Campaign</description>
    <inlineHelpText>Billing Date based on the Billing Rule + Billing Calendar</inlineHelpText>
    <label>Billing Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/CS_Billing_Schedule_Item__c/fields/Billing_Schedule__c.field-meta.xml
<CustomField>
    <fullName>Billing_Schedule__c</fullName>
    <label>Billing Schedule</label>
    <referenceTo>CS_Billing_Schedule__c</referenceTo>
    <relationshipLabel>Billing Schedule Items</relationshipLabel>
    <relationshipName>Billing_Schedule_Items</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/CS_Billing_Schedule_Item__c/fields/Sales_Order__c.field-meta.xml
<CustomField>
    <fullName>Sales_Order__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Link to the related Sales Order.</description>
    <inlineHelpText>Link to the related Sales Order.</inlineHelpText>
    <label>Sales Order</label>
    <referenceTo>csmso__Sales_Order__c</referenceTo>
    <relationshipLabel>Billing Schedule Item</relationshipLabel>
    <relationshipName>CS_Billing_Schedule_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/CS_Billing_Schedule_Item__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>Billing Schedule Status.</description>
    <inlineHelpText>Billing Schedule Status</inlineHelpText>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Open</fullName>
            </value>
            <value>
                <fullName>Locked</fullName>
            </value>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Ready</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
            <value>
                <fullName>Forecast</fullName>
            </value>
            <value>
                <fullName>Pending Closure</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/CS_Sales_Order_Schedule__c/CS_Sales_Order_Schedule__c.object-meta.xml
<CustomObject>
    <label>Sales Order Schedule</label>
    <nameField>
        <displayFormat>RS-{00000000}</displayFormat>
        <label>Sales Order Schedules Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sales Order Schedules</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/CS_Sales_Order_Schedule__c/fields/Billing_Calendar__c.field-meta.xml
<CustomField>
    <fullName>Billing_Calendar__c</fullName>
    <formula>TEXT(Sales_Order__r.Billing_Calendar__c)</formula>
    <label>Billing Calendar</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/CS_Sales_Order_Schedule__c/fields/Billing_Date__c.field-meta.xml
<CustomField>
    <fullName>Billing_Date__c</fullName>
    <label>Billing Date</label>
    <summarizedField>CS_Billing_Schedule__c.Next_Billing_Date__c</summarizedField>
    <summaryForeignKey>CS_Billing_Schedule__c.CS_Sales_Order_Schedule__c</summaryForeignKey>
    <summaryOperation>min</summaryOperation>
    <type>Summary</type>
</CustomField>

unpackaged/main/default/objects/CS_Sales_Order_Schedule__c/fields/Sales_Order__c.field-meta.xml
<CustomField>
    <fullName>Sales_Order__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Link to the related Sales Order</description>
    <inlineHelpText>Link to the related Sales Order</inlineHelpText>
    <label>Sales Order</label>
    <referenceTo>csmso__Sales_Order__c</referenceTo>
    <relationshipLabel>Sales Order Schedules</relationshipLabel>
    <relationshipName>Sales_Order_Schedules</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Sales_Order_Schedule_Batch__mdt/Sales_Order_Schedule_Batch__mdt.object-meta.xml
<CustomObject>
    <label>Sales Order Schedule Batch</label>
    <pluralLabel>Sales Order Schedule Batches</pluralLabel>
</CustomObject>

unpackaged/main/default/classes/CS_BatchLockBillingScheduleTest.cls
/**
 * @name CS_BatchLockBillingScheduleTest
 * @description Test for CS_BatchLockBillingSchedule class
 * @revision
 *
 */
@isTest
private class CS_BatchLockBillingScheduleTest {


    private void createTestData() {
        //Account Creation.    
        List<Account> acc = TestDataSetupSO.createAccounts(1);
       
        //Contact Creation.
        List<Contact> con = TestDataSetupSO.createContacts(1, acc);
       
        //Opportunity Creation.
        List<Opportunity> opp = TestDataSetupSO.createOpportunities(1, acc, con);

        csmso__Sales_Order__c salesOrder = TestDataSetupSO.createSalesOrder(acc[0], opp[0]);

        CS_Sales_Order_Schedule__c salesOrderSchedule = new CS_Sales_Order_Schedule__c();
        salesOrderSchedule.Sales_Order__c = salesOrder.Id;
        salesOrderSchedule.CurrencyIsoCode = 'USD';
        insert salesOrderSchedule;

        CS_Billing_Schedule__c billingSchedule = new CS_Billing_Schedule__c();
        billingSchedule.CS_Sales_Order_Schedule__c = salesOrderSchedule.Id;
        billingSchedule.CurrencyIsoCode = 'USD';
        billingSchedule.Sales_Order__c = billingSchedule.Id;
        insert billingSchedule;
    }

    /**
     * Tests getQueryMethod with Bill Runs
     */
    @IsTest
    private static void test_getQueryString() {
        
        //Account Creation.    
        List<Account> acc = TestDataSetupSO.createAccounts(1);
       
        //Contact Creation.
        List<Contact> con = TestDataSetupSO.createContacts(1, acc);
       
        //Opportunity Creation.
        List<Opportunity> opp = TestDataSetupSO.createOpportunities(1, acc, con);

        csmso__Sales_Order__c salesOrder = TestDataSetupSO.createSalesOrder(acc[0], opp[0]);

        CS_Sales_Order_Schedule__c salesOrderSchedule = new CS_Sales_Order_Schedule__c();
        salesOrderSchedule.Sales_Order__c = salesOrder.Id;
        salesOrderSchedule.CurrencyIsoCode = 'USD';
        insert salesOrderSchedule;

        CS_Billing_Schedule__c billingSchedule = new CS_Billing_Schedule__c();
        billingSchedule.CS_Sales_Order_Schedule__c = salesOrderSchedule.Id;
        billingSchedule.CurrencyIsoCode = 'USD';
        billingSchedule.Sales_Order__c = billingSchedule.Id;
        insert billingSchedule;
        
        
        String INITIAL_QUERY_TEMPLATE = 'SELECT Id FROM csmso__Sales_Order__c WHERE Id IN ' +
                                           '(SELECT Sales_Order__c FROM CS_Billing_Schedule_Item__c ' +
                                           'WHERE Status__c = {0} AND ({1}))';
        String QUERY_TEMPLATE = 'SELECT Id, Name, Status__c, Billing_Calendar__c, Billing_Date__c ' +
                                           'FROM CS_Billing_Schedule_Item__c ' +
                                           'WHERE Status__c = {0} AND ({1})';
        CS_th_Worker.create();
        
        List<CS_Billing_Schedule_Item__c> billingScheduleItems = new List<CS_Billing_Schedule_Item__c>();
        for(Integer i = 0; i < 5; i++) {
            billingScheduleItems.add(CS_th_BillingScheduleItem.create(CS_const_BillingScheduleItem.Status_Open,
                                 CS_const_BillingScheduleItem.BillingCalendar_Standard,
                                 Date.today().addDays(-10), false, false));
        }
        
        for(Integer i = 0; i < billingScheduleItems.size(); i++) {
            billingScheduleItems[i].Billing_Schedule__c = billingSchedule.id;
        }
        
        insert billingScheduleItems;
        
        CS_th_BillRun.create(CS_const_BillRun.Status_Scheduled, CS_const_BillRun.CalendarType_Standard, Date.today());

        Test.startTest();
        
        CS_BatchLockBillingSchedule batch = new CS_BatchLockBillingSchedule();
        batch.salesOrderScheduleBatches = new List<Sales_Order_Schedule_Batch__mdt>();
        String query = batch.getQueryString(QUERY_TEMPLATE,'');
        
        Test.stopTest();

        System.assert(String.isNotBlank(query));
    }

    /**
     * Tests getQueryMethod without Bill Runs
     */ 
    @IsTest
    private static void test_getQueryStringNoBillRun() {
        
        //Account Creation.    
        List<Account> acc = TestDataSetupSO.createAccounts(1);
       
        //Contact Creation.
        List<Contact> con = TestDataSetupSO.createContacts(1, acc);
       
        //Opportunity Creation.
        List<Opportunity> opp = TestDataSetupSO.createOpportunities(1, acc, con);

        csmso__Sales_Order__c salesOrder = TestDataSetupSO.createSalesOrder(acc[0], opp[0]);

        CS_Sales_Order_Schedule__c salesOrderSchedule = new CS_Sales_Order_Schedule__c();
        salesOrderSchedule.Sales_Order__c = salesOrder.Id;
        salesOrderSchedule.CurrencyIsoCode = 'USD';
        insert salesOrderSchedule;

        CS_Billing_Schedule__c billingSchedule = new CS_Billing_Schedule__c();
        billingSchedule.CS_Sales_Order_Schedule__c = salesOrderSchedule.Id;
        billingSchedule.CurrencyIsoCode = 'USD';
        billingSchedule.Sales_Order__c = billingSchedule.Id;
        insert billingSchedule;
        
        String INITIAL_QUERY_TEMPLATE = 'SELECT Id FROM csmso__Sales_Order__c WHERE Id IN ' +
                                           '(SELECT Sales_Order__c FROM CS_Billing_Schedule_Item__c ' +
                                           'WHERE Status__c = {0} AND ({1}))';
        String QUERY_TEMPLATE = 'SELECT Id, Name, Status__c, Billing_Calendar__c, Billing_Date__c ' +
                                           'FROM CS_Billing_Schedule_Item__c ' +
                                           'WHERE Status__c = {0} AND ({1})';
        CS_th_Worker.create();
        
        List<CS_Billing_Schedule_Item__c> billingScheduleItems = new List<CS_Billing_Schedule_Item__c>();
        for(Integer i = 0; i < 5; i++) {
            billingScheduleItems.add(CS_th_BillingScheduleItem.create(CS_const_BillingScheduleItem.Status_Open,
                                 CS_const_BillingScheduleItem.BillingCalendar_Standard,
                                 Date.today().addDays(-10), false, false));
        }
        
        for(Integer i = 0; i < billingScheduleItems.size(); i++) {
            billingScheduleItems[i].Billing_Schedule__c = billingSchedule.id;
        }
        
        insert billingScheduleItems;

        Test.startTest();
        
        CS_BatchLockBillingSchedule batch = new CS_BatchLockBillingSchedule();
        batch.salesOrderScheduleBatches = new List<Sales_Order_Schedule_Batch__mdt>();
        String query = batch.getQueryString(QUERY_TEMPLATE,'');
        
        Test.stopTest();

        System.assert(String.isNotBlank(query));
        System.assert(!query.contains('Billing_Date__c <= '));
    }

    /**
     * Tests onStart method
     */ 
    @IsTest
    private static void test_onStart() {
        
        //Account Creation.    
        List<Account> acc = TestDataSetupSO.createAccounts(1);
       
        //Contact Creation.
        List<Contact> con = TestDataSetupSO.createContacts(1, acc);
       
        //Opportunity Creation.
        List<Opportunity> opp = TestDataSetupSO.createOpportunities(1, acc, con);

        csmso__Sales_Order__c salesOrder = TestDataSetupSO.createSalesOrder(acc[0], opp[0]);

        CS_Sales_Order_Schedule__c salesOrderSchedule = new CS_Sales_Order_Schedule__c();
        salesOrderSchedule.Sales_Order__c = salesOrder.Id;
        salesOrderSchedule.CurrencyIsoCode = 'USD';
        insert salesOrderSchedule;

        CS_Billing_Schedule__c billingSchedule = new CS_Billing_Schedule__c();
        billingSchedule.CS_Sales_Order_Schedule__c = salesOrderSchedule.Id;
        billingSchedule.CurrencyIsoCode = 'USD';
        billingSchedule.Sales_Order__c = billingSchedule.Id;
        insert billingSchedule;
        CS_th_Worker.create();
        
        List<CS_Billing_Schedule_Item__c> billingScheduleItems = new List<CS_Billing_Schedule_Item__c>();
        for(Integer i = 0; i < 5; i++) {
            billingScheduleItems.add(CS_th_BillingScheduleItem.create(CS_const_BillingScheduleItem.Status_Open,
                                 CS_const_BillingScheduleItem.BillingCalendar_Standard,
                                 Date.today().addDays(-10), false, false));
        }
        
        for(Integer i = 0; i < billingScheduleItems.size(); i++) {
            billingScheduleItems[i].Billing_Schedule__c = billingSchedule.id;
        }
        
        insert billingScheduleItems;
        
        CS_th_BillRun.create(CS_const_BillRun.Status_Scheduled, CS_const_BillRun.CalendarType_Standard, Date.today());

        Test.startTest();
        
        CS_BatchLockBillingSchedule batch = new CS_BatchLockBillingSchedule();
        batch.salesOrderScheduleBatches = new List<Sales_Order_Schedule_Batch__mdt>();
        Database.QueryLocator query = batch.onStart();
        
        Test.stopTest();
    }

    /**
     * Tests onFinish method
     */     
    @IsTest
    private static void test_onFinish() {
        
        //Account Creation.    
        List<Account> acc = TestDataSetupSO.createAccounts(1);
       
        //Contact Creation.
        List<Contact> con = TestDataSetupSO.createContacts(1, acc);
       
        //Opportunity Creation.
        List<Opportunity> opp = TestDataSetupSO.createOpportunities(1, acc, con);

        csmso__Sales_Order__c salesOrder = TestDataSetupSO.createSalesOrder(acc[0], opp[0]);

        CS_Sales_Order_Schedule__c salesOrderSchedule = new CS_Sales_Order_Schedule__c();
        salesOrderSchedule.Sales_Order__c = salesOrder.Id;
        salesOrderSchedule.CurrencyIsoCode = 'USD';
        insert salesOrderSchedule;

        CS_Billing_Schedule__c billingSchedule = new CS_Billing_Schedule__c();
        billingSchedule.CS_Sales_Order_Schedule__c = salesOrderSchedule.Id;
        billingSchedule.CurrencyIsoCode = 'USD';
        billingSchedule.Sales_Order__c = billingSchedule.Id;
        insert billingSchedule;
        
        CS_th_Worker.create();
        
        List<CS_Billing_Schedule_Item__c> billingScheduleItems = new List<CS_Billing_Schedule_Item__c>();
        for(Integer i = 0; i < 5; i++) {
            billingScheduleItems.add(CS_th_BillingScheduleItem.create(CS_const_BillingScheduleItem.Status_Open,
                                 CS_const_BillingScheduleItem.BillingCalendar_Standard,
                                 Date.today().addDays(-10), false, false));
        }
        
        for(Integer i = 0; i < billingScheduleItems.size(); i++) {
            billingScheduleItems[i].Billing_Schedule__c = billingSchedule.id;
        }
        
        insert billingScheduleItems;
        
        Bill_Run__c billRun = CS_th_BillRun.create(CS_const_BillRun.Status_Scheduled, CS_const_BillRun.CalendarType_Standard, Date.today());
        billRun.Reference_Date__c = Date.today().addDays(1);
        update billRun;

        Test.startTest();
        
        CS_BatchLockBillingSchedule batch = new CS_BatchLockBillingSchedule();
        batch.salesOrderScheduleBatches = new List<Sales_Order_Schedule_Batch__mdt>();
        batch.onFinish();
        
        Test.stopTest();

        List<Bill_Run__c> billRuns = [SELECT Id, Status__c FROM Bill_Run__c WHERE Status__c = :CS_const_BillRun.Status_LockingBillSchedules];
        System.assertEquals(1, billRuns.size());
    }
    
    /**
     * Tests doWork method
     */     
    @IsTest
    private static void test_doWork() {
        
        //Account Creation.    
        List<Account> acc = TestDataSetupSO.createAccounts(1);
       
        //Contact Creation.
        List<Contact> con = TestDataSetupSO.createContacts(1, acc);
       
        //Opportunity Creation.
        List<Opportunity> opp = TestDataSetupSO.createOpportunities(1, acc, con);

        csmso__Sales_Order__c salesOrder = TestDataSetupSO.createSalesOrder(acc[0], opp[0]);

        CS_Sales_Order_Schedule__c salesOrderSchedule = new CS_Sales_Order_Schedule__c();
        salesOrderSchedule.Sales_Order__c = salesOrder.Id;
        salesOrderSchedule.CurrencyIsoCode = 'USD';
        insert salesOrderSchedule;

        CS_Billing_Schedule__c billingSchedule = new CS_Billing_Schedule__c();
        billingSchedule.CS_Sales_Order_Schedule__c = salesOrderSchedule.Id;
        billingSchedule.CurrencyIsoCode = 'USD';
        billingSchedule.Sales_Order__c = billingSchedule.Id;
        insert billingSchedule;
        
        CS_th_Worker.create();
        
        List<CS_Billing_Schedule_Item__c> billingScheduleItems = new List<CS_Billing_Schedule_Item__c>();
        for(Integer i = 0; i < 5; i++) {
            billingScheduleItems.add(CS_th_BillingScheduleItem.create(CS_const_BillingScheduleItem.Status_Open,
                                 CS_const_BillingScheduleItem.BillingCalendar_Standard,
                                 Date.today().addDays(-10), false, false));
        }
        
        for(Integer i = 0; i < billingScheduleItems.size(); i++) {
            billingScheduleItems[i].Billing_Schedule__c = billingSchedule.id;
        }
        
        insert billingScheduleItems;
        
        CS_th_BillRun.create(CS_const_BillRun.Status_Scheduled, CS_const_BillRun.CalendarType_Standard, Date.today());

        Test.startTest();
        
        CS_BatchLockBillingSchedule batch = new CS_BatchLockBillingSchedule();
        batch.salesOrderScheduleBatches = new List<Sales_Order_Schedule_Batch__mdt>();
        batch.doWork(billingScheduleItems);
        
        Test.stopTest();

        List<CS_Billing_Schedule_Item__c> billSchedules = [SELECT Id, Status__c FROM CS_Billing_Schedule_Item__c WHERE Status__c = :CS_const_BillingScheduleItem.Status_Locked];
        System.assertEquals(0, billSchedules.size());
    }
    
    /**
     * Tests execute method
     */     
    @IsTest
    private static void test_execute() {
        
        //Account Creation.    
        List<Account> acc = TestDataSetupSO.createAccounts(1);
       
        //Contact Creation.
        List<Contact> con = TestDataSetupSO.createContacts(1, acc);
       
        //Opportunity Creation.
        List<Opportunity> opp = TestDataSetupSO.createOpportunities(1, acc, con);

        csmso__Sales_Order__c salesOrder = TestDataSetupSO.createSalesOrder(acc[0], opp[0]);

        CS_Sales_Order_Schedule__c salesOrderSchedule = new CS_Sales_Order_Schedule__c();
        salesOrderSchedule.Sales_Order__c = salesOrder.Id;
        salesOrderSchedule.CurrencyIsoCode = 'USD';
        insert salesOrderSchedule;

        CS_Billing_Schedule__c billingSchedule = new CS_Billing_Schedule__c();
        billingSchedule.CS_Sales_Order_Schedule__c = salesOrderSchedule.Id;
        billingSchedule.CurrencyIsoCode = 'USD';
        billingSchedule.Sales_Order__c = billingSchedule.Id;
        insert billingSchedule;
        
        CS_th_Worker.create();
        
        List<CS_Billing_Schedule_Item__c> billingScheduleItems = new List<CS_Billing_Schedule_Item__c>();
        for(Integer i = 0; i < 50; i++) {
            billingScheduleItems.add(CS_th_BillingScheduleItem.create(CS_const_BillingScheduleItem.Status_Open,
                                 CS_const_BillingScheduleItem.BillingCalendar_Standard,
                                 Date.today().addDays(-10), false, false));
            billingScheduleItems.add(CS_th_BillingScheduleItem.create(CS_const_BillingScheduleItem.Status_Open,
                                 CS_const_BillingScheduleItem.BillingCalendar_Standard,
                                 Date.today().addDays(10), false, false));
            billingScheduleItems.add(CS_th_BillingScheduleItem.create(CS_const_BillingScheduleItem.Status_Locked,
                                 CS_const_BillingScheduleItem.BillingCalendar_Standard,
                                 Date.today().addDays(-15), false, false));
            billingScheduleItems.add(CS_th_BillingScheduleItem.create(CS_const_BillingScheduleItem.Status_Open,
                                 CS_const_BillingScheduleItem.BillingCalendar_Standard,
                                 Date.today().addDays(-2), false, false));
            billingScheduleItems.add(CS_th_BillingScheduleItem.create(CS_const_BillingScheduleItem.Status_Open,
                                 CS_const_BillingScheduleItem.BillingCalendar_Broadcast,
                                 Date.today().addDays(-15), false, false));
        }
        
        for(Integer i = 0; i < billingScheduleItems.size(); i++) {
            billingScheduleItems[i].Billing_Schedule__c = billingSchedule.id;
        }
        
        insert billingScheduleItems;
        
        List<Bill_Run__c> billRuns = new List<Bill_Run__c>{
            CS_th_BillRun.create(CS_const_BillRun.Status_Scheduled, CS_const_BillRun.CalendarType_Standard, Date.today().addDays(-12), false),
            CS_th_BillRun.create(CS_const_BillRun.Status_Scheduled, CS_const_BillRun.CalendarType_Standard, Date.today().addDays(-5), false),
            CS_th_BillRun.create(CS_const_BillRun.Status_Scheduled, CS_const_BillRun.CalendarType_Standard, Date.today().addDays(15), false),
            CS_th_BillRun.create(CS_const_BillRun.Status_LockingBillSchedules, CS_const_BillRun.CalendarType_Standard, Date.today().addDays(-2), false),
            CS_th_BillRun.create(CS_const_BillRun.Status_LockingBillSchedules, CS_const_BillRun.CalendarType_Broadcast, Date.today().addDays(25), false)
        };
        insert billRuns;

        Test.startTest();
        
        CS_BatchLockBillingSchedule batch = new CS_BatchLockBillingSchedule();
        batch.salesOrderScheduleBatches = new List<Sales_Order_Schedule_Batch__mdt>();
        batch.execute();
        
        Test.stopTest();

        List<CS_Billing_Schedule_Item__c> billSchedules = [SELECT Id, Status__c FROM CS_Billing_Schedule_Item__c WHERE Status__c = :CS_const_BillingScheduleItem.Status_Locked];
        System.assertEquals(50, billSchedules.size());
        
        List<Bill_Run__c> billRunsLocked = [SELECT Id, Status__c FROM Bill_Run__c WHERE Status__c = :CS_const_BillRun.Status_LockingBillSchedules];
        System.assertEquals(4, billRunsLocked.size());
    }
}