unpackaged/main/default/objects/Account/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>Denotes the status of an agent in the agent lifecycle</description>
    <inlineHelpText>Denotes the status of an agent in the agent lifecycle</inlineHelpText>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Trial</fullName>
            </value>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Downgraded</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Suspended</fullName>
            </value>
            <value>
                <fullName>Expired</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Billing_Schedule_Rule__c/Billing_Schedule_Rule__c.object-meta.xml
<CustomObject>
    <label>Billing Schedule Rule</label>
    <nameField>
        <label>Billing Schedule Rule Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Billing Schedule Rules</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/CS_Billing_Schedule__c/CS_Billing_Schedule__c.object-meta.xml
<CustomObject>
    <label>Billing Schedule</label>
    <nameField>
        <displayFormat>BIL-{00000000}</displayFormat>
        <label>Billing Schedule Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Billing Schedule</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/CS_Billing_Schedule__c/fields/CS_Sales_Order_Schedule__c.field-meta.xml
<CustomField>
    <fullName>CS_Sales_Order_Schedule__c</fullName>
    <label>CS Sales Order Schedule</label>
    <referenceTo>CS_Sales_Order_Schedule__c</referenceTo>
    <relationshipName>Billing_Schedule_Headers</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/CS_Billing_Schedule__c/fields/Product_Configuration__c.field-meta.xml
<CustomField>
    <fullName>Product_Configuration__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Link to Product Configuration</description>
    <inlineHelpText>Link to Product Configuration</inlineHelpText>
    <label>Product Configuration</label>
    <referenceTo>cscfga__Product_Configuration__c</referenceTo>
    <relationshipName>Billing_Schedule_Headers</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/CS_Billing_Schedule__c/fields/Sales_Order__c.field-meta.xml
<CustomField>
    <fullName>Sales_Order__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Link to the related Sales Order</description>
    <inlineHelpText>Link to the related Sales Order</inlineHelpText>
    <label>Sales Order</label>
    <referenceTo>csmso__Sales_Order__c</referenceTo>
    <relationshipName>Billing_Schedule_Headers</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/CS_Billing_Schedule_Item__c/CS_Billing_Schedule_Item__c.object-meta.xml
<CustomObject>
    <description>Individiual details for one billing period for one line within a Sales Order</description>
    <label>Billing Schedule Item</label>
    <nameField>
        <displayFormat>BILI-{00000000}</displayFormat>
        <label>Billing Schedule Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Billing Schedule Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/CS_Billing_Schedule_Item__c/fields/Billing_Period_Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Billing_Period_Start_Date__c</fullName>
    <description>- Monthly Standard: The latest from SO Line Start Date or first day of Standard Calendar Month for the Billing Date
 - Monthly Broadcast: The latest from SO Line Start Date or first day of Broadcast Calendar Month for the Billing Date</description>
    <inlineHelpText>- Monthly Standard: The latest from SO Line Start Date or first day of Standard Calendar Month for the Billing Date
 - Monthly Broadcast: The latest from SO Line Start Date or first day of Broadcast Calendar Month for the Billing Date</inlineHelpText>
    <label>Billing Period Start Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/CS_Billing_Schedule_Item__c/fields/Billing_Quantity__c.field-meta.xml
<CustomField>
    <fullName>Billing_Quantity__c</fullName>
    <description>Billing Quantity is calculated as follows : 
- If Billing Source = Contracted -&gt; Billing Quantity = Overwrite Quantity if not 0 otherwise Forecast Quantity up to Capped Quantity 
- Updated by Workflow
- If Billing Source = DFP Actuals -&gt;Billing Quantity = Overwrite Quantity if not 0 otherwise DFP Actuals up to Capped Quantity 
- If Billing Source = 3rd Party Actuals -&gt; Billing Quantity = Overwrite Quantity if not 0 otherwise 3rd Party Actuals up to Capped Quantity</description>
    <inlineHelpText>Billing Quantity calculated from Forecast, Overwrite, Contracted and Capped fields.</inlineHelpText>
    <label>Billing Quantity</label>
    <precision>16</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/CS_Billing_Schedule_Item__c/fields/Billing_Schedule__c.field-meta.xml
<CustomField>
    <fullName>Billing_Schedule__c</fullName>
    <label>Billing Schedule</label>
    <referenceTo>CS_Billing_Schedule__c</referenceTo>
    <relationshipLabel>Billing Schedule Items</relationshipLabel>
    <relationshipName>Billing_Schedule_Items</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/CS_Billing_Schedule_Item__c/fields/DFP_Actuals__c.field-meta.xml
<CustomField>
    <fullName>DFP_Actuals__c</fullName>
    <defaultValue>0</defaultValue>
    <description>Number  of impressions / clicks form DFP</description>
    <inlineHelpText>Number  of impressions / clicks form DFP</inlineHelpText>
    <label>1st Party Actuals</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/CS_Billing_Schedule_Item__c/fields/Product_Configuration__c.field-meta.xml
<CustomField>
    <fullName>Product_Configuration__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Link to the related Product Configuration (Sales Order Line)</description>
    <inlineHelpText>Link to the related Product Configuration (Sales Order Line)</inlineHelpText>
    <label>Product Configuration</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>cscfga__Product_Configuration__c.Sales_Order__c</field>
            <operation>equals</operation>
            <valueField>$Source.Sales_Order__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>cscfga__Product_Configuration__c</referenceTo>
    <relationshipLabel>Billing Schedule Item</relationshipLabel>
    <relationshipName>Billing_Schedule_Item</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/CS_Billing_Schedule_Item__c/fields/Sales_Order__c.field-meta.xml
<CustomField>
    <fullName>Sales_Order__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Link to the related Sales Order.</description>
    <inlineHelpText>Link to the related Sales Order.</inlineHelpText>
    <label>Sales Order</label>
    <referenceTo>csmso__Sales_Order__c</referenceTo>
    <relationshipLabel>Billing Schedule Item</relationshipLabel>
    <relationshipName>CS_Billing_Schedule_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/CS_Billing_Schedule_Item__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>Billing Schedule Status.</description>
    <inlineHelpText>Billing Schedule Status</inlineHelpText>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Open</fullName>
            </value>
            <value>
                <fullName>Locked</fullName>
            </value>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Ready</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
            <value>
                <fullName>Forecast</fullName>
            </value>
            <value>
                <fullName>Pending Closure</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/CS_Sales_Order_Schedule__c/CS_Sales_Order_Schedule__c.object-meta.xml
<CustomObject>
    <label>Sales Order Schedule</label>
    <nameField>
        <displayFormat>RS-{00000000}</displayFormat>
        <label>Sales Order Schedules Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sales Order Schedules</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/CS_Sales_Order_Schedule__c/fields/Sales_Order__c.field-meta.xml
<CustomField>
    <fullName>Sales_Order__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Link to the related Sales Order</description>
    <inlineHelpText>Link to the related Sales Order</inlineHelpText>
    <label>Sales Order</label>
    <referenceTo>csmso__Sales_Order__c</referenceTo>
    <relationshipLabel>Sales Order Schedules</relationshipLabel>
    <relationshipName>Sales_Order_Schedules</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/classes/CS_ValidateIFCsInvokerTest.cls
/**
 * Created by tvrtko.matosevic on 20/06/2019.
 */

@IsTest
private class CS_ValidateIFCsInvokerTest {

    @IsTest
    public static void validateValidateIFCsInvokerTest() {
        CS_utl_User.disableAllTriggers(UserInfo.getUserId());
        csmso__SalesOrderAPI__c soapi = TestDataSetupSO.createSalesOrderAPI();
        insert soapi;

        //Account Creation.
        List<Account> Acc = TestDataSetupSO.createAccounts(1);

        //Contact Creation.
        List<Contact> con = TestDataSetupSO.createContacts(1,Acc);

        //Opportunity Creation.
        List<Opportunity> opp = TestDataSetupSO.createOpportunities(1,Acc,con);

        //SalesOrder Creation.
        List<csmso__Sales_Order__c> salesOrders = TestDataSetupSO.createSalesOrders(1,Acc,opp);

        //Product Definition Creation.
        List<cscfga__Product_Definition__c> prodDef = TestDataSetupSO.createProductDefinitions(1);

        //Attribute definition Creation.

        //Product Baskets  Creation.
        List<cscfga__Product_Basket__c> prodBaskets = TestDataSetupSO.createProdBaskets(1,salesOrders);

        //Product Configs creation.
        List<cscfga__Product_Configuration__c> prodConfigs = TestDataSetupSO.createProdConfigs(1,prodBaskets,prodDef);


        //Fulfilment Creation.
        List<csdf__Fulfilment__c> fulfilment = testDataSetupBilling.createFulfilment(1,salesOrders,Acc);
        Billing_Schedule_Rule__c bScheduleRule = testDataSetupBilling.createBillingScheduleRule();
        Billing_Schedule_Rule__c rScheduleRule = testDataSetupBilling.createRevenueScheduleRule();

        for(cscfga__Product_Configuration__c pConfig: prodConfigs){
            if (salesOrders.size() > 0) {
                pConfig.Sales_Order__c = salesOrders[0].Id;
            }
            pConfig.Billing_Schedule_Rule__c = bScheduleRule.Id;
            pConfig.Revenue_Schedule_Rule__c = rScheduleRule.Id;
            pConfig.Requires_Rescheduling__c= true;
            pConfig.cscfga__Configuration_Status__c ='Valid';
        }
        update prodConfigs;

        //List<Revenue_Recognition_Schedule__c> rSchedules = testDataSetupBilling.createRevenueSchedules(3,salesOrders,fulfilmentItem,prodConfigs);
        List<CS_Sales_Order_Schedule__c> salesOrderSchedules = new List<CS_Sales_Order_Schedule__c>();

        for(csmso__Sales_Order__c salesOrder:salesOrders){
            CS_Sales_Order_Schedule__c sOs = new CS_Sales_Order_Schedule__c();
            sOs.Sales_Order__c = salesOrder.Id;
            salesOrderSchedules.add(sOs);
        }

        insert salesOrderSchedules;

        List<CS_Billing_Schedule__c> bSchedules = new List<CS_Billing_Schedule__c>();

        for(CS_Sales_Order_Schedule__c sOrderSchedule:salesOrderSchedules){
            CS_Billing_Schedule__c bScheduleHeader = new CS_Billing_Schedule__c();
            bScheduleHeader.CS_Sales_Order_Schedule__c = sOrderSchedule.Id;
            bSchedules.add(bScheduleHeader);
        }

        insert bSchedules;

        CS_Billing_Schedule__c bScheduleHeader = bSchedules[0];


        cscfga__Product_Configuration__c pc = [SELECT Id, Sales_Order__c
        FROM cscfga__Product_Configuration__c
        LIMIT 1][0];

        CS_Billing_Schedule_Item__c bschedule = new CS_Billing_Schedule_Item__c();
        bschedule.Product_Configuration__c = pc.Id;
        bschedule.Status__c = 'Locked';
        bschedule.Sales_Order__c = pc.Sales_Order__c;
        bschedule.DFP_Actuals__c = 100;
        //bSchedule.Billing_Quantity__c = 10.0;
        bschedule.Net_Rate__c = 100.0;
        bschedule.Billing_Period_Start_Date__c = Date.today();
        bschedule.Billing_Schedule__c=bScheduleHeader.Id;
        insert bschedule;

        List<Object> paramsList = new List<Object>();
        Map<String, Object> paramsObj = new Map<String, Object>();
        paramsObj.put('ConfigId', pc.Id);
        paramsList.add(paramsObj);

        Map<String, Object> paramsObj1 = new Map<String, Object>();
        paramsObj1.put('Sales_Order_Id_0', pc.Sales_Order__c);
        paramsList.add(paramsObj1);

        Map<String, Object> paramsObj2 = new Map<String, Object>();
        paramsObj2.put('Insertion_Quantity_0', 1000);
        paramsList.add(paramsObj2);

        Map<String, Object> paramsObj3 = new Map<String, Object>();
        paramsObj3.put('Start_Date_0', Date.today());
        paramsList.add(paramsObj3);

        Map<String, Object> paramsObj4 = new Map<String, Object>();
        paramsObj4.put('End_Date_0', Date.today()+15);
        paramsList.add(paramsObj4);

        Map<String, Object> paramsObj5 = new Map<String, Object>();
        paramsObj5.put('Rate_0', 12);
        paramsList.add(paramsObj5);

        Map<String, Object> paramsObj6 = new Map<String, Object>();
        paramsObj6.put('Fulfilment_Item_Status_0', 'InProgress');
        paramsList.add(paramsObj6);

        Map<String, Object> finalParamObj = new Map<String,Object>();
        finalParamObj.put('data', paramsList);

        Test.startTest();
        CS_ValidateIFCsInvoker validateIFCInvoker = new CS_ValidateIFCsInvoker();
        String performActionResult = validateIFCInvoker.performAction(JSON.serialize(finalParamObj));
        Map<String, Object> resultJSONObject = (Map<String, Object>) JSON.deserializeUntyped(performActionResult);
        Test.stopTest();

        System.assertEquals((Boolean)resultJSONObject.get('isError'), true);
        System.assertNotEquals((String)resultJSONObject.get('errorMsg'), null);
    }
}