unpackaged/main/default/objects/Account/fields/Subsidiary__c.field-meta.xml
<CustomField>
    <fullName>Subsidiary__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Denotes the PG subsidiary to which the account belongs to</description>
    <inlineHelpText>Denotes the PG subsidiary to which the account belongs to</inlineHelpText>
    <label>Subsidiary</label>
    <referenceTo>Subsidiary__c</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/iPP_ideveloper__e/iPP_ideveloper__e.object-meta.xml
<CustomObject>
    <label>iPP ideveloper</label>
    <pluralLabel>iPP idevelopers</pluralLabel>
</CustomObject>

unpackaged/main/default/objects/iPP_ideveloper__e/fields/opp_Id__c.field-meta.xml
<CustomField>
    <fullName>opp_Id__c</fullName>
    <label>opp Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Primary_Sales_Order__c.field-meta.xml
<CustomField>
    <fullName>Primary_Sales_Order__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Primary Sales Order linked to this Opportunity</description>
    <inlineHelpText>Primary Sales Order linked to this Opportunity</inlineHelpText>
    <label>Primary Sales Order</label>
    <referenceTo>csmso__Sales_Order__c</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Subsidiary__c.field-meta.xml
<CustomField>
    <fullName>Subsidiary__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Subsidiary</label>
    <referenceTo>Subsidiary__c</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Subsidiary_Code__c.field-meta.xml
<CustomField>
    <fullName>Subsidiary_Code__c</fullName>
    <formula>Subsidiary__r.Subsidiary_Code__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Subsidiary Code</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Subsidiary__c/Subsidiary__c.object-meta.xml
<CustomObject>
    <description>This is a custom object to contain the information on Subsidiary and Country</description>
    <label>Subsidiary</label>
    <nameField>
        <label>Subsidiary Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Subsidiaries</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Subsidiary__c/fields/Subsidiary_Code__c.field-meta.xml
<CustomField>
    <fullName>Subsidiary_Code__c</fullName>
    <description>An internal custom code for checking with User subsidiary and using this code to determine approval route</description>
    <label>Subsidiary Code</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/classes/SendB2BiPPNotify.cls
public class SendB2BiPPNotify {
    
    @InvocableMethod 
    public static void callWorkato(List<String> IDList){
        system.debug('callWorkato');
        String sobjectType =((ID)IDList[0]).getSObjectType().getDescribe().getName();
        String objId = IDList[0];
        iPP_ideveloper__e  ippEvent = new iPP_ideveloper__e();
       String payloadId;
        if(sobjectType == 'Opportunity'){
            Opportunity opp = [Select id,Primary_Sales_Order__c,AccountId from opportunity where id =: objId];
            List<csdf__Fulfilment_Item__c> fliList = [Select id,Product_Configuration__c from csdf__Fulfilment_Item__c
                                                      where csdf__Fulfilment__r.Sales_Order__c  =: opp.Primary_Sales_Order__c
                                                      and Product_Configuration__r.Name like 'Developer Listings%'];
            if(fliList.size() > 0){
               payloadId = IDList[0];
            }
            
            
        } else {
            Account acc = [select id, (Select id from opportunities
                                       where Subsidiary__r.Subsidiary_Code__c = 'iPP' 
                                       and StageName='Closed Won') 
                           from Account where id = :IDList[0] ];
            if(acc.opportunities.size() > 0)
               payloadId = acc.opportunities[0].Id;
        }
        if(payloadId != null){
            ippEvent.opp_Id__c = payloadId;
            system.debug(iPPEvent);
            EventBus.publish(ippEvent);
        }
        //SendNotify.afterInsert(IDList);
        
    }
}