unpackaged/main/default/objects/Account/fields/Subsidiary__c.field-meta.xml
<CustomField>
    <fullName>Subsidiary__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Denotes the PG subsidiary to which the account belongs to</description>
    <inlineHelpText>Denotes the PG subsidiary to which the account belongs to</inlineHelpText>
    <label>Subsidiary</label>
    <referenceTo>Subsidiary__c</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Billing_Entity__c/Billing_Entity__c.object-meta.xml
<CustomObject>
    <label>Billing Entity</label>
    <nameField>
        <displayFormat>NS-{0000}</displayFormat>
        <label>Netsuite ID Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Billing Entities</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Billing_Entity__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>Netsuite_IDs</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/Billing_Entity__c/fields/Credit_Status_Auto__c.field-meta.xml
<CustomField>
    <fullName>Credit_Status_Auto__c</fullName>
    <inlineHelpText>Auto Credit Status from Netsuite</inlineHelpText>
    <label>Credit Status (Auto)</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Suspension</fullName>
            </value>
            <value>
                <fullName>Pre Suspension</fullName>
            </value>
            <value>
                <fullName>Referral</fullName>
            </value>
            <value>
                <fullName>Escalation</fullName>
            </value>
            <value>
                <fullName>At Risk</fullName>
            </value>
            <value>
                <fullName>Watch</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Billing_Entity__c/fields/Subsidiary__c.field-meta.xml
<CustomField>
    <fullName>Subsidiary__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Subsidiary</label>
    <referenceTo>Subsidiary__c</referenceTo>
    <relationshipName>Netsuite_IDs</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Billing_Entity__c/fields/Subsidiary_Code__c.field-meta.xml
<CustomField>
    <fullName>Subsidiary_Code__c</fullName>
    <formula>Subsidiary__r.Subsidiary_Code__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Subsidiary Code</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Billing_Entity__c.field-meta.xml
<CustomField>
    <fullName>Billing_Entity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Billing Entity</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Opportunities (Billing Entity)</relationshipLabel>
    <relationshipName>Opportunities8</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Subsidiary__c.field-meta.xml
<CustomField>
    <fullName>Subsidiary__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Subsidiary</label>
    <referenceTo>Subsidiary__c</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Subsidiary_Code__c.field-meta.xml
<CustomField>
    <fullName>Subsidiary_Code__c</fullName>
    <formula>Subsidiary__r.Subsidiary_Code__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Subsidiary Code</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/recordTypes/B2B.recordType-meta.xml
<RecordType>
    <fullName>B2B</fullName>
    <active>true</active>
    <businessProcess>B2B</businessProcess>
    <description>B2B Opportunity Record</description>
    <label>B2B</label>
</RecordType>

unpackaged/main/default/objects/Subsidiary__c/Subsidiary__c.object-meta.xml
<CustomObject>
    <description>This is a custom object to contain the information on Subsidiary and Country</description>
    <label>Subsidiary</label>
    <nameField>
        <label>Subsidiary Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Subsidiaries</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Subsidiary__c/fields/Subsidiary_Code__c.field-meta.xml
<CustomField>
    <fullName>Subsidiary_Code__c</fullName>
    <description>An internal custom code for checking with User subsidiary and using this code to determine approval route</description>
    <label>Subsidiary Code</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/classes/PGBillingEntityTriggerHandler.cls
public class PGBillingEntityTriggerHandler implements PGTriggerInterface{
             public static boolean isExecutedFromBETrigger = false;

  List<Billing_Entity__c> listBE;
    List<Billing_Entity__c> oldListBE ;
    Map<Id,Billing_Entity__c> triggerOldMap;
    Map<Id,Billing_Entity__c> triggerNewMap;
    
    public PGBillingEntityTriggerHandler() {  
        listBE = new  List<Billing_Entity__c>();
        oldListBE = new List<Billing_Entity__c>();
        triggerOldMap = new Map<Id,Billing_Entity__c>();
        triggerNewMap = new Map<Id,Billing_Entity__c>();
    }
    
    //Use this variable to disable this trigger from transaction
    public static Boolean TriggerDisabled = false;
    
    //check if the trigger is disabled from transaction
    public Boolean isDisabled(){
        return TriggerDisabled;
    }
    public void beforeInsert(List<sObject> newList) { 
    }
    
    public void afterInsert(List<sObject> newList , Map<Id, sObject> newMap) {
        List<Billing_Entity__c> newBEList= new List<Billing_Entity__c>();
        newBEList = (List<Billing_Entity__c>)newList;
        
        updateFulfilmentAllowed(newBEList,null,(Map<Id, Billing_Entity__c>) newMap);
    }
    public void beforeUpdate(List<sObject> newList, Map<Id, sObject> newMap, List<sObject> oldList, Map<Id, sObject> oldMap) {
       
    }
    
    public void afterUpdate(List<sObject> newList, Map<Id, sObject> newMap, List<sObject> oldList, Map<Id, sObject> oldMap) {
        List<Billing_Entity__c> newBEList= new List<Billing_Entity__c>();
        newBEList = (List<Billing_Entity__c>)newList;
        
        updateFulfilmentAllowed(newBEList,(Map<Id, Billing_Entity__c>) oldMap,(Map<Id, Billing_Entity__c>) newMap);
    }
    public void beforeDelete(List<sObject> oldList , Map<Id, sObject> oldMap) { 
        
    }
    public void afterDelete(List<sObject> oldList , Map<Id, sObject> oldMap) {
        
    }
    
    public void afterUnDelete(List<sObject> newList, Map<Id, sObject> newMap) {         
    } 
    
    // update fulfilment Allowed field on sales force
    public static void updateFulfilmentAllowed(List<Billing_Entity__c> beList,Map<Id, Billing_Entity__c> oldMap,Map<Id, Billing_Entity__c> newMap){
        Set<id> accId = new Set<id>();
        Set<id> oppId = new Set<id>();
        String iPP_Sub = label.MY_SUBSIDIARY_IPP_NAME;
        List<csmso__Sales_Order__c> updateSOList = new list<csmso__Sales_Order__c>();
        System.debug('###'+beList);
        Map<id,string> AcctoBEMap = new Map<id,string>();
        
        for(Billing_Entity__c be: beList){
            if( (oldMap!= null && be.Credit_Status_Auto__c != oldMap.get(be.Id).Credit_Status_Auto__c && be.Subsidiary_Code__c =='iPP')||(oldMap == null && be.Subsidiary_Code__c =='iPP') ){
                 accId.add(be.Account__c);
                AcctoBEMap.put(be.Account__c,be.Credit_Status_Auto__c);
            }
           
        }
        System.debug('###'+accId);
        System.debug('###'+iPP_Sub);
       // list<Account> acc = [Select id,Name,(Select id from Opportunities) From Account Where id IN:accId];
        list<Opportunity> Opplist = [Select id,Name,AccountId,Subsidiary__r.Name, RecordType.DeveloperName From Opportunity Where AccountId IN: accId AND RecordType.DeveloperName = 'B2B' AND Subsidiary__r.Name =: iPP_Sub ];
      //  Map<id,list<Opportunity>> AccToOppMap = new Map<id,list<Opportunity>>();
      //  Map<id,list<csmso__Sales_Order__c>> OppToSOMap = new Map<id,list<csmso__Sales_Order__c>>();
        System.debug('@@@ opp list'+Opplist.size());
        
        for(Opportunity op: Opplist){
            oppId.add(op.id);
        }
       
        list<csmso__Sales_Order__c> solist = [Select Id,Fulfilment_Allowed__c,Updated_From__c,csmso__Opportunity__c,csmso__Opportunity__r.accountID from csmso__Sales_Order__c 
                                              where csmso__Opportunity__c IN :oppId and Updated_From__c != 'Manual'];
         System.debug('$$$'+solist.size());                               
        for(csmso__Sales_Order__c so: solist){
           // System.debug('&&&'+so.csmso__Opportunity__r.account.Credit_Status_Auto__c);
            if(AcctoBEMap.get(so.csmso__Opportunity__r.accountID) == 'Suspension'||
               AcctoBEMap.get(so.csmso__Opportunity__r.accountID) == 'Pre Suspension'){
                //   if(so.Fulfilment_Allowed__c!=false){
                so.Fulfilment_Allowed__c = false;
                so.Updated_From__c = 'Account Trigger';
                updateSOList.add(so);
                //   }
            }
            else if(AcctoBEMap.get(so.csmso__Opportunity__r.accountID) != 'Suspension' &&
                    AcctoBEMap.get(so.csmso__Opportunity__r.accountID) != 'Pre Suspension'){
                   //        if(so.Fulfilment_Allowed__c!=true){
                so.Fulfilment_Allowed__c = true;
                so.Updated_From__c = 'Account Trigger';
                updateSOList.add(so);
                    //       }
            }
            
        }           
        isExecutedFromBETrigger = true;
       update updateSOList;
        
        
    }
    
}