unpackaged/main/default/objects/Account/fields/Subsidiary__c.field-meta.xml
<CustomField>
    <fullName>Subsidiary__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Denotes the PG subsidiary to which the account belongs to</description>
    <inlineHelpText>Denotes the PG subsidiary to which the account belongs to</inlineHelpText>
    <label>Subsidiary</label>
    <referenceTo>Subsidiary__c</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/OMC_Rejected_Reason__c.field-meta.xml
<CustomField>
    <fullName>OMC_Rejected_Reason__c</fullName>
    <label>OMC Rejected Reason</label>
    <type>TextArea</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/OMC_Submitted_Time__c.field-meta.xml
<CustomField>
    <fullName>OMC_Submitted_Time__c</fullName>
    <description>Timestamp to indicate the most recent time that the Opportunity was submitted to OMC.</description>
    <label>OMC Submitted Time</label>
    <type>DateTime</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Subsidiary__c.field-meta.xml
<CustomField>
    <fullName>Subsidiary__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Subsidiary</label>
    <referenceTo>Subsidiary__c</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/recordTypes/B2C.recordType-meta.xml
<RecordType>
    <fullName>B2C</fullName>
    <active>true</active>
    <businessProcess>B2C</businessProcess>
    <description>B2C Opportunity Record</description>
    <label>B2C</label>
</RecordType>

unpackaged/main/default/objects/Pricebook2/fields/Subsidiary__c.field-meta.xml
<CustomField>
    <fullName>Subsidiary__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Denotes the PG subsidiary to which the pricebook belongs to</description>
    <inlineHelpText>Denotes the PG subsidiary to which the pricebook belongs to</inlineHelpText>
    <label>Subsidiary</label>
    <referenceTo>Subsidiary__c</referenceTo>
    <relationshipLabel>Price Books</relationshipLabel>
    <relationshipName>Price_Books</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Quote/fields/OMC_Rejected_Reason__c.field-meta.xml
<CustomField>
    <fullName>OMC_Rejected_Reason__c</fullName>
    <label>OMC Rejected Reason</label>
    <type>TextArea</type>
</CustomField>

unpackaged/main/default/objects/Quote/fields/OMC_Submitted_Time__c.field-meta.xml
<CustomField>
    <fullName>OMC_Submitted_Time__c</fullName>
    <label>OMC Submitted Time</label>
    <type>DateTime</type>
</CustomField>

unpackaged/main/default/objects/Quote/fields/Subsidiary__c.field-meta.xml
<CustomField>
    <fullName>Subsidiary__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Subsidiary</label>
    <referenceTo>Subsidiary__c</referenceTo>
    <relationshipLabel>Quotes</relationshipLabel>
    <relationshipName>Quotes</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Quote/recordTypes/B2C.recordType-meta.xml
<RecordType>
    <fullName>B2C</fullName>
    <active>true</active>
    <label>B2C</label>
</RecordType>

unpackaged/main/default/objects/Subsidiary__c/Subsidiary__c.object-meta.xml
<CustomObject>
    <description>This is a custom object to contain the information on Subsidiary and Country</description>
    <label>Subsidiary</label>
    <nameField>
        <label>Subsidiary Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Subsidiaries</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

unpackaged/main/default/objects/User/fields/Subsidiary__c.field-meta.xml
<CustomField>
    <fullName>Subsidiary__c</fullName>
    <label>Subsidiary</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Subsidiary</valueSetName>
    </valueSet>
</CustomField>

unpackaged/main/default/classes/oppRejectionUpdate_Batch_Test.cls
@isTest
    public class oppRejectionUpdate_Batch_Test {
        
        @isTest static void method1()
        {
            User thisUser = [SELECT Id,Subsidiary__c FROM User WHERE Id =: UserInfo.getUserId()];
            System.runAs (thisUser) {
                // Call method to insert test records
                PGTestDataFactory_v2.initSetupData();
                //data setup
                system.debug('DML TestDataFactory');
                Subsidiary__c sb = PGTestDataFactory_v2.createSubsidiary(thisUser);
                Pricebook2 standardPB = PGTestDataFactory_v2.CreateStandardPricebook(sb);
                Account acc=PGTestDataFactory_v2.createB2CAccount('test@test.com','12321', thisUser, sb);
                opportunity opp =PGTestDataFactory_v2.createB2CSubscriptionOpty(acc, thisUser, sb, standardPB, 'B2C - Renewal');
                opp.StageName='Closed Won';
                opp.OMC_Submitted_Time__c= system.today().AddDays(-30);
                opp.OMC_Rejected_Reason__c=   'test' ;
                update opp;
                quote q= PGTestDataFactory_v2.createQuote(opp, sb, acc, StandardPB, 'B2C - Renewal', 'Proposal');
                Test.startTest();
                oppRejectionUpdate_Batch obj = new oppRejectionUpdate_Batch();
                Database.executeBatch(obj);
                Test.stopTest();
                
                
                
            }
        }
    }