unpackaged/main/default/objects/Account/fields/Total_Spending_Amount_last_12_months__c.field-meta.xml
<CustomField>
    <fullName>Total_Spending_Amount_last_12_months__c</fullName>
    <description>This is total spending on Discretionary Products</description>
    <inlineHelpText>This is total spending on Discretionary Products</inlineHelpText>
    <label>Total Spending Amount (last 12 months)</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Months_Included__c.field-meta.xml
<CustomField>
    <fullName>Months_Included__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Included in Total Spending 12 months or not</description>
    <label>Months Included</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Total_Spending_on_Discretionary_Prod_new__c.field-meta.xml
<CustomField>
    <fullName>Total_Spending_on_Discretionary_Prod_new__c</fullName>
    <defaultValue>0.00</defaultValue>
    <label>Total Spending on Discretionary Product</label>
    <precision>15</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Total_Spending_on_Discretionary_Product__c.field-meta.xml
<CustomField>
    <fullName>Total_Spending_on_Discretionary_Product__c</fullName>
    <label>Total Spending on Discretionary Product</label>
    <summarizedField>OpportunityLineItem.Amount__c</summarizedField>
    <summaryFilterItems>
        <field>OpportunityLineItem.Product_Category__c</field>
        <operation>equals</operation>
        <value>Discretionary</value>
    </summaryFilterItems>
    <summaryForeignKey>OpportunityLineItem.OpportunityId</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

unpackaged/main/default/classes/AccountTS_Batch.cls
global class AccountTS_Batch implements Database.Batchable<sObject>{

    String query, strParameter;
    
    public AccountTS_Batch(String AccountId) {
        strParameter = AccountId;
    }

    global Database.QueryLocator start(Database.BatchableContext BC)  {
        list<Id> listAccountId;
        set<Id> setAccountId = new set<Id>(); 
        setAccountId.add(strParameter);
        system.debug('batchjob account:' + setAccountId);
        listAccountId = new list<Id>(setAccountId);
        system.debug('listAccountId.size:'+listAccountId.size());
        string criteria = string.join(listAccountId, '\', \'');
        query = 'select AccountId, Id, Total_Spending_on_Discretionary_Product__c,Total_Spending_on_Discretionary_Prod_new__c  from Opportunity where AccountId in (\''+criteria+'\') and Months_Included__c = true';
        system.debug(query);
        return Database.getQueryLocator(query);
    }
    
    global void execute(Database.BatchableContext BC, list<Opportunity> TSOppty) {
        Decimal TSAmount = 0.00;
        Id AccountId = null;
        list<Account> listAccountId = new list<Account>();
        system.debug('TS:' + TSOppty);
        if(TSOppty.size() > 0){
            for (Opportunity row: TSOppty) {
                TSAmount += (row.Total_Spending_on_Discretionary_Prod_new__c!=null)?row.Total_Spending_on_Discretionary_Prod_new__c:0.00;
                AccountId = row.AccountId;
            }
            if(TSAmount > 0){
                for(Account data:[select Total_Spending_Amount_last_12_months__c  from Account where id =: AccountId]){
                    data.Total_Spending_Amount_last_12_months__c  = TSAmount;
                    listAccountId.add(data);
                }
            }
            if(AccountId != null) {
                Database.SaveResult[] srList = Database.update(listAccountId, false);
                
                // Iterate through each returned result
                for (Database.SaveResult sr : srList) {
                    if (sr.isSuccess()) {
                        // Operation was successful, so get the ID of the record that was processed
                        system.debug('succeed sr.getId():'+sr.getId());
                    }
                }
            }
        }
    }
    
    global void finish(Database.BatchableContext BC) {
        //css
        AccountCSS_Batch w = new AccountCSS_Batch(strParameter);
        database.executeBatch(w);
    }
    
}