unpackaged/main/default/objects/Campaign_Eligibility__c/Campaign_Eligibility__c.object-meta.xml
<CustomObject>
    <label>Campaign Eligibility</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Campaign Eligibilities</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Entitlement_Promotion__c/Entitlement_Promotion__c.object-meta.xml
<CustomObject>
    <label>Entitlement Promotion</label>
    <nameField>
        <label>Entitlement Product Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Entitlement Promotion</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Entitlement_Promotion__c/fields/Promo_Mechanic__c.field-meta.xml
<CustomField>
    <fullName>Promo_Mechanic__c</fullName>
    <description>Denotes the related promo mechanic of this entitlement Promotion</description>
    <inlineHelpText>Denotes the related promo mechanic of this entitlement Promotion</inlineHelpText>
    <label>Promo Mechanic</label>
    <referenceTo>Promo_Mechanic__c</referenceTo>
    <relationshipName>Entitlement_Product</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/Promo_Mechanic__c/Promo_Mechanic__c.object-meta.xml
<CustomObject>
    <label>Promo Mechanic</label>
    <nameField>
        <label>Promo Mechanic Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Promo Mechanic</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Promo_Mechanic__c/fields/Campaign_Eligibility__c.field-meta.xml
<CustomField>
    <fullName>Campaign_Eligibility__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Denotes the related Campaign Eligibility Record</description>
    <inlineHelpText>Denotes the related Campaign Eligibility Record</inlineHelpText>
    <label>Campaign Eligibility</label>
    <referenceTo>Campaign_Eligibility__c</referenceTo>
    <relationshipLabel>Promo Mechanic</relationshipLabel>
    <relationshipName>Promo_Mechanic</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/classes/SSCampaignsGETAPI_TEST.cls
@isTest
public class SSCampaignsGETAPI_TEST {
    
    @isTest
    public static void test(){
        
        PGTestDataFactory_v2.CreateTriggerExecuteCS('PGCampaignEligibilityTrigger',false);
        PGTestDataFactory_v2.CreateTriggerExecuteCS('PGPromoMechanicTrigger',false);
        PGTestDataFactory_v2.CreateTriggerExecuteCS('PGEntitlementPromoTrigger',false);
        
        Campaign cma = PGTestDataFactory_v2.CreateCampaign(System.Today().addmonths(1));
        Campaign_Eligibility__c ce = PGTestDataFactory_v2.CreateCampaignEligibility(cma.Id);
        insert ce;
        Promo_Mechanic__c prm = PGTestDataFactory_v2.CreatePromoMechanic(null,ce.Id);
        Entitlement_Promotion__c ep = PGTestDataFactory_v2.CreateEntitlementPromotion(prm.Id);
        
        
        RestRequest req = new RestRequest();
        RestResponse res = new RestResponse();
        req.requestURI = '/services/apexrest/api/renewalsscampaign/'+cma.Id;
        req.httpMethod = 'GET';
        
        RestContext.request = req;
        RestContext.response= res;
        
        Test.startTest();
        SSCampaignsGETAPI.getDetails();
        Test.stopTest();   
    }
    @isTest
    public static void test1(){
        
        
        RestRequest req = new RestRequest();
        RestResponse res = new RestResponse();
        req.requestURI = '/services/apexrest/api/renewalsscampaign/';
        req.httpMethod = 'GET';
        
        RestContext.request = req;
        RestContext.response= res;
        
        Test.startTest();
        SSCampaignsGETAPI.getDetails();
        Test.stopTest();   
    }
    @isTest
    public static void test2(){
        
        
        
        RestRequest req = new RestRequest();
        RestResponse res = new RestResponse();
        req.requestURI = '/services/apexrest/api/renewalsscampaign/cmaId';
        req.httpMethod = 'GET';
        
        RestContext.request = req;
        RestContext.response= res;
        
        Test.startTest();
        SSCampaignsGETAPI.getDetails();
        Test.stopTest();   
    }
}