unpackaged/main/default/objects/Campaign_Eligibility__c/Campaign_Eligibility__c.object-meta.xml
<CustomObject>
    <label>Campaign Eligibility</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Campaign Eligibilities</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Campaign_Eligibility__c/fields/Campaign__c.field-meta.xml
<CustomField>
    <fullName>Campaign__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Denotes the campaign for which campaign eligibility is created</description>
    <inlineHelpText>Denotes Campaign for which campaign eligibility is created</inlineHelpText>
    <label>Campaign</label>
    <referenceTo>Campaign</referenceTo>
    <relationshipLabel>Campaign Eligibilities</relationshipLabel>
    <relationshipName>Campaign_Eligibilities</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Campaign_Eligibility__c/fields/Criteria_Type__c.field-meta.xml
<CustomField>
    <fullName>Criteria_Type__c</fullName>
    <description>Denotes the type of entry of criteria</description>
    <inlineHelpText>Denotes the type of entry of criteria</inlineHelpText>
    <label>Criteria Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>SOQL</fullName>
            </value>
            <value>
                <fullName>Apex Method</fullName>
            </value>
            <value>
                <fullName>Custom Metadata</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Campaign_Eligibility__c/fields/Next_run_scheduled__c.field-meta.xml
<CustomField>
    <fullName>Next_run_scheduled__c</fullName>
    <description>Denotes the next time the campaign eligibility is run by Campaign Rule Engine (CRE) for the related campaign</description>
    <inlineHelpText>Denotes the next time the campaign eligibility is run by Campaign Rule Engine (CRE) for the related campaign</inlineHelpText>
    <label>Next Run scheduled</label>
    <type>DateTime</type>
</CustomField>

unpackaged/main/default/objects/Campaign_Eligibility__c/fields/Rule_Name_Extension__c.field-meta.xml
<CustomField>
    <fullName>Rule_Name_Extension__c</fullName>
    <description>To accommodate longer SOQL queries (&gt;255 char) when Criteria Type is &#39;SOQL&#39;</description>
    <inlineHelpText>To accommodate longer SOQL queries (&gt;255 char) when Criteria Type is &#39;SOQL&#39;</inlineHelpText>
    <label>Rule Name Extension</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

unpackaged/main/default/objects/Campaign_Eligibility__c/fields/Run_Frequency__c.field-meta.xml
<CustomField>
    <fullName>Run_Frequency__c</fullName>
    <description>Denotes predetermined list of frequencies for this rule to be run by Campaign Rule Engine</description>
    <inlineHelpText>Hourly- 9AM to 9PM
Daily- 6AM
Weekly- Every Monday at 6AM
Monthly- 1st day of the month at 6AM
Not Applicable- Choose this option if rule is not going to be run in a predefined schedule</inlineHelpText>
    <label>Run Frequency</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Hourly</fullName>
            </value>
            <value>
                <fullName>Daily</fullName>
            </value>
            <value>
                <fullName>Weekly</fullName>
            </value>
            <value>
                <fullName>Monthly</fullName>
            </value>
            <value>
                <fullName>Not Applicable</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Campaign_Eligibility__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>Denotes whether the rule is active or inactive</description>
    <inlineHelpText>Denotes whether the rule is active or inactive</inlineHelpText>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Dynamic_SOQL__mdt/Dynamic_SOQL__mdt.object-meta.xml
<CustomObject>
    <description>This custom metadata is used to store SOQL and use them dynamically in the apex code</description>
    <label>Dynamic SOQL</label>
    <pluralLabel>Dynamic SOQL</pluralLabel>
</CustomObject>

unpackaged/main/default/objects/Dynamic_SOQL__mdt/fields/Name__c.field-meta.xml
<CustomField>
    <fullName>Name__c</fullName>
    <description>To Store the Name of Custom Metadata. Standard Name has 40 CharacterLimit</description>
    <inlineHelpText>To Store the Name of Custom Metadata. Standard Name has 40 CharacterLimit</inlineHelpText>
    <label>Name</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

unpackaged/main/default/objects/Dynamic_SOQL__mdt/fields/SOQL_Query__c.field-meta.xml
<CustomField>
    <fullName>SOQL_Query__c</fullName>
    <description>To Store query in metadata and use them later in apex code</description>
    <inlineHelpText>To write validated SOQL</inlineHelpText>
    <label>SOQL Query</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

unpackaged/main/default/classes/SchedulerToActivateCamp.cls
global class SchedulerToActivateCamp implements System.Schedulable {
    
    public List<Id> listOfCmpIds;
    public String active;
    
    global SchedulerToActivateCamp(List<Id> listOfCampaignIds, String actv ){
        listOfCmpIds = new List<Id>();
        listOfCmpIds = listOfCampaignIds;
        active = actv;        
    }
    
    global void execute(System.SchedulableContext context) {
        
        List<Campaign> toUpdateCampaigns = new List<Campaign>();
        if(listOfCmpIds!=null){
            for(Id campaignId : listOfCmpIds){
                Campaign cmp = new Campaign();
                cmp.Id = campaignId;
                if(active == 'Active'){
                    
                    cmp.IsActive = true;
                }
                else if(active == 'InActive'){
                    
                    cmp.IsActive = false;
                }
                toUpdateCampaigns.add(cmp);
            }
        }
        
        if(toUpdateCampaigns!=null)
            update toUpdateCampaigns;
        
        if(active == 'Active')
            RunCRE(listOfCmpIds);
        
        // To remove jobs from scheduled job list
        system.abortJob(context.getTriggerId());
        
    }
    
    public static void RunCRE(List<Id> listOfCmpIds){
        List<String> campaignIds=new List<string>();
        list<Id> ceIdList = new list<Id>();
        map<Id,String> ceQueryMap = new map<Id,String>();
        //to Fetch All SOQL Metadata
        map<string,string> nameVsQuery = new map<string,string>();
        for(Dynamic_SOQL__mdt meta : [Select SOQL_Query__c,Name__c from  Dynamic_SOQL__mdt]){
            nameVsQuery.put(meta.Name__c,meta.SOQL_Query__c);
        }
        List<Campaign_ELigibility__C> ceList =[select id,Campaign__r.RecordType.name,campaign__c,Run_Frequency__c,
                                               Next_run_scheduled__c,Criteria_Type__c,
                                               Rule_Name_Extension__c from campaign_eligibility__c 
                                               where Status__c='Active' 
                                               and campaign__r.IsActive=true
                                               and campaign__r.Id =:listOfCmpIds];
                                              
        
        for(Campaign_ELigibility__C ce:ceList)   {
            
            if(ce.Criteria_Type__c == 'SOQL' || ce.Criteria_Type__c == 'Custom Metadata'){
                if(String.isNotBlank(String.valueOf(ce.get('Rule_Name_Extension__c')))
                   && String.isNotBlank(String.valueOf(ce.get('Criteria_Type__c')))){
                       
                       if(ce.Criteria_Type__c == 'SOQL'){
                           ceIdList.add(ce.Id);
                           ceQueryMap.put((Id)ce.get('id'),String.valueOf(ce.get('Rule_Name_Extension__c')));
                       }else if(ce.Criteria_Type__c == 'Custom Metadata'){
                           if(nameVsQuery.containsKey(ce.Rule_Name_Extension__c) && String.isNotBlank(nameVsQuery.get(ce.Rule_Name_Extension__c))){
                               ceIdList.add(ce.Id);
                               ceQueryMap.put((Id)ce.get('id'),String.valueOf(nameVsQuery.get(ce.Rule_Name_Extension__c)));
                           }
                           
                       }
                       
                   }
                
            }else{
                campaignIds.add(ce.Campaign__c);
            }
        }  
        
        if(campaignIds.size() > 0){
            PreprocessorRuleEngine.startPreProcessing('Campaign Eligibility',null,campaignIds);
        }
        if(!ceIdList.isEmpty()){
            Database.executeBatch(new ProcessingBatchSOQL(ceQueryMap,ceIdList),2000);
        }
    }
}