unpackaged/main/default/objects/Campaign_Eligibility__c/Campaign_Eligibility__c.object-meta.xml
<CustomObject>
    <label>Campaign Eligibility</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Campaign Eligibilities</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Campaign_Eligibility__c/fields/Criteria_Type__c.field-meta.xml
<CustomField>
    <fullName>Criteria_Type__c</fullName>
    <description>Denotes the type of entry of criteria</description>
    <inlineHelpText>Denotes the type of entry of criteria</inlineHelpText>
    <label>Criteria Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>SOQL</fullName>
            </value>
            <value>
                <fullName>Apex Method</fullName>
            </value>
            <value>
                <fullName>Custom Metadata</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Campaign_Eligibility__c/fields/Rule_Name_Extension__c.field-meta.xml
<CustomField>
    <fullName>Rule_Name_Extension__c</fullName>
    <description>To accommodate longer SOQL queries (&gt;255 char) when Criteria Type is &#39;SOQL&#39;</description>
    <inlineHelpText>To accommodate longer SOQL queries (&gt;255 char) when Criteria Type is &#39;SOQL&#39;</inlineHelpText>
    <label>Rule Name Extension</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

unpackaged/main/default/objects/Campaign_Eligibility__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>Denotes whether the rule is active or inactive</description>
    <inlineHelpText>Denotes whether the rule is active or inactive</inlineHelpText>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/classes/VerifyEligibilityController_Test.cls
@isTest
public class VerifyEligibilityController_Test {
    
    @isTest static void method1(){  
        
        Campaign camp=null;
        Campaign_Eligibility__c campEligibility=null;
        camp= PGTestDataFactory_v2.CreateCampaign(System.Today().addmonths(1));
        
        campEligibility=PGTestDataFactory_v2.CreateCampaignEligibility(camp.id);
        campEligibility.Criteria_Type__c = 'SOQL';
        campEligibility.Status__c='Active';
        
        insert campEligibility;
        
        String className='test';
        String methodName='test123';
        
        test.startTest();
        try{
            VerifyEligibilityController.validateClassAndMethod(className, methodName);
            VerifyEligibilityController.validationCampaignEligibilityQuery(campEligibility.id);
        }
        catch (Exception e){}
        test.stopTest();
    }
    @isTest static void method2(){  
        Campaign camp=null;
        Campaign_Eligibility__c campEligibility=null;
        camp= PGTestDataFactory_v2.CreateCampaign(System.Today().addmonths(1));
        campEligibility=PGTestDataFactory_v2.CreateCampaignEligibility(camp.id);
        campEligibility.Criteria_Type__c = 'Apex Method';
        campEligibility.Rule_Name_Extension__c = 'Test;test23';
        campEligibility.Status__c='Active';
        
        insert campEligibility;
        
        String className='test';
        String methodName='test432;';
        
        test.startTest();
        try{
            VerifyEligibilityController.validateClassAndMethod('', '');
            VerifyEligibilityController.validationCampaignEligibilityQuery(campEligibility.id);
        }
        catch(Exception e){}
        test.stopTest();
    }
    
    @isTest static void method3(){  
        
        Campaign camp=null;
        Campaign_Eligibility__c campEligibility=null;
        camp= PGTestDataFactory_v2.CreateCampaign(System.Today().addmonths(1));
        
        campEligibility=PGTestDataFactory_v2.CreateCampaignEligibility(camp.id);
        campEligibility.Criteria_Type__c = 'SOQL';
        campEligibility.Rule_Name_Extension__c = 'Select id from Contact;';
        campEligibility.Status__c='Active';
        
        insert campEligibility;
        
        String className='test';
        String methodName='test123';
        
        test.startTest();
        try{
            VerifyEligibilityController.validateClassAndMethod(className, methodName);
            VerifyEligibilityController.validationCampaignEligibilityQuery(campEligibility.id);
        }
        catch (Exception e){}
        test.stopTest();
    }
    @isTest static void method4(){  
        
        Campaign camp=null;
        Campaign_Eligibility__c campEligibility=null;
        camp= PGTestDataFactory_v2.CreateCampaign(System.Today().addmonths(1));
        
        campEligibility=PGTestDataFactory_v2.CreateCampaignEligibility(camp.id);
        campEligibility.Criteria_Type__c = ''; 
        campEligibility.Status__c='Active';
        
        insert campEligibility;
        
        String className='test';
        String methodName='test123';
        
        test.startTest();
        try{
            VerifyEligibilityController.validateClassAndMethod(className, methodName);
            VerifyEligibilityController.validationCampaignEligibilityQuery(campEligibility.id);
        }
        catch (Exception e){}
        test.stopTest();
    }
    
}