unpackaged/main/default/objects/Campaign_Eligibility__c/Campaign_Eligibility__c.object-meta.xml
<CustomObject>
    <label>Campaign Eligibility</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Campaign Eligibilities</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Campaign_Eligibility__c/fields/Run_Frequency__c.field-meta.xml
<CustomField>
    <fullName>Run_Frequency__c</fullName>
    <description>Denotes predetermined list of frequencies for this rule to be run by Campaign Rule Engine</description>
    <inlineHelpText>Hourly- 9AM to 9PM
Daily- 6AM
Weekly- Every Monday at 6AM
Monthly- 1st day of the month at 6AM
Not Applicable- Choose this option if rule is not going to be run in a predefined schedule</inlineHelpText>
    <label>Run Frequency</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Hourly</fullName>
            </value>
            <value>
                <fullName>Daily</fullName>
            </value>
            <value>
                <fullName>Weekly</fullName>
            </value>
            <value>
                <fullName>Monthly</fullName>
            </value>
            <value>
                <fullName>Not Applicable</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Trigger_Execute__c/Trigger_Execute__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>Trigger Execute</label>
</CustomObject>

unpackaged/main/default/objects/Trigger_Execute__c/fields/Enable_del__c.field-meta.xml
<CustomField>
    <fullName>Enable_del__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Enable del</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/classes/CREScheduleRunAtSix_test.cls
@isTest
public class CREScheduleRunAtSix_test {
    
    
    static testMethod void mainTest(){
        
        Trigger_Execute__c TE = new Trigger_Execute__c();
        TE.Name = 'PGCampaignEligibilityTrigger';
        TE.Enable_del__c = true;
        insert TE;
        
        Campaign camp=null;
        Campaign camp1=null;
        Campaign camp2=null;
        Campaign_Eligibility__c campEligibility=null;
        Campaign_Eligibility__c campEligibility1=null;
        Campaign_Eligibility__c campEligibility2=null;
        camp= PGTestDataFactory_v2.CreateCampaign(System.Today().addmonths(1));
        campEligibility=PGTestDataFactory_v2.CreateCampaignEligibility(camp.id);
        campEligibility.Run_Frequency__c='Weekly';
        insert campEligibility;
        camp1= PGTestDataFactory_v2.CreateCampaign(System.Today().addmonths(2));
        camp2= PGTestDataFactory_v2.CreateCampaign(System.Today().addmonths(3));
        campEligibility1=PGTestDataFactory_v2.CreateCampaignEligibility(camp1.id);
        campEligibility1.Run_Frequency__c='Daily';
        insert campEligibility1;
        campEligibility2=PGTestDataFactory_v2.CreateCampaignEligibility(camp2.id);
        campEligibility2.Run_Frequency__c='Monthly';
        insert campEligibility2;
        
        Test.startTest();
        CREScheduleRunAtSix sh1 = new CREScheduleRunAtSix();
        String sch = '0 0 2 * * ?'; 
        system.schedule('Test CRE', sch, sh1); 
        Test.stopTest();
    }
    
}