unpackaged/main/default/objects/CamMemberStatusValue__c/CamMemberStatusValue__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>CamMemberStatusValue</label>
</CustomObject>

unpackaged/main/default/objects/CamMemberStatusValue__c/fields/Values__c.field-meta.xml
<CustomField>
    <fullName>Values__c</fullName>
    <label>Values</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Campaign/fields/Campaign_End_DateTime__c.field-meta.xml
<CustomField>
    <fullName>Campaign_End_DateTime__c</fullName>
    <description>Stores End Date Time of campaign.</description>
    <label>Campaign End DateTime</label>
    <type>DateTime</type>
</CustomField>

unpackaged/main/default/objects/Campaign/fields/Campaign_Start_DateTime__c.field-meta.xml
<CustomField>
    <fullName>Campaign_Start_DateTime__c</fullName>
    <description>Stores Start Date Time of campaign.</description>
    <label>Campaign Start DateTime</label>
    <type>DateTime</type>
</CustomField>

unpackaged/main/default/objects/Campaign/fields/Country__c.field-meta.xml
<CustomField>
    <fullName>Country__c</fullName>
    <description>Denotes the country of campaign members and is synonymous with currency field</description>
    <inlineHelpText>Denotes the country of campaign members and is synonymous with currency field</inlineHelpText>
    <label>Country</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Country</valueSetName>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Campaign/fields/Source_Campaign_Reference__c.field-meta.xml
<CustomField>
    <fullName>Source_Campaign_Reference__c</fullName>
    <description>Reference of campaign in external system eg: CMS</description>
    <inlineHelpText>Reference of campaign in external system eg: CMS</inlineHelpText>
    <label>Source Campaign Reference</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Campaign/recordTypes/Marketing_Promo.recordType-meta.xml
<RecordType>
    <fullName>Marketing_Promo</fullName>
    <active>true</active>
    <label>Marketing Promo</label>
</RecordType>

unpackaged/main/default/objects/Campaign_Eligibility__c/Campaign_Eligibility__c.object-meta.xml
<CustomObject>
    <label>Campaign Eligibility</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Campaign Eligibilities</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Campaign_Eligibility__c/fields/Campaign__c.field-meta.xml
<CustomField>
    <fullName>Campaign__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Denotes the campaign for which campaign eligibility is created</description>
    <inlineHelpText>Denotes Campaign for which campaign eligibility is created</inlineHelpText>
    <label>Campaign</label>
    <referenceTo>Campaign</referenceTo>
    <relationshipLabel>Campaign Eligibilities</relationshipLabel>
    <relationshipName>Campaign_Eligibilities</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Entitlement_Promotion__c/Entitlement_Promotion__c.object-meta.xml
<CustomObject>
    <label>Entitlement Promotion</label>
    <nameField>
        <label>Entitlement Product Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Entitlement Promotion</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Entitlement_Promotion__c/fields/Discount__c.field-meta.xml
<CustomField>
    <fullName>Discount__c</fullName>
    <description>Denotes the percentage of discount on the line item that has the related promo mechanic applied</description>
    <inlineHelpText>Denotes the percentage of discount on the line item that has the related promo mechanic applied</inlineHelpText>
    <label>Discount %</label>
    <precision>12</precision>
    <scale>6</scale>
    <type>Percent</type>
</CustomField>

unpackaged/main/default/objects/Entitlement_Promotion__c/fields/Promo_Mechanic__c.field-meta.xml
<CustomField>
    <fullName>Promo_Mechanic__c</fullName>
    <description>Denotes the related promo mechanic of this entitlement Promotion</description>
    <inlineHelpText>Denotes the related promo mechanic of this entitlement Promotion</inlineHelpText>
    <label>Promo Mechanic</label>
    <referenceTo>Promo_Mechanic__c</referenceTo>
    <relationshipName>Entitlement_Product</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/Promo_Mechanic__c/Promo_Mechanic__c.object-meta.xml
<CustomObject>
    <label>Promo Mechanic</label>
    <nameField>
        <label>Promo Mechanic Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Promo Mechanic</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Promo_Mechanic__c/fields/Campaign_Eligibility__c.field-meta.xml
<CustomField>
    <fullName>Campaign_Eligibility__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Denotes the related Campaign Eligibility Record</description>
    <inlineHelpText>Denotes the related Campaign Eligibility Record</inlineHelpText>
    <label>Campaign Eligibility</label>
    <referenceTo>Campaign_Eligibility__c</referenceTo>
    <relationshipLabel>Promo Mechanic</relationshipLabel>
    <relationshipName>Promo_Mechanic</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Trigger_Execute__c/Trigger_Execute__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>Trigger Execute</label>
</CustomObject>

unpackaged/main/default/objects/Trigger_Execute__c/fields/Enable_del__c.field-meta.xml
<CustomField>
    <fullName>Enable_del__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Enable del</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/classes/PGCampaignTrigger_Test.cls
@isTest
public class PGCampaignTrigger_Test {
    
    @isTest
    static void PGCampaignTriggerMethod(){
        
        CamMemberStatusValue__c cms = new CamMemberStatusValue__c();
        cms.Name = Schema.SObjectType.Campaign.getRecordTypeInfosByName().get('B2B Developer Online Form').getRecordTypeId();
        cms.Values__c = 'Test';
        insert cms;
		
        Campaign cm = new Campaign();
        cm.Name = 'TestCampaign';
        cm.IsActive = true;
        cm.Source_Campaign_Reference__c='camp1';
        cm.RecordTypeId =Schema.SObjectType.Campaign.getRecordTypeInfosByName().get('B2B Developer Online Form').getRecordTypeId();
        cm.EndDate = system.today().addDays(-2);
        insert cm;
		      
        Campaign cm1 = new Campaign();
        cm1.Name = 'TestCampaign1';
        cm1.IsActive = true;
        cm1.Source_Campaign_Reference__c='camp1';
        //cm1.RecordTypeId =Schema.SObjectType.Campaign.getRecordTypeInfosByName().get('B2B Developer Online Form').getRecordTypeId();
        cm1.EndDate = system.today().addDays(-2);
        insert cm1;
       
        
        Test.startTest();
        List<CampaignMemberStatus> CampaignMemberStatusList = [select Id from CampaignMemberStatus where CampaignId = : cm.Id];
        system.assert(CampaignMemberStatusList.size() != null);
        system.debug('CampaignMemberStatusList$$$$ '+CampaignMemberStatusList);
        Test.stopTest();
    }
    @isTest
    static void PGCampaignTriggerMethod_ErrorCase(){
        
        Campaign cm = new Campaign();
        cm.Name = 'TestCampaign';
        cm.IsActive = true;
        cm.Source_Campaign_Reference__c='camp1';
        cm.RecordTypeId =Schema.SObjectType.Campaign.getRecordTypeInfosByName().get('B2B Developer Online Form').getRecordTypeId();
        cm.EndDate = system.today().addDays(-2);
        insert cm;
		      
        Campaign cm1 = new Campaign();
        cm1.Name = 'TestCampaign1';
        cm1.IsActive = true;
        cm1.Source_Campaign_Reference__c='camp1';
        cm1.RecordTypeId = Schema.SObjectType.Campaign.getRecordTypeInfosByName().get('B2B Developer Online Form').getRecordTypeId();
        cm1.EndDate = system.today().addDays(-2);
        
        Test.startTest();
        try{
        insert cm1;
        }
        catch(exception ex){
            Boolean expectedExceptionThrown =  ex.getMessage().contains('Campaign with same Source Campaign Reference already Activated.') ? true : false;
   			System.assertEquals(expectedExceptionThrown, true);
        }
        Test.stopTest();
    }
    
    public static testmethod void afterUpdateTest() {
        
        Trigger_Execute__c TE = new Trigger_Execute__c();
        TE.Name = 'PGCampaignEligibilityTrigger';
        TE.Enable_del__c = true;
        insert TE;
        
        Trigger_Execute__c TEPromoMech = new Trigger_Execute__c();
        TEPromoMech.Name = 'PGPromoMechanicTrigger';
        TEPromoMech.Enable_del__c = true;
        insert TEPromoMech;
        
        Trigger_Execute__c TEEntPromo = new Trigger_Execute__c();
        TEEntPromo.Name = 'PGEntitlementPromoTrigger';
        TEEntPromo.Enable_del__c = true;
        insert TEEntPromo;
        
        List<Campaign> campList = new List<Campaign>();
        Campaign camp = new Campaign();
        camp.Name = 'TestCampaign';
        camp.IsActive = false;
        camp.Country__c = 'Singapore';
        camp.CurrencyIsoCode = 'SGD';
        camp.Source_Campaign_Reference__c='camp1';
        camp.RecordTypeId =Schema.SObjectType.Campaign.getRecordTypeInfosByDeveloperName().get('Marketing_Promo').getRecordTypeId();
        camp.StartDate = system.today();
        camp.Campaign_Start_DateTime__c = system.now();
        camp.Campaign_End_DateTime__c = system.now().addDays(+1);
        camp.EndDate = system.today().addDays(+1);
        insert camp;

        Campaign_Eligibility__c campElig = new Campaign_Eligibility__c();
        campElig.Name = 'Test Elig';
        campElig.CurrencyIsoCode ='SGD';
        campElig.Campaign__c =camp.Id ;
        insert campElig;
        
        Test.startTest();
        camp.IsActive = true;
        update camp;
        
        Promo_Mechanic__c promoMech = new Promo_Mechanic__c();
        promoMech.Name = 'Test PM';
        promoMech.CurrencyIsoCode ='SGD';
        promoMech.Campaign_Eligibility__c =campElig.Id ;
        insert promoMech;
        update promoMech; 
        
        Entitlement_Promotion__c entPromo1 = new Entitlement_Promotion__c();
        entPromo1.Name = 'Test EntPromo1';
        entPromo1.Promo_Mechanic__c = promoMech.Id;
        entPromo1.Discount__c = 10;
        insert entPromo1;
     
        camp.IsActive = false;
        camp.Country__c = 'Thailand';
        camp.CurrencyIsoCode = 'THB';
        update camp;
        Test.stopTest();
    }
}