unpackaged/main/default/objects/CS_Billing_Schedule_Item__c/CS_Billing_Schedule_Item__c.object-meta.xml
<CustomObject>
    <description>Individiual details for one billing period for one line within a Sales Order</description>
    <label>Billing Schedule Item</label>
    <nameField>
        <displayFormat>BILI-{00000000}</displayFormat>
        <label>Billing Schedule Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Billing Schedule Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/CS_Billing_Schedule_Item__c/fields/Billing_Schedule__c.field-meta.xml
<CustomField>
    <fullName>Billing_Schedule__c</fullName>
    <label>Billing Schedule</label>
    <referenceTo>CS_Billing_Schedule__c</referenceTo>
    <relationshipLabel>Billing Schedule Items</relationshipLabel>
    <relationshipName>Billing_Schedule_Items</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/CS_Billing_Schedule_Item__c/fields/Sales_Order__c.field-meta.xml
<CustomField>
    <fullName>Sales_Order__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Link to the related Sales Order.</description>
    <inlineHelpText>Link to the related Sales Order.</inlineHelpText>
    <label>Sales Order</label>
    <referenceTo>csmso__Sales_Order__c</referenceTo>
    <relationshipLabel>Billing Schedule Item</relationshipLabel>
    <relationshipName>CS_Billing_Schedule_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/CS_Billing_Schedule_Item__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>Billing Schedule Status.</description>
    <inlineHelpText>Billing Schedule Status</inlineHelpText>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Open</fullName>
            </value>
            <value>
                <fullName>Locked</fullName>
            </value>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Ready</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
            <value>
                <fullName>Forecast</fullName>
            </value>
            <value>
                <fullName>Pending Closure</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/CS_Billing_Schedule_Item__c/fields/Valid_for_Auto_Cancellation__c.field-meta.xml
<CustomField>
    <fullName>Valid_for_Auto_Cancellation__c</fullName>
    <description>Indicates if this line is valid to be auto-cancelled or not</description>
    <formula>NOT(ISPICKVAL(Status__c, &#39;Cancelled&#39;))
&amp;&amp; X3rd_Party_Actuals__c = 0
&amp;&amp; ISBLANK(X3rd_Party_Actuals_as_of__c)
&amp;&amp; DFP_Actuals__c = 0
&amp;&amp; ISBLANK(DFP_Actuals_as_of__c)
&amp;&amp; Exported_to_ERP__c = false 
&amp;&amp; Exported_to_Integration__c = false</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>Indicates if this line is valid to be auto-cancelled or not</inlineHelpText>
    <label>Valid for Auto-Cancellation</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/CS_Revenue_Schedule_Item__c/CS_Revenue_Schedule_Item__c.object-meta.xml
<CustomObject>
    <description>Individiual details for one billing period for one line within a Sales Order</description>
    <label>Revenue Schedule Item</label>
    <nameField>
        <displayFormat>REVI-{00000000}</displayFormat>
        <label>Revenue Recognition Schedule Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Revenue Schedule Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/CS_Revenue_Schedule_Item__c/fields/Revenue_Schedule__c.field-meta.xml
<CustomField>
    <fullName>Revenue_Schedule__c</fullName>
    <description>Link to Revenue Schedule Header</description>
    <inlineHelpText>Link to Revenue Schedule Header</inlineHelpText>
    <label>Revenue Schedule</label>
    <referenceTo>CS_Revenue_Schedule__c</referenceTo>
    <relationshipLabel>Revenue Schedule Items</relationshipLabel>
    <relationshipName>Revenue_Schedule_Items</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/CS_Revenue_Schedule_Item__c/fields/Sales_Order__c.field-meta.xml
<CustomField>
    <fullName>Sales_Order__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Link to the related Sales Order.</description>
    <inlineHelpText>Link to the related Sales Order.</inlineHelpText>
    <label>Sales Order</label>
    <referenceTo>csmso__Sales_Order__c</referenceTo>
    <relationshipLabel>Revenue Schedule Item</relationshipLabel>
    <relationshipName>CS_Revenue_Schedule_Item</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/CS_Revenue_Schedule_Item__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>Rev Rec Schedule Status.</description>
    <inlineHelpText>Rev Rec Schedule Status.</inlineHelpText>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Open</fullName>
            </value>
            <value>
                <fullName>Locked</fullName>
            </value>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Ready</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
            <value>
                <fullName>Forecast</fullName>
            </value>
            <value>
                <fullName>Pending Closure</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/CS_Revenue_Schedule_Item__c/fields/Valid_for_Auto_Cancellation__c.field-meta.xml
<CustomField>
    <fullName>Valid_for_Auto_Cancellation__c</fullName>
    <description>Indicates if this line is valid to be auto-cancelled or not</description>
    <formula>NOT(ISPICKVAL(Status__c, &#39;Cancelled&#39;))
&amp;&amp; X3rd_Party_Actuals__c = 0
&amp;&amp; ISBLANK(X3rd_Party_Actuals_as_of__c)
&amp;&amp; DFP_Actuals__c = 0
&amp;&amp; ISBLANK(DFP_Actuals_as_of__c)
&amp;&amp; Exported_to_ERP__c = false
&amp;&amp; Exported_to_Integration__c = false</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>Indicates if this line is valid to be auto-cancelled or not</inlineHelpText>
    <label>Valid for Auto-Cancellation</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/classes/CS_P_PrimarySOChange.cls
/**
* ─────────────────────────────────────────────────────────────────────────────────────────────────┐
* Used to update handle logic After Primary SO changes
* ──────────────────────────────────────────────────────────────────────────────────────────────────
* @author         Sasa Marjancic   <sasa.marjancic@cloudsense.com>
* ──────────────────────────────────────────────────────────────────────────────────────────────────
* @changes
* v1.0            sasa.marjancic@cloudsense.com
* 2018-10-22      Initial version
*
* @changes
* v2.0           aldo.topic@cloudsense.com
* 2020-03-09     When Primary Sales Order changes from true to false - remove/cancel BSI/RSI
* ─────────────────────────────────────────────────────────────────────────────────────────────────┘
*/
public class CS_P_PrimarySOChange extends CS_ProcessBase {
	@TestVisible
	Map<Id, csmso__Sales_Order__c> applicableObjects;

	@TestVisible
	Map<Id, csmso__Sales_Order__c> oldObjects;

	public CS_P_PrimarySOChange(Map<Id, csmso__Sales_Order__c> oldObjects) {
		super(CS_ProcessDefinition.PRIMARYSO_CHANGE, 'CS_P_PrimarySOChange');

		this.oldObjects = oldObjects;
		applicableObjects = new Map<Id, csmso__Sales_Order__c>();
	}

	public override void isRecordEligible(SObject obj) {
		csmso__Sales_Order__c newSalesOrder = (csmso__Sales_Order__c) obj;
		csmso__Sales_Order__c oldSalesOrder = oldObjects != null ? (csmso__Sales_Order__c) oldObjects.get(newSalesOrder.Id) : null;

		if(oldSalesOrder != null && oldSalesOrder.Primary_Sales_Order__c == true && newSalesOrder.Primary_Sales_Order__c == false) {
			applicableObjects.put(newSalesOrder.Id, newSalesOrder);
		}

		this.runProcess = !applicableObjects.isEmpty() && !CS_ProcessExecution.wasProcessExecuted(CS_ProcessDefinition.PRIMARYSO_CHANGE);
	}

	public override void logic() {
		List<SObject> scheduleItemsToCancel = new List<SObject>();
		List<SObject> scheduleItemsToDelete = new List<SObject>();
		Map<Id, CS_Billing_Schedule_Item__c> soToBScheduleItem = new Map<Id, CS_Billing_Schedule_Item__c>();
		Map<Id, CS_Revenue_Schedule_Item__c> soToRScheduleItem = new Map<Id, CS_Revenue_Schedule_Item__c>();

		List<CS_Billing_Schedule_Item__c> bScheduleItems = [
			SELECT Id, Status__c, Billing_Schedule__c, Valid_for_Auto_Cancellation__c, Sales_Order__c
				FROM CS_Billing_Schedule_Item__c
				WHERE Sales_Order__c = :applicableObjects.keySet()
		];

		List<CS_Revenue_Schedule_Item__c> rScheduleItems = [
			SELECT Id, Status__c, Revenue_Schedule__c, Valid_for_Auto_Cancellation__c, Sales_Order__c
				FROM CS_Revenue_Schedule_Item__c
				WHERE Sales_Order__c = :applicableObjects.keySet()
		];

		for(CS_Billing_Schedule_Item__c bsi : bScheduleItems) {
			soToBScheduleItem.put(bsi.Sales_Order__c, bsi);
		}

		for(CS_Revenue_Schedule_Item__c rsi : rScheduleItems) {
			soToRScheduleItem.put(rsi.Sales_Order__c, rsi);
		}

		for(csmso__Sales_Order__c salesOrder : applicableObjects.values()) {
			if (salesOrder.Sold__c && soToBScheduleItem.get(salesOrder.Id) != null) {
				scheduleItemsToCancel.add(soToBScheduleItem.get(salesOrder.Id));
			}
			else if (soToRScheduleItem.get(salesOrder.Id) != null) {
				scheduleItemsToDelete.add(soToRScheduleItem.get(salesOrder.Id));
			}
		}

		if(!scheduleItemsToCancel.isEmpty()) {
			CS_ScheduleService.cancelScheduleItems(scheduleItemsToCancel);
		}

		if(!scheduleItemsToDelete.isEmpty()) {
			CS_ScheduleService.deleteScheduleItems(scheduleItemsToDelete);
		}
	}
}