unpackaged/main/default/objects/CS_Billing_Schedule_Item__c/CS_Billing_Schedule_Item__c.object-meta.xml
<CustomObject>
    <description>Individiual details for one billing period for one line within a Sales Order</description>
    <label>Billing Schedule Item</label>
    <nameField>
        <displayFormat>BILI-{00000000}</displayFormat>
        <label>Billing Schedule Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Billing Schedule Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/CS_Billing_Schedule_Item__c/fields/Product_Configuration__c.field-meta.xml
<CustomField>
    <fullName>Product_Configuration__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Link to the related Product Configuration (Sales Order Line)</description>
    <inlineHelpText>Link to the related Product Configuration (Sales Order Line)</inlineHelpText>
    <label>Product Configuration</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>cscfga__Product_Configuration__c.Sales_Order__c</field>
            <operation>equals</operation>
            <valueField>$Source.Sales_Order__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>cscfga__Product_Configuration__c</referenceTo>
    <relationshipLabel>Billing Schedule Item</relationshipLabel>
    <relationshipName>Billing_Schedule_Item</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/CS_Billing_Schedule_Item__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>Billing Schedule Status.</description>
    <inlineHelpText>Billing Schedule Status</inlineHelpText>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Open</fullName>
            </value>
            <value>
                <fullName>Locked</fullName>
            </value>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Ready</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
            <value>
                <fullName>Forecast</fullName>
            </value>
            <value>
                <fullName>Pending Closure</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/CS_Billing_Schedule_Item__c/fields/Valid_for_Auto_Cancellation__c.field-meta.xml
<CustomField>
    <fullName>Valid_for_Auto_Cancellation__c</fullName>
    <description>Indicates if this line is valid to be auto-cancelled or not</description>
    <formula>NOT(ISPICKVAL(Status__c, &#39;Cancelled&#39;))
&amp;&amp; X3rd_Party_Actuals__c = 0
&amp;&amp; ISBLANK(X3rd_Party_Actuals_as_of__c)
&amp;&amp; DFP_Actuals__c = 0
&amp;&amp; ISBLANK(DFP_Actuals_as_of__c)
&amp;&amp; Exported_to_ERP__c = false 
&amp;&amp; Exported_to_Integration__c = false</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>Indicates if this line is valid to be auto-cancelled or not</inlineHelpText>
    <label>Valid for Auto-Cancellation</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/CS_Revenue_Schedule_Item__c/CS_Revenue_Schedule_Item__c.object-meta.xml
<CustomObject>
    <description>Individiual details for one billing period for one line within a Sales Order</description>
    <label>Revenue Schedule Item</label>
    <nameField>
        <displayFormat>REVI-{00000000}</displayFormat>
        <label>Revenue Recognition Schedule Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Revenue Schedule Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/CS_Revenue_Schedule_Item__c/fields/Product_Configuration__c.field-meta.xml
<CustomField>
    <fullName>Product_Configuration__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Link to the related Product Configuration (Sales Order Line)</description>
    <inlineHelpText>Link to the related Product Configuration (Sales Order Line)</inlineHelpText>
    <label>Product Configuration</label>
    <referenceTo>cscfga__Product_Configuration__c</referenceTo>
    <relationshipLabel>Revenue Schedule Item</relationshipLabel>
    <relationshipName>Revenue_Schedule_Item</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/CS_Revenue_Schedule_Item__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>Rev Rec Schedule Status.</description>
    <inlineHelpText>Rev Rec Schedule Status.</inlineHelpText>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Open</fullName>
            </value>
            <value>
                <fullName>Locked</fullName>
            </value>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Ready</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
            <value>
                <fullName>Forecast</fullName>
            </value>
            <value>
                <fullName>Pending Closure</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/CS_Revenue_Schedule_Item__c/fields/Valid_for_Auto_Cancellation__c.field-meta.xml
<CustomField>
    <fullName>Valid_for_Auto_Cancellation__c</fullName>
    <description>Indicates if this line is valid to be auto-cancelled or not</description>
    <formula>NOT(ISPICKVAL(Status__c, &#39;Cancelled&#39;))
&amp;&amp; X3rd_Party_Actuals__c = 0
&amp;&amp; ISBLANK(X3rd_Party_Actuals_as_of__c)
&amp;&amp; DFP_Actuals__c = 0
&amp;&amp; ISBLANK(DFP_Actuals_as_of__c)
&amp;&amp; Exported_to_ERP__c = false
&amp;&amp; Exported_to_Integration__c = false</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>Indicates if this line is valid to be auto-cancelled or not</inlineHelpText>
    <label>Valid for Auto-Cancellation</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/classes/ArchiveNonServedLineController.cls
global with sharing class ArchiveNonServedLineController implements csmso.CSRemoteActionDelegation.CSRemoteActionDelegate {
    global String performAction(String parameters) {
    	if (String.isEmpty(parameters)){
    		return JSON.serialize('error');
    	}
        
        // update BSI status 
        List<CS_Billing_Schedule_Item__c> billingSchedulesToUpdate = new List<CS_Billing_Schedule_Item__c>();
        for (CS_Billing_Schedule_Item__c currentBSI : [SELECT Id, Status__c
                                                       FROM CS_Billing_Schedule_Item__c
                                                       WHERE Product_Configuration__c = :parameters
                                                             AND Valid_for_Auto_Cancellation__c = true]) {
	        currentBSI.Status__c = CS_const_SalesOrder.ScheduleStatus_Cancelled;
            billingSchedulesToUpdate.add(currentBSI);
	    }
	    if (billingSchedulesToUpdate.size() > 0) {
	    	UPDATE billingSchedulesToUpdate;
	    }

	    // update RSI status 
        List<CS_Revenue_Schedule_Item__c> revenueSchedulesToUpdate = new List<CS_Revenue_Schedule_Item__c>();
        for (CS_Revenue_Schedule_Item__c currentRSI : [SELECT Id, Status__c
                                                       FROM CS_Revenue_Schedule_Item__c
                                                       WHERE Product_Configuration__c = :parameters
                                                             AND Valid_for_Auto_Cancellation__c = true]) {
	        currentRSI.Status__c = CS_const_SalesOrder.ScheduleStatus_Cancelled;
            revenueSchedulesToUpdate.add(currentRSI);
	    }
	    if (revenueSchedulesToUpdate.size() > 0) {
	    	UPDATE revenueSchedulesToUpdate;
	    }

        // update FI status 
        List<csdf__Fulfilment_Item__c> fulfilmentItemsToUpdate = new List<csdf__Fulfilment_Item__c>();
        for (csdf__Fulfilment_Item__c currentFI : [SELECT id, csdf__Status__c 
                                                   FROM csdf__Fulfilment_Item__c 
                                                   WHERE Product_Configuration__c=:parameters 
                                                         AND csdf__Status__c != :CS_const_SalesOrder.FulfilmentItemStatus_PausedInventoryReleased]) {
	        currentFI.csdf__Status__c = CS_const_SalesOrder.FulfilmentItemStatus_PausedInventoryReleased;
            fulfilmentItemsToUpdate.add(currentFI);
	    }
	    if (fulfilmentItemsToUpdate.size() > 0) {
	    	UPDATE fulfilmentItemsToUpdate;
	    }

    	return JSON.serialize('Success');
    }
}