unpackaged/main/default/objects/CS_Billing_Schedule_Item__c/CS_Billing_Schedule_Item__c.object-meta.xml
<CustomObject>
    <description>Individiual details for one billing period for one line within a Sales Order</description>
    <label>Billing Schedule Item</label>
    <nameField>
        <displayFormat>BILI-{00000000}</displayFormat>
        <label>Billing Schedule Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Billing Schedule Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/CS_Billing_Schedule_Item__c/fields/Billing_Calendar__c.field-meta.xml
<CustomField>
    <fullName>Billing_Calendar__c</fullName>
    <description>Billing Calendar as defined in the Sales Order
- Standard
- Broadcast</description>
    <inlineHelpText>Billing Calendar as defined in the Sales Order
- Standard
- Broadcast</inlineHelpText>
    <label>Billing Calendar</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Standard</fullName>
            </value>
            <value>
                <fullName>Broadcast</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/CS_Billing_Schedule_Item__c/fields/Billing_Date__c.field-meta.xml
<CustomField>
    <fullName>Billing_Date__c</fullName>
    <description>Billing Date based on the Billing Rule + Billing Calendar.
-Monthly Standard  : Last day of each Standard Calendar Month from SO line item  Start to End of Campaign.
-Monthly Broadcast: Last day of each Broadcast Calendar Month from SO line item  Start to End of Campaign</description>
    <inlineHelpText>Billing Date based on the Billing Rule + Billing Calendar</inlineHelpText>
    <label>Billing Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/CS_Billing_Schedule_Item__c/fields/Billing_Source__c.field-meta.xml
<CustomField>
    <fullName>Billing_Source__c</fullName>
    <description>Billing Rule as defined in the Sales Order Line
 - Contracted
 - DFP Actuals
 - 3rd Party Actuals</description>
    <inlineHelpText>Billing Rule as defined in the Sales Order Line
 - Contracted
 - DFP Actuals
 - 3rd Party Actuals</inlineHelpText>
    <label>Billing Source</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Contracted</fullName>
            </value>
            <value>
                <fullName>DFP Actuals</fullName>
            </value>
            <value>
                <fullName>3rd Party Actuals</fullName>
            </value>
            <value>
                <fullName>Megaphone</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/CS_Billing_Schedule_Item__c/fields/Flight_Begin__c.field-meta.xml
<CustomField>
    <fullName>Flight_Begin__c</fullName>
    <description>Flight Begin as defined in the Sales Order Line.</description>
    <inlineHelpText>Flight Begin as defined in the Sales Order Line.</inlineHelpText>
    <label>Flight Begin</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/CS_Billing_Schedule_Item__c/fields/Insertion_Unit_Type__c.field-meta.xml
<CustomField>
    <fullName>Insertion_Unit_Type__c</fullName>
    <description>Insertion Unit Type as defined in the Sales Order Line.</description>
    <inlineHelpText>Insertion Unit Type as defined in the Sales Order Line.</inlineHelpText>
    <label>Insertion Unit Type</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/CS_Billing_Schedule_Item__c/fields/Product_Configuration__c.field-meta.xml
<CustomField>
    <fullName>Product_Configuration__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Link to the related Product Configuration (Sales Order Line)</description>
    <inlineHelpText>Link to the related Product Configuration (Sales Order Line)</inlineHelpText>
    <label>Product Configuration</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>cscfga__Product_Configuration__c.Sales_Order__c</field>
            <operation>equals</operation>
            <valueField>$Source.Sales_Order__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>cscfga__Product_Configuration__c</referenceTo>
    <relationshipLabel>Billing Schedule Item</relationshipLabel>
    <relationshipName>Billing_Schedule_Item</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/CS_Billing_Schedule_Item__c/fields/X3rd_Party_Ad_Server__c.field-meta.xml
<CustomField>
    <fullName>X3rd_Party_Ad_Server__c</fullName>
    <description>3rd Party Ad Server as defined in the Sales Order Line.</description>
    <inlineHelpText>3rd Party Ad Server as defined in the Sales Order Line.</inlineHelpText>
    <label>3rd Party Ad Server</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/CS_Revenue_Schedule_Item__c/CS_Revenue_Schedule_Item__c.object-meta.xml
<CustomObject>
    <description>Individiual details for one billing period for one line within a Sales Order</description>
    <label>Revenue Schedule Item</label>
    <nameField>
        <displayFormat>REVI-{00000000}</displayFormat>
        <label>Revenue Recognition Schedule Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Revenue Schedule Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/CS_Revenue_Schedule_Item__c/fields/Billing_Source__c.field-meta.xml
<CustomField>
    <fullName>Billing_Source__c</fullName>
    <description>Billing Rule as defined in the Sales Order Line.</description>
    <inlineHelpText>Billing Rule as defined in the Sales Order Line.</inlineHelpText>
    <label>Billing Source</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Contracted</fullName>
            </value>
            <value>
                <fullName>DFP Actuals</fullName>
            </value>
            <value>
                <fullName>3rd Party Actuals</fullName>
            </value>
            <value>
                <fullName>Megaphone</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/CS_Revenue_Schedule_Item__c/fields/Flight_End__c.field-meta.xml
<CustomField>
    <fullName>Flight_End__c</fullName>
    <description>Flight End as defined in the Sales Order Line.</description>
    <inlineHelpText>Flight End as defined in the Sales Order Line.</inlineHelpText>
    <label>Flight End</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/CS_Revenue_Schedule_Item__c/fields/Product_Configuration__c.field-meta.xml
<CustomField>
    <fullName>Product_Configuration__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Link to the related Product Configuration (Sales Order Line)</description>
    <inlineHelpText>Link to the related Product Configuration (Sales Order Line)</inlineHelpText>
    <label>Product Configuration</label>
    <referenceTo>cscfga__Product_Configuration__c</referenceTo>
    <relationshipLabel>Revenue Schedule Item</relationshipLabel>
    <relationshipName>Revenue_Schedule_Item</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/CS_Revenue_Schedule_Item__c/fields/Rev_Rec_Date__c.field-meta.xml
<CustomField>
    <fullName>Rev_Rec_Date__c</fullName>
    <description>Rev Rec Date based on the Rev Rec Rule +Rev Rec Calendar.
-Monthly Standard : Last day of each Standard Calendar Month from SO Line Item Start to End of Campaign</description>
    <inlineHelpText>Rev Rec Date based on the Rev Rec Rule +Rev Rec Calendar.
-Monthly Standard : Last day of each Standard Calendar Month from SO Line Item Start to End of Campaign</inlineHelpText>
    <label>Rev Rec Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/CS_Revenue_Schedule_Item__c/fields/Third_Party_Monthly_Actuals__c.field-meta.xml
<CustomField>
    <fullName>Third_Party_Monthly_Actuals__c</fullName>
    <label>Third Party Monthly Actuals</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/Third_Party_Monthly_Actual__c/Third_Party_Monthly_Actual__c.object-meta.xml
<CustomObject>
    <label>Third Party Monthly Actual</label>
    <nameField>
        <displayFormat>TPMAR-{00000}</displayFormat>
        <label>Third Party Monthly Actual</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Third Party Monthly Actuals</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Third_Party_Monthly_Actual__c/fields/Local_Server_Name__c.field-meta.xml
<CustomField>
    <fullName>Local_Server_Name__c</fullName>
    <label>Local Server Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/X3rd_Party_Ad_Server__c/X3rd_Party_Ad_Server__c.object-meta.xml
<CustomObject>
    <description>Object to store 3rd Party Ad Server values</description>
    <label>3rd Party Ad Server</label>
    <nameField>
        <displayFormat>AS-{00000000}</displayFormat>
        <label>Ad Server Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>3rd Party Ad Servers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/X3rd_Party_Ad_Server__c/fields/X3rd_Party_Ad_Server__c.field-meta.xml
<CustomField>
    <fullName>X3rd_Party_Ad_Server__c</fullName>
    <description>Values for 3rd Party Ad Server from DFP Spotify Prod definition</description>
    <inlineHelpText>Values for 3rd Party Ad Server from DFP Spotify Prod definition</inlineHelpText>
    <label>3rd Party Ad Server</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>MediaMind</fullName>
            </value>
            <value>
                <fullName>DFA by Google</fullName>
            </value>
            <value>
                <fullName>FlashTalking</fullName>
            </value>
            <value>
                <fullName>Innovid3P</fullName>
            </value>
            <value>
                <fullName>Dart Report Reader</fullName>
            </value>
            <value>
                <fullName>Mediaplex</fullName>
            </value>
            <value>
                <fullName>Rubicon</fullName>
            </value>
            <value>
                <fullName>EyeReturn</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/classes/CS_BatchConsolidateThirdPartyActuals.cls
/**
 * Created by jameshladek on 2/11/20.
 *
 * This is a batch class that gathers Third Party Monthly Actuals data as related to a product configuration
 * then calculate the total number of Clicks or Impressions based on tne Insertion Unit Type on the
 * Product Configuration. Then take this total and put it on the related Billing Schedule Item and
 * Revenue Schedule Item
 *
 * @since February 11, 2020
 * @version 1.0
 * @author james.hladek@cloudsense.com
 */

public with sharing class CS_BatchConsolidateThirdPartyActuals extends CS_BatchWorker {

    /**
     * The constructor that will be called from the scheduler
     */
    public CS_BatchConsolidateThirdPartyActuals() {
        super('CS_BatchConsolidateThirdPartyActuals', 10);
    }

    public static void scheduleIt() {
        System.schedule('Consolidate 3rd Party Monthly Actuals', '0 0 20 3 * ?', new CS_BatchConsolidateThirdPartyActuals());
    }

    /**
     * Constructor that accepts two parameters and calls the parent class to start the batch process
     *
     * @param processName
     * @param batchSize
     */
    public override void init(String processName, Integer batchSize) {
        super.init(processName, batchSize);

        List<csdf__Custom_Report_Execution__c> reportExecution = [
                SELECT Id, csdf__Report_Status__c
                FROM csdf__Custom_Report_Execution__c
                WHERE CreatedDate = TODAY
                AND csdf__Custom_Report_Definition__r.Scheduled_Execution__c = TRUE
                AND csdf__Report_Status__c != 'Integration Error'
                AND csdf__Report_Status__c != 'Completed'
        ];
        this.delayExecution = !reportExecution.isEmpty();

    }

    /**
     * Method is used as the Start functionality on a Salesforce batch process.
     * The method gets the queryString to query for the Product Configurations,
     * Billing Schedule Items and Revenue Schedule Items. And passes back to the
     * parent method the performs query and passes the list on to the execute method.
     *
     * @return
     */
    public override Database.QueryLocator onStart() {
        this.queryString = getQueryString();
        return super.onStart();
    }

    /**
     * This method performs the work to be done by the batch process. The method queries the
     * Third Party Monthly Actuals records to calculate the number of Clicks or Impressions
     * That are related to the Product Configuration. After the data is tabulated the values
     * are populated on the Billing Schedule Item and the Revenue Schedule Item and then updates
     * these items.
     *
     * @param scope List of Product Configurations with Billing Schedule Items and Revenue Schedule Items.
     */
    public override void doWork(List<SObject> scope) {
        List<cscfga__Product_Configuration__c> configs = (List<cscfga__Product_Configuration__c>) scope;
        Set<String> lineIds = new Set<String>();
        List<SObject> billingScheduleItems = new List<SObject>();
        List<SObject> revenueScheduleItems = new List<SObject>();
        Map<String, List<AggregateResult>> resultById = new Map<String, List<AggregateResult>>();

        for (cscfga__Product_Configuration__c config : configs) {
            lineIds.add(config.Order_Line_ID__c);
        }
        for (AggregateResult result : getMonthlyAcutals(lineIds)) {
            String lineId = (String) result.get('Order_Line_Id__c');
            List<AggregateResult> results = resultById.get('lineId');
            if (results == null) {
                results = new List<AggregateResult>();
            }
            results.add(result);
            resultById.put(lineId, results);
        }
        for (cscfga__Product_Configuration__c pc : configs) {
            Decimal monthlyTotal = 0;
            if (resultById.containsKey(pc.Order_Line_ID__c)) {
                for (AggregateResult monthlyResult : resultById.get(pc.Order_Line_ID__c)) {
                    String localServer = (String) monthlyResult.get('Local_Server_Name__c');
                    if (pc.X3rd_Party_Ad_Server_Name__c == localServer) {
                        if (pc.Insertion_Unit_Type__c.equalsIgnoreCase('CPC')) {
                            monthlyTotal = (Decimal) monthlyResult.get('expr0');
                        } else {
                            monthlyTotal = (Decimal) monthlyResult.get('expr1');
                        }
                        for (CS_Billing_Schedule_Item__c bsi : pc.Billing_Schedule_Item__r) {
                            if(bsi.Billing_Calendar__c == CS_const_BillingScheduleItem.BillingCalendar_Standard) {
                                bsi.Third_Party_Monthly_Actuals__c = monthlyTotal;
                                billingScheduleItems.add(bsi);
                            }
                        }
                        for (CS_Revenue_Schedule_Item__c rsi : pc.Revenue_Schedule_Item__r) {
                            rsi.Third_Party_Monthly_Actuals__c = monthlyTotal;
                            revenueScheduleItems.add(rsi);
                        }

                    }
                }
            }
        }
        update billingScheduleItems;
        update revenueScheduleItems;
    }

/**
 * The string that is generated for the use in the Database.query method
 *
 * @return
 */
    private String getQueryString() {
        String query = 'SELECT Id, Flight_Begin__c, Flight_End__c, Insertion_Unit_Type__c, Order_Line_Id__c, X3rd_Party_Ad_Server_Name__c,' +
                ' (SELECT Id, Third_Party_Monthly_Actuals__c, Insertion_Unit_Type__c, X3rd_Party_Ad_Server__c, Product_Configuration__r.X3rd_Party_Ad_Server_Name__c, Billing_Calendar__c FROM Billing_Schedule_Item__r WHERE Billing_Date__c = LAST_MONTH),' +
                ' (SELECT Id, Third_Party_Monthly_Actuals__c, Insertion_Unit_Type__c, X3rd_Party_Ad_Server__c, Product_Configuration__r.X3rd_Party_Ad_Server_Name__c FROM Revenue_Schedule_Item__r WHERE Rev_Rec_Date__c = LAST_MONTH)' +
                ' FROM cscfga__Product_Configuration__c WHERE (Flight_Begin__c <= LAST_MONTH AND FLight_End__c >= LAST_MONTH) AND Billing_Source__c = \'3rd Party Actuals\'';
        return query;
    }

/**
 * Queries for the Third Party Monthly Actual records that are related to Product Configurations
 *
 * @param orderLineIds Set of Product Configuration ids.
 *
 * @return
 */
    private List<AggregateResult> getMonthlyAcutals(Set<String> orderLineIds) {
        return (List<AggregateResult>) [
                SELECT Order_Line_Id__c, Local_Server_Name__c, SUM(Clicks__c), SUM(Impressions__c)
                FROM Third_Party_Monthly_Actual__c
                WHERE Order_Line_Id__c IN :orderLineIds
                AND Report_Date__c = LAST_MONTH
                GROUP BY Order_Line_Id__c, Local_Server_Name__c
        ];
    }

}