unpackaged/main/default/objects/CS_Billing_Schedule_Item__c/CS_Billing_Schedule_Item__c.object-meta.xml
<CustomObject>
    <description>Individiual details for one billing period for one line within a Sales Order</description>
    <label>Billing Schedule Item</label>
    <nameField>
        <displayFormat>BILI-{00000000}</displayFormat>
        <label>Billing Schedule Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Billing Schedule Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/CS_Billing_Schedule_Item__c/fields/Flight_Begin__c.field-meta.xml
<CustomField>
    <fullName>Flight_Begin__c</fullName>
    <description>Flight Begin as defined in the Sales Order Line.</description>
    <inlineHelpText>Flight Begin as defined in the Sales Order Line.</inlineHelpText>
    <label>Flight Begin</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/CS_Billing_Schedule_Item__c/fields/Product_Configuration__c.field-meta.xml
<CustomField>
    <fullName>Product_Configuration__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Link to the related Product Configuration (Sales Order Line)</description>
    <inlineHelpText>Link to the related Product Configuration (Sales Order Line)</inlineHelpText>
    <label>Product Configuration</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>cscfga__Product_Configuration__c.Sales_Order__c</field>
            <operation>equals</operation>
            <valueField>$Source.Sales_Order__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>cscfga__Product_Configuration__c</referenceTo>
    <relationshipLabel>Billing Schedule Item</relationshipLabel>
    <relationshipName>Billing_Schedule_Item</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/CS_Billing_Schedule_Item__c/fields/Scheduled_Quantity__c.field-meta.xml
<CustomField>
    <fullName>Scheduled_Quantity__c</fullName>
    <description>Scheduled Quantity is calculated as the pro-rata Contracted Quantity based on the Billing Start Period and Billing End Period for each Billing Schedule Line
Scheduled Quantity is calculated as an integer and adjustments to accommodate the pro-rata calculation are included on the last period</description>
    <inlineHelpText>Scheduled Quantity is calculated as the pro-rata Contracted Quantity based on the Billing Start Period and Billing End Period for each Billing Schedule Line
Scheduled Quantity is calculated as an integer and adjustments to accommodate the pro-rata calcul</inlineHelpText>
    <label>Scheduled Quantity</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/classes/CS_BillingScheduleTest.cls
/**
* ─────────────────────────────────────────────────────────────────────────────────────────────────┐
* Description : Test Class for CS_BillingSchedule
* ──────────────────────────────────────────────────────────────────────────────────────────────────
* @author     : Kalyan Erraguntla <kalyan.erraguntla@cloudsensesolutions.com>
* ──────────────────────────────────────────────────────────────────────────────────────────────────
*/
@isTest
public class CS_BillingScheduleTest {
    /**
     *  schedule mapping
     */	
	@isTest
    public static void test_getScheduleMapping() {
    	CS_Billing_Schedule_Item__c bSchedule = new CS_Billing_Schedule_Item__c();
    	
        Test.startTest();
        
        CS_BillingSchedule bs = new CS_BillingSchedule();
        system.assertequals( bs.getScheduleMapping().get('scheduledQuantity'),'Scheduled_Quantity__c');
        system.assertequals( bs.getScheduleMapping().get('flightBegin'),'Flight_Begin__c');
        system.assertequals( bs.getScheduleMapping().get('flightEnd'),'Flight_End__c');
        system.assertequals( bs.getScheduleMapping().get('productConfigId'),'Product_Configuration__c');
        
        Test.stopTest();
    }
    
    
    /**
     * start date for schedule
     */	
	@isTest
    public static void test_getScheduleStartDate() {
    	CS_Billing_Schedule_Item__c bSchedule = new CS_Billing_Schedule_Item__c();
    	
        Test.startTest();
        
        CS_BillingSchedule bs = new CS_BillingSchedule();
        system.assertequals( bs.getScheduleStartDate(bSchedule),null);
        Test.stopTest();
    }
    
    /**
     *  end date for schedule
     */	
	@isTest
    public static void test_getScheduleEndDate() {
    	CS_Billing_Schedule_Item__c bSchedule = new CS_Billing_Schedule_Item__c();
        
        Test.startTest();
        
        CS_BillingSchedule bs = new CS_BillingSchedule();
        system.assertequals( bs.getScheduleEndDate(bSchedule),null);
        
        Test.stopTest();
    }
    
}