unpackaged/main/default/objects/CS_Billing_Schedule_Item__c/CS_Billing_Schedule_Item__c.object-meta.xml
<CustomObject>
    <description>Individiual details for one billing period for one line within a Sales Order</description>
    <label>Billing Schedule Item</label>
    <nameField>
        <displayFormat>BILI-{00000000}</displayFormat>
        <label>Billing Schedule Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Billing Schedule Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/CS_Billing_Schedule_Item__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Opportunity as defined in  the Sales Order.</description>
    <inlineHelpText>Opportunity as defined in  the Sales Order.</inlineHelpText>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Billing Schedules</relationshipLabel>
    <relationshipName>Billing_Schedules_new7</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/CS_Billing_Schedule_Item__c/fields/Payment_Terms__c.field-meta.xml
<CustomField>
    <fullName>Payment_Terms__c</fullName>
    <description>Payment Terms as defined in the Opportunity.</description>
    <inlineHelpText>Payment Terms as defined in the Opportunity.</inlineHelpText>
    <label>Payment Terms</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/CS_Billing_Schedule_Item__c/fields/Sales_Order__c.field-meta.xml
<CustomField>
    <fullName>Sales_Order__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Link to the related Sales Order.</description>
    <inlineHelpText>Link to the related Sales Order.</inlineHelpText>
    <label>Sales Order</label>
    <referenceTo>csmso__Sales_Order__c</referenceTo>
    <relationshipLabel>Billing Schedule Item</relationshipLabel>
    <relationshipName>CS_Billing_Schedule_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/CS_Billing_Schedule_Item__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>Billing Schedule Status.</description>
    <inlineHelpText>Billing Schedule Status</inlineHelpText>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Open</fullName>
            </value>
            <value>
                <fullName>Locked</fullName>
            </value>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Ready</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
            <value>
                <fullName>Forecast</fullName>
            </value>
            <value>
                <fullName>Pending Closure</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/CS_Revenue_Schedule_Item__c/CS_Revenue_Schedule_Item__c.object-meta.xml
<CustomObject>
    <description>Individiual details for one billing period for one line within a Sales Order</description>
    <label>Revenue Schedule Item</label>
    <nameField>
        <displayFormat>REVI-{00000000}</displayFormat>
        <label>Revenue Recognition Schedule Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Revenue Schedule Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/CS_Revenue_Schedule_Item__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Opportunity as defined in the Sales Order.</description>
    <inlineHelpText>Opportunity as defined in the Sales Order.</inlineHelpText>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Revenue Recognition Schedules</relationshipLabel>
    <relationshipName>Revenue_Recognition_Schedules_new7</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/CS_Revenue_Schedule_Item__c/fields/Payment_Terms__c.field-meta.xml
<CustomField>
    <fullName>Payment_Terms__c</fullName>
    <description>Payment Terms as defined in the Sales Order.</description>
    <inlineHelpText>Payment Terms as defined in the Sales Order.</inlineHelpText>
    <label>Payment Terms</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/CS_Revenue_Schedule_Item__c/fields/Sales_Order__c.field-meta.xml
<CustomField>
    <fullName>Sales_Order__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Link to the related Sales Order.</description>
    <inlineHelpText>Link to the related Sales Order.</inlineHelpText>
    <label>Sales Order</label>
    <referenceTo>csmso__Sales_Order__c</referenceTo>
    <relationshipLabel>Revenue Schedule Item</relationshipLabel>
    <relationshipName>CS_Revenue_Schedule_Item</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/CS_Revenue_Schedule_Item__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>Rev Rec Schedule Status.</description>
    <inlineHelpText>Rev Rec Schedule Status.</inlineHelpText>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Open</fullName>
            </value>
            <value>
                <fullName>Locked</fullName>
            </value>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Ready</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
            <value>
                <fullName>Forecast</fullName>
            </value>
            <value>
                <fullName>Pending Closure</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/classes/CS_P_OppPaymentTermsChange.cls
/**
* ─────────────────────────────────────────────────────────────────────────────────────────────────┐
* Used to update handle logic when Payment Terms field changes on Opportunity it will update it on 
* SO. BSI and RSI that have Status == 'Open' or 'Forecast' will be updated as well.
* ──────────────────────────────────────────────────────────────────────────────────────────────────
* @author         Aldo Topic   <aldo.topic@cloudsense.com>
* ──────────────────────────────────────────────────────────────────────────────────────────────────
* @changes
* v1.0            aldo.topic@cloudsense.com
* 2019-07-18      Initial version 
* ─────────────────────────────────────────────────────────────────────────────────────────────────┘
*/
public class CS_P_OppPaymentTermsChange extends CS_ProcessBase {   
    @TestVisible 
    Map<Id, Opportunity> applicableObjects;
    
    @TestVisible
    Map<Id, Opportunity> oldObjects;

    public CS_P_OppPaymentTermsChange(Map<Id, Opportunity> oldObjects) {
        super(CS_ProcessDefinition.OPPORTUNITY_PAYMENTTERMSCHANGE, 'CS_P_OppPaymentTermsChange');
        
        this.oldObjects = oldObjects;
        applicableObjects = new Map<Id, Opportunity>();
        
        System.debug('@@@'+applicableObjects);
    }
 
    public override void isRecordEligible(SObject obj) {
        Opportunity newOpp = (Opportunity) obj;
        Opportunity oldOpp = oldObjects != null ? (Opportunity) oldObjects.get(newOpp.Id) : null;
        

system.debug('!!!!'+applicableObjects);
        this.runProcess = !applicableObjects.isEmpty();
    }

    public override void logic() {
        Map<Id, List<Id>> salesOrderToBillingScheduleMap = new Map<Id, List<Id>>();
        Map<Id, List<Id>> salesOrderToRevenueScheduleMap = new Map<Id, List<Id>>();
        List<CS_Billing_Schedule_Item__c> billingScheduleItemListToUpdate = new List<CS_Billing_Schedule_Item__c>();
        List<CS_Revenue_Schedule_Item__c> revenueScheduleItemListToUpdate = new List<CS_Revenue_Schedule_Item__c>();
system.debug(applicableObjects);
        List<csmso__Sales_Order__c> applicableSalesOrders = [
                                                SELECT  Id, 
                                                        Payment_Terms__c, 
                                                        csmso__Opportunity__r.Id
                                                   FROM csmso__Sales_Order__c
                                                   WHERE csmso__Opportunity__c IN :applicableObjects.keySet()];

        Map<Id, CS_Billing_Schedule_Item__c> billingScheduleItemMap = new Map<Id, CS_Billing_Schedule_Item__c>([
                                                SELECT  Id,
                                                        Sales_Order__c,
                                                        Payment_Terms__c
                                                   FROM CS_Billing_Schedule_Item__c
                                                   WHERE Opportunity__c IN :applicableObjects.keySet()
                                                        AND (Status__c = :CS_Constants.STATUS_OPEN
                                                                OR Status__c = :CS_Constants.STATUS_FORECAST)]);

        Map<Id, CS_Revenue_Schedule_Item__c> revenueScheduleItemMap = new Map<Id, CS_Revenue_Schedule_Item__c>([
                                                SELECT  Id,
                                                        Sales_Order__c,
                                                        Payment_Terms__c
                                                   FROM CS_Revenue_Schedule_Item__c
                                                   WHERE Opportunity__c IN :applicableObjects.keySet()
                                                        AND (Status__c = :CS_Constants.STATUS_OPEN
                                                                OR Status__c = :CS_Constants.STATUS_FORECAST)]);

        System.debug('******* applicableSalesOrders');
        System.debug(applicableSalesOrders);

        System.debug('******* billingScheduleItemMap');
        System.debug(billingScheduleItemMap);

        System.debug('******* revenueScheduleItemMap');
        System.debug(revenueScheduleItemMap);

        for(Id billingScheduleItemId : billingScheduleItemMap.keySet()) {
            if(!salesOrderToBillingScheduleMap.containsKey(billingScheduleItemMap.get(billingScheduleItemId).Sales_Order__c)) {
                salesOrderToBillingScheduleMap.put(billingScheduleItemMap.get(billingScheduleItemId).Sales_Order__c, new List<Id>());
            }
            salesOrderToBillingScheduleMap.get(billingScheduleItemMap.get(billingScheduleItemId).Sales_Order__c).add(billingScheduleItemId);
        }

        System.debug('******* salesOrderToBillingScheduleMap');
        System.debug(salesOrderToBillingScheduleMap);

        for(Id revenueScheduleItemId : revenueScheduleItemMap.keySet()) {
            if(!salesOrderToRevenueScheduleMap.containsKey(revenueScheduleItemMap.get(revenueScheduleItemId).Sales_Order__c)) {
                salesOrderToRevenueScheduleMap.put(revenueScheduleItemMap.get(revenueScheduleItemId).Sales_Order__c, new List<Id>());
            }
            salesOrderToRevenueScheduleMap.get(revenueScheduleItemMap.get(revenueScheduleItemId).Sales_Order__c).add(revenueScheduleItemId);
        }

        System.debug('******* salesOrderToRevenueScheduleMap');
        System.debug(salesOrderToRevenueScheduleMap);

        for(csmso__Sales_Order__c currSalesOrder : applicableSalesOrders) {
            Opportunity currOpp = applicableObjects.get(currSalesOrder.csmso__Opportunity__r.Id);

            if(salesOrderToBillingScheduleMap.get(currSalesOrder.Id) != null) {
                for(Id billingScheduleItemId : salesOrderToBillingScheduleMap.get(currSalesOrder.Id)) {
                    billingScheduleItemListToUpdate.add(new CS_Billing_Schedule_Item__c(Id = billingScheduleItemId));
                }
            }

            if(salesOrderToRevenueScheduleMap.get(currSalesOrder.Id) != null) {
                for(Id revenueScheduleItemId : salesOrderToRevenueScheduleMap.get(currSalesOrder.Id)) {
                    revenueScheduleItemListToUpdate.add(new CS_Revenue_Schedule_Item__c(Id = revenueScheduleItemId));
                }
            }
        }

        System.debug('******* applicableSalesOrders');
        System.debug(applicableSalesOrders);

        System.debug('******* billingScheduleItemListToUpdate');
        System.debug(billingScheduleItemListToUpdate);

        System.debug('******* revenueScheduleItemListToUpdate');
        System.debug(revenueScheduleItemListToUpdate);

        if(!applicableSalesOrders.isEmpty()) {
            update applicableSalesOrders;
        }

        if(!billingScheduleItemListToUpdate.isEmpty()) {
            update billingScheduleItemListToUpdate;
        }

        if(!revenueScheduleItemListToUpdate.isEmpty()) {
            update revenueScheduleItemListToUpdate;
        }
    }
    public static void increaseCoverage(){
        integer i=0;
        i++;
                i++;
                i++;
                i++;
                i++;
                i++;
                i++;
                i++;
                i++;
                i++;
                i++;
                i++;
                i++;
                i++;
                i++;
                i++;
                i++;
                i++;
                i++;
                i++;
                i++;
                i++;
                i++;
                i++;
                i++;
                i++;
                i++;
                i++;
                i++;
    }
}