unpackaged/main/default/objects/Bill_Run__c/Bill_Run__c.object-meta.xml
<CustomObject>
    <description>Bill Run object is used to schedule Billing Date. With that he is also setting Lock and Auto-Reconciliation Date. Also contains Calendar Type and Status fields.</description>
    <label>Bill Run</label>
    <nameField>
        <displayFormat>BR-{00000000}</displayFormat>
        <label>Bill Run No</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Bill Runs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Bill_Run__c/fields/Billing_Date__c.field-meta.xml
<CustomField>
    <fullName>Billing_Date__c</fullName>
    <description>Set the Billing Date or the Revenue Period End Date of Bill Run.</description>
    <inlineHelpText>Set the Billing Date or the Revenue Period End Date of Bill Run.</inlineHelpText>
    <label>Billing / Revenue Date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/Bill_Run__c/fields/Calendar_Type__c.field-meta.xml
<CustomField>
    <fullName>Calendar_Type__c</fullName>
    <description>Calendar Type - can be Standard or Broadcast.</description>
    <inlineHelpText>Calendar Type - can be Standard or Broadcast.</inlineHelpText>
    <label>Calendar Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Standard</fullName>
                <default>true</default>
                <label>Standard</label>
            </value>
            <value>
                <fullName>Broadcast</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Bill_Run__c/fields/Is_Lock_Billing_Date__c.field-meta.xml
<CustomField>
    <fullName>Is_Lock_Billing_Date__c</fullName>
    <formula>If(ISNULL(Reference_Date__c), Lock_Billing_Date__c &lt;= TODAY(), Lock_Billing_Date__c &lt;= Reference_Date__c)</formula>
    <label>Is Lock Billing Date</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Bill_Run__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>Status of the Bill Run.</description>
    <inlineHelpText>Status of the Bill Run.</inlineHelpText>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Scheduled</fullName>
                <default>true</default>
                <label>Scheduled</label>
            </value>
            <value>
                <fullName>Locking Bill Schedules</fullName>
            </value>
            <value>
                <fullName>Auto-Reconciliating</fullName>
            </value>
            <value>
                <fullName>Complete</fullName>
            </value>
            <value>
                <fullName>Consolidating Actuals</fullName>
                <isActive>false</isActive>
                <label>Consolidating Actuals</label>
            </value>
            <value>
                <fullName>Recalculating Billing Schedules</fullName>
                <isActive>false</isActive>
                <label>Recalculating Billing Schedules</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Bill_Run__c/recordTypes/Billing.recordType-meta.xml
<RecordType>
    <fullName>Billing</fullName>
    <active>true</active>
    <label>Billing</label>
</RecordType>

unpackaged/main/default/objects/CS_Billing_Schedule_Item__c/CS_Billing_Schedule_Item__c.object-meta.xml
<CustomObject>
    <description>Individiual details for one billing period for one line within a Sales Order</description>
    <label>Billing Schedule Item</label>
    <nameField>
        <displayFormat>BILI-{00000000}</displayFormat>
        <label>Billing Schedule Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Billing Schedule Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/CS_Billing_Schedule_Item__c/fields/Bill_Run__c.field-meta.xml
<CustomField>
    <fullName>Bill_Run__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Bill Run</label>
    <referenceTo>Bill_Run__c</referenceTo>
    <relationshipLabel>Billing Schedule Items</relationshipLabel>
    <relationshipName>Billing_Schedule_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/CS_Billing_Schedule_Item__c/fields/Billing_Calendar__c.field-meta.xml
<CustomField>
    <fullName>Billing_Calendar__c</fullName>
    <description>Billing Calendar as defined in the Sales Order
- Standard
- Broadcast</description>
    <inlineHelpText>Billing Calendar as defined in the Sales Order
- Standard
- Broadcast</inlineHelpText>
    <label>Billing Calendar</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Standard</fullName>
            </value>
            <value>
                <fullName>Broadcast</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/CS_Billing_Schedule_Item__c/fields/Billing_Date__c.field-meta.xml
<CustomField>
    <fullName>Billing_Date__c</fullName>
    <description>Billing Date based on the Billing Rule + Billing Calendar.
-Monthly Standard  : Last day of each Standard Calendar Month from SO line item  Start to End of Campaign.
-Monthly Broadcast: Last day of each Broadcast Calendar Month from SO line item  Start to End of Campaign</description>
    <inlineHelpText>Billing Date based on the Billing Rule + Billing Calendar</inlineHelpText>
    <label>Billing Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/CS_Billing_Schedule_Item__c/fields/Sales_Order__c.field-meta.xml
<CustomField>
    <fullName>Sales_Order__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Link to the related Sales Order.</description>
    <inlineHelpText>Link to the related Sales Order.</inlineHelpText>
    <label>Sales Order</label>
    <referenceTo>csmso__Sales_Order__c</referenceTo>
    <relationshipLabel>Billing Schedule Item</relationshipLabel>
    <relationshipName>CS_Billing_Schedule_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/CS_Billing_Schedule_Item__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>Billing Schedule Status.</description>
    <inlineHelpText>Billing Schedule Status</inlineHelpText>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Open</fullName>
            </value>
            <value>
                <fullName>Locked</fullName>
            </value>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Ready</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
            <value>
                <fullName>Forecast</fullName>
            </value>
            <value>
                <fullName>Pending Closure</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/CS_Revenue_Schedule_Item__c/CS_Revenue_Schedule_Item__c.object-meta.xml
<CustomObject>
    <description>Individiual details for one billing period for one line within a Sales Order</description>
    <label>Revenue Schedule Item</label>
    <nameField>
        <displayFormat>REVI-{00000000}</displayFormat>
        <label>Revenue Recognition Schedule Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Revenue Schedule Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/CS_Revenue_Schedule_Item__c/fields/Bill_Run__c.field-meta.xml
<CustomField>
    <fullName>Bill_Run__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Bill Run</label>
    <referenceTo>Bill_Run__c</referenceTo>
    <relationshipLabel>Revenue Schedule Items</relationshipLabel>
    <relationshipName>Revenue_Schedule_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/CS_Revenue_Schedule_Item__c/fields/Rev_Rec_Calendar__c.field-meta.xml
<CustomField>
    <fullName>Rev_Rec_Calendar__c</fullName>
    <description>Rev Rec Calendar as defined in the Sales Order.</description>
    <inlineHelpText>Rev Rec Calendar as defined in the Sales Order.</inlineHelpText>
    <label>Rev Rec Calendar</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Standard</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/CS_Revenue_Schedule_Item__c/fields/Rev_Rec_Date__c.field-meta.xml
<CustomField>
    <fullName>Rev_Rec_Date__c</fullName>
    <description>Rev Rec Date based on the Rev Rec Rule +Rev Rec Calendar.
-Monthly Standard : Last day of each Standard Calendar Month from SO Line Item Start to End of Campaign</description>
    <inlineHelpText>Rev Rec Date based on the Rev Rec Rule +Rev Rec Calendar.
-Monthly Standard : Last day of each Standard Calendar Month from SO Line Item Start to End of Campaign</inlineHelpText>
    <label>Rev Rec Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/CS_Revenue_Schedule_Item__c/fields/Sales_Order__c.field-meta.xml
<CustomField>
    <fullName>Sales_Order__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Link to the related Sales Order.</description>
    <inlineHelpText>Link to the related Sales Order.</inlineHelpText>
    <label>Sales Order</label>
    <referenceTo>csmso__Sales_Order__c</referenceTo>
    <relationshipLabel>Revenue Schedule Item</relationshipLabel>
    <relationshipName>CS_Revenue_Schedule_Item</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/CS_Revenue_Schedule_Item__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>Rev Rec Schedule Status.</description>
    <inlineHelpText>Rev Rec Schedule Status.</inlineHelpText>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Open</fullName>
            </value>
            <value>
                <fullName>Locked</fullName>
            </value>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Ready</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
            <value>
                <fullName>Forecast</fullName>
            </value>
            <value>
                <fullName>Pending Closure</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/CS_Sales_Order_Schedule__c/CS_Sales_Order_Schedule__c.object-meta.xml
<CustomObject>
    <label>Sales Order Schedule</label>
    <nameField>
        <displayFormat>RS-{00000000}</displayFormat>
        <label>Sales Order Schedules Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sales Order Schedules</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/CS_Sales_Order_Schedule__c/fields/Billing_Calendar__c.field-meta.xml
<CustomField>
    <fullName>Billing_Calendar__c</fullName>
    <formula>TEXT(Sales_Order__r.Billing_Calendar__c)</formula>
    <label>Billing Calendar</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/CS_Sales_Order_Schedule__c/fields/Billing_Date__c.field-meta.xml
<CustomField>
    <fullName>Billing_Date__c</fullName>
    <label>Billing Date</label>
    <summarizedField>CS_Billing_Schedule__c.Next_Billing_Date__c</summarizedField>
    <summaryForeignKey>CS_Billing_Schedule__c.CS_Sales_Order_Schedule__c</summaryForeignKey>
    <summaryOperation>min</summaryOperation>
    <type>Summary</type>
</CustomField>

unpackaged/main/default/objects/CS_Sales_Order_Schedule__c/fields/Rev_Rec_Calendar__c.field-meta.xml
<CustomField>
    <fullName>Rev_Rec_Calendar__c</fullName>
    <formula>Sales_Order__r.Rev_Rec_Calendar__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Rev Rec Calendar</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/CS_Sales_Order_Schedule__c/fields/Rev_Rec_Date__c.field-meta.xml
<CustomField>
    <fullName>Rev_Rec_Date__c</fullName>
    <label>Rev Rec Date</label>
    <summarizedField>CS_Revenue_Schedule__c.Next_Rev_Rec_Date__c</summarizedField>
    <summaryForeignKey>CS_Revenue_Schedule__c.CS_Sales_Order_Schedule__c</summaryForeignKey>
    <summaryOperation>min</summaryOperation>
    <type>Summary</type>
</CustomField>

unpackaged/main/default/objects/CS_Sales_Order_Schedule__c/fields/Sales_Order__c.field-meta.xml
<CustomField>
    <fullName>Sales_Order__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Link to the related Sales Order</description>
    <inlineHelpText>Link to the related Sales Order</inlineHelpText>
    <label>Sales Order</label>
    <referenceTo>csmso__Sales_Order__c</referenceTo>
    <relationshipLabel>Sales Order Schedules</relationshipLabel>
    <relationshipName>Sales_Order_Schedules</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/classes/CS_BatchLockBillingSchedule.cls
/**
 * @name CS_BatchLockBillingSchedule
 * @description Class that handles Locking of Billing Schedule Items
 * @revision
 *
 */
public class CS_BatchLockBillingSchedule extends CS_SalesOrderScheduleBatch implements Schedulable {
	@TestVisible
	private static String INITIAL_QUERY_TEMPLATE = 'SELECT Id FROM csmso__Sales_Order__c WHERE Last_Date_Booked__c != null AND Id IN ' +
			   		   					   '(SELECT Sales_Order__c FROM CS_Sales_Order_Schedule__c WHERE ({0}))';
			   		   					   
	@TestVisible
	private Map<String, BillRun> calendarTypesMap {
		get {
			if(calendarTypesMap == null) {
				calendarTypesMap = new Map<String, BillRun>();
		
				for(Bill_Run__c billRun : this.billRuns) {
					BillRun br = new BillRun(billRun);
					if(!calendarTypesMap.containsKey(br.key)) {
						calendarTypesMap.put(br.Key, br);
					}
					
					if(calendarTypesMap.get(br.key).billingDate < billRun.Billing_Date__c) {
						calendarTypesMap.put(br.key, br);
					}	
				}
			}
			
			return calendarTypesMap;
		}
		set;
	}
	
	@TestVisible
	private List<Bill_Run__c> billRuns {
		get {
			if(billRuns == null) {
				billRuns = [SELECT Id, Name, Calendar_Type__c, Status__c, Billing_Date__c, RecordType.Name
							FROM Bill_Run__c
							WHERE Is_Lock_Billing_Date__c = true
							AND Status__c = :CS_const_BillRun.Status_Scheduled];
			}
			
			return billRuns;
		}
		set;
	}
	
	@TestVisible
	private Map<String, Map<Date, BillRun>> billRunsByDate {
		get {
			if(billRunsByDate == null) {
				billRunsByDate = new Map<String, Map<Date, BillRun>>();
		
				for(Bill_Run__c billRun : this.billRuns) {
					BillRun br = new BillRun(billRun);
					if(!billRunsByDate.containsKey(br.key)) {
						billRunsByDate.put(br.key, new Map<Date, BillRun>());
					}
					
					billRunsByDate.get(br.key).put(br.billingDate, br);
				}
			}
			
			return billRunsByDate;
		}
		set;		
	}
	
	public Map<String, ScheduleItemQuery> scheduleItemQueries = new Map<String, ScheduleItemQuery>{
		'CS_Billing_Schedule_Item__c' => new ScheduleItemQuery(
			'CS_Billing_Schedule_Item__c',
			'Billing_Calendar__c',
			'Billing',
			'SELECT Id, Name, Status__c, Billing_Calendar__c, Billing_Date__c FROM CS_Billing_Schedule_Item__c WHERE ({0}) AND Status__c = {1}',
			'(Billing_Calendar__c = {0} AND Billing_Date__c <= {1}) OR '
		),
		'CS_Revenue_Schedule_Item__c' => new ScheduleItemQuery(
			'CS_Revenue_Schedule_Item__c',
			'Rev_Rec_Calendar__c',
			'Revenue Recognition',
			'SELECT Id, Name, Status__c, Rev_Rec_Calendar__c, Rev_Rec_Date__c FROM CS_Revenue_Schedule_Item__c WHERE ({0}) AND Status__c = {1}',
			'(Rev_Rec_Calendar__c = {0} AND Rev_Rec_Date__c <= {1}) OR '
		)
	};
	
	/**
	 * Class constructor
	 * @return CS_BatchLockBillingSchedule
	 */
	public CS_BatchLockBillingSchedule() {
		super('CS_BatchLockBillingSchedule', 1);
	}

	/**
	 * Method that locks Billing Schedule Items
	 * @param  salesOrders List<SObject>
	 */
	public override void doWork(List<SObject> salesOrders) {
		if(!salesOrders.isEmpty()) {
			Map<Id, SObject> salesOrdersToProcess = new Map<Id, SObject>(salesOrders);
			for(ScheduleItemQuery itemQuery : this.scheduleItemQueries.values()) {		
				try {
					String itemQueryString = getQueryString(itemQuery.queryString, itemQuery.billRunType);
					if(String.isNotBlank(itemQueryString)) {
						itemQueryString +=  + ' AND Sales_Order__c IN (\'' + CS_utl_Array.join((List<String>) new List<Id>(salesOrdersToProcess.keySet()), '\',\'') + '\')';
						List<SObject> scheduleItems = Database.query(
							itemQueryString
						);
						
						for(SObject scheduleItem : scheduleItems) {
							Date calendarTypeDate = calendarTypesMap.get(String.valueOf(scheduleItem.get(itemQuery.calendarField)) + String.valueOf(itemQuery.billRunType)).billingDate;
							scheduleItem.put('Status__c', CS_const_SalesOrder.ScheduleStatus_Locked);
							scheduleItem.put('Bill_Run__c', billRunsByDate.get(String.valueOf(scheduleItem.get(itemQuery.calendarField)) + String.valueOf(itemQuery.billRunType)).get(calendarTypeDate).billRun.Id);
						}
					
						update scheduleItems;
					}
				}
				catch (Exception e) {
					for(Id salesOrderId : salesOrdersToProcess.keySet()) {
						log.addMessage(e, salesOrderId);
					}
					
					this.success = false;
				}
			}
		}
	}
	
	@TestVisible
	protected override Database.QueryLocator onStart() {
		this.queryString = getQueryString(INITIAL_QUERY_TEMPLATE, null);
		
		return super.onStart();
	}
	
	@TestVisible
	protected override void onFinish() {
		for(Bill_Run__c billRun : billRuns) {
			billRun.Status__c = CS_const_BillRun.Status_LockingBillSchedules;
		}
		
		update billRuns;
		
		super.onFinish();
	}
	
	@TestVisible
	private String getQueryString(String template, String billRunType) {
		String calendarQuery = '';
		for(BillRun billRun : calendarTypesMap.values()) {
			if(String.isBlank(billRunType) || billRun.recordType == billRunType) {
				calendarQuery += '(' + billRun.queryString + ') OR ';
			}
		}
		
		if(String.isNotBlank(calendarQuery)) {
			return String.format(template, new List<String>{calendarQuery.substring(0, calendarQuery.length() - ' OR '.length()), escapeString(CS_const_SalesOrder.ScheduleStatus_Open)});
		}

		return String.isBlank(billRunType) ? this.queryString : null;
	}
}