unpackaged/main/default/objects/Bill_Run__c/Bill_Run__c.object-meta.xml
<CustomObject>
    <description>Bill Run object is used to schedule Billing Date. With that he is also setting Lock and Auto-Reconciliation Date. Also contains Calendar Type and Status fields.</description>
    <label>Bill Run</label>
    <nameField>
        <displayFormat>BR-{00000000}</displayFormat>
        <label>Bill Run No</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Bill Runs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Bill_Run__c/fields/Billing_Date__c.field-meta.xml
<CustomField>
    <fullName>Billing_Date__c</fullName>
    <description>Set the Billing Date or the Revenue Period End Date of Bill Run.</description>
    <inlineHelpText>Set the Billing Date or the Revenue Period End Date of Bill Run.</inlineHelpText>
    <label>Billing / Revenue Date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/Bill_Run__c/fields/Calendar_Type__c.field-meta.xml
<CustomField>
    <fullName>Calendar_Type__c</fullName>
    <description>Calendar Type - can be Standard or Broadcast.</description>
    <inlineHelpText>Calendar Type - can be Standard or Broadcast.</inlineHelpText>
    <label>Calendar Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Standard</fullName>
                <default>true</default>
                <label>Standard</label>
            </value>
            <value>
                <fullName>Broadcast</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Bill_Run__c/recordTypes/Billing.recordType-meta.xml
<RecordType>
    <fullName>Billing</fullName>
    <active>true</active>
    <label>Billing</label>
</RecordType>

unpackaged/main/default/objects/Sales_Order_Schedule_Batch__mdt/Sales_Order_Schedule_Batch__mdt.object-meta.xml
<CustomObject>
    <label>Sales Order Schedule Batch</label>
    <pluralLabel>Sales Order Schedule Batches</pluralLabel>
</CustomObject>

unpackaged/main/default/classes/CS_SalesOrderScheduleBatch.cls
/**
 * @name CS_SalesOrderScheduleBatch
 * @description Class that handles Sales Order Schedule updates
 * @revision
 *
 */
public abstract class CS_SalesOrderScheduleBatch extends CS_BatchWorker {
	@TestVisible
	protected CS_DMLWorker dml;
	
	@TestVisible
	private List<Sales_Order_Schedule_Batch__mdt> salesOrderScheduleBatches {
		get {
			if(salesOrderScheduleBatches == null) {
				salesOrderScheduleBatches = [SELECT Id, DeveloperName, Order__c
											FROM Sales_Order_Schedule_Batch__mdt
											ORDER BY Order__c ASC];
			}
			
			return salesOrderScheduleBatches;
		}
		set;
	}
	
	/**
	 * Class constructor
	 * @return CS_BillingScheduleBatch
	 */
	public CS_SalesOrderScheduleBatch(String processName) {
		this(processName, null);
	}
	
	/**
	 * Class constructor
	 * @return CS_BillingScheduleBatch
	 */
	public CS_SalesOrderScheduleBatch(String processName, Integer batchSize) {
		super(processName, batchSize);
		init(processName, batchSize);
	}
	
	public virtual override void init(String processName, Integer batchSize) {
		super.init(processName, batchSize);
		dml = new CS_DMLWorker();
	}
	
	/**
     * Method execute on finish of the batch
     * @return Database.QueryLocator
     */	
	@TestVisible
	protected virtual override void onFinish() {
		this.recordCount = dml.recordCount;
		startNextBatch(getNextBatchName());
	}

	/**
     * Method that gets the next batch name in chain
     * @return String
     */		
	@TestVisible
	private String getNextBatchName() {
		for(Integer i = 0; i < salesOrderScheduleBatches.size(); i++) {
			Sales_Order_Schedule_Batch__mdt sosb = salesOrderScheduleBatches.get(i);
			if(sosb.DeveloperName.equalsIgnoreCase(this.processName) && (i + 1 < salesOrderScheduleBatches.size())) {
				return salesOrderScheduleBatches.get(i + 1).DeveloperName;
			}
		}
		
		return null;
	}

	/**
     * Method that starts the next batch
     */		
	@TestVisible
	private Boolean startNextBatch(String batchName) {
		if(String.isNotBlank(batchName)) {
			Type t = Type.forName(batchName);
			CS_SalesOrderScheduleBatch batch = (CS_SalesOrderScheduleBatch) t.newInstance();
			batch.execute();
			return true;
		}
		
		return false;
	}

	/**
     * Method that escapes a string for query
     */		
	@TestVisible
	protected String escapeString(String value) {
		return '\'' + value + '\'';
	}
	
	public class BillRun {
		public String calendarType {get; set;}
		public String key {get; set;}
		public String recordType {get; set;}
		public Date billingDate {get; set;}
		public String queryString {get; set;}
		public Bill_Run__c billRun {get; set;}
		
		public BillRun(Bill_Run__c billRun) {
			this.calendarType = billRun.Calendar_Type__c;
			this.recordType = billRun.RecordType.Name;
			this.key = billRun.Calendar_Type__c + billRun.RecordType.Name;
			this.billingDate = billRun.Billing_Date__c;
			this.billRun = billRun;
			this.queryString = this.recordType == 'Billing' ? String.format('(Billing_Calendar__c = {0} AND Billing_Date__c <= {1})', new List<String>{escapeString(this.calendarType), String.valueOf(this.billingDate)}) : 
															  String.format('(Rev_Rec_Calendar__c = {0} AND Rev_Rec_Date__c <= {1})', new List<String>{escapeString(this.calendarType), String.valueOf(this.billingDate)});
		}
		
		/**
	     * Method that escapes a string for query
	     */		
		@TestVisible
		private String escapeString(String value) {
			return '\'' + value + '\'';
		}	
	}
	
	public class ScheduleItemQuery {
		public String scheduleType {get; set;}
		public String calendarField {get; set;}
		public String billRunType {get; set;}
		public String queryString {get; set;}
		public String whereClause {get; set;}
		
		public ScheduleItemQuery(String scheduleType, String calendarField, String billRunType, String queryString, String whereClause) {
			this.scheduleType = scheduleType;
			this.calendarField = calendarField;
			this.billRunType = billRunType;
			this.queryString = queryString;
			this.whereClause = whereClause;
		}
	}
}