unpackaged/main/default/objects/Bill_Run__c/Bill_Run__c.object-meta.xml
<CustomObject>
    <description>Bill Run object is used to schedule Billing Date. With that he is also setting Lock and Auto-Reconciliation Date. Also contains Calendar Type and Status fields.</description>
    <label>Bill Run</label>
    <nameField>
        <displayFormat>BR-{00000000}</displayFormat>
        <label>Bill Run No</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Bill Runs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Bill_Run__c/fields/Billing_Date__c.field-meta.xml
<CustomField>
    <fullName>Billing_Date__c</fullName>
    <description>Set the Billing Date or the Revenue Period End Date of Bill Run.</description>
    <inlineHelpText>Set the Billing Date or the Revenue Period End Date of Bill Run.</inlineHelpText>
    <label>Billing / Revenue Date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/Bill_Run__c/fields/Calendar_Type__c.field-meta.xml
<CustomField>
    <fullName>Calendar_Type__c</fullName>
    <description>Calendar Type - can be Standard or Broadcast.</description>
    <inlineHelpText>Calendar Type - can be Standard or Broadcast.</inlineHelpText>
    <label>Calendar Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Standard</fullName>
                <default>true</default>
                <label>Standard</label>
            </value>
            <value>
                <fullName>Broadcast</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Bill_Run__c/fields/Lock_Billing_Date__c.field-meta.xml
<CustomField>
    <fullName>Lock_Billing_Date__c</fullName>
    <description>Date when Billing Schedule / Revenue Schedule Locking will occur.</description>
    <formula>Auto_Reconciliation_Date__c - 1</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>Date when Billing Schedule / Revenue Schedule Locking will occur.</inlineHelpText>
    <label>Locking Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/Bill_Run__c/fields/SObject_Type__c.field-meta.xml
<CustomField>
    <fullName>SObject_Type__c</fullName>
    <formula>IF(RecordType.Name == &#39;Billing&#39;, &#39;CS_Billing_Schedule_Item__c&#39;, &#39;CS_Revenue_Schedule_Item__c&#39;)</formula>
    <label>SObject Type</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Bill_Run__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>Status of the Bill Run.</description>
    <inlineHelpText>Status of the Bill Run.</inlineHelpText>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Scheduled</fullName>
                <default>true</default>
                <label>Scheduled</label>
            </value>
            <value>
                <fullName>Locking Bill Schedules</fullName>
            </value>
            <value>
                <fullName>Auto-Reconciliating</fullName>
            </value>
            <value>
                <fullName>Complete</fullName>
            </value>
            <value>
                <fullName>Consolidating Actuals</fullName>
                <isActive>false</isActive>
                <label>Consolidating Actuals</label>
            </value>
            <value>
                <fullName>Recalculating Billing Schedules</fullName>
                <isActive>false</isActive>
                <label>Recalculating Billing Schedules</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Bill_Run__c/recordTypes/Billing.recordType-meta.xml
<RecordType>
    <fullName>Billing</fullName>
    <active>true</active>
    <label>Billing</label>
</RecordType>

unpackaged/main/default/objects/CS_Billing_Schedule__c/CS_Billing_Schedule__c.object-meta.xml
<CustomObject>
    <label>Billing Schedule</label>
    <nameField>
        <displayFormat>BIL-{00000000}</displayFormat>
        <label>Billing Schedule Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Billing Schedule</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/CS_Billing_Schedule__c/fields/Product_Configuration__c.field-meta.xml
<CustomField>
    <fullName>Product_Configuration__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Link to Product Configuration</description>
    <inlineHelpText>Link to Product Configuration</inlineHelpText>
    <label>Product Configuration</label>
    <referenceTo>cscfga__Product_Configuration__c</referenceTo>
    <relationshipName>Billing_Schedule_Headers</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/CS_Billing_Schedule__c/fields/Sales_Order__c.field-meta.xml
<CustomField>
    <fullName>Sales_Order__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Link to the related Sales Order</description>
    <inlineHelpText>Link to the related Sales Order</inlineHelpText>
    <label>Sales Order</label>
    <referenceTo>csmso__Sales_Order__c</referenceTo>
    <relationshipName>Billing_Schedule_Headers</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/CS_Billing_Schedule_Item__c/CS_Billing_Schedule_Item__c.object-meta.xml
<CustomObject>
    <description>Individiual details for one billing period for one line within a Sales Order</description>
    <label>Billing Schedule Item</label>
    <nameField>
        <displayFormat>BILI-{00000000}</displayFormat>
        <label>Billing Schedule Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Billing Schedule Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/CS_Billing_Schedule_Item__c/fields/Bill_Run__c.field-meta.xml
<CustomField>
    <fullName>Bill_Run__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Bill Run</label>
    <referenceTo>Bill_Run__c</referenceTo>
    <relationshipLabel>Billing Schedule Items</relationshipLabel>
    <relationshipName>Billing_Schedule_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/CS_Billing_Schedule_Item__c/fields/Billing_Date__c.field-meta.xml
<CustomField>
    <fullName>Billing_Date__c</fullName>
    <description>Billing Date based on the Billing Rule + Billing Calendar.
-Monthly Standard  : Last day of each Standard Calendar Month from SO line item  Start to End of Campaign.
-Monthly Broadcast: Last day of each Broadcast Calendar Month from SO line item  Start to End of Campaign</description>
    <inlineHelpText>Billing Date based on the Billing Rule + Billing Calendar</inlineHelpText>
    <label>Billing Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/CS_Billing_Schedule_Item__c/fields/Product_Configuration__c.field-meta.xml
<CustomField>
    <fullName>Product_Configuration__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Link to the related Product Configuration (Sales Order Line)</description>
    <inlineHelpText>Link to the related Product Configuration (Sales Order Line)</inlineHelpText>
    <label>Product Configuration</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>cscfga__Product_Configuration__c.Sales_Order__c</field>
            <operation>equals</operation>
            <valueField>$Source.Sales_Order__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>cscfga__Product_Configuration__c</referenceTo>
    <relationshipLabel>Billing Schedule Item</relationshipLabel>
    <relationshipName>Billing_Schedule_Item</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/CS_Billing_Schedule_Item__c/fields/Sales_Order__c.field-meta.xml
<CustomField>
    <fullName>Sales_Order__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Link to the related Sales Order.</description>
    <inlineHelpText>Link to the related Sales Order.</inlineHelpText>
    <label>Sales Order</label>
    <referenceTo>csmso__Sales_Order__c</referenceTo>
    <relationshipLabel>Billing Schedule Item</relationshipLabel>
    <relationshipName>CS_Billing_Schedule_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/CS_Billing_Schedule_Item__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>Billing Schedule Status.</description>
    <inlineHelpText>Billing Schedule Status</inlineHelpText>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Open</fullName>
            </value>
            <value>
                <fullName>Locked</fullName>
            </value>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Ready</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
            <value>
                <fullName>Forecast</fullName>
            </value>
            <value>
                <fullName>Pending Closure</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/CS_Revenue_Schedule__c/CS_Revenue_Schedule__c.object-meta.xml
<CustomObject>
    <description>Header record for Revenue Recognition line items at Product Configuration level</description>
    <label>Revenue Schedule</label>
    <nameField>
        <displayFormat>REV-{00000000}</displayFormat>
        <label>Revenue Schedule Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Revenue Schedule</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/CS_Revenue_Schedule__c/fields/Product_Configuration__c.field-meta.xml
<CustomField>
    <fullName>Product_Configuration__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Link to Product Configuration</description>
    <inlineHelpText>Link to Product Configuration</inlineHelpText>
    <label>Product Configuration</label>
    <referenceTo>cscfga__Product_Configuration__c</referenceTo>
    <relationshipName>Revenue_Schedule_Headers</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/CS_Revenue_Schedule__c/fields/Sales_Order__c.field-meta.xml
<CustomField>
    <fullName>Sales_Order__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Link to the related Sales Order</description>
    <inlineHelpText>Link to the related Sales Order</inlineHelpText>
    <label>Sales Order</label>
    <referenceTo>csmso__Sales_Order__c</referenceTo>
    <relationshipName>Revenue_Schedule_Headers</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/CS_Revenue_Schedule_Item__c/CS_Revenue_Schedule_Item__c.object-meta.xml
<CustomObject>
    <description>Individiual details for one billing period for one line within a Sales Order</description>
    <label>Revenue Schedule Item</label>
    <nameField>
        <displayFormat>REVI-{00000000}</displayFormat>
        <label>Revenue Recognition Schedule Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Revenue Schedule Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/CS_Revenue_Schedule_Item__c/fields/Bill_Run__c.field-meta.xml
<CustomField>
    <fullName>Bill_Run__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Bill Run</label>
    <referenceTo>Bill_Run__c</referenceTo>
    <relationshipLabel>Revenue Schedule Items</relationshipLabel>
    <relationshipName>Revenue_Schedule_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/CS_Revenue_Schedule_Item__c/fields/Product_Configuration__c.field-meta.xml
<CustomField>
    <fullName>Product_Configuration__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Link to the related Product Configuration (Sales Order Line)</description>
    <inlineHelpText>Link to the related Product Configuration (Sales Order Line)</inlineHelpText>
    <label>Product Configuration</label>
    <referenceTo>cscfga__Product_Configuration__c</referenceTo>
    <relationshipLabel>Revenue Schedule Item</relationshipLabel>
    <relationshipName>Revenue_Schedule_Item</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/CS_Revenue_Schedule_Item__c/fields/Sales_Order__c.field-meta.xml
<CustomField>
    <fullName>Sales_Order__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Link to the related Sales Order.</description>
    <inlineHelpText>Link to the related Sales Order.</inlineHelpText>
    <label>Sales Order</label>
    <referenceTo>csmso__Sales_Order__c</referenceTo>
    <relationshipLabel>Revenue Schedule Item</relationshipLabel>
    <relationshipName>CS_Revenue_Schedule_Item</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/CS_Revenue_Schedule_Item__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>Rev Rec Schedule Status.</description>
    <inlineHelpText>Rev Rec Schedule Status.</inlineHelpText>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Open</fullName>
            </value>
            <value>
                <fullName>Locked</fullName>
            </value>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Ready</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
            <value>
                <fullName>Forecast</fullName>
            </value>
            <value>
                <fullName>Pending Closure</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/CS_Sales_Order_Schedule__c/CS_Sales_Order_Schedule__c.object-meta.xml
<CustomObject>
    <label>Sales Order Schedule</label>
    <nameField>
        <displayFormat>RS-{00000000}</displayFormat>
        <label>Sales Order Schedules Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sales Order Schedules</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/CS_Sales_Order_Schedule__c/fields/Billing_Date__c.field-meta.xml
<CustomField>
    <fullName>Billing_Date__c</fullName>
    <label>Billing Date</label>
    <summarizedField>CS_Billing_Schedule__c.Next_Billing_Date__c</summarizedField>
    <summaryForeignKey>CS_Billing_Schedule__c.CS_Sales_Order_Schedule__c</summaryForeignKey>
    <summaryOperation>min</summaryOperation>
    <type>Summary</type>
</CustomField>

unpackaged/main/default/objects/CS_Sales_Order_Schedule__c/fields/Sales_Order__c.field-meta.xml
<CustomField>
    <fullName>Sales_Order__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Link to the related Sales Order</description>
    <inlineHelpText>Link to the related Sales Order</inlineHelpText>
    <label>Sales Order</label>
    <referenceTo>csmso__Sales_Order__c</referenceTo>
    <relationshipLabel>Sales Order Schedules</relationshipLabel>
    <relationshipName>Sales_Order_Schedules</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/classes/CS_utl_Schedule.cls
/**
 * @name CS_utl_Schedule
 * @description Utility class for Schedules
 * @revision
 *
 */
public class CS_utl_Schedule {
	/**
	 * Property to get and cache Active Bill Runs
	 */
	@TestVisible
	public static List<Bill_Run__c> billRuns {
		get {
			if(billRuns == null) {
				billRuns = [SELECT Id, Name, Billing_Date__c, Calendar_Type__c, Status__c, RecordType.Name, SObject_Type__c
							FROM Bill_Run__c
							WHERE Lock_Billing_Date__c >= TODAY AND Billing_Date__c <= TODAY];
			}
			
			return billRuns;
		}
		set;
	}

	public static Boolean isApplicable(Bill_Run__c billRun, String scheduleObject, cscfga__Product_Configuration__c config) {
		return billRun.SObject_Type__c == scheduleObject &&
			(billRun.SObject_Type__c == 'CS_Revenue_Schedule_Item__c' ||
			(billRun.SObject_Type__c == 'CS_Billing_Schedule_Item__c' && billRun.Calendar_Type__c == config.Sales_Order__r.Billing_Calendar__c));
	}
	
	/**
	 * Checks if Schedule can be deleted
	 * @param schedule SObject
	 * @return    	   Boolean
	 */
	@TestVisible
	public static Boolean isDeletable(SObject schedule) {
		Map<String, Object> fieldValues = schedule.getPopulatedFieldsAsMap();
		return String.isNotBlank(schedule.Id) 
               && (fieldValues.get('Is_Closed__c') == null 
                   || !((Boolean) fieldValues.get('Is_Closed__c')))
               && fieldValues.get('Status__c') != CS_const_SalesOrder.ScheduleStatus_Cancelled;
	}
	
	/**
	 * Checks if Schedule is billed
	 * @param schedule SObject
	 * @return    	   Boolean
	 */
	@TestVisible
	public static Boolean isBilled(SObject schedule) {
		Map<String, Object> fieldValues = schedule.getPopulatedFieldsAsMap();
		return String.isNotBlank(schedule.Id) && (fieldValues.get('Status__c') == CS_const_SalesOrder.ScheduleStatus_PendingClosure ||
				fieldValues.get('Status__c') == CS_const_SalesOrder.ScheduleStatus_Closed);
	}
	
	public static Boolean isAutoReconciled(SObject schedule) {
		Map<String, Object> fieldValues = schedule.getPopulatedFieldsAsMap();
		return isBilled(schedule) || fieldValues.get('Status__c') == CS_const_SalesOrder.ScheduleStatus_Ready || fieldValues.get('Status__c') == CS_const_SalesOrder.ScheduleStatus_Pending;
	}
	
	/**
	 * Create a Sales Order Schedule
	 * @param salesOrderId Id
	 * @return    		   CS_Sales_Order_Schedule__c
	 */
	@TestVisible
	public static CS_Sales_Order_Schedule__c createSalesOrderSchedule(Id salesOrderId) {
		return new CS_Sales_Order_Schedule__c(Sales_Order__c = salesOrderId);
	}
	
	/**
	 * Create a Billing Schedule
	 * @param salesOrderId 		   Id
	 * @param salesOrderSchedule   CS_Sales_Order_Schedule__c
	 * @param productConfiguration cscfga__Product_Configuration__c
	 * @return    		 		   CS_Billing_Schedule__c
	 */
	@TestVisible
	public static CS_Billing_Schedule__c createBillingSchedule(Id salesOrderId, CS_Sales_Order_Schedule__c salesOrderSchedule, cscfga__Product_Configuration__c productConfiguration) {
		return new CS_Billing_Schedule__c(Sales_Order__c = salesOrderId,
										  CS_Sales_Order_Schedule__c = salesOrderSchedule.Id,
										  CS_Sales_Order_Schedule__r = salesOrderSchedule,
										  Product_Configuration__c = productConfiguration.Id,
										  Product_Configuration__r = productConfiguration);
	}
	
	/**
	 * Create a Revenue Schedule
	 * @param salesOrderId 		   Id
	 * @param salesOrderSchedule   CS_Sales_Order_Schedule__c
	 * @param productConfiguration cscfga__Product_Configuration__c
	 * @return    		 		   CS_Revenue_Schedule__c
	 */
	@TestVisible
	public static CS_Revenue_Schedule__c createRevenueSchedule(Id salesOrderId, CS_Sales_Order_Schedule__c salesOrderSchedule, cscfga__Product_Configuration__c productConfiguration) {
		return new CS_Revenue_Schedule__c(Sales_Order__c = salesOrderId,
										  CS_Sales_Order_Schedule__c = salesOrderSchedule.Id,
										  CS_Sales_Order_Schedule__r = salesOrderSchedule,
										  Product_Configuration__c = productConfiguration.Id,
										  Product_Configuration__r = productConfiguration);
	}
}