unpackaged/main/default/objects/OCR_Campaign_Contact_Bypass__c/OCR_Campaign_Contact_Bypass__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>OCR Campaign Contact Bypass</label>
</CustomObject>

unpackaged/main/default/objects/OCR_Campaign_Contact_Bypass__c/fields/OpportunityID__c.field-meta.xml
<CustomField>
    <fullName>OpportunityID__c</fullName>
    <label>OpportunityID</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Order_Type__c.field-meta.xml
<CustomField>
    <fullName>Order_Type__c</fullName>
    <description>Indicates the type of the Order which is used for pricing and for grouping orders</description>
    <inlineHelpText>Indicates the type of the Order which is used for pricing and for grouping orders</inlineHelpText>
    <label>Media Order Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Direct Commercial</fullName>
                <default>true</default>
                <label>Direct Commercial</label>
            </value>
            <value>
                <fullName>House Guaranteed</fullName>
            </value>
            <value>
                <fullName>House Non-Guaranteed</fullName>
            </value>
            <value>
                <fullName>Labels AdCredit</fullName>
            </value>
            <value>
                <fullName>Labels Commercial</fullName>
            </value>
            <value>
                <fullName>Reseller</fullName>
            </value>
            <value>
                <fullName>Programmatic Guaranteed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/classes/OCRCampaignCOntactByPass_CC_test.cls
@isTest
public class OCRCampaignCOntactByPass_CC_test {
    /*static testmethod void test()
{
Opportunity opp = new opportunity();
opp.Name = 'Test Opp';
opp.StageName = 'Proposal';
opp.CloseDate = system.today().AddDays(30);
opp.Order_Type__c = 'Contract - Renewal';
insert opp;
OCR_Campaign_Contact_Bypass__c cs = new OCR_Campaign_Contact_Bypass__c();
cs.Name = 'test';
cs.OpportunityID__c ='122726252';
string recordid ='test123';
test.startTest();
//   BypassOCRrestriction.getHiearchySettings(recordid);
test.stopTest();
}*/
    static testmethod void test2()
    {
        Account acc = TestDataSetupSO.createB2BAcc();
        insert acc;
        Opportunity opp = new opportunity();
        opp.Name = 'Test Opp';
        opp.StageName = 'prospecting';
        opp.AccountId = acc.Id;
        opp.CloseDate = system.today().AddDays(30);
        opp.Order_Type__c = 'Contract - Renewal';
        insert opp;
        
        
        OCR_Campaign_Contact_Bypass__c cs = new OCR_Campaign_Contact_Bypass__c();
        cs.Name = 'test';
        
        
        string recordid ='test123';
        test.startTest();
        try {
            OCRCampaignCOntactByPass_CC.checkValidations(recordid);
        } catch(Exception ex) {}
        test.stopTest();
        
        
    }
    static testmethod void test3()
    {
        Account acc = TestDataSetupSO.createB2BAcc();
        insert acc;
        Opportunity opp = new opportunity();
        opp.Name = 'Test Opp';
        opp.StageName = 'prospecting';
        opp.AccountId = acc.Id;
        opp.CloseDate = system.today().AddDays(30);
        opp.Order_Type__c = 'Contract - Renewal';
        insert opp;
        
        
        OCR_Campaign_Contact_Bypass__c cs = new OCR_Campaign_Contact_Bypass__c();
        cs.Name = 'test';
        
        Profile p = [SELECT Id FROM Profile WHERE Name='System Administrator']; 
        User u = new User(Alias = 'standt', Email='systemAdminPropertyGuru@test1org.com', 
                          EmailEncodingKey='UTF-8', LastName='Testing', LanguageLocaleKey='en_US', 
                          LocaleSidKey='en_US', ProfileId = p.Id, 
                          TimeZoneSidKey='America/Los_Angeles', UserName='systemAdminPropertyGuru@test1org.com');
        
        System.runAs(u) {
            string recordid ='test123';
            test.startTest();
            try {
                OCRCampaignCOntactByPass_CC.checkValidations(recordid);
            } catch(Exception ex) {}
            test.stopTest();
        }
        
    }
    
}