unpackaged/main/default/objects/Product_Class__c/Product_Class__c.object-meta.xml
<CustomObject>
    <label>Product Class</label>
    <nameField>
        <label>Class Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Product Classes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Product_Master_Table__c/Product_Master_Table__c.object-meta.xml
<CustomObject>
    <label>Product Master Table</label>
    <nameField>
        <displayFormat>PMT-{0000000}</displayFormat>
        <label>Product Master Table Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Product Master Tables</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Product_Master_Table__c/fields/Actual_Record_Id__c.field-meta.xml
<CustomField>
    <fullName>Actual_Record_Id__c</fullName>
    <label>Actual Record Id</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Product_Master_Table__c/fields/Bundle_Only__c.field-meta.xml
<CustomField>
    <fullName>Bundle_Only__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Bundle Only</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Product_Master_Table__c/fields/Deferred_Account_Code__c.field-meta.xml
<CustomField>
    <fullName>Deferred_Account_Code__c</fullName>
    <label>Deferred Account Code</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Product_Master_Table__c/fields/Duration__c.field-meta.xml
<CustomField>
    <fullName>Duration__c</fullName>
    <label>Duration</label>
    <precision>4</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/Product_Master_Table__c/fields/Duration_Term__c.field-meta.xml
<CustomField>
    <fullName>Duration_Term__c</fullName>
    <label>Duration Term</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Product_Master_Table__c/fields/Effective_end_date__c.field-meta.xml
<CustomField>
    <fullName>Effective_end_date__c</fullName>
    <label>Effective end date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/Product_Master_Table__c/fields/Effective_start_date__c.field-meta.xml
<CustomField>
    <fullName>Effective_start_date__c</fullName>
    <label>Effective start date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/Product_Master_Table__c/fields/Income_Account_Code__c.field-meta.xml
<CustomField>
    <fullName>Income_Account_Code__c</fullName>
    <label>Income Account Code</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Product_Master_Table__c/fields/Product_Catagory__c.field-meta.xml
<CustomField>
    <fullName>Product_Catagory__c</fullName>
    <label>Product Catagory</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Product_Master_Table__c/fields/Product_Class__c.field-meta.xml
<CustomField>
    <fullName>Product_Class__c</fullName>
    <label>Product Class</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Product_Master_Table__c/fields/Product_Definition_Name__c.field-meta.xml
<CustomField>
    <fullName>Product_Definition_Name__c</fullName>
    <label>Product Definition Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Product_Master_Table__c/fields/Product_List_Price__c.field-meta.xml
<CustomField>
    <fullName>Product_List_Price__c</fullName>
    <label>Product List Price</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/Product_Master_Table__c/fields/Product_Stored_In__c.field-meta.xml
<CustomField>
    <fullName>Product_Stored_In__c</fullName>
    <description>Field to display Product stored in which object</description>
    <label>Product Stored In</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Product_Master_Table__c/fields/Product_Subclass__c.field-meta.xml
<CustomField>
    <fullName>Product_Subclass__c</fullName>
    <label>Product Subclass</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Product_Master_Table__c/fields/Rev_Accrual_GL_Code__c.field-meta.xml
<CustomField>
    <fullName>Rev_Accrual_GL_Code__c</fullName>
    <label>Rev Accrual GL Code</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Product_Master_Table__c/fields/SKU_Number__c.field-meta.xml
<CustomField>
    <fullName>SKU_Number__c</fullName>
    <label>SKU Number</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Product_Master_Table__c/fields/SOV__c.field-meta.xml
<CustomField>
    <fullName>SOV__c</fullName>
    <label>SOV</label>
    <precision>5</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/Product_Master_Table__c/fields/Starting_Day__c.field-meta.xml
<CustomField>
    <fullName>Starting_Day__c</fullName>
    <label>Starting Day</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Product_Master_Table__c/fields/Tax_Code__c.field-meta.xml
<CustomField>
    <fullName>Tax_Code__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Tax Code</label>
    <referenceTo>Tax_Code__c</referenceTo>
    <relationshipName>B2B_Product_Master_Tables</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Tax_Code__c/Tax_Code__c.object-meta.xml
<CustomObject>
    <description>This is custom object to store all tax codes and rates.</description>
    <label>Tax Code</label>
    <nameField>
        <label>Tax Code</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Tax Codes</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Tax_Code__c/fields/Active__c.field-meta.xml
<CustomField>
    <fullName>Active__c</fullName>
    <defaultValue>true</defaultValue>
    <description>Field to indicate whether Tax Code is Active or Inactive in SF</description>
    <inlineHelpText>Field to indicate whether Tax Code is Active or Inactive in SF</inlineHelpText>
    <label>Active</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Tax_Code__c/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <description>Denotes description for the tax code</description>
    <inlineHelpText>Denotes description for the tax code</inlineHelpText>
    <label>Description</label>
    <type>TextArea</type>
</CustomField>

unpackaged/main/default/classes/BatchUpsertNAAprodsToMasterTable.cls
global class BatchUpsertNAAprodsToMasterTable implements Database.Batchable<sObject>, Schedulable{
    
    public void execute(SchedulableContext sc){  
        DataBase.executeBatch(new BatchUpsertNAAprodsToMasterTable());  
    }
    
    global Database.QueryLocator start( Database.BatchableContext BC ) {
        String thisday = String.valueOf(DateTime.now()).replace(' ', 'T');
        String beforeday = String.valueOf(DateTime.now().adddays(Integer.valueOf(Label.Fetch_Records_of_Days))).replace(' ', 'T');
        thisday = thisday + 'Z';
        beforeday = beforeday + 'Z';
        String query = Label.Fetch_NAA_Products_Query;
        query = query.replace('DateFrom', beforeday);
        query = query.replace('today', thisday);
        
        System.debug('query** '+query);
        
        return Database.getQueryLocator(query);
    }
    global void execute(Database.BatchableContext BC, List<csmso__Node_Advert_Assignment__c>scope){
        
        List<Product_Master_Table__c> masterRecordsList = new List<Product_Master_Table__c>();
        Map<String, csmso__Rate_Card_Item_Price__c> naaToRateCardItemMap = new Map<String, csmso__Rate_Card_Item_Price__c>();
        Set<Id> naaIds = new Set<Id>();
        if(!scope.isEmpty()){
            for(csmso__Node_Advert_Assignment__c naa : scope){
                naaIds.add(naa.Id);
            }
        }
            
        List<csmso__Rate_Card_Item_Price__c> RateCardItemList = [Select Id, Name, csmso__Price_Per_Unit__c, Income_Account__c, Deferred_Revenue_Account__c, csmso__Rate_Card__r.csmso__From_Date__c,
                                                                 Tax_Code__c, Product_Category__c, Product_Class__c, Product_Subclass__c, csmso__Advert_Assignment__c, csmso__Rate_Card__r.csmso__To_Date__c
                                                                 from csmso__Rate_Card_Item_Price__c where csmso__Advert_Assignment__c =: naaIds];
        System.debug('RateCardItemList*** '+RateCardItemList);
        If(!RateCardItemList.isEmpty()){
            for(csmso__Rate_Card_Item_Price__c rcItem : RateCardItemList){
                naaToRateCardItemMap.put(rcItem.csmso__Advert_Assignment__c, rcItem);
            }
        }
        
        Map<String, Product_Master_Table__c> ActualRecToPmRecMap = new Map<String, Product_Master_Table__c>();
        for(Product_Master_Table__c pmt : [Select id, Name, Actual_Record_Id__c, Product_Name__c, Active__c, Bundle_Only__c,
                                               SKU_Number__c, Income_Account_Code__c, Deferred_Account_Code__c, Tax_Code__c,
                                               Product_Class__c, Effective_start_date__c, Product_Stored_In__c, Product_Definition_Name__c,
                                               Effective_end_date__c, Product_List_Price__c, Product_Subclass__c, Product_Catagory__c
                                               from Product_Master_Table__c where Actual_Record_Id__c =: naaIds]){
            ActualRecToPmRecMap.put(pmt.Actual_Record_Id__c, pmt);
        }
        Map<String,String> incomeAcc = getPicklistvalue('csmso__Rate_Card_Item_Price__c', 'Income_Account__c');
        Map<String,String> deferredAcc = getPicklistvalue('csmso__Rate_Card_Item_Price__c', 'Deferred_Revenue_Account__c');
        Map<String,String> prodCategory = getPicklistvalue('csmso__Rate_Card_Item_Price__c', 'Product_Category__c');
        Map<String,String> prodClass = getPicklistvalue('csmso__Rate_Card_Item_Price__c', 'Product_Class__c');
        Map<String,String> prodSubClass = getPicklistvalue('csmso__Rate_Card_Item_Price__c', 'Product_Subclass__c');
        Map<String,String> durationTerm = getPicklistvalue('csmso__Node_Advert_Assignment__c', 'Duration_Term__c');
        
        for(csmso__Node_Advert_Assignment__c na : scope){
            Product_Master_Table__c masterRecord = new Product_Master_Table__c();
            if(ActualRecToPmRecMap.containskey(na.Id))
                masterRecord.Id = ActualRecToPmRecMap.get(na.Id).Id;
            masterRecord.Actual_Record_Id__c = na.Id;
            masterRecord.Product_Name__c = na.Product_Name__c;
            masterRecord.Bundle_Only__c = na.Bundle_Only__c;
            masterRecord.Product_Stored_In__c = 'Node Advert Assignment';
            masterRecord.Description__c = na.Product_Info__c;
            masterRecord.Rev_Accrual_GL_Code__c = na.Rev_Accrual_GL_Code__c;
            masterRecord.Product_Definition_Name__c = na.Served_by__c;
            masterRecord.Duration__c = na.Duration__c;
            masterRecord.Duration_Term__c = durationTerm.get(na.Duration_Term__c);
            masterRecord.CurrencyIsoCode = na.CurrencyIsoCode;
            masterRecord.SOV__c = na.SOV__c;
            masterRecord.Starting_Day__c = na.Starting_Day__c;
            if(naaToRateCardItemMap.containskey(na.Id) && naaToRateCardItemMap.get(na.Id) != null){
                masterRecord.Income_Account_Code__c = incomeAcc.get(naaToRateCardItemMap.get(na.Id).Income_Account__c);
                masterRecord.Deferred_Account_Code__c = deferredAcc.get(naaToRateCardItemMap.get(na.Id).Deferred_Revenue_Account__c);
                masterRecord.Tax_Code__c = naaToRateCardItemMap.get(na.Id).Tax_Code__c;
                masterRecord.Effective_end_date__c = naaToRateCardItemMap.get(na.Id).csmso__Rate_Card__r.csmso__To_Date__c;
                masterRecord.Effective_start_date__c = naaToRateCardItemMap.get(na.Id).csmso__Rate_Card__r.csmso__From_Date__c;
                masterRecord.Product_Catagory__c = prodCategory.get(naaToRateCardItemMap.get(na.Id).Product_Category__c);
                masterRecord.Product_Class__c = prodClass.get(naaToRateCardItemMap.get(na.Id).Product_Class__c);
                masterRecord.Product_Subclass__c = prodSubClass.get(naaToRateCardItemMap.get(na.Id).Product_Subclass__c);
                masterRecord.Product_List_Price__c = naaToRateCardItemMap.get(na.Id).csmso__Price_Per_Unit__c;
            }                        
            masterRecordsList.add(masterRecord);
        }
        if(!masterRecordsList.isEmpty())
            Upsert masterRecordsList;
    }
    global void finish(Database.BatchableContext BC){
    }
    
    public Map<String, String> getPicklistvalue(String objectName, String fieldName){
        
        Map<String, String> picklistValuesMaps = new Map<String, String>();
        Schema.SObjectType s = Schema.getGlobalDescribe().get(objectName) ;
        Schema.DescribeSObjectResult r = s.getDescribe() ;
        Map<String,Schema.SObjectField> fields = r.fields.getMap() ;
        Schema.DescribeFieldResult fieldResult = fields.get(fieldName).getDescribe();
        List<Schema.PicklistEntry> ple = fieldResult.getPicklistValues();
        for( Schema.PicklistEntry pickListVal : ple){
            picklistValuesMaps.put(pickListVal.getValue(), pickListVal.getLabel());
        } 
        return picklistValuesMaps;
    }
}