unpackaged/main/default/objects/CS_Revenue_Schedule_Item__c/CS_Revenue_Schedule_Item__c.object-meta.xml
<CustomObject>
    <description>Individiual details for one billing period for one line within a Sales Order</description>
    <label>Revenue Schedule Item</label>
    <nameField>
        <displayFormat>REVI-{00000000}</displayFormat>
        <label>Revenue Recognition Schedule Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Revenue Schedule Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/CS_Revenue_Schedule_Item__c/fields/Advertiser__c.field-meta.xml
<CustomField>
    <fullName>Advertiser__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Advertiser as defined in the Sales Order.</description>
    <inlineHelpText>Advertiser as defined in the Sales Order.</inlineHelpText>
    <label>Advertiser</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Revenue Recognition Schedules (Advertiser)</relationshipLabel>
    <relationshipName>Revenue_Recognition_Schedules_new1</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/CS_Revenue_Schedule_Item__c/fields/Agency__c.field-meta.xml
<CustomField>
    <fullName>Agency__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Agency as defined in the Sales Order.</description>
    <inlineHelpText>Agency as defined in the Sales Order.</inlineHelpText>
    <label>Agency</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Revenue Recognition Schedules (Agency)</relationshipLabel>
    <relationshipName>Revenue_Recognition_Schedules_new2</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/CS_Revenue_Schedule_Item__c/fields/Bill_to_Account__c.field-meta.xml
<CustomField>
    <fullName>Bill_to_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Bill To Account</description>
    <inlineHelpText>Bill To Account</inlineHelpText>
    <label>Bill to Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Revenue Schedule Items (Bill to Account)</relationshipLabel>
    <relationshipName>Revenue_Schedule_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/CS_Revenue_Schedule_Item__c/fields/Sales_Order__c.field-meta.xml
<CustomField>
    <fullName>Sales_Order__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Link to the related Sales Order.</description>
    <inlineHelpText>Link to the related Sales Order.</inlineHelpText>
    <label>Sales Order</label>
    <referenceTo>csmso__Sales_Order__c</referenceTo>
    <relationshipLabel>Revenue Schedule Item</relationshipLabel>
    <relationshipName>CS_Revenue_Schedule_Item</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/CS_Revenue_Schedule_Item__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>Rev Rec Schedule Status.</description>
    <inlineHelpText>Rev Rec Schedule Status.</inlineHelpText>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Open</fullName>
            </value>
            <value>
                <fullName>Locked</fullName>
            </value>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Ready</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
            <value>
                <fullName>Forecast</fullName>
            </value>
            <value>
                <fullName>Pending Closure</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/classes/CS_P_SOBillAdvertiserAgencyChange.cls
/**
* ─────────────────────────────────────────────────────────────────────────────────────────────────┐
* Used to update handle update RSI logic after changes on following fields Advertiser__c, Agency__c, Bill_To_Account__c
* ──────────────────────────────────────────────────────────────────────────────────────────────────
* @author         Ivan Ravnjak   <ivan.ravnjak@cloudsense.com>
* ──────────────────────────────────────────────────────────────────────────────────────────────────
* @changes
* v1.0            ivan.ravnjak@cloudsense.com
* 2019-04-15      Initial version 
* ─────────────────────────────────────────────────────────────────────────────────────────────────┘
*/
public class CS_P_SOBillAdvertiserAgencyChange extends CS_ProcessBase {
	@TestVisible 
	Map<Id, csmso__Sales_Order__c> applicableObjects;
	
	@TestVisible
	Map<Id, csmso__Sales_Order__c> oldObjects;

	public CS_P_SOBillAdvertiserAgencyChange(Map<Id, csmso__Sales_Order__c> oldObjects) {
		super(CS_ProcessDefinition.SO_BILLADVERTISERAGENCYCHANGE, 'CS_P_SOBillAdvertiserAgencyChange');
		
		this.oldObjects = oldObjects;
		applicableObjects = new Map<Id, csmso__Sales_Order__c>();
	}
 
	public override void isRecordEligible(SObject obj) {
		csmso__Sales_Order__c newSalesOrder = (csmso__Sales_Order__c) obj;
		csmso__Sales_Order__c oldSalesOrder = oldObjects != null ? (csmso__Sales_Order__c) oldObjects.get(newSalesOrder.Id) : null;

		if(oldSalesOrder.Bill_To_Account_Final__c !=  newSalesOrder.Bill_To_Account_Final__c){
            applicableObjects.put(newSalesOrder.Id, newSalesOrder);
        } 
        else if(oldSalesOrder.Advertiser_Final__c !=  newSalesOrder.Advertiser_Final__c){
            applicableObjects.put(newSalesOrder.Id, newSalesOrder);
        }
        else if(oldSalesOrder.Agency_Final__c != newSalesOrder.Agency_Final__c) {
        	applicableObjects.put(newSalesOrder.Id, newSalesOrder);
        }


		this.runProcess = !applicableObjects.isEmpty();
	}

	public override void logic() {
		List<CS_Revenue_Schedule_Item__c> rScheduleItems  = new List<CS_Revenue_Schedule_Item__c>();
		List<CS_Revenue_Schedule_Item__c> updateRSchedules  = new List<CS_Revenue_Schedule_Item__c>();

		//Fetching Billing Schedules.
		rScheduleItems = [select id, Advertiser__c, Agency__c, Bill_To_Account__c, Sales_Order__c  FROM CS_Revenue_Schedule_Item__c
			                                                      WHERE Sales_Order__c IN :applicableObjects.keySet()
			                                                      AND (Status__c =:CS_const_SalesOrder.ScheduleStatus_Forecast OR 
			                                                      	   Status__c =:CS_const_SalesOrder.ScheduleStatus_Open)];

		if ( !rScheduleItems.isEmpty() ){
			for (CS_Revenue_Schedule_Item__c currRSchedule : rScheduleItems){
				csmso__Sales_Order__c currSO = applicableObjects.get(currRSchedule.Sales_Order__c);
				
				currRSchedule.Advertiser__c = currSO.Advertiser_Final__c;
				currRSchedule.Agency__c = currSO.Agency_Final__c;
				currRSchedule.Bill_To_Account__c = currSO.Bill_To_Account_Final__c;

				updateRSchedules.add(currRSchedule);
			}
		}
		
		if( !updateRSchedules.isEmpty() ){
			UPDATE updateRSchedules;
		}
	}
}