unpackaged/main/default/objects/CS_Revenue_Schedule_Item__c/CS_Revenue_Schedule_Item__c.object-meta.xml
<CustomObject>
    <description>Individiual details for one billing period for one line within a Sales Order</description>
    <label>Revenue Schedule Item</label>
    <nameField>
        <displayFormat>REVI-{00000000}</displayFormat>
        <label>Revenue Recognition Schedule Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Revenue Schedule Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/CS_Revenue_Schedule_Item__c/fields/Rev_Rec_Period_Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Rev_Rec_Period_Start_Date__c</fullName>
    <description>-Monthly Standard : The Latest from SO Line Start Date or first day of Standard Calendar Month for the Rev Rec Date.</description>
    <inlineHelpText>-Monthly Standard : The Latest from SO Line Start Date or first day of Standard Calendar Month for the Rev Rec Date.</inlineHelpText>
    <label>Rev Rec Period Start Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/CS_Revenue_Schedule_Item__c/fields/Revenue_Schedule__c.field-meta.xml
<CustomField>
    <fullName>Revenue_Schedule__c</fullName>
    <description>Link to Revenue Schedule Header</description>
    <inlineHelpText>Link to Revenue Schedule Header</inlineHelpText>
    <label>Revenue Schedule</label>
    <referenceTo>CS_Revenue_Schedule__c</referenceTo>
    <relationshipLabel>Revenue Schedule Items</relationshipLabel>
    <relationshipName>Revenue_Schedule_Items</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/CS_Revenue_Schedule_Item__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>Rev Rec Schedule Status.</description>
    <inlineHelpText>Rev Rec Schedule Status.</inlineHelpText>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Open</fullName>
            </value>
            <value>
                <fullName>Locked</fullName>
            </value>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Ready</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
            <value>
                <fullName>Forecast</fullName>
            </value>
            <value>
                <fullName>Pending Closure</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/CS_Revenue_Schedule_Item__c/fields/Total_Open_Qty__c.field-meta.xml
<CustomField>
    <fullName>Total_Open_Qty__c</fullName>
    <label>Total Open Qty</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/CS_Revenue_Schedule_Item__c/fields/Total_Open_Qty_in_Previous_Period__c.field-meta.xml
<CustomField>
    <fullName>Total_Open_Qty_in_Previous_Period__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Total Open Qty in Previous Period</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/classes/CS_P_UpdateOpenQuantityRevenue.cls
/**
* ─────────────────────────────────────────────────────────────────────────────────────────────────┐
* Used open quantity on RSI
* ──────────────────────────────────────────────────────────────────────────────────────────────────
* @author         Sasa Marjancic   <sasa.marjancic@cloudsense.com>
* ──────────────────────────────────────────────────────────────────────────────────────────────────
* @changes
* ─────────────────────────────────────────────────────────────────────────────────────────────────┘
*/
public class CS_P_UpdateOpenQuantityRevenue extends CS_ProcessBase {      
	@TestVisible 
	Map<Id, CS_Revenue_Schedule_Item__c> applicableObjects;

    @TestVisible 
	Map<Id, CS_Revenue_Schedule_Item__c> oldObjects;

    @TestVisible
    Set<Id> revenueScheduleIds;

	public CS_P_UpdateOpenQuantityRevenue(Map<Id, CS_Revenue_Schedule_Item__c> oldObjects) {
		super(CS_ProcessDefinition.RSI_UPDATEOPENQUANTITY, 'CS_P_UpdateOpenQuantityRevenue');

		applicableObjects = new Map<Id, CS_Revenue_Schedule_Item__c>();
        revenueScheduleIds = new Set<Id>();
        this.oldObjects = oldObjects;
	}
 
	public override void isRecordEligible(SObject obj) {
		CS_Revenue_Schedule_Item__c revenueScheduleItem = (CS_Revenue_Schedule_Item__c) obj;
        CS_Revenue_Schedule_Item__c oldRevenueScheduleItem = oldObjects.get(revenueScheduleItem.Id);
		
		if(revenueScheduleItem.Total_Open_Qty__c != oldRevenueScheduleItem.Total_Open_Qty__c) {
			applicableObjects.put(revenueScheduleItem.Id, revenueScheduleItem);
            revenueScheduleIds.add(revenueScheduleItem.Revenue_Schedule__c);
		}

		this.runProcess = !applicableObjects.isEmpty();
	}

	public override void logic() {
        Map<Id, List<CS_Revenue_Schedule_Item__c>> revenueScheduleItems = new Map<Id, List<CS_Revenue_Schedule_Item__c>>();
        for(CS_Revenue_Schedule_Item__c rsi : [SELECT Id, Revenue_Schedule__c, Rev_Rec_Period_Start_Date__c
                                                FROM CS_Revenue_Schedule_Item__c
                                                WHERE Revenue_Schedule__c = :revenueScheduleIds
                                                AND Status__c = :CS_const_SalesOrder.ScheduleStatus_Open
                                                AND Id != :applicableObjects.keySet()]) {
            if(!revenueScheduleItems.containsKey(rsi.Revenue_Schedule__c)) {
                revenueScheduleItems.put(rsi.Revenue_Schedule__c, new List<CS_Revenue_Schedule_Item__c>());
            }
            revenueScheduleItems.get(rsi.Revenue_Schedule__c).add(rsi);
        }

        List<CS_Revenue_Schedule_Item__c> rsiToUpdate = new List<CS_Revenue_Schedule_Item__c>();
        for(CS_Revenue_Schedule_Item__c rsi : applicableObjects.values()) {
            List<CS_Revenue_Schedule_Item__c> currentRevenueScheduleItems = revenueScheduleItems.get(rsi.Revenue_Schedule__c);
            if(currentRevenueScheduleItems != null) {
                for(CS_Revenue_Schedule_Item__c currentRsi : currentRevenueScheduleItems) {
                    currentRsi.Total_Open_Qty_in_Previous_Period__c = rsi.Total_Open_Qty__c;
                    rsiToUpdate.add(currentRsi);
                }
            }
        }

        if(!rsiToUpdate.isEmpty()) {
            update rsiToUpdate;
        }
	}
}