unpackaged/main/default/objects/Opportunity/fields/Agent_Accepted_Time__c.field-meta.xml
<CustomField>
    <fullName>Agent_Accepted_Time__c</fullName>
    <label>Agent Accepted Time</label>
    <type>DateTime</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Approval_Status__c.field-meta.xml
<CustomField>
    <fullName>Approval_Status__c</fullName>
    <label>Approval Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Discount Approval Submitted</fullName>
            </value>
            <value>
                <fullName>Discount Approval Approved</fullName>
            </value>
            <value>
                <fullName>Discount Approval Rejected</fullName>
            </value>
            <value>
                <fullName>Re-submit Discount Approval</fullName>
            </value>
            <value>
                <fullName>Awaits OMC Approval</fullName>
            </value>
            <value>
                <fullName>OMC Approval Submitted</fullName>
            </value>
            <value>
                <fullName>OMC Approval Approved</fullName>
            </value>
            <value>
                <fullName>OMC Approval Recalled</fullName>
            </value>
            <value>
                <fullName>OMC Approval Rejected</fullName>
            </value>
            <value>
                <fullName>Not Required</fullName>
            </value>
            <value>
                <fullName>NS Order Generated</fullName>
            </value>
            <value>
                <fullName>Product Owner Approved</fullName>
            </value>
            <value>
                <fullName>Director Approved</fullName>
            </value>
            <value>
                <fullName>Country Manager Approved</fullName>
            </value>
            <value>
                <fullName>CBO Approved</fullName>
            </value>
            <value>
                <fullName>Discount Approval Required</fullName>
                <isActive>false</isActive>
                <label>Discount Approval Required</label>
            </value>
            <value>
                <fullName>Manager Approved</fullName>
                <isActive>false</isActive>
                <label>Manager Approved</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Country__c.field-meta.xml
<CustomField>
    <fullName>Country__c</fullName>
    <formula>TEXT(Subsidiary__r.Country__c )</formula>
    <label>Country</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Invoice_Id__c.field-meta.xml
<CustomField>
    <fullName>Invoice_Id__c</fullName>
    <externalId>true</externalId>
    <label>Invoice Id</label>
    <length>20</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Payment_Amount__c.field-meta.xml
<CustomField>
    <fullName>Payment_Amount__c</fullName>
    <label>Payment Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Payment_Reference__c.field-meta.xml
<CustomField>
    <fullName>Payment_Reference__c</fullName>
    <label>Payment Reference</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Payment_Time__c.field-meta.xml
<CustomField>
    <fullName>Payment_Time__c</fullName>
    <label>Payment Time</label>
    <type>DateTime</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Payment_Type__c.field-meta.xml
<CustomField>
    <fullName>Payment_Type__c</fullName>
    <label>Payment Method</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Online</fullName>
            </value>
            <value>
                <fullName>Offline</fullName>
            </value>
            <value>
                <fullName>credit-card</fullName>
                <label>Credit Card</label>
            </value>
            <value>
                <fullName>bank-transfer</fullName>
                <label>Bank Transfer</label>
            </value>
            <value>
                <fullName>paypal</fullName>
                <label>Paypal</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Submit_to_OMC_Manually__c.field-meta.xml
<CustomField>
    <fullName>Submit_to_OMC_Manually__c</fullName>
    <defaultValue>true</defaultValue>
    <label>Submit to OMC Manually</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/to_FOC_Approval__c.field-meta.xml
<CustomField>
    <fullName>to_FOC_Approval__c</fullName>
    <formula>if(OR(AND( Country__c = &#39;Singapore&#39;,Total_Amount_of_FOC_Product__c  &gt; 0), AND( Country__c = &#39;Malaysia&#39;, Total_Amount_of_FOC_Before_Discount_MY__c &gt; 0)) ,true,false)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>to FOC Approval</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/to_VIP_Approval__c.field-meta.xml
<CustomField>
    <fullName>to_VIP_Approval__c</fullName>
    <formula>if( Count_of_VIP_Subscription_new__c &gt; 0,true,false)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>to VIP Approval</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Total_Gross_Amount__c.field-meta.xml
<CustomField>
    <fullName>Total_Gross_Amount__c</fullName>
    <inlineHelpText>Total Amount after discount &amp; tax</inlineHelpText>
    <label>Total Gross Amount</label>
    <summarizedField>OpportunityLineItem.Gross_Amount__c</summarizedField>
    <summaryForeignKey>OpportunityLineItem.OpportunityId</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/recordTypes/B2C.recordType-meta.xml
<RecordType>
    <fullName>B2C</fullName>
    <active>true</active>
    <businessProcess>B2C</businessProcess>
    <description>B2C Opportunity Record</description>
    <label>B2C</label>
</RecordType>

unpackaged/main/default/objects/Payment__c/Payment__c.object-meta.xml
<CustomObject>
    <label>Payment</label>
    <nameField>
        <displayFormat>PY{0}</displayFormat>
        <label>Payment Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Payments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Payment__c/fields/Amount__c.field-meta.xml
<CustomField>
    <fullName>Amount__c</fullName>
    <label>Amount</label>
    <precision>10</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

unpackaged/main/default/objects/Payment__c/fields/Quote_Record__c.field-meta.xml
<CustomField>
    <fullName>Quote_Record__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Denotes the quote record that payment is created for</description>
    <inlineHelpText>Denotes the quote record that payment is created for</inlineHelpText>
    <label>Quote Record</label>
    <referenceTo>Quote</referenceTo>
    <relationshipLabel>Payments</relationshipLabel>
    <relationshipName>Payments</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Product2/fields/Multiple_Sale_Not_Allowed__c.field-meta.xml
<CustomField>
    <fullName>Multiple_Sale_Not_Allowed__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Represents product can not be sold multiple times within a single quote.</description>
    <inlineHelpText>Represents product can not be sold multiple times within a single quote</inlineHelpText>
    <label>Multiple Sale Not Allowed</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Quote/fields/Agent_Accepted_Time__c.field-meta.xml
<CustomField>
    <fullName>Agent_Accepted_Time__c</fullName>
    <label>Agent Accepted Time</label>
    <type>DateTime</type>
</CustomField>

unpackaged/main/default/objects/Quote/fields/Approval_Status__c.field-meta.xml
<CustomField>
    <fullName>Approval_Status__c</fullName>
    <label>Approval Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Discount Approval Submitted</fullName>
            </value>
            <value>
                <fullName>Discount Approval Approved</fullName>
            </value>
            <value>
                <fullName>Discount Approval Rejected</fullName>
            </value>
            <value>
                <fullName>Re-submit Discount Approval</fullName>
            </value>
            <value>
                <fullName>Awaits OMC Approval</fullName>
            </value>
            <value>
                <fullName>OMC Approval Submitted</fullName>
            </value>
            <value>
                <fullName>OMC Approval Approved</fullName>
            </value>
            <value>
                <fullName>OMC Approval Recalled</fullName>
            </value>
            <value>
                <fullName>OMC Approval Rejected</fullName>
            </value>
            <value>
                <fullName>Not Required</fullName>
            </value>
            <value>
                <fullName>NS Order Generated</fullName>
            </value>
            <value>
                <fullName>Discount Approval Recalled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Quote/fields/Country__c.field-meta.xml
<CustomField>
    <fullName>Country__c</fullName>
    <formula>TEXT(Opportunity.Subsidiary__r.Country__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Country</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Quote/fields/Floor_Price_Type__c.field-meta.xml
<CustomField>
    <fullName>Floor_Price_Type__c</fullName>
    <description>Used to identify approvers for ad/ prime credit discount approval</description>
    <label>Floor Price Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Above Floor Price</fullName>
            </value>
            <value>
                <fullName>Below Floor Price</fullName>
            </value>
            <value>
                <fullName>Below List Price</fullName>
            </value>
            <value>
                <fullName>Below List Price with Discount</fullName>
            </value>
            <value>
                <fullName>Between Floor Price</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Quote/fields/Invoice_Id__c.field-meta.xml
<CustomField>
    <fullName>Invoice_Id__c</fullName>
    <label>Invoice Id</label>
    <length>20</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

unpackaged/main/default/objects/Quote/fields/Payment_Amount__c.field-meta.xml
<CustomField>
    <fullName>Payment_Amount__c</fullName>
    <label>Payment Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

unpackaged/main/default/objects/Quote/fields/Payment_Reference__c.field-meta.xml
<CustomField>
    <fullName>Payment_Reference__c</fullName>
    <label>Payment Reference</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Quote/fields/Payment_Time__c.field-meta.xml
<CustomField>
    <fullName>Payment_Time__c</fullName>
    <label>Payment Time</label>
    <type>DateTime</type>
</CustomField>

unpackaged/main/default/objects/Quote/fields/Quote_Type__c.field-meta.xml
<CustomField>
    <fullName>Quote_Type__c</fullName>
    <label>Quote Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>B2C - Standard</fullName>
            </value>
            <value>
                <fullName>B2C - Upgrade</fullName>
            </value>
            <value>
                <fullName>B2C - Renewal</fullName>
            </value>
            <value>
                <fullName>B2C - Conversion</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Quote/fields/Submit_to_OMC_Manually__c.field-meta.xml
<CustomField>
    <fullName>Submit_to_OMC_Manually__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Submit to OMC Manually</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Quote/fields/to_FOC_Approval__c.field-meta.xml
<CustomField>
    <fullName>to_FOC_Approval__c</fullName>
    <formula>if(OR(AND( Country__c = &#39;Singapore&#39;,Total_Amount_of_FOC_Product__c &gt; 0),AND( Country__c = &#39;Thailand&#39;,Total_Amount_of_FOC_Product_TH__c &gt; 0), AND( Country__c = &#39;Malaysia&#39;, Total_Amount_of_FOC_Before_Discount_MY__c &gt; 0)) ,true,false)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>to FOC Approval</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Quote/fields/to_VIP_Approval__c.field-meta.xml
<CustomField>
    <fullName>to_VIP_Approval__c</fullName>
    <formula>if(Count_of_VIP_Subscription__c &gt; 0,true,false)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>to VIP Approval</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Quote/fields/Total_Gross_Amount__c.field-meta.xml
<CustomField>
    <fullName>Total_Gross_Amount__c</fullName>
    <label>Total Gross Amount</label>
    <summarizedField>QuoteLineItem.Gross_Amount__c</summarizedField>
    <summaryForeignKey>QuoteLineItem.QuoteId</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

unpackaged/main/default/objects/Quote/recordTypes/B2C.recordType-meta.xml
<RecordType>
    <fullName>B2C</fullName>
    <active>true</active>
    <label>B2C</label>
</RecordType>

unpackaged/main/default/objects/QuoteLineItem/fields/Amount__c.field-meta.xml
<CustomField>
    <fullName>Amount__c</fullName>
    <formula>IF( Complimentary__c = TRUE, IF(Record_Type__c=&quot;B2C&quot;, (UnitPrice * Quantity) - Total_Price__c , (UnitPrice * Quantity) - Discounted_Amount__c - Total_Price__c) , IF(Record_Type__c=&quot;B2C&quot;, (UnitPrice * Quantity) - Discounted_Amount__c - Pro_Rate_Amount__c, (UnitPrice * Quantity) - Discounted_Amount__c))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Price after discount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

unpackaged/main/default/objects/QuoteLineItem/fields/Discount__c.field-meta.xml
<CustomField>
    <fullName>Discount__c</fullName>
    <defaultValue>0</defaultValue>
    <description>Copied from Oppty Product Discount__c</description>
    <label>Discount %</label>
    <precision>5</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

unpackaged/main/default/objects/QuoteLineItem/fields/Discount_Amount__c.field-meta.xml
<CustomField>
    <fullName>Discount_Amount__c</fullName>
    <defaultValue>0</defaultValue>
    <description>Copy from Oppty Product Discount_Amount__</description>
    <label>Discount Amt</label>
    <precision>18</precision>
    <scale>3</scale>
    <type>Currency</type>
</CustomField>

unpackaged/main/default/objects/QuoteLineItem/fields/Quote_Type__c.field-meta.xml
<CustomField>
    <fullName>Quote_Type__c</fullName>
    <formula>TEXT(Quote.Quote_Type__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Quote Type</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/classes/ApprovalProcessStinger.cls
/*
* TestClass : ApprovalProcessStinger_Test
*/
public class ApprovalProcessStinger {
    
    @AuraEnabled
    public static void sendApporval(Id recordId){
        
        Quote qu = [Select Id,Status,isSyncing,to_FOC_Approval__c,to_VIP_Approval__c,Invoice_Id__c,Quote_Type__c,Total_Gross_Amount__c,Agent_Accepted_Time__c,approval_Status__c,recordType.Name,Country__c,Opportunity.Payment_Type__c,Opportunity.Payment_Time__c,Opportunity.Payment_Amount__c,Opportunity.Payment_Reference__c,OpportunityId from Quote where Id = : recordId];
        List<ContentDocumentLink> lstFiles= [SELECT ContentDocumentId FROM ContentDocumentLink WHERE LinkedEntityId =:qu.OpportunityId];
        //List<Payment__c> paymentList = [Select Id from Payment__c where Quote_Record__c = : recordId]; 
        Approval.ProcessSubmitRequest [] requestList = new Approval.ProcessSubmitRequest []{};
            
            if(!Test.isRunningTest() && qu.isSyncing == false){
                throw new AuraHandledException('Cannot submit an unsynced quote to OMC.');
            }else if(!Test.isRunningTest() &&  qu.Total_Gross_Amount__c == 0 && qu.Agent_Accepted_Time__c == null){
                throw new AuraHandledException('This Quote cannot be submitted to OMC. Please ensure customer has approved it.');
            }else if(qu.Total_Gross_Amount__c > 0 && (qu.Agent_Accepted_Time__c == null)){
                throw new AuraHandledException('This Quote cannot be submitted to OMC. Please ensure customer has approved it, and the payment has been made.');
            }else if( qu.approval_Status__c == 'OMC Approval Submitted'){
                throw new AuraHandledException('Your Quote is already sent to OMC. Please wait until OMC approved or rejected your Quote.');
            }else if( qu.approval_Status__c == 'OMC Approval Approved'){
                throw new AuraHandledException('This Quote has already approved by OMC.');
            }else if( !Test.isRunningTest() && qu.recordType.Name=='B2C' && !qu.to_VIP_Approval__c && !qu.to_FOC_Approval__c && (lstFiles==null || lstFiles.size()==0 )) {
                throw new AuraHandledException('Error : Please upload Attachment and Payment');
            }else{
                update new Quote(Id = qu.Id,submit_to_OMC_Manually__c=false);
                update new Opportunity(Id = qu.OpportunityId,submit_to_OMC_Manually__c=false);
                // Send approval
                Approval.ProcessSubmitRequest req1 = new Approval.ProcessSubmitRequest();
                req1.setComments('Need OMC Approval');
                req1.setObjectId(qu.Id);                
                // Submit the record to specific process
                req1.setProcessDefinitionNameOrId('Quote_B2C_PG_SG_OMC_Approval');
                system.debug('Send Approval');
                
                Approval.ProcessResult result = Approval.process(req1);
                system.debug('getInstanceStatus>>>'+result.getInstanceStatus());  
            }
    }
    @AuraEnabled
    public static string beforeApprovalValidation(String recordId){
        if(Approval.isLocked(recordId)){
            return 'Error : Record is locked';
        }
        
        List<ProcessDefinition> processDefinitionList = [SELECT id,TableEnumOrId FROM ProcessDefinition where TableEnumOrId = 'Quote' limit 50000];
        if(processDefinitionList == null || (processDefinitionList != null && processDefinitionList.isEmpty())){
            return 'Error : No Approval Process found on this object';
        }
        return 'SUCCESS';
    }
    @AuraEnabled
    public static string runApproval(string recordId, string approvalComment){
         List<QuoteLineItem> qliList = [SELECT Id,QuoteId,product2.Multiple_Sale_Not_Allowed__c,Discount_Amount__c,
                                       Quote.Floor_Price_Type__c,Discount__c,Price_before_discount__c,Amount__c FROM QuoteLineItem WHERE QuoteId = :recordId];
        Boolean isRequired= false;
        for(QuoteLineItem qli:qliList){
            if((qli.Quote.Floor_Price_Type__c == 'Below List Price') || ((qli.Discount__c == null || qli.Discount__c == 0 )
               && (qli.Discount_Amount__c == null || qli.Discount_Amount__c == 0) )){
                   isRequired = false;
               } else {
                   isRequired = true;
                   break;
               }
        }
        if(!isRequired) {
            return 'Error : No approval is required. Please proceed for payment';
        }
        Approval.ProcessSubmitRequest req = new Approval.ProcessSubmitRequest();
        req.setComments(approvalComment);
        req.setObjectId(recordId);
        Approval.ProcessResult result;
        try{
            update new Quote(id = recordId, Approval_Requester_Comment__c = approvalComment);
            result = Approval.process(req);
        }catch(Exception exp){
            return 'Error : '+exp.getMessage();
        }
        if(result.isSuccess() && !Test.isRunningTest()){
            return 'Discount Approval Request Submitted';
        }
        else{
            try{
                update new Quote(id = recordId, Approval_Requester_Comment__c = '');
            }catch(exception e){
                return 'Error : While removing Approval Requester Comment '+e.getMessage();
            }
            string errorToReturn = 'Errors : ';
            List<Database.Error> errorList = result.getErrors();
            if(errorList != null && !errorList.isEmpty()){
                for(Database.error errorStr : errorList){
                    errorToReturn += errorStr.getMessage()+'; ';
                } 
            }
            return errorToReturn;
        } 
    }
}