unpackaged/main/default/objects/Opportunity/fields/Agreement_Status_Date__c.field-meta.xml
<CustomField>
    <fullName>Agreement_Status_Date__c</fullName>
    <label>Agreement Status Date</label>
    <type>DateTime</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/SO_for_Customer_Approval__c.field-meta.xml
<CustomField>
    <fullName>SO_for_Customer_Approval__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>SO for Customer Approval</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>csmso__Sales_Order__c.csmso__Opportunity__r.Id</field>
            <operation>equals</operation>
            <valueField>$Source.Id</valueField>
        </filterItems>
        <infoMessage>Select a Sales Order that is attached to this Opportunity.</infoMessage>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>csmso__Sales_Order__c</referenceTo>
    <relationshipLabel>Opportunities (SO for Customer Approval)</relationshipLabel>
    <relationshipName>Opportunities1</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/classes/CS_P_SOAgreementStatusDateModified.cls
/**
* ─────────────────────────────────────────────────────────────────────────────────────────────────┐
* Update Sales Order after Opportunity has been sent out for signature
* ──────────────────────────────────────────────────────────────────────────────────────────────────
* @author         Sasa Marjancic
* ──────────────────────────────────────────────────────────────────────────────────────────────────
* @changes
* ─────────────────────────────────────────────────────────────────────────────────────────────────┘
*/
public class CS_P_SOAgreementStatusDateModified extends CS_ProcessBase {

    @TestVisible
    Map<Id, Opportunity> applicableObjects;

    @TestVisible
    Map<Id, Opportunity> oldOpps;

    private List<csmso__Sales_Order__c> salesOrderToUpdate{get;set;}

    public CS_P_SOAgreementStatusDateModified(Map<Id, Opportunity> oldOpps) {
        super(CS_ProcessDefinition.SO_AGREEMENTSTATUSDATEUPDATED, 'CS_P_SOAgreementStatusDateModified');

        applicableObjects = new Map<Id, Opportunity>();
        this.oldOpps = oldOpps;
    }

    public override void isRecordEligible(SObject obj) {
        Opportunity newOpp = (Opportunity) obj;
        Opportunity oldOpp = oldOpps.get(newOpp.Id);

        if(oldOpp.Agreement_Status_Date__c != newOpp.Agreement_Status_Date__c && newOpp.SO_for_Customer_Approval__c != null && newOpp.Agreement_Status_Date__c != null) {
            applicableObjects.put(newOpp.Id, newOpp);
        }

        this.runProcess = !applicableObjects.isEmpty();
    }

    public override void logic() {
        if (!applicableObjects.isEmpty()) {
            CSPOFA.Events.emit('update', applicableObjects.keySet());
        }
    }
}