unpackaged/main/default/objects/Opportunity/fields/Country__c.field-meta.xml
<CustomField>
    <fullName>Country__c</fullName>
    <formula>TEXT(Subsidiary__r.Country__c )</formula>
    <label>Country</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Upgrade_Package_Lookup__c/Upgrade_Package_Lookup__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>Upgrade Package Lookup Table</label>
</CustomObject>

unpackaged/main/default/objects/Upgrade_Package_Lookup__c/fields/Country__c.field-meta.xml
<CustomField>
    <fullName>Country__c</fullName>
    <label>Country</label>
    <length>60</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Upgrade_Package_Lookup__c/fields/Level__c.field-meta.xml
<CustomField>
    <fullName>Level__c</fullName>
    <label>Level</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/Upgrade_Package_Lookup__c/fields/Renewal_SKU__c.field-meta.xml
<CustomField>
    <fullName>Renewal_SKU__c</fullName>
    <label>Renewal SKU</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Upgrade_Package_Lookup__c/fields/Renewal_Type__c.field-meta.xml
<CustomField>
    <fullName>Renewal_Type__c</fullName>
    <label>Renewal Type</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Upgrade_Package_Lookup__c/fields/Upgrade_SKU__c.field-meta.xml
<CustomField>
    <fullName>Upgrade_SKU__c</fullName>
    <label>Upgrade SKU Outside</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

unpackaged/main/default/classes/AssignMY_SGRenewalOpp.cls
public class AssignMY_SGRenewalOpp {
    
    // fetch the list of users having role as MY renewal Team lead or MY Renewal Sales Rep
    public static List<User> getMYRenewalSalesRep(){
        List<User> listUser=[Select id from User where
                             (UserRole.name = 'MY - Renewal Team Lead' or UserRole.Name = 'MY - Renewal Sales Rep')
                             and IsActive = true];
        return listUser;
    }
    
    // divide the renewal oppty's among MY renewal sales rep/lead
    public static void assignMYRenewalOppty(Map<String, list<Opportunity>> ruleCodeMapMY){
        List<User> listUser=getMYRenewalSalesRep();
        List<Opportunity> oppList=new List<Opportunity>();
        integer userCount=listUser.size();
        integer i=0;
        List<Upgrade_Package_Lookup__c> upgPkgList = [Select Country__c,Level__c,Name, Renewal_SKU__c,Upgrade_SKU__c,Renewal_Type__c,IsActive__c 
                                                      from Upgrade_Package_Lookup__c where  Country__c ='Malaysia' order by Level__c desc];
        for(String s:ruleCodeMapMY.keySet()){
            system.debug('>>>>><<<< '+s);
        }
        for(Upgrade_Package_Lookup__c upgPkg : upgPkgList){
            String ruleCode =upgPkg.name.replace(' - MY','').toLowerCase();
            system.debug('ruleCode    '+ruleCode);
            if(ruleCodeMapMY.containsKey(ruleCode)){
                for(Opportunity opp : ruleCodeMapMY.get(ruleCode)){
                    oppList.add(new opportunity(id=opp.id,ownerid=listUser[i].id));
                    //opp.ownerid=listUser[i].id;
                    i++;
                    if(i==userCount){
                        i=0;
                    }
                }
            }
        }
        Database.executeBatch(new UpdateRenewalOppOwner_Batch(oppList),10);
        //call batch class
    }
}