unpackaged/main/default/objects/Opportunity/fields/OMC_Rejected_Reason__c.field-meta.xml
<CustomField>
    <fullName>OMC_Rejected_Reason__c</fullName>
    <label>OMC Rejected Reason</label>
    <type>TextArea</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/OMC_Submitted_Time__c.field-meta.xml
<CustomField>
    <fullName>OMC_Submitted_Time__c</fullName>
    <description>Timestamp to indicate the most recent time that the Opportunity was submitted to OMC.</description>
    <label>OMC Submitted Time</label>
    <type>DateTime</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Opportunity_Type__c.field-meta.xml
<CustomField>
    <fullName>Opportunity_Type__c</fullName>
    <defaultValue>IF( $RecordType.DeveloperName = &#39;B2C&#39; , &#39;B2C - Standard&#39;, null)</defaultValue>
    <label>Opportunity Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>B2C - Standard</fullName>
            </value>
            <value>
                <fullName>B2C - Upgrade</fullName>
            </value>
            <value>
                <fullName>B2C - Renewal</fullName>
            </value>
            <value>
                <fullName>Self-Serve Standard</fullName>
            </value>
            <value>
                <fullName>Self-Serve Renewal</fullName>
            </value>
            <value>
                <fullName>Self-Serve Abandoned</fullName>
            </value>
            <value>
                <fullName>Marketing Automation</fullName>
            </value>
            <value>
                <fullName>B2C - Conversion</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Opportunity/recordTypes/B2C.recordType-meta.xml
<RecordType>
    <fullName>B2C</fullName>
    <active>true</active>
    <businessProcess>B2C</businessProcess>
    <description>B2C Opportunity Record</description>
    <label>B2C</label>
</RecordType>

unpackaged/main/default/objects/Quote/fields/OMC_Rejected_Reason__c.field-meta.xml
<CustomField>
    <fullName>OMC_Rejected_Reason__c</fullName>
    <label>OMC Rejected Reason</label>
    <type>TextArea</type>
</CustomField>

unpackaged/main/default/objects/Quote/fields/OMC_Submitted_Time__c.field-meta.xml
<CustomField>
    <fullName>OMC_Submitted_Time__c</fullName>
    <label>OMC Submitted Time</label>
    <type>DateTime</type>
</CustomField>

unpackaged/main/default/objects/Quote/recordTypes/B2C.recordType-meta.xml
<RecordType>
    <fullName>B2C</fullName>
    <active>true</active>
    <label>B2C</label>
</RecordType>

unpackaged/main/default/classes/oppRejectionUpdate_Batch.cls
//TEST CLASS:oppRejectionUpdate_Batch_Test
global class oppRejectionUpdate_Batch implements Database.Batchable<sObject>, Database.Stateful{
    global Database.QueryLocator start(Database.BatchableContext BC)  {
        String query ='SELECT Id ,OMC_Submitted_Time__c,OMC_Rejected_Reason__c FROM Opportunity WHERE Opportunity_Type__c !=\'\' AND (StageName = \'Closed Won\' OR StageName =\'Closed Lost\') AND (Recordtype.developerName =\'B2C\' OR Recordtype.developerName =\'B2C Closed Lost\')';
        
        return Database.getQueryLocator(query);
    }
    global void execute(Database.BatchableContext BC, List<Opportunity> scope){
        
        Map<ID,Opportunity> opportunityToUpdate = new Map<ID,Opportunity>();
        Map<ID,Quote> relatedQuotes = new Map<ID,Quote>();
        
        for(Opportunity opp : scope){
            opportunityToUpdate.put(opp.id,opp);
        }
        
        for(Quote q :[SELECT Id, OMC_Submitted_Time__c,OMC_Rejected_Reason__c,OpportunityId FROM Quote WHERE OMC_Submitted_Time__c !=null AND OMC_Rejected_Reason__c !=null AND OpportunityId IN : opportunityToUpdate.keyset() order by OMC_Submitted_Time__c desc]){
            
            if(!relatedQuotes.containskey(q.OpportunityId)){
                relatedQuotes.put(q.OpportunityId,q);
            }
            
        }       	   
        for(Quote q :relatedQuotes.values()){
            opportunityToUpdate.get(q.OpportunityId).OMC_Rejected_Reason__c = q.OMC_Rejected_Reason__c;
            
        }
        
        update opportunityToUpdate.values();
        
    }
    global void finish(Database.BatchableContext BC) {
        
    }
}