unpackaged/main/default/objects/Opportunity/fields/Primary_Sales_Order__c.field-meta.xml
<CustomField>
    <fullName>Primary_Sales_Order__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Primary Sales Order linked to this Opportunity</description>
    <inlineHelpText>Primary Sales Order linked to this Opportunity</inlineHelpText>
    <label>Primary Sales Order</label>
    <referenceTo>csmso__Sales_Order__c</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Product_Category__c.field-meta.xml
<CustomField>
    <fullName>Product_Category__c</fullName>
    <label>Product Category</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Awards</fullName>
            </value>
            <value>
                <fullName>China Solutions</fullName>
            </value>
            <value>
                <fullName>Events</fullName>
            </value>
            <value>
                <fullName>Agent Discretionary</fullName>
            </value>
            <value>
                <fullName>Agent Subscriptions</fullName>
            </value>
            <value>
                <fullName>Developer Listings</fullName>
            </value>
            <value>
                <fullName>Online Advertising</fullName>
            </value>
            <value>
                <fullName>Marketing Services</fullName>
            </value>
            <value>
                <fullName>Database Marketing</fullName>
            </value>
            <value>
                <fullName>Content</fullName>
            </value>
            <value>
                <fullName>FinTech</fullName>
            </value>
            <value>
                <fullName>FastKey</fullName>
            </value>
            <value>
                <fullName>Data MPD</fullName>
            </value>
            <value>
                <fullName>Discretionary</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Opportunity/recordTypes/B2B.recordType-meta.xml
<RecordType>
    <fullName>B2B</fullName>
    <active>true</active>
    <businessProcess>B2B</businessProcess>
    <description>B2B Opportunity Record</description>
    <label>B2B</label>
</RecordType>

unpackaged/main/default/classes/BatchToUpdateProdCatOpp.cls
public class BatchToUpdateProdCatOpp  implements Database.Batchable<sObject>{
    public Database.QueryLocator start(Database.BatchableContext bc) {

        return Database.getQueryLocator(
            'Select id,Product_category__c, (select id,Product_category__c from OpportunityLineItems) from Opportunity where Product_category__c=null and Primary_Sales_Order__c!=null and (recordtype.Name=\'B2B\' or recordType.name=\'Direct booking\') '
        ); 
    }
    public void execute(Database.BatchableContext bc, List<Opportunity> scope){
        List<Opportunity> oppList = new  List<Opportunity>();
        for(Opportunity opp : Scope){
            Set<String> category = new set<String>();
            for(OpportunityLineItem oli : opp.OpportunityLineItems){
                if(oli.Product_category__c != null)
                category.add(oli.Product_category__c);
             }
            if(category.size()>0){
            List<String> cat = new List<String>();
                cat.addAll(category);
            opp.Product_category__c = String.join(cat, ';');
            oppList.add(opp);
            }
        }
        update OppList;
    }
    public void finish(Database.BatchableContext bc){
    }
}