unpackaged/main/default/objects/Opportunity/fields/Primary_Sales_Order__c.field-meta.xml
<CustomField>
    <fullName>Primary_Sales_Order__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Primary Sales Order linked to this Opportunity</description>
    <inlineHelpText>Primary Sales Order linked to this Opportunity</inlineHelpText>
    <label>Primary Sales Order</label>
    <referenceTo>csmso__Sales_Order__c</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Product_Category__c.field-meta.xml
<CustomField>
    <fullName>Product_Category__c</fullName>
    <label>Product Category</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Awards</fullName>
            </value>
            <value>
                <fullName>China Solutions</fullName>
            </value>
            <value>
                <fullName>Events</fullName>
            </value>
            <value>
                <fullName>Agent Discretionary</fullName>
            </value>
            <value>
                <fullName>Agent Subscriptions</fullName>
            </value>
            <value>
                <fullName>Developer Listings</fullName>
            </value>
            <value>
                <fullName>Online Advertising</fullName>
            </value>
            <value>
                <fullName>Marketing Services</fullName>
            </value>
            <value>
                <fullName>Database Marketing</fullName>
            </value>
            <value>
                <fullName>Content</fullName>
            </value>
            <value>
                <fullName>FinTech</fullName>
            </value>
            <value>
                <fullName>FastKey</fullName>
            </value>
            <value>
                <fullName>Data MPD</fullName>
            </value>
            <value>
                <fullName>Discretionary</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Opportunity/recordTypes/B2B.recordType-meta.xml
<RecordType>
    <fullName>B2B</fullName>
    <active>true</active>
    <businessProcess>B2B</businessProcess>
    <description>B2B Opportunity Record</description>
    <label>B2B</label>
</RecordType>

unpackaged/main/default/objects/OpportunityLineItem/fields/Product_Configuration__c.field-meta.xml
<CustomField>
    <fullName>Product_Configuration__c</fullName>
    <label>Product Configuration</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Product2/fields/Product_Category__c.field-meta.xml
<CustomField>
    <fullName>Product_Category__c</fullName>
    <description>Denotes the category of B2C products</description>
    <inlineHelpText>Denotes the category of B2C products</inlineHelpText>
    <label>Product Category</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Subscription</fullName>
            </value>
            <value>
                <fullName>Discretionary</fullName>
            </value>
            <value>
                <fullName>Repost</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/classes/BatchToUpdateProdCatOpp_test.cls
@isTest 
public class BatchToUpdateProdCatOpp_test {
    @testSetup
    public static void DataSetup(){
        Pricebook2 pricebookPGSG = new Pricebook2();
        pricebookPGSG.Name = 'PG SG';
        pricebookPGSG.IsActive = true; 
        pricebookPGSG.CurrencyIsoCode = 'SGD';
        insert pricebookPGSG;
        Account acc = TestDataSetupBasic.createAccount();
        acc.RecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('B2B - Account').getRecordTypeId();
        insert acc;
        Contact con = TestDataSetupBasic.createContact(acc);
        insert con;
        
        Opportunity opp = TestDataSetupBasic.createOpportunity(acc, con);
        opp.RecordTypeId = Schema.SObjectType.Opportunity.getRecordTypeInfosByName().get('B2B').getRecordTypeId();
        opp.Pricebook2Id = pricebookPGSG.Id;
        insert opp;
        csmso__Sales_Order__c so =TestDataSetupSO.createSalesOrder(acc,opp);
        insert so;
        opp.Primary_Sales_Order__c = so.id;
        update Opp;
        Product2 product2Awards = new Product2();
        product2Awards.Name = 'product2Name';
        product2Awards.CurrencyIsoCode = 'SGD';
        //product2sToInsert.add(product2Awards);
        
        insert product2Awards;
       
        Id stdPriceBook = Test.getStandardPricebookId();
        PricebookEntry pricebookEntryStandard = new PricebookEntry();
        pricebookEntryStandard.UnitPrice = 20;
        pricebookEntryStandard.IsActive = true;
        pricebookEntryStandard.CurrencyIsoCode = 'SGD';
        pricebookEntryStandard.Product2Id = product2Awards.Id;
        pricebookEntryStandard.Pricebook2Id = stdPriceBook;
        insert pricebookEntryStandard;
        
        PricebookEntry pricebookEntryPGSG = new PricebookEntry();
        pricebookEntryPGSG.UnitPrice = 40;
        pricebookEntryPGSG.IsActive = true;
        pricebookEntryPGSG.CurrencyIsoCode = 'SGD';
        pricebookEntryPGSG.Product2Id = product2Awards.Id;
        pricebookEntryPGSG.Pricebook2Id = pricebookPGSG.Id;
        insert pricebookEntryPGSG;

        OpportunityLineItem oli = new OpportunityLineItem(Product_Configuration__c='wertyui'+'',Product_category__c='Discretionary',pricebookentryid=pricebookEntryPGSG.id,product2id=product2Awards.id,Opportunityid=Opp.id);
        insert oli;

        
    }
    @isTest
    public static void test1(){
        Database.executeBatch(new BatchToUpdateProdCatOpp());
    }
}