unpackaged/main/default/objects/Opportunity/fields/Submit_to_OMC_Manually__c.field-meta.xml
<CustomField>
    <fullName>Submit_to_OMC_Manually__c</fullName>
    <defaultValue>true</defaultValue>
    <label>Submit to OMC Manually</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Payment__c/Payment__c.object-meta.xml
<CustomObject>
    <label>Payment</label>
    <nameField>
        <displayFormat>PY{0}</displayFormat>
        <label>Payment Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Payments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Payment__c/fields/Opportunity_Record__c.field-meta.xml
<CustomField>
    <fullName>Opportunity_Record__c</fullName>
    <description>Denotes the opportunity record that payment is created for</description>
    <inlineHelpText>Denotes the opportunity record that payment is created for</inlineHelpText>
    <label>Opportunity Record</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Payments</relationshipLabel>
    <relationshipName>Payments</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/Payment__c/fields/Quote_Record__c.field-meta.xml
<CustomField>
    <fullName>Quote_Record__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Denotes the quote record that payment is created for</description>
    <inlineHelpText>Denotes the quote record that payment is created for</inlineHelpText>
    <label>Quote Record</label>
    <referenceTo>Quote</referenceTo>
    <relationshipLabel>Payments</relationshipLabel>
    <relationshipName>Payments</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Quote/fields/Submit_to_OMC_Manually__c.field-meta.xml
<CustomField>
    <fullName>Submit_to_OMC_Manually__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Submit to OMC Manually</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/classes/QuoteOMCAutoApprovalController.cls
/*
 * TestClass : QuoteOMCAutoApprovalController_Test
 */
public without sharing class QuoteOMCAutoApprovalController {
    
    @InvocableMethod
    public static void submitOMCApproval(List<Id> paymentIdsList){
        List<Approval.ProcessSubmitRequest> requests = new List<Approval.ProcessSubmitRequest> ();
        list<Opportunity> toUpdateOpp = new list<Opportunity>();
        list<Quote> toUpdateQuote = new list<Quote>();
        List<Payment__c> paymentList = [SELECT Id, Opportunity_Record__c,Quote_Record__c,Quote_Record__r.OwnerId FROM Payment__c where Id IN : paymentIdsList];
        // Create an approval request for the Opportunity
        for(Payment__c py : paymentList){
            
            Approval.ProcessSubmitRequest req1 = new Approval.ProcessSubmitRequest();
            req1.setComments('Submitting request for approval automatically using Trigger');
            req1.setObjectId(py.Quote_Record__c);
            req1.setSubmitterId(py.Quote_Record__r.OwnerId);
            req1.setProcessDefinitionNameOrId('Quote_B2C_PG_SG_OMC_Approval');
            toUpdateOpp.add(new Opportunity(id = py.Opportunity_Record__c,Submit_to_OMC_Manually__c  = false));
            toUpdateQuote.add(new Quote(id = py.Quote_Record__c,Submit_to_OMC_Manually__c  = false));    
            // Submit the approval request for the Quote
            requests.add(req1);
            
        }
        
        Approval.ProcessResult[] processResults = null;
        try {
            update toUpdateOpp;
            update toUpdateQuote;
            processResults = Approval.process(requests, true);
    	}catch (System.DmlException e) {
        	System.debug('Exception Is ' + e.getMessage());
    	}
        
    }
}