unpackaged/main/default/objects/Quote/fields/Agent_Accepted_Time__c.field-meta.xml
<CustomField>
    <fullName>Agent_Accepted_Time__c</fullName>
    <label>Agent Accepted Time</label>
    <type>DateTime</type>
</CustomField>

unpackaged/main/default/objects/Quote/fields/Country__c.field-meta.xml
<CustomField>
    <fullName>Country__c</fullName>
    <formula>TEXT(Opportunity.Subsidiary__r.Country__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Country</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Quote/fields/Guruland_Link_Created_Date__c.field-meta.xml
<CustomField>
    <fullName>Guruland_Link_Created_Date__c</fullName>
    <label>Guruland Link Created Date</label>
    <type>DateTime</type>
</CustomField>

unpackaged/main/default/objects/Quote/fields/Payment_Next_Reminder_Date__c.field-meta.xml
<CustomField>
    <fullName>Payment_Next_Reminder_Date__c</fullName>
    <description>Stores the date to send the email every 3rd day from payment link created date as per PGAUTO- 5138</description>
    <label>Payment Next Reminder Date</label>
    <type>DateTime</type>
</CustomField>

unpackaged/main/default/objects/Quote/fields/Quote_Type__c.field-meta.xml
<CustomField>
    <fullName>Quote_Type__c</fullName>
    <label>Quote Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>B2C - Standard</fullName>
            </value>
            <value>
                <fullName>B2C - Upgrade</fullName>
            </value>
            <value>
                <fullName>B2C - Renewal</fullName>
            </value>
            <value>
                <fullName>B2C - Conversion</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Quote/fields/SG_Payment_Link_Expiry__c.field-meta.xml
<CustomField>
    <fullName>SG_Payment_Link_Expiry__c</fullName>
    <description>Stores the expiray date for SG renewal quotes as per PGAUTO- 5138</description>
    <label>SG Payment Link Expiry</label>
    <type>DateTime</type>
</CustomField>

unpackaged/main/default/objects/Quote/recordTypes/B2C.recordType-meta.xml
<RecordType>
    <fullName>B2C</fullName>
    <active>true</active>
    <label>B2C</label>
</RecordType>

unpackaged/main/default/classes/SG_RenewalOppty_SendEmailReminder.cls
//TEST CLASS: SG_RenewalOppty_SendEmailReminder_Test
global class SG_RenewalOppty_SendEmailReminder implements Database.Batchable<sObject>,Schedulable {
    public void execute(SchedulableContext sc){  
        DataBase.executeBatch(new SG_RenewalOppty_SendEmailReminder(), 200);  
    }
    
    public Database.QueryLocator start(Database.BatchableContext bC){
        string query='select Id,Payment_Next_Reminder_Date__c,SG_Payment_Link_Expiry__c ,Guruland_Link_Created_Date__c from Quote where Status =\'Pending Online Payment\' and Quote_Type__c=\'B2C - Renewal\' and country__c=\'Singapore\'and Agent_Accepted_Time__c=null and Guruland_Link_Created_Date__c!=null and IsSyncing = true and recordtype.name = \'B2C\' and SG_Payment_Link_Expiry__c >  Today  ';
        return Database.getQueryLocator(query);
    }
    
    public void execute(Database.BatchableContext bC, List<quote> recordList) {
        DateTime dT = System.now(); 
        Date myDate = date.newinstance(dT.year(), dT.month(), dT.day()); // Converts dateTime into Date field
        List<Quote> toUpdateQuote = new List<Quote>();
        for(Quote quo :recordList ){
            if(quo.Payment_Next_Reminder_Date__c == null){
                
                DateTime guruDt = quo.Guruland_Link_Created_Date__c;
                Date guruDtDate = date.newinstance(guruDt.year(), guruDt.month(), guruDt.day());  // Converts dateTime into Date field
                
                if(myDate == guruDtDate.adddays(3)){
                    quo.Payment_Next_Reminder_Date__c  = quo.Guruland_Link_Created_Date__c.adddays(3);  
                }
            }else{
                DateTime reminderDt = quo.Payment_Next_Reminder_Date__c;
                Date reminderDtmyDate = date.newinstance(reminderDt.year(), reminderDt.month(), reminderDt.day());  // Converts dateTime into Date field
                if(myDate == reminderDtmyDate.adddays(3)){
                    //   if(DATEVALUE(System.today()) == DATEVALUE(quo.Payment_Next_Reminder_Date__c.adddays(3))){
                    quo.Payment_Next_Reminder_Date__c=  quo.Payment_Next_Reminder_Date__c.adddays(3);
                }      
            }
            toUpdateQuote.add(quo);
        }
        System.debug(toUpdateQuote);
        if(!toUpdateQuote.isempty()){
            update toUpdateQuote;
        }
    }
    
    public void finish(Database.BatchableContext bC) {
        
    }
}