unpackaged/main/default/objects/No_Triggers__c/No_Triggers__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>Disables and enables triggers per User for triggers using trigger pattern.</description>
    <label>No Triggers</label>
</CustomObject>

unpackaged/main/default/objects/No_Triggers__c/fields/Flag__c.field-meta.xml
<CustomField>
    <fullName>Flag__c</fullName>
    <defaultValue>true</defaultValue>
    <description>Flag indicating triggers on or off for user.</description>
    <inlineHelpText>Flag indicating triggers on or off for user.</inlineHelpText>
    <label>Flag</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Process_Deactivation__c/Process_Deactivation__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>Disables specific process in triggers for specific User.</description>
    <label>Process Deactivation</label>
</CustomObject>

unpackaged/main/default/objects/Process_Deactivation__c/fields/Active__c.field-meta.xml
<CustomField>
    <fullName>Active__c</fullName>
    <defaultValue>true</defaultValue>
    <description>Flag indicating is process execution is enabled</description>
    <inlineHelpText>Flag indicating is process execution is enabled</inlineHelpText>
    <label>Active</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Process_Deactivation__c/fields/Processes__c.field-meta.xml
<CustomField>
    <fullName>Processes__c</fullName>
    <description>Name of the process</description>
    <inlineHelpText>Name of the process</inlineHelpText>
    <label>Processes</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/classes/CS_utl_User.cls
/**
* ─────────────────────────────────────────────────────────────────────────────────────────────────┐
* Utility class to manipulate users
* ──────────────────────────────────────────────────────────────────────────────────────────────────
* @author         Ivan Ravnjak   <ivan.ravnjak@cloudsense.com>
* ──────────────────────────────────────────────────────────────────────────────────────────────────
* @changes
* ─────────────────────────────────────────────────────────────────────────────────────────────────┘
*/
public class CS_utl_User
{
	public static Boolean isDeactivatedForDataMigration = false;
	public static Boolean isTriggerDeactivatedForOffers = false;

    public static String userProfile {
        get {
            if(userProfile == null) {
                userProfile = [SELECT Id, Name FROM Profile WHERE Id = :UserInfo.getProfileId()].Name;
            }

            return userProfile;
        }
        set;
    }

    /*
     * Gets or Sets the master switch for trigger deactivations for the current transaction.
     */
    public static boolean isTriggerDeactivationEnabledForAllTriggers { 
        get {
            if(isTriggerDeactivationEnabledForAllTriggers == null) {
                isTriggerDeactivationEnabledForAllTriggers = false;
            }
            return isTriggerDeactivationEnabledForAllTriggers;
        }
        set;
    }

    /**
     * Checks if the trigger should run for the user
     * @return Boolean
     */
    public static Boolean isTriggerActiveForMe() {
        No_Triggers__c noTriggers = No_Triggers__c.getInstance(UserInfo.getUserId());

        return !isTriggerDeactivationEnabledForAllTriggers && (noTriggers == null || !noTriggers.Flag__c);
    }

    /**
     * Checks if the process is active for the current user
     * @param  process CS_ProcessDefinition
     * @return         Boolean
     */
    public static Boolean isProcessActiveForMe(CS_ProcessDefinition process) {
        Process_Deactivation__c processDeactivation = Process_Deactivation__c.getInstance();

        if(processDeactivation == null || !processDeactivation.Active__c) {
            return true;
        }

        return !(processDeactivation.Active__c && 
                 (processDeactivation.Processes__c.contains(process.name()) ||
                  processDeactivation.Processes__c.equals(CS_ProcessDefinition.ALL.name())));
    }

    /**
     * Disables triggers for the given user
     * @param userId Id
     */
    public static void disableAllTriggers(Id userId) {
        No_Triggers__c noTriggers = No_Triggers__c.getInstance(userId);
        PGTestDataFactory_v2.CreateTriggerExecuteCS('Trigger_OpportunitySplit',true);

        if(noTriggers == null) {
            noTriggers = new No_Triggers__c();
            noTriggers.SetupOwnerId = userId;
            noTriggers.Flag__c = true;
        }
        else {
            noTriggers.Flag__c = true;
        }

        upsert noTriggers;
    }

    /**
     * Enables triggers for the given user
     * @param userId Id
     */
    public static void enableAllTriggers(Id userId) {
        No_Triggers__c noTriggers = No_Triggers__c.getInstance(userId);

        if(noTriggers != null) {
            noTriggers.Flag__c = false;
            upsert noTriggers;
        }     
    }
}