unpackaged/main/default/objects/No_Triggers__c/No_Triggers__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>Disables and enables triggers per User for triggers using trigger pattern.</description>
    <label>No Triggers</label>
</CustomObject>

unpackaged/main/default/objects/No_Triggers__c/fields/Flag__c.field-meta.xml
<CustomField>
    <fullName>Flag__c</fullName>
    <defaultValue>true</defaultValue>
    <description>Flag indicating triggers on or off for user.</description>
    <inlineHelpText>Flag indicating triggers on or off for user.</inlineHelpText>
    <label>Flag</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Process_Deactivation__c/Process_Deactivation__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>Disables specific process in triggers for specific User.</description>
    <label>Process Deactivation</label>
</CustomObject>

unpackaged/main/default/objects/Process_Deactivation__c/fields/Active__c.field-meta.xml
<CustomField>
    <fullName>Active__c</fullName>
    <defaultValue>true</defaultValue>
    <description>Flag indicating is process execution is enabled</description>
    <inlineHelpText>Flag indicating is process execution is enabled</inlineHelpText>
    <label>Active</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Process_Deactivation__c/fields/Processes__c.field-meta.xml
<CustomField>
    <fullName>Processes__c</fullName>
    <description>Name of the process</description>
    <inlineHelpText>Name of the process</inlineHelpText>
    <label>Processes</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/classes/CS_utl_UserTest.cls
/**
* ─────────────────────────────────────────────────────────────────────────────────────────────────┐
* Test class for CS_utl_User
* ──────────────────────────────────────────────────────────────────────────────────────────────────
* @author         Ivan Ravnjak   <ivan.ravnjak@cloudsense.com>
* ──────────────────────────────────────────────────────────────────────────────────────────────────
* @changes
* ─────────────────────────────────────────────────────────────────────────────────────────────────┘
*/
@isTest

private class CS_utl_UserTest {
    /**
     * Test isTriggerActiveForMe method
     */
    @isTest
    public static void test_isTriggerActiveForMe() {
        Test.startTest();

        System.assert(CS_utl_User.isTriggerActiveForMe());

        CS_utl_User.isTriggerDeactivationEnabledForAllTriggers = true;
        System.assert(!CS_utl_User.isTriggerActiveForMe());

        CS_utl_User.isTriggerDeactivationEnabledForAllTriggers = false;
        System.assert(CS_utl_User.isTriggerActiveForMe());

        CS_utl_User.disableAllTriggers(UserInfo.getUserId());
        System.assert(!CS_utl_User.isTriggerActiveForMe());

        CS_utl_User.enableAllTriggers(UserInfo.getUserId());
        System.assert(CS_utl_User.isTriggerActiveForMe());

        Test.stopTest();
    }

    /**
     * Test isProcessActiveForMe method
     */
    @isTest
    public static void test_isProcessActiveForMe() {
        Test.startTest();

        System.assert(CS_utl_User.isProcessActiveForMe(CS_ProcessDefinition.UNIT_TEST_PROCESS));

        Process_Deactivation__c processDeactivation = Process_Deactivation__c.getInstance();

        if(processDeactivation == null) {
            processDeactivation = new Process_Deactivation__c();
            processDeactivation.Active__c = true;
            processDeactivation.Processes__c = CS_ProcessDefinition.UNIT_TEST_PROCESS.name();
            processDeactivation.SetupOwnerId = UserInfo.getUserId();
        }
        else {
        	processDeactivation.Active__c = true;
        	processDeactivation.Processes__c = CS_ProcessDefinition.UNIT_TEST_PROCESS.name();
        }

        upsert processDeactivation;
        System.assert(!CS_utl_User.isProcessActiveForMe(CS_ProcessDefinition.UNIT_TEST_PROCESS));

        Process_Deactivation__c processDeactivationAll = Process_Deactivation__c.getInstance();

        if(processDeactivation == null) {
            processDeactivation = new Process_Deactivation__c();
            processDeactivation.Active__c = true;
            processDeactivation.Processes__c = CS_ProcessDefinition.ALL.name();
            processDeactivation.SetupOwnerId = UserInfo.getUserId();
        }
        else {
        	processDeactivation.Active__c = true;
        	processDeactivation.Processes__c = CS_ProcessDefinition.ALL.name();
        }

        upsert processDeactivation;
        System.assert(!CS_utl_User.isProcessActiveForMe(CS_ProcessDefinition.UNIT_TEST_PROCESS));

        Test.stopTest();
    }

    /**
     * Test enableAllTriggers and disableAllTriggers methods
     */
    @isTest
    public static void test_enableDisableAllTriggers() {
        Id userId = UserInfo.getUserId();
        No_Triggers__c noTriggers;

        Test.startTest();
        CS_utl_User.disableAllTriggers(userId);
        noTriggers = No_Triggers__c.getInstance(userId);
        System.assert(noTriggers.Flag__c);

        CS_utl_User.enableAllTriggers(userId);
        noTriggers = No_Triggers__c.getInstance(userId);
        System.assert(!noTriggers.Flag__c);

        CS_utl_User.disableAllTriggers(userId);
        noTriggers = No_Triggers__c.getInstance(userId);
        System.assert(noTriggers.Flag__c);

        Test.stopTest();
    }
    
   
}